### ISSUE TITLE
Group and Profile Types are not working for the menus.

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1001]
**Describe the bug**

Group and Profile Types are not working for the menus when someone tries to add one of them in his/her menu. Screenshot: https://prnt.sc/svvo14.

**Video**
https://www.loom.com/share/d49898f4e52d47668613b0e618e9522a

**To Reproduce**
1. Create a group type
2. Assign a group to that
3. Navigate to 'Appearance > Menus'
4. Add the group type to the menu.
5. Check the added menu in frontend.

The same procedure for the Profile Types.

**Expected behavior**
Group and Profile Types menu option should show the related groups and profiles.

**Support ticket links**
https://secure.helpscout.net/conversation/1184662008/76148

**Comment by chetansatasiya** [comment]
@imehedidev We don't have this kind of functionality like it will show the member like this. If you have to see the specifice group/profile type then you have to use shortcode and need to add those shortcode in page.

I created a PR #1133  that will remove the option from the Appearance > Menus
