### ISSUE TITLE
unwanted code snippet 

### ISSUE THREAD

**Issue by officelearn** [buddyboss/buddyboss-platform#1002]
**Describe the bug**
When my website visitors visit my website and register as a user, an error message appears above the user form itself. Have tried reinstalling the entire site but it does not help.

**Expected behavior**
unwanted code snippet appears on the front end of my user registration page. Uses Buddyboss theme sender registration page and not third party.
**Screenshots**
![image](https://user-images.githubusercontent.com/54389961/84034102-2c35c300-a99a-11ea-841f-43ad7083ba37.png)

**Comment by eisenwasser** [comment]
@officelearn This is fixed in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-3/
