### ISSUE TITLE
User can send empty messages. Bug with extra spaces

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1004]
**Describe the bug**
User can send empty messages. Can send extra spaces. 

**To Reproduce**
1. Go to messages and try to sent a messages to some user
2. Press a space button (one or several times) and send the message
3. Try to send `"       test             test        "` message (with using a lot of spaces, GitHub don't allow to do it here)
4. See the result
5. Also user can send empty activity feed post
![image](https://user-images.githubusercontent.com/4050715/84066777-e0a60800-a9df-11ea-9ae6-9c923f5ee48d.png)

**Expected behavior**
- Empty messages should not be sent
- Extra spaces should be removed (something like [trim()](https://www.php.net/manual/en/function.trim.php) function in PHP)

**Screenshots / GIF**
![bb-spaces](https://user-images.githubusercontent.com/4050715/84064278-cb2edf00-a9db-11ea-99a9-220dc3f353d0.gif)

---

## Another similar problem with extra spaces:
**To Reproduce**
1. Go to messages and try to sent a messages to some user
2. Try to send some link ("https://google.com " for example) with some spaces in the end

3. You will see extra `&nbsp;` symbol in the end of the link
![image](https://user-images.githubusercontent.com/4050715/84064700-82c3f100-a9dc-11ea-809e-865000d7c372.png)

4. With this symbol link is not working
![image](https://user-images.githubusercontent.com/4050715/84064739-953e2a80-a9dc-11ea-995f-3b673ad4389b.png)

**Expected behavior**
Link should not have `&nbsp;` symbol in the end. 

**GIF:**
![bb-link-bug](https://user-images.githubusercontent.com/4050715/84066112-df281000-a9de-11ea-9a10-e5d6778a34ea.gif)

**Solution:** 
- I think you can use [trim()](https://www.php.net/manual/en/function.trim.php) function before sending a message.
- If the message will be empty - do not send the message.
- link should not have any extra symbols in the end. 

**Notice:** 
All this bugs should be tested in activity feed too. Because user also can publish empty post in activity feed
![bb-activity-posts](https://user-images.githubusercontent.com/4050715/84067291-a8eb9000-a9e0-11ea-997b-d80ef8c63068.gif)

**Configuration:** 
- buddyboss-platform 1.4.1
- buddyboss-theme 1.5.0
- WordPress  5.4.1

**Comment by sourabhmatolia** [comment]
Hello @AiratHalitov 

Issue created above is fixed and released in Buddyboss Platform v1.4.7.

**Find plugin v1.4.7 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-7/

Please update the plugin to see the latest changes.

Thanks

**Comment by AiratHalitov** [comment]
@sourabhmatolia 
Thanks! 
Now it's working good. 

Could you add `target="_blank"` option for external links in messages?
![image](https://user-images.githubusercontent.com/4050715/88846961-cd553300-d1ff-11ea-90e9-c9fc25220d46.png)


How it is working in activity feed:

![image](https://user-images.githubusercontent.com/4050715/88846855-a5fe6600-d1ff-11ea-8e9a-c7261831ac9d.png)

**Comment by sourabhmatolia** [comment]
@AiratHalitov 

Please go ahead and create a separate issue. We will have a look.
Thanks.

**Comment by AiratHalitov** [comment]
#1287
