### ISSUE TITLE
Upload zip-archive of buddyboss-platform into release assets

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1010]
**Is your feature request related to a problem? Please describe.**
There is a problem with fast changing version of platform when you testing buddyboss-platform. 
[Releases](https://github.com/buddyboss/buddyboss-platform/releases) page should be more detailed and more convenient. The problem is that the plugin is located in /src/ folder and you need to get it from there.
I wrote about this earlier in comments and I was told that it will be implemented, but still not done.
![image](https://user-images.githubusercontent.com/4050715/84286559-47e6c800-ab58-11ea-8731-a44964d30e8b.png)

**Describe the solution you'd like**

- Add zip-archive with buddyboss-platform plugin 
- Archive name should be like `buddyboss-platform-vX.X.X.zip` (X.X.X - version)
- Add a changelog into release description
- Add a title like this "vX.X.X"

**Describe alternatives you've considered**
Examples (How it should be):

- https://github.com/WordPress/gutenberg/releases
- https://github.com/woocommerce/woocommerce/releases
- https://github.com/Yoast/wordpress-seo/releases
- https://github.com/Automattic/jetpack/releases

**Comment by eisenwasser** [comment]
Thanks for the reminder

**Comment by eisenwasser** [comment]
@AiratHalitov 

I've gone ahead and done it for every release from 1.3.0 up to the current release.
https://github.com/buddyboss/buddyboss-platform/releases

This will be part of the release process going forward.

**Comment by AiratHalitov** [comment]
@eisenwasser 
Thanks!
Now Releases page looks great! 
And I can receive notifications about new releases.  (without title they didn't work).

**Comment by eisenwasser** [comment]
Awesome!
