### ISSUE TITLE
Commenting a photo to a group activity is not working

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1012]
**Describe the bug**
When you try to comment a photo to group activity it is not showing

**To Reproduce**
1. Go to any groups and make any post
2. Go to sitewide activity
3. Comment to the group activity with an attached image
4. Notice that your comment will be posted but will not include the image you have attached

**Screencast**
https://drive.google.com/file/d/1O9w0JGHmLBE5HvXVWtnM4-8Ice1ZG5XH/view

**Support ticket links**
https://secure.helpscout.net/conversation/1188830051/76866/

**Comment by KartikSuthar** [comment]
@ayron-paul I have checked into my local as well on the demo site but I can not reproduce this issue. 

Can you please check and close the ticket if it's not there?

**Comment by ayron-paul** [comment]
Hi @KartikSuthar, as per checking, this has been addressed on a duplicate card https://github.com/buddyboss/buddyboss-platform/issues/1058. You may close this one, thanks.
