### ISSUE TITLE
Ability To Limit Documents & Photos Maximum Upload File Size

### ISSUE THREAD

**Issue by King-Ding** [buddyboss/buddyboss-platform#1013]
**Is your feature request related to a problem? Please describe.**
It can be a problem if users upload humungous files to your site, slowing it down severely.

**Describe the solution you'd like**
With the new update of Documents (which is fantastic by the way), it would be great if you can add the ability to set a maximum file size for upload. This could be amended by admins in the backend, and the limit also displayed in the frontend upon file upload for users to be aware of.

**Describe alternatives you've considered**
Limiting the upload size via hosting/htaccess, however this limits upload size everyone including admins, so is not a long term feasible solution.

**Comment by AiratHalitov** [comment]
Related: #991

**Comment by eisenwasser** [comment]
@King-Ding 

Thanks for the feedback. This is on our list actually.

1. Give the admin an option for max file size for photos and documents.

2 Limit the amount of photos/docs that can be uploaded per batch. Currently it is hard-coded to 10 documents, but we could give you an option to adjust that.

**Comment by AiratHalitov** [comment]
fixed in v1.4.8
You can close this issue
