### ISSUE TITLE
Discussion topic detail is missing under 'My replies' when viewing someone else's profile. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1015]
**Describe the bug**
For you, the discussion topic is listed along with a link under Profile > Forums section. This tells the viewer what topic the reply is for. In the view on someone else's profile, the discussion topic is not listed. So you have no idea what the reply is talking about. The view from your profile is what we should see on all profile pages 

**To Reproduce**
1. Go to 'Profile > Forums'
2. Click on 'My replies'.
3. You will see https://prnt.sc/sxqqpl
4. Go to any other user's 'Profile > Forums' > My replies. 
5. You will see https://prnt.sc/sxqrc4

**Expected behavior**
Discussion topic detail should show. 

**Screenshots**
https://prnt.sc/sxqqpl
https://prnt.sc/sxqrc4

**Support ticket links**
Ihttps://secure.helpscout.net/conversation/1186501428/76413/

**Jira issue** : [PROD-944]

[PROD-944]: https://buddyboss.atlassian.net/browse/PROD-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sadrul** [comment]
@sourabhmatolia do we need this? Default bbpress has same behavior, for own profile >forums> replies created page https://i.imgur.com/3Qz292F.png and this is for others - https://i.imgur.com/0HHQmLo.png  need your comments on this
