### ISSUE TITLE
Audio System

### ISSUE THREAD

**Issue by ragnabnet** [buddyboss/buddyboss-platform#1017]
Hello buddyboss, i'd like to request a feature for audio play system in comment section. As this covid pandemic spreading, the urgency of online class is really increasing. So, for us as a language teacher, we really need this audio upload feature to be implemented in buddyboss system. Could you make this happen? Thank you.

**Comment by eisenwasser** [comment]
@ragnabnet 

This already exists now. If you enable Documents, you can upload MP3 files.
https://www.youtube.com/watch?v=H_6c0PBGQok

In terms of adding this into default WordPress comments, we are not planning to do that. We are considering an option to convert comments into activity and then all activity functions will be available where currently you see comments. If we do that it will resolve this in comments also.

Thanks!

**Comment by ragnabnet** [comment]
Yes, it's already available but we can't play the audio, and user unable to
download it.

**Comment by ragnabnet** [comment]
Yes, it's already available but we can't play the audio, and user unable to download it.

**Comment by chetansatasiya** [comment]
@ragnabnet send us support ticket will look into the site.

**Comment by ragnabnet** [comment]
Ok Thanks!

**Comment by ragnabnet** [comment]
The support team said that the mp3 files can't be played directly from the frontend, it only can be downloaded by all of the users and play it locally on user's gadget.

But this is really concern us as a teacher that our audio will be spread for all of the users and could be misused by other people.

**Comment by chetansatasiya** [comment]
@ragnabnet Can you paste it your ticket number here?

**Comment by ragnabnet** [comment]
Yes, actually i already asked two times for this in support ticket:
Here's today's ticket: #77522

And here's the ticket number for yesterday for asking the
same question: #77368

Thank you!

**Comment by chetansatasiya** [comment]
@ragnabnet I got your ticket and I replied their it will fix in our upcoming release.

**Comment by ragnabnet** [comment]
Great! Really glad to use buddyboss!

**Comment by eisenwasser** [comment]
@ragnabnet Thanks, it will be resolved in the next update. Monday or Tuesday.
