### ISSUE TITLE
Privacy doesn't work after the first fragment of the URI if we enable the private network. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1018]
**Describe the bug**
Privacy doesn't work after the first fragment of the URI if we enable the private network. If the URL is https://example.com/blog/ it will work if we just mention **_"/blog/"_** in the settings. 

But if the URL is https://example.com/events/event-1/ and if we mention **_"/events/event-1/"_**  in the setting, it doesn't work. 

**To Reproduce**
1. Go to BuddyBoss > Settings page
2. Add a URL with two fragments in the privacy settings
3. See error

**Expected behavior**
It should work regardless of the number of fragments in the URI. 

**Screenshots**
-

**Support ticket links**
- https://secure.helpscout.net/conversation/1188061504/76731?folderId=3701247

**Comment by marienel21** [comment]
The bug is no longer reproducible on the current version. The mentioned URI Fragments is working.
