### ISSUE TITLE
Forums - main discussions index is not showing ones from private forums/groups

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#1020]
**Describe the bug**
Logged in users are seeing on the /forums/ page only discussion topics from public groups/forums. They should see all discussions, even those from private/hidden, as long as that user has permissions to view that content.

**To Reproduce**
1. Join some private/hidden groups with forums
2. Add some replies in discussions
3. Go to /forums/ page
4. You will only see discussions from public ones

**Expected behavior**
You should see all discussions you have access to anywhere else on the site

**Screenshots**

**Support ticket links**
Posted on Youtube by user "Collangettes Mathieu"
Posted on Youtube by user "Le Carnet Digital de Scendre"
https://www.youtube.com/watch?v=fDmWumAWy_c&lc=Ugwwnz4i3tBtxc0EGlx4AaABAg&feature=em-comments

**Comment by KartikSuthar** [comment]
@eisenwasser I have checked and tried to reproduce the issue but can not produce the issue, it seems like working fine.
http://somup.com/cY1U2EQBPL

**Comment by eisenwasser** [comment]
@ankitguptaindia @mohit-buddyboss 

Can you guys please test and try to reproduce? 

We had multiple people post this on Youtube so it has to be real. Unless it was patched already...

Thanks!

**Comment by sumitbuddyboss** [comment]
@eisenwasser 
I have checked and tried to reproduce the issue but can not reproduce the issue, it working fine for me. For the proof please check the below video.

Video:
https://www.loom.com/share/dd1c99c169ae4bbcb7a713478fb590f7

CC @ankitguptaindia
