### ISSUE TITLE
Prevent bbp profile completion widget transients from bloating wp_options with autoloaded data 

### ISSUE THREAD

**Issue by tamara-m** [buddyboss/buddyboss-platform#1021]
**Is your feature request related to a problem? Please describe.**
preparing a db for a large conversion of a forum into BuddyBoss, I noticed the following autoloaded 'yes' data
_transient_bbprofilecompletion3bp_xprofile_profile_completion_widget-2
_transient_bbprofilecompletion15bp_xprofile_profile_completion_widget-2
_transient_bbprofilecompletion55bp_xprofile_profile_completion_widget-2, etc.

![chrome_2020-06-11_19-11-48](https://user-images.githubusercontent.com/9288041/84444153-77103e80-ac17-11ea-9755-41551e92cbbe.jpg)

This can be seriously detrimental for performance if we multiply these times a relatively large amount of users.

Do you need to have these autoloaded every time WordPress loads? Can't they be fetched from the db on demand? 

**Describe the solution you'd like**
I would like the bbprofilecompletion widget transients to have autoloaded set to no
If you could place these in a custom table instead of wp_options, that would be actually a solution.

As is, I'm thinking we may not be able to use this really beautiful profile completion widget because of the toll on performance the autoloaded data will have on this site with a large amount of users.

Thanks in advance for your consideration.

**Comment by eisenwasser** [comment]
@tamara-m Thanks for this feedback, we will look into this.

**Comment by tamara-m** [comment]
#549 would automatically solve this issue too, by setting an expiration to the transient @eisenwasser

**Comment by eisenwasser** [comment]
Thanks, noted

**Comment by eisenwasser** [comment]
@tamara-m This will be fixed in https://github.com/buddyboss/buddyboss-platform/pull/1056
Still in testing.

**Comment by chetansatasiya** [comment]
Closing this as it's fixed in https://github.com/buddyboss/buddyboss-platform/pull/1056

**Comment by sourabhmatolia** [comment]
Hello @tamara-m 

Issue created above is fixed and released in Buddyboss Platform v1.4.7.

**Find plugin v1.4.7 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-7/

Please update the plugin to see the latest changes.

Thanks.
