### ISSUE TITLE
Subscribe To Group Activity Feeds (Email Subscription)

### ISSUE THREAD

**Issue by King-Ding** [buddyboss/buddyboss-platform#1023]
**Describe the solution you'd like**
Just like in BB forums, users can subscribe to particular topics or single forums. It would be great if users had the same ability to subscribe to the **activity feed** of groups

**Describe alternatives you've considered**
There's a plugin for this already, but it's very old and the email formatting isn't nearly as beautiful as buddyboss'. The plugin does work however: https://github.com/boonebgorges/buddypress-group-email-subscription/

**Comment by eisenwasser** [comment]
@King-Ding Thanks for the suggestion

**Comment by TokumeiJG** [comment]
Yes! It would really help user engagement BUT, like the plugin mentioned above, different levels of subscriptions are essential to not annoy users.

**Comment by King-Ding** [comment]
> Yes! It would really help user engagement BUT, like the plugin mentioned above, different levels of subscriptions are essential to not annoy users.

Not necessarily, unless your buddypress site has thousands of participants in the same group? In which case, you probably wouldn't want group subscriptions. This would be useful for smaller groups, or groups in which members can only comment on admin updates (members cannot create their own updates for example) :)

**Comment by TokumeiJG** [comment]
Sorry I guess not "essential", I just wanted to say I like how buddypress-group-email-subscription had different options (no email, daily digest, weekly digest, every email) so everyone could choose what they like.  So, if BuddyBoss implements it, I hope they too provide different options like that.

**Comment by King-Ding** [comment]
> Sorry I guess not "essential", I just wanted to say I like how buddypress-group-email-subscription had different options (no email, daily digest, weekly digest, every email) so everyone could choose what they like. So, if BuddyBoss implements it, I hope they too provide different options like that.

Oh yeah, I totally agree :)

**Comment by marienel21** [comment]
Hi @King-Ding,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
