### ISSUE TITLE
Users able to accept the group invitation on clicking group title. (without clicking on Accept button)

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#1024]
**Describe the bug**
If any user has been invited to private group, then it shows two button ( Accept and Reject ) after clicking on notification. But user is able to accept the group invitation on clicking group title. (without clicking on Accept button) 

**To Reproduce**
1. Go to 'Group single page and send invitation to a user'
2. Then login as invitee user and click on invite notification
3. It will go to a page where there is a group name/link & accept/reject button.
4. If user click on group link, he becomes a member of that group, no need to click on accept button

**Expected behavior**
User should not become a member after click on group link, must have to press accept button

**Screenshots**
In this video, i showed how default wp/bp works and how buddyboss-platform/buddyboss-theme works - https://www.loom.com/share/d05141197761435980500abd17d2afce

**Support ticket links**
n/a

**Comment by eisenwasser** [comment]
@KartikSuthar 

This is high priority bug, we need a fix for a client project.

**Comment by mehulkaklotar** [comment]
@sadrul @eisenwasser This is not a bug. In the case of buddypress, it has home tab or front page of group which is not present in the platform. so in case of buddypress too, if member was invited to the group and member visits the request membership page of group, member will be accepted automatically. https://www.loom.com/share/61607605ced34091916babae2a6c1bcb

**Comment by eisenwasser** [comment]
@sadrul 

We discussed in Scrum, we will work on this. When you go to the Requests tab in the group, if you have a pending invite, we will instead make this screen also look like the pending invite screen on your profile. Meaning it will allow you to accept/reject from the main tab you see on the group.

**Comment by eisenwasser** [comment]
@KartikSuthar This is for you as discussed in scrum

**Comment by sadrul** [comment]
@eisenwasser I got it, that would be great. thank you so much!

**Comment by eisenwasser** [comment]
@sadrul 
This is live now.
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-4/

**Comment by sadrul** [comment]
@eisenwasser Great news! Thank you so much! working perfectly :)
