### ISSUE TITLE
Uploaded documents cannot be downloaded when the Rank Math SEO plugin is activated.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1028]
**Describe the bug**
Uploaded documents cannot be downloaded when the Rank Math SEO plugin is activated.

* Affects all locations where you can download files (activity feed, profile feed, group feed, discussion forums, private messages)
* The "Copy Download Link" function is also affected, and even when pasted on a new browser tab, it will redirect to the site's homepage.

**To Reproduce**
1. Activate the 'Rank Math SEO' plugin. 
2. Try downloading a document. 

**Support ticket links**
https://secure.helpscout.net/conversation/1192744904/77512?folderId=3701249

**Comment by AiratHalitov** [comment]
Related: #1031
