### ISSUE TITLE
Document download option is not working when Yoast is activated

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1031]
**Describe the bug**

The document download option is not working when Yoast is activated. The same for the RankMath plugin.

**To Reproduce**

1. Install and activate the Yoast/RankMath
2. Upload a file.
3. And try to download that.

**Expected behavior**

Download should work.

**Video**

https://www.loom.com/share/05c0f5e4513441d7894e1a68a714c3cf

**Support ticket links**

https://secure.helpscout.net/conversation/1188703587/76841

**Comment by AiratHalitov** [comment]
The same issue was on my test site. 
https://github.com/buddyboss/buddyboss-platform/issues/987#issuecomment-640288019

**Comment by AiratHalitov** [comment]
Related: #1028

**Comment by imehedidev** [comment]
Similar issue with the **SEOPress** plugin. It seems the download functionality has conflicts with SEO plugins.

**Comment by eisenwasser** [comment]
@imehedidev @AiratHalitov 

These issues will be resolved in today's upcoming release.
