### ISSUE TITLE
Preview Links from youtube and vimeo not working on Activity feed on mobile. 

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1032]
**Describe the bug**
Preview Links from youtube and vimeo not working on mobile. You need to enter a space in order preview links to be enabled

**To Reproduce**
1. Enable Preview Links in BuddyBoss > Settings
2. On actual mobile device, paste any link from youtube or vimeo in the Activity feed and hit post
3. Try to paste the same link again but enter a space after pasting the link and hit post

**Expected behavior**
After pasting the links, preview links should load instantaneously

**Screenshots**
https://drive.google.com/open?id=11-JtrVubUV4amBmmbdnvZmEm4kICq26U

**Support ticket links**
https://secure.helpscout.net/conversation/1189818521/77050

**Comment by marienel21** [comment]
Bug nonexistent on the latest version. Tested preview links in mobile.
