### ISSUE TITLE
Problem with /members links on subsites in WP network

### ISSUE THREAD

**Issue by robheymann** [buddyboss/buddyboss-platform#1037]
Hi,

Struggling to get any real support after purchasing the buddyboss theme and associated plugins.

On sub network sites, the members related links that are available via the profile menu all access pages on the root (main) site. The problem with this is that the theme then changes to what is on the root url, as well as our usecase is that users who logged in via a subsite, are restricted to that subsite, and now with a redirect to the root site for all /members pages, our custom security will prevent this.

2nd issue is the "buddypanel" menu section does not appear on the Menus page for subsites. All works correctly for the main site, but no section is visible for the subsites.

Your assistance would really be helpful, I urgently need to move on with this, or go another route.

**Comment by eisenwasser** [comment]
@robheymann thanks, noted. Can you please add your support ticket IDs so we can follow up there as well, if we have questions related to your specific site.

@KartikSuthar Can you follow up and look into this one?

**Comment by KartikSuthar** [comment]
@robheymann Can you please share the support ticket IDs?

**Comment by bb-yudhisthir** [comment]
Its been responded in the following HS ticket https://secure.helpscout.net/conversation/1191225984/77256/ and closed.
Closing this GitHub issue

**Comment by Pagan-Idel** [comment]
Are BuddyBoss customers expected to pay for HS access to view the results of HS ticket https://secure.helpscout.net/conversation/1191225984/77256/ ?
