### ISSUE TITLE
BP Group Documents plugin conflict

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#1046]
**Describe the bug**
Some of customers are using the `BP Group Documents` plugin for the group documents. Now we have added our own Group Documents so now both are conflicting with eachother.

**To Reproduce**
1. Install BP Group Documents plugin and activate it
2. Disable the BB documents from the settings https://prnt.sc/t1hslp
3. If you go into the Documents tab in group it will load the BB Documents insted of BP Group Documents plugin.

**Expected behavior**
If someone added and activated the BP Group Documents plugin and deactivated the BB Documents then it should work based on the BP Group Documents plugin.

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by eisenwasser** [comment]
@chetansatasiya 

What is the support ticket for this one?

**Comment by edsvcs** [comment]
This looks like an issue one of my clients is dealing with right now. We are running the latest versions of BB Platform and BB Theme but BB Docs still takes over the BP Group Documents display, effectively preventing access to the hundreds of documents already live on the system. How can we make BB play nice like it did before v1.4 when this broke?

**Comment by chetansatasiya** [comment]
> This looks like an issue one of my clients is dealing with right now. We are running the latest versions of BB Platform and BB Theme but BB Docs still takes over the BP Group Documents display, effectively preventing access to the hundreds of documents already live on the system. How can we make BB play nice like it did before v1.4 when this broke?

@edsvcs you can disable our platform docs completly https://prnt.sc/ucr42g and you can run the BP Group Documents

**Comment by edsvcs** [comment]
@chetansatasiya Unfortunately that's not the case... We opened a ticket with BuddyBoss support and they confirmed that unchecking the boxes on that screen does not disable your docs feature or resolve the conflict... Any other ideas? Alternately, has anyone written a script to migrate from BP Group Documents to BB Docs?
