### ISSUE TITLE
Cannot translate "By creating an account you are agreeing to the Terms of Service and Privacy Policy."

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1059]
**Describe the bug**
Cannot translate "By creating an account you are agreeing to the Terms of Service and Privacy Policy." when using other language files.

**To Reproduce**
1. Switch to another site language with prebuilt translation such as German/French/Hungarian.
2. Using Loco Translate, in Plugins > BuddyBoss Platform, translate the "By creating an account you are agreeing to the %s and %s." string.
3. Go to the registration page and notice it will not be translated.

**Screenshots**
![reg](https://user-images.githubusercontent.com/58522498/85165781-e8479580-b298-11ea-812c-1c2fa111583a.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1198489486/78419

**Comment by chetansatasiya** [comment]
@ayron-paul it already translatable and working fine witout any issues. see for more details https://www.loom.com/share/2f3e436e307949c7a0a725c769b44581

**Comment by ayron-paul** [comment]
Hi @chetansatasiya, I am still able to reproduce this with the latest version, please follow the steps above, it works for English but not for other languages, try to switch the Site Language to Deutsch.

Please see: https://drive.google.com/file/d/1LMLZyrrlz96Z5teJTaWIJcAhwuTQ3sYC/view
