### ISSUE TITLE
Cannot rename documents with non-English characters

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1060]
**Describe the bug**
Only English characters are being accepted for renaming a document.

**To Reproduce**
1. Go to documents and upload any file.
2. Try to rename it using non-English characters (such as Arabic, Chinese, Japanese, etc.)

**Screenshots**
![non-english](https://user-images.githubusercontent.com/58522498/85187167-3e83fb00-b2d0-11ea-91a9-311f538f544a.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1199598930/78596

**Comment by amincdev** [comment]
This issue has been fixed here: https://github.com/buddyboss/buddyboss-platform/issues/1161

**Comment by amincdev** [comment]
@ayron-paul Please update the customer.
