### ISSUE TITLE
User Ability/ Feature Restriction Based on Level

### ISSUE THREAD

**Issue by ragnabnet** [buddyboss/buddyboss-platform#1061]
**Is your feature request related to a problem? Please describe.**
We'd like buddyboss to add a new feature to restrict user based on their contribution and level. (similar to gamification but this also enable the restriction for feature)

**Describe the solution you'd like**
I'll just copy from what discourse.org do to their forum system.

Trust Level 0 — New
By default, all new users start out at trust level 0, meaning trust has yet to be earned. These are visitors who just created an account, and are still learning the community norms and the way your community works. New users’ abilities are restricted for safety – both theirs and yours.

(We also want to hide any “advanced” functionality from new users to make the UI less confusing for them as they gain more experience.)

Users at trust level 0 cannot …

Send personal messages to other users
“Reply as new topic” via Link button (UI removed)
Flag posts
Post more than 1 image
Post any attachments
Post more than 2 hyperlinks in a post
Have actual links in the ‘about me’ field of their profile (will be silently and temporarily converted to plain text)
Mention more than 2 users in a post
Post more than 3 topics
Post more than 10 replies
Edit their own posts after more than 24 hours
Admins can change these limitations by searching for newuser and first_day in site settings.

**Trust Level 1 — Basic**
At Discourse, we believe reading is the most fundamental and healthy action in any community. If a new user is willing to spend a little time reading, they will quickly be promoted to the first trust level.

Get to trust level 1 by…

Entering at least 5 topics
Reading at least 30 posts
Spend a total of 10 minutes reading posts
Users at trust level 1 can…

Use all core Discourse functions; all new user restrictions are removed
Send PMs
Upload images and attachments if enabled
Edit wiki posts
Flag posts
Mute other users
Admins can change these thresholds by searching for tl1 in site settings.

**Trust Level 2 — Member**
Members keep coming back to your community over a series of weeks; they have not only read, but actively participated long and consistently enough to be trusted with full citizenship.

Get to trust level 2 by…

Visiting at least 15 days, not sequentially
Casting at least 1 like
Receiving at least 1 like
Replying to at least 3 different topics
Entering at least 20 topics
Reading at least 100 posts
Spend a total of 60 minutes reading posts
Users at trust level 2 can…

Use the “Invite others to this topic” button for one-click onboarding of new users to participate in topics
Invite outside users to PMs making a group PM
Daily like limit increased by 1.5×
Ignore other users
Edit their own posts for up to 30 days after posting
Admins can change these thresholds by searching for tl2 in site settings.

**Trust Level 3 — Regular**
Regulars are the backbone of your community, the most active readers and reliable contributors over a period of months, even years. Because they’re always around, they can be further trusted to help tidy up and organize the community.

To get to trust level 3, in the last 100 days…

Must have visited at least 50% of days
Must have replied to at least 10 different non-PM topics
Of topics created in the last 100 days, must have viewed 25% (capped at 500)
Of posts created in the last 100 days, must have read 25% (capped at 20k)
Must have received 20 likes, and given 30 likes.*
Must not have received more than 5 spam or offensive flags (with unique posts and unique users for each, confirmed by a moderator)
Must not have been suspended or silenced
* These likes must be across a minimum number of different users (1/5 the number), across a minimum number of different days (1/4 the number). Likes cannot be from PMs.

All of the above criteria must be true to achieve trust level 3. Furthermore, unlike other trust levels, you can lose trust level 3 status. If you dip below these requirements in the last 100 days, you will be demoted back to Member. However, in order to avoid constant promotion/demotion situations, there is a 2-week grace period immediately after gaining Trust Level 3 during which you will not be demoted.

Users at trust level 3 can…

Recategorize and rename topics
Access a secure category only visible to users at trust level 3 and higher
Have all their links followed (we remove automatic nofollow)
TL3 spam flags cast on TL0 user posts immediately hide the post
TL3 flags cast on TL0 user posts in sufficient diversity will auto-silence the user and hide all their posts
Make their own posts wiki (that is, editable by any TL1+ users)
Daily like limit increased by 2×
Admins can change these thresholds by searching for TL3 in site settings.

**Trust Level 4 — Leader**
Leaders are regulars who have been around forever and seen everything. They set a positive example for the community through their actions and their posts. If you need advice, these are the folks you turn to first, and they’ve earned the highest level of community trust, such that they are almost moderators within the community already.

Get to trust level 4 by…

Manual promotion by staff only
(Possibly via a to-be-developed election system in the future)
Users at trust level 4 can…

Edit all posts
Pin/unpin topic
Close topics
Archive topics
Make topics unlisted
Split and merge topics
Reset topic bump date
Daily like limit increased by 3×
Any TL4 flag cast on any post immediately takes effect and hides the target post
We believe this trust system has been a success so far, as it leads to stronger, more sustainable communities by carefully empowering members, regulars, and leaders to curate and lead their own communities. But like everything else in Discourse, the trust system is evolving over time as we gain more experience with more communities. We’ll continue to update this post with any changes.

**Describe alternatives you've considered**
Similar to what Discourse.org can do, in terms of user ability restriction.

I hope this feature can be real someday. Thank you!

**Comment by marienel21** [comment]
Hi @ragnabnet,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
