### ISSUE TITLE
Profile > View error when BadgeOS is activated

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1062]
**Describe the bug**
Profile > View is prompting an error when BadgeOS is activated with BuddyBoss Platform.
Basically, all pages with /members slug have the error.

**To Reproduce**
1. Install and activate BadgeOS with BuddyBoss Platform
2. On Frontend, click Profile > View or any pages that has /members slug
3. See error

**Expected behavior**
page is showing Error Notice: Trying to get property 'user_email' of non-object in /www/wp-content/plugins/badgeos/includes/open_badge/class-open-badge.php on line 498

**Screenshots**
![image](https://user-images.githubusercontent.com/58522224/85210767-53ff3080-b375-11ea-93eb-5fce785d49b5.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1199465056/78574

**Comment by buddy4kp** [comment]
Hello @emmanoctaviano 
Yes, When I was checking earlier, I was facing the same issue that you have described above. But now at the latest code of platform, I can not reproduce this issue. So please check once again with the latest code and let us know if you are still facing the same issue. Below is the video recording of working the above issue.
https://www.loom.com/share/f851e56b1b564ed5b6e5463257191171
Thanks
+ @chetansatasiya

**Comment by sourabhmatolia** [comment]
@buddy4kp 

I can replicate this issue when I am on DEV branch here:
https://prnt.sc/trtm72 (Enable debug in wp-config.php)

When I deactivate Buddyboss Platform then Notice is gone.
Please have a look. Thanks.

**Comment by manishpatolia** [comment]
@sourabhmatolia @buddy4kp 

That JSON data display issue is with the BadgeOS plugin.
We need to configure pages in the BadgeOS and that the JSON data display issue will be solved.
Step:
1) BadgeOS 
2)Click on OB Integration
3) configure/create missing open badge pages.
https://prnt.sc/try0es

**Comment by buddy4kp** [comment]
Thank you @manishpatolia 
Yes, I have already created this configure pages in the BadgeOS that's why I can not reproduce this issue in my local.

@sourabhmatolia  Please check this once and let us know your feedback. Thanks

**Comment by chetansatasiya** [comment]
@sourabhmatolia @manishpatolia @buddy4kp @emmanoctaviano 

You guys need to set the BadgeOs settings page see here https://prnt.sc/tsza2r and it will fix the issue.

I am closing this issue as it's external issue and I think this will be handled in BadgeOs plugin.

Let me know if anyone have any suggestion on this.
