### ISSUE TITLE
Group Fields + Advanced Group Search

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#1063]
**Is your feature request related to a problem? Please describe.**
Customers need the ability to customize the fields in groups. Currently you can only add Group Title and Description. They would prefer full customizability for group fields just like profile fields. And the ability to search groups by field, and to set fields only for specific group types.

**Describe the solution you'd like**
Video Explanation 1 - https://www.loom.com/share/f79c57cde1d34556827656dcc10f35c5
Video Explanation 2 - https://www.loom.com/share/4601537b6cfb4f8eb764bd932b00cc90

- Group Fields, just like profile fields
- Advanced Group Search form
- New "About" tab on group for displaying fields
- Group fields can be set per group type

**Describe alternatives you've considered**
Some customers use https://wordpress.org/plugins/buddypress-groups-extras/
Not a great solution.

**Support ticket links**
None yet

**Jira issue** : [PROD-943]

[PROD-943]: https://buddyboss.atlassian.net/browse/PROD-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by eisenwasser** [comment]
We will work on this later...

**Comment by tonymeltone** [comment]
I like this.

**Comment by fabiomail** [comment]
This is a fantastic feature improvement for Groups. Any estimation on when it will be released?

**Comment by eisenwasser** [comment]
@fabiomail No estimation. This is a future-planned project and won't be worked on for a while.

**Comment by eisenwasser** [comment]
@MTN-Studio 

Adding custom fields into groups is not coming soon, so you would need to do this custom.

If you are using BuddyBoss Theme, go into /buddyboss-theme/buddypress/groups/single/group-header.php
You can edit that template file to add content into the group header. And/or use the hooks in there.

Also look into /buddyboss-theme/buddypress/groups/single/parts/header-item-actions.php

**Comment by MTN-Studio** [comment]
@eisenwasser Thanks so much for pointing me in the right place Michael. That was sort of the direction we were heading into next. We've been testing the viability of BB for my client for the past week and they're really excited so it's definitely something that I'll be working on. If we do come up with a way of managing it, I'll get it written up somewhere to share.
