### ISSUE TITLE
bp_document_get('activity_id')=>id of new created activity for doc)

### ISSUE THREAD

**Issue by Obeeone-tech** [buddyboss/buddyboss-platform#1067]
I need to get the array of documents filtered by the activity_id i get with add_action bp_activity_after_save ... But the newly created document has activity_id = 0 
array (
  'documents' => 
  array (
    0 => 
    (object) array(
       'id' => 297,
       'blog_id' => 1,
       'attachment_id' => 3156,
       'user_id' => 1,
       'title' => 'Documents',
       'folder_id' => 0,
       'group_id' => 6,
       'activity_id' => 0,
       'privacy' => 'grouponly',
       'menu_order' => 0,
       'date_created' => '2020-06-21 19:21:54',
       'date_modified' => '2020-06-21 19:21:54',
       'parent' => 0,
       'attachment_data' => 
      array (
        'full' => '',
        'thumb' => '',
        'activity_thumb' => '',
        'meta' => '',
      ),
       'group_name' => 'Cinema Lovers',
       'visibility' => 'Public',
       'user_email' => 'xxx.xxx@xxx.be',
       'user_nicename' => 'xxx-xxx',
       'user_login' => 'xxx.xxx@xxx.be',
       'display_name' => 'woadmin',
    ),
  ),
  'total' => 1,
  'has_more_items' => false,
)
And i don't understand why ? Can you help me ?

**Comment by mehulkaklotar** [comment]
@Obeeone-tech You can get document ids by using activity meta like this:

```bp_activity_get_meta( $activity_id, 'bp_document_ids', true ); ```

It will return comma separated ids of documents.
