### ISSUE TITLE
Issues with RTL

### ISSUE THREAD

**Issue by shashank-buddyboss** [buddyboss/buddyboss-platform#1069]
**Describe the bug**
When user switch to RTL language there are few alignment issues with Text and Icons.

**To Reproduce**
1. Switch to RTL Language and check the below screenshots.

**Expected behavior**
RTL language website should not create any text and icon alignment issue.

**Screenshots**
- https://ibb.co/Lhr986Z
- https://ibb.co/kKf8y1n
- https://ibb.co/RDZP0qQ
- https://ibb.co/SrrnHTc
- https://ibb.co/hMdjmzM
- https://ibb.co/VHPqwZ0
- https://ibb.co/8rmskv0
- https://ibb.co/fSSJG3n
- https://ibb.co/cYFG3Mf
- https://ibb.co/d5TyTZj
- https://ibb.co/BnX267y

**Support ticket links**
https://secure.helpscout.net/conversation/1200394140/78710?folderId=3827369

**Jira issue** : [PROD-941]

[PROD-941]: https://buddyboss.atlassian.net/browse/PROD-941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sagarjadhav** [comment]
@ankitguptaindia Can you please test and see if issues occurs?
I can't reproduce most of the issues mentioned above.

**Comment by Dadparvar** [comment]
> @ankitguptaindia Can you please test and see if issues occurs?
> I can't reproduce most of the issues mentioned above.

Except the last Screenshot, I can reproduce all the issues in 2 of my Persian (RTL) websites.
