### ISSUE TITLE
Profile Search > Distance: missing icon

### ISSUE THREAD

**Issue by shanebp** [buddyboss/buddyboss-platform#1073]
**Describe the bug**
The _locator.png_ is called from the wrong dir and results on a 404.

**To Reproduce**

1. Install Version 4.1 of the [BP xProfile Location](https://wordpress.org/plugins/bp-xprofile-location/) plugin
2. In Platform > Profile Search, add a Location field and set _search mode_ to _distance_
3. Go to the members directory
4. Note the missing icon in the Profile Search interface

**Expected behavior**
A pull request for this simple fix has been submitted.

**Comment by eisenwasser** [comment]
@shanebp  

This is live now: https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-4/
