### ISSUE TITLE
Sharing Instagram post on activity page throws an error. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1078]
**Describe the bug**
Sharing an Instagram post on the activity page throws an error. I could replicate the issue on our demo site. 

**To Reproduce**
1. Go to activity page
2. Share the URL of an Instagram post
3. See error

**Expected behavior**
It should work without issues. 

**Screenshots**
- https://i.imgur.com/8lRhPbH.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1200460489/78715?folderId=3701247

**Comment by archanabb** [comment]
User's comment:
Wordfence security plugin does not allow other users from different IPs to post the IG link. A popup to whitelist the URL only opens up for the admins and hence, the subscribers are not able to post IG URLs.

**Comment by asaquzzamanbb** [comment]
Due to Facebook’s decision to close the oEmbed end point for embedding Instagram links.
So it's not the BuddyBoss platform issue.
More details check this link https://wordpress.org/support/article/instagram-embed/
