### ISSUE TITLE
Option to hide all sub-groups from the main Groups directory

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#1079]
**Is your feature request related to a problem? Please describe.**
Users have asked if we can hide all sub-groups from the main groups directory. So you would only see parent groups (and standalone groups) in the groups directory.

"In your example using universities and their departments, ideally the groups page would only show the universities, and the user would click a particular university to pull up their departments. As it is, the groups page shows all the universities AND ALL the departments, making the page a complete and utter mess.  Do you have any plans or recommendations to fix this? Thanks."

**Describe the solution you'd like**
At BuddyBoss > Settings > Groups, in the "Group Hierarchies" metabox.
We can add an option to "Hide subgroups from the main Groups Directory"

**Support ticket links**
Requested on Youtube by user "Jas For Portland"
https://youtu.be/94LJT_trRls

**Comment by ZiadJ** [comment]
I started distancing myself from Buddyboss because of that but will gladly reconsider if this can be fixed in reasonable time.

**Comment by eisenwasser** [comment]
@ZiadJ 

Thanks for the feedback. It's on our list and will be added.

**Comment by zachkinsey** [comment]
Can't wait for it to be added! 

The only question is, when?

**Comment by eisenwasser** [comment]
We will prioritize it for this month, thanks

**Comment by ZiadJ** [comment]
> 
> 
> We will prioritize it for this month, thanks

It's been quite a while already and I'm wondering if the feature will be released anytime soon

**Comment by chetansatasiya** [comment]
@ZiadJ It's merged in next release branch so it will be in next release for sure.

**Comment by sourabhmatolia** [comment]
@ZiadJ  @zachkinsey 


Issue created above is released in Buddyboss Platform v1.5.1.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-1/

Please update the plugin to see the latest changes.

Thank you.
