### ISSUE TITLE
Repeater fields - if you add too many at once it will duplicate the fields in the admin

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#1082]
**Describe the bug**
"It is an issue where a regular user adds a basic repeater field (one text field) from the front end enough times (like 10 times) and it actually duplicates those fields inside the admin panel. I was able to replicate it on your demo."

**To Reproduce**
1. Create a repeater field
2. In your profile, add a basic repeater field (one text field) from the front end enough times (like 10 times) 
3. Save your profile
4. View the field group in the admin

**Expected behavior**
It should not create any extra fields in the admin

**Support ticket links**
Posted in Youtube by user "Anna DiTommaso"
https://www.youtube.com/watch?v=ofIf0VTQxok&lc=Ugz6p7u-ShTD1GaSfl94AaABAg&feature=em-comments

**Comment by bb-yudhisthir** [comment]
another ticket with duplicate repeater fields in frontend as well as backend https://secure.helpscout.net/conversation/1478103200/135311
