### ISSUE TITLE
BuddyPress Featured Members by BuddyDev, widget follow button not working

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1087]
**Describe the bug**
BuddyPress Featured Members plugin by BuddyDev follow button not working on widget

**To Reproduce**
1. Install BuddyPress Featured Members by BuddyDev
2. Go to widgets, add BuddyPress Featured Members on a BB Page (Activity page for example)
3. On frontend, go to any users profile and click Set Featured button 
4. Check Activity page

**Expected behavior**
Follow button Activity page widget must work

**Screenshots**
![image](https://user-images.githubusercontent.com/58522224/85769726-d9575c00-b74c-11ea-8e83-73232b616e90.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1204466958/79599

**Comment by bb-yudhisthir** [comment]
same issue https://secure.helpscout.net/conversation/1482313839/136061

**Comment by marienel21** [comment]
The 'feature request' widget shows no 'follow' button on the current version. Member's name may be aligned to center to improve design. 
![image](https://user-images.githubusercontent.com/77659570/125330784-c1637200-e379-11eb-977c-9c8b228dfee9.png)
