### ISSUE TITLE
Social Groups Widget Issue

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1095]
**Describe the bug**

The social group widget is displaying hidden groups for users with Administrator-level privileges. The widget does not appear to display hidden groups even for members of that group if they are not sited, administrators.

**To Reproduce**
https://www.loom.com/share/ade0d9ec624245838e5849f7b4f89db3

**Expected behavior**
Hidden Groups should appear for all group members.

**Support ticket links**
https://secure.helpscout.net/conversation/1202407832/79133

**Comment by marienel21** [comment]
Bug can't be replicated in the latest version. Members of the Hidden Group can now see the hidden group listed in the Social Group widget.
