### ISSUE TITLE
URL previews are not generated for some websites on activity page. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1098]
**Describe the bug**
A user is trying to post website URLs in the activities, some of them are porn websites. And the preview is not generated. 

I tested this on the user's site, on our demo and on my local and I could replicate the issue. I used the following two URLs shared by the user. 
- https://xhamster.com/videos/corriendo-desnudas-bajo-el-sol-5851249
- http://www.bodycontact.com/

User video - https://screenrec.com/share/CveplTSWd7

I had confirmed this with Chetan and he mentioned that there is no restriction added for porn sites. 

**To Reproduce**
1. Go to the activity page
2. Share the URLs mentioned above
3. See error

**Expected behavior**
The preview should be generated for all the URLs if there is no restriction added for porn sites. 

**Screenshots**
- https://www.loom.com/share/f913ce7ef0f94f50a2c0ab5f2f2eac38

**Support ticket links**
- https://secure.helpscout.net/conversation/1201267672/78892/
- https://secure.helpscout.net/conversation/1207629972/80336
- https://secure.helpscout.net/conversation/1273939645/97255?folderId=3955985

**Jira issue** : [PROD-940]

[PROD-940]: https://buddyboss.atlassian.net/browse/PROD-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rcimedia** [comment]
I am running into the same issue ... (just not with porn sites) ... it happens with all articles on medium.com 
See my experience .. https://screenrec.com/share/CveplTSWd7

or Try Link Preview on BuddyBoss Demo this link:
https://elemental.medium.com/a-supercomputer-analyzed-covid-19-and-an-interesting-new-theory-has-emerged-31cb8eba9d63

It appears BuddyBoss Link preview seems not to play well with other sites like medium.com 
it may be due to protection with cloudflare.com .. even though Facebook and other link previews work just fine.

ETA .. It appears the free WP Link Preview plugin found a way to fix this.  You might want to download the plugin to see what they did.
https://wordpress.org/support/topic/preview-not-working-with-medium-https/

**Comment by sourabhmatolia** [comment]
@rcimedia 

Issue created above is released in BuddyBoss Platform v1.5.2

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-2/

Please update the plugin to see the latest changes.

Thank you.

**Comment by bb-yudhisthir** [comment]
Embed preview issue when posting the link by some third party URL by members like
https://mjbizdaily.com/doj-official-reiterates-stance-against-marijuana-firms-in-280e-fight/
Please check the preview sows “Please Wait: Cloudflare” here, but the preview is working on other platforms like facebook, even this google sheet https://prnt.sc/13juwr3
Replicated at demo and dev server, is it the issue at our end or at the host end of this URL
https://secure.helpscout.net/conversation/1525490809/144452

**Comment by sadrul** [comment]
@bb-yudhisthir This site https://mjbizdaily.com/doj-official-reiterates-stance-against-marijuana-firms-in-280e-fight/ using special protection from cloudflare. It works fine on FB, Twitter, Linkedin. Looks like they provided special provision for these big giants. But when we check Preview Generator or Online Preview then it fails. We can't fix this from our end, they need to reduce the protection from their end.

**Comment by surajkrsingh** [comment]
@sadrul 
We have one more customer issue related to the URL preview where some URLs are not working on the platform but it is working fine with other online tools and social media. 
The issue with URL - https://rivian.com/newsroom/article/rivian-announces-confidential-submission-of-draft-registration-statement

See this - https://tinyurl.com/yznxwb86
https://secure.helpscout.net/conversation/1614731876/161161?folderId=3709082

**Comment by sadrul** [comment]
@surajkrsingh This is something that might occur due to AWS Web Application Firewall (AWS WAF) rules associated with the CloudFront distribution and possibly can be resolved by tweaking settings there  https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-error-request-blocked/
