### ISSUE TITLE
USER SPECIFIC ISSUE: WordPress default Welcome email translation is not working when the platform plugin is active. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1099]
**Describe the bug**
WordPress default Welcome email translation is not working when the platform plugin is active. 

It works fine with the default setup WP theme and platform plugin deactivated. But when we activate the platform plugin, the email is being received in English. 

**To Reproduce**
1. Translate the WordPress default welcome email
2. register yourself 
3. check the email

**Expected behavior**
The translations should work without issue

**Screenshots**
https://i.imgur.com/XN4kmTB.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1194915559/77897/

**Comment by ngolwalkar** [comment]
Admin will have to translate the email template content manually. There is no issue with the code. So closing this issue.

**Comment by ngolwalkar** [comment]
Admin will have to translate the email template content manually. There is no issue with the code. So closing this PR.
