### ISSUE TITLE
Two issues are experienced when displaying the forum using the shortcode in LearnDash course lesson. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1101]
**Describe the bug**
Issues is experienced when displaying the forum using the shortcode in the LearnDash course lesson. I used the following shortcode **_`[bbp-single-topic id=37913]`_** in the course lesson description to display the discussions. 

**Issue 1** 
CSS issues, fixed in theme PR and merged already...

**Issue 2** 
For **_subscribers_**(students), the discussions are not displayed. It is displayed as a blank page instead. Please refer to the screenshot to know more. 

**To Reproduce**
1. Go to LearnDash > Lesson > Edit > Add the shortcode
2. Visit the lesson on the front end as an admin
3. Visit the lesson on the front end as a subscriber(student)

**Expected behavior**
The shortcode should work without any issue. 

**Screenshots**
- https://i.imgur.com/JktlhuI.jpg : admin
- https://i.imgur.com/uv7y0a9.jpg : student

**Support ticket links**
- https://secure.helpscout.net/conversation/1202742859/79225/

**Comment by annrra** [comment]
@archanabb JFI - I am copying this issue in buddyboss-theme project since buttons styling should be applied there - https://github.com/buddyboss/buddyboss-theme/issues/806

**Comment by annrra** [comment]
Issue #1 is fixed in this PR - https://github.com/buddyboss/buddyboss-theme/pull/807
@chetansatasiya 
Please take a look at issue #2 as per this additional info - https://github.com/buddyboss/buddyboss-theme/pull/807#issuecomment-652892184

**Comment by eisenwasser** [comment]
@chetansatasiya 

The core issue is that we are displaying the discussion form to users who do not have access to view that discussion. So then they see reply/subscribe buttons and blank content. They should not see anything. Instead they can get a notice "You do not have access to view this discussion." We need to test other forum shortcodes for similar issue.
