### ISSUE TITLE
Better UX to unhide a hidden message conversation

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1109]
**Describe the bug**
There no visual option to unhide a hidden message conversation. Users need to unhide by searching for the conversation and clicking it. A user wouldn't know that they can search for hidden conversations. 

Also, in a case when a user hides a message and cannot remember who she or he had a message with about a certain topic, it would be easy for the user to select an option to view hidden messages, manually search through and locate the message, and unhide it if she or he wishes to reply to the individual or multiple member message.

**To Reproduce**
1. Go to 'Inbox'
2. Click on 'Hide Conversation'

**Expected behavior**
You may want to consider a solution to give users access to a list of their hidden conversations. And they can unhide a conversation from there.

**Screenshots**
https://imgur.com/a/oInv10z

**Support ticket links**
https://secure.helpscout.net/conversation/1204879730/79726

**Jira issue** : [PROD-939]

[PROD-939]: https://buddyboss.atlassian.net/browse/PROD-939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1306742688/102901/

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1694623197/173527/
