### ISSUE TITLE
Messages - sending an image doesn't show on the receiver's end

### ISSUE THREAD

**Issue by ld-rlph** [buddyboss/buddyboss-platform#1116]
**Describe the bug**
Sending a message with an image, on the receiver's end it doesn't but in your end it shows.
This bug exists in version 1.4.4 and above.

**To Reproduce**
1. Send a message with an image to a particular connection

**Expected behavior**
It should show a message with an image

**Support ticket links**
https://secure.helpscout.net/conversation/1207964791/80389?folderId=3943007

**Comment by chetansatasiya** [comment]
@ld-rlph this will be fixed in our upcoming release. However you can add this patch to your site https://github.com/buddyboss/buddyboss-platform/pull/1091/files

**Comment by chetansatasiya** [comment]
@ld-rlph This is fixed in the today's release https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-6/ please update and it will fix the issue.
