### ISSUE TITLE
Hidden Group Discussion Bug

### ISSUE THREAD

**Issue by ld-rlph** [buddyboss/buddyboss-platform#1117]
**Describe the bug**
In a hidden group there is a discussion created by the group organizer and the members of the group aren't able to see it.

**To Reproduce**
1. Create a group and set it as hidden,
2. Add group members
2. Post a discussion inside the group using the organizer account
3. Login as a particular member of the account
4. Group member not able to see the discussion inside the group created by the organizer

**Expected behavior**
It should see the discussion since the account is member of the group

**Support ticket links**
https://secure.helpscout.net/conversation/1201354152/78918?folderId=3943007

**Comment by buddy4kp** [comment]
Hello @ld-rlph 
I have followed the above steps and try for re-produce this issue But I can not reproduce it. So please try with latest code of platform and let us know if you are still facing this issue. Below is the video recording of working fine this issue.
https://www.loom.com/share/44410e46ca8a4035b91a1c13ca5092a5
Thanks
+ @chetansatasiya

**Comment by sourabhmatolia** [comment]
@ld-rlph 

Can you please confirm if this is working fine for you now in recent release?
