### ISSUE TITLE
Cannot create or edit any posts

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1118]
**Describe the bug**
Cannot create or edit posts, custom post types, pages when the private messaging component is activated.

**To Reproduce**
1. Activate private messaging component
2. try to create or modify a post or page.

**Screenshots**
![post](https://user-images.githubusercontent.com/58522498/86289197-dca38980-bc1d-11ea-8d81-37cce6aba95f.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1212784946/81075/
https://secure.helpscout.net/conversation/1212569779/81007/
https://secure.helpscout.net/conversation/1212350454/80976/

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1213102809/81157/
