### ISSUE TITLE
Notification issue for being mentioned in the product review section

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1120]
**Describe the bug**
The notification when someone mentioned you in the review section of a single product is still unread even after viewing it.

**To Reproduce**
1. Go to BuddyBoss > Settings > Activity
2. Enable the following https://i.ibb.co/cgjhPHs/comments.png.
3. Go to a single product page and under the review tab, mention a user
4. Login using the mentioned user, and try to click on the notification regarding being mentioned.
5. Notice that it will not go away even after viewing it.

**Screencast**
https://drive.google.com/file/d/1w1IQZsGqSu12jn5Dhja-n7xV8IfH-Lm_/view

**Screenshots**
![notif](https://user-images.githubusercontent.com/58522498/86299422-ce139d00-bc32-11ea-8327-4c5c7d2ab4a6.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1212446962/80992/

**Comment by marienel21** [comment]
Bug can't be replicated in the latest version of the product. **It no longer allows mentioning a user/member under Reviews of a Single WC product.**
