### ISSUE TITLE
Compatibility issue with BuddyBoss Wall

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1137]
**Describe the bug**
The notification when someone likes your activity post **does not have the correct avatar** and **still unread even after viewing it**.

**To Reproduce**
1. Install BuddyBoss Wall.
2. Create an activity post
3. Using another account, like the activity post you created
4. Going back to the main user, check the notification and notice that it will not have the correct avatar.
5. Click on the notification and notice that it will still be unread after viewing it.

**Screenshots**
![ss](https://user-images.githubusercontent.com/58522498/86496980-45bc0600-bdb2-11ea-96d4-3f186965cb18.png)
![ss2](https://user-images.githubusercontent.com/58522498/86496982-46ed3300-bdb2-11ea-971d-570591f866a4.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1213149438/81176?folderId=3709081

**Comment by imehedidev** [comment]
**BuddyBoss Wall Time Stamp conflict**

The Time Stamp on a post disappeared when the BuddyBoss Child theme is activated. Yes, it disappears with the fresh child theme. Video: https://www.loom.com/share/de2f92ffb58647feb32fc8a12526d5a2
[Note: No issues with the BuddyBoss Parent theme]

**To Reproduce**

1. Install and activate BuddyBoss Wall
2. Install and activate the BuddyBoss Child theme
3. Check the Activity Feed

Support ticket links
https://secure.helpscout.net/conversation/1215090645/81682

**Comment by mahedihasannoman** [comment]
Hi @ayron-paul , BuddyBoss Wall is no longer needed in BuddyBoss Platform. See the doc: https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddyboss-wall/

So please close this ticket.

**Comment by ayron-paul** [comment]
The customer is using the BuddyBoss Wall to be able to like the comments which is not on the platform yet. Closing now, since this is already on the roadmap.
<img width="578" alt="chrome_D1ozr3vH1F" src="https://user-images.githubusercontent.com/58522498/133805889-d8282b4b-5c32-41b8-9944-a74e870eea79.png">
