### ISSUE TITLE
Numbered list formatting issue

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1138]
**Describe the bug**
Numbered list formatting is not displaying well when there are multiple sub-lists. Video explanation:  https://drive.google.com/file/d/1OKzHcX-9D864Zfa-kP_zFZl-gsXFyxCA/view

**Expected behavior**
Main and sub list should intend well

**Screenshots**
Edit: <img width="1680" alt="Edit Entry" src="https://user-images.githubusercontent.com/61000837/86517127-37b8c480-be48-11ea-9fee-5d561be3fe9d.png">
View: <img width="1680" alt="View" src="https://user-images.githubusercontent.com/61000837/86517130-43a48680-be48-11ea-8d3a-5420cb768a17.png">

**Support ticket links**
- https://secure.helpscout.net/conversation/1211771504/80862
- https://secure.helpscout.net/conversation/1149650605/71022

**Comment by chetansatasiya** [comment]
@sagarjadhav @amincdev Can anyone look into this please?

**Comment by amincdev** [comment]
@chetansatasiya I'll look into this soon.
