### ISSUE TITLE
Groups pages become slow when there are thousands of users in it with the latest version.

### ISSUE THREAD

**Issue by buntybuddyboss** [buddyboss/buddyboss-platform#1142]
If any group has thousands of users, then all the sub-tabs of that group are loading slow.

Previously reported here > https://github.com/buddyboss/buddyboss-platform/issues/859. Which was fixed in v1.4.0

This issue I noticed after v1.4.3. It's working fine till v1.4.3

**To Reproduce**
1. Go to Groups which has thousands of users.
2. Try to click on all the sub-tabs one by one
3. All the pages of that group will load slow.

**Expected behavior**
Single groups pages should not load slow when there are thousands of users in it.

**Video**
https://www.loom.com/share/bded52dd83a446928b40c5844c4ab157

**Sample DB from my local site**
[wp_bbplatform.sql.zip](https://github.com/buddyboss/buddyboss-platform/files/4879500/wp_bbplatform.sql.zip)

**Support Tickets**
Needed for @buntybuddyboss for a client project

**Comment by chetansatasiya** [comment]
@buntybuddyboss We have fixed this issue in #1130 PR you can make this https://github.com/buddyboss/buddyboss-platform/pull/1130/commits/f19b29c964768ab6f3e6b54a7ca076b09dfd2364 change into the customer site and it will fix the loading issue.
