### ISSUE TITLE
After moving the discussion, the forum name is not changing in the activity feed 

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1145]
**Describe the bug**
When you move a discussion to another forum, the forum name is not changing in the activity feed, this happens when there are existing subforums when there is none, it is working fine.

**To Reproduce**
1. Create a forum
2. Create a subforum
3. Add a discussion
4. Try to move the discussion to another forum
5. Now go to the activity feed and notice that the forum has not changed.

**Screencasts**
- https://drive.google.com/file/d/1Y_eV5O-ywk9x1ENjbWKWK2SDV1Pq4gaW/view
- https://drive.google.com/file/d/1KxJwDqxrRUIuBFLBBRc_Q3it4p8Hb80q/view

**Screenshots**
![ss](https://user-images.githubusercontent.com/58522498/86633049-beb19c80-c002-11ea-8f03-ec9be98dbabd.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1187525310/76614

**Comment by marienel21** [comment]
Bug is no longer reproducible on the latest version of the Platform.
