### ISSUE TITLE
New blog post activity from subsites are not working 

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1146]
**Describe the bug**
When creating a new blog post on a subsite, the blog activity feed is not working, this happens when BuddyBoss Platform is Network activated. Furthermore, when using BuddyPress it works well.

**To Reproduce**
1. On a multisite, network activate the BuddyBoss Platform
2. On network admin, go to BuddyBoss > Settings > Activity > activate, blog post, https://i.ibb.co/L840H6q/blogactivity.png
3. Go to any subsite, and post a new blog.
4. Go to the root site and check the news feed, notice that the activity from the subsite is not showing.

**Expected behavior**
You can try to Network activate the BuddyPress plugin and it works well

**Screenshots**

- When using BuddyBoss Platform: https://drive.google.com/file/d/1AcD8dEBKFS35qD0MZJghYx1EmNcHrLpl/view
- When using BuddyPress: https://drive.google.com/file/d/1-nu-useZjrmc6iV79_kIuDtgdzDp0LW5/view

**Support ticket links**
https://secure.helpscout.net/conversation/1190459338/77136/

**Comment by KartikSuthar** [comment]
@ayron-paul @ankitguptaindia 
I have checked and found that issue was already fixed into the dev branch. 
http://somup.com/cYitXs6lX8

Can you please check and confirm?

**Comment by ayron-paul** [comment]
Hi @KartikSuthar, I can confirm that the issue seems to be fixed from the latest **dev branch**. Thanks!

**Comment by KartikSuthar** [comment]
Thanks @ayron-paul ! I am closing the issue.
