### ISSUE TITLE
Comments section for modal image not working on multiple photo uploads in Groups > Activity feed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1147]
**Describe the bug**
Comments section for modal image not working on multiple photo uploads in Groups > Activity feed.
When you upload a single image in Groups > Activity Feed and clicking the uploaded image, the comments section work/

**To Reproduce**
1. Go to Groups > Activity Feed
2. Upload multiple images
3. Click on one of the uploaded image
4. See error, notice that the Comments section for the pop up of the image does not show

**Expected behavior**
When you upload a single image and you click on it, the pop up shows with comment section.
This should happen the same for multiple images

**Screenshots**
https://drive.google.com/file/d/1az8tddVXuxSqUaprbTUPiFlF-njN0n0R/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1208505608/80485

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1227173670/83588

**Comment by amincdev** [comment]
@emmanoctaviano Closing this issue because this issue is already fixed and I see that customers are also informed for the same in both tickets mentioned above.
