### ISSUE TITLE
Only "Public" Profile Updates Shown on Activity Feed, Even Among Connected Users

### ISSUE THREAD

**Issue by Coopman14** [buddyboss/buddyboss-platform#1148]
**Describe the bug**
Profile field updates are only visible in Activity Feed when the profile field has been chosen for "public" visiblity.  If two users are connected and the field is chosen for visibility to "connections", the updates do not appear in the Activity Feed of the connected user.  Likewise, changes to profile fields chosen for visibility to "all members" do not appear in the Activity Feed of other users.

**To Reproduce**
1. Activate "member updates their profile details" in the Posts in Activity Feed BuddyBoss settings on the backend.
2. Connect User A and User B on the site.
3. Change a profile field in User A's profile with the profile field visibility selected for "connections".
4. Visit User B's Activity Feed to see that User A's profile field change is not displayed on User B's Activity Feed.

**Expected behavior**
Users would see an update in their Activity Feed when a connected user edits a profile field with visibility to "connections".

**Screenshots**
Screenshots would likely not be very helpful.  The bug is a lack of an update on the Activity Feed.

**Support ticket links**
80293

**Comment by asaquzzamanbb** [comment]
This issue seems fixed here https://github.com/buddyboss/buddyboss-platform/issues/1167
