### ISSUE TITLE
Groups - show photos and album count in tabs

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#115]
Show photos and album count in group tabs

https://secure.helpscout.net/conversation/1112111628/13420/

**Comment by marienel21** [comment]
The feature now applies to the current version. 
![Screenshot (2)](https://user-images.githubusercontent.com/77659570/124801896-f2aefd00-df89-11eb-9607-bce1cc2ecb64.png)
