### ISSUE TITLE
Browser tab name always shows the First Name when Display Name Format is different.

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1154]
**Describe the bug**
No matter what is the Display Name Format, the browser tab name shows the First Name always.

**Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/68964d19cdf64291be1cbdc4762803e8

**Expected behavior**
Browser tab name should work based on the Display Name Format settings. Ex: when user selects the Nickname, it should show the Nickname; not the First Name.

**Screenshots**
![download](https://user-images.githubusercontent.com/61000837/86784158-04ae4500-c083-11ea-9077-e1472aab6b1b.jpeg)

**Support ticket links**
https://secure.helpscout.net/conversation/1211642323/80830/

**Comment by janakkaneriya007** [comment]
@imehedidev I have checked the display format settings and found that it's working fine. You just have to run the community settings after changing the display format to update the display format for site on related areas that includes browser tab(Page title). Follow the screenshots below.
https://prnt.sc/uvdk88
https://prnt.sc/uvdkry
