### ISSUE TITLE
Time Stamp conflict with TranslatePress

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1155]
**Describe the bug**
Timestamp issue when using TranslatePress to convert the site to any other language. The time is always "right now" for all of the updates when it's switched to a different language, while this function works perfectly fine in the English version.

**To Reproduce - Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/516f07bfbe6343cc9d6fb04163ebbd2d

**Expected behavior**
It should show the correct time.

**Screenshots**
https://prnt.sc/tder2m

**Support ticket links**
https://secure.helpscout.net/conversation/1215884566/81833

**Comment by chetansatasiya** [comment]
Closing this as this fixed in https://github.com/buddyboss/buddyboss-platform/pull/1266
