### ISSUE TITLE
Notification issue when someone added product review

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1158]
**Describe the bug**
The notification is still unread when someone added a new review on your product even after viewing it.

**To Reproduce**
1. Go to BuddyBoss > Settings > Activity
2. Enable the following https://i.ibb.co/cgjhPHs/comments.png.
3. Go to a single product page and under the review tab, add a review.
4. Login using the product owner and check your notification.
5. Notice that it will not go away even after viewing it.

**Screenshot**
![ssss](https://user-images.githubusercontent.com/58522498/86818349-da777a00-c0b8-11ea-9530-b5485e242df6.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1212446962/80992/

**Comment by janakkaneriya007** [comment]
Related issue: https://github.com/buddyboss/buddyboss-platform/issues/1251

**Comment by janakkaneriya007** [comment]
Related PR here: https://github.com/buddyboss/buddyboss-platform/pull/1667
