### ISSUE TITLE
Translating the "BuddyBoss" admin menu is causing an issue to Theme Options and License Keys page

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1160]
**Describe the bug**
When you translate the "BuddyBoss" admin menu, the Theme Options and License Keys admin pages are not accessible

**To Reproduce**
1. Go to Loco Translate > Plugins > BuddyBoss Platform
2. Translate "BuddyBoss" to any word
3. Navigate to Theme Options and License Keys and notice that neither of them is working.

**Screenshots**
![translate2](https://user-images.githubusercontent.com/58522498/86849863-e7a95e80-c0e2-11ea-8d7b-eb213a044740.png)
![translate](https://user-images.githubusercontent.com/58522498/86849864-e841f500-c0e2-11ea-8ac9-fc35ef7aed5e.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1216406470/81940
https://secure.helpscout.net/conversation/1217701161/82132

**Comment by janakkaneriya007** [comment]
Issue is related to BuddyBoss Theme: https://github.com/buddyboss/buddyboss-theme/issues/1088
