### ISSUE TITLE
Rename ducument to a non-english language (like PERSIAN) issue

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#1161]
**Describe the bug**
when we want to change the ducument name to a non-english language (like PERSIAN) name, it shows this message: 
"Following special characters are not supported: ' " \ * | / > < ? ` ; : {space}"

If the file name is non-english when uploaded, there is no problem, but it is for renaming!

**Screenshots**
![Capturewefw](https://user-images.githubusercontent.com/13551603/86888626-ba26da00-c10f-11ea-824a-a03a2575a547.PNG)

**Comment by mailalaki** [comment]
i hope it will be resolved soon

**Comment by amincdev** [comment]
@mailalaki This issue is already in development. Issue link: https://github.com/buddyboss/buddyboss-platform/issues/1072

**Comment by sourabhmatolia** [comment]
Hello @mailalaki  

Issue created above is fixed and released in Buddyboss Platform v1.4.7.

**Find plugin v1.4.7 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-7/

Please update the plugin to see the latest changes.

Thanks

**Comment by mailalaki** [comment]
hi
tanx for new update (1.4.7) and it fixed non-english characters, but why {space} key is not supported?!!
it is better if it does not support, automatically convert it to {dash} (-) after inserting the name.
![buddyboss](https://user-images.githubusercontent.com/13551603/88888844-4e3e1a00-d254-11ea-80e1-3a71468ba63a.PNG)

**Comment by chetansatasiya** [comment]
> hi
> tanx for new update (1.4.7) and it fixed non-english characters, but why {space} key is not supported?!!
> it is better if it does not support, automatically convert it to {dash} (-) after inserting the name.
> ![buddyboss](https://user-images.githubusercontent.com/13551603/88888844-4e3e1a00-d254-11ea-80e1-3a71468ba63a.PNG)

@mailalaki We are following the standard of WordPress and if you upload the file with the space it will automatically add `-` in the file name. You can check by going into the WordPress backend and in Media tab.

**Comment by mailalaki** [comment]
> 
> 
> > hi
> > tanx for new update (1.4.7) and it fixed non-english characters, but why {space} key is not supported?!!
> > it is better if it does not support, automatically convert it to {dash} (-) after inserting the name.
> > ![buddyboss](https://user-images.githubusercontent.com/13551603/88888844-4e3e1a00-d254-11ea-80e1-3a71468ba63a.PNG)
> 
> @mailalaki We are following the standard of WordPress and if you upload the file with the space it will automatically add `-` in the file name. You can check by going into the WordPress backend and in Media tab.

ok, so to pay attention to the user experience, i think it is necessary to automatically convert `spaces` to `-`. as in changing the folder name, we do not have to insert `-` .

**Comment by chetansatasiya** [comment]
@mailalaki We are allowing the spaces into the folder name so you don't need to insert `-` into the folder name.

**Comment by mailalaki** [comment]
> 
> 
> @mailalaki We are allowing the spaces into the folder name so you don't need to insert `-` into the folder name.

yes, i mean renaming files should be the same as renaming folders without the need for `-`. after entering the name, the `space` replace automatically in file name.
