### ISSUE TITLE
Activities are not generated if the visibility of the profile field is set to "my connections"

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1167]
**Describe the bug**
Activities are not generated if the visibility of the profile field is set to "my connections". I tried setting it to public, but the activity was generated only once. 

**To Reproduce**
1. Go to BuddyBoss > profile > set the profile field visibility to "my connections"
2. Edit that field through profile > edit on the front end
3. Check the activity page

**Expected behavior**
- The activities must be generated at least on the user's profile page who is editing the profile. 

**Screenshots**If applicable, add screenshots to help explain your problem.
- https://i.imgur.com/S7Y9jRt.jpg
- https://www.loom.com/share/90e8de8b3ed1483f94c0fe07ef0e127f

**Support ticket links**
- https://secure.helpscout.net/conversation/1207507244/80293/

**Comment by KartikSuthar** [comment]
Hey @archanabb , 

I have checked for this and found that We are posting the activity while the profile visibility set to the public.
We can not post activity for non-public fields.

This is followed by BuddyPress and Platform both.
There is no sense to post activity for the user himself while they updating his own profile.

@sourabhmatolia Can you please give your suggestion here?

**Comment by sourabhmatolia** [comment]
@KartikSuthar @archanabb 

I think it makes sense what Kartik says above.

These auto-generated activities are always public, if Member updates their profile field which is not public (my connection, all member, only me) then logically that should not be added as a public activity. 
So logically the way it works right now is fine. 

That's my feedback. Let me know @archanabb if this makes sense?

We can close this issue. Thanks.
