### ISSUE TITLE
Group members can't see their hidden group when a group page is created with the group type shortcode

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1171]
**Describe the bug**
Group members can't see their hidden group when a group page is created with the group type shortcode. It works when the group privacy is public and private.

**To Reproduce - Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/4ae51e6e43354b748622f44d497a7f2c

**Expected behavior**
Group members see their hidden groups.

**Support ticket links**
https://secure.helpscout.net/conversation/1218549643/82261

**Comment by sumitbuddyboss** [comment]
Fixed. I have tested on fix/1171 branch this issue is resolve now. For proof please check the below video.

**Video:**
https://www.loom.com/share/80feb3d35fa44e628284c992ea4534d5
