### ISSUE TITLE
WC Vendors Pro Integration issues

### ISSUE THREAD

**Issue by christinabbsupport** [buddyboss/buddyboss-platform#1179]
Issues identified by Customer:

1. If someone registers through the WC Vendors screen (which is absolutely necessary so that people can register as vendors), it doesn’t register with a user type in BuddyBoss. That means it will still show on the user list even if it’s not supposed to. 

2. The mobile version of the dashboard isn’t mobile friendly 

3. There is no mapping function that works. Here’s the email from GeoMyWP: It seems that when the BuddyBoss team included the BP Profile Search plugin inside its own theme they had also modified the functions and hooks names of the original plugin. And because of that, the integration of GEO my WP is no longer working. If I am correct ( about renaming the functions and hooks of the plugin ), then what the BuddyBoss team had done is not OK and they should have not done it this way. Because of that, other integrations with the BP Profile Search would no longer work. The only solution I can suggest is to keep the BP Profile Search Geolocation core extension of GEO my WP deactivated. This way the map of the Members Directory Geolocation extension is still working.

**Support ticket links**
https://secure.helpscout.net/conversation/1186286246/76388?folderId=3701264

**Jira issue** : [PROD-936]

[PROD-936]: https://buddyboss.atlassian.net/browse/PROD-936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chetansatasiya** [comment]
@dipskakadiya When you get a chance please look into this.
