### ISSUE TITLE
Uploading photos on iPhone, the photo is rotated sideways. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1180]
**Describe the bug**
When adding photos on the iPhone using Chrome or Safari using the Add Photos button on the Photos profile tab, then clicking on the "Drop images here to upload", then clicking on the Take Photo, and taking a photo, the image displays sideways and not in the correct upright position.

**To Reproduce**
1. Go to 'profile > photos'
2. Click on 'Add Photos'
3. Click on 'Drop images here to upload' then Take Photo from camera. 

**Expected behavior**
Right orientation. 

**Screenshots**
[Attachments.zip](https://github.com/buddyboss/buddyboss-platform/files/4901953/Attachments.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1218485289/82244?folderId=3701249

**Comment by perfectlifetime** [comment]
When will this issue be fixed?  It's a very visible bug to site users.  Also I updated the helpscout ticket via the BuddyBoss ticketing system to convey that this also happens with the profile photo uploads on the iPhone, if you click on Choose Image Size after selecting the photo from the iPhone photo gallery and then select Large, Medium or Small.  It actually uploads the photo sideways.

**Comment by mehulkaklotar** [comment]
@sourabhmatolia @eisenwasser @chetansatasiya We need to update dropzone lib to latest. It may have some changes in design frontend.

**Comment by Anve-sri** [comment]
@mehulkaklotar Please also have a look at https://github.com/buddyboss/buddyboss-platform/issues/1403 , might be related.

**Comment by dipskakadiya** [comment]
Related ticket : https://github.com/buddyboss/buddyboss-theme/pull/219

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

This issue appears sometime with some photos. Not every time with all photos. It showing little weird behavior every time. 
when you upload and select photos from phone media folder and select the size of given options then it rotate photos sometime left or some time right. 

Refer below screenshot - 

- Looks fine when use these photos - https://i.imgur.com/Mh79qRc.jpg

- It doesn't look fine with these photos - https://i.imgur.com/vt0TahJ.jpg  

--
@sumitbuddyboss 
Please report these issue on respective PR where you testing others fixes.

**Comment by sfraise** [comment]
They show upside down now
