### ISSUE TITLE
BuddyBoss compatibility issue with TranslatePress in multisite setup

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1185]
**Describe the bug**
When using TranslatePress in multisite setup, other component pages of other languages is not working

**To Reproduce**
1. Activate TranslatePress
2. In the admin toolbar, go to Translate Site > Settings
3. Add other languages
4. Go to any component pages
5. change the URL or switch to other languages and notice that the page is blank

**Screencast**
https://tinyurl.com/y744uj7p

**Support ticket links**
https://secure.helpscout.net/conversation/1211869674/80881

**Jira issue** : [PROD-935]

[PROD-935]: https://buddyboss.atlassian.net/browse/PROD-935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mahedihasannoman** [comment]
Hi @ayron-paul , I am not able to reproduce this issue with latest version of BuddyBoss Platform & theme. Will you please check and confirm if the issue is still happening on your end? If not then please close this issue.

**Comment by mahedihasannoman** [comment]
I can replicate this issue on my end.
