### ISSUE TITLE
Group save not working when Zoom Integrations is activated on Platform Pro

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1186]
**Describe the bug**
Group save not working when Zoom Integrations is activated on Platform Pro.
When API credentials are placed on Groups, this works, but without API credentials, the save button is not working

**To Reproduce**
1. Enable Platform pro
2. Go to BuddyBoss > Integrations > Zoom and enable Zoom
3. Go to a single Group, and click Save

**Expected behavior**
The save button is not working when Zoom integration is enabled, some customers wan't certain Groups to have Zoom and other Groups to be Zoom disabled.

**Screenshots**
https://drive.google.com/file/d/1FtzW0mQSp2CW6TQfCu7zpmCZuLP1rHdW/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1220184261/82535

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1221287876/82705/

**Comment by KartikSuthar** [comment]
@emmanoctaviano @ayron-paul 
It was fixed from the Platform Pro and it will be in next release: 
https://github.com/buddyboss/buddyboss-platform-pro/pull/30
