### ISSUE TITLE
Learndash changing the Edit page links in admin bar to homepage instead of groups page

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1187]
**Describe the bug**
Groups edit page in front end redirects to Homepage

**To Reproduce**
Issue can be replicated in Demo
1. Go to Groups page (frontend)
2. Click on Edit Page 
3. See error

**Expected behavior**
When editing Groups page, it should not redirect to Homepage edit

**Screenshots**
https://drive.google.com/file/d/1W9XNhXcswICRddM7ruLi8LY2I7bgfiGp/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1215499495/81761

**Comment by sourabhmatolia** [comment]
@chetansatasiya 

When we try to access Leardash Group archive page then it doesn't work. 

Please watch the video shared here for more details:
https://www.loom.com/share/6a7373d3eff2492292bb1804ab1389d7

Thanks.
