### ISSUE TITLE
Check existing friendship before creating a new friendship request

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1199]
**Describe the bug**
Initial issue reported : [https://github.com/buddypress/BP-REST/issues/321](url)

Hello, I've already reported this issue on the BuddyPress REST API Github and the issue has been resolved since then.

Via the REST API, you can create as many as friendship request as you want. This leads to a problem in the database (duplicate friendship requests).

**To Reproduce**
Create multiple identical friendship request via the rest api endpoint (friends).

**Support ticket links**
https://github.com/buddypress/BP-REST/issues/321

**Comment by sourabhmatolia** [comment]
Hello @ExoGeek  

Issue created above is fixed and released in Buddyboss Platform v1.4.7.

**Find plugin v1.4.7 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-7/

Please update the plugin to see the latest changes.

Thanks
