### ISSUE TITLE
Repeater field delete issue

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1200]
**Describe the bug**
When you delete an old record from a repeater field it duplicates some data when you add a new record.

**To Reproduce**
1. Create a repeater fieldset with at least 10 fields
2. Go to edit profile and add at least 3 records
4. Try to delete the oldest record
5. After deleting add a new record and notice that it will already have data from other fields.

**Screencast**
https://cutt.ly/9fDJawl

**Support ticket links**
https://secure.helpscout.net/conversation/1204976046/79764

**Comment by marienel21** [comment]
I can't replicate thid bug on the latest version of the Platform.
