### ISSUE TITLE
Comment issue when uploading multiple photo in a group.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1201]
**Describe the bug**
When posting a single picture, I can comment on that picture, but when posting 2 or more pictures, I can't comment on that picture. The comment area is blank when you view the photo in the lightbox.

**To Reproduce**
1. Open a group and post 2 or more pictures at a time.
2. Click on the photo to open it in a lightbox.
3. See error

**Expected behavior**
should be able to comment on each photo if multiple photos are uploaded

**Screenshots**
https://prnt.sc/ti0btd
https://prnt.sc/ti0c8a

**Support ticket links**
https://secure.helpscout.net/conversation/1225878989/83384

**Comment by KartikSuthar** [comment]
@furqanbb 
I have checked with the dev branch and it's already fixed.
http://somup.com/cYitlx6l2a

PR: https://github.com/buddyboss/buddyboss-platform/pull/1093
