### ISSUE TITLE
Join Group button redirects to 404 page when Profile Type Joining option is activated

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1205]
**Describe the bug**

Join Group button of a Private Group redirect to 404 page when Profile Type Joining option is activated inside the Group Type settings.

**To Reproduce - Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/58ac01fca790493ca78b8315a83adf7b

**Support ticket links**
https://secure.helpscout.net/conversation/1222048968/82814

**Comment by KartikSuthar** [comment]
@imehedidev I am closing this issue as it was already fixed in the PR: https://github.com/buddyboss/buddyboss-platform/pull/1128
