### ISSUE TITLE
BB REST API : Reply to message using thread_id (without setting recipients field)

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1207]
**Describe the bug**
We should be able to reply to an existing thread using only the thread_id (no need to set recipients). But because the recipients field is set to "required", there's an error "rest_missing_callback_param" ("Missing parameter(s): recipients").

```
// Edit recipients properties.
$args['recipients']['required']          = true;
```

**To Reproduce**
This HTTP POST Request should work :
```
POST {{host}}/wp-json/buddyboss/v1/messages
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 13,
  "message": "Test reply to existing thread using id"

}
```

**Expected behavior**
In order to correct this issue, the only thing to do is to modify the line 1536 in the file "class-bp-rest-messages-endpoint.php"

`$args['recipients']['required']          = false;`

**Comment by sourabhmatolia** [comment]
Hello @ExoGeek  

Issue created above is fixed and released in Buddyboss Platform v1.4.7.

**Find plugin v1.4.7 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-7/

Please update the plugin to see the latest changes.

Thanks
