### ISSUE TITLE
Zoom translation using TranslatePress plugin

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1208]
**Describe the bug**
Translating the zoom page using translatepress plugin 

**To Reproduce**
1.  Create new zoom meeting.
2. Go to zoom tab.
3. See error

**Expected behavior**
Either the time schedule should also be translated or not.

**Screenshots**
In english:
https://prnt.sc/tif3ib
In mandarin:
https://prnt.sc/tievn9

**Support ticket links**
https://secure.helpscout.net/conversation/1214571461/81568?folderId=3943005
Related ticket:
https://secure.helpscout.net/conversation/1217911270/82160?folderId=3709080
https://secure.helpscout.net/conversation/1220209934/82541?folderId=3709081
https://secure.helpscout.net/conversation/1374813046/116093

**Comment by fabiomail** [comment]
Having the same issue with TranslatePress and Zoom, without even translating the zoom page. 

Very annoying because it is impossible to use the zoom feature with translatepress plugin activated.

Could you prioritize the fix?

**Comment by fabiomail** [comment]
up

**Comment by fabiomail** [comment]
@chetansatasiya @jrbuddyboss any updates on this?

**Comment by sourabhmatolia** [comment]
**UPDATE**

Task moved to Platform Pro
