### ISSUE TITLE
Only Me option not working on Photo upload ( anyone can see that photo & also without login )

### ISSUE THREAD

**Issue by eat-code** [buddyboss/buddyboss-platform#1211]
**Describe the bug**
When user Post updates from activity Feed Only Me option not working for Photo upload. anyone can see that photo & also without login.

**To Reproduce**
1. Go to Activity Feed section
2. Click on the Upload photo icon and upload a photo
3. set the visible mod to only me.
4. See it with an incognito mode or log in with other users you can see the photo.

**Expected behavior**
Should not display the photo anyone if set the privacy to only me.

**Screenshots**
https://www.loom.com/share/65e2550e363c41c69c82ca88cabdf87b

**Support ticket links**
https://secure.helpscout.net/conversation/1227287263/83604?folderId=3709081

**Comment by imehedidev** [comment]
It doesn't work with "My connections" either.

https://secure.helpscout.net/conversation/1232360945/84503

**Comment by sourabhmatolia** [comment]
@KartikSuthar 

Reviewed issue fixed but it doesn't work for me.

Please check video for more details:
https://www.loom.com/share/3ed98644d1a145d08ca6ee84c0023846

Thanks.
