### ISSUE TITLE
BuddyPanel is hidden on mobile device when using Elementor header and buddyboss header block widget is not mobile friendly.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1212]
**Describe the bug**
Trying to build a custom header using Elementor and the header block also isn't mobile-friendly. It does not include the menus in the BuddyPanel on mobile devices.

**Expected behavior**
Show buddypanel on mobile and mobile friendly Buddyboss header block widget. 

**Screenshots**
https://www.loom.com/share/fe743b644bf546baa1084a30d27b058a

**Support ticket links**
https://secure.helpscout.net/conversation/1223686489/83059?folderId=3701249

**Comment by annrra** [comment]
@Anve-sri @sagarjadhav 
moving this issue to buddyboss theme since it is theme related - https://github.com/buddyboss/buddyboss-theme/issues/864
we can close/archive this one

**Comment by irixzafra** [comment]
Hi, any update on this? Still the issue. I follow to the link abobe but its broken: 
https://github.com/buddyboss/buddyboss-theme/issues/864

**Comment by lazmo88** [comment]
Having the same issue, also the link is dead https://github.com/buddyboss/buddyboss-theme/issues/864


> Hi, any update on this? Still the issue. I follow to the link abobe but its broken:
> https://github.com/buddyboss/buddyboss-theme/issues/864
