### ISSUE TITLE
Editing a reply edits the main discussion

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1217]
**Describe the bug**
Using a subscriber account, when you try to edit your reply after visiting another page, you will be able to edit the main discussion

**To Reproduce**
1. Using a non admin account, try to reply to any discussion
2. Visit another page on your site
3. Go back to the discussion and edit your reply
4. Notice that it will edit the main discussion

**Screencast**
https://bit.ly/2DQhhJG

**Support ticket links**
https://secure.helpscout.net/conversation/1221905857/82787
https://secure.helpscout.net/conversation/1227954508/83710
https://secure.helpscout.net/conversation/1234538663/84821

**Comment by chetansatasiya** [comment]
Closing this issue as we already fixed in theme here https://github.com/buddyboss/buddyboss-theme/pull/839
