### ISSUE TITLE
Privacy settings (private network) are not working after updating the BuddyBoss Theme. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1223]
**Describe the bug**
Privacy settings (private network) are not working after updating the BuddyBoss Theme. I made the site private and added a few links to be public like /home/ etc. But I was not able to access any page that was made public. 

It worked for me with the old version of the theme. But it stopped working when I updated the 1.5.3.

**To Reproduce**
1. Go to BuddyBoss Platform settings
2. Enable private network and make some URLs public
3. Visit the public URLs 

**Expected behavior**
The public pages should be accessed even when the site is set to be private.

**Screenshots**
- https://i.imgur.com/uAiOpb8.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1227957503/83712/

**Comment by chetansatasiya** [comment]
I am looking into this @archanabb

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1227933862/83707

**Comment by marienel21** [comment]
Bug no longer reproducible on the current version of the Platform
