### ISSUE TITLE
Margin issue when using Elementor page template.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1225]
**Describe the bug**
Created a page using elementor and added a shortcode for the group type to display the groups, There is gap in place of buddypanel even though the buddypanel option is disabled from a theme setting.
Removing the group type shortcode fixes the gap issue.

It seems some wrong classes are being added to the body.

**To Reproduce**
1. Create a new page using an elementor.
2. Add group type shortcode eg [group type="test"]
3. disable the buddypanel from a theme setting.
4. See the gap on the front end.

**Expected behavior**
If Buddypanel is disabled, there should not be gap.

**Screenshots**
https://prnt.sc/tjhqjk
https://prnt.sc/tjhq8u
https://prnt.sc/tjhrct

**Support ticket links**
https://secure.helpscout.net/conversation/1225957370/83394

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1373402986/115884/

**Comment by kishanjasani** [comment]
This is not a Platform issue. It's related to the theme.
