### ISSUE TITLE
Broken HTML in forum replies breaks whole page

### ISSUE THREAD

**Issue by buntybuddyboss** [buddyboss/buddyboss-platform#1226]
When we copy and paste things from internet, and that copied content contains invalid HTML, then replies page is all broken.

**Steps to reproduce the behavior:**
1. Go to any discussion.
2. Reply with some invalid HTML content. ( I have shared my local DB and shared video as well. You can have that invalid HTML from backend. )
3. Refresh the page.

**Expected behavior**
Replies page should not be broken.

**Video**
https://www.loom.com/share/6e92c3cca70e42c1a0f8728c7e7feab1

**My Local DB**
[wp_bbplatform-2020-07-17-3443e94.sql.zip](https://github.com/buddyboss/buddyboss-platform/files/4938993/wp_bbplatform-2020-07-17-3443e94.sql.zip)

**Comment by amincdev** [comment]
@buntybuddyboss This is already work-in-progress here: https://github.com/buddyboss/buddyboss-platform/pull/1034

**Comment by manishpatolia** [comment]
@mehulkaklotar @KartikSuthar 

As per our discussion, still having the issue. Please watch below videos:

Client Dev site: https://www.loom.com/share/aabf5094e0d24dedacce7cf6147eea5d
Default Site: https://www.loom.com/share/81b1a8a2b5b64ee0acc2b5bafd773cd8

**Comment by buntybuddyboss** [comment]
@mehulkaklotar @KartikSuthar When we edit that broken html reply from backend and when we switch editor from text - visual and then save it, then it fixes the issue. May be this helps.

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1269572675/90961

**Comment by sourabhmatolia** [comment]
@buntybuddyboss @manishpatolia @imehedidev 

Issue shared above is partially fixed and partially pending.
Whatever fixed here (https://github.com/buddyboss/buddyboss-platform/pull/1034) so far we will release.
Pending issues @KartikSuthar @amincdev will work on that soon in priority.

Thanks.

**Comment by imehedidev** [comment]
HTML tags are showing in the forums when subscribers post copy-paste content from an external DOCS to forums:
https://www.loom.com/share/47d0561e85834ef6a9e5d2d517914cb2

**Comment by sourabhmatolia** [comment]
@KartikSuthar will share an update on the same soon. Thanks.

**Comment by imehedidev** [comment]
@sourabhmatolia @KartikSuthar 
A user still has the issue after applying the 1.5.8 update. Please check this video: https://www.loom.com/share/275e19b9c4a0465881d3bf5f8485a113

**Comment by KartikSuthar** [comment]
@imehedidev 
As discussed with @sourabhmatolia I have to unwrap the ordered list and unordered list tags while performing copy and past.

I have made this change and created PR: https://github.com/buddyboss/buddyboss-platform/pull/1572
