### ISSUE TITLE
Created event for private group

### ISSUE THREAD

**Issue by ld-rlph** [buddyboss/buddyboss-platform#1231]
**Describe the bug**
News Feed page -> All Updates tab, whenever an admin creates an event for a private group, the update shows on all users, even the users which is not a member of the private group see the update on their news feed, and when the user clicks it will show a page not found, this happens because user is not member of the private group.

**To Reproduce**
1. Create a private group
2. Create an event and assign it to that private group you created
3. Login as user that is not a member of that private group you created
4. Go to news feed page and you will see that update that says "[user name] posted a new event, [event name]"
5. Click on that feed and it will redirect to a page that don't exist (404 page not found)

**Expected behavior**
That feed should not show on users that is not a member of that private group where the event is assigned to, it makes no sense to show that since they are not a member of that private group and see that update, and when clicked it will just show page not found error.

**Screenshots**
https://prnt.sc/tjtcwe
https://prnt.sc/tjtduo

**Support ticket links**
https://secure.helpscout.net/conversation/1227442409/83630

**Comment by buddy4kp** [comment]
Hello @ld-rlph 
I am trying to reproduce this issue But I can not as we do not have more details for 2nd step ("Create an event and assign it to that private group you created"). i.e Which event plugin we have to use, where you are assigning the event to private group etc...
If Possible, Please provide us with more details or video for this issue so we can check and fix it.
Thanks.

**Comment by ld-rlph** [comment]
Here's a video: https://www.loom.com/share/5907bf31d5f24778a013d11b7e93b79e

**Comment by sourabhmatolia** [comment]
@buddy4kp @ld-rlph 

"Events Manager" plugin adds activity when an event is created, we can disable the Buddyboss platform setting to create Event CPT activity again which is creating a problem.

**Please watch the video shared below showing problem and the solution:**
https://www.loom.com/share/f62d86c6507f4be7be6e511e3d620a0a

Please confirm @ld-rlph  if this makes sense?
We can close this issue. Thanks.

**Comment by bb-ralph** [comment]
Resolved, thank you!
