### ISSUE TITLE
Discussion list not showing up for album photo

### ISSUE THREAD

**Issue by eat-code** [buddyboss/buddyboss-platform#1232]
**Describe the bug**
Discussion list not showing up for album photo. In a group page, there is an option for creating an album. After creating an album when clicking on the single photo it opens a popup and the right sidebar will be empty. But here should display a discussion list. 

**To Reproduce**
1. Go to a group page and create an album
2. Click on the single photo within the album
3. On the right sidebar will be empty

**Expected behavior**
Discussion list should display here, like comments 

**Screenshots**
https://prnt.sc/tkknml

**Support ticket links**
https://secure.helpscout.net/conversation/1226141113/83428/

**Comment by chetansatasiya** [comment]
@eat-code I am not able to reproduce this issue. I checked on demo see here https://www.loom.com/share/1d79b0f6db37495dbe211b5c80caefb4 and there is no any issue. Could you check with the latest release and see if this working or not in customer site.
