### ISSUE TITLE
Documents tab layout - document list broken

### ISSUE THREAD

**Issue by jlessamn** [buddyboss/buddyboss-platform#1248]
**Describe the bug**

In documents tab the list files or directories are not very organized with other components like buttons and search field. It seems like they are on same line and it compress the space reserved for files and directories description. It gets worth when you are using vertical menu navigation option. 

If you create a second layer and navigate into a sub-directory the problem vanish.

**To Reproduce**
1. Go to Documents tab
2. Upload a file or create a directory

**Expected behavior**
The first layer should work as second layer of directories or files

**Screenshots**
Screenshots attached to show the problem, it´s self explanatory. 

![horizontal directory - first layer](https://user-images.githubusercontent.com/8340903/88210193-2a624f00-cc2a-11ea-911b-a5c923d7151b.PNG)
![horizontal directory - second layer](https://user-images.githubusercontent.com/8340903/88210196-2b937c00-cc2a-11ea-8b55-594d19e77d6f.PNG)
![vertical directory - first layer](https://user-images.githubusercontent.com/8340903/88210198-2c2c1280-cc2a-11ea-8940-9d5c1cae5ef1.PNG)
![vertical directory - second layer](https://user-images.githubusercontent.com/8340903/88210200-2cc4a900-cc2a-11ea-9b89-fa2b5c52b9c9.PNG)

**Comment by amincdev** [comment]
@jlessamn Can you please let us know which theme you are using?

**Comment by jlessamn** [comment]
> @jlessamn Can you please let us know which theme you are using?

Hi Amin,

I've tried with twenty twenty, twenty nineteen but my theme is wallstreet-pro

Thanks

**Comment by sourabhmatolia** [comment]
@jlessamn 

Issue created above is released in Buddyboss Platform v1.5.0.

Find platform v1.5.0 release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-8/

Please update the plugin to see the latest changes.

Thank you.
