### ISSUE TITLE
Gamipress posts appear on Activity page even when it is unchecked on Buddyboss settings. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1249]
**Describe the bug**
Gamipress posts for achievement still being posted even if custom post for Gamipress are already disabled in the activity.

**To Reproduce**
1. Disable the CPTs from BuddyBoss > Settings > Activity > Posts in Activity feed.
2. Create badges and achievement. https://gamipress.com/docs/tutorials/creating-an-achievement-type/
3. Assign an achievement to user. 
4. It will show under Activity posts.

**Expected behavior**
Should not show.

**Support ticket links**
https://secure.helpscout.net/conversation/1230291526/84146?folderId=3701249

**Comment by shohelbuddyboss** [comment]
@Anve-sri Could you please make a screencast by reproducing this issue from the first to last. I've checked several times, can't reproduce.

**Comment by Anve-sri** [comment]
> @Anve-sri Could you please make a screencast by reproducing this issue from the first to last. I've checked several times, can't reproduce.

Please check this https://www.loom.com/share/aff21dbded0b464a9d7fc389e7be4d5f

**Comment by shohel** [comment]
@Anve-sri 

There is a setting from Gamipress-BuddyPress integration that appearing at the achievement type page from Gamepress menu, select an achievement type, and check the settings below.

https://prnt.sc/u4xa42

If anyone would like to stop post badge in the user's activity timeline. turn off **Achievement Activity** settings.

Unchecking post type from the BuddyBoss menu will not work here.

The logic is, **Actually GamePres - BuddyPress integration** plugin posting the activity

Feel free to let me know if you have any more confusion.

cc @sourabhmatolia

**Comment by shohelbuddyboss** [comment]
@Anve-sri

There is a setting from Gamipress-BuddyPress integration that appearing at the achievement type page from Gamepress menu, select an achievement type, and check the settings below.

https://prnt.sc/u4xa42

If anyone would like to stop post badge in the user's activity timeline. turn off Achievement Activity settings.

Unchecking post type from the BuddyBoss menu will not work here.

The logic is, Actually GamePres - BuddyPress integration plugin posting the activity

Feel free to let me know if you have any more confusion.

cc @sourabhmatolia

**Comment by Anve-sri** [comment]
@shohelbuddyboss Thanks for checking this. It works.
