### ISSUE TITLE
RTL bug: Cropping image was not working properly

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1253]
**Describe the bug**
Cropping image in avatar and cover photo with RTL language activated conflicting the issue.

**To Reproduce**
1. Go to any page that you can edit an image like profile picture
2. Try upload new image and crop it.
3. See Error

**Expected behavior**
Cropping images should work properly.

**Screenshots**
https://storyxpress.co/video/kcxhdkvxwrkyc25nk

**Support ticket links**
https://secure.helpscout.net/conversation/1227420482/83627?folderId=3709081

**Comment by logicallayer** [comment]
This is a major issue as it is an important functionality without reasonable work around. Can we raise the priority please?

**Comment by marienel21** [comment]
Bug is not reproducible on the latest version of the Platform.

**Comment by chetansatasiya** [comment]
As per the @marienel21 comment in the latest version, it can't reproducible so closing this. Feel free to reopen if the issue coming with other steps.
