### ISSUE TITLE
Password reset email shows in English when the site language is Deutsch

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1261]
**Describe the bug**
Password reset email shows in English when the site language is Deutsch when the BuddyBoss Platform is active. 

**To Reproduce - Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/36bddeaa3f72450ab3915cc1db9971f8

**Expected behavior**
Password Reset Email should be in Deutsch

**Support ticket links**
https://secure.helpscout.net/conversation/1233782751/84715

**Comment by KartikSuthar** [comment]
@imehedidev I have checked for the issue, email content is translatable by the plugin.
you can install the loco translation plugin and check its works:
http://prntscr.com/tr4jk1
http://prntscr.com/tr4iok

**Comment by chetansatasiya** [comment]
@imehedidev We are closing this issue now and please update the customer which @KartikSuthar suggested above.
