### ISSUE TITLE
BBPress shortcodes not working for non-admins

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1262]
**Describe the bug**
Shortcode from https://codex.bbpress.org/features/shortcodes/ are not working for non-admin users.
For admins, this is working fine

**To Reproduce**
I used the bbps-single-topic shortcode in this test, you need to create a sample discussion for this
1. Create a page
2. insert shortcode from BBPress
3. As an Admin, view page on front end
4. Login as a subscriber and view page again, see error

**Expected behavior**
BBPress shortcode should render both for admin and non-admins

**Screenshots**
![Admin-backend-view](https://user-images.githubusercontent.com/58522224/88479960-88be6300-cf85-11ea-9f08-400fa4f208ec.JPG)
![Admin-frontend-view](https://user-images.githubusercontent.com/58522224/88479965-8c51ea00-cf85-11ea-96f2-12a90b85e606.JPG)
![Subscriber-frontend-view](https://user-images.githubusercontent.com/58522224/88479982-adb2d600-cf85-11ea-8e95-3cf108bd2efc.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1235072565/84908

**Comment by KartikSuthar** [comment]
@emmanoctaviano I think, it's a duplicate issue.
We have already fixed with the PR: https://github.com/buddyboss/buddyboss-platform/pull/714
Please check and close the issue if fixed.

**Comment by emmanoctaviano** [comment]
closing this card. issue is already fixed
