### ISSUE TITLE
Extended profile profile name + last ame fields are showing blanks for those account create on woo-commerce checkout page

### ISSUE THREAD

**Issue by eat-code** [buddyboss/buddyboss-platform#1263]
**Describe the bug**
Issue: The client is using woo commerce, woocommerce-subscription, and buddy boss-platform. He set up woo-commerce to allow for creating an account at checkout but the extended profile fields are showing blanks.

**To Reproduce**
1. Allow customers to create an account during checkout in Woocomerce setting
2. Buy a product without account and create an account during checkout
3. See the users list and edit one of them then click on the Extended profile and saw their profile name and last name are missing.

**Expected behavior**
During woocommerce checkout, those accounts are created should merge with extended profile field.

**Screenshots**
https://prnt.sc/tp2aph

**Support ticket links**
https://secure.helpscout.net/conversation/1232429625/84518?folderId=3955985

**Comment by KartikSuthar** [comment]
Hey @eat-code , Can you please check this issue with the latest version(v1.4.7)?
We have already fixed this issue in PR: https://github.com/buddyboss/buddyboss-platform/pull/1165
