### ISSUE TITLE
BB REST - Upload Member Cover from Windows OS : Directory error

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1268]
**Describe the bug**
I try to use BB REST API to upload a member's cover on my Windows development machine but it fails. 

`POST {{host}}/wp-json/buddyboss/v1/members/{{user-id}}/cover`

```
{
  "code": "bp_rest_attachments_user_cover_upload_error",
  "message": "The cover image directory is not valid.",
  "data": {
    "status": 500
  }
}
```
The problem seems to be located in the file trait-attachments.php (line 89).

```
if ( 0 !== validate_file( $cover_dir ) || ! is_dir( $cover_dir ) ) {
```
should be 

```
if ( 1 === validate_file( $cover_dir ) || ! is_dir( $cover_dir ) ) {
```
Then, you will also see another error 

```
{
  "code": "bp_rest_attachments_user_cover_upload_error",
  "message": "You have selected an image that is smaller than recommended. For better results, make sure to upload an image that is larger than 0px wide, and 0px tall.",
  "data": {
    "status": 500
  }
}
```

Ps : I think the same issue occurs with Group Cover.

Regards,
Didier

**Comment by sourabhmatolia** [comment]
@ExoGeek

Issue created above is released in Buddyboss Platform v1.5.0.

Find platform v1.5.0 release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-8/

Please update the plugin to see the latest changes.

Thank you.
