### ISSUE TITLE
Profile Search: Filter result function not working properly

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1270]
**Describe the bug**
Two members with same input in City (SingleLineText), State/County/Territory (SingleLineText), and Make (Dropdown) only one is showing in result.

**To Reproduce**
1. Go to 'https://www.staging2.meetupmoto.com/members/
2. Try adding in filter results City = Fort, State/County/Territory = Florida, Bike Make = Harley Davidson
3. Enter the result.

**Expected behavior**
The two members should be seen in filter result.

**Screenshots**
FIlter Result:​
​https://prnt.sc/tpjwrm
​
​1st Member:
​https://prnt.sc/tpjxax
​2nd Member:
​https://prnt.sc/tpjxoo

**Support ticket links**
https://secure.helpscout.net/conversation/1232815175/84574?folderId=3943005

**Jira issue** : [PROD-931]

[PROD-931]: https://buddyboss.atlassian.net/browse/PROD-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by marienel21** [comment]
I can't replicate this issue on the latest version of the Platform. 
![image](https://user-images.githubusercontent.com/77659570/128364858-f4999f86-2ef1-429f-9049-7490f265d43a.png)

**Comment by jrbuddyboss** [comment]
https://www.loom.com/share/b7394471bf3b479cbc1b4afbbc2e1f8c
