### ISSUE TITLE
Privacy is not working for Albums photos. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1272]
**Describe the bug**
If you create an album with privacy 'Only me' , the photos are visible to others on News feed and Photos page. 

**To Reproduce**
https://www.loom.com/share/22a8d8a9d3ee415bb3c47300b9d57017

**Expected behavior**
The 'Only me' setting should work. 

**Screenshots**
https://www.loom.com/share/22a8d8a9d3ee415bb3c47300b9d57017

**Support ticket links**
https://secure.helpscout.net/conversation/1237676465/85333?folderId=3701249

**Comment by chetansatasiya** [comment]
@Anve-sri I am closing this issue as it's not reproducible in `dev` and `master` and also in demo see this video I did the same thing and it's working totally fine https://www.loom.com/share/fcbf3d924fb547969450ddbadee1985f
