### ISSUE TITLE
Post Attributes = 0 - under Profile Types

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1274]
**Describe the bug**
Post Attributes = 0 showing under the Profile Types. 

**To Reproduce**
1. Go to 'BuddyBoss > Profiles > Profile Types'
2. Click on 'Add New' and check.

**Expected behavior**
It shouldn't be there.

**Screenshots**
https://prnt.sc/tq0t93

**Support ticket links**
https://secure.helpscout.net/conversation/1235167991/84922

**Jira issue** : [PROD-930]

[PROD-930]: https://buddyboss.atlassian.net/browse/PROD-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chetansatasiya** [comment]
@eisenwasser @imehedidev 

This is not an issue that post attribute will help you to display order the member types in frontend see here https://prnt.sc/tszr74

**Comment by eisenwasser** [comment]
@chetansatasiya 

That is not obvious at all. Why would we have an option called "Post Attributes" that sets the order? Why not call it something more intuitive and add helper text explaining what it does? This is not a satisfactory response to Mehedi or the customer. The customer is correct that this is confusing and not in any way obvious or discoverable what this option does.
