### ISSUE TITLE
BP REST Media Endpoint does not support additional REST fields

### ISSUE THREAD

**Issue by sjregan** [buddyboss/buddyboss-platform#1275]
**Describe the bug**
Fields added to the 'bp_media' object type via `register_rest_field()` are not present in REST response.
The `prepare_item_for_response` function does not call `add_additional_fields_to_object()`

**To Reproduce**
1. Register a REST field for bp_media
2. Send request to endpoint
3. View response

**Expected behavior**
The registered REST field to be present in the REST response.

**Comment by sjregan** [comment]
@KartikSuthar @chetansatasiya I don't believe the commit fixes this issue, `update_additional_fields_for_object()` has been added for `create_item` and `update_item` but `add_additional_fields_to_object` has not been added to `prepare_item_for_response`.

**Comment by KartikSuthar** [comment]
Thanks, @sjregan I reopen the issue and will update you once fix.

**Comment by sourabhmatolia** [comment]
@sjregan 


Issue created above is released in Buddyboss Platform v1.5.1.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-1/

Please update the plugin to see the latest changes.

Thank you.
