### ISSUE TITLE
LearnDash Group Memberships - BB Platform conflict

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#1278]
**Describe the bug**
When you have Learndash & BuddyBoss group integration enabled. If Learndash group is paid then you will join the group via BuddyBoss group then you will join automaitaclly Learndash Group without paying anything and access the course.

**To Reproduce**
1. Enable the integration of Learndash & BuddyBoss LearnDash groups → Social groups & Social groups → LearnDash groups sync via BuddyBoss > Integration > Learndash
2. Create a Paid Group in Learndash and it will create a group in BuddyBoss group as well.
3. You are able to join the LearnDash group without paying anything via BuddyBoss groups

**Expected behavior**
You should not able to join the group without paying.

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

**Membership Accepting**
When group is public. public groups things will assessable without any restriction. it should be private. 
Also we can access the course even group public is paid.

**Issue video:**
https://www.loom.com/share/fde0da7b3b234f3eac8ec027655632d8
https://prnt.sc/tqy5su

CC @ankitguptaindia
