### ISSUE TITLE
Display "Powered By GIPHY" attribution marks where the Giphy API is utilized

### ISSUE THREAD

**Issue by KartikSuthar** [buddyboss/buddyboss-platform#1283]
**Is your feature request related to a problem? Please describe.**
When moving from beta key to production key 'Giphy' asks to clearly display "Powered By GIPHY" attribution marks where the API is utilized.

**Describe the solution you'd like**
https://support.giphy.com/hc/en-us/articles/360035158592-What-conditions-does-my-app-project-need-to-meet-in-order-to-get-a-production-API-Key-

**Describe alternatives you've considered**
http://prntscr.com/tqxmgf

**Support ticket links**
https://secure.helpscout.net/conversation/1212508305/81000?folderId=3701249

**Jira issue** : [PROD-929]

[PROD-929]: https://buddyboss.atlassian.net/browse/PROD-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AiratHalitov** [comment]
After that could you add an instruction how to apply for a GIPHY Production API Key?

**Questions from GIPHY:**

- Please describe your app briefly and how you plan to use GIPHY inside your app.
- Which API does your app utilize? (Search or Search + Upload)
- What categories best describe your app?

Link to application form: `https://developers.giphy.com/dashboard/apply/APP_ID`

**Comment by nosfatsug** [comment]
Funny how adding gifs from giphy is standard, but cannot work in production without the attribution...seems like this would have been addressed quicker.

**Comment by rolloverbond** [comment]
+1 this enhancement - also we're currently using the beta version but the size of the GIFs is absolutely insane... they take up the whole screen for users. A way to resize these would be ideal.
