### ISSUE TITLE
Mentioning a member on a blog post is not working on subsite

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1293]
**Describe the bug**
When you mention someone on a blog post which is not a member of the current subsite it is not being linked on their profile, but using BuddyPress it works.

**To Reproduce**
1. On a multisite setup, network activate the BuddyBoss Platform, then go to a subsite.
2. create a new post and mention someone on your post that is not a member of the current subsite.
3. Go to the blog page you just posted and notice it is not linked to its profile page

**Expected behavior**
Being mentioned on a blog post even you are not a member of the current site should still link to your profile.

**Screencast**
https://cutt.ly/QdeZSNS

**Screenshots**
![BuddyPress](https://user-images.githubusercontent.com/58522498/89083110-8fecd300-d3c2-11ea-82cb-9d87d4614157.jpg)
![platform](https://user-images.githubusercontent.com/58522498/89083113-91b69680-d3c2-11ea-82bf-41c92f31ce48.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1190459338/77136/

**Jira issue** : [PROD-928]

[PROD-928]: https://buddyboss.atlassian.net/browse/PROD-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Dreamsync** [comment]
Wow that's amazing. I didn't know Buddypress did that. 

There's so much potential for Buddyboss if they embrace the social blogging network paradigm, rather than just focusing on single-site networks.
