### ISSUE TITLE
Discussions - Replying with an image bug

### ISSUE THREAD

**Issue by bb-ralph** [buddyboss/buddyboss-platform#1294]
**Describe the bug**
Inside a particular group > Discussions > when you create a reply with an image, first reply is fine, but when you reply once again, the image you uploaded on your last reply is still there and it causes a bug.

**To Reproduce**
Please see screencast: https://screenrec.com/share/X8fpNyBFtm

**Expected behavior**
After replying with an image, it should reset the reply popup not just the description but also the image that was previously uploaded

**Support ticket links**
https://secure.helpscout.net/conversation/1236738362/85193

**Comment by bb-ralph** [comment]
Another issue found that is related to this ticket, see screencast: https://screenrec.com/share/bgFKm1ABEO

**Comment by marienel21** [comment]
Bug - image showing twice in Group discussion reply is no longer reproducible in the latest version of the product. 
![image](https://user-images.githubusercontent.com/77659570/125613959-c116a811-b140-47e6-9981-9eb38d22a5d4.png)
