### ISSUE TITLE
$display_name is not initialized in some installations

### ISSUE THREAD

**Issue by shanebp** [buddyboss/buddyboss-platform#1297]
In `buddyboss-platform\bp-xprofile\bp-xprofile-functions.php`
In `function bp_xprofile_get_member_display_name`

`$display_name` is not initialized.  Some sites use non-standard user names.  So it can fall thru the switch statement and then throw a Notice in the filter hook at the bottom. 
`return apply_filters( 'bp_xprofile_get_member_display_name', trim( $display_name ), $user_id );`

The fix is simple.  Just initialize `$display_name` before the switch statement. 

PR created.

**Comment by sourabhmatolia** [comment]
@shanebp 

Issue created above is released in Buddyboss Platform v1.4.8.

**Find platform v1.4.8 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-8/

Please update the plugin to see the latest changes.
