### ISSUE TITLE
Using emoji, having an unexpected link preview

### ISSUE THREAD

**Issue by bb-ralph** [buddyboss/buddyboss-platform#1300]
**Describe the bug**
Whenever you write something in activity feed, timeline or activity feed inside a group with an emoji, it unexpectedly show a link preview.

**To Reproduce**
1. Write something on activity feed, timeline, or activity feed inside a group with an emoji, it will show a link preview.

**Expected behavior**
It should not have a link preview.

**Screenshots**
https://drive.google.com/file/d/1rRX9nd5lhAoR8YGeg0nZVu984LY8qG24/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1240911233/85904

**Comment by felipeganash** [comment]
Video preview here: https://www.loom.com/share/e71087f7a47c45bb92523ad632c9d8b8

**Comment by marienel21** [comment]
bug no longer reproducible on the latest version of the product
