### ISSUE TITLE
Show relevant Feed - at the global news feed page

### ISSUE THREAD

**Issue by shohelbuddyboss** [buddyboss/buddyboss-platform#1311]
**Is your feature request related to a problem? Please describe.**

In the global news feed page, there should be an option to show only content relevant to the users.

**Describe the solution you'd like**

BuddyBoss Settings > Activity > Add an option (Show Relevant Feed)

**Support ticket links**

https://www.facebook.com/groups/buddyboss/permalink/1004572619977580/

**Suggestion From Michael**

https://www.loom.com/share/67989c746c9248cd9ffe38472ec5f4fd

**Comment by sourabhmatolia** [comment]
@shohelbuddyboss 

When Relevant activity feed settings enabled then make sure we show Posts relevant to logged-in members always.

These are all the relevant posts category for the logged-in member:

- Posts logged-in user creates
- Posts from logged-in user connections
- Posts from people logged-in user following
- Posts from logged-in user Groups
- Posts from logged-in user Subscribed Forums
- Posts from logged-in user Subscribed Discussions
- Posts logged-in user @mentioned

Please confirm if we are already considering all categories shared above. 

Thanks.

**Comment by shohel** [comment]
@sourabhmatolia 

The related feed will show below things.

- Posts logged-in user creates
- Posts from logged-in user connections
- Posts from people logged-in user following
- Posts from logged-in user Groups
- Posts logged-in user @mentioned


I will check with the subscriber forum and reply

**Comment by ExoGeek** [comment]
@shohelbuddyboss  Concerning "Posts from logged-in user Groups". Do I well understand what it means : Show feeds from groups in which the current logged-in user is a member/moderator/organizer ?

Because for the moment, any feeds from public group is displayed on the global activity feed of the user (even if he is not a member of that public group).
