### ISSUE TITLE
Changing the pagination of activity on admin dashboard is not working

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1314]
**Describe the bug**
When changing the pagination setting of activity on the admin dashboard, it returns to the default 20 items per page.

**To Reproduce**
1. Go to Admin dashboard > BuddyBoss > Activity
2. Open the screen options and change the pagination value, notice that it returns to the default value after saving.

**Screenshots**
![pagination](https://user-images.githubusercontent.com/58522498/89458164-26d9d680-d799-11ea-9e11-7bd32196cb44.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1246360658/86844/
https://secure.helpscout.net/conversation/1249498858/87385/

**Comment by janakkaneriya007** [comment]
@ayron-paul 
I have checked this on our demo site and it's working fine. Follow below video.
https://www.loom.com/share/86bf71c5edfa43b8a893e44a3684b063
