### ISSUE TITLE
Zoom: Gutenberg Schedule Meeting Host/Participant not syncing

### ISSUE THREAD

**Issue by johnraybuddyboss** [buddyboss/buddyboss-platform#1320]
**Describe the bug**
When adding a new zoom block in gutenberg editor, the schedule meeting host and participant enabling and disabling is not syncing properly.

**To Reproduce**
1. Create new page and insert new zoom block with gutenberg.
2. View the created page.
3. Click manage meeting details.
4. Errors was when the host and participant both ON in zoom account setting, only the host will be ON while the participant stay off.

**Expected behavior**
Created zoom meeting with host and participant ON should sync between gutenberg block and zoom account setting.

Notice: Inside group page, there is a sync button https://prnt.sc/tvngg9 that update the setting between the page and zoom account. Might be useful to have also in gutenberg block?

**Screenshots**
Gutenberg
https://prnt.sc/tvnnnb
Zoom Account
https://prnt.sc/tvno3r

Screen Recording:
https://drive.google.com/file/d/1XWYalcqszhr4h-Wgwx2CTUMdxcXLwXU1/view?usp=sharing
https://drive.google.com/file/d/1vZ6yqipwpnys1f5WHJA3XY3u1iHhVKJR/view

**Support ticket links**
https://secure.helpscout.net/conversation/1245278436/86650?folderId=3709080

**Comment by mehulkaklotar** [comment]
https://github.com/buddyboss/buddyboss-platform-pro/issues/65
