### ISSUE TITLE
Gamipress - Achievement Description not showing in Activity feed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1324]
**Describe the bug**
When a user is awarded an Achievement, the Badge show on activity feed but the description does not

**To Reproduce**
Issue can be replicated in demo
1. IN WP Dashboard > Go to user profile and click edit
2. Add an achievement for that user
3. Go to activity feed

**Expected behavior**
Achievement description should show

**Screenshots**
https://drive.google.com/file/d/19U7-nNv5yfBsh3ameOGt1lHOKujhglZR/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1247621896/87075
https://secure.helpscout.net/conversation/1290392017/100218

**Comment by amincdev** [comment]
@emmanoctaviano With the latest update of Gamipress - BuddyBoss integration plugin, This issue is fixed. Can you please confirm and update the customers in the above tickets?

**Comment by marienel21** [comment]
![image](https://user-images.githubusercontent.com/77659570/125641322-38d31be2-8940-44de-86ef-eb2d1ef0ff06.png)

**Comment by emmanoctaviano** [comment]
@amincdev tested and this works. waiting for CX reply
