### ISSUE TITLE
Smileys in the mobile view are not fully shown when you write in Message and Forum.

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1325]
**Describe the bug**
Emoji/smileys in the mobile view are not fully shown when you write in Messag, Forum, and also group discussion.

**To Reproduce**
1. Go to Forum or Group discussion from mobile and try to insert Emoji / Smiley

**Expected behavior**
Need to be responsive in the Mobile devices.

**Screenshots**
https://prnt.sc/twlnca
https://prnt.sc/twlmkj

**Support ticket links**
https://secure.helpscout.net/conversation/1249392263/87368/

**Comment by amincdev** [comment]
Closing this issue, It is created in theme : https://github.com/buddyboss/buddyboss-theme/issues/1053
