### ISSUE TITLE
Without admin no one can't post " link " on activity timeline

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1326]
**Describe the bug**
If you log in as a subscriber or any other role without admin then can't post a link on activity timeline. It's show

There was a problem posting your update. Please try again.

**To Reproduce**
1. Sign in as a subscriber or any other role without admin
2. Try to post a link on the activity timeline

**Expected behavior**
Other user roles can also post the link

**Screenshots**
https://prnt.sc/twyaqi

**Support ticket links**
https://secure.helpscout.net/conversation/1244651353/86536?folderId=3955985

**Comment by jvmison** [comment]
I'm experiencing the same problem. If you are signed in as admin but select "View as" a non-admin, it will allow you to post I noticed.

**Comment by jvmison** [comment]
Can we set to high priority? this seems to be a common thing that people use the activity feed for and without a fix for this, it could affect the userbase

**Comment by jeremystory1** [comment]
I ditto the comment above.  Seems that not being able to post a link should be a high priority.

**Comment by janakkaneriya007** [comment]
@jakir-git @jvmison @jeremystory1 

Activity follows default discussion settings for posting link in activity and comments to prevent spams. You can change that settings here: https://prnt.sc/uvx7vf

**Comment by courage2change** [comment]
I've changed the discussion settings to allow 20 links, but still getting 'There was a problem posting your update. Please try again' for non-admin users - is there anything else that could be the issue?
