### ISSUE TITLE
Group name is not syncing between BuddyBoss and LearnDash.

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1327]
**Describe the bug**
Group name is not syncing between BuddyBoss Social Groups and LearnDash. If you change the group's name from the frontend, it is not syncing in LearDash Group at the backend.

**To Reproduce**
1. Make sure that you activated  **Enable group sync functionality FROM BuddyBoss Social Groups TO LearnDash Groups** and **Enable group sync functionality FROM LearnDash Groups TO BuddyBoss Social Groups**.
(BuddyBoss > Integration > LearnDash)
2. Create a Group in LearnDash LMS > Groups. Example name: "Group Sync"
3. Go to the frontend, go to Groups page. Then, select the Group Sync, go to Manage, and try to edit the name.

https://prnt.sc/tx36bb
http://prnt.sc/tx36e6

4. Go back at the backend, go to LearnDash > Groups. You will see that it still has the old name which in my testing "Group Sync" instead of the new name "Sync this Groups chochocho".

https://prnt.sc/tx36jr

**Expected behavior**
Group name should sync

**Support ticket links**
https://secure.helpscout.net/conversation/1247016391/86971

**Comment by bstreet123456789** [comment]
+1 This would be very useful please :)

**Comment by mattttis** [comment]
+1, this would be extremely useful :)

**Comment by mattttis** [comment]
Hi it's been a while since this has been updated. Are there any plans for fixing this bug?

**Comment by bstreet123456789** [comment]
Thank you so much everyone!!!

**Comment by sourabhmatolia** [comment]
@bstreet123456789 @mattttis

Issue mentioned above is released in BuddyBoss Platform v1.5.7

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-7/

Please update the plugin to see the latest changes.

Thank you.
