### ISSUE TITLE
BB REST API : Get Activities of a user_id

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1329]
**Describe the bug**
I try to list activities of a specific user_id with the request below. But that request returns too many activities (I can't filter activities specific of a certain user).

`GET {{host}}/wp-json/buddyboss/v1/activity?user_id=12`

What I want to achieve is to retrieve the same activities listed on the page : http://buddyboss.localhost/members/bb-neville/activity/

Here are the parameters used by this page when calling the function get in the file class-bp-activitiy-activity.php. As you can see, the field "scope" contains 2 parameters. But because this field is a "String" in the BB REST API, we can't request the same activities from the REST API.

```
Array
(
    [page] => 1
    [per_page] => 20
    [max] => 
    [sort] => DESC
    [privacy] => 
    [search_terms] => 
    [meta_query] => 
    [date_query] => 
    [filter_query] => 
    [filter] => Array
        (
            [user_id] => 12
            [object] => 
            [action] => 
            [primary_id] => 
            [secondary_id] => 
            [offset] => 
            [since] => 
        )

    [scope] => just-me,mentions
    [display_comments] => threaded
    [show_hidden] => 
    [exclude] => 
    [in] => 
    [spam] => ham_only
    [update_meta_cache] => 1
    [count_total] => 
    [fields] => all
)
```

In order to correct this issue, I suggest 2 modifications :

1) Modify the scope parameter to become an array (in place of a String)
2) When user_id is set and scope is not set (via the rest api parameters). Automatically set scope = [just-me,mentions]

Regards,

**Comment by KartikSuthar** [comment]
@ExoGeek you can try this parameter 
`user_id=12` as well the `scope=just-me`

`GET {{host}}/wp-json/buddyboss/v1/activity?user_id=12&scope=just-me`

It will return same as the web.

**Comment by ExoGeek** [comment]
@KartikSuthar With scope=just-me, there're some missing activities (mention)

1. Go to the profile page of your friend (/members/bb-neville/activity/)
2. Create an activity (write something to neville)
3. REST Request does not contain the activity created on 2 BUT that activity is displayed on /members/bb-neville/activity/ page)

`GET {{host}}/wp-json/buddyboss/v1/activity?user_id=12&scope=just-me`

**Comment by dawnerd** [comment]
I'm seeing this as well. When making the request as a logged in user, the user_id param doesn't work and includes other users' posts. If I make the request without being logged in it's being filtered correctly.

**Comment by baltagih2** [comment]
> I'm seeing this as well. When making the request as a logged in user, the user_id param doesn't work and includes other users' posts. If I make the request without being logged in it's being filtered correctly.

Same here

**Comment by meetmakadiya** [comment]
@ExoGeek @dawnerd @baltagih2 
cc: @KartikSuthar 
I checked with the latest version and not replicated the issue. steps to check the issue are as follows.
1. Go to the profile page of a friend.
2. Create an activity.
3. check the Rest API  request with login and without login and activity include on api.
with-login: http://i.imgur.com/4bNmvkt.png
without-login: http://i.imgur.com/Q5t0eea.png

let me know if I miss anything.
Thanks

**Comment by meetmakadiya** [comment]
I believe we can already close this issue for now. If this issue comes up again, feel free to comment on the details here to reopen this issue.

**Comment by dawnerd** [comment]
Still happening in version 1.7.9

### Without Auth
```
curl --request GET \
  --url 'https://<snip>/wp-json/buddyboss/v1/activity?component=activity&user_id=45&per_page=1&scope=just-me&page=1'
```
```
[
  {
    "user_id": 45,
    "name": "FTTroy",
    "component": "activity",
    "content": {
      "rendered": "<p>Testing score notif comments<\/p>\n"
    },
    "date": "2021-08-03T17:16:21",
    "id": 269,
    "link": "https:\/\/<snip>\/news-feed\/p\/269\/",
    "primary_item_id": 0,
    "secondary_item_id": 0,
    "status": "published",
    "title": "<a href=\"https:\/\/<snip>\/members\/troy\/\">FTTroy<\/a> posted an update",
    "type": "activity_update",
    "favorited": false,
    "can_favorite": true,
    "favorite_count": "1",
    "can_comment": true,
    "can_edit": false,
    "can_delete": false,
    "content_stripped": "Testing score notif comments",
    "privacy": "public",
    "activity_data": {
      "can_edit_privacy": true,
      "album_id": 0,
      "group_id": 0,
      "group_name": "",
      "folder_id": 0,
      "profile_video": false,
      "group_video": false,
      "profile_media": false,
      "group_media": false,
      "profile_document": false,
      "group_document": false
    },
    "feature_media": "",
    "comment_count": 2,
    "user_avatar": {
      "full": "https:\/\/www.gravatar.com\/avatar\/51990b649e492316f49a0db7fbfd56b1?s=150&#038;r=g&#038;d=mm",
      "thumb": "https:\/\/www.gravatar.com\/avatar\/51990b649e492316f49a0db7fbfd56b1?s=50&#038;r=g&#038;d=mm"
    },
    "can_report": false,
    "reported": false,
    "report_button_text": "Report Post",
    "report_type": "Post",
    "bp_media_ids": null,
    "media_gif": null,
    "comment_upload_media": false,
    "bp_videos": null,
    "bp_documents": false,
    "comment_upload_document": false,
    "_links": {
      "self": [
        {
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/activity\/269"
        }
      ],
      "collection": [
        {
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/activity\/"
        }
      ],
      "user": [
        {
          "embeddable": true,
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/members\/45"
        }
      ],
      "favorite": [
        {
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/activity\/269\/favorite"
        }
      ]
    }
  }
]
```

### With Auth

```
curl --request GET \
  --url 'https://<snip>/wp-json/buddyboss/v1/activity?component=activity&user_id=45&per_page=1&scope=just-me&page=1' \
  --header 'Authorization: Bearer <snip>'
```

```
[
  {
    "user_id": 66,
    "name": "marang1",
    "component": "activity",
    "content": {
      "rendered": "<p>Testing usernames<\/p>\n"
    },
    "date": "2021-10-07T16:41:34",
    "id": 617,
    "link": "https:\/\/<snip>\/news-feed\/p\/617\/",
    "primary_item_id": 0,
    "secondary_item_id": 0,
    "status": "published",
    "title": "<a href=\"https:\/\/<snip>\/members\/marang\/\">marang1<\/a> posted an update",
    "type": "activity_update",
    "favorited": false,
    "can_favorite": true,
    "favorite_count": 0,
    "can_comment": true,
    "can_edit": false,
    "can_delete": false,
    "content_stripped": "Testing usernames",
    "privacy": "public",
    "activity_data": {
      "can_edit_privacy": true,
      "album_id": 0,
      "group_id": 0,
      "group_name": "",
      "folder_id": 0,
      "profile_video": false,
      "group_video": false,
      "profile_media": true,
      "group_media": true,
      "profile_document": false,
      "group_document": false
    },
    "feature_media": "",
    "comment_count": 0,
    "user_avatar": {
      "full": "https:\/\/<snip>\/wp-content\/uploads\/avatars\/66\/610cf87eb4aef-bpfull.jpg",
      "thumb": "https:\/\/<snip>\/wp-content\/uploads\/avatars\/66\/610cf87ec7387-bpthumb.jpg"
    },
    "can_report": true,
    "reported": false,
    "report_button_text": "Report Post",
    "report_type": "Post",
    "bp_media_ids": null,
    "media_gif": null,
    "comment_upload_media": true,
    "bp_videos": null,
    "bp_documents": false,
    "comment_upload_document": false,
    "_links": {
      "self": [
        {
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/activity\/617"
        }
      ],
      "collection": [
        {
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/activity\/"
        }
      ],
      "user": [
        {
          "embeddable": true,
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/members\/66"
        }
      ],
      "favorite": [
        {
          "href": "https:\/\/<snip>\/wp-json\/buddyboss\/v1\/activity\/617\/favorite"
        }
      ]
    }
  }
]
```

@meetmakadiya I noticed you used accessToken in your request. Perhaps this is an issue with how requests are authenticated.  In any case something weird is going on. I'm doing some more digging on our end to see what could be causing it.

**Comment by dawnerd** [comment]
Further digging finds:

Logged what `$args` is from the `bp_rest_activity_get_items_query_args` filter. When not logged in `$args['scope']` matches the url param but when logged in scope changes to `just-me,mentions,friends,following` which I think is why the others are showing up.

Is there a reason scope gets changed like that?
