### ISSUE TITLE
Duplicating an event leads to 404 page not found

### ISSUE THREAD

**Issue by bb-ralph** [buddyboss/buddyboss-platform#1330]
**Describe the bug**
Duplicating an event leads to 404 page not found when clicked in news feed page.

**To Reproduce**
Follow the screencast to reproduce: https://www.loom.com/share/d710097ff21b4755b6d3e9554fb253a5

**Expected behavior**
It should post it in the news feed but when clicked it should not redirect the user to page not found, unless deleted.

**Support ticket links**
https://secure.helpscout.net/conversation/1227442409/83630

**Comment by chetansatasiya** [comment]
@bb-ralph I am closing this issue as it's not a platform issue.

**Event Manager** itself creating a event activity on the plugin end and adding a wrong URL into the activity table https://prnt.sc/v9wq7p and causing the 404.

If you disable the actvity create on **Event Manager** plugn by placing this code `remove_filter('em_event_save','bp_em_record_activity_event_save', 10, 2);` into your theme functions file and activate the plaftom activity by checking this settings https://prnt.sc/v9wsbl and it will work without any issue and it will not cause 404.

Let me know if you still have any questions.
