### ISSUE TITLE
BB REST API : Groups Endpoint - Field can_join is always false for Private Groups

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1339]
**Describe the bug**
When you make a request to the Group's endpoints, the field "can_join" is always false for Private Groups.

`GET {{host}}/wp-json/buddyboss/v1/groups`
`GET {{host}}/wp-json/buddyboss/v1/groups/103`

In the method "bp_rest_user_can_join" (located in the file class-bp-rest-groups-endpoint.php), you retrive the meta data of the group : "_bp_group_type_enabled_member_type_join". But this meta data is not set up when you create a new group (at least when you create a group without Group Type and from the website)

**To Reproduce**
1. User1 : Create a group from the website (let all default settings value)
2. User2 : Retrieve group detail via a REST API request.
3. User2 : See if can_join = true

**Expected behavior**
If group is private and Group Type is configured to let user join the group, return true. 

Regards,

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Release update shared here: 
https://github.com/buddyboss/buddyboss-platform/issues/1268#issuecomment-686277286

Thanks.
