### ISSUE TITLE
BB REST API : Groups Details Endpoint - Count field do not include hidden groups

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1341]
**Describe the bug**
When you make a REST API Call to the endpoint "Groups Details", the fields "tabs->personal->count" and "tabs->all->count" do not take into account hidden groups.

`GET {{host}}/wp-json/buddyboss/v1/groups/details`

**To Reproduce**
1. Create a hidden group
2. REST API "/groups/details"
3. See "count" fields and compare them to http://buddyboss.localhost/groups/

**Expected behavior**
A solution could be to add request parameters to the endpoint "/groups/details" (see function groups_get_groups in bp-groups-functions.php)

```
$defaults = array(
	'include'            => false,          // Only include these specific groups (group_ids).
	'exclude'            => false,          // Do not include these specific groups (group_ids).
	'group_type'         => '',             // Array or comma-separated list of group types to limit results to.
	'group_type__in'     => '',             // Array or comma-separated list of group types to limit results to.
	'group_type__not_in' => '',             // Array or comma-separated list of group types that will be excluded from results.
	'show_hidden'        => false,          // Show hidden groups to non-admins.
	'status'             => array(),        // Array or comma-separated list of group statuses to limit results to.
);
```

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Release update shared here: 
https://github.com/buddyboss/buddyboss-platform/issues/1268#issuecomment-686277286

Thanks.
