### ISSUE TITLE
PHP 7.* above & WordPress 5.5 Compatiblity

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#1344]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by AiratHalitov** [comment]
@chetansatasiya 
Hi!
Is buddyboss-platfrorm compatible with WordPress 5.5? 
When will buddyboss-platfrorm v1.4.9 be released?

**Comment by AiratHalitov** [comment]
Fixed in v1.4.9
