### ISSUE TITLE
Custom translation file is not being prioritized in Loco Translate

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1352]
**Describe the bug**
When there is an existing custom translation file (like French, German, and Hungarian) which is located on the safe location recommended by Loco Translate -`wp-content/languages/loco/` it is not being prioritized, therefore, the prebuilt translations in the plugin are the ones being loaded first, overriding the translation made by the user.

**To Reproduce**
1. Go to Loco Translate > plugins > BuddyBoss Platform
2. Add new translation file that has a prebuilt in the plugin like French, German, or Hungarian
3. Make sure that the new translation file is in the safe location - `wp-content/languages/loco/` and try to translate any strings.
4. Switch your site language and notice that your translations do not take effect.

**Expected behavior**
The safe location of Loco Translate should be loaded first.

**References**
- https://localise.biz/wordpress/plugin/faqs/custom-folder#step3
- https://localise.biz/wordpress/plugin/manual/msginit#order

**Screenshots**
![translation1](https://user-images.githubusercontent.com/58522498/90206795-24215600-de17-11ea-895c-cb3a8854a969.jpg)

**Suggested solution** 
On the fie `\wp-content\plugins\buddyboss-platform\bp-core\bp-core-functions.php` at line 2350, add the line below:
- `trailingslashit( WP_LANG_DIR . '/loco/plugins')`

![suggestion](https://user-images.githubusercontent.com/58522498/90206819-34d1cc00-de17-11ea-806e-f6a4f925aa5e.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1250988652/87654

**Comment by KartikSuthar** [comment]
Hey @ayron-paul 
As discussed with @mehulkaklotar and @chetansatasiya , We don't need to add these codes into the platform.
Loco translator plugin provides the ability to Relocate the file. 
http://prntscr.com/u21a1b
http://somup.com/cYjqic6m7o
you can use this.

**Comment by ayron-paul** [comment]
Hi @KartikSuthar,

Thank you for looking into this.

As mentioned above, the issue persists for the existing custom translation files (like French, German, and Hungarian). Relocating the custom translation file in the author directory is not possible, it will show this kind of error, https://i.ibb.co/FqZBHSf/plugin.jpg. It is also not recommended, as mentioned on the tutorial (https://cutt.ly/ofup05v) because once we release an update it will be overridden.

There is another solution, to relocate the translation file to the system language directory, but it shows a notice that the custom translation files might get removed once WordPress will be updated, please see these https://i.ibb.co/wLzJ6ZQ/system2.jpg and https://i.ibb.co/2s9vnb8/system.jpg. Can you confirm if this solution will be okay and will not have any issues once the WordPress will have an update?

Thanks!

**Comment by ayron-paul** [comment]
Hi @dipskakadiya, thank you for confirming, I will inform the customer.
