### ISSUE TITLE
BB REST API : Media Endpoint - Order is always DESC because of a upper-lower case mismatch

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1353]
**Describe the bug**
When you make a BB REST API request to the endpoint "media", the filter "order" is always set to desc because of an issue with upper and lower case. 

`GET {{host}}/wp-json/buddyboss/v1/media?context=edit&include=202,203,204,205&order=asc`

In the endpoint "media", order filter must be in lower case.
In the function BP_Media::get (file class-bp-media.php - line 359), the arg must be in upper case.

Because of that, the condition below is always false 

```
// Sorting.
$sort = $r['sort'];
if ( $sort != 'ASC' && $sort != 'DESC' ) {
	$sort = 'DESC';
}
```

**To Reproduce**
1. Make a API Request to media endpoint with filter "order=asc"
2. The result is not ordered ASC

Regards

**Comment by ExoGeek** [comment]
**Enhancement idea :** 

If user request medias using "include=205,203,204,206" and doesn't set order and orderby filters. 

`GET {{host}}/wp-json/buddyboss/v1/media?context=edit&include=205,203,204,206`

In that case, the SQL request should not add ORDER BY clause in the SQL Code.

In that way, we could query media in specific order.

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Release update shared here: 
https://github.com/buddyboss/buddyboss-platform/issues/1268#issuecomment-686277286

Thanks.
