### ISSUE TITLE
Frontend/Styling/Look and Feel BuddyBoss Theme issues : The LearnDash Group course landing page template

### ISSUE THREAD

**Issue by 007ke** [buddyboss/buddyboss-platform#1357]
**Describe the bug**
Learndash Group (v 3.2 and above) landing page template style (look and feel) is missing / not created. This style should be similar to a LearnDash Course landing page template using the BuddyBoss Theme. Both web links attached below.

**To Reproduce**
1. Update to the latest LearnDash version 3.2.2 
2. Go to Learndash (LD) Groups section and create a new LD group and add two or more courses within this new group.
2. Configure the LD Group pricing, feature image and all other group related details. 
3. Save, Publish and preview the page layout
4. See issue. The page layout is as per the default LearnDash Group page template and not BuddyBoss Theme Course page template

**Expected behavior**
The LD Group page layout should be similar to the BuddyBoss Theme Course page template with Add to Cart / Buy Now button and other details more pertaining to LD group related details 

**Weblink / Screen Shot**
Check these two weblinks: 
https://hubtoo.org/ld-groups/vative-academy-lean-champion/    (LD Group landing page template)
https://hubtoo.org/courses/identify-value-and-waste-vative/       (LD Course landing page template)

**Support ticket links**
BuddyBoss Ticket # 85751

**Jira issue** : [PROD-921]

[PROD-921]: https://buddyboss.atlassian.net/browse/PROD-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by eisenwasser** [comment]
@007ke 

It is assigned and will be reviewed soon. Thanks!

**Comment by 007ke** [comment]
Thanks Michael. Appreciate. Also if needed, i can opt to be a tester

**Comment by eisenwasser** [comment]
@007ke After reviewing this further, we have found that the content on these pages is actually correct. If you disable BuddyBoss Theme and BuddyBoss Platform, you will see that the content on the two pages is very different and this is coming from LearnDash itself. We are trying on purpose not to change the content LearnDash provides on each template, as much as possible, but to style it all to match our theme nicely.

Some of this content does not look nice, it does not match our theme style. So we need to update it to make it look nicer, which we will do. But we should not be adding the "Add to Cart / Buy Now" buttons when LearnDash is not doing that in their own template. We are likely to break LearnDash functionality once we go down that path. We really want to keep our LearnDash templates "clean" meaning true to how LearnDash intends that template to work. But yes this definitely needs a design refresh.

**Comment by 007ke** [comment]
Hi @eisenwasser i agree the content is correct but the display style needs to match BuddyBoss theme. 

As to 'add to cart / buy now' ... the feature is very much there in every LD group creation (similar to LD course creation) and only logical to have that same show up in LD group landing page. If it does not show up in the LD template then i think we should raise this as an issue with LearnDash dev team as well as this is a bug. If we notice the creation of a LD group is having almost all the settings of a LD course creation. I, personally, do not understand why create the LD group settings with 'buy now' / 'closed' / extra settings and do not have the same as a front end display to serve that purpose. Definitely a 'bug' with LD template and we should have this raised to LD dev team. Can your team (as being developers) raise this with them and in-turn share the feedback with us all? Thanks. 

I also understand that it could be another challenge for you and your team as currently there is no front end 'buying' for social groups and due to this new LD group 'buying' feature, sooner or later that would be the most logical step to follow in the BuddyBoss Social Group creation.

Thanks BuddyBoss team for your instant support and providing us with your service excellence approach.

**Comment by 007ke** [comment]
Hi @eisenwasser / @amincdev  ....  any update / feedback?

**Comment by sourabhmatolia** [comment]
Hi @007ke 

Sourabh here from BuddyBoss. I see your request on HelpScout.

**Task Update is:**

Suggestion you shared above makes sense.
We started working on this task internally.
We are in the Design phase for Learndash group screens.

Once designs are approved internally then we will start implementing.
You can expect this to be "In Progress" soon and ready in the coming month.

That's the update I have for you so far.
Let me know if you have more questions.

Thank you.

**Comment by 007ke** [comment]
Thanks Sourabh

If possible, Can you please share the tasks and flows? Is this only for LD
Group or are we extending this to BuddyBoss Social Groups as well ?

Thanks & Regards

Best Regards,

Ketan

**Comment by sourabhmatolia** [comment]
@007ke 

We are planning to work on LD Group screens with all different options from Learndash.
That should take care of 'add to cart / buy now' option you are talking about above.

We are not extending anything in Social Groups for this task.
We already have Social Group Compatible with LD Groups when Sync is enabled. 
Social Group respects all LD Group features. Like if LD Group is Paid then don't allow users to JOIN the Social group.

You can find more details on LD Group and Social Group compatibility here: 
https://github.com/buddyboss/buddyboss-platform/pull/1280

Thanks.

**Comment by 007ke** [comment]
@eisenwasser 
This LD layout issue is pending since August 2020. 
Does it take this long????????????? Seriously!!!

**Comment by 007ke** [comment]
@chetansatasiya @eisenwasser @sumitbuddyboss
There is no update to my message past 8 days. Also this issue is pending past 8 months.
Your customer support team has no idea when this will be resolved.

**Comment by sourabhmatolia** [comment]
Hello @007ke 

Sorry for delaying this.
There is a lot going on internally in BuddyBoss.
We will shift focus to this as soon as we can but we don't have any official ETA on this.
The best I can tell is, it is important for us to fix this, we will fix this, but we don't have a date.
I hope that helps.
Thanks.

**Comment by 007ke** [comment]
@sourabhmatolia @marienel21 @eisenwasser 
**Today ... its been exactly ONE YEAR since this issue was first reported. AND there is NO resolution or even support or discussion on this. Everytime, I have to keep reminding and chasing :-( **  

Its a pure Learndash BuddyBoss theme integration issue and possibly a new page template has to be created to support the LearnDash Groups landing page which by the way works and displays fine on the standard wordpress default themes.

Why are you unable to even support the official LearnDash feature and related integration into your BuddyBoss theme after being extremely patient for ONE WHOLE YEAR.

**Comment by 007ke** [comment]
@amincdev

**Comment by eisenwasser** [comment]
This issue is in the pipeline to be resolved, thanks

**Comment by 007ke** [comment]
@eisenwasser @mikejyoung @chetansatasiya @sourabhmatolia @amincdev 

I'm myself feeling embarrassed asking the same thing repeatedly.... 

This is not any new feature request but a BUG in your theme. The default learndash theme as well as all the other themes don't seem to have this issue and only buddyboss theme is having this issue. 

**It's now been 15 MONTHS and you have not yet resolved this simple bug?????  WHEN WILL THIS BE FIXED!!!!!!**

Very unhappy with your support service.

**Comment by eisenwasser** [comment]
@007ke This is being worked on and will be released once ready.

Sorry it has taken so long, it has not been a priority project. But we are working on designs now.

I'm not sure what you mean when you say it is a bug? The only issue is that we have not taken the time to add special styling to LearnDash Group pages to make them look really pretty with the theme design. The content on the page is exactly the same as when I switch to any other theme. It is just a styling issue. Where do you see a functional bug?

You mention above that "The page layout is as per the default LearnDash Group page template and not BuddyBoss Theme Course page template"

But that is not the case from what I can tell. The group page template is not using the course template by default in any theme. It is showing a list of courses using different markup than the course index, and once you join the group those courses can be expanded to reveal your progress in them. Basically, it is displaying the courses using the same markup that a course uses to display its lessons/topics. That is how LearnDash intends for this to work. So the project is just to style all of that to match our theme style.

**Comment by eisenwasser** [comment]
@007ke To elaborate on what I mean:

https://www.loom.com/share/aefc0327d50149d2801d37a99d65aee9

**Comment by 007ke** [comment]
@eisenwasser @chetansatasiya @sourabhmatolia @amincdev @mikejyoung 
Thanks Michael and i can confirm what you said above is correct as per the screenshot and the issue is now more on styling the learndash groups archive page and the learndash groups single page.

I further researched and found a way that buddyboss platform can work with learndash groups and detailing the steps here below for you and your team's further discussion.

**Current Challenge:**

- BuddyBoss Groups works top - down (one needs to first be enrolled into the parent group to be further enrolled in sub-groups)
- LearnDash Groups works bottom-up (one needs to be first enrolled into the sub-group then the parent group)
- LearnDash Groups are more about bundling courses together for a single purchase and access apart from group branding and managing / reporting
- BuddyBoss Groups are not ecommerce ready


**Possible Solution:**

- Make Learndash Groups integration similar to Learndash Courses integration within the BuddyBoss Pro Platform. Here, I will refer Learndash Groups as LD-Groups so not to confuse BuddyBoss Groups (BB Groups).
- Create an integration within BB Groups so on the BB Groups Single landing page, as a tab we can see a new 'LD Groups' next to the LD Courses. This tab will again only display the list of enrolled LD-Groups and LD-Groups Certificates (same style as LD-Courses) with the LD Group(s) progress
- Purchase / Enrolment / Access of LD Groups can have a separate styling similar to LD Courses (which is yet to be created by you and unstyled as per your screenshot image above) 
- On the syncing LD to or from BB, create another option as 'do nothing', so both LD Groups and BB Groups work independent to each other    
- Make BB Groups ecommerce ready so additional to current option of public and private, one can also have 'paid' and 'unpaid' to join the BB Group. If paid, then option to create how many users within this BB Group. Front-end visitor can purchase one or multiple access (so a visitor can buy multiple seats and by default this visitor can have the role of a 'moderator' for this BB Group. This visitor can only see and manage their members and not other members within this BB Group. Invite / Add other members as per the number of seats purchased. View (reports) for their members only. 

This way BB platform can work with their own features without conflicting with LD Groups features and functionality.
