### ISSUE TITLE
Single LearnDash Group mapped to multiple BuddyBoss Social Groups with granular user role permission, capability and status update 

### ISSUE THREAD

**Issue by 007ke** [buddyboss/buddyboss-platform#1358]
**Is your feature request related to a problem? Please describe.**
(1) One / Single LearnDash (LD) Group can be mapped to multiple BuddyBoss Social Groups
(2) BuddyBoss Social Groups navigation to have more tabs like Group Course Management only visible to Social Group Manager and Moderator roles to help view and manage the group member's course progress, reporting and activities like assignment / essay grading   

**Describe the solution you'd like**
The Buddy Boss platform + BuddyBoss Theme should be able to provide a simple way to map a single LD group to one or many Social Groups. This will further help manage a group of members under a specific social group manager / moderators. This will restrict a group cluster to be seen and managed by its own group manager / moderators without the need to create duplicate LD groups and/or multiple Group Leaders within each LD Group.

Further the Social Group Manager / Moderators can have role capabilities and permissions further added to match the LD group leader user role so that the LD learner progress / activities like grading an essay / assignment, etc ... managed in the front end from within the social group navigation. 

For Example:  
(1) Granularly define and map the capabilities, permissions and status of a group leader role to a social group manager role 
(2) Granularly define and map the capabilities, permissions and status of a group leader role to a social moderator role (with more restriction .... like a moderator can grade an essay / assignment but the status would change to approval pending and the final approval can be sanctioned by the social group manager role)

 
**Describe alternatives you've considered**
When under BuddyBoss Platform Settings  >Integrations > LearnDash. Go to the section LearnDash Group -> Social Groups. Further to the exact point, Sync Leaders and Sync Users.

Here, we can map sync leaders twice .... one for manager role and other for moderator role. We can then provide a check box to select the applicable learndash leader permission / capability / status to be mapped to each of the social group manager/moderator role. Similarly the Learndash sync user role can be further enhanced to granularly define and map to the social group member role.

**Comment by marienel21** [comment]
Hi @007ke,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
