### ISSUE TITLE
One user is unable to upload files in Group documents folder if the folder created by another user

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1360]
**Describe the bug**
One user is unable to upload files in the Group documents folder if the folder created by another user. It was working with the 1.4.6 version. Not working since 1.4.7.

**To Reproduce**
1. Create a folder ex: BuddyBoss Platform in the group's document folder
2. Try to upload a file on the BuddyBoss Platform folder as another group member. Notice that **Upload Files** and **Create Folder** button is not visible.

**Expected behavior**
Group document folders should accessible for all group members.

**Support ticket links**
https://secure.helpscout.net/conversation/1254134315/88241

**Comment by imehedidev** [comment]
It is intended.

**Comment by chetansatasiya** [comment]
HS Tickets:

https://secure.helpscout.net/conversation/1318923928/104841
https://secure.helpscout.net/conversation/1321681317/105399
https://secure.helpscout.net/conversation/1311614543/103693
https://secure.helpscout.net/conversation/1294448311/100972
https://secure.helpscout.net/conversation/1254134315/88241

**Comment by MitchRosal** [comment]
https://secure.helpscout.net/conversation/1376191369/116301/

**Comment by carmeltajanlangit** [comment]
https://secure.helpscout.net/conversation/1421104428/124356?folderId=4355035
