### ISSUE TITLE
How to switch back to admin?

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1362]
**Describe the bug**
There is no way to switch back to admin without re-login when "**Show the Toolbar for logged-in members (non-admins)**" option is not active.

**To Reproduce**
1. Disable option "**Show the Toolbar for logged-in members (non-admins)**" in settings (`/wp-admin/admin.php?page=bp-settings`)
2. Switch to some user (click "View As")
3. Try to switch back

**Expected behavior**
A "View As" button should be converted to "Switch back" button. The button shouldn't disappear.

buddyboss-platform v1.4.9

**Comment by janakkaneriya007** [comment]
@AiratHalitov You can switch back to admin by goin switched user's profile. Follow below video.
https://www.loom.com/share/a4c850fb2ba74cc298e40b1145769210

**Comment by AiratHalitov** [comment]
@janakkaneriya007 
I your video on test site it's looks and working good. But I don't see this "Back to Admin" button. 
Maybe there is conflict with some of plugins.
