### ISSUE TITLE
Copy Pasting Messages

### ISSUE THREAD

**Issue by bb-ralph** [buddyboss/buddyboss-platform#1363]
**Describe the bug**
Copy pasting a message removes a space. It works fine when no copy pasting done.

**To Reproduce**
https://www.loom.com/share/0784278e0ba649529a68570893f13963

**Expected behavior**
It should not remove the space

**Support ticket links**
https://secure.helpscout.net/conversation/1255966003/88594

**Comment by marienel21** [comment]
Bug is not reproducible in the current version of the product. Copy-pasting message works fine
