### ISSUE TITLE
Title, Description not working from Yoast option some of the Buddyboss pages

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1371]
**Describe the bug**
Title and description meta tag not working from Yoast option of buddyboss pages:

See video as a reference
https://www.loom.com/share/5d2b3bf54353402b99395b363e2f9271

- /blog/ (BuddyBoss Blog page)
- /members/ (BuddyBoss Members directories page)
- /members/USERNAME (BuddyBoss single member page)
- /groups/ (BuddyBoss Groups directories page)
- /groups/GROUPNAME (BuddyBoss Single group page)
- /activity/ (BuddyBoss Activity feed page)
- /forums/ (BuddyBoss Forums page)
- /documents/ (BuddyBoss Documents page)
- /registration/ (BuddyBoss Registration page)
- /activation/ (BuddyBoss Activation page)
- /course/ (LearnDash courses archive page)
- /shop/ (WooCommerce shop page)

**To Reproduce**
1. Install [Yoast SEO plugin](https://wordpress.org/plugins/wordpress-seo/) and buddyboss-platform 
2. Try to customize SEO description of some buddyboss page 
3. Open the page and see source code of page (CTRL+U)
4. You should see description meta tag. It should be looks like this:
`<meta name="description" content="Custom description of your page..." />`
5. But you will not see the description meta tag.

**Expected behavior**
All this pages should have custom title, description, but with buddybos-platform it is not displayed.

Related issue in Yoast SEO plugin (BuddyPress integration): https://github.com/Yoast/wordpress-seo/issues/7331
You can see there [some my code snippets](https://github.com/Yoast/wordpress-seo/issues/7331#issuecomment-414325874) for BuddyPress + YoastSEO integration.

Maybe you could add better integration with Yoast SEO plugin. 

Maybe these bugs are coming from your buddyboss-theme, I don't know.
There is also a problem with displaying Yoast SEO breadcrumbs (enable here `/wp-admin/admin.php?page=wpseo_titles#top#breadcrumbs`) on BuddyBoss pages.

- buddyboss-platform 1.4.9
- Yoast SEO plugin 14.8
- WordPress 5.5

**Comment by sourabhmatolia** [comment]
Akshit please take over this task.

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss 

Meta title and description for /forums/ page is not getting change when we set Title and description through Yoast Plugin.
Tested on Dev branch. Used Yoast SEO Plugin.
Video : https://www.loom.com/share/8543441c94c24714a7d5c8a92966745b

**Comment by sourabhmatolia** [comment]
@AiratHalitov

Issue mentioned above is released in BuddyBoss Platform v1.5.8

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-8/

Please update the plugin to see the latest changes.

Thank you.
