### ISSUE TITLE
Accessing the hidden group is returning "Too Many Redirects" error.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1372]
**Describe the bug**
When someone tries to access the hidden group who is not a member of that group, returning "Too Many Redirect" error.

**To Reproduce**
1. Create a Hidden Group.
2. Log in as a normal user who is not a member of that group.
3. Try accessing that group via a direct URL.
4. See error.

**Expected behavior**
It should show the notice that "you don't have access to this group".

**Screencast**
https://screencast-o-matic.com/watch/cYjF2QG8ZQ

**Support ticket links**
https://secure.helpscout.net/conversation/1252205081/87906?folderId=3701248

**Comment by janakkaneriya007** [comment]
@furqanbb It seems it's fixed on current dev branch.
https://www.loom.com/share/6e875d8d95b6408c81832f88a389727c
