### ISSUE TITLE
Activity page Document file name overlapping on Firefox web browser

### ISSUE THREAD

**Issue by bb-ralph** [buddyboss/buddyboss-platform#1374]
**Describe the bug**
Overlapping text when the document file name is too long on firefox web browse only.
I have provided a CSS code to client to fix, but this is an issue in our platform so I considered posting this issue here.

CSS code that I provided to the client to fix the issue:
.bb-activity-media-wrap .bb-activity-media-elem.document-activity .document-description-wrap .document-detail-wrap{
flex-basis:auto;
}

**To Reproduce**
1. Open Firefox Web Browser
2. Upload a document that has a long file name

**Screencast**
https://drive.google.com/file/d/1dEdZFUpzUFlMCxUsUCJggSsbicCHjcf_/view

**Expected behavior**
The text should not overlap

**Screenshots**
![Capture](https://user-images.githubusercontent.com/68835527/90572819-89928f80-e1e7-11ea-8633-c58658e6ec52.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1256395201/88666

**Comment by amincdev** [comment]
@bb-ralph Closing this issue because I checked with Firefox and it is showing fine: https://prnt.sc/11nl65g. Please reopen this issue if you are still facing issue with any specific steps.
