### ISSUE TITLE
I’M FOLLOWING Widget not working properly on My Profile > CONNECTION page

### ISSUE THREAD

**Issue by shashank-buddyboss** [buddyboss/buddyboss-platform#1378]
**Describe the bug**
On My Profile > CONNECTION page, on I’M FOLLOWING Widget people avatar appears 12 and beside the I’M FOLLOWING Widget title text, the number shows 16. 

This issue happens only on My Profile > CONNECTION page apart from this page it is working fine i.e https://prnt.sc/u25x91.

**To Reproduce**
1. Go to Admin dashboard > appearance > widgets > Members - Single Profile add (BB) Members I'm Following widger https://prnt.sc/u25to3
2. Go to frontend side, Click on Profile > Connections from the menu https://prnt.sc/u25w3b
3. See an error on the Connection tab page > https://prnt.sc/u25xyi

**Expected behavior**
How it works on another page > https://prnt.sc/u25x91

**Screenshots**
https://prnt.sc/u25xyi

**Comment by dipskakadiya** [comment]
@shashank-buddyboss 
This is the wrong issue. Actually `Connection` and `followers`  are separate things. 
 you can compare that count with Profile header data 

<img width="390" alt="Screenshot 2020-09-16 at 3 03 49 PM" src="https://user-images.githubusercontent.com/2979084/93319722-d5a81280-f82d-11ea-9977-a54b89d19848.png">
