### ISSUE TITLE
Photo with message not working

### ISSUE THREAD

**Issue by ThemeMetro** [buddyboss/buddyboss-platform#1385]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Go to New activity post'
2. Click on 'photo and write a message along with then post'
3. Scroll down to 'only text message is showing in post without photo '

**Expected behavior**
It should be show full post message + media (photo OR file)

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by marienel21** [comment]
Bug not reproducible in the current version of Platform and Theme.
