### ISSUE TITLE
Display issue when you use emoji in the album title

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1392]
**Describe the bug**
If you use emoji into your album title, there's a small display issue on the page https://buddyboss.localhost/members/exogeek/photos/albums/

**To Reproduce**
1. Edit album title with "Album with emoji 🐏🐑"
2. Validate

**Expected behavior**
Correctly display emoji.

**Screenshots**
![image](https://user-images.githubusercontent.com/46819762/90987348-910cbc80-e58a-11ea-9eb7-e3e9d8d0355c.png)

![image](https://user-images.githubusercontent.com/46819762/90987353-a7b31380-e58a-11ea-95bd-2926e16f6137.png)

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by kishanjasani** [comment]
Hi, @ExoGeek, 
Not able to replicate tried it with other themes too. But not able to replicate the issue. If you are still getting the issue you can reopen it. Thanks

**Comment by ExoGeek** [comment]
@kishanjasani There's still the issue. I've tested on https://demos.buddyboss.com/online-communities/

You can see the screencast there : https://youtu.be/YMqxxj-sG-Q

**Comment by kishanjasani** [comment]
@ExoGeek Not sure. But I am not able to reproduce. Can you check my recording : https://www.awesomescreenshot.com/video/4752259?key=1f1dc3b0d858d14d027b4c463eb34df9
Am I missing any step?

**Comment by ExoGeek** [comment]
@kishanjasani This is very strange. I've tested on my Mac with Safari and Chrome and it has worked as expected. 

This issue seems to be related to Firefox and Chrome for **Windows**.
