### ISSUE TITLE
When send only emoticons in messaging system, does not send

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1394]
**Describe the bug**
When trying to send only emoticons in the messaging system, does not send ( Some of them.) It gives an error(Please add some content to your message).

**To Reproduce**
1. Go to the Messages section.
2. Try to send the only emoji.
3. See error.

**Expected behavior**
Should be able to send the only emoji without content.

**Screenshots**
https://prnt.sc/u4qzy2
https://prnt.sc/u4r06k

**Comment by ExoGeek** [comment]
Are you using the last release of BuddyBoss platform ? I manage to send a message with only emoji.

![image](https://user-images.githubusercontent.com/46819762/91029652-4b3e0b80-e5ff-11ea-8c69-d05e7ab16c3d.png)

**Comment by ExoGeek** [comment]
But what I've just found is that when you copy-paste some text containing emojis, it doesn't send.

**Issue 1**
1. Copy the text "et plus avec 💪😃👉"
2. Paste that text in the reply field of buddyboss messaging system
3. Press "Send Reply"
=> Doesn't work.

**Issue 2**
1. Copy the emoji "💪" (only the emoji)
2. Paste the emoji in the reply field of buddyboss messaging system
3. Press "Send Reply"
=> The emoji is not correctly displayed (is displayed in full size inside the reply field)
=> An error is displayed "Please add some content"

![image](https://user-images.githubusercontent.com/46819762/91030916-20a08280-e600-11ea-8138-cc850c1d5602.png)

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Issue created above is released in Buddyboss Platform v1.5.1.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-1/

Please update the plugin to see the latest changes.

Thank you.
