### ISSUE TITLE
Group type - None cannot be selected in Profile Type settings

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1396]
**To Reproduce**
1. Create Group Types
2. Create a Profile Type
3. In "Group Type Creation" of Profile Type Settings select **None**
4. Notice the error

**Screen Recording**
https://cutt.ly/5faWd5h

**Screenshots**
![group type none](https://user-images.githubusercontent.com/58522498/91084892-3acd7580-e67f-11ea-9359-b3cbadf62919.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1256971100/88760/

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1261845845/89618

**Comment by marienel21** [comment]
Bug fixed. Not applicable on the latest version of the product.
