### ISSUE TITLE
Users Don't have Add Photo button in Albums

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1399]
**Describe the bug**
Users are not able to Add photos in albums of a group if the album is created by some other user. They can Add photos into their own created albums. It is working fine with BuddyBoss Platform v1.4.6. 

**To Reproduce**
1. Create an Album in a Public Group (for example Test Group) with admin user role or any user role
2. Now login as a different user and navigate Group (Test Group) >> Albums >> Open the Album created by Admin.
3. See, there is no "Add Photo" button.

**Expected behavior**
Users should be able to Add Photos to the Group Albums as it was working with v1.4.6

**Support ticket links**
https://secure.helpscout.net/conversation/1253859413/88201

**Comment by sourabhmatolia** [comment]
This is the expected behaviour. Closing issue.
