### ISSUE TITLE
When replying to a post authors comment, it generates double notifications

### ISSUE THREAD

**Issue by BenJackGill** [buddyboss/buddyboss-platform#1402]
**Describe the bug**
User blog posts have a comment section at the bottom. The post author can add their own comments and reply to other comments there.

When someone replies to the post authors comment the post author receives two notifications. The post author gets one "commented on" blog post notification, and one "replied to" comment notification.

Receiving two notifications for the same comment is redundant and confusing.

**To Reproduce**
1. Turn on BuddyBoss Activity Feeds component, and allow commenting on blog posts
2. Create a blog post
3. Leave a comment on your own blog post
4. Login as another user
5. Reply to the post authors comment
6. Go back to post authors account, you will receive two notifications
7. The first "replied to" comment notification is needed. The second "commented on" blog post notification is not.

**Expected behavior**
One notification per comment.

- Only the "replied to" comment notification should be generated if it is a new reply to a post author comment.
- Only the "commented on" blog post notification should be generated if it is a new top level comment. 

**Screenshots**
Screenshot of the double notification: https://imgur.com/a/1uyudWZ

**Comment by marienel21** [comment]
Hi @BenJackGill 

The issue mentioned above is released in BuddyBoss Platform v1.7.7

You can check release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-7/

Please update the plugin to see the latest changes.

Thank you.
Marienel - Product Team
