### ISSUE TITLE
Uploading the profile photo from 'Selfies' folder , the photo gets rotated

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1403]
**Describe the bug**
I am on latest iOS 13.6.1 , when uploading the profile photo from 'Selfies' folder and then selecting the 'Image size' , the photo gets rotated. Please check here https://www.youtube.com/watch?v=Yc-XmXMX7k4&feature=youtu.be

**To Reproduce**

1. Login and go to 'Change Profile photo' page.
2. Try uploading a photo from 'Selfies' album in your iOS photo gallery.
3. Select the image size after selecting the photo. Please check here https://www.youtube.com/watch?v=Yc-XmXMX7k4&feature=youtu.be
4. Then see the error. 

**Expected behavior**
No rotation should happen

**Screenshots**
https://www.youtube.com/watch?v=Yc-XmXMX7k4&feature=youtu.be

**Support ticket links**
https://secure.helpscout.net/conversation/1218485289/82244/

**Comment by ankitguptaindia** [comment]
@sumitbuddyboss @mehulkaklotar 

Tested this specific issue on iOS 13.7 Safari.

Some photos getting rotated after uploading from Selfie folder.
![IMG_17B07AE9CA06-1](https://user-images.githubusercontent.com/6384299/94519969-1d289880-0249-11eb-8cad-819149151471.jpeg)
![IMG_F2DD80F68672-1](https://user-images.githubusercontent.com/6384299/94520115-552fdb80-0249-11eb-86e4-0ac2f4d6d1b8.jpeg)

**Comment by asaquzzamanbb** [comment]
@Anve-sri 

Would you please test the issue again and let me know if the problem still exists. Please check the image there is no rotation after upload image.
https://prntscr.com/10nuazk

**Comment by jrbuddyboss** [comment]
Thank you @asaquzzamanbb. Working fine now on my end: https://drive.google.com/file/d/1U99pJnBqYPA9xmVvHRcCJs1Trmr73pb6/view?usp=sharing

**Comment by jrbuddyboss** [comment]
Reopened the issue as still persist. 
Platform Version 1.5.8.2
Screen Recording: https://drive.google.com/file/d/1WaLWnfVZ9yETI7qyI2Fnxf7CFXztqIkC/view

Thanks Mishu for confirmation.

**Comment by jrbuddyboss** [comment]
Re-open the issue as still persist. Talked with @asaquzzamanbb and will proceed after some priority issues. 🙂

https://user-images.githubusercontent.com/67351383/120472723-d4793e80-c3d8-11eb-9f25-1819d56f7cf9.mov

**Comment by chetansatasiya** [comment]
@jrbuddyboss @asaquzzamanbb @sourabhmatolia @jitendrabanjara1991 

Closing this issue as it's an IOS issue. See here for more info.

https://stackoverflow.com/a/66836205
https://github.com/disintegration/imaging/issues/104#issuecomment-549141804

If you are uploading the original file then there are not any issues, so this is an IOS different sizes options selections issue with image `orientation` always giving the `1` and that's why PHP script also understanding the photo is good so no need to rotate more info in above Github issue.
