### ISSUE TITLE
Public content option doesn't work when a page is created with WPML

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1406]
**Describe the bug**
The public content option of Platform Privacy doesn't work when a page is created with the WPML plugin. 

**To Reproduce**
Steps to reproduce the behavior: https://www.loom.com/share/eba3491a3c7e47b4a7b1ec64da6fcadd

**Expected behavior**
The WPML translated page should remain publicly visible always. 

**Screenshots**
https://prnt.sc/u68fxx

**Support ticket links**
https://secure.helpscout.net/conversation/1257252943/88800
https://secure.helpscout.net/conversation/1302177831/102194/

**Comment by ExoGeek** [comment]
I've got the same problem. I do use Memberpress and WPML (in a private network). I try to translate de pricing page (which is a group in Memberpress) and I want to set public access to that page.

http://localhost/plans/pricing/ => **OK** (public access)
http://localhost/fr/plans/pricing/ => **KO** (no public access)

In BuddyBoss settings page, I've addeed **_/fr/plans_** in the section "Privacy" -> "Public Content".

**Comment by tdx79** [comment]
Having same issue:

SCENARIO 1 (/it**/**)
In BuddyBoss settings page, I've added https://domain.com/ and https://domain.com/it/ in "Privacy" -> "Public Content"
https://domain.com/ => OK (public access)
https://domain.com/it/ => KO (no public access)

SCENARIO 2 (/it)
In BuddyBoss settings page, I've added https://domain.com/ and https://domain.com/it in "Privacy" -> "Public Content"
https://domain.com/ => OK (public access)
https://domain.com/it/ => OK (public access) => ISSUE => all /it/ pages being exposed to public (privacy completely bypassed)

**Comment by chetansatasiya** [comment]
@ExoGeek @tdx79 Can you verify https://github.com/buddyboss/buddyboss-platform/pull/1760 PR will fix the issues or not?

**Comment by ExoGeek** [comment]
Hi @chetansatasiya . Just tested #1760 and it works. I manage to access **/plans/pricing/** (english) and **/fr/plans/prix/** (french).

**Comment by sourabhmatolia** [comment]
@ExoGeek @tdx79 


Issue discussed above is released in BuddyBoss Platform v1.5.5.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-5/

Please update the plugin to see the latest changes.

Thank you.
