### ISSUE TITLE
Links extend parent div in Reply form, making Post button unreachable 

### ISSUE THREAD

**Issue by tamara-m** [buddyboss/buddyboss-platform#1408]
This image replicating the issue on BuddyBoss demo site says it all. The blue highlight is me selecting via Inspect, the parent div just above the one with class "bbp-the-content-wrapper"

![Z7kgK0to7T](https://user-images.githubusercontent.com/9288041/91375893-3b3a4d80-e7f2-11ea-9d4f-a4c3d32a9c11.jpg)

**Comment by bb-yudhisthir** [comment]
Unable to replicate with the latest version https://screencast-o-matic.com/watch/crQ2QVVQWvM
Closing this issue
