### ISSUE TITLE
same filter in "bp_document_user_can_manage_document" and "bp_document_user_can_manage_folder"

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#1409]
same filter in `"bp_document_user_can_manage_document"` and `"bp_document_user_can_manage_folder"` functions

![image](https://user-images.githubusercontent.com/13551603/91425093-efc68480-e86f-11ea-99ee-9e9307372a72.png)
and
![image](https://user-images.githubusercontent.com/13551603/91425156-040a8180-e870-11ea-8f23-c5a8c85057cf.png)

**Comment by sourabhmatolia** [comment]
@mailalaki 

Issue created above is released in Buddyboss Platform v1.5.0.

Find platform v1.5.0 release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-8/

Please update the plugin to see the latest changes.

Thank you.
