### ISSUE TITLE
User Profile photo update activity

### ISSUE THREAD

**Issue by ThemeMetro** [buddyboss/buddyboss-platform#1411]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Go to 'upload new photo in profile.'
2. Click on '.in activity only show message while it should be show updated profile photo'

**Expected behavior**

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by fun99** [comment]
It there any update on this?

**Comment by kent-carlo** [comment]
Tested on plugin's latest version and it's working fine
![image](https://user-images.githubusercontent.com/82648504/130242152-e2e36c94-1554-49bf-9714-d1ed33fc29fc.png)

**Comment by ThemeMetro** [comment]
Its not working.. Only message s showing while it should be show the photo like facebook profile pic update news feed update.
