### ISSUE TITLE
Discussion replies from the activity feed is not showing up/syncing on the actual discussion post/thread.

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1412]
**Is your feature request related to a problem? Please describe.**
Issue: discussion replies from the activity feed is not showing up/syncing on the actual discussion post/thread.

https://www.loom.com/share/f430482736544d8dad3d0bda2b4541ee

**Describe the solution you'd like**
I think replies from the activity feed should marge with the actual discussion post/thread.

**Support ticket links**
https://secure.helpscout.net/conversation/1262147791/89675?folderId=3955985

**Comment by marienel21** [comment]
The comment option is no longer shown in the activity on the latest version of the Platform.
![image](https://user-images.githubusercontent.com/77659570/129490628-a17607bc-fe63-4929-8deb-9cb85bde41f3.png)
