### ISSUE TITLE
Allow other users (with roles) to Move documents to folders created by other users

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1416]
**Is your feature request related to a problem? Please describe.**
Users who created folders in Groups document can only move documents uploaded by them. 

**Describe the solution you'd like**
Allow the other users to move documents to folders that they have not created. Maybe we could create an option that organizers or moderators have this ability.

**Screenshot**
https://drive.google.com/file/d/1iUcBoD0h-KKBz74NF2-ZzAx_L5JBFyLt/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1253822391/88192?folderId=3701258

**Comment by megseoh** [comment]
I require this feature as well.

**Describe the solution you'd like**
All group members should be allowed to move/upload/download any folders or files within their group - these permissions can be controlled within the group settings: **Who can manage documents in this group?**

**Support ticket links**
[Ticket ID #111460 **Report a bug : Group Organizers Can't Upload Documents**](https://www.buddyboss.com/my-account/?conversation_id=1350198508)
