### ISSUE TITLE
Link Preview issues on iPad.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1418]
**Describe the bug**
The preview of the links is not appearing unless you place an 'SPACE' or a 'SLASH' right after the link .  Please refer to the video attached for concise explanation. 

**To Reproduce**
Please Watch the attached Video. 
[iPad.zip](https://github.com/buddyboss/buddyboss-platform/files/5144874/iPad.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1258389693/89017?folderId=3701249

**Comment by dipskakadiya** [comment]
@Anve-sri it's working fine on develop branch so might be this issue already fixed or it'll be fixed in the next release.

Proof: https://screencast-o-matic.com/watch/cYQD60JyzK

**Comment by Anve-sri** [comment]
Working for me too. Thanks @dipskakadiya

**Comment by chetansatasiya** [comment]
Closing this as this is not reproducable anymore.
