### ISSUE TITLE
News Feed: Adding link with text

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1422]
**Describe the bug**
Adding post in news feed pasting link and a text in the upper part of the link.

**To Reproduce**
1. Go to News Feed 
2. Try adding link and wait for the thumbnail appear. Now add text in upper part of the link and try to click post button. 
3. See error

**Expected behavior**
Post should appear in news feed.

**Screenshots**
Client screen recording:
https://imgur.com/a/BCpPXuv

My recording:
https://drive.google.com/file/d/1wXprebewybjauywEYR74ssEV2SNpSiOu/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1259317373/89148?folderId=3709080

**Comment by marienel21** [comment]
I can't replicate this on the latest version of the Platform.

**Comment by jrbuddyboss** [comment]
Fixed with latest released: https://prnt.sc/1q4g6f1
