### ISSUE TITLE
BB REST API - Media Endpoint : the field activity_id is set to 0 when update a media

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1424]
**Describe the bug**
When you want to "move" a media into an album, you need to make a Media Update Request. But, when you make that request, the field bp_media.activity_id is always reset to 0 (in the database).

`POST {{host}}/wp-json/buddyboss/v1/media/269?group_id=111&album_id=10`

This is because we can't set the parameter "activity_id" in an update request.

An easy solution could be to edit the line 432 of the file "bp-media-function.php"

From
`$media->activity_id   = (int) $r['activity_id'];`
To
`$media->activity_id   = ( ! $r['activity_id'] ? $media->activity_id : $r['activity_id']);`

**To Reproduce**
1. Take any media in the database with activity_id <> 0 (in the database bp_media)
2. Update that media (update album_id for example) by using a rest request.
3. Query the database to read bp_media.activity_id of your updated media.

**Expected behavior**
Do not reset activity_id when updating a media.

**Screenshots**
none

**Support ticket links**
none

**Comment by ExoGeek** [comment]
@KartikSuthar Sorry but this issue is not resolved.

**To Reproduce**
1. Upload via the website a new media (in http://buddyboss.localhost/members/bb-neville/photos/)
2. Have a look into the database (bp_media table), you should see : 

![image](https://user-images.githubusercontent.com/46819762/98445552-8fc64700-2118-11eb-93ce-04cb8dc1a790.png)

3. Execute the following rest api request in order to move that media into existing album : 

```
### Move media into album
POST {{host}}/wp-json/buddyboss/v1/media/329
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "album_id": 7
}
```
4. When the request is executed, see again into the database.

![image](https://user-images.githubusercontent.com/46819762/98445627-e92e7600-2118-11eb-924e-ea32050c6d34.png)

You can see that the column activity_id = 0 !

**To Resolve**
To resolve this issue, you have to edit the **line 630** of the file **_class-bp-rest-media-endpoint.php_** (function **_update_item_**).

Add the code `'activity_id'   => $media->activity_id,` to the array : 

```
$args = array(
	'id'            => $media->id,
	'privacy'       => $media->privacy,
	'attachment_id' => $media->attachment_id,
	'group_id'      => $media->group_id,
	'album_id'      => $media->album_id,
	'activity_id'   => $media->activity_id,
);
```

**Comment by KartikSuthar** [comment]
Thanks, @ExoGeek I have reopened this and update you shortly.
