### ISSUE TITLE
Imgur double Embeds in Forum Topics

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1426]
**Describe the bug**
Embedding Imgur links (e.g. https://imgur.com/a/11fDymR#newbDET) in forum topics and replies leads to embed being displayed multiple times. For some reason, it sometimes works as expected, while the Imgur link itself then gets removed. This does not seem to happen in activities.

**To Reproduce**
https://www.loom.com/share/498f2d5817554f25a3376571b36c3880

**Support ticket links**
https://secure.helpscout.net/conversation/1264847316/90140?folderId=3701248

**Comment by marienel21** [comment]
I cannot reproduce this bug on the latest version of the Platform.

**Comment by furqanbb** [comment]
Yes, Seems working fine now. Closing the issue here.
