### ISSUE TITLE
Network member search is redirecting to 404 on WPML secondary languages

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1428]
**Describe the bug**
Member search (autocomplete result) isn't working on WPML secondary languages. Video Explanation: https://www.loom.com/share/e7a5512cd83e4d7089a21d75de156867

**To Reproduce**
1. Search a member using the network search option from a secondary language page: https://prnt.sc/u8z1ag
2. Click on autocomplete result: https://prnt.sc/u8z3y4 

**Expected behavior**
It should redirect to the correct member profile page. 

**Support ticket links**
https://secure.helpscout.net/conversation/1263396150/89927/

**Comment by kent-carlo** [comment]
@imehedidev I tested with the latest buddyboss platform plugin and it works just fine. https://www.loom.com/share/31b129e4373747d691d19418a501365d
