### ISSUE TITLE
Topic title issue if it contains an apostrophe.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1433]
**Describe the bug**
Write anything with apostrophe, e.g - "Hello it's a question" Then post that topic without content.
after posting check the topic title. You'll see "Hello it\'s a question". It is adding a backslash itself.

**To Reproduce**
https://screencast-o-matic.com/watch/cYQVhUH1he

**Expected behavior**
It should not add backslash.

**Screenshots**
https://prnt.sc/u9dhz2

**Support ticket links**
https://secure.helpscout.net/conversation/1268593740/90795

**Comment by dipskakadiya** [comment]
@furqanbb I'm not sure how you able to submit a topic form with an empty description. On my end, I can't submit that form with empty description
