### ISSUE TITLE
Background click opens buddyboss website

### ISSUE THREAD

**Issue by ritz082** [buddyboss/buddyboss-platform#1434]
I would not call this a bug but a malware.
I have buddyboss theme and Platform on Wordpress Multisite installation. One subsite is using other theme without buddyboss platform. On that subsite, if i click on background, https://www.buddyboss.com/platform/ opens. Its normally click under which is obviously installed by buddyboss intentionally. When I disable buddyboss, i dont get this problem.
I have video recording for the same. I have converted it into gif 
![buddyboss-is-fraud](https://user-images.githubusercontent.com/50196563/91859315-ed0cca80-ec87-11ea-9792-614144f28e72.gif)

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by sourabhmatolia** [comment]
Hi @ritz082 

We don't think this is Malware or something done deliberately.
Checking GIF and the details you shared above, looks like some Plugin/Theme conflict.

We will have a look and update you. Thanks.

**Comment by ritz082** [comment]
Why and how will any theme open their website.
I think everyone here is smart enough to know what is what.
The buddyboss people have stopped replying to me. I have noticed, same thing is happening on frontend also.. I have lost huge traffic to their website.
I have evidence and codes with me. They are not on wordpress depository , maybe for the same reason. They have stopped replying me on social medias and just denyed any support on their website (where I had purchased their theme/ which by the way does not work as intended)
Once it is cleared from github, I will be looking forward to take legal action against them.

**Comment by eisenwasser** [comment]
@ritz082 

`I would not call this a bug but a malware`

Malware definition: 
`Malware is the collective name for a number of malicious software variants, including viruses, ransomware and spyware. Shorthand for malicious software, malware typically consists of code developed by cyberattackers, designed to cause extensive damage to data and systems or to gain unauthorized access to a network.`

You are referring to a minor plugin conflict and calling it malware. Your issue has not been reproduced outside of your website's install. We have many thousands of customers, nobody else is seeing this issue. It is likely a conflict in your admin with some other plugin.

`The buddyboss people have stopped replying to me. I have noticed, same thing is happening on frontend also.. I have lost huge traffic to their website.`

You already received a refund are not an active customer. You requested a refund on August 29. You expect us to continue to respond to your support tickets after asking for a refund?
