### ISSUE TITLE
Buddyboss Template not working in Elementor

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1436]
**Describe the bug**
Can't insert buddyboss template inside elementor editor.

**To Reproduce**
1. Go to Page and edit with elementor
2. Add buddyboss template and insert
3. See error

**Expected behavior**
Templates can be inserted in elementor editor.

**Screenshots**
https://www.loom.com/share/89565860eb62483bb44e0ae4917a8ca1 
https://a.cl.ly/GGuRld7N 
I tried replicating the issue here:
On our sandbox - working
My flywheelsites - not working
Localhost - not working
I tried deactivating elementor pro in our sandbox and it's still working.
No luck doing some workaround on my flywheelsites and Localhost.

**Support ticket links**
https://secure.helpscout.net/conversation/1265003587/90168?folderId=3943005
https://secure.helpscout.net/conversation/1265117877/90181?folderId=3709080

**Comment by King-Ding** [comment]
Can also confirm this 👍
