### ISSUE TITLE
Location Autocomplete plugin don't show Location fields at the time of Group Creation

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#1442]
**Describe the bug**

As per the plugin code logic, it should show Group Location fields at the time of Group Creation steps.
But it don't show when using Platform Plugin's Group. Works fine when using BuddyPress plugin.

**To Reproduce**
I have tested and found issue with Platform plugin.
https://www.loom.com/share/2ee62fa09f734fcc9e12c2f18280ad0b

**Expected behavior** Should show All fields at the time of Group creation.

**Screenshots**

With BuddyPress - https://i.imgur.com/Cw5WkNV.jpg
With Platform  - https://i.imgur.com/PXUoL9J.jpg
Our Scope - https://snipboard.io/Cp1w45.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1253612222/88161?folderId=3701264

**Comment by christinabbsupport** [comment]
https://secure.helpscout.net/conversation/1246200716/86821?folderId=3701264

**Comment by chetansatasiya** [comment]
@ankitguptaindia This is already fixed in Location Autocomplete plugin. So we have to add a new release in Location Autocomplete plugin and it will fix the issue.

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Some Notice are appearing when saving location fields on profile related to Platform plugin.

https://www.loom.com/share/de181d011c6c4a2280214469ee549845

**Comment by ankitguptaindia** [comment]
Above notice in not related to Location Autocomplete plugin. 

Issues have fixed now. Location fields are appearing for New Group, Edit old group, Registration Page, Member Profiles fields.



Test summary with BB Platform - https://www.loom.com/share/a0a18174257d40e4b4929f8e228e11cc
Test summary with BuddyPress - https://www.loom.com/share/7f804da67ed54990bb49a113104f65a0


These fixes will come with release of Location Autocomplete Plugin.

**Comment by ankitguptaindia** [comment]
https://www.buddyboss.com/release-notes/location-autocomplete-for-buddypress-1-2-3/ has been released.
