### ISSUE TITLE
Subscribers could not post consecutively on Group Discussions

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1452]
**Describe the bug**
In Groups Discussions, users with subscriber roles could not post consecutively. Admins roles have no problem

**To Reproduce**
1. Go to Groups discussion
2. Create a discussion, then reply to that discussion
3. Then follow up another reply on that same discussion

**Expected behavior**
The post button just keeps loading, no warning at all. and this won't post

**Screenshots**
https://drive.google.com/file/d/1KFCqSNM5hPG13LN0nJQWmT2ofoTYBHmC/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1272969936/97110?folderId=3701258

**Comment by dipskakadiya** [comment]
@emmanoctaviano 
I tired on my local as well as on the demo site. I can't reproduce this. 
Please check this video https://screencast-o-matic.com/watch/cYQbXmJpyb. Let me know if I missing any step for reproducing this.

**Comment by emmanoctaviano** [comment]
@dipskakadiya try with non-admin user. thanks

**Comment by dipskakadiya** [comment]
@emmanoctaviano this issue already fixed with https://github.com/buddyboss/buddyboss-theme/pull/860
