### ISSUE TITLE
Message conversation is not opening conversation on mobile when user clicks on a specific conversation

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1453]
**Describe the bug**
**In mobile devices:** from the header inbox option when the user clicks on a specific conversation, the message conversation is selected but it is not opening on the first click. The user needs to click again to open that conversation. 

**To Reproduce**
Steps to reproduce the behavior: https://www.loom.com/share/e02c8a98ffbf47ddad66df79e6ba593e

**Expected behavior**
Open the conversation on the first click

**Support ticket links**
https://secure.helpscout.net/conversation/1274136661/97287

**Jira issue** : [PROD-917]

[PROD-917]: https://buddyboss.atlassian.net/browse/PROD-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amincdev** [comment]
https://secure.helpscout.net/conversation/1562409814/151279/

**Comment by amincdev** [comment]
@chetansatasiya If We fix this issue then: If user goes to message page in mobile then the first thread will be open by default like this: https://ibb.co/zF7yp4R

Let me know your thought.
