### ISSUE TITLE
Wrong Gravatar on Messaging

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1454]
**Describe the bug**
When you select "Identicon" has default (gr)avatar, the avatar shown on the messaging is the default gravatar icon and not an "identicon".

![image](https://user-images.githubusercontent.com/46819762/92334809-95a89900-f091-11ea-8f07-167a84b72e24.png)

But the avatar of Luna is the following : 

![image](https://user-images.githubusercontent.com/46819762/92334978-e79dee80-f092-11ea-8b96-bd3280c355c0.png)

**To Reproduce**
1. Go to wp-admin and change the default avatar (select Identicon)
2. Go to your inbox

See the avatar.

**Expected behavior**

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Issue created above is released in BuddyBoss Platform v1.5.2

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-2/

Please update the plugin to see the latest changes.

Thank you.
