### ISSUE TITLE
Wordpress Search function not working

### ISSUE THREAD

**Issue by haccpmentor** [buddyboss/buddyboss-platform#1455]
**Describe the bug**
What is essentially happening is that the search function for wordpress is not working when I have the BuddyPress Platform plugin installed. I disabled all of my plugins and reactivated one by one to diagnose the issue was related to BuddyPress Platform plugin. For your information I am using the following versions:

- BuddyPress Platform - 1.5.0
- My theme is Astra (2.5.4). I also tried with Wordpress Twenty Twenty theme and the issue also occurred when the BuddyPress plugin was activated.
-  Wordpress 5.4.2
- php 7.4

**To Reproduce**
1. Go to 'https://haccpmentor.com'
2. Click on 'search' icon in top navigation menu bar
3. Type in search term, for example,  'allergens' or 'haccp' or 'pest control' or calibration
4. See error - no search results returned.

**Expected behavior**
The search function to work. When putting in a search term, matching examples to show posts, pages etc.

**Screenshots**
I have attached two screenshots for you to review. What is essentially happening is that the search function for wordpress is not working when I have the BuddyPress Platform plugin installed.

**This is with the plugin enabled**

![Search HACCP Buddyboss plugin enabled](https://user-images.githubusercontent.com/70865310/92337370-712dda80-f0ec-11ea-8658-944443b9221a.png)

**This is with the plugin disabled**

![Search HACCP Buddyboss plugin disabled](https://user-images.githubusercontent.com/70865310/92337375-7ab74280-f0ec-11ea-8105-d672f49284fe.png)

**Support ticket links**
Issue has been advised through the contact request on the buddyboss website.

**Comment by sourabhmatolia** [comment]
@haccpmentor 

Issue created above is released in Buddyboss Platform v1.5.3.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-3/

Please update the plugin to see the latest changes.

Thank you.
