### ISSUE TITLE
Compatibility issue with BP Group Documents

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1468]
**Describe the bug**
All files uploaded in a group using the BP Group Documents plugin gone missing after the BuddyBoss Platform introduced the built-in Documents feature in 1.4.0.

**Integration Page**
https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/bp-group-documents/

**To Reproduce**
1. Use BuddyBoss Platform 1.3.5
2. Install BP Group Documents plugin
3. Go to any groups
4. Upload a file
5. Update to the latest BuddyBoss Platform plugin
6. Revisit the group where you have uploaded the file
7. See the error

**Screenshots**
![ss1](https://user-images.githubusercontent.com/58522498/92542245-de6f7600-f27a-11ea-99cf-8563a8daba26.png)
![ss2](https://user-images.githubusercontent.com/58522498/92542248-df080c80-f27a-11ea-94b5-f589e9d21a43.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1274826105/97404

**Comment by chetansatasiya** [comment]
@ayron-paul We are not giving the compatibility of BP Group Documents plugin. So If customer need to use BP Group Documents plugin then they need to disable the platform Documents.

**Comment by chetansatasiya** [comment]
@ayron-paul I also checked in my local with the latest platform and it looking like this https://prnt.sc/ue0fnv which you saying like in `1.3.5` 

Do you have any settings OR any steps to reproduce this issue?

**Comment by sourabhmatolia** [comment]
@chetansatasiya 

Please watch the video shared below for more details on the issue:
https://www.loom.com/share/b22712a907264ac1ad6820a176b912a7

Thanks.

**Comment by ayron-paul** [comment]
Hi @chetansatasiya,

Here is the video following the steps provided above, please see https://cutt.ly/0fR8Sth. Thanks!

**Comment by chetansatasiya** [comment]
@sourabhmatolia @ayron-paul I tried in 2 systems with 4 local setup and I didn't face any issue.

See here: https://www.loom.com/share/0c40da87be684c5c91ba09d1cde643ae

**Comment by ayron-paul** [comment]
Hi @chetansatasiya, may I know if there are some alternatives on how we can disable the Documents on the platform aside from disabling it through the Media Settings? Maybe we just missed it? Thanks!

**Comment by chetansatasiya** [comment]
@ayron-paul We have a settings here https://prnt.sc/um6hul to disable documents.

**Comment by ayron-paul** [comment]
Hi @chetansatasiya, in reference to the video I have provided in this thread, https://cutt.ly/0fR8Sth, I have already disabled those settings but the issue remains. Moreover, I also tried using the dev branch but still got the same result.

**Comment by chetansatasiya** [comment]
@sourabhmatolia @ayron-paul I am closing this issue as this is a conflict with the platform documents & BP Group Documents plugin.

**SOLUTION**

1. Disable the checkbox https://prnt.sc/ur02mx Group Documents from the platform settings.
2. Copy the `documents.php` template file from the BP Group Documents plugin using the FTP/SFTP PATH: `wp-content/plugins/bp-group-document/templates/groups/single/documents.php`
3. Go to the BuddyBoss Child Theme and paste it `documents.php` via FTP/SFTP PATH: `wp-content/themes/buddyboss-theme-child/buddypress/groups/single/documents.php`

You will get BP Group Documents template and all the documents from the BP Group Documents plugin.
