### ISSUE TITLE
Code error with xprofile bp-xprofile-functions.php

### ISSUE THREAD

**Issue by eat-code** [buddyboss/buddyboss-platform#1473]
**Describe the bug**
Recently, I'm seeing a series of code displaying in the "complete your profile" widget area. It seems to reference bp-xprofile that is listed as being compatible with BuddyBoss. This problem is a new one and didn't exist prior to the recent BuddyBoss platform and theme update, late last week. When the screen is refreshed, the code disappears only to reappear when the page is reloaded again. When I deactivate the "BuddyPress Xprofile Custom Field Types" plugin, the code/error still appears (albeit with reference to a different line of code) where the "complete your profile" widget should be. Do you have any suggestions? BuddyPress Xprofile Custom Field Types is listed as a plugin that should work together with the BuddyBoss platform (although it's been a few months since THAT plugin was updated). Thanks. - Debbie

See this screenshot
https://prnt.sc/uengp5

**To Reproduce**
Can't reproduce the error from my end but I found a fix within our code

https://prnt.sc/uenfoq

Please add check this ( is_array( $group_ids  ) the issue will be fixed.

**Screenshots**
https://prnt.sc/uengp5

**Support ticket links**
https://secure.helpscout.net/conversation/1246500521/86864?folderId=3955985#modal

**Comment by sourabhmatolia** [comment]
@eat-code 

Fixed warning shared above. It will be out in the next Platform release. Thanks.
