### ISSUE TITLE
Lesson Grid shortcode Progression label

### ISSUE THREAD

**Issue by dipskakadiya** [buddyboss/buddyboss-platform#1478]
LD Lesson Grid Shortcode, we are showing "Status" label but that is not correct so we removed with #381. We need to bring back that "Status" label with correct logic.

**Describe the solution you'd like**
We can change logic like below 

> If the lesson grid set for a single course [ From Lesson grid setting ] then we will show progression status to that course. 

> If showing all course lessons then we need to check the lesson associated with one course then show status according to that course
if lesson is shared with multiple courses then create a custom function to get the first course and show status according to that or we can hide status 

**Support ticket links**
Ref: https://github.com/buddyboss/buddyboss-theme/issues/381

**Comment by annrra** [comment]
Issue moved in https://github.com/buddyboss/buddyboss-theme/issues/1752
