### ISSUE TITLE
Preview getting changed when editing post which has Embed link

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#1480]
**Describe the bug**

When user editing the post and nothing change in content just changed Privacy options then Preview getting changed  and Link appearing on screen after edit.

After Edit - https://i.imgur.com/lSJ1jM5.jpg 
Before Edit - https://prnt.sc/uewzzy

**To Reproduce**
https://www.loom.com/share/577649dfba8f4d55a151b62ef25b323c

**Expected behavior**

If user don't change content then it should not make effect in embed preview

**Screenshots**
After Edit - https://i.imgur.com/lSJ1jM5.jpg 
Before Edit - https://prnt.sc/uewzzy

**Support ticket links**
N/A -  Reported by QA.

**Comment by marienel21** [comment]
I can't reproduce this on demo.

**Comment by chetansatasiya** [comment]
Closing this as per the @marienel21 tested on a demo.
