### ISSUE TITLE
"Invalid activation key" message false positive 

### ISSUE THREAD

**Issue by Ottartheboar** [buddyboss/buddyboss-platform#1485]
**Describe the bug**
If members try to activate their account a second time by following the URL in their activation email and submitting the activation form, they receive the message "Invalid activation key".  This is confusing to some users and appears to not be the correct error message got this user flow.

**To Reproduce**
1. Go to member registration page
2. Register a new member
3. Click on the URL in the activation email
4. Summit the activation form (with auto-populated activation key) to successfully activate the account 
5. Return to email and open the activation URL again
6. Submit the activation form (with auto-populated activation key) again
7. Receive the message "Invalid activation key."

**Expected behavior**
Ideally the message should indicate to the user that the key isn't invalid but rather that it is already activated. Users tend to understand the "Invalid activation key" message to mean they can't activate their account and don't attempt to sign into their accounts to verify account inactivity.

The BuddyPress Members activation function `bp_core_activate_signup()` includes a test for signups which have already been activated. In this case the error message would be "The user is already active" which encourages users to attempt signing in.

**Comment by sourabhmatolia** [comment]
@Ottartheboar

Issue mentioned above is released in BuddyBoss Platform v1.6.0

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-6-0/

Please update the plugin to see the latest changes.

Thank you.

**Comment by cupidblack** [comment]
If the user could be redirected to the login page if "The user is already active".
