### ISSUE TITLE
BB REST API - Notifications Endpoint (update_reply) : Store main activity id in the response

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1490]
**Is your feature request related to a problem? Please describe.**
I use the REST API in a mobile app. In that app, I display notifications based on the query `GET {{host}}/wp-json/buddyboss/v1/notifications`. 

When user clics on one of the notification, I would like to open the screen attached to the notification. But it's not always easy to open the correct screen because we don't always have the correct ID.

For example, here is a notification "update_reply". What I would like to do is to open the screen "Display Activity" with the ID = 932. But the ID 932 is only visible in the link_url field (I need to extract that ID from a string).

```
    "id": 1128,
    "user_id": 1,
    "item_id": 936,
    "secondary_item_id": 12,
    "component": "activity",
    "action": "update_reply",
    "date": "2020-09-14T16:09:07",
    "is_new": 1,
    "description": {
      "rendered": "<a href=\"http:\/\/buddyboss.localhost\/news-feed\/p\/932\/?rid=1128#acomment-936\">Neville commented on one of your updates<\/a>"
    },
    "link_url": "http:\/\/buddyboss.localhost\/news-feed\/p\/932\/?rid=1128#acomment-936",
    "rest_actions": "",
    "object": "user",
    "object_id": 12,
```
**Describe the solution you'd like**
Could you use fields "object" and "object_id" to store the ID of the parent activity ?

```
    "object": "activity",
    "object_id": 932,
```
**Describe alternatives you've considered**
Another solution could be to use the field "secondary_item_id" to store the activity id but that field is stored in the database and that could be harder to implement that solution.

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
