### ISSUE TITLE
Sort Group Types Alphabetically

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1492]
**Is your feature request related to a problem? Please describe.**
When there are several group types, the group type dropdown is not user friendly, some users are having some hard time to find the group type they are looking for.

**Describe the solution you'd like**
Be able to sort the Group Type filter in the Group directory so that the user can easily find and select a group type.

**Screenshot**
![group-types](https://user-images.githubusercontent.com/58522498/93181535-2571d580-f76b-11ea-89d3-6a2e5b05fbd3.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1273251749/97145

**Jira issue** : [PROD-914]

[PROD-914]: https://buddyboss.atlassian.net/browse/PROD-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shyamwp14** [comment]
there is no way to sort the Group Types in the dropdwon menu of ther front-end
https://secure.helpscout.net/conversation/1525076566/144377/
