### ISSUE TITLE
Post Data getting lost if user edit any other post while creating new post.

### ISSUE THREAD

**Issue by shohelbuddyboss** [buddyboss/buddyboss-platform#1494]
**Describe the bug**

UX Bug - Post Data getting lost if user edit any other post while creating new post.
UX- In this scenario any author will loss typed content in text editor if they edited any post at the same time.
Refer video for details.

**To Reproduce**

https://www.loom.com/share/f415bee7f1654c8c850c900ef7528259

**Expected behavior**

This should not remove data if user edit old activity at the time of writing new post.

**Screenshots**

https://www.loom.com/share/f415bee7f1654c8c850c900ef7528259

**Support ticket links**

N/A- Internal from QA.

**Jira issue** : [PROD-913]

**Theme Issue:**
https://github.com/buddyboss/buddyboss-theme/issues/979

[PROD-913]: https://buddyboss.atlassian.net/browse/PROD-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chetansatasiya** [comment]
@jitendrabanjara1991 This is for you
