### ISSUE TITLE
Poor thumbnail quality when photo is wider (when aspect ratio > 1.5)

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1495]
**Describe the bug**
When you upload a "wide" photo, the thumbnail created for that photo is very poor. 

See the image quality of the third photo (full dimension of that photo is 2560x1064) : 
![image](https://user-images.githubusercontent.com/46819762/93197711-41b24a00-f74c-11ea-9003-472cabc54b96.png)

Here is the HTML code of that photo : 

`<img src="https://buddyboss.localhost/wp-content/uploads/2020/09/image1599214832733-400x166.jpg" alt="image1599214832733" class="">`

You can see that the dimension of the thumbnail is 400x166 but the img zone is 270x270.

**To Reproduce**
1. Take a photo where width is much greater thant height (or height is much greater than width)
2. Upload that photo
3. See thumbnail quality

**Expected behavior**
I think, there is 2 solutions : 

1) Resize the image in a way that we have both sides of the image >= 400 pixels (In the example above, the thumbnail dimension should be : 964 x 400)
2) Resize the image in a way that we have both sides of the image >= 270 (that correspond to the size in the template. In the example above the thumbnail should be 650x270)

**Screenshots**
See above

**Support ticket links**
none

**Comment by kent-carlo** [comment]
Can't replicate the issue with the latest version of buddyboss platform.
