### ISSUE TITLE
BB REST API - Activity Endpoint : Missing display_comments in documentation of get_item

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1496]
**Describe the bug**
This is not a bug but rather a documentation issue. 

When you display available arguments for the rest api request `GET {{host}}/wp-json/buddyboss/v1/activity/932`, there're only 2 arguments availables : id and context.

But when you look into the method `get_item` and `prepare_item_for_response` in the file "_class-bp-rest-activity-endpoint.php_", you can see that there's another argument that you can use : **display_comments**

Could you update the documention of that endpoint ?

Ps : Please, do not remove that argument because it is very usefull to be able to get main activity + comments in one single request.

**To Reproduce**
Execute `OPTIONS {{host}}/wp-json/buddyboss/v1/activity/932`. 
You only see 2 args : id, context.

**Expected behavior**
You should also list display_comments as available argument

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by sourabhmatolia** [comment]
@ExoGeek 


Issue created above is released in Buddyboss Platform v1.5.1.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-1/

Please update the plugin to see the latest changes.

Thank you.
