### ISSUE TITLE
The text formatting buttons are working weird for customer site

### ISSUE THREAD

**Issue by dipskakadiya** [buddyboss/buddyboss-platform#1497]
**Describe the bug**
The text formatting buttons are working weird for customer site

**To Reproduce**

1. - The toolbar editor is activated upon clicking on it with no text present in the text box. When clicking on the bold or italic the toolbar then dims. If you then write text it is bold and/or italic and the toolbar is now activated and whatever you chose is also activated. Visually, the bold and italic looks as if it was not chosen when in fact it was and the toolbar actually has recorded what you chose.
2. - The link, quote, and ordered/unordered lists work right away when selecting them without any text present.
3. - The preformatted text will only work with text present. The text cannot be bold, italic, or underlined, otherwise you will have the bug shown in the video.

**Expected behavior**
It should show correct formatting.

**Screenshots**
Ihttps://www.loom.com/share/79d7b3e9f45a4493b06af217073d78f6. 

**Support ticket links**
https://secure.helpscout.net/conversation/1152352783/71441/

**Comment by amincdev** [comment]
@dipskakadiya This issue seems connected to this PR (Already worked on): https://github.com/buddyboss/buddyboss-platform/pull/1169

**Comment by dipskakadiya** [comment]
@amincdev Look like it's different as #1169 is for list formatting and this issue is above to <b> and <i> formating. 
As I notice when the user opens the formatting toolbar the first time then they need to click twice to activated formatting option.

So that issue need to fix.

**Comment by amincdev** [comment]
@dipskakadiya Yes, But this behaviour also fixed in that. Can you please check with `fix/1138`?

**Comment by dipskakadiya** [comment]
@amincdev Issue is still there `fix/1138`. I fixed that with this PR.

**Comment by amincdev** [comment]
@dipskakadiya Great, Thank you for confirming.
