### ISSUE TITLE
BB REST API - Groups Settings : Any member should be able to read group settings

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1500]
**Describe the bug**
When you display a group in a mobile app using BB REST API, any member should be able to get the group settings using the request below : 

`GET {{host}}/wp-json/buddyboss/v1/groups/6/settings?nav=group-settings`

Otherwize, there's no way for the member to know if he is allowed to manage photos, to create new album, to invite others, ... (all settings of the group available there : https://buddyboss.localhost/groups/teaching-ideas/admin/group-settings/). 

With the rest request `GET {{host}}/wp-json/buddyboss/v1/groups/6`, we can only know if current user "can_post" and "can_join".

**To Reproduce**
1. Log in with any member (which is not an organizer of the group)
2. Request `GET {{host}}/wp-json/buddyboss/v1/groups/6/settings?nav=group-settings`

For the moment, this request returns an error : 

```
{
  "code": "bp_rest_authorization_required",
  "message": "Sorry, you are not allowed to see the group settings.",
  "data": {
    "status": 403
  }
}
```

**Expected behavior**
The current logged in user should be able to make the request in order for him to know all of the permissions he has in the group.

I think that the code below should be removed from the file _class-bp-rest-group-settings-endpoint.php_, method _get_item_permissions_check_ (_line 225_)

```
// If group author does not match logged_in user, block update.
if ( true === $retval && ! $this->groups_endpoint->can_user_delete_or_update( $group ) ) {
	$retval = new WP_Error(
		'bp_rest_authorization_required',
		__( 'Sorry, you are not allowed to see the group settings.', 'buddyboss' ),
		array(
			'status' => rest_authorization_required_code(),
		)
	);
}
```

**Screenshots**
none

**Support ticket links**
none

**Comment by meetmakadiya** [comment]
@ExoGeek I check with member role login and check to show the proper result and if a user is not a member of the group then shwoing the error so working as expected. if I miss anything let me know thanks.

**Comment by meetmakadiya** [comment]
I believe we can already close this issue for now. If this issue comes up again, feel free to comment on the details here to reopen this issue.
