### ISSUE TITLE
Bug in Follow and Unfollow Tex Label

### ISSUE THREAD

**Issue by raftaar1191** [buddyboss/buddyboss-platform#1503]
**Describe the bug**
When I click on user that I am already following and to unfollow the text change to **Unfollow** but when I click on some other user to whom I am following or not following the first user where I have click previous to unfollow text change. Not sure it a bug or we have this feature. 
Please watch the below video for more information

**To Reproduce**
http://somup.com/cYQD6oXppE

**Expected behavior**
The Text should be directly change to Follow not Unfollow

**Screenshots**
http://somup.com/cYQD6oXppE

**Jira issue** : [PROD-912]

[PROD-912]: https://buddyboss.atlassian.net/browse/PROD-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by surajkrsingh** [comment]
@raftaar1191 
We tested this issue and found some situations like..
1. When we click on **Follow** state > it return to the **following** but whenever click on the **following** state the button text change into **unfollow** state (that is just notice kind of thing ) then you have to click on that once more to unfollow the member.
2. If you just click on unfollow state and click anywhere on the page it will return into the previous state that is following and this is not the case like happening when clicking on any other member follow button.

So, whenever you want to unfollow someone then you have to click twice consecutively.
See this - https://www.awesomescreenshot.com/video/4750177?key=1b020ba44fb30b6d1242c212f018064d

I think this is not a bug but yes we consider it as an improvement.
@KartikSuthar Can you please review this issue? and let me know, is fix required to not?

**Comment by dipskakadiya** [comment]
@surajkrsingh I think we should have only two-state, Following/unfollow. User getting confused with follow, following, unfollow . Definitely, this should be fixed.

I think. here we need better UX to differentiate status and action items
here,  follow, unfollow - action items.  Following - status.

CC: @sourabhmatolia @KartikSuthar
