### ISSUE TITLE
Duplicate entries of repeater fields in database bp_xprofile_fields table

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1513]
**Describe the bug**
Duplicate entries of  repeater fields in bp_xprofile_fields table

**To Reproduce**
1. Create Repeater Fields, ex: field 1, field 2, field 3
2. In front end, add values for the fields multiple times
3. check bp_xprofile_fields table, all entries are added and appear duplicated entries on the table

**Screenshots**
https://drive.google.com/file/d/1cUrY00kM8nIVXO0mh8Fl6TkwTxdKvsDD/view?usp=sharing
https://drive.google.com/file/d/1n22mFWBEdKQJ808KkcNvdjhbUYuHLTXo/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1176956824/75219

**Comment by bb-yudhisthir** [comment]
another ticket with duplicate repeater fields in frontend as well as backend https://secure.helpscout.net/conversation/1478103200/135311

**Comment by shyamwp14** [comment]
Repeater FIeld Set adding extra / duplicate fields (Frontend as well as backend)
https://secure.helpscout.net/conversation/1571931607/153478/

**Comment by janakkaneriya007** [comment]
This issue is fixed in this PR: https://github.com/buddyboss/buddyboss-platform/pull/2716
