### ISSUE TITLE
I can't increase the post size

### ISSUE THREAD

**Issue by rezariazi** [buddyboss/buddyboss-platform#1515]
**Describe the bug**
I am trying to increase the post size and even though the php.ini has been modified to 200MB, still can't increase the limitation from 32MB.

**To Reproduce**
I have changed the php.ini on the server

**Expected behavior**
Based on the attached screenshot, I should be able to change the limitation.

**Screenshots**
Please find the attached file

**Support ticket links**
N/A
<img width="1347" alt="Screen Shot 2020-09-20 at 3 16 23 PM" src="https://user-images.githubusercontent.com/28366948/93720116-fbe2f080-fb54-11ea-8364-684458f6a795.png">

**Comment by marienel21** [comment]
I can't reproduce this bug in my local with the latest version of the product.
