### ISSUE TITLE
The formatting in Post update looks broken with list. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1529]
**Describe the bug**
The formatting in Post update looks broken after its published. Please see the video attached for more detail.  

**To Reproduce**
Please follow the video, 

**Screenshots**
https://www.loom.com/share/11152a7593a140abbd826a9fac772df2

**Support ticket links**
https://secure.helpscout.net/conversation/1282706153/98836?folderId=3701249

**Comment by janakkaneriya007** [comment]
This issue is related with #1138 and it's fixed on related branch.

**Comment by sadrul** [comment]
@Anve-sri The issue seems already fixed and released. I have tested on sandbox site and got it working fine
Proof : https://www.loom.com/share/295d490814b14e0ea8a3c5a7be4ae937
Could you please cross check and close this issue
