### ISSUE TITLE
Forum on profile page is not working when Forum component page is set as home page

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1533]
**Describe the bug**
Forum on the profile page is not working when the Forum component page is set as home page, **this happens when using BuddyBoss Platform version 1.5.1 and later**. When using 1.5.0 and older versions the forum is working fine.

**To Reproduce**
1. Using the latest version of the platform, set Forum as homepage in Settings > Reading.
2. Go to the profile page and notice that the forum tab is missing.
3. **NOTE!! This happens only when using BuddyBoss Platform version 1.5.1 and later.**

**Expected behavior**
The forum tab on the profile page should work even if it is set as the homepage.

**Screencast**
https://cutt.ly/ZfXJrxv

**Screenshots**
![forum](https://user-images.githubusercontent.com/58522498/93941560-4fc22500-fd61-11ea-99b7-a65e253541d5.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1287902303/99810/

**Comment by marienel21** [comment]
bug nonexistent in the latest version. Tested in local
