### ISSUE TITLE
Change group term to other words in URL

### ISSUE THREAD

**Issue by janakkaneriya007** [buddyboss/buddyboss-platform#1537]
**Describe the bug**
I am working on one of the client project and came across one requirement where client wants to change "BuddyBoss Group" term to "Company". I was able to change the hardcoded group labels to word company labels but when it comes to change the URL from "groups" to "companies" it's not working fine. for more details refer the video.

**To Reproduce**
**Issue1:**
1. "BuddyBoss Theme" theme activated
2. try to change the group term to any word in URL of the groups by actions and filters
3. Not able change group term

**issue2:**
1. "BuddyBoss Theme" theme activated
2. try to change the group term to any word in URL of the groups by below code
function ts_change_groups_slug(){
	global $bp;
	$bp->groups->root_slug = 'companies';
	return $bp->groups->root_slug;
}
add_filter( 'bp_get_groups_slug', 'ts_change_groups_slug' );
add_filter( 'bp_get_groups_root_slug', 'ts_change_groups_slug' );
3. visit the members group page it's now showing correctly

**Expected behavior**
Should be able to change the group term to any word as per requirement.
Members groups page should show the correct layout for the group

**Screenshots**
https://www.loom.com/share/52f8c1979ece46f0b876c54f6d73011a

**Jira issue** : [PROD-910]

[PROD-910]: https://buddyboss.atlassian.net/browse/PROD-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mehulkaklotar** [comment]
We need to scope this properly for each every component in the plugin. We will need to allow changing slugs of every component.

@sourabhmatolia @dipskakadiya @chetansatasiya

**Comment by janakkaneriya007** [comment]
@sourabhmatolia @chetansatasiya @mehulkaklotar 

We also should make sure that the slug changing functionality will work for the RTL languages. I am currently working on one issue like this so I thought should share this with you all.

**Comment by sourabhmatolia** [comment]
@all

This issue is created to allow to change Social Group slug "group" from URL everywhere using Filters.
We will work on a separate Issue to provide option to change slug for all the components.
Thanks.
