### ISSUE TITLE
Profile picture looks blurry even when upload a high resolution picture.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1543]
**Describe the bug**
I have uploaded a high resolution profile picture but the photo looks blurry. 

**To Reproduce**
1. Profile picture on different places looks blurry in chrome but fine in firefox.
**Firefox:**  https://prnt.sc/1x24a1n
**Chrome:** https://prnt.sc/1x24dk2
2. Elementor Dashboard intro block has 150 x 150 PX image in area of 200 x 200 PX
3. Notice on profile and group picture uploader page is missing about image dimension

**Expected behavior**

1. Sharp profile image expected on different places like header, activity head in chrome like firefox.
2. Elementor Dashboard page should load 300 x 300 PX image instead of 150 x 150 PX
3. Show notice on profile and group picture uploader page : https://prnt.sc/1xp5y7z

**Support ticket links**
https://secure.helpscout.net/conversation/1266397546/90397/

**Comment by mahedihasannoman** [comment]
https://secure.helpscout.net/conversation/1488353411/137537?folderId=4314898

**Comment by angelic-joyce** [comment]
https://secure.helpscout.net/conversation/1559665198/150487?folderId=4465050

**Comment by sourabhmatolia** [comment]
**UPDATE**

@amincdev will do R & D to look for alternate solutions to handle profile picture cropping.

**Comment by patrickmcelwee** [comment]
We found this issue on our new site, and it is not affected by Firefox/Chrome use. To reproduce, you need to use an image that is not square, where the crop box will be a smaller part of the overall image.

Here are two images that illustrate the problem and should allow you to reproduce it. The first is the original photo, 3385 x 5077, and is similar to a photo taken on a phone that one of our users might upload. When this is uploaded to the crop tool, it is blurry _before any cropping takes place_, suggesting that the image is downgraded prior to displaying the crop screen.

![image](https://user-images.githubusercontent.com/808015/142647125-3bb2467a-e660-47db-99d6-7b35375acdfc.png)

Here's the original:
![PatrickMcElwee_sml](https://user-images.githubusercontent.com/808015/142645288-bd977a60-3513-4d67-a52b-65c5763d70da.jpg)

The second image was cropped by me in Photoshop. It is 2291 x 2291, and when uploaded to BuddyBoss and cropped by the website, it continues to look relatively sharp.

![PatrickMcElwee_square](https://user-images.githubusercontent.com/808015/142645262-57988021-8863-49f7-8e94-a490390947e5.jpg)

Here is a side-by-side of the final result in the two cases:
![image](https://user-images.githubusercontent.com/808015/142646296-f4866e8c-1d80-4009-83cd-f3904d956bac.png) 
![image](https://user-images.githubusercontent.com/808015/142646369-a328732f-48c6-4774-8abb-91b4b1fbd4b6.png)

I hope that's helpful and that you can reopen this ticket. I'm happy to assist however I can.
