### ISSUE TITLE
Visibility Settings of Repeater Fields not synced-in on Account Privacy

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#1544]
**Describe the bug**
Visibility Settings of Repeater Fields not synced-in on Account Privacy

**To Reproduce**
1. Create a Profile Field set, Repeater Set = Enabled
2. Add a single field, Visibility = Public, Allow Members to override
3. Go to Profile > Edit Profile > Select the profile set create
4. Add information, then edit visibility to Only Me
5. Save Changes
6. Profile dropdown > Account > Privacy
7. Visibility does not sync up

**Expected behavior**
Synced-up visibility settings on **Profile Visibility on Edit Profile** and **Account >Privacy Settings**

**Screenshots**
https://www.loom.com/share/db188ed830ec42d69054f88a3f188231

**Support ticket links**
https://secure.helpscout.net/conversation/1280187196/98309

**Comment by shyamwp14** [comment]
Support ticket links
https://secure.helpscout.net/conversation/1363723297/114208?folderId=4265312

**Comment by sourabhmatolia** [comment]
UPDATE

Here's how we should handle this:
https://www.loom.com/share/9745b78afd574ce49daae4ccc22c2196
