### ISSUE TITLE
Profile Completion for Social Network field

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1555]
**Is your feature request related to a problem? Please describe.**
The Profile Completion widget is currently requiring all the social network fields to be set. As per the customer, the Social Network field should already be considered as completed as soon as any of the social network field options have been filled out, since, some of the users do not have an account for all the Social Media.

**Describe the solution you'd like**
To have an option wherein the Admin can decide if all the social network links must be set or just any of them before the Profile Completion widget gets completed.

**Screenshots**
![social-network](https://user-images.githubusercontent.com/58522498/94309279-660ef180-ffaa-11ea-890e-db6f53de9a9c.jpg)
![widget](https://user-images.githubusercontent.com/58522498/94309281-660ef180-ffaa-11ea-8a7e-9355a28ce669.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1288563104/99929

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1447423718/129565/
