### ISSUE TITLE
Checkboxes on registration page label and checkbox/radiobuttons display below each other

### ISSUE THREAD

**Issue by Aloew88** [buddyboss/buddyboss-platform#1556]
Hello,

I have a problem and I can't figure out what's wrong.

I created a website with BuddyBoss but I have a weird issue with my checkboxes and radio buttons. 
They all display in a vertical row. But label on top checkbox below. See screenshot or check register page of my website. 

Link to my register form so you can see what's going on
[http://www.tgirl-chat.nl/registreer](url)

So I started testing on my localhost with a clean install first only BuddyBoss installed on default WordPress theme (Twenty Twenty)
That gave me the issue from the start, so I have the same problem on my host with the registration form.

**See below how my checkboxes appear with labels on top and not next to them.**
![image](https://user-images.githubusercontent.com/43612195/94321039-c8f28f80-ff8e-11ea-96d7-4b8cc66c32c8.png)

**This is only **BuddyPress** activated register form is normal.**
![image](https://user-images.githubusercontent.com/43612195/94318905-d3f6f100-ff89-11ea-8121-2f536d2115ed.png)

****BuddyBoss** activated and you can see no plugins only WP reset en BuddyPress deactivated.**
![image](https://user-images.githubusercontent.com/43612195/94319095-2e904d00-ff8a-11ea-964e-a5416577173c.png)

**And this is what happens.**
![image](https://user-images.githubusercontent.com/43612195/94319271-8929a900-ff8a-11ea-9861-80d791c287f7.png) 

Contacted BuddyBoss by email, and they tried to recreate the issue, but they didn't have the issue I am having.
They said to go here for help.

I'm totally lost since I'm trying to figure it out for days with no solution.

If you need more info please let me know.

**Comment by ZiadJ** [comment]
It shouldn't be too hard to fix with a couple of lines of CSS. If you can provide a sample link for the registration page that would help.

**Comment by ZiadJ** [comment]
It shouldn't be hard to fix with just a couple of lines of CSS. The link you provided does not show any checkboxes though so adding them back temporarily would help.

**Comment by Aloew88** [comment]
Hi ZiadJ, 

I have put it back. I was working on another solution with BuddyForms but that didn't work either for my needs.
As you can see all the checkboxes have the same issue on my registration page. 
I just want the label to appear next to the checkbox. Like it should

I'm not an expert at coding so if you could point out how to get this to work with CSS I will be greatly appreciated 

Let me know if you need anything else

**Comment by ZiadJ** [comment]
Try and add this to the theme CSS and you'll be good to go:
```
.bs-styled-checkbox {
 position:absolute;
 opacity:0
}
.bs-styled-checkbox+label {
 line-height:1
}
.bs-styled-checkbox+label:before {
 content:'';
 margin-right:10px;
 display:inline-block;
 vertical-align:text-top;
 width:20px;
 height:20px;
 background:#fff;
 border-radius:3px;
 border:1px solid #c9cbca
}
```
If you're not sure how to go about doing thati, however, then feel free to let me know and I'll guide you through.

**Comment by ZiadJ** [comment]
That's for the date selectors:
`
.datebox-selects label {
  display: inline-block !important;
}
.datebox-selects select {
  width: 100px;
}
`
However, it seems like you don't have the Buddyboss theme installed and activated so that could be the reason you're getting those issues.

**Comment by Aloew88** [comment]
Thanks so much ZiadJ this did the trick it's working... both the date and checkboxes are correct now.
