### ISSUE TITLE
You can not go to Forums setting while creating a group when using Persian forum slugs.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1557]
**Describe the bug**
When I want to create a group, the 1st and 2nd steps of the group creation form works fine, but from Forums step, it doesn't work. 

**To Reproduce**
Follow https://www.loom.com/share/1642b9a9643a4c249a878de5888a5fb4

**Expected behavior**

**Screenshots**
Provided 

**Support ticket links**
https://secure.helpscout.net/conversation/1285719008/99362?folderId=3701249

**Comment by janakkaneriya007** [comment]
@Anve-sri 
This issue is fixed here: https://github.com/buddyboss/buddyboss-platform/pull/1215

**Comment by sadrul** [comment]
@sourabhmatolia the issue is already fixed here https://github.com/buddyboss/buddyboss-platform/pull/1215 which is already released. I checked using release branch for both platform and buddyboss-theme and seems working fine
Proof: https://www.loom.com/share/7069fad621a148edbe07d0308014d085

**Comment by sadrul** [comment]
@imehedidev could you please check this and close it if already fixed.

**Comment by imehedidev** [comment]
Already resolved
