### ISSUE TITLE
Download media doesn't work when the media url contains "?" (signed url)

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1560]
**Describe the bug**
I do use WP Offload Media to offload medias to S3 and I've configured the plugin in order to use private link for each media (url needs to be signed in order to be accessed and displayed).

The link "download" doesn't work on the image theater because some characters in the file url are replaced (for example, "?" is replaced by "_".

**To Reproduce**
- Use signed URL to access your media
- Go to "Photos" page
- Click on one photo to display the theater
- Click on the "Download" link (at the right bottom)

**Expected behavior**
- User should be able to download media even if the url is signed

**Screenshots**
![image](https://user-images.githubusercontent.com/46819762/94410827-1aaa3e00-0178-11eb-9981-e7966c51821a.png)

![image](https://user-images.githubusercontent.com/46819762/94410571-cd2dd100-0177-11eb-8262-c04f9957a652.png)

**Support ticket links**
none

**Comment by ExoGeek** [comment]
Duplicate : #1578

**Comment by chetansatasiya** [comment]
@ExoGeek Can you check your issue with this branch https://github.com/buddyboss/buddyboss-platform/pull/1732 and see if it's working for you or not?

**Comment by ExoGeek** [comment]
@chetansatasiya Don't know if I still have to test this issue because @ankitguptaindia have made a loom video that still shows the bug.

In #1732 commits, I don't see any changes to media (photos) download (only document component).

**Comment by ExoGeek** [comment]
@chetansatasiya Everything is working fine. #1732 has corrected the issue. Thanks
