### ISSUE TITLE
Moderation (Block Members and Report Content)

### ISSUE THREAD

**Issue by dipskakadiya** [buddyboss/buddyboss-platform#1562]
**Is your feature request related to a problem? Please describe.**
Block user and Report Content Module

**Describe the solution you'd like**

Detailed scope shared in the documents below.

Doc Version
https://docs.google.com/document/d/1J3DnMnPYgDmZryghMRrTOlzIgpt2Im55aPddeNVJKtM/edit?usp=sharing

PDF Version
https://drive.google.com/file/d/12Wvk-otIv7CBSDH7inKtX9zUDtE2WqWl/view?usp=sharing

Internal Doc:
https://docs.google.com/spreadsheets/d/1fuDtOGSmE-1Zgj6uRThSZaNo_mehJ8yTfW7L8lOGtSc/edit?usp=sharing

**Comment by sourabhmatolia** [comment]
**UPDATE**

Docs shared above should be accessible to everyone. Thnx.
