### ISSUE TITLE
Reflected XSS when describing an image

### ISSUE THREAD

**Issue by Marnick39** [buddyboss/buddyboss-platform#1568]
**Describe the bug**
There is a reflected XSS vulnerability when entering javascript as part of the description of an image. This javascript code seems to be stored safely in the back-end because when the image is closed and opened again the description seems sanitized and does not run. Due to the reflective nature of the vulnerability, it has a rather limited impact.

**To Reproduce**
1. Go to an image which is part of a message (for example a message to someone, or a post in the forum)
2. Click on the image (to make the description/replies to it visible)
3. Click on 'add a description' or 'Edit' in the description area of the image.
4. Add a piece of javascript, for example '<script src=http://xss.rocks/xss.js? >'
5. See the XSS alert.

**Expected behavior**
Have no javascript run when entering it as part of the description of an image.

**Comment by sourabhmatolia** [comment]
@Marnick39 

Issue created above is released in Buddyboss Platform v1.5.3.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-3/

Please update the plugin to see the latest changes.

Thank you.
