### ISSUE TITLE
Insufficient filename sanitation when uploading a profile picture.

### ISSUE THREAD

**Issue by Marnick39** [buddyboss/buddyboss-platform#1569]
**Describe the bug**
It seems that the sanitation process for the filename is incomplete and produces an invalid filename.
Uploading an image with a strange name as a profile picture gets accepted and 'uploaded', but breaks later on in the procedure. It will show two broken images (image not found) and when you try to crop the 'image' it will throw an error. See screenshots below.

**Confirmed strange filenames:**  (feel free to test additional strings for list)

- ⁄**?.⁄..⁄.png

**To Reproduce**
1. Go to '<username>/profile/change-avatar/'
2. Click on 'Select your file'
3. Pick a file with a strange filename (list above)
4. Wait for upload to complete
5. See broken images
6. Try to crop (and fail)

**Expected behavior**
When entering an undesirable filename it needs to be sanitized before it is uploaded, this seems to be happening only partly here, since it does not upload the entire filename (the '*'s are removed from the filename), but still delivers a broken filename.
When trying to upload the same image as a cover photo, it results in an error: 'There was a problem uploading the cover photo.'.

**Screenshots**
![image](https://user-images.githubusercontent.com/17315511/94604768-ac54a100-0287-11eb-9f59-6775a76aeda1.png)
--
![image](https://user-images.githubusercontent.com/17315511/94604818-bb3b5380-0287-11eb-9ac3-326b3787ed94.png)

**Comment by janakkaneriya007** [comment]
@Marnick39 
I have tried to reproduce the issue on my local and couldn't reproduce it.
https://www.loom.com/share/e3d044b37a2c47f798b1d6539e11f281

**Comment by marienel21** [comment]
Bug not reproducible on the current version of the product.
