### ISSUE TITLE
Follow feature doesn't work

### ISSUE THREAD

**Issue by omojahed** [buddyboss/buddyboss-platform#1575]
**Describe the bug**

Follow button is not displayed.
Option "Allow your members to follow the activity of each other on their timeline" **ACTIVATED**
This behavior is visible even on demonstration instances.

**To Reproduce**
1. Go to Activity Settings
2. Activate "Allow your members to follow the activity of each other on their timeline"
3. Go to Members page
4. "Follow" button on members cards is not displayed

**Expected behavior**
"Follow" button must be displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/7328295/94684764-cbefd600-0328-11eb-91cb-58b3f6e91f74.png)

![image](https://user-images.githubusercontent.com/7328295/94684839-ea55d180-0328-11eb-856a-90f9daee0757.png)

**Support ticket links**

**Comment by manishpatolia** [comment]
@omojahed I have checked the above issue with the dev branch and on our demo and I seem working fine for me.
See my proof and let me know if I'm wrong. 

https://www.loom.com/share/9645fb03cb304a329435b5910730d596
