### ISSUE TITLE
When a user is an instructor, some of the search results are not displaying

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1586]
**Describe the bug**
When a user is an instructor, some of the search results are not displaying like the courses, blogs, and forums.

**To Reproduce**
1. Install the Multiple Instructor Role Plugin (https://www.buddyboss.com/resources/docs/integrations/learndash/multiple-instructors-for-learndash/)
2. Assign an instructor role to a user.
3. Log in using the user with the instructor role
4. Try to search for a course or a blog
5. See the error

**Screencast**
https://cutt.ly/jf88ZJm

**Screenshots**
![search result](https://user-images.githubusercontent.com/58522498/94876363-09b84000-048a-11eb-9962-5ae6fa19ace3.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1296243977/101249

**Comment by cduff915** [comment]
Note: Multiple Instructors for LeatnDash (Instructor Role) is an addon to LearnDash and requires LearnDash to be installed first.

**Comment by ayron-paul** [comment]
A solution shared by the customer, can be inserted in functions.php:

```
/**
* Allow frontend ajax queries without author checks for proper data.
*
* @param object $query WP_Query
* @return object Updated WP_Query session.
* @author Kumar Rajpurohit <kumar.rajpurohit@wisdmlabs.com>
*/

function ir_custom_filter_buddyboss_queries($query) {

  // Check if ajax query
  if (wp_doing_ajax()) {

    // Check if user is logged in and instructor
    if (! is_user_logged_in() || ! function_exists('wdm_is_instructor') || ! wdm_is_instructor()) {
      return $query;
    }

    // Check if buddyboss course filter request
    if (! empty($_GET) && array_key_exists('action', $_GET) && 'buddyboss_lms_get_courses' == $_GET['action']) {
      $query->set('author__in', array());
    }

    // Check if buddyboss member filter request
    if (! empty($_POST) && array_key_exists('action', $_POST) && 'members_filter' == $_POST['action']) {
      $query->set('author__in', array());
    }

    // Check if buddyboss search ajax
    if (! empty($_POST) && array_key_exists('action', $_POST) && 'bp_search_ajax' == $_POST['action']) {
      $query->set('author__in', array());
    }

  }

  return $query;

}
add_filter('ir_filter_instructor_query', 'ir_custom_filter_buddyboss_queries');
```
