### ISSUE TITLE
Lack of Gutenberg Integration with Boss Theme

### ISSUE THREAD

**Issue by maralihart** [buddyboss/buddyboss-platform#1588]
**Describe the bug**
When changing font size on Gutenberg blocks, the font doesn't change on the actual site. We are using Boss Theme.

**To Reproduce**
1. Go to the Page Editor
2. Using Gutenberg, change font of text
3. View page

**Expected behavior**
The font to match whatever is on the Gutenberg preview

**Comment by mikejyoung** [comment]
We weren't able to reproduce this issue in the latest versions of our products, so we are closing this issue.
