### ISSUE TITLE
Not play audio files

### ISSUE THREAD

**Issue by bhavik-s-eq** [buddyboss/buddyboss-platform#1593]
**Describe the bug**
Once we create reply or topic using media like mp3 . Show player not working 

**To Reproduce**

**Expected behavior**
Working files
![git1](https://user-images.githubusercontent.com/67588051/95078764-4a86b200-0733-11eb-92e7-9fa916109300.png)
![git1](https://user-images.githubusercontent.com/67588051/95078789-51152980-0733-11eb-88d0-2cc6e50e8924.png)

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by chetansatasiya** [comment]
@bhavik-s-eq I would recommend you to go fully descriptive while opening the issues and all the information as much as you can like this https://prnt.sc/utf9pn

**Comment by bhavik-s-eq** [comment]
Sure @chetansatasiya

**Comment by marienel21** [comment]
This is not reproducible in the current version. Tested in Activity and Forums, audio files are working fine.
