### ISSUE TITLE
Profile Fieldset tabs are being cached

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1595]
**Describe the bug**
When object caching is enabled, the profile fieldset tabs are not displaying accordingly for different profile types in the "Edit Profile" page.

**To Reproduce**
1. Enable object caching.
2. Create some profile types and assign them to different users.
3. Create multiple fieldsets with different availability for each profile type.
4. Try to log in using different users with different profile types.
5. See the error.

**Screencast**
https://cutt.ly/IgqBcjQ

**Screenshots**
![obj-cache-profile](https://user-images.githubusercontent.com/58522498/95140788-4180f980-07a2-11eb-9264-c404a5da9624.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1297684337/101479

**Comment by imehedidev** [comment]
When object cache is enabled users are getting an error message: https://prnt.sc/ul28qa when they try to delete a user who has a profile type.
