### ISSUE TITLE
When you copy paste from the clipboard, the image do not appear in forum.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1606]
**Describe the bug**
 If you paste an image in a forum from clipboard, that posts it visually however when the post is saved and reopened the image is missing. 

**Screenshots**
[pasting images.zip](https://github.com/buddyboss/buddyboss-platform/files/5346018/pasting.images.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1298100968/101522/

**Comment by mikeemesser** [comment]
Same behavior in status updates!
