### ISSUE TITLE
All tags are lost upon updating a discussion

### ISSUE THREAD

**Issue by ZiadJ** [buddyboss/buddyboss-platform#1610]
**To Reproduce**
1. Create a discussion with a few tags
2. Edit the discussion
3. Added tags are no longer there

**Expected behavior**
Tags need to be listed in the tags field during edits

**Comment by bb-yudhisthir** [comment]
User should edit and remove the tags on edit screen, currently only it can be done by admin from the dashboard.
https://secure.helpscout.net/conversation/1543543461/147770/

**Comment by mightyx** [comment]
Hey,

I face the same issue. I noticed it is possible for an admin to edit the post also in the frontend. He will then also not see the tags but when he saves, it will be fixed most of the time.

**Comment by marienel21** [comment]
Hi @ZiadJ @mightyx,

The issue mentioned above is released in BuddyBoss Platform v1.7.6

You can check release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-6/

Please update the plugin to see the latest changes.

Thank you.
