### ISSUE TITLE
Gravatar is not displayed in received email (Gmail)

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1612]
**Describe the bug**
After making a friend request, an email is sent. That email contains the avatar of both member. But, If a member uses gravatar as avatar, that gravatar is not displayed in the received email.

When I have a look to the "original message" in order to access the html code of the email, I see that : 
`
<img alt="" src="https://www.gravatar.com/avatar/353012ab0905f16de9bb271696fa3a90?s=280&amp;r=g&amp;d=identicon%09%09%09%09%09%09%09%09%09%09%09%09" width="140" height="140" style="margin:0; padding:0; border:none; display:block;" border="0">`

But as you can see in the screenshot section below, the gravatar is not displayed.

Ps : You can also see that the url seems to be mal formated because you don't have "identicon" gravatar (instead, you have default gravatar image).

**To Reproduce**
1. Do a friend request to a member using gravatar
2. Go to the inbox of your friend (in my case : Gmail)
3. Do you see the gravatar ?

**Expected behavior**
Show the avatar of the member.

**Screenshots**
Gravatar is not displayed : 

![image](https://user-images.githubusercontent.com/46819762/95569656-258d8a00-0a26-11eb-93eb-5eb78789a652.png)

**Support ticket links**
none

**Comment by ExoGeek** [comment]
With the latest version of BuddyBoss Platform, this issue seems to be resolved.

![image](https://user-images.githubusercontent.com/46819762/97354739-26337680-1896-11eb-8372-c4be8475b6e0.png)

**Comment by ExoGeek** [comment]
Very strange, I still have that error : 

![image](https://user-images.githubusercontent.com/46819762/101277824-694b0880-37b7-11eb-9bef-4e7d8e2d862e.png)

Here is the code : `<img alt="" src="https://www.gravatar.com/avatar/16ab422e281b1274ca4f73c41053a89f?s=280&amp;r=g&amp;d=identicon%09%09%09%09%09%09%09%09%09%09%09%09" width="140" height="140" style="margin:0; padding:0; border:none; display:block;" border="0">`

**Comment by meetmakadiya** [comment]
@ExoGeek Try to replicate with the latest version(1.7.6) but not that might be fixed with the latest version(1.7.6). please check the attachment.
http://i.imgur.com/y4Relsq.png
