### ISSUE TITLE
Default Grid view not working within Groups Type

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1613]
**Describe the bug**
If we create a group type and assign some group on that category then when we this group category then the default grid view is not working. It always shows the list view.

https://prnt.sc/uw2fee

**To Reproduce**
1. Create a group type 
2. Select some group on that category
3. View that group category
4. See the default Grid view is not working but the grid view button is Active
https://prnt.sc/uw2fee

**Expected behavior**
Should the grid view by default as Buddyboss settings

**Screenshots**
https://prnt.sc/uw2fee

**Support ticket links**
https://secure.helpscout.net/conversation/1298601849/101641?folderId=3955985

**Comment by manishpatolia** [comment]
@jakir-git 
I have checked with the latest pull and also on our demo but I seem working fine for me.
Please see my proof and let me know if I'm checking any step wrong.

https://www.loom.com/share/4a98a425d70f4600a0c7a058fc06c56a

**Comment by jakir-git** [comment]
@manishpatolia 

Please see this video
https://www.loom.com/share/bd0c8fc6fc184d68a60b6e61f33e21db?from_recorder=1

The issue is only when we want default Grid View, not list view.

**Comment by meetmakadiya** [comment]
@jakir-git 
I check with the latest version on the dev site and did not replicate the issue on the dev site.
please refer video and let me know if I miss anything. 
https://www.loom.com/share/be65be8604614f2cbf5691ee56d389dc
