### ISSUE TITLE
Activity Feed Comments on Forum Discussions do not Sync

### ISSUE THREAD

**Issue by mikeemesser** [buddyboss/buddyboss-platform#1619]
**Describe the bug**
If someone comments to a forum notification from within the activity feed, this comment is not synced to the forum discussion itself. This behavior is very confusing for users, because that way every single posting in a forum can become part of an indefinite number of completely separate threads. This is totally useless.

I consider it a bug, because this feature (commenting in the activity feed) works as expected for group posts and blog posts. Forum discussions are the only place where activity feed comments are not synced.

**To Reproduce**
1. Post to a forum
2. Comment on the corresponding notification within the activity feed (which, for average users, is not discernible from the forum posting itself)
3. See if the comment shows up as a comment to the posting in the forum itself. It doesn't.

**Expected behavior**
If someone comments to a piece of content, one would expect that the comment appears in the same places the original content appears.

**Comment by khunteebwar** [comment]
I also would like to request BuddyBoss team to take action on this bug asap. It is not okay to see the comments are disappearing in the activity feeds. The comments should be synced or integrated to the original thread.

**Comment by fabiomail** [comment]
Agree. It is a big deal for a community platform.

**Comment by rolloverbond** [comment]
Ditto the above comments. We don't use WP comments and only forum discussion replies and so there is no functionality to respond to discussions from within the activity feed.

**Comment by Ianpax** [comment]
It would help significantly! Much better UX!

**Comment by TokumeiJG** [comment]
1000% agree.  I intentionally hid the "Comment" button for Forum posts in the activity feed because it was confusing my users...

**Comment by ChristianVernize** [comment]
Agreed! When people comment on the feed it doesnt count as an answer to the discussion, so apperently no one asnwer it!
