### ISSUE TITLE
Profile Types cannot be translated with WPML

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1620]
**Describe the bug**
When Profile Types are set to be translated via WPML, this gets treated as another entry of profile type for a different language, this should only be treated as string, at least for the title. Once the profile type is created on a different language, it doesn't take effect on the members page.

**To Reproduce**
1. Install WPML , setup a different language and setup language switcher for frontend
2. Create Profile Types and set as translatable
3. Edit the created Profile Type in different language (you will redirected to a new entry for the language)
4. Assign the created Profile Type to a User
5. Go to Members page in front end, try to select a different language 
6. see error

**Expected behavior**
Profile Types should be treated as string and not as a new entry. 
The translation should take effect

**Screenshots**
https://drive.google.com/file/d/1OITNC1o9MYsizLwuWRWNMA6nG1vwllIA/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1299740855/101799

**Jira issue** : [PROD-904]

[PROD-904]: https://buddyboss.atlassian.net/browse/PROD-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mahedihasannoman** [comment]
Hi @emmanoctaviano , BuddyBoss platform is not fully compatible with WPML also WPML is not in integration list. So it could be a feature request for now.
