### ISSUE TITLE
BB REST API - Groups Endpoint : Ability to retrieve hidden group info when invited

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1628]
**Describe the bug**
When a user is invited to join a hidden group, that user should be able to retrieve some informations about the group via the REST API.

At least the name of the group and the avatar.

**To Reproduce**
1. User1 created a hidden group
2. User1 invites User2 to join the group
3. User2 lists all group invites using the REST API `GET {{host}}/wp-json/buddyboss/v1/groups/invites`
4. User2 wants to see at least the name of the group using the rest api `GET {{host}}/wp-json/buddyboss/v1/groups/27/`

For the moment, User2 receives the response below : 
```
{
  "code": "bp_rest_authorization_required",
  "message": "Sorry, you cannot view the group.",
  "data": {
    "status": 403
  }
}
```

**Expected behavior**
A user should be able to access some information about a hidden group for which he is invited to join.

**Screenshots**
none

**Support ticket links**
none

**Comment by Thierry333** [comment]
This is a real problem in the BuddyBoss app: when an invitation to a hidden group is sent to someone, it cannot be viewed or accepted in the app!!! Can you please correct this bug

**Comment by meetmakadiya** [comment]
@Thierry333 regarding the hidden group invite through an app and accept from an app is working as expected please find the attachment video.
https://www.loom.com/share/fcfd14fa12bc414bbd82efb2094f29a0

**Comment by ExoGeek** [comment]
Hello @meetmakadiya Could you please check the invitation scree

1. Go to More
2. Click on your name (profile)
3. Click on Groups
4. Click on "Invitations"

In that screen, you do not see hidden group invitation (only private and public group invitations).

=> In the notification screen, you can see the invitation.
![Screenshot_20210916-104423_Cryptophilo](https://user-images.githubusercontent.com/46819762/133582151-164a9c60-aae3-4c05-9d1f-836131163f3b.jpg)

=> In the screen "group invitation", you don't see the invitation because the group is hidden.
![Screenshot_20210916-104408_Cryptophilo](https://user-images.githubusercontent.com/46819762/133582152-a837ad67-d3e9-4693-a44e-e97b6d6407ad.jpg)

**Comment by meetmakadiya** [comment]
@ExoGeek replicated the issue and pass to the product team and issue related to the App so we create the issue on app repo(private) and I will update here once issue fixed.
