### ISSUE TITLE
Preview of message editor and sent message is different

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#1637]
**Describe the bug**
When user is editing the message, formatting of the message is different than editor formatting.

**To Reproduce**
1. Go to Message reply or compose message
2. Type any word or bullet list and send it.
3. now type same text as message just sent and compare them visually.

**Expected behavior**
It should be same formatting for both sent message and in the editor.

**Screenshots**
https://prnt.sc/v0dt1j

**Comment by amincdev** [comment]
This issue is related to the theme. Closing this and created in theme: https://github.com/buddyboss/buddyboss-theme/issues/1130
