### ISSUE TITLE
The Group send invites list itself is not able to load more names when scrolling down

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1647]
**Describe the bug**
The list of members has an issue to load in Group send invites. the list itself is not able to load more names when scrolling down. Works in other browsers and diff locations.

**To Reproduce**
See this video
https://www.loom.com/share/5aa75f0fa5194da0b384561e3eca7773

**Expected behavior**
Should able to load more names when scrolling down

**Support ticket links**
https://secure.helpscout.net/conversation/1308180589/103192?folderId=3955985

**Comment by amincdev** [comment]
@jakir-git I just checked and it is working fine. Closing this issue. Please re-open if you find an issue related to this.

Proof: https://www.loom.com/share/8819f962ee664c5d814e582e3bf5ee0b
