### ISSUE TITLE
Group activity is not being included in the network search

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1651]
**To Reproduce**
1. Make sure the Activity is activated in the Network Search setting. https://i.ibb.co/QP2Qjm9/network-search.jpg
2. Go to any group.
3. Post an update on the group feed.
4. Now, try to search the activity you just posted on the group using the network search. https://i.ibb.co/WKfVGgb/search.jpg
5. Notice that there will be no search result.

**Expected behavior**
Group activity should be included in the Network Search just like the group activity comments.

**Screenshots**
![group activity search](https://user-images.githubusercontent.com/58522498/96363946-2d59d680-116a-11eb-94d0-a541b8858b00.jpg)
![group activity search2](https://user-images.githubusercontent.com/58522498/96363947-2df26d00-116a-11eb-9829-d3e2e6945f13.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1297979153/101511

**Comment by marienel21** [comment]
This bug is no longer reproducible on the latest version of the Platform. 
![image](https://user-images.githubusercontent.com/77659570/129491370-71604506-9a34-4ab5-b134-ec7edda3401e.png)

**Comment by bb-yudhisthir** [comment]
As per checking its not replicable now http://somup.com/crQ2e8raau, closing this issue
