### ISSUE TITLE
Elementor Pro post widget excerpt length

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1652]
**Describe the bug**
When adding the Elementor Pro post widget on a page, the excerpt length didn't change. Switching with Twenty twenty theme worked well.

**To Reproduce**
1. Create new page and edit with elementor
2. Add new elementor post widget.
3. Change the excerpt length of this widget.

**Expected behavior**
Excerpt length of Elementor post widget should worked while the Buddyboss Theme activated

**Screenshots**
https://www.loom.com/share/233db3fd2afb483fb771862b2acff41f

**Comment by annrra** [comment]
This is an issue coming from theme
Issue is moved into buddyboss-theme - https://github.com/buddyboss/buddyboss-theme/issues/1140
