### ISSUE TITLE
After hitting the Unfollow button on a single member, the Follow button becomes blank.

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1656]
**Describe the bug**
After hitting the Unfollow button on a single member, the Follow button becomes blank.

**To Reproduce**
https://www.loom.com/share/405faaa751b741b3967929a9f388fea9?from_recorder=1

**Screenshots**
https://www.loom.com/share/405faaa751b741b3967929a9f388fea9?from_recorder=1

**Support ticket links**
https://secure.helpscout.net/conversation/1303317428/102336?folderId=3955985

**Comment by amincdev** [comment]
This issue is related to the theme. So, Created a new one in theme and closing this one: https://github.com/buddyboss/buddyboss-theme/issues/1149
