### ISSUE TITLE
{{group.name}} email token is not working in email notifications

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1657]
**Describe the bug**
{{group.name}} email token is not working in email notifications: http://prnt.sc/uwjk70

**Screenshots**
http://prnt.sc/uwjk70

**Support ticket links**
https://secure.helpscout.net/conversation/1299751429/101802

**Possible solution**

File number `bp-messages/bp-messages-functions.php`

Line number 820

replace

```
$group      = bp_messages_get_meta( $id, 'group_id', true );
$group_name = bp_get_group_name( groups_get_group( $group ) );
```

with 

```
$group      = bp_messages_get_meta( $id, 'group_id', true );
if ( ! $group && isset( $_POST[ 'group' ] ) ){
	$group  = sanitize_text_field( $_POST[ 'group' ] );
}
$group_name = bp_get_group_name( groups_get_group( $group ) );
```

Solution provided by @shohel 

**Jira issue** : [PROD-902]

[PROD-902]: https://buddyboss.atlassian.net/browse/PROD-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by austere-rm** [comment]
I reported this bug (ticket 101802). Why is it labelled `can't reproduce`? The bug was successfully reproduced on the staging and patched, but not fixed.
