### ISSUE TITLE
Mention not tagging correctly when users have same Nickname

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1658]
**Describe the bug**
Users have the capability to change Nicknames which is used for @Mentions, however, when users have the same Nicknames, the tagging does not work correctly. 
Example:
User1 nickname: John Doe
User2 nickname: John
When you go to User2 profile and write something to his timeline, this gets to show on User1 timeline and this tags him, instead of the post going to User2 and tag him.

**To Reproduce**
1. Edit two user profiles and change them to have similar nicknames. user1: John Doe, user2: John
2. View user2 profile and write something on his timeline
3. Visit user1 timeline in his profile

**Expected behavior**
When tagging or writing to someone, this should tag correctly showing on correct timeline
Another solution is to have restriction to user different nicknames

**Screenshots**
https://drive.google.com/file/d/19L99ZJyvWOBQYLWJx-1vn9kBXMJFr9IR/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1301944518/102164

**Jira issue** : [PROD-901]

[PROD-901]: https://buddyboss.atlassian.net/browse/PROD-901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Shamina07** [comment]
https://secure.helpscout.net/conversation/1574721725/154051?folderId=3709080
