### ISSUE TITLE
Hidden members are appearing when inviting to join the group.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1660]
**Describe the bug**
When a user's profile type is set to be Hidden for the member directory, the user is still visible when someone creates group invite step.

Profile Type: https://prnt.sc/v23fqv
User Emily: https://prnt.sc/v239xw
When creating a Group and sending invites, Emily is visible - https://prnt.sc/v23b33

**To Reproduce**
https://screencast-o-matic.com/watch/cY6qjk7An2

**Expected behavior**
The hidden profile type's members should not appear anywhere on the site.

**Support ticket links**
https://secure.helpscout.net/conversation/1312876528/103896?folderId=3701248

**Comment by janakkaneriya007** [comment]
@furqanbb 

https://prnt.sc/11fvrml

This setting will just hide members from the members directory not ftom the group invitation screen.

**Comment by furqanbb** [comment]
@janakkaneriya007 If a user is hidden from the Members Directory, it should not be shown anywhere on the site.

**Comment by furqanbb** [comment]
Confirmed. This is the default behavior. Closing this one.
