### ISSUE TITLE
Buddyboss Platform Pro Integration

### ISSUE THREAD

**Issue by ragnabnet** [buddyboss/buddyboss-platform#1664]
Hello, is there any plan to make buddyboss platform pro integrate with the google meet?
Since google meet is the biggest platform for teacher to teach because we can connect it to the google classroom also.

**Comment by marienel21** [comment]
Hi @ragnabnet ,
	
Thank you for your feature request.
	
We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on and suggest new features on our public roadmap: http://buddyboss.com/roadmap I'll be closing this issue now to keep our GitHub issues focused on tasks that are ready for development.
	
Marienel
BuddyBoss Product Team
