### ISSUE TITLE
Medium Editor_ Formatting Option (Ordered, Unordered List Format and Link) related issue.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#1668]
**Describe the bug**
**Issue 1:** 
When we use Ordered and Unordered List formatting option while creating update, discussion and while sending replies and messages then list are not appearing in proper format.
https://prnt.sc/v3qczq
https://prnt.sc/v49lf1
https://prnt.sc/v49l67

**Issue 2:**  
Link option available under Formatting option is not working on FIREFOX Browser.

**To Reproduce**
Issue 1:
1. Use Numbered List formatting option available under formatting options of Editor on News Feed, Forum, User profile and Messages.

and
Issue 2:
1.  Open website in Firefox.
2. Use Link option available under formatting options of Editor on News Feed, Forum, User profile and Messages.

**Expected behavior**
Ordered/Unordered List and Link option must work properly.

**Screenshots**
https://www.loom.com/share/a84bae99410a4c96abf68354a1854bce
https://prnt.sc/v3qczq
https://prnt.sc/v49lf1
https://prnt.sc/v49l67

**Comment by amincdev** [comment]
@mohit-buddyboss
The first issue you are showing is already fixed here: https://github.com/buddyboss/buddyboss-platform/pull/1169

**About Firefox issue:** I found that when you don't have text and yet you try to add a link then Chrome simply add URL as text. But, in Firefox if there's no text then it does not add a link. This is intentional behaviour of Firefox. Check here: https://bugzilla.mozilla.org/show_bug.cgi?id=895510 (Check the last comment, which is dated 5 months ago.)

**Comment by mohit-buddyboss** [comment]
> @mohit-buddyboss
> The first issue you are showing is already fixed here: #1169

Okay, Thank You !
> 
> **About Firefox issue:** I found that when you don't have text and yet you try to add a link then Chrome simply add URL as text. But, in Firefox if there's no text then it does not add a link. This is intentional behaviour of Firefox. Check here: https://bugzilla.mozilla.org/show_bug.cgi?id=895510 (Check the last comment, which is dated 5 months ago.)

@amincdev In Firefox if we add text then also link functionality is not working.  Video : https://www.loom.com/share/faccc33a65df43789b0eca349fffa7eb

**Comment by amincdev** [comment]
@mohit-buddyboss Yes, correct. In Firefox if you have no text selected while adding a link then it does not work as I said earlier. User needs to select text before adding a link.

**Comment by mohit-buddyboss** [comment]
Issue resolved in #1169 PR
