### ISSUE TITLE
BuddyBoss Wall Time Stamp conflict

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1669]
**Describe the bug**
The Time Stamp on a post disappeared when the BuddyBoss Child theme is activated. Yes, it disappears with the fresh child theme. Video: https://www.loom.com/share/de2f92ffb58647feb32fc8a12526d5a2

[Note: No issues with the BuddyBoss Parent theme]

**To Reproduce**

1. Install and activate BuddyBoss Wall
2. Install and activate the BuddyBoss Child theme
3. Check the Activity Feed

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1215090645/81682

**Jira issue** : [PROD-900]

[PROD-900]: https://buddyboss.atlassian.net/browse/PROD-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by meetmakadiya** [comment]
@imehedidev 
Add below code on buddyboss-wall plugin so fix the issue.
file-location: public_html/wp-content/plugins/buddyboss-wall/templates/bp-nouveau/activity/entry.php
search function bp_activity_action() and below that function add code snippet. 

`<p class="activity-date">
<a href="<?php echo esc_url( bp_activity_get_permalink( bp_get_activity_id() ) ); ?>"><?php echo bp_core_time_since( bp_get_activity_date_recorded() ); ?></a>
				<?php
				if ( function_exists( 'bp_nouveau_activity_is_edited' ) ){
					bp_nouveau_activity_is_edited();
				}
				?>
			</p>`

once code added looks like this: http://i.imgur.com/CL4gBFy.png
