### ISSUE TITLE
HTML preformatting not working on Activity feed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1688]
**Describe the bug**
On previous version of the BuddyBoss Platform, writing formatted HTML on text editor and pasting on Activity works, after the update, HTML are being stripped down after pasting. This is also happening on forums

**To Reproduce**
1. Go to text editor, preferably in Post or Page where you can create an HTML formatted text in Gutenburg block
2. Create a bulleted list
3. Copy the bulleted list and paste on Activity feed

**Expected behavior**
Tested this on previous version of Platform v1.5.2 and this works, even with the latest theme
After Platform v1.5.3 update, the HTML are being stripped down when pasted on Activity feed, also on forums

**Screenshots**
https://drive.google.com/file/d/1aeIO7evFPdOS-jHTNlYgitDEGSICFXMM/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1314303207/104108
https://secure.helpscout.net/conversation/1324102061/105998

**Comment by MitchRosal** [comment]
https://secure.helpscout.net/conversation/1525319086/144414?folderId=3701391
