### ISSUE TITLE
Password reset email is not displaying properly when Paid Membership Pro is active

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1704]
**Describe the bug**
When Paid Membership Pro is active along with the BuddyBoss Platform, the password reset email source code contains several `<BR>` tags causing to have unnecessary spaces on the final output.

**To Reproduce**
1. Activate Paid Membership Pro
2. Go to the reset password page.
3. Try to reset your password.
4. Check the email and see the error

**Screenshots**
![pmpro](https://user-images.githubusercontent.com/58522498/97456427-d4611e00-1973-11eb-8d06-1cee82550acf.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1300227041/101884
https://secure.helpscout.net/conversation/1322282892/105612

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1321809440/105460/
