### ISSUE TITLE
Provide Media/Document item Permalink

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#1707]
**Is your feature request related to a problem? Please describe.**

Currently, we don't have Single page link for media/document.

When searching any media/document then this is redirecting to photos page instead of particular media so if any image is listing in bottom of photos page after load more then it's hard to find.
Particular searched image should appear on clicking search result.

**Describe the solution you'd like**

It simply open the respective image only when click on image from search result instead of listing all images.

https://www.loom.com/share/36516962e61448e7ba7d6076a5fd8eac

**Support ticket links**
NA. Reported by QA.

**Comment by ankitguptaindia** [comment]
@sourabhmatolia Its important as per UX point of view.
Please assign milestone to fix.

cc
@dipskakadiya If this is part of this PR https://github.com/buddyboss/buddyboss-platform/pull/1488  please fix then.

**Comment by sourabhmatolia** [comment]
@ankitguptaindia 

Agree.

@dipskakadiya 

It should redirect to Photos tab in Profile but it should also open a Photo popup instantly showing image selected from the search dropdown or screen.

**Comment by dipskakadiya** [comment]
Based on Discussion with @sourabhmatolia,
We going to open a single activity page which attached to the media/Document.
