### ISSUE TITLE
The JS script magnific-popup.js is loaded twice (platform + theme)

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1712]
**Describe the bug**
It seems that the script magnific-popup.js is loaded twice when using BuddyBoss Platform + BuddyBoss Theme.

**To Reproduce**
Test your site using gtmetrix.

**Expected behavior**
Load that script once (the latest version)

**Screenshots**
![image](https://user-images.githubusercontent.com/46819762/97703333-be0cac80-1ab0-11eb-8776-e558b67e16d5.png)

**Support ticket links**
none

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Issue mentioned above is released in BuddyBoss Theme v1.6.6

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-theme-releases/1-6-6/

Please update the Theme to see the latest changes.

Thank you.
