### ISSUE TITLE
Group email notification via group activity feed

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1717]
**Describe the bug**
When adding a new content on activity feed inside group section, the group email notification didn't follow the format 
especially those paragraph style and breaks.

**To Reproduce**
1. Go to any group section.
2. Add some new post or update on activity feed of that have some paragraph style like bold, italic, etc especially breaks.
3. Once posted, check the email notification for this feed.

**Expected behavior**
The paragraph format on group email notification should follow the style according to post in activity feed.

**Screenshots**
https://www.dropbox.com/s/yi2aflqp96vetts/BuddyBossEmailFormattingProblem.mp4?dl=0
https://prnt.sc/vacxf6
https://prnt.sc/vacyxv

**Support ticket links**
https://secure.helpscout.net/conversation/1304863379/102597
https://secure.helpscout.net/conversation/1321858215/105481

**Comment by mahedihasannoman** [comment]
Hi @jrbuddyboss , This is not our issue. It is a third party plugin issue. "BuddyPress Group Email Subscription" plugin itself is removing HTML from email content. Possible could be adding the below lines in child themes functions.php file.

remove_filter( 'ass_clean_content', 'strip_tags', 4 );
add_filter( 'ass_clean_content', 'wp_kses_post', 4 );

You can close this issue.
