### ISSUE TITLE
Forum reply is being saved but email is not being sent when Paid Memberships Pro – bbPress Add On is active

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1718]
**Describe the bug**
Forum reply is being saved but email is not being sent when Paid Memberships Pro – bbPress Add On is active. The Post button is spinning.

**To Reproduce**
Steps to reproduce the behavior: https://www.loom.com/share/a8bede5af7e842ce8f1b70f7fd1d1617

**Expected behavior**

**Support ticket links**
https://secure.helpscout.net/conversation/1320852821/105191

**Comment by jrbuddyboss** [comment]
Related ticket: https://secure.helpscout.net/conversation/1348189948/110894

**Comment by jrbuddyboss** [comment]
@kent-carlo Confirmed with a client that the issue was already fixed: https://prnt.sc/1qhtfjr

**Comment by kent-carlo** [comment]
Thanks @jrbuddyboss
