### ISSUE TITLE
Getting PHP notices when using the BB platform with PHP 7.4 version

### ISSUE THREAD

**Issue by raftaar1191** [buddyboss/buddyboss-platform#1719]
**Describe the bug**
Getting PHP notices when using the Platform with PHP 7.4 version
```
Warning: get_headers(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /wp-content/plugins/buddyboss-platform/bp-core/bp-core-avatars.php on line 691
```

**To Reproduce**
1. Create a new WP site with PHP 7.4 version
2. Install BB theme and Platform in that 
3. Import dummy data from the Platform Tools sections
4. Now Try to view any user profile and you will see PHP notices

**Expected behavior**
There should not be any Notices

**Screenshots**
![image](https://user-images.githubusercontent.com/22215595/97779476-58015180-1ba4-11eb-882b-97531f75dae3.png)

**Support ticket links**
None

**Comment by davidmabelle** [comment]
Also Warning: Invalid argument supplied for foreach() in /kunder/gmailc_6254/cocrea_8883/public/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-theme-settings.php on line 26

**Comment by dipskakadiya** [comment]
The solution we should try for fixing issue `Warning: get_headers(): SSL operation failed with code 1.`

https://stackoverflow.com/questions/37274206/get-headers-ssl-operation-failed-with-code-1

**Comment by dkvasani** [comment]
Hi @sourabhmatolia I am not able to generate this issue. I have PHP 7.4 and WordPress 5.6 and try to import data buddypress tools.
I don't see any warning error while visiting user profile page.

**Comment by dkvasani** [comment]
Hi @sourabhmatolia 
As Discussed with you i am not replicat this issue so i am closing this issue.

@davidmabelle 
Also Warning: Invalid argument supplied for foreach() in /kunder/gmailc_6254/cocrea_8883/public/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-theme-settings.php on line 26
We have checked we are not getting such warning. so closing this isssue
