### ISSUE TITLE
PHP 7.4 Issue

### ISSUE THREAD

**Issue by davidmabelle** [buddyboss/buddyboss-platform#1720]
**Describe the bug**

Warning: Invalid argument supplied for foreach() in /kunder/gmailc_6254/cocrea_8883/public/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-theme-settings.php on line 26

**To Reproduce**
1. Install BuddyBoss Theme and Platform on a server with PHP 7.4

**Expected behavior**
No Error messages

**Comment by davidmabelle** [comment]
foreach no longer changes the internal array pointer

**Comment by davidmabelle** [comment]
https://www.php.net/manual/en/migration70.incompatible.php

**Comment by davidmabelle** [comment]
Warning: Invalid argument supplied for foreach() 

buddyboss-platform/bp-core/admin/bp-core-admin-theme-settings.php on line 26

**Comment by meetmakadiya** [comment]
Hello, @davidmabelle Not replicated the issue on 7.4 PHP with the latest platform version. please try with the latest version and let me know till that time I will close the issue.
