### ISSUE TITLE
Notifications for Liking in Activity post not working

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1721]
**Describe the bug**
When a user posts in activity feed, and someone likes this, the notification that someone liked his post is not showing

**To Reproduce**
1. Go to Activity feed, and post something
2. Login as a different user and like that post
3. Login back to the first user
4. See that he will not receive the notification that someone liked his post
Issue was replicated in dev environment and demo

**Expected behavior**
Notification for liking should work

**Screenshots**
https://drive.google.com/file/d/1HoIMAgrnwP114J7gIKIKMVU2AaahIfBW/view?usp=sharing
https://drive.google.com/file/d/1i_nKoqd23ZemeK2_LOjDF03PwpbVwo0a/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1324748708/106108
https://secure.helpscout.net/conversation/1324338063/106044

**Jira issue** : [PROD-899]

[PROD-899]: https://buddyboss.atlassian.net/browse/PROD-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by surajkrsingh** [comment]
Similar ticket - https://secure.helpscout.net/conversation/1561662455/151084/
The customer is also looking for the **activity post > like notification** on the app.
