### ISSUE TITLE
Make BuddyPress Reorder Tabs plugins compatible with BuddyBoss Platform

### ISSUE THREAD

**Issue by raftaar1191** [buddyboss/buddyboss-platform#1725]
**Is your feature request related to a problem? Please describe.**
Getting this error when using BuddyPress Reorder Tabs plugin with BuddyBoss Platform
Hey! BuddyPress Reorder Tabs requires BuddyPress version 2.6 or higher. You seem to have an older version and therefore BuddyPress Reorder Tabs is not working on your site. Please update BuddyPress.

**Describe the solution you'd like**
This should be compatible with BB platform as well

**Describe alternatives you've considered**
Make BuddyBoss Platform compatible with BuddyPress Reorder Tabs plugins

**Comment by mikejyoung** [comment]
We are working on our own feature to reorder tabs so won't be supporting this specifically.
