### ISSUE TITLE
Radiobox/Checkboxes of Contact form 7 misaligned

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1739]
**Describe the bug**
When Contact Form 7 shortcode is used on a page, the radioboxes and checkboxes are misaligned

**To Reproduce**
1. Install CF7
2. Create form with radioboxes and checkboxes
3. add CF7 shortcode to a page and view on frontend

**Expected behavior**
radioboxes and checkboxes must be aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/58522224/98260151-eec37900-1fbd-11eb-9df5-8c0a78906264.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1324743380/106106

**Comment by amincdev** [comment]
I have created an Issue in theme and closing this one as this is related to theme: https://github.com/buddyboss/buddyboss-theme/issues/1181
