### ISSUE TITLE
BB REST API - Media Albums Endpoint : Get albums info without media fields to limit response size

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1742]
**Is your feature request related to a problem? Please describe.**
I would like to use a rest request to list all available albums. That request already exists but it returns all albums + all medias in each album !

The request takes long to be executed and the size of response is very height (in Ko).

For optimization purpose, I would like to be able to list albums without media field.

Edit : Maybe I should create an new issue for that but it could be very useful to add a new field "cover image" containing the url of the image used for the cover of the album (thumb + full size).

**Describe the solution you'd like**
A solution could be to modify the context of the field media by removing embed. In that way, when context=embed, medias in albums won't be returned in the rest response.

```
'media'         => array(
	'context'     => array( 'view', 'edit' ),
	'description' => __( 'Album\'s media.', 'buddyboss' ),
	'readonly'    => true,
	'type'        => 'object',
	'properties'  => array(
		'medias' => array(
			'context'     => array( 'view', 'edit' ),
			'description' => __( 'The Album\'s Media.', 'buddyboss' ),
			'readonly'    => true,
			'type'        => 'object',
		),
	),
),
```

Ps : You have done the same "tricks" for the rest api "messages" (get threads without messages).

**Describe alternatives you've considered**
In the function "get_items", there's an argument "fields" which seems to select what fields have to be returned in the rest response. Maybe we could use that field to manually select fields in the reponse.

**Support ticket links**
none

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
