### ISSUE TITLE
Incorrect "My Groups" count when viewed on Group Type page

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1743]
**Describe the bug**
When you view a Group Type on the frontend in "site.com/groups/type/(group-type-name)/", this shows all the Groups with that current Group Type but the "My Groups" tab count is wrong

**To Reproduce**
1. Create a Group Type ex: Group Type A
2. Create at least two Groups, and associate one group with Group Type A
3. As a user, join on those Groups
4. In frontend, view site.com/groups/type/group-type-a/
5. The "My Groups" tab show 2 groups, then change to 1

**Expected behavior**
The "My Groups" count should remain 2

**Screenshots**
https://drive.google.com/file/d/1Ik0EgNOFA737_933OHiIMWX59Hy0HfDW/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1327878834/106862

**Comment by nitishkaila** [comment]
@emmanoctaviano

I have checked with the latest pull but it's working fine for me.
Please check the following video and let me know if I'm checking any step wrong.

https://www.loom.com/share/678e5ea62b47414bb4ff50e5dc8a11da

**Comment by sourabhmatolia** [comment]
@nitishkaila 

I see three issues here:
- Group Count is not working properly
- On Specific Group Type screen > My Group tab is not working
- Grid View vs List View setting is not getting saved. Should work same as the Main Group directory page.

Check Video:
https://www.loom.com/share/611e651f49af4abb9bed40b5cd15f452

**Comment by nitishkaila** [comment]
Hi @sourabhmatolia,

I have submitted pull request for those issues which you have mentioned.

Thanks
