### ISSUE TITLE
Group Leader not synching as an Organizer in Groups

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1745]
**Describe the bug**
When LD Groups and Social Groups is activated and vice versa in LearnDash Integrations

**To Reproduce**
1. Learndash must be activated
2. In BuddyBoss > Learndash > Integrations, activate LD Group to Social Groups and Social Groups to LD Group
3. Still in integrations, Social Group settings, match Organizer to Group Leader
4. Still in integrations, In LearnDash Group settings, match Group Leader to Organizer
5. Add user in a Social Group, then assign this as an Organizer
6. Though the user is counted as Leader in Learndash Groups view, when you click edit on the LearnDash Group, he is not added as a Leader

**Expected behavior**
When you add a Group Leader in a Learndash Group, this get synched as an Organizer in Social Group
But when you add an Organizer in Social Group, he is not shown as Group Leader in Learndash group

**Screenshots**
https://drive.google.com/file/d/1fJCfifpz2A0aHg9d9hu5vJ0vxMnstRlZ/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1328087095/106893

**Comment by khunteebwar** [comment]
In addition, with the same setting mentioned above, the users enrolled in the Social Group still aren't able to enroll in the LD assigned Group Course. well, it synced for most of the users but still not synced for some users.

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1456207759/131082
