### ISSUE TITLE
Send emails in batches 

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#1746]
**Is your feature request related to a problem? Please describe.**
In platform, we send emails to all members in one go and it works fine but when the site has a lot of users like in thousands or millions, it won't work and it will break there.

**Describe the solution you'd like**
We should send emails in batch/parts and send emails for all components.

**Describe alternatives you've considered**
No alt.

### Scope
We will create a DB table to list down the email queue. When an email is requested to send, it will be added to the queue.
A cron job will run every 2 minutes and will send max 20 emails every time and will delete the items which is sent.

### Related Platform API issue
https://github.com/buddyboss/buddyboss-platform-api/issues/315

### Related Platform PRO issue
https://github.com/buddyboss/buddyboss-platform-pro/issues/190

**Comment by justinpatrickkeller** [comment]
Really looking forward to this. If beta testing is needed please feel free to reach out to me. We run a site with 120+ Groups that uses Group Messaging extensively. Set up on Cloudways Vultr Servers using API connection through FluentSMTP with AmazonSES. Group Messages almost always fail when the group size gets above 100 members. Hopefully this solution will solve the issues with Group Messages for large groups!

**Comment by hercivalbuddyboss** [comment]
[https://secure.helpscout.net/conversation/1564601644/151814](https://secure.helpscout.net/conversation/1564601644/151814)

**Comment by sadrul** [comment]
Scope: We will create a DB table to list down the email queue. When an email is requested to send, it will be added to the queue. 
A cron job will run every 2 minutes and will send max 20 emails every time and will delete the items which is sent.
cc: @sourabhmatolia @chetansatasiya @KartikSuthar
