### ISSUE TITLE
Issue in the Strings Translation with Loco Translate ( German, French, Italian )

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1749]
**Describe the bug**
There are 2 string I can't translate in the Buddyboss platform
1: Forums ( Can't translate )
2: Please enter 1 or more characters ( Can't find this string within Loco translate )

**To Reproduce**
https://www.loom.com/share/35aa978fe0fd477a81dc111886868511

**Expected behavior**
Should translate in German, French, Italian 

**Support ticket links**
https://secure.helpscout.net/conversation/1326343626/106536?folderId=3955985

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1390136544/118757/

**Comment by milanhirapra** [comment]
I am unable to replicate this on my local machine and dev site.
Here are the videos for all three languages:

**Italian:**
**Please enter 1 or more characters:** https://vimeo.com/583792625/89c036ef09
**Forums:** https://vimeo.com/583793884/f394291ea2

**German:** https://vimeo.com/583797911/0a79e2c994
**French:** https://vimeo.com/583799013/6e21b1693b

**Comment by jakir-git** [comment]
Seems the issue is fixed now we can close this.
