### ISSUE TITLE
GamiPress + Elementor Widgets issues.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1759]
**Describe the bug**
https://drive.google.com/file/d/1cT54NGZIzz9Sb8t1u9knTQmsKPox8S53/view

**To reproduce**
Please refer to the screen recording to reproduce the issues.
https://drive.google.com/file/d/1cT54NGZIzz9Sb8t1u9knTQmsKPox8S53/view

**Support ticket links**
https://secure.helpscout.net/conversation/1335979839/108481?folderId=3709081

**Comment by annrra** [comment]
@furqanbb 
Need to fill in the description of the issue:
Partially connected and overlapped with this one - https://github.com/buddyboss/buddyboss-theme/issues/922 - wp widgets styling for elementor pages
Yet, I see some issues with gamipress widgets styling on default sidebar widget areas - https://drive.google.com/file/d/1ksVJtTkohYxT9I7OPjclfPdacxoFMZ7V/view
In summary - there are styling issues with gamipress widgets, and not with elementor wp widgets specifically

**Comment by annrra** [comment]
@furqanbb 
This is rather a theme related issue - so it is moved to this one - https://github.com/buddyboss/buddyboss-theme/issues/1189
