### ISSUE TITLE
With Redis enabled you need to manually flush the cache after moving photos into album

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1766]
**Describe the bug**
I do use Redis Server on a BuddyBoss website (I've installed Redis Object Cache Plugin). When I add/move some existing photos to an album, I need to manually flush the (redis) cache to see the change.

This only happens when I enable Redis server.

**To Reproduce**
1. Upload some photos in the activity feed (in a group or in your profile)
2. Create a new album
3. Click on the button "Add Photos" -> "Select Photos"
4. Select multiple photos
5. Validate

After the validation (5), you will be redirected to the album page and you will see photos inside the album. But when you leave that page and come back later, you won't see any photo in the album.

If you flush the cache, on will see your photos inside the album.

**Expected behavior**
When you move some photos into albums (with redis server enabled), you should see your photos inside that album without having to manually flush the cache.

**Screenshots**
none

**Support ticket links**
none

**Comment by ExoGeek** [comment]
There's the same bug when you **upload** medias inside album. 

I suppose this bug is related to wp_cache function (missing call to that function).

**Comment by Hemligg** [comment]
When is this issue going to get some attention? It's a real show stopper for the album feature.

**Comment by bstreet123456789** [comment]
This is also a limitation of document folders as well. When creating and deleting folders, Redis needs to be cleared in order for the changes to be visible. It looks like it is the way that BB creates and handles albums and folders.

**Comment by fabiomail** [comment]
I confirm that the same issue happens for the document feature. I reported it months ago...

**Comment by Felipemauah** [comment]
I have same problem! @krunal-buddyboss @dipskakadiya @mehulkaklotar @chetansatasiya @sourabhmatolia @sadrul I need help!

**Comment by futureyoon** [comment]
+1

**Comment by vingogly** [comment]
Please address this - thanks.

**Comment by bstreet123456789** [comment]
For anyone having this issue, I have added the following to my wp-config to ignore the document and photo groups from Redis. Still testing, but appears to work nicely.

define( 'WP_REDIS_IGNORED_GROUPS', [ 
		'bp_document',
		'bp_album'
		]);

**Comment by chetansatasiya** [comment]
@bstreet123456789 @vingogly @futureyoon @Felipemauah @fabiomail @bstreet123456789 @Hemligg @ExoGeek This will be fixed very soon guys.

**Comment by chetansatasiya** [comment]
@bstreet123456789 @vingogly @futureyoon @Felipemauah @fabiomail @bstreet123456789 @Hemligg @ExoGeek Can you guys check in your staging server using this PR https://github.com/buddyboss/buddyboss-platform/pull/2271 like it's fixed your issues or not?

**Comment by Felipemauah** [comment]
> @bstreet123456789 @vingogly @futureyoon @Felipemauah @fabiomail @bstreet123456789 @Hemligg @ExoGeek Can you guys check in your staging server using this PR https://github.com/buddyboss/buddyboss-platform/pull/2271 like it's fixed your issues or not?

Hello @chetansatasiya .

Is great improvement!! Thank you!!

**Comment by fabiomail** [comment]
@chetansatasiya hi, how can I download the modified version to be tested? I am not really familiar with GitHub.

**Comment by fabiomail** [comment]
What's the status of this fix? @sourabhmatolia @chetansatasiya

**Comment by sourabhmatolia** [comment]
@exogeet @Hemligg @ouch-digital @fabiomail @Felipemauah @futureyoon @vingogly

Issue mentioned above is released in BuddyBoss Platform v1.5.9

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-9/

Please update the plugin to see the latest changes.

Thank you.

**Comment by fabiomail** [comment]
Thank you @sourabhmatolia . The changelog only mentions Media; does this fix also include Documents?

**Comment by chetansatasiya** [comment]
> Thank you @sourabhmatolia . The changelog only mentions Media; does this fix also include Documents?

@fabiomail it fixed in both Media & Documents
