### ISSUE TITLE
Forums page return 404 when set as child page of other Component pages

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#1767]
**Describe the bug**
Forums page return 404 when set as child page of other Component pages
_Note: Forums page set as child of a regular page works_

**To Reproduce**
1. On demo, go to Pages
2. Change Page Parent of Forums to any Component pages (Activity Feed)
3. View Forum page, see 404

**Expected behavior**
Regardless if the parent page of the forums is a component page or a regular page, Forums page should not return as 404

**Screenshots**
https://www.loom.com/share/3eed3474ffd245369a41583c6ac4c44c

**Support ticket links**
https://secure.helpscout.net/conversation/1329618264/107230/

**Comment by mehulkaklotar** [comment]
@marilyn9425 @sourabhmatolia @krunal-buddyboss If forum page is set under any component pages, it will not work. this creates issues for many things. Customer should not set forum page as a child to any component pages. We have a code that looks for slugs for component pages and if 2 components are parent child of each other then that will create confusion between components.

**Comment by chetansatasiya** [comment]
@mehulkaklotar I agreed with you here https://github.com/buddyboss/buddyboss-platform/issues/1767#issuecomment-791375568

Let's close this.

CC: @sourabhmatolia
