### ISSUE TITLE
Group Type Creation "None" option doesn't work.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1768]
**Describe the bug**
In Profile Type administration / Group Type Creation: it is impossible to select (None). All group types are available and selectable; only the (None) checkbox cannot be clicked.

**To Reproduce**
https://screencast-o-matic.com/watch/cYXIhpMdmd

**Expected behavior**
"None" should be selectable.

**Screenshots**
https://prnt.sc/viebb7

**Support ticket links**
https://secure.helpscout.net/conversation/1328538009/106976/
https://secure.helpscout.net/conversation/1367178517/114874

**Comment by marienel21** [comment]
Bug non existent in the latest version of the Platform.
