### ISSUE TITLE
All notifications for Private Group request access are being marked as read once you just visited one of them

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1772]
**Describe the bug**
All notifications for Private Group request access are being marked as read once you just visited one of them. Even when these notifications came from different users and groups.

**To Reproduce**
1. Create at least two private groups.
2. Using a subscriber account, request access to those private groups you just created.
3. After that, log back to the group organizer's account.
4. Check your notification and try to click one of the private group request access notifications.
5. Once you have redirected, notice that all request access notification will be marked as read.

**Expected behavior**
Only the one you just clicked must be marked as read.

**Screenscasts**
- https://cutt.ly/Qg0vgZ1
- https://www.loom.com/share/3237d2159ed84a0ab58e31aaabe3e5c9 (from customer)

**Screenshots**
![group-notif](https://user-images.githubusercontent.com/58522498/99086307-4b4d1680-2604-11eb-89e5-0e184673fea5.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1336250387/108537

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1493830938/138699
