### ISSUE TITLE
Improved Front End User Experience like Date input in profile edit section

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1773]
**Is your feature request related to a problem? Please describe.**
To help improve the user experience: 1. In Profile > Field Sets; The Field Sets should be allowed to "group" wherein the admin can group particular data sets into a group that will separate them for the user. Right now, it looks pretty cluttered (see screenshot ) with several fields to edit without distinction between them. 2. The date field should be adjusted. Currently, if the user only enters the year and saves, it erases all date info. It's all or none. -If only the year is input, then only the year is displayed in a user profile if month and year are input, then month and year are displayed, etc. or -Allow admin to set: Y only, m/Y only, d/m/y; this way if the admin sets Y only, the user will only have a field of Y to input. 

See this video
https://www.loom.com/share/1b114e97ba4545029f8c1cdd9ac117a7

See screenshot as a reference
https://prnt.sc/vj5br3
https://prnt.sc/vj5byz
https://prnt.sc/vj5c5n

**Describe the solution you'd like**
Need an easy User experience to save user data.

**Support ticket links**
https://secure.helpscout.net/conversation/1337866817/108796/

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1585799713/156007/

**Comment by marienel21** [comment]
We have imported this request into ProductBoard to review as we plan new features.

As new features and improvements are planned, we will add them to our public roadmap:
https://roadmap.buddyboss.com

I’m closing this issue in order to ensure our backlog only contains items that are ready for development.

Thanks,
Marienel - BuddyBoss Product Team
