### ISSUE TITLE
Conditional Profile Fields not working with Repeater Fields

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1776]
**Describe the bug**
Concern: Repeater Field Set Issue - If one of the field under the repeater set is a conditional field,

- the corresponding field that depends on the conditional fields sometimes appears and sometimes and sometimes does not
- If the conditional field is already triggered and has already appeared, it will also be visible again when a new fieldset is added, even if the condition is not yet fulfilled

**To Reproduce**
Steps to Reproduce:
1. Create a repeater set
2. Set 1 profile field as conditional and dependent on another field
3. In the front end, notice that the reported issue can be encountered.

Here is a video for your reference: https://www.loom.com/share/a0a0ba7052f34fd2b65b1be88f1ae0f2

**Support ticket links**
https://secure.helpscout.net/conversation/1329619052/107232?folderId=3955985

**Comment by nitishkaila** [comment]
@jakir-git @sourabhmatolia

I have checked this issue and found that it's related to **Conditional Profile Fields for BuddyPress** plugin. The Conditional Profile Fields plugin always matches the first repeater field value for the rest of the repeater fields. For the proof, I have applied a quick solution to prepare a video.

https://www.loom.com/share/85845af6761a4a828bbc84188d3247ad

**Comment by jakir-git** [comment]
Thank you so much. I understand now.

**Comment by jabaghSaeed1** [comment]
@nitishkaila can you provide the solution please how did you make the condition work for the other fields ?
