### ISSUE TITLE
Documents - Preview not generarting while using offload media

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#1781]
**Describe the bug**
When Using the Offload media plugin then in Document PDF preview not generating.

**To Reproduce**
1. Enabled the Imagick extension on server.
2. Add WP Offload Media Plugin and activate the plugin and make a sync with AWS OR any cloud
3. Enable the **Remove Files From Server** from the settings WP Offload Media Plugin **ADVANCED OPTIONS**
4. Upload a document it will not show the preview of the PDF even if you have a Imagick enabled on server.

**Expected behavior**
It should show the preview image if you have Imagick enabled on server.

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1326503974/106571/

**Comment by wtatters** [comment]
This same issue is also occuring with wp media folders S3 connections

**Comment by ExoGeek** [comment]
There's still an issue with the preview when the setting "Remove Files From Server" is enabled (I do also use Private Media functionnality but it seems to have no impact on the issue. The issue seems to be related to "Remove Files From Server").

I've tested this with BuddyBoss Beta 1.7.0.1.

![image](https://user-images.githubusercontent.com/46819762/121887388-f5199080-cd16-11eb-9a5a-b1ffcb03d618.png)

**Comment by chetansatasiya** [comment]
> There's still an issue with the preview when the setting "Remove Files From Server" is enabled (I do also use Private Media functionnality but it seems to have no impact on the issue. The issue seems to be related to "Remove Files From Server").
> 
> I've tested this with BuddyBoss Beta 1.7.0.1.
> 
> ![image](https://user-images.githubusercontent.com/46819762/121887388-f5199080-cd16-11eb-9a5a-b1ffcb03d618.png)

@ExoGeek I tried in the current beta version in my local environment using this `video-uploading` branch https://github.com/buddyboss/buddyboss-platform/pull/1630 and it working fine without any issues 

https://www.loom.com/share/8acce2f4dc5f4dd3b3b0fda053095f27

**Comment by sourabhmatolia** [comment]
@wtatters @ExoGeek

Issue shared above is fixed and released with BuddyBoss Platform v1.7.0

Check Changelog here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-0/

Thank you for showing interest. Thnx
