### ISSUE TITLE
Hidden subforums are visible when the parent forum is assigned to a public group

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1785]
**To Reproduce**
1. Create a public group.
2. Assign a forum to that group.
3. Add a hidden subforum to the assigned forum.
4. Go to the public group you just created and navigate to the discussion tab
5. Notice that the hidden subforum is listed but goes to the 404 page when clicked.
 
**Screencast**
https://cutt.ly/Ig70M9q

**Support ticket links**
https://secure.helpscout.net/conversation/1339909938/109174

**Comment by meetmakadiya** [comment]
@ayron-paul 
Not replicated with Version 1.7.4 please check the video for more details.
https://www.loom.com/share/44fdb3ba955d4cbc869d66083f247bc4

**Comment by ayron-paul** [comment]
Hi @meetmakadiya, I can confirm that the issue cannot be reproduced with the latest version. Thank you for checking!
