### ISSUE TITLE
Activity comments pagination

### ISSUE THREAD

**Issue by amincdev** [buddyboss/buddyboss-platform#1789]
**Is your feature request related to a problem? Please describe.**
Right now, When activity has more comments then few comments are shown and few are hidden. After clicking on "View previous comments" It shows all remaining comments.

**Describe the solution you'd like**
Instead of show/hide, Load only (n) comments on page load and when the user clicks "View previous comments" then load more (n) comments with AJAX.

**Comment by mikejyoung** [comment]
This is related to another feature we're preparing. We can implement this when doing that. Closing the issue here.

**Comment by durdenx** [comment]
@mikejyoung is there any related issue for your feature, so we can follow the progress?

**Comment by mikejyoung** [comment]
Not yet, we're working on a number of designs for activity feed improvements. Once the designs are approved, new issues will be added to the backlog.

However, we will be moving our issue backlog to a private Jira project soon and deactivating the "Issues" component in this GitHub repo. However the "Pull Requests" component will be stay active so once an issue has a pull request, you'll be able to track its progress publicly.

**Comment by mikejyoung** [comment]
@durdenx 
This is the feature that this improvement will likely be connected to:
https://roadmap.buddyboss.com/c/117-show-select-comments-under-activity-posts
