### ISSUE TITLE
Header Search Bar - Multiple issues and Improvements

### ISSUE THREAD

**Issue by annrra** [buddyboss/buddyboss-platform#1799]
**Describe the bug**
Related issue - https://github.com/buddyboss/buddyboss-theme/issues/1169
1. when searching any item from header search and number of items in plugin setting is more than 15 then search result list getting hidden on scroll https://i.imgur.com/nie9rC7.jpg

2. If user is on search result page and searching something again from search page then auto suggest list is not appearing expected.

**To Reproduce**
Refer above linked related issue

**Expected behavior**

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by amincdev** [comment]
This Issue has been worked here with a proper solution: 
https://github.com/buddyboss/buddyboss-platform/issues/2900
