### ISSUE TITLE
Forum discussions and replies from private groups are visible in the search result for non-members

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1801]
**To Reproduce**
1. Create a private group with an associated forum.
2. Create a new discussion and add a reply to that forum you just created.
3. Using another account, which is not a member of the group you just created, try to search any keyword from the discussion or reply on that private group.
4. Notice that the search result includes discussion/reply from the private group that he is not a member

**Expected behavior**
The search result should not include contents from the private group that the user is not a member

**Screencast**
https://cutt.ly/Shq7IiL

**Support ticket links**
https://secure.helpscout.net/conversation/1334116048/108103

**Comment by ngolwalkar** [comment]
I confirmed it with @ayron-paul , It is working fine now. So i am closing this issue,
