### ISSUE TITLE
The group feed and members list is not working when BP Auto Group Join is installed in multisite setup

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1803]
**To Reproduce**
1. In a multisite setup, Install and activate BP Auto Group Join plugin.
2. Now go to any group page and notice that the News Feed and Members are not working.

**Screenshots**
![feed](https://user-images.githubusercontent.com/58522498/99724367-7e087a80-2aee-11eb-8c5d-c5a9c83558e0.png)
![members](https://user-images.githubusercontent.com/58522498/99724371-7ea11100-2aee-11eb-9c59-27f02733d440.png)

**Jira issue** : [PROD-894]

[PROD-894]: https://buddyboss.atlassian.net/browse/PROD-894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by biguenique** [comment]
I also noticed that [BP Auto Group Join](https://wordpress.org/plugins/bp-auto-group-join/) is not compatible with BuddyBoss Platform in a couple ways:

1. It caused me a critical error on group display;
2. The member type discrimination functionality is meant to work along with the [BuddyPress Member Type](https://www.buddyboss.com/product/buddypress-member-types/) plugin and is not compatible with BBP's member type implementation.

I guess it wouln't actually be a BuddyBoss Platform issue is _both plugins_ were not published by BuddyBoss themselves!

Until it gets fixed, if all you need is to automatically join new users to (a) specific group(s), you can simply rely on some very simple code snippet and spare yourself the extra plugin:

```
/**
 * Automatically adds newly activated user to some group (here with group_id = 7)
 * @link https://stackoverflow.com/questions/36684517/buddypress-auto-join-group
 * @link https://gist.github.com/imath/59875514ff46ba5e191b
 * @link https://www.buddyboss.com/resources/reference/functions/groups_join_group/
 */
function join_some_group( $user_id ) {
	if( !$user_id ) return false;
	$group_id = 7; // Udpade with your actual group ID
	groups_join_group( $group_id, $user_id );
}
add_action( 'bp_core_activated_user', 'join_some_group' );
```
