### ISSUE TITLE
Irrelevant names are showing when searching a user in the private messaging 

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1810]
**Describe the bug**
When the user's first name, last name, or nickname was used or mentioned in other profile fields, when you try to search them in the private messaging, there are irrelevant names showing up. And in most cases, the user you are trying to message is not being listed.

**To Reproduce (in demo site)** please see: https://cutt.ly/LhrqfeZ
1. Create another profile field like "my best friend".
2. Edit some users and set "Trent" in their "my best friend" profile field.
3. Now, go to private messaging and try to search for "Trent" as you recipient.
4. Notice that irrelevant names are showing in the list and you cannot find Trent anymore.

**Expected behavior**
The private messaging search must be only limited to first name, last name and nickname because it will show unrelated or irrelevant names. It will be difficult to find the user.

**Screencast**
https://cutt.ly/LhrqfeZ

**Screenshots**
![IMG](https://user-images.githubusercontent.com/58522498/99848755-4a445800-2bb5-11eb-8995-2e5f2a90a577.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1339832494/109164

**Comment by sourabhmatolia** [comment]
Akshit please take over this task.
