### ISSUE TITLE
Documents - Preview taking time to load the activity page and other pages where preview is coming.

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#1818]
**Describe the bug**
Due to the load of the WordPress in `preview.php` file it's slowing the actvity and other pages where document is loading.

**To Reproduce**
1. Add to many documents which have a preview image like add too many PDF 
2. Go to the activity page and it will slow the activity load.

**Expected behavior**
It should load the instantantly as others like media.

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by sourabhmatolia** [comment]
Issue fixed and release here:
https://github.com/buddyboss/buddyboss-platform/pull/1630
