### ISSUE TITLE
Cannot add another data for repeater fields when there are fields that are only available for specific profile type

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1823]
**Describe the bug**
Cannot add another data for repeater fields when there are fields that are only available for specific profile type.

**To Reproduce**
1. Create at least 3 Profile Types.
2. Create at least 2 Repeater Fieldset.
3. Add some fields to each Repeater Fieldset and make sure that some of them are only available for at least two of your profile types.
4. Assign one of your profile types to one of your members.
5. login using that member's account and go to the Edit Profile page.
6. Try to add data on the repeater fields.
7. After saving, click "Add Another" and notice that it will just open the first data set you have entered.

**Screencast**
https://cutt.ly/khiIkrm

**Screenshots**
![ss](https://user-images.githubusercontent.com/58522498/99998959-73a1f580-2dfa-11eb-8dee-63f62ba015cf.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1332273185/107787

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1452354994/130406/

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1451076099/130218/

**Comment by sadrul** [comment]
@sourabhmatolia This issue fixed in this PR - https://github.com/buddyboss/buddyboss-platform/pull/2286

proof: https://www.loom.com/share/7273e1029739453899d59687eaae17a9
