### ISSUE TITLE
Activity Performance Enhancement

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#1825]
**Is your feature request related to a problem? Please describe.**
Right now, with all features enabled on Platform, Activity is becoming slow when loading. Sometime with Media/Documents, it loads in more than 10 seconds for concurrent requests.

**Describe the solution you'd like**
- Fix document/photo preview load
- Fix activity query/functions overall to make use of cache and identify we don't duplicate anything on each request.

**Comment by mikejyoung** [comment]
This is tracked inside of Product Board. Closing the issue here. It will be implemented in a future scope.
