### ISSUE TITLE
Not showing update nick name on group page for following users

### ISSUE THREAD

**Issue by krunal-buddyboss** [buddyboss/buddyboss-platform#1833]
**Describe the bug**
Issue: When customer are changing nicknames, the @mention for the changed nickname works for Activity page but not on Groups Activity pages, Group forum/Discussions

Example: user: "john" changed nickname to "juan" 
when you mention him in Activity feed, this shows as "@juan" which is correct
But inside BuddyBoss Group activity feed or forums, this still shows as "@john"

**To Reproduce**
1. Change the nick name of for two user one that you are following and one without following
2. Check on Activity and Group page by mentioned @ for autosuggestion
3. You will show updated nick name for the user that you are following

**Expected behavior**
On both Activity and Group page, it should show updated nick name for all users(whether you are following or not following)

**Screenshots**
https://www.loom.com/share/4fc1130bf9eb42d88cadf078313e6c13

**Support ticket links**
https://secure.helpscout.net/conversation/1323185628/105869

**Comment by marienel21** [comment]
bug no longer exists in the latest version of the product.

**Comment by milanhirapra** [comment]
I found this issue in the latest version of the BB platform.
Please check here: https://vimeo.com/577125153/94ef59e0c9

HS: https://secure.helpscout.net/conversation/1572870302/153653/
