### ISSUE TITLE
Profile Type with WP Roles are not synched when changing Profile Type

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1843]
**Describe the bug**
Creating Profile Types has the ability to select a WP Role. But when you update Profile Types with different WP Roles, this is not synched or updated

**To Reproduce**
1. Create Profile Types with different WP Roles
 ex. name: Profile Type 1, role: contributor
      name: Profile Type 2, role: author
2. Create a sample user
3. Assign the user to Profile Type 1, in WP Dashboard > Users
4. Assign the user to Profile Type 2
5. See error, when assigned to Profile Type 2, user should be author

**Expected behavior**
When Profile Tyep1 with Contributor role is selected for a user and changed to Profile Type 2.
The WP Role should also changed as Profile Type 2 has Author role.

**Screenshots**
https://drive.google.com/file/d/1SlQWoKYwyosipaZdiMPGAmCc-mPabUXm/view?usp=sharing
issue can be seen in demo
https://drive.google.com/file/d/14P1xArYPwBICZRdmmi9XC_9RXlM-1i7x/view

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1580238587/155095

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1349719335/111339
