### ISSUE TITLE
The admin email notification for the New User Registration is not properly displaying for iOS Email application

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1845]
**To Reproduce**
1. Using an iOS device, log in with your website's admin email.
2. Go to your website and try to register a new user.
3. As an admin, you will receive an email notification for "New User Registration".
4. Viewing the email using an iOS device you will notice that it does not display properly.

**Screenshots**
![other email](https://user-images.githubusercontent.com/58522498/100618620-08ef3d80-3357-11eb-9893-20b970b142d3.jpg)
![ios](https://user-images.githubusercontent.com/58522498/100618625-0987d400-3357-11eb-8b46-50ab2abda8f3.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1337181178/108665

**Jira issue** : [PROD-886]

[PROD-886]: https://buddyboss.atlassian.net/browse/PROD-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mahedihasannoman** [comment]
Hi @ayron-paul , I have tested with macOS default email application and the issue is not happening on my testing. See my screenshot: https://nimb.ws/euF4rj
Can you please check again and confirm if the issue is still happening on iOS?

**Comment by ayron-paul** [comment]
Hi @mahedihasannoman, yes I am still able to reproduce the issue on the default iOS email app.
