### ISSUE TITLE
Error 404 when a user leaves a hidden group

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1851]
**Describe the bug**
When a user leaves a hidden group, an HTTP 404 error is displayed.

**To Reproduce**
1. Go into a hidden group (where you are a member)
2. Leave that group by clicking on the button "Leave Group"

=> A 404 error is displayed.

**Expected behavior**
When user leaves a hidden group, go back to https://demos.buddyboss.com/online-communities/groups/

**Screenshots**
none

**Support ticket links**
none

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Issue reported above released with BuddyBoss Platform v1.5.7.3

Thanks.
