### ISSUE TITLE
BB REST API - Signup Endpoint : Do not return activitation key in the response

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1859]
**Describe the bug**
When you register a new user using the BB REST API (signup endpoint), the **activation_key** is returned in the response. 

I don't think it's a good idea because a hacker could create a bunch of users and because he directly know the activation_key in the response, he's able to activate each and every account directly (through rest api call) without having to verify the email.

**To Reproduce**
1. Create users using `POST {{host}}/wp-json/buddyboss/v1/signup`
2. Fetch the **activation_key** in the response
3. Validate each user using a HTTP request : `{{host}}/activate/<<activation_key>>`

**Expected behavior**
Only returns the activation_key field if the user who make the request is the **administrator** (This can be usefull for administrative tasks).

**Screenshots**
none

**Support ticket links**
none

**Comment by ExoGeek** [comment]
See : https://github.com/imath/BP-REST/commit/95d8aa9f42de1f3fdb19127234e568ec66448b41

**Comment by meetmakadiya** [comment]
@ExoGeek 
Without an administrator account API through **authorization_required** error so the only administrator can see the **activation_key** so hacker could not create the bunch of users.
We are closing this issue for now. If you can replicate the issue, you may reopen this.

**Comment by ExoGeek** [comment]
@meetmakadiya 
I've just tested with the latest version of BuddyBoss and you can still create and activate a new user (without having a valid email address or being an administrator).

First, you have to make a REST API request : 
```
### Register new user
POST http://localhost/wp-json/buddyboss/v1/signup
Content-Type: application/json

{
  "signup_email": "neville12@buddyboss.com",
  "signup_password": "abcdef1234",
  "signup_password_confirm" : "abcdef1234",
  "field_1": "Neville12",
  "field_2": "Buddy",
  "field_3": "Neville12"
}
```
The response looks like : 
```
{
  "success": true,
  "message": "Avant de pouvoir vous connecter, vous devez confirmer votre adresse e-mail via l'email que nous venons de vous envoyer.",
  "data": {
    "id": 33,
    "user_login": "neville12",
    "user_name": "Neville12",
    "registered": "2021-08-23T15:32:26",
    "activation_key": "t6rxFQZLUqjWh4sCc3lanIjsYiQLqgSj",
    "user_email": "neville12@buddyboss.com",
	...
  }
}
```

You copy the "activation_key" value from the response and you open a web browser (firefox in my case). You type the URL :

`http://localhost/activate/t6rxFQZLUqjWh4sCc3lanIjsYiQLqgSj`

![image](https://user-images.githubusercontent.com/46819762/130477920-ed9275fc-2cf9-4f26-b6d9-ce525f1cbd0a.png)

Result : Your account was activated successfully!

![image](https://user-images.githubusercontent.com/46819762/130478014-8efcb919-80d4-41b9-9c27-662341ee6cd7.png)
