### ISSUE TITLE
BB REST API - Signup Activation : Only activate account with the activation_key

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1860]
**Describe the bug**
For activate an account, you can use the BB REST API "signup/activate". That endpoint "signup/activate" accepts 3 types of parameter : a signup id, a user_login or an email.

Because that endpoint is publicly accessible, anyone can activate any pending signup account. You only have to query the endpoint with 1, 2, 3 ,4 ...

Each and every pending acccount will be validated !

**To Reproduce**
1. Register a new user using the REST API

```
POST {{host}}/wp-json/buddyboss/v1/signup
Content-Type: application/json

{
  "signup_email": "neville@buddyboss.com",
  "signup_password": "abcdef1234",
  "field_1": "Neville",
  "field_2": "Buddy",
  "field_3": "neville01"
}
```
2. Fetch the **id** from the response.
3. `PATCH {{host}}/wp-json/buddyboss/v1/signup/activate/5`

The user is activated without having to validate his email address.

**Expected behavior**
The parameter **id** in the **signup/activate** endpoint should only be the **activation_key** (Except for administrator). An administrator should be able to validate a user using the id or the email but that option should not be accessible for public request !

**Screenshots**
none

**Support ticket links**
none

**Comment by mdleung** [comment]
Has this been updated?
