### ISSUE TITLE
BB REST API - Signup Endpoint : BP_SIGNUPS_SKIP_USER_CREATION and Memberpress + Buddypress Plugin integration

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1861]
**Describe the bug**
In order to optimize the database size, I would like to enable "BP_SIGNUPS_SKIP_USER_CREATION" in the wp-config.php (see explanation in the file **bp-members-functions.php** - line **1815** - function **bp_core_signup_user**).

Enable **Memberpress + BuddyPress Integration** to automatically attach a free membership + join some groups when user register.

In the file "**MpBuddyPress.php**", you can see :
`add_action('bp_core_signup_user',               array($this, 'capture_bp_signups'), 11, 5);`

**Memberpress + BuddyPress Integration** works well when BP_SIGNUPS_SKIP_USER_CREATION is false. But when it's true, because you don't call the action "bp_core_signup_user" when activating and creating the user, that plugin doesn't work.

_Edit : I also have to check but it seems that there's a problem with emails sent during registration (when user validate his account, welcome emails are not sent)_

**To Reproduce**
1. Add `define('BP_SIGNUPS_SKIP_USER_CREATION', true);` in wp-config.php
2. Install and activate **Memberpress** and **MemberPress + BuddyPress Integration**
3. Register a new user using the rest api 

```
POST {{host}}/wp-json/buddyboss/v1/signup
Content-Type: application/json

{
  "signup_email": "neville01@buddyboss.com",
  "signup_password": "abcdef1234",
  "field_1": "Neville",
  "field_2": "Buddy",
  "field_3": "neville01"
}
```

4. Activate the new user

Because do_action('bp_core_signup_user'...) is not called when creating the user, there's no default membership attached to him.

**Expected behavior**
Execute WP action 'bp_core_signup_user' when you create the user for optmized integration between memberpress and buddyboss.

**Screenshots**
none

**Support ticket links**
none

**Comment by mahedihasannoman** [comment]
Issue moved to Platform API: https://github.com/buddyboss/buddyboss-platform-api/issues/334
PR: https://github.com/buddyboss/buddyboss-platform-api/pull/335
