### ISSUE TITLE
Adding plugin to BuddyBoss lntegrations Page

### ISSUE THREAD

**Issue by andreuka** [buddyboss/buddyboss-platform#1863]
Hi there!

Is there any way to add plugins to BuddyBoss integrations page?
https://www.buddyboss.com/integrations/
Seems like contact form at that page is broken.

I sent request long time ago to add this plugin:
https://wordpress.org/plugins/bp-better-messages/

And still no answer positive or negative. I also noticed there is no way to leave my email when I completed my application.

Thanks!

**Comment by grahamhoffman** [comment]
Please contact BuddyBoss General Enquiries Support.

https://www.buddyboss.com/contact/
