### ISSUE TITLE
BB REST API - Signup Form : Bad schema returned when OPTIONS request

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1864]
**Describe the bug**
When you display the schema of the endpoint "signup/form", it returns the schema of "signup".

**To Reproduce**
1. `OPTIONS {{host}}/wp-json/buddyboss/v1/signup/form`

**Expected behavior**
Return schema of form signup endpoint.

```
[
    {
        "id": "field_1",
        "label": "First Name",
        "description": "",
        "type": "textbox",
        "required": true,
        "options": "",
        "member_type": []
      },
      { ... }
]
```

**Screenshots**
none

**Support ticket links**
none

**Comment by ExoGeek** [comment]
There is the same issue with `OPTIONS {{host}}//wp-json/buddyboss/v1/signup/activate`

**Comment by surajkrsingh** [comment]
@janakkaneriya007 
I am getting the correct schema from the endpoint `{{host}}/wp-json/buddyboss/v1/signup/form`  as user expected
See this - https://tinyurl.com/yebvzmld

Can we close this issue?

**Comment by surajkrsingh** [comment]
@ExoGeek 
We tested the endpoints mentioned above.

**The below screenshots has the correct schema for these endpoints.**
1. For  `OPTIONS {{host}}/wp-json/buddyboss/v1/signup/form`
Expected schema - https://tinyurl.com/yet79fsc

2. For `OPTIONS {{host}}//wp-json/buddyboss/v1/signup/activate` 
Expected schema - https://tinyurl.com/yffph8ao

And as per your expected result schema -  https://tinyurl.com/yebvzmld
`GET {{host}}/wp-json/buddyboss/v1/signup/form`  is the correct endpoint

**Comment by surajkrsingh** [comment]
@dipskakadiya  Can we close this issue?

**Comment by ExoGeek** [comment]
@surajkrsingh Based on your screenshot, that seems to be ok right now.

Thanks
