### ISSUE TITLE
Duplicate input when typing korean

### ISSUE THREAD

**Issue by newcode365** [buddyboss/buddyboss-platform#1870]
When typing in Korean on the forum, duplicate input is entered as shown in the attached screenshot. 

![input bug](https://user-images.githubusercontent.com/48101203/101093955-f5fe9680-35fe-11eb-911f-4c5a4e234e86.png)

**Jira issue** : [PROD-883]

[PROD-883]: https://buddyboss.atlassian.net/browse/PROD-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bb-yudhisthir** [comment]
The issue is in the third party vendor - medium editor JS, and issue already raised - https://github.com/yabwe/medium-editor/issues/1485

Also there is the fix - https://github.com/yabwe/medium-editor/pull/1492/commits/0762aafe42cafcaa9ad323b18372217a43bac618

**Comment by bb-yudhisthir** [comment]
same with Japanese https://secure.helpscout.net/conversation/1710086016/175992/

**Comment by hercivalbuddyboss** [comment]
https://secure.helpscout.net/conversation/1728944114/178893/

**Comment by bb-yudhisthir** [comment]
> this is english but using a mobile device, the keyboard has a autocomplete function that triggers the duplication https://secure.helpscout.net/conversation/1728944114/178893/

@hercivalbuddyboss its not related to this issue

**Comment by hercivalbuddyboss** [comment]
> > this is english but using a mobile device, the keyboard has a autocomplete function that triggers the duplication https://secure.helpscout.net/conversation/1728944114/178893/
> 
> @hercivalbuddyboss its not related to this issue

Can be replicated on our demo: https://drive.google.com/file/d/1ztk7RKvaESpynuYcYDU0hsbEdQNSByMO/view?usp=sharing
