### ISSUE TITLE
Theme Options goes to 404 if we translate the BuddyBoss string on the Menu

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1872]
**Describe the bug**
While click on the theme options goes to 404 if we translate the BuddyBoss string on the Menu

**To Reproduce**
https://www.loom.com/share/500ed4eeffe448e2a1d3de4b8fc01a59

**Support ticket links**
https://secure.helpscout.net/conversation/1335318529/108346/

**Comment by janakkaneriya007** [comment]
@jakir-git BuddyBoss menu consists of plugin and theme menu so the same string should be translated in theme as well to get the theme options working. Refer to below video.
https://www.loom.com/share/a233e9c2f20b417da7898825f88c0183
