### ISSUE TITLE
Can not translate 'Drop image here to upload' string.

### ISSUE THREAD

**Issue by cereneto** [buddyboss/buddyboss-platform#1875]
Describe the bug
String "Drop your image here" can not be translated. 
After commit 802229c, string pass from "Drop your file here" to "Drop your image here" without change in .pot file.

To Reproduce

1. Go to 'Activity' page.
2. Click on media upload icon.
3. You will see the text 'Drop images here to upload'
4. You can not translate the text.

**Comment by surajkrsingh** [comment]
POT file has been updated
Tested the issue and found that the string **Drop images here to upload** is translatable and working fine with other languages.
**See this** - https://tinyurl.com/yhnctlk8

**Comment by surajkrsingh** [comment]
@janakkaneriya007 I am closing this issue because this is working fine
