### ISSUE TITLE
BuddyBoss' Elementor Activity Element

### ISSUE THREAD

**Issue by aashley21** [buddyboss/buddyboss-platform#1877]
**Describe the bug**
The "All Activity" link points to "news-feed" but it should be "/news-feed" Because of this, users get a 404 page because it appends /news-feed after the slug for the page they are currently on. It should be appended to the root domain.

**Comment by meetmakadiya** [comment]
@aashley21 can't reproduce the issue with the latest version(1.7.7.1) so can you please confirm with the latest version and let me know.
Thanks.

**Comment by imehedidev** [comment]
Not replicable with the latest version.
