### ISSUE TITLE
Add New Member - Select user bug

### ISSUE THREAD

**Issue by welshlamb10** [buddyboss/buddyboss-platform#1897]
Since the latest WP Core 5.6 there appears to be a bug. When attempting to add users to a group and typing into the 'Add Members' field - no dropdown list is being produced to select the user.

1. Update to WP Core 5.6
2. Go to Groups
3. Type username into 'Add New Members'
4. No list of users will be displayed when starting to type

The expected behaviour when typing a username is a list of users should be displayed allowing you to select

Please can you let me know if anyone else is experiencing this issue?

**Comment by dkvasani** [comment]
Hi @welshlamb10 and @sourabhmatolia 

Can you please add screenshots here.

I am not able to understand in which page you are exactly talking about ?

Thanks

**Comment by welshlamb10** [comment]
@dkvasani - no problem, here is a screenshot. I hope this helps.
![issue](https://user-images.githubusercontent.com/33103165/102591488-fff9bc80-4109-11eb-8819-30a7245d71cc.png)
screenshot

**Comment by welshlamb10** [comment]
Bug related to another 3rd party plugin.
