### ISSUE TITLE
Email links without href

### ISSUE THREAD

**Issue by jstriedinger** [buddyboss/buddyboss-platform#1915]
Hi!
Every single email delivered by our site does NOT include the href attribute in any link. I have no idea why. 
We have a site in AWS lightsail and using Amazon SES as smtp with the offload ses plugin.

There is also no way to edit the email tokens of buddyboss (as far as I know) so there is really nothing I can do. Attached some pics of the situation.

![Captura2](https://user-images.githubusercontent.com/2267876/102410766-02033480-3fbf-11eb-8610-6af50823fb4a.JPG)
![Captura1](https://user-images.githubusercontent.com/2267876/102410763-016a9e00-3fbf-11eb-95fa-495218bbcbf1.JPG)

Thanks!

**Comment by imehedidev** [comment]
@jstriedinger We have tried to reproduce the issue with the latest version of the BuddyBoss Platform. Can you please recheck with the latest version? We are closing this issue for now. If you can replicate the issue, you may reopen this.
