### ISSUE TITLE
 Mention's notification does not disappear automatically after reading the message.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1919]
**Describe the bug**
When you @mention in the comment section of a blog post, it generates a notification but the notification count doesn't disappear automatically once you click and read the message.

**To Reproduce**
http://somup.com/cYlbjc2kNs

**Expected behavior**
It should be automatically disappeared once you click and read the message.

**Support ticket links**
https://secure.helpscout.net/conversation/1355854784/112706?folderId=3701248

**Comment by mahedihasannoman** [comment]
Hi @furqanbb , I have gone through some testing and unable to replicate this issue anymore. Please refer to my video: https://www.loom.com/share/4d96ab4b3ff94a099ac84df25f1699f9
Please check on your end and close this ticket if you are not able to replicate this issue anymore.
Thanks
