### ISSUE TITLE
Members of hidden groups cannot access subforums in the hidden group

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#1920]
**Describe the bug**
 I have a situations whereby members of hidden groups cannot access subforums in the hidden group. I am getting an error 404 message when I try to access subforums as a member of the hidden group. .

**To Reproduce**
1. Go to any group tab and  edit any group option, then checked "Group forum setting enabled"
2. Go to Forum tab, view forum and then click on member
3.  Then click on member profile and go to view  as  then click on the same group as we edit previously
4.  You can subforum option then you can click on that forum, then getting 404 error.

**Screenshots**
https://www.loom.com/share/48208f9a1ba04c089b5ce2b6735d5784

**Support ticket links**
https://secure.helpscout.net/conversation/1365303413/114489?folderId=4265312

**Comment by meetmakadiya** [comment]
PR already added: https://github.com/buddyboss/buddyboss-platform/pull/2117
