### ISSUE TITLE
Bad Username and Nickname allowed when signup is done via Memberpress Plugin

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#1946]
**Describe the bug**
When Memberpress is used for user registration process, the user can choose their email as username. This is not a problem for wordpress or Memberpress but that leads to some errors in Buddyboss.

Examples of errors : Mention and messaging don't work anymore because the nickname is the email ( the nickname looks like : @john.doe@email.com)

Here is the solution I've found for the moment (still need some tests) : 

```
function pf_validate_bb_nickname_from_memberpress( $errors ) {
    $nickname   = (string) sanitize_text_field( $_POST[ 'user_login' ] );
	$field_id   = bp_xprofile_nickname_field_id();
	$field_name = xprofile_get_field( $field_id )->name;

	$message    = bp_xprofile_validate_nickname_value('', $field_id, $nickname, '');

	if (! empty( $message ) ){
		$errors[ 'user_login' ] = str_replace( $field_name, __('Username', 'memberpress'), $message);
	}

	return $errors;
}
add_filter('mepr-validate-signup', 'pf_validate_bb_nickname_from_memberpress');
```

**To Reproduce**
1. Register a new user using Memberpress
2. Fill the email address as Username

**Expected behavior**
User should not be able to register an account using an email as the username.

**Screenshots**
none

**Support ticket links**
none

**Jira issue** : [PROD-876]

[PROD-876]: https://buddyboss.atlassian.net/browse/PROD-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bstillLloyd** [comment]
It should also be noted that when a Nickname contains an email - that user can't edit their Buddyboss profile fields due to the "nickname" validation failing on the front end when saving the profile form.

I am currently experiencing this issue on a client site.
