### ISSUE TITLE
Allow administrators to assign the group parent without joining any groups

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1956]
**Is your feature request related to a problem? Please describe.**
Currently, if you are an Administrator and not part of any groups, you cannot assign any group parent.

**Describe the solution you'd like**
To be able to assign any group parent without joining any groups if you have an Administrator account

**Screenshot**
![group-parent](https://user-images.githubusercontent.com/58522498/103096216-2bb30000-463e-11eb-88dc-70ef8b65be5f.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1373861610/115966

**Jira issue** : [PROD-875]

[PROD-875]: https://buddyboss.atlassian.net/browse/PROD-875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mikejyoung** [comment]
@sourabhmatolia 
I'm marking this as a bug rather than a feature request as admins should always be able to do this kind of functionality.

**Comment by ayron-paul** [comment]
Hi @ngolwalkar,

Steps to reproduce:
1. Create at least two Admin accounts
2. Using the first admin you created, create multiple groups
3. Now logged in using the second admin account
4. Go to any groups that were created from the first admin account
5. Notice that nothing is on the list of Group Parent

Screenshots:
- Using an admin who is a member of all groups https://i.ibb.co/Z8rmNMw/1.png
- Using an admin that is NOT a part of any groups https://i.ibb.co/y6xYtd7/2.png

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1724849299/178348/

**Comment by jnlr** [comment]
Any solution for this "bug" ?
We encounter the same issue here :(
I need an account on https://secure.helpscout.net/conversation/1724849299/178348/ to check the end of this thread...
