### ISSUE TITLE
Group Page: Sidebar message keeps on loading

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1969]
**Describe the bug**
When sending message through any group page, the message in sidebar keeps on loading

**To Reproduce**
1. Go to any group page
2. Click to "Send Messages"
3. Scroll down the sidebar
4. The members keep on loading

**Expected behavior**

**Screenshots**
 https://www.loom.com/share/1c3111a2d051491da4329822358147c4

**Support ticket links**
https://secure.helpscout.net/conversation/1371849330/115634

**Comment by sourabhmatolia** [comment]
@jrbuddyboss 

Issue fixed here:
https://github.com/buddyboss/buddyboss-platform/pull/1922

It will be released soon. Thanks.
