### ISSUE TITLE
Getting Warning on User blog Bookmark tab on the buddyboss user profile Page.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1970]
**Describe the bug**
If wp-debug mode is enabled, getting Warning on the Bookmark tab on the buddyboss user profile page and posts are automatically being bookmarked for all users. Please refer to the screen recording.
http://somup.com/cYlvi82LZ8

**To Reproduce**
1. Go to 'Enable wp-debug mode' and Install/Activate the BP User Blog plugin.
2.  Go to Profile page > Blog > Bookmark tab
3. See an error and automatically bookmarked posts.

**Screenshots**
https://prnt.sc/wbd4rd

**Support ticket links**
https://secure.helpscout.net/conversation/1380062262/116886?folderId=3701248

**Comment by manishpatolia** [comment]
@furqanbb This is not platform related issue. 
This issue with the **BuddyPress User Blog** plugin so I have fixed this issue in this plugin repo.

So I'm closing this issue here.

@ankitguptaindia I have fixed the issue and pushed the code on BP user blog repo.

Thanks.
