### ISSUE TITLE
Rest API Endpoint : Unable to understand how to post images and create bp_media_ids Please help

### ISSUE THREAD

**Issue by pavan2reach** [buddyboss/buddyboss-platform#1975]
`POST {{root_url}}/wp-json/buddyboss/v1/activity?user_id=22&component=activity&content="This is a sample Post from Json"`

In the above query, **content="This is a sample Post from JSON"** instead of text I wanted to **send an image**, how to do that

Please help!!!

**Comment by KartikSuthar** [comment]
Hey @pavan2reach 

you need to upload the image by using the media upload endpoint: http://prntscr.com/wc0uh9
you will get the `upload_id`

you need to pass those as `bp_media_ids` in an activity post request.
http://prntscr.com/wc0vtx

Thanks!
