### ISSUE TITLE
Infinite loading after deleting messages

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#1982]
**Describe the bug**
Shows infinite loading after clicking the "Delete your messages" 

**To Reproduce**
1. Go to Messages
2. Message user
3. Click the menu icon dots
4. Click Delete your messages

**Expected behavior**
Will delete the messages 

**Screenshots**
https://prnt.sc/wdlxby

**Comment by nitishkaila** [comment]
@amincdev I have checked this issue and found that `#bp-message-thread-list:empty:before` CSS selector displaying the loader when the message thread empty. Can you please take a look on your end?

**Comment by sourabhmatolia** [comment]
@nitishkaila 

This is not front-end work. Something you should be able to handle.

IF we are sending a message to a member on the site for the first time and when we click on "Delete your message" then it basically deletes the thread and it should open another recent thread for the logged-in member.
IF no other thread found then it should look empty like this: https://prnt.sc/z7z1gi

Right now when ul tag is empty then CSS is getting applied. But if we trigger to show the previous thread or empty message screen then it will work fine.
You can still talk to Amin if you need help. But something you can handle.

Thanks.

**Comment by nitishkaila** [comment]
@sourabhmatolia @amincdev  

I have submitted a pull request for this issue.

https://github.com/buddyboss/buddyboss-platform/pull/2147

Thanks
