### ISSUE TITLE
Integrating BuddyPress Documentation into Platform

### ISSUE THREAD

**Issue by vingogly** [buddyboss/buddyboss-platform#1983]
The BuddyBoss  documentation needs to provide a link to the relevant BuddyPress documentation where ever it's needed, since many people coming to BuddyBoss didn't come to it as experienced BuddyPress users. An alternative would be to merge the BuddyPress documentation into the Platform documentation.

Here is an example: a current thread on Facebook asks: "Is there a shortcode or alternative redirect that I can use which after login, the USER gets redirected to the course page on buddyboss? I can't figure out USERNAME alternative or placeholder."

Graham Hoffman responded that the placeholder is /me/ - and states that this is in the BuddyPress documentation. A user of Platform shouldn't have to flip back and forth between this site and BuddyPress to answer a question - and you have many users who have no idea what the relationship is between BuddyPress and BuddyBoss. Frankly, I've looked up the /me/ placeholder issue multiple times because I keep forgetting. 

This is a usability issue - and it's not just about the /me/ placeholder, it's something that should be addressed in the documentation. My advice is: contract with a good information architect/usability expert to go over all the documentation and restructure it, integrating BuddyPress docs with the Platform docs. Having a Facebook group and a knowledge base that only covers BuddyBoss isn't adequate.

**Comment by mikejyoung** [comment]
HI @vingogly 

Thank you for this feedback.

I've logged this request to be brought up in internal discussions regarding improving the BuddyBoss documentation.

I'm going to close this issue now.

Mike
Product Manager
