### ISSUE TITLE
Location Autocomplete plugin messes up search results of BuddyBoss Platform

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1989]
**Describe the bug**
When Location Autocomplete plugin is activated on BuddyBoss Platform, this throws an error and showing no search results on initial load

**To Reproduce**
1. Install Location Autocomplete plugin with BuddyBoss Platform
2. On frontend, search some term
3. See error

**Expected behavior**
this works when BuddyPress and different theme activated

**Screenshots**
https://drive.google.com/file/d/1OWdQHyvHAgrWIZyBktzJgrejz5IDvNUR/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1381998258/117262

**Comment by janakkaneriya007** [comment]
@emmanoctaviano 
This been fixed and merged here: https://github.com/buddyboss/buddyboss-platform/issues/2009
Can close it after checking on your side.

**Comment by janakkaneriya007** [comment]
Liked issue is already fixed so closing this issue.
