### ISSUE TITLE
CSS Conflict with LearnDash plugin

### ISSUE THREAD

**Issue by bornforlamp** [buddyboss/buddyboss-platform#1993]
**Describe the bug**
CSS Conflict with LearnDash plugin inside BuddyBoss > Theme Options > BuddyPanel, Tried to share CSS to customer, but customer wants a long term fix instead of temporary CSS.

**To Reproduce**
1. Go to  BuddyBoss > Theme Options > BuddyPanel
2. Have LearnDash plugin enabled
3. Check BuddyPanel Position and BuddyPanel Default State, The Left/Right and Open/Closed label are not at proper location.

**Expected behavior**
Proper styling for texts

**Screenshots**
https://www.dropbox.com/s/33wfi4u2pviuoim/Screenshot_2.png?dl=0

**Support ticket links**
https://secure.helpscout.net/conversation/1383140162/117502?folderId=3709081

**Comment by shashank-buddyboss** [comment]
This is related to **Theme** so closing this one and created below one.

URL: https://github.com/buddyboss/buddyboss-theme/issues/1263

Thanks.
