### ISSUE TITLE
Taxonomy Tags (Category) on Community Media Submissions

### ISSUE THREAD

**Issue by dmuellerstl** [buddyboss/buddyboss-platform#1998]
**Is your feature request related to a problem? Please describe.**
Feature does not exist. This is a request/recommendation.

**Describe the solution you'd like**
Option to enable media "Category" taxonomy tags so that user media/document uploads can be tagged from a set of pre-defined category taxonomy terms. For example, a user may upload a photo and in the modal window where they upload the image and enter an optional description, choose from a set of pre-defined categories (taxonomy terms) for their upload, similar to how posts are categorized. In this way, users are able to categorize their uploads so that they can be automatically displayed in collections elsewhere on the site by category. If a user uploads a video (on roadmap 2021 Q1), they could tag it with the category "Short Video" or "Long Video" or any number of available terms created by the admin so that their upload automatically goes into a specific collection/gallery without the need for admin moderation. This should be a fairly simple feature to introduce by enabling a Category taxonomy on media by plugin option and then adding a term selector to the user's media upload/edit view/modal. 

**Describe alternatives you've considered**
Implemented the Category taxonomy on Media/attachment posts so that an administrator can go into the media library and categorize user uploaded content manually. This is basically just adding standard taxonomy/terms to media uploads but requires admin moderation/pruning instead of letting the community contribute to these collections automatically. That is why it would be helpful for users to have this option during their upload/edit process on photos/videos they upload. 

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by marienel21** [comment]
Hi @dmuellerstl ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
