### ISSUE TITLE
Theme options sidebars buttons are not displaying correctly

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2004]
**Describe the bug**
BuddyBoss > Theme Options > Sidebars buttons resize when LearnDash LMS is active 

**To Reproduce**
1. Make sure LearnDash LMS is enabled
2. Go to BuddyBoss > Theme Options > Sidebars 
3. See error

**Screenshots**
![download](https://user-images.githubusercontent.com/74121050/103629156-f16d2b00-4f7a-11eb-8a54-3aef5dd5c6da.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1386320521/118125

**Comment by amincdev** [comment]
@Santos-Jamie Closing this issue because this issue has been fixed and released in BuddyBoss theme.
