### ISSUE TITLE
After restoring a trashed discussion or reply, it turns into a draft

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2023]
**Describe the bug**
When you delete a discussion or a reply, then restore them, it disappears on the frontend because it becomes a draft.

**To Reproduce**
1. Go to the forum.
2. Select a discussion or a reply.
3. Delete the discussion or reply.
4. Try to restore them and notice it will disappear and becomes a draft.

**Screencast**
https://cutt.ly/QjllcZj

**Support ticket links**
https://secure.helpscout.net/conversation/1386921500/118253

**Comment by roopeshbuddyboss** [comment]
Hi @ayron-paul ,

For reply the PR is https://github.com/buddyboss/buddyboss-platform/pull/2479 and it's merged in the release branch.

For discussion PR is https://github.com/buddyboss/buddyboss-platform/pull/2605 and it's in the review state.

Thanks

**Comment by mahedihasannoman** [comment]
Duplicate issue: https://github.com/buddyboss/buddyboss-platform/issues/2441 & https://github.com/buddyboss/buddyboss-platform/issues/2467
