### ISSUE TITLE
Add notification for comments in Learndash Courses, Topics, Quizzes, Submitted Essays, Blogs and other CPTs

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#2026]
**Is your feature request related to a problem? Please describe.**
When comments are made on CPTS, LD Courses, Topics, Lessons and any other CPT's, authors should get a BB notifications on the users who commented on this. 

**Describe the solution you'd like**
Add notifications for commenting

**Support ticket links**
https://secure.helpscout.net/conversation/1385139244/117945

**Comment by giulianopires** [comment]
Any update on this?

**Comment by mikejyoung** [comment]
This is not something we are currently planning. 

I've imported this idea in our product management software. We'll review it as we plan new features. 

I'm closing this issue now as part of our effort to keep our backlog limited to features ready for development.
