### ISSUE TITLE
BB REST API - Activity Endpoint : Using group_id also returns sub-activities with secondary_item_id not null

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2035]
**Describe the bug**
In the previous version of BuddyBoss (1.5.*), in order to retrieve the activities inside a group, we had to make the following rest api request : 

`GET {{host}}/wp-json/buddyboss/v1/activity?context=embed&page=1&per_page=20&group_id=132`

That request used to return the same activities that the ones displayed in the website : {{host}}/groups/{{group_slud}}/

Since the update to BuddyBoss 1.6.*, the same request also returns activities where **secondary_item_id > 0** AND  **privacy=media**.

Even if you make the request `GET {{host}}/wp-json/buddyboss/v1/activity?context=embed&page=1&per_page=20&group_id=132&secondary_item_id=0`, it doesn't filter "main" activities (don't want to retrieve sub-activities).

**To Reproduce**
1. Go to a group page
2. Create an activity with multiple photos (upload multiples photos)
3. Make the request `GET {{host}}/wp-json/buddyboss/v1/activity?context=embed&page=1&per_page=20&group_id=132`

**Expected behavior**
That request should only returns main activities (with secondary_item_id = 0) and not the main activity + each sub-activity linked to each media.

**Screenshots**
none

**Support ticket links**
none

**Comment by mahedihasannoman** [comment]
Unable to reproduce this issue. Please see the screenshot below.
![screenshot-app-live browserstack com-2021 08 24-21_47_06](https://user-images.githubusercontent.com/12556175/130648718-5316832a-7165-4d1c-98c5-0b5042c32293.png)

Also the API endpoint should be the following:
`{{host}}/wp-json/buddyboss/v1/activity?_embed=true&per_page=10&page=1&display_comments=threaded&search=&component=groups&primary_id=11`
