### ISSUE TITLE
I have a suggestion for improving URL parsing feature for the activity post form

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2036]
**Is your feature request related to a problem? Please describe.**
One of our customer came across with an issue that some URL is not showing preview in activity feed for example: [https://colourpop.com/products/rose-lip-mask-moisturizer](https://colourpop.com/products/rose-lip-mask-moisturizer).

It says Access Denied in preview like the screenshot: [https://prnt.sc/wlx65w](https://prnt.sc/wlx65w)

If you add any **shopify** or **Squarespace** site URL then it will not show the link preview.

Video: https://www.loom.com/share/7e54b3b3c4fe47fa8a0ebafdd52659c1

I know this could be happen for many reason like the site content could be private or site administrator does not allow to access anything other then human etc. but when I dive into the source code and done some debugging I found when I pass an user-agent the URL is getting accessible instantly. So I thing there is a room of improvement when we parsing URL in the activity post area.

**Describe the solution you'd like**
We can make use of the user's user-agent since they are posting an activity through the browser. I saw buddyboss-platform currently passing empty string for the user-agent key in this file buddyboss-platform/bp-core/bp-core-functions.php on line 4939. Screenshot: [https://prnt.sc/wlxmxi](https://prnt.sc/wlxmxi)

So my suggestion would be instead of passing an empty string for the user agent key we can make use of this supper global variable: $_SERVER['HTTP_USER_AGENT'] or use WP default user agent. Suggested code should be look like the below one.

$user_agent = '';
if( isset( $_SERVER['HTTP_USER_AGENT'] ) && $_SERVER['HTTP_USER_AGENT'] != '' ){
	$user_agent = $_SERVER['HTTP_USER_AGENT'];
}
// safely get URL and response body.
$response = wp_safe_remote_get(
	$url,
	array(
		'user-agent' => $user_agent, // Default value being blocked by Cloudflare
	)
);
$body     = wp_remote_retrieve_body( $response );

I have tested the code works well in almost every possible situation.

**Support ticket links**
The issue was originally reported in this ticket: [https://secure.helpscout.net/conversation/1393537424/119351](https://secure.helpscout.net/conversation/1393537424/119351)

**Jira issue** : [PROD-982]

[PROD-982]: https://buddyboss.atlassian.net/browse/PROD-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Nayeem-BB** [comment]
https://secure.helpscout.net/conversation/1573484195/153812
