### ISSUE TITLE
Discussions or replies cannot be searched when they are not associated with any groups.

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2045]
**To Reproduce**
1. Create a forum.
2. Add a discussion.
3. Add a reply.
4. Make sure that forums, discussions, and replies are enabled in the network search setting. https://i.ibb.co/MGvrzBm/search.jpg
5. Go to the frontend and try to search the discussion/reply you just created.
6. Notice that you cannot find it. Try to associate that forum to any groups and that when you can search it.

**Screenshots**
![discussionreply](https://user-images.githubusercontent.com/58522498/104745309-e8553880-5788-11eb-861a-5f43d98f9208.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1395857303/119775

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1385199545/117953/

**Comment by marilyn9425** [comment]
marking as closed. issue resolved.
