### ISSUE TITLE
Delete account button is not working from Account > Delete Account page for users

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2055]
**Describe the bug**
Delete account button is not working from Account > Delete Account page for users whether they have checked the "I understand the consequences" checkbox. See the screenshot for more info

**Screenshots**
[https://prnt.sc/x4oak3](https://prnt.sc/x4oak3)

**Support ticket links**
[https://secure.helpscout.net/conversation/1393433379/119334](https://secure.helpscout.net/conversation/1393433379/119334)

**Comment by lunchinnet** [comment]
This is something we need prioritized and solved as well.

**Comment by sohomnet** [comment]
Is this fix pushed into Version1.5.7.3?

**Comment by sourabhmatolia** [comment]
@lunchinnet @sohomnet

Issue mentioned above is released in BuddyBoss Platform v1.5.8

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-8/

Please update the plugin to see the latest changes.

Thank you.
