### ISSUE TITLE
The slug is conflicting when we use under public content.

### ISSUE THREAD

**Issue by anand-bb** [buddyboss/buddyboss-platform#2057]
**Describe the bug**
When the site is on private mode and the client allowed a few pages under public content so it is conflicting with the slugs.
For example, there are two pages.
News Feeds (Slug -> news-feeds) (Private)
News  (Slug -> news) (Public)

Since the News page is public, the code is considering News feeds public as well.
I tried to make understand the client that it is because of the conflict of the slugs.

**To Reproduce**
Create two pages.
a) News feed
b) News

Mark the News feed page as private and News page as public and you will see the conflict.

**Expected behavior**
I guess we should match the **Exact slug** so even if this is the case, the news page could remain public and news-feeds could be private.

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1399214242/120439?folderId=4312419

**Comment by ngolwalkar** [comment]
After discussion with @anand-bb, there is no issue with this, so closing this issue.
