### ISSUE TITLE
Loco Translate Spanish "members" to "miembros"

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#2058]
**Describe the bug**
Translate "members" to "miembros"

**To Reproduce**
1. Go to group page
2. Check the members to count.
3. It should be miembros.

**Expected behavior**
members should be miembros

**Screenshots**
https://prnt.sc/x6fii4

**Support ticket links**
https://secure.helpscout.net/conversation/1399571585/120482

**Comment by milanhirapra** [comment]
@jrbuddyboss 

This string comes from the buddyboss theme.
Here is the video how to translate this string : https://vimeo.com/590989588/17995a28d2
