### ISSUE TITLE
(BB) Forum List Widgets Disregarding (Parent Forum ID) on the widget query

### ISSUE THREAD

**Issue by hercivalbuddyboss** [buddyboss/buddyboss-platform#2064]
**Describe the bug**
Any of this option ( "0" to show only root - "any" to show all ) is disregarded by the query. The client is confused by these options. No Difference in the results whether "0" or "any" arguments. i found out that the function widget is disregarding this option.

**To Reproduce**
---

**Expected behavior**
If we continue with this option, we should improve the query according to this option( "0" to show only root - "any" to show all ) or totally remove this option on the forum list widget

**Screenshots**
[https://prnt.sc/xdktie](https://prnt.sc/xdktie)
[https://prnt.sc/xfceh0](https://prnt.sc/xfceh0)
[https://prnt.sc/xfe3p0](https://prnt.sc/xfe3p0)

**Support ticket links**
[https://secure.helpscout.net/conversation/1396840734/119948?folderId=4222127](https://secure.helpscout.net/conversation/1396840734/119948?folderId=4222127)

**Jira issue** : [PROD-865]

[PROD-865]: https://buddyboss.atlassian.net/browse/PROD-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bonebusta** [comment]
Adding HS ticket as a reference. 
https://secure.helpscout.net/conversation/1424098234/124882/
