### ISSUE TITLE
Forum search not working properly

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#2069]
**Describe the bug**
When users search in Forum Search box, the search function does not work even if you enter a correct term like a Forum title
When you also search for a term with no available query, after hitting enter, the forum results shows blank

**To Reproduce**
This issue can be reproduced on our demo
1. Go to Forums page
2. Search for a correct query, like forum title
3. See error, this loader shows no result
4. Search again using a term that have no query and hit enter
5. Then remove your search term and hit enter again
6. The results still shows blank

**Expected behavior**
Forum search should work consistently

**Screenshots**
https://drive.google.com/file/d/10GMslo-4yktFAhJgVA97d1gEker1EUM6/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1400222589/120581
https://secure.helpscout.net/conversation/1405186781/121644

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1412795731/122990/
