### ISSUE TITLE
Pagination count displaying twice on the "No replies" and "Most Popular Discussions" forum

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2071]
**Describe the bug**
The "No replies" and "Most Popular Discussions" forums has additional pagination count on the top which should only be at the bottom of the page 

**To Reproduce**
1. Go to https://demos.buddyboss.com/online-communities/forums/view/no-replies/ or https://demos.buddyboss.com/online-communities/forums/view/popular/
2. You will see the first pagination on the top and second at the bottom

**Expected behavior**
Pagination count will only be visible at the bottom of the page like the other forum-related pages

**Support ticket links**
https://secure.helpscout.net/conversation/1406193368/121819

**Comment by mahedihasannoman** [comment]
Hi @Santos-Jamie , This is not an issue. This is a default behaviour that pagination will show at top and bottom as well. Please close this ticket.
