### ISSUE TITLE
Invite by email an external user to directly join a group (Group Send Invites functionality)

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2075]
**Is your feature request related to a problem? Please describe.**
For the moment, we can invite an external user to join the community with the component "send invites" (**/members/exogeek/invites/**). That invitation is linked to a member. 

I would like to have a similar feature for the group. I would like to be able to create a group and invite external users to join that group. When the guest register his new account, he is automatically invited to join the group from where he was invited.

Obviously, there's some security concerns when the group is hidden or private. But with "secret_key", we can find a way to preserve security (see description below).

**Describe the solution you'd like**
1) Generate a random secret key ([a-zA-Z0-9]{8}) for each group.
2) Store that secret key in the database (bp_groups_groupmeta) : use meta_key "invite_secret_key".
3) Add a new menu in the group page where user can "send invites".
4) Send an email to invite the external user. That email contains a href link containing the secret key (For example, if the secret key is 'Ad45g45fG', the link could looks like https://host/group/invite/Ad45g45fG).
5) When user click on that link, route the user to the registration page/the login page.
6) As soon as his accound is created/loggedin, invite him to join the group (automatically create a group invitation for the group where "invite_secret_key" = "Ad45g45fG").

- Group administrator should be able to generate a new secret_key (if the existing secret_key has been stolen).
- Group admin should be able to disable that functionality.

**Describe alternatives you've considered**
none

**Support ticket links**
none

**Comment by Thierry333** [comment]
Good idea! 
this could be a nice way to foster new links

**Comment by marienel21** [comment]
Hi @ExoGeek ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Comment by bi1101** [comment]
Are there any updates on this feature?
