### ISSUE TITLE
The Groups is not appearing in the search result when the Location auto-complete for BuddyPress activate 

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#2087]
**Describe the bug**
The Groups is not appearing in the search result when the Location auto-complete for BuddyPress activate 

**To Reproduce**
https://www.loom.com/share/69e3b40ffd524a5989821488362dcf28

**Support ticket links**
https://secure.helpscout.net/conversation/1407830238/122145?folderId=3955985

**Comment by mahedihasannoman** [comment]
Hi @jakir-git I have gone through some testing and unable to replicate this issue anymore. Please see my video: https://www.loom.com/share/34409f744e804b38969c6e75a48c8049
If you are not able to replicate this issue on your end then please close this ticket.
