### ISSUE TITLE
Facebook live URL Preview showing update your browser while posting on the Activity Feed

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#2094]
**Describe the bug**
Concern: A few days ago they can put the link of his Facebook live video in the group or the activity fee page. But now they cant. When they put the link of the FBLive video it just says "update your browser" indeed it has a link
Troubleshooting/Testing Steps Attempted: Adv cust to update browser or use a different browser to test. They did, experienced the same issue.

**To Reproduce**
https://www.loom.com/share/cc22b5715d8f4a26a90803e04278ebb3

**Support ticket links**
https://secure.helpscout.net/conversation/1401968366/120942?folderId=3955985

**Comment by chevectra87** [comment]
I have the same problem!

- WP version 5.7.2
- BuddyBoss Platform Pro version 1.1.3

Does someone know about a workaround to fix it? 

Does it possible to change the activity feed editor?
![Captura de Tela 2021-06-17 às 13 42 46](https://user-images.githubusercontent.com/4582019/122439303-ebd83000-cf71-11eb-8260-81806fca90a6.png)

**Comment by kishanjasani** [comment]
@jakir-git We are getting this message from Facebook and we do not have control over this request. So It's actually not an issue. Closing this, If you have findings regarding this, you can reopen the issue.
