### ISSUE TITLE
Unread message count shows wrong at the top bar.

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2097]
**Describe the bug**
Unread message count shows wrong at the top bar because it also counting unread messages from hidden threads.

**To Reproduce**
1. Send a message to Jessica
2. Login as Jessica then go the the messages page.
3. Then click on the (x) icon for the newly appeared thread without viewing the messages.
4. Now you should see the unread message count for the hidden threads and there is no way to remove the unread message count from the message notification area.

**Expected behavior**
There should not be unread message count for hidden threads

**Screenshots**
[https://prnt.sc/xxlg96](https://prnt.sc/xxlg96)

**Support ticket links**
[https://secure.helpscout.net/conversation/1406883779/121947?folderId=4178440](https://secure.helpscout.net/conversation/1406883779/121947?folderId=4178440)

**Comment by patriciaadr** [comment]
A client also reported the same issue: https://secure.helpscout.net/conversation/1530056704/145304

**Comment by harshalQA** [comment]
Fixed.

Added QA comment against PR: https://github.com/buddyboss/buddyboss-platform/pull/2826#issuecomment-917869813
