### ISSUE TITLE
Hidden Groups Appear in User Profiles

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2100]
**Describe the bug**
Hidden groups are visible to other member https://prnt.sc/x8ff6v
If you go to a profile, click groups you do see the groups that are hidden. If you click on a group you are not in that is hidden, you get an error page. https://www.loom.com/share/7945f71d22aa4557a4c5dcaf3e41e341

**Expected behavior**
Hidden group should not be visible to other member.

**Screenshots**
https://www.loom.com/share/9db56894f1c74d86a92bcf63ab62cd7c

**Support ticket links**
https://secure.helpscout.net/conversation/1400540208/120636/

**Comment by nayeemparvezchowdhury** [comment]
https://secure.helpscout.net/conversation/1409979426/122509/

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1435170974/126987?folderId=3701248

**Comment by welshlamb10** [comment]
I have found same bug. Needs addressing urgently!

**Comment by harshadmane** [comment]
Another issue: https://secure.helpscout.net/conversation/1452430212/130419/

**Comment by krunal-buddyboss** [comment]
@chetansatasiya 
I have applied this changes after discussed with @dipskakadiya as some scenario was failed to show hidden groups for logged in user on profile page. After apply these changes all scenarios looks good I have also checked and verified. Thanks.
+ @mehulkaklotar
