### ISSUE TITLE
PHP 8.0 Deprecate required parameters after optional parameters

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#2101]
Deprecated error for buddyboss platform with PHP 8.0 & WP 5.6 installation
I'm getting an error in the front side and backend as well - Deprecated | Required parameter $option follows optional parameter $value

See the screenshot for more details: [https://prnt.sc/y01dzu](https://prnt.sc/y01dzu)

**To Reproduce**
You will see the error for PHP 8.0 & WP 5.6 environment

**Expected behavior**
Should not be any Deprecated error.

**Screenshots**
[https://prnt.sc/y01dzu](https://prnt.sc/y01dzu)
[https://prnt.sc/y01e2q](https://prnt.sc/y01e2q)

**Comment by sadrul** [comment]
@sumitbuddyboss This issue is fixed on `feature/membership` branch and merged to dev by @chetansatasiya. Can you please test.

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

Fixed > 
I have checked in the dev branch and the related issue is resolved, for the proof please check the below video.

video:
https://www.loom.com/share/5d516f27545142b184598d4138b84967
https://prnt.sc/y054ig


@chetansatasiya 
Ready to release 🚀
