### ISSUE TITLE
Forum association with groups

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#2112]
**Describe the bug**
When 1 Forum is associated with 1 group then that forum cannot be associated with any other group. That should be the logic.
So when forum is associated with 1 group then that Forum should not show in dropdown in frontend and backend group screens. Create Group in Frontend, Manage Group in Frontend, Edit Group in Backend.
Also there should be logic while saving Forum settings to check if Forum already associated, if YES then throw error.
I think you can create issue OR note details in existing issue if any.
You have someone work on it. Thanks

-----

**Further UPDATE**

**Check Video**: https://www.loom.com/share/cbb6379fa57d45e3a8369860416398d6

- Do not allow same Forum to be associated with more than 1 Group. (already scoped above)

- Do not allow to associate sub-forums or any level child forums to any group no matter if parent forum associated with Group or No.
Do not allow to associate Forums Type Category also with the Group.
Needs to be taken care of Adding/Editing Group backend, Adding/Editing Group Frontend.

- When Forum associated with Group then Forum and all level child Forums "Visibility" Field should be disabled.

- Disable "Forum Parent" and "Type" Field when the main Forum associated with Group.

- Group Forum's Sub-Forums will inherit the same privacy as Group.
Layout will be same as Parent forum in Groups.
Single Sub-Forum URL in Group:
domain.com/groups/GROUP_SLUG/forums/SUB_FORUM_SLUG
Sub-Forum Single Discussion URL in Group (same as parent forum discussion):
domain.com/groups/GROUP_SLUG/forums/topic/DISCUSSION_SLUG/

- Sub-Forums and all level child forums and discussions always should be linked to Group URL if associated same as Parent Forum from Backend and Frontend.

- Make sure everything here is backward compatible.
IF currently one forum associated with multiple Group then let it work as it is otherwise it will break the existing customer site.
	- Same set of discussion show for both the groups
	- View Forum redirects to any one of the Group. Maybe the one assigned last. That's how it is.
	- Same workflow for child forums.
IF currently any sub-forum associated with Group then also it should work fine.

- Make sure all change here works fine with Forum settings "Allow social groups to have their own forums" both enabled or disabled.
- Settings > Forums > Group Forums Parent, Remove this settings option from BB settings panel.
Make sure everything here is backward compatible.

### Related Platform API PR
https://github.com/buddyboss/buddyboss-platform-api/pull/300

### Related Theme PR
https://github.com/buddyboss/buddyboss-theme/pull/1345

### Related App Native Issue
https://github.com/buddyboss/buddyboss-app-native/issues/1518

**Comment by shakilAshraful** [comment]
### App Scope

@asaquzzamanbb Bhai, Found 2 two areas that directly concern the App with respect to this task. Adjustments are required in the APIs as described below- 

cc @sourabhmatolia 
___

1. At the time of selecting forums in the group creation process (or during a group settings edit), the app shows the forum list received from the group settings API (curl attached).  The app would need the filtered list coming from the API where the response excludes -
   - Forums having the type “Category”
   - Child Forums
   - Forums already associated with other groups 

[Find the entry in index 2 then `options`  in the response]
```
 curl -H "accept:application/json, text/plain, */*" -H "keep-alive:true" -H "connection:keep-alive" -H "accesstoken:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYmItYXBwLXBsYXRmb3JtLmZseXdoZWVsc2l0ZXMuY29tOnJlc3QtYXBpIiwiaWF0IjoxNjI3NjI4Nzc3LCJuYmYiOjE2Mjc2Mjg3NzcsImV4cCI6MTYzNTQwNDc3NywianRpIjoiRVleNkZHVjZTREdATzVqUjAzc216OEcxR003JDVLXlcxdUN4YllhQkhtQCIsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.1w_PSza6WcekVDt56J_G-QGJH14x1_H2_i8y4Z--LeE" -H "appid:dd4a7c" -H "appversion:2.0.1" -H "appcodeversion:1.2.9" -H "appplatform:ios" https://bb-app-platform.flywheelsites.com/wp-json/buddyboss/v1/groups/329/settings?nav=forum
```
   
 2. Sub-forums need to contain the group reference when their parent forum is connected to a group. The curl below returns a forum where it has value in the `group` field as well as `_embedded.group[0]` however, for nested sub-forums, the `group` field is empty and when the same API is called with one of the nested sub-forum ids, the response doesn't embed the group object.
 ```
 curl -H "accept:application/json, text/plain, */*" -H "keep-alive:true" -H "connection:keep-alive" -H "accesstoken:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYmItYXBwLXBsYXRmb3JtLmZseXdoZWVsc2l0ZXMuY29tOnJlc3QtYXBpIiwiaWF0IjoxNjI3NjMyMzQyLCJuYmYiOjE2Mjc2MzIzNDIsImV4cCI6MTYzNTQwODM0MiwianRpIjoibElEZFglaDZsMUFkSUFASnhpaiYxTSFFYnpPYlU2YVAkZWs0UyEoMDZjeSIsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.NsYPLGGZYOW5QiGPWGubhzRb6OVcEtR939MNgeRCOJY" -H "appid:dd4a7c" -H "appversion:2.0.1" -H "appcodeversion:1.2.9" -H "appplatform:ios" https://bb-app-platform.flywheelsites.com/wp-json/buddyboss/v1/forums/8836?_embed=true
 ```
 
- cURL for sub-forum (it doesn't contain any group data - embedded or otherwise):
 ```
 curl -H "accept:application/json, text/plain, */*" -H "appid:dd4a7c" -H "appversion:2.0.1" -H "accesstoken:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYmItYXBwLXBsYXRmb3JtLmZseXdoZWVsc2l0ZXMuY29tOnJlc3QtYXBpIiwiaWF0IjoxNjI3NjMyMzQyLCJuYmYiOjE2Mjc2MzIzNDIsImV4cCI6MTYzNTQwODM0MiwianRpIjoibElEZFglaDZsMUFkSUFASnhpaiYxTSFFYnpPYlU2YVAkZWs0UyEoMDZjeSIsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.NsYPLGGZYOW5QiGPWGubhzRb6OVcEtR939MNgeRCOJY" -H "keep-alive:true" -H "connection:keep-alive" -H "appcodeversion:1.2.9" -H "appplatform:ios" https://bb-app-platform.flywheelsites.com/wp-json/buddyboss/v1/forums/8842?_embed=true
 ```

**Comment by asaquzzamanbb** [comment]
@shakilAshraful @sourabhmatolia 

As per discussion with Shakil, there is no need for any changes **app native** side for this issue.

**Comment by shakilAshraful** [comment]
@sumitbuddyboss @mohit-buddyboss please make sure to test this on the android and iOS apps built from https://bb-app-platform.flywheelsites.com/, `appboss / Unfold#6Juliet`.

**Comment by shakilAshraful** [comment]
@sumitbuddyboss @mohit-buddyboss please make sure to test this on the android and iOS apps built from https://bb-app-platform.flywheelsites.com.

**Comment by shakilAshraful** [comment]
UPDATE: As discussed in the scoping call with @KartikSuthar & @chetansatasiya, new app scope has been revealed for this task. Further details of the scope are described in the bb app native issue - https://github.com/buddyboss/buddyboss-app-native/issues/1518

cc. @sourabhmatolia @asaquzzamanbb

**Comment by harshalQA** [comment]
QA status: Pass

All the related PR's are tested and Ready for release:

App native PR: https://github.com/buddyboss/buddyboss-app-native/issues/1518

Plugins and Platform PR's:
https://github.com/buddyboss/buddyboss-platform/pull/2117
https://github.com/buddyboss/buddyboss-theme/pull/1345
https://github.com/buddyboss/buddyboss-platform-api/pull/300
