### ISSUE TITLE
Forum > Uploading Media file create two instance of media file. 

### ISSUE THREAD

**Issue by sumitbuddyboss** [buddyboss/buddyboss-platform#2115]
**Describe the bug**
If the forum discussion is marked as closed and add a reply with photo and document then it will create two replies.

**To Reproduce**
1. Go to the forum  
2. Mark as closed
3. Add a new reply with a Photo or Document

**Expected behavior**
Photo and Document should be displayed only one reply.

**Related issue Theme**
https://github.com/buddyboss/buddyboss-theme/issues/1333

**Issue Video**
https://www.loom.com/share/0b410ff38c574894934a7459a5ecfeed

**Comment by chetansatasiya** [comment]
Closing this as this is related to theme.
