### ISSUE TITLE
Forum visibility issue. . 

### ISSUE THREAD

**Issue by nayeemch** [buddyboss/buddyboss-platform#2129]
**Describe the bug**
After creating a New forum and setting the visibility to Private, it shows a 404 page for logged out users. . . It should be redirected to the login page. . 

Even if you set the visibility to Public and Select a Private forum as Parent, it will be redirected to 404 for the logged out users. . 

**To Reproduce**

Create a Forum and select the setting like this https://i.imgur.com/vdP3AK8.png and open in an incognito window

Again on that Forum and select the setting like this https://i.imgur.com/11RrgeD.png and open in an incognito window

Same kind of issue from a client: https://www.loom.com/share/21a2dde176e9473dac8cc37151aa8021

**Expected behavior**
It should be redirected to Login page instead of taking to the 404 error page. . 

**Jira issue** : [PROD-858]

[PROD-858]: https://buddyboss.atlassian.net/browse/PROD-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by torpinouche** [comment]
Has any progress been made on this issue? It's really confusing to get a 404 when you click a link you received from a BuddyBoss email notification!

**Comment by torpinouche** [comment]
When you receive a notification email with a link to the post and you get 404 it makes no sense at all! You should be redirected to the login page so you can log and then access the post.
