### ISSUE TITLE
Inviting members to Sub group restricted to parent Group option not working

### ISSUE THREAD

**Issue by ghost** [buddyboss/buddyboss-platform#2133]
**Describe the bug**
Group owner can see all site members when clicking on invite member in hidden even if the option "Restrict Invitations" from the Group Hierarchies section is enabled in BuddyBoss > Settings > Group - https://prnt.sc/yvqqu8

**To Reproduce**
1. Go to any sub group 
2. Click on send invites
3. You should see all the site members in the send invites.

**Expected behavior**
Should only see members already enrolled in Parent group in Send invites, but all site members are in the list

**Support ticket links**
https://secure.helpscout.net/conversation/1421237136/124377?folderId=4304220

**Comment by milanhirapra** [comment]
Can't replicate this issue.
Here is the video: https://vimeo.com/591020751/35d7032179
