### ISSUE TITLE
Link Preview issue.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#2134]
**Describe the bug**
Posting a link with multiple previews is not working. after clicking in post update to post the link it will load several minutes and will have an error.
The link will be posted if the preview is removed but if the preview is not removed link will not be posted and will have errors.
https://prnt.sc/z2bgd9

**To Reproduce**
1- Go to the News Feed page.
2- Try to post the following link with a preview
https://www.cbc.ca/news/business/general-motors-electric-oilpatch-1.5905637
3- See error.

**Expected behavior**
Multiple preview links should also be posted in the activity feed.

**Screenshots**
https://prnt.sc/z2bgd9

**Support ticket links**
https://secure.helpscout.net/conversation/1422014906/124518/

**Comment by nayeemparvezchowdhury** [comment]
https://secure.helpscout.net/conversation/1432124167/126379/

**Comment by rmmehta** [comment]
Hello , 

I am able to add multiple Posting a link with multiple previews. 

Please see the screen shot for the same.

![screenshot-dev-riddhi flywheelsites com-2021 08 25-17_35_28](https://user-images.githubusercontent.com/82605214/130787510-870d0199-3848-4dc5-9c60-e3cda9e5427c.png)


I have used below links for reference: 

1) https://www.cbc.ca/news/business/general-motors-electric-oilpatch-1.5905637
2) https://www.wordstream.com/blog/ws/2015/02/09/how-to-write-a-blog-post
3) https://uplandsoftware.com/kapost/resources/blog/link-strategy-blog-posts/

Thanks,

**Comment by kishanjasani** [comment]
@rmmehta I already checked this issue. There is some issue with the few links.

Actually, we are downloading the images from these preview URLs and attach those images to the post attachment. But from few sites, the `wp_download_url` function is unable to download the images and it takes 4-5 min to complete the process of downloading.

In meantime, we are not able to see the preview for these URLs. But after few minutes we can see the preview.
