### ISSUE TITLE
New User Role Assignment doesn't stick upon initial User creation

### ISSUE THREAD

**Issue by ghost** [buddyboss/buddyboss-platform#2140]
**Describe the bug**
When Platform and Pro is active and we add a user from Users > Add New and assign a Role say for ex: Editor, the user role is switched to Subscriber

**To Reproduce**
1. Go to Users > Add New
2. Add a New user with Editor role 
3. When the page redirects to All Users page, the role is switched to Subscriber
4. Youtube video: https://youtu.be/D9KaORmWi8U

**Expected behavior**
The user role assigned should stick

**Support ticket links**
https://secure.helpscout.net/conversation/1424683981/124993?folderId=4304220

**Comment by Robeastius** [comment]
Good morning, I hope that this message finds you all well. Any idea when this issue/bug will be addressed? Also, is it necessary that I continue to have the test site up that this bug is associated to? I'd like to take it down by the end of the day. Thank you.

Sincerely,
Robert

**Comment by marienel21** [comment]
I can't replicate this bug on the latest version of the product.

**Comment by Robeastius** [comment]
Dear Team and @mikejyoung 

I just tested this same bug out today and I **was** able to replicate it and have been able to replicate it, reliably, since reporting it. Can we re-open this and look further into the issue? The problem was not solved and still exists. I am running BuddyBoss Platform Pro v1.1.4 with Wp v5.8, btw.

Thank you.

Sincerely,
Robert

**Comment by mikejyoung** [comment]
Hi @Robeastius 

I just tested this myself and could not validate the issue.

It is likely coming from a third-party plugin or theme. If you contact our support team, they can help validate the exact cause.

However, if the issue doesn't come from one of our official integrations, it will would need to be escalated to the third-party plugin or theme developer.
