### ISSUE TITLE
Replying to Private Messages is not working when Social Groups Component is deactivated

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2141]
**To Reproduce**
1. Deactivate Social Groups Component.
2. Go to Messages and reply to any of your friends
3. Notice the error.

**Expected Behavior**
Private messaging should work even without social groups component. It was working using previous versions

**Screencast**
https://cutt.ly/AkCqhQA

**Screenshots**
![ss](https://user-images.githubusercontent.com/58522498/107863704-4f056900-6e91-11eb-8ef7-3b331885dc58.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1423957635/124850/

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1426047500/125255/
