### ISSUE TITLE
Trying to get property 'post_parent' in /wp-content/plugins/buddyboss-platform/bp-forums/forums/template.php on line 732

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2142]
**Describe the bug**
The following PHP notice is showing in groups discussion page: Trying to get property 'post_parent' in /wp-content/plugins/buddyboss-platform/bp-forums/forums/template.php on line 732.
The notice is showing for PHP version: 7.4.15 

**Screenshots**
[https://prnt.sc/zii6og](https://prnt.sc/zii6og)

**Support ticket links**
[https://secure.helpscout.net/conversation/1425552472/125164?folderId=4314898](https://secure.helpscout.net/conversation/1425552472/125164?folderId=4314898)

**Comment by milanhirapra** [comment]
@mahedihasannoman 

I can't reproduce this. Please check the screenshot: https://nimb.ws/SFOfCg
