### ISSUE TITLE
'Undefined index' notices when using WP-CLI

### ISSUE THREAD

**Issue by lumpysimon** [buddyboss/buddyboss-platform#2163]
**Describe the bug**
When running any WP-CLI command on a site with the BuddyBoss theme installed, there are five `Undefined index` notices displayed, which clutters the output of the command and fills up the `debug.log` file if debugging is enabled.

**To Reproduce**
1. Run any WP-CLI command, such as `wp plugin list`

The following output appears before the list of plugins:

```
wp plugin list
Notice: Undefined index: SERVER_NAME in /Users/whoever/www/boss/wp-content/themes/buddyboss-theme/inc/admin/admin-init.php on line 18
Notice: Undefined index: SERVER_NAME in /Users/whoever/www/boss/wp-content/themes/buddyboss-theme/inc/admin/admin-init.php on line 18
Notice: Undefined index: SERVER_NAME in /Users/whoever/www/boss/wp-content/themes/buddyboss-theme/inc/admin/admin-init.php on line 18
Notice: Undefined index: SERVER_NAME in /Users/whoever/www/boss/wp-content/themes/buddyboss-theme/inc/admin/admin-init.php on line 18
Notice: Undefined index: SERVER_NAME in /Users/whoever/www/boss/wp-content/themes/buddyboss-theme/inc/admin/admin-init.php on line 18
```

**Expected behavior**
There should be no notices.

Thanks :)

**Comment by surajkrsingh** [comment]
@lumpysimon 
These PHP notices are already fixed in the theme.
On Commit - https://github.com/buddyboss/buddyboss-theme/commit/740e93b1bcd7e95c1e92e6deac9e6ee2b2c44775

I am closing this issue.
