### ISSUE TITLE
http is showing on website field even when https is added

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#2165]
**Describe the bug**
when you add a website field and input your url, on the edit field in frontend it shows https but after saving and viewing your profile it shows http

**To Reproduce**
1. create a Profile Field with Website field
2. In front end, edit your profile and add your website with https in url
    ex. https://www.mywebsite.com
3. Save and view Profile
4. See error, your website field, it shows http://www.mywebsite.com

**Expected behavior**
the http or https should be removed when a url is added on website field

**Screenshots**
https://prnt.sc/100sphj
https://prnt.sc/100spyi

**Support ticket links**
https://secure.helpscout.net/conversation/1430551109/126113

**Comment by marienel21** [comment]
Bug not reproducible on the latest version of the Platform and Theme.
