### ISSUE TITLE
issue with content text editor with shift-tab outdent bullets after editing forum content/reply

### ISSUE THREAD

**Issue by hercivalbuddyboss** [buddyboss/buddyboss-platform#2166]
**Describe the bug**
 issue when using bulleted list after editing content

**To Reproduce**
[https://vimeo.com/514509617/bca6abde66](https://vimeo.com/514509617/bca6abde66)

**Screenshots**
[https://vimeo.com/514509617/bca6abde66](https://vimeo.com/514509617/bca6abde66)

**Support ticket links**
[https://secure.helpscout.net/conversation/1429936697/125991](https://secure.helpscout.net/conversation/1429936697/125991)

**Comment by marienel21** [comment]
This bug is no longer visible on the current version of the platform. Tested on demo.
