### ISSUE TITLE
BuddyPanel: a menu that stick to bottom disappear when selecting third header

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#2169]
**Describe the bug**
 When activating the third header in theme options, the bp-menu-item-at-bottom is disappeared

**To Reproduce**
1. Go to Theme Options 
2. On header tab, select the third header style
3. Add new menu in buddypanel and make it stick to bottom.
4. Visit the homepage and check the created menu that stick at the bottom of the buddypanel.

**Expected behavior**
The menu that stick at the bottom should appear when selecting the third header.

**Screenshots**
https://www.loom.com/share/b1025c4acf324f8eb06b0a857635f03c

**Support ticket links**
Related Ticket: https://secure.helpscout.net/conversation/1431013009/126189/

**Comment by jrbuddyboss** [comment]
Related ticket: https://secure.helpscout.net/conversation/1499075569/139662

**Comment by amincdev** [comment]
This issue is related to the theme, Created a new issue there and closing this one:
https://github.com/buddyboss/buddyboss-theme/issues/1427
