### ISSUE TITLE
HTML list in Paragraph field not rendered when used in Repeater Field

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#2173]
**Describe the bug**
When using Paragraph text field in Repeater Field, this does not render the HTML list

**To Reproduce**
1. Create a repeater field
2. add paragraph field
3. In frontend, edit profile and add `"<li>"` tags 

**Expected behavior**
Lists normally work when field set is not set to repeater, this must also work in repeater field set

**Screenshots**
http://somup.com/crn0bzD4z3

**Support ticket links**
https://secure.helpscout.net/conversation/1432898163/126511

**Comment by shashank-buddyboss** [comment]
@emmanoctaviano 

I have reproduced this issue with latest versions of theme, platform and WordPress, but I could not replicate the issue.

**Versions:**
- **Platform:** https://prnt.sc/1im5fia
- **Theme:** https://prnt.sc/1im5ke1
- **WordPress:** https://prnt.sc/1im5u2t

**_Video proof:_**
https://www.loom.com/share/6cfc848329234006bbe2f6a999f36459

**Comment by shashank-buddyboss** [comment]
Confirm with @emmanoctaviano , issue is working fine, so closing this issue.
