### ISSUE TITLE
Photos and images don't respect privacy "only me" and are accessible to anyone on the internet via direct link

### ISSUE THREAD

**Issue by ouch-digital** [buddyboss/buddyboss-platform#2177]
**Describe the bug**
Photos and images are accessible via direct link to their /wp-content/uploads/12/example.png links even when permissions are set to "only me". This represents a considerable security risk where site owners and users might think their images are private, but are accessible from the internet without permissions. Visitors can easily crawl these folders to access all private images on a Buddyboss site. Photos and images uploaded don't respect the permissions set by the user in the same way that documents do. 

**To Reproduce**
1. Go to profile feed or photos tab to upload a photo.
2. Click on upload a photo
3. Set the permissions of the photo to "only me"
4. Open the photo/image in Buddyboss. Right click to open the image in a new tab and copy the direct link for the image (https://example.com/wp-content/uploads/12/example.png)
5. Open a new private window in chrome/firefox where you are not logged into Buddyboss. Paste the URL for the private image. You will have access to the image.

**Expected behavior**
The expected behaviour is that the visitor will be denied access to the image in the same way that documents deny access.

**Support ticket links**
Support ticket #125624 first reported.

**Comment by mahedihasannoman** [comment]
Hi @ouch-digital , Please update the BuddyBoss Platform because in latest version we have restricted direct access to the media file link. So no one will able to view media files without proper authorization.
Thanks
