### ISSUE TITLE
The empty folder remains in the documents even if we delete the folder

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2178]
**Describe the bug**
The empty folder remains in the documents even if we delete the folder

**To Reproduce**
1. Go to Groups > Documents
2. Create a folder
3. Then delete the created folder
4. You'll notice the folder name gets deleted but an empty folder remains we cannot delete the empty folder.

**Expected behavior**
The folder should get deleted.

**Screenshots**
https://prnt.sc/10666qm

**Support ticket links**
https://secure.helpscout.net/conversation/1428962036/125811/

**Comment by shashank-buddyboss** [comment]
@harshadmane 

I have reproduce this issue on our DEMO site and its working fine.

Please review the following video > https://www.loom.com/share/0ff4e0f2755049bda55ebac58aa79395

If its working fine then please let me know so I can close the issue.

Thanks
