### ISSUE TITLE
Courses are not sorted alphabetically inside groups

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2179]
**Describe the bug**
Courses are not sorted alphabetically inside groups

**To Reproduce**
The courses were also not sorted alphabetically here: 
https://mindbodyfunctionalmedicine.com/members/cat/courses/

So I shared following snippet to client which solved the issue.

add_filter( 'bp_learndash_user_courses_atts', 'learndash_course_orderby_date', 10, 1 );

function learndash_course_orderby_date( $atts ) {
$atts['orderby'] = 'title';
$atts['order'] = 'ASC';
return $atts;
}

But the same code doesn't works for courses in groups here:
https://mindbodyfunctionalmedicine.com/groups/level-1-functional-medicine-certification/

Customer has already added the shortcode in Learndash courses to sort alphabetically but it doesn't work.

**Expected behavior**
Courses should sort alphabetically.

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1418750132/123940/

**Comment by surajkrsingh** [comment]
@harshadmane 
This is not a bug.

We tested this issue and found `bp_learndash_user_courses_atts` filter only works for user courses as its name denoted.

For the group courses, the learndash function `learndash_group_enrolled_courses` is used that doesn't take any argument for the attribute. So, it returns the courses as default order.

But you can use this filter 
`apply_filters( 'bp_ld_learndash_group_enrolled_courses', $courseIds, $group_id )` to re-arrange the course ids with some logic or you can override it.
