### ISSUE TITLE
Copy URL button not visible on the front side.

### ISSUE THREAD

**Issue by sumitbuddyboss** [buddyboss/buddyboss-platform#2181]
**Describe the bug**
Copy URL button not visible on the front side.

**To Reproduce**
1. Go to 'Learndash'
2. Create a new program
3. Add File block

**Expected behavior**
Copy URL button should be visible on the front side

**Issue video**
https://www.loom.com/share/9854328d5299436c8a7e3fff414c113d

Website URL:
https://bb-app-platform.flywheelsites.com/courses/sumit-supported-block-test-wp-editor/

**Comment by shashank-buddyboss** [comment]
Confirm with @sumitbuddyboss ,

The issue is not replicate with the latest versions of BB-theme, BB-Platform & WordPress. Please check the following issue.

**Video:** https://www.loom.com/share/c6ee036fa5454c26a4a658fd76baa1eb
