### ISSUE TITLE
Forum Import loading error

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2182]
**Describe the bug**
There is loading issue (as a Starting Conversion) while importing Forum under Buddyboss > Tools > Import  Forum section.

**To Reproduce**
1. Go to 'Buddyboss'
2. Click on 'Tools'
3. Then go to Import Forums and start importing
4. See error loading as "starting Conversation"

**Expected behavior**
While import Forum, it should not be loading as "Starting Conversion".

**Screenshots**
https://prnt.sc/10790wn

**Support ticket links**
https://secure.helpscout.net/conversation/1428997142/125820?folderId=4265312

**Comment by janakkaneriya007** [comment]
@shyamwp14 
I am not able to generate this issue on my side. Can you share steps to generate the issue?

**Comment by shyamwp14** [comment]
Now on the latest version of Buddyboss platform, we are able to import the forum.
