### ISSUE TITLE
Group URL doesn't work in email sent to admin

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2188]
**Describe the bug**
If a user wants to join a group, the group admin gets a notification by email. In this email the group name is linked to the group but this link doesn't work. 

The customer has translated ursing POEdit.

The {{{group.url}}} is not converted to actual url

**To Reproduce**
1. When a user joins a group an email is sent to admin
2. The groups url in the email is not working

**Expected behavior**
Should include the groups url

**Screenshots**
https://prnt.sc/109v090
https://prnt.sc/109v2d8

**Support ticket links**
https://secure.helpscout.net/conversation/1438475415/127810?folderId=4304220

**Jira issue** : [PROD-850]

[PROD-850]: https://buddyboss.atlassian.net/browse/PROD-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mahedihasannoman** [comment]
https://secure.helpscout.net/conversation/1480676067/135720?folderId=4314898
