### ISSUE TITLE
Reply in Group does not show in Timeline and all the group activity should be report in timeline

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2189]
**Is your feature request related to a problem? Please describe.**
The Reply in Group does not show in Timeline and all the group activity should be report in timeline

It will only post group forum posts or activity posts on the other user's feed if the two conditions hold:
1. The two users are connected. This is a bug because it ignores the setting :
Restrict the Activity Feed directory to only posts that are relevant to the logged-in member"
2. The group is public. This is a bug because both persons are members of the private group, they should see each other's forum posts and activity, not only when it is a public group.
Here is the video where I demonstrate these two bugs: https://www.loom.com/share/d6e0e68a10834ec6b937194491deba58?sharedAppSource=personal_library

**Describe the solution you'd like**
The Reply in Group should be show in Timeline  which  is not reported  in timeline and  Regarding the functionality of the group which is reporting group activity that we are register for which is not only reporting activity should be report in timeline.

**Issue/feature request Screenshot and Video url**
https://www.loom.com/share/ca156281001d4bbe8fdceaea903abf9c

https://www.loom.com/share/cff4723a97354f2b877643e0f2d1caf1
https://www.loom.com/share/d6e0e68a10834ec6b937194491deba58

**Support ticket links**
https://secure.helpscout.net/conversation/1439664018/128035?folderId=4265312

**Comment by elevatingcreativity** [comment]
Hello, I was the originator of the support ticket, and there are actually **three separate issues I've identified.** I believe it would be less confusing to have each one as a separate issue, rather than all in one. I will post the separate issues, and then I will come back to this issue and link them here.

**Comment by elevatingcreativity** [comment]
I have now posted the three separate issues, this one could be closed.

1. https://github.com/buddyboss/buddyboss-platform/issues/2191
2. https://github.com/buddyboss/buddyboss-platform/issues/2192
3. https://github.com/buddyboss/buddyboss-platform/issues/2193

Thank you
