### ISSUE TITLE
Profile type Members Hidden In The Group's Manage Members Page!

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#2190]
When the **"Hide all members of this type from Members Directory"** option is enabled in the profile type, users of this type will not show it in the group's manage members page (XXXX.com/groups/XXXX/admin/manage-members/)!

**Comment by marienel21** [comment]
I can't reproduce this bug on the latest version of the Platform.

**Comment by mailalaki** [comment]
> 
> 
> I can't reproduce this bug on the latest version of the Platform.

This only happens when the user's role is **MODERATOR** or **ADMIN** in the group.
See here (I did not remember reporting it once before):
https://github.com/buddyboss/buddyboss-platform/issues/2470

**Comment by milanhirapra** [comment]
Similar issue: https://github.com/buddyboss/buddyboss-platform/issues/2470
