### ISSUE TITLE
@mention in comment never shows in activity feed

### ISSUE THREAD

**Issue by elevatingcreativity** [buddyboss/buddyboss-platform#2191]
**Describe the bug**
When an @mention is made of a user in a top-level activity post in a group, the post is shown in the user's activity feed (expected).
When an @mention is made of a user in a comment to an activity post in a group, the comment is never shown in the user's activity feed (bug).

See this video for more: https://www.loom.com/share/1e65960bfb1f42109524b83646d2429b

**To Reproduce**
See video: https://www.loom.com/share/1e65960bfb1f42109524b83646d2429b

**Expected behavior**
The user's activity feed should show all @mentions in groups it is subscribed to, regardless of whether top level or comment

**Screenshots**
https://www.loom.com/share/1e65960bfb1f42109524b83646d2429b

**Support ticket links**
https://secure.helpscout.net/conversation/1439664018/128035?folderId=4265312

Note, this is one of three separate issues I encountered with activity feed posts, which were posted in https://github.com/buddyboss/buddyboss-platform/issues/2189

To reduce confusion, I am now posting these separately and individually.

**Comment by marienel21** [comment]
I can't reproduce this bug on the latest version of the Platform. Tested on demo.

**Comment by kent-carlo** [comment]
This is intended. Activity is only visible in user's end when you mention that user in activity. It won't be visible when you mention the user only in comment.
