### ISSUE TITLE
BuddyBoss duplicate component page notice show a broken link

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2201]
**Describe the bug**
If I add duplicate page for BuddyBoss component page from BuddyBoss > Pages then the following message show at the top: (Each BuddyBoss Component needs its own WordPress page. The following WordPress Pages have more than one component associated with them: . Repair)
where Repair text is linked with a broken/invalid link.

Please refer to this screenshot: [https://prnt.sc/10bgxlh](https://prnt.sc/10bgxlh)

**To Reproduce**
Please assign some duplicate page for BuddyBoss component pages then you will find the message with broken link in any other admin pages.

**Support ticket links**
https://secure.helpscout.net/conversation/1441590842/128464?folderId=4314898

**Jira issue** : [PROD-849]

[PROD-849]: https://buddyboss.atlassian.net/browse/PROD-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by angelic-joyce** [comment]
https://secure.helpscout.net/conversation/1643344040/166039/
