### ISSUE TITLE
bp activity bug in BB Theme 1.6.4.1, Platform, or Wall

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2206]
**Describe the bug**
Whenever users comments on wall nothing happens

**To Reproduce**
Comments from customer:

look at this JavaScript file from BuddyBoss platform: buddyboss-platform/bp-templates/bp-nouveau/js/buddypress-activity.js Line 1726. var activity_data = target.closest( '.activity-item' ).data( 'bp-activity' ); It is looking for the closest .activity-item and then the data attribute bp-activity. Now look at the HTML for a bp activity inside a group:

There is no bp-activity data field so whenever a user tries to comment, nothing happens. I believe the culprit lies in this BuddyBoss Wall file: buddyboss-wall/templates/bp-nouveau/activity/entry.php Line 13 shows that there is no data-bp-activity attribute. Is it possible that BuddyBoss Wall is no longer compatible with BuddyBoss platform?

**Expected behavior**
User should be able to add comments

**Screenshots**
https://prnt.sc/10ck7z9

**Support ticket links**
https://secure.helpscout.net/conversation/1443025567/128746/

**Comment by mahedihasannoman** [comment]
BuddyBoss Wall plugin is not needed when BuddyBoss Platform is installed because it is an in-built component in the BuddyBoss Platform. Ref: https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddyboss-wall/
