### ISSUE TITLE
After updating to version 1.5.7 group members can no longer upload photos on group activity

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2210]
**To Reproduce**
1. Create a group.
2. Set "**Who can manage photos in this group?**" to "**Organizers**"
3. Add some members and organizers
4. log in as a member and visit the group you just created
5. Try to post an activity and notice there is no way to attach a photo

**Expected behavior**
It was working for earlier versions like 1.5.6

**Screenshots**
![2](https://user-images.githubusercontent.com/58522498/110011274-31257880-7d5a-11eb-82c3-56cf0e0d4c5f.jpg)
![1](https://user-images.githubusercontent.com/58522498/110011282-32ef3c00-7d5a-11eb-882c-549cb219437f.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1440552534/128258

**Comment by marienel21** [comment]
I can't reproduce this bug on the latest version of the Platform.
