### ISSUE TITLE
 Who's online widget is showing incorrect count of users.

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2218]
**Describe the bug**
The widget Who's Online is not showing the correct count of users. It is actually showings users as online when they are not online.

**To Reproduce**
1. Go to 'Wp-admin Dashboard'
2. Click on 'Appearance' then go to Widget area
3. Drag and Drop "(BB) Who's Online" widget
4. See error online count is not showing

**Expected behavior**
Who's online widget showing correct count of users.

**Screenshots**
https://prnt.sc/10fwh3n
https://prnt.sc/10fwibl

**Support ticket links**
https://secure.helpscout.net/conversation/1436156686/127247?folderId=4265312

**Comment by manishpatolia** [comment]
@shyamwp14  
I have checked with the latest pull and I seem this is working fine for me.

User 1:
https://prnt.sc/13e879r

Without Login :
https://prnt.sc/13e88fb

Let me know there have any specific steps or scenarios.

**Comment by shyamwp14** [comment]
Ok, now you can close this issue. I will inform to the customer that to update latest version of Buddyboss platform. so it will work fine.

**Comment by manishpatolia** [comment]
Okay sure
