### ISSUE TITLE
Buddyboss Social group can not delete

### ISSUE THREAD

**Issue by sumitbuddyboss** [buddyboss/buddyboss-platform#2221]
**Describe the bug**
IBuddyboss Social group can not delete when we delete from learndash.

**To Reproduce**
1)Sync with learndash
2)Create group in learndash
3)Delete group In learndash
4)Check the group in Buddyboss backend and See an error

**Expected behavior**
Should be deleted from learndash side

**Screenshots**
https://www.loom.com/share/0da9b854d8974a27ad8003b8a2ff4d89

**Comment by asaquzzamanbb** [comment]
@sumitbuddyboss 
You are just trashing the LD Group, not deleted permanently. It will work fine if you delete permanently the LD Group.

**Comment by sumitbuddyboss** [comment]
Hello @asaquzzamanbb 

Thank you for the comment.

@sourabhmatolia Need your inputs here.
