### ISSUE TITLE
Profile field names not escaped, backslashes added

### ISSUE THREAD

**Issue by lumpysimon** [buddyboss/buddyboss-platform#2236]
If the `name` field of a profile field has a character such as an apostrophe in it, a backslash is added. On each subsequent save, more backslashes are added.

On the back-end:
<img width="320" alt="Screenshot 2021-03-11 at 12 05 58" src="https://user-images.githubusercontent.com/625372/110785058-63efd500-8262-11eb-9c40-b6066852ea15.png">

<img width="543" alt="Screenshot 2021-03-11 at 12 09 08" src="https://user-images.githubusercontent.com/625372/110785254-a44f5300-8262-11eb-9c8c-2ea127374f87.png">

On the front-end:

<img width="384" alt="Screenshot 2021-03-11 at 12 12 06" src="https://user-images.githubusercontent.com/625372/110785610-0b6d0780-8263-11eb-877b-1e752c359bb7.png">

**Comment by harshalQA** [comment]
Fixed: Retested on site url: https://bb-app-platform.flywheelsites.com/wp-admin/admin.php?page=bp-profile-setup&mode=edit_field&group_id=1&field_id=14395#tabs-1

Video: https://www.loom.com/share/2c961e49fac646ad829d23a038e6c5a8

1] Dashboard screenshot: https://www.awesomescreenshot.com/image/13335872?key=897ef7f11523fd36729992d990c3ab37

2] App screenshot: https://www.awesomescreenshot.com/image/13335935?key=6a9851955320d7f21b293227acd399fc

**Comment by harshalQA** [comment]
Fixed: Retested on site url: https://bb-app-platform.flywheelsites.com/wp-admin/

Video:
https://vimeo.com/609688163/ed3343c851

**Comment by lumpysimon** [comment]
Thank you :)
