### ISSUE TITLE
getting an error on jquery.atwho.min.js in console.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#2239]
**Describe the bug**
When trying to add a forum discussion in the Korean language, getting an error in the console. Please refer to the screenshot.
https://prnt.sc/10jf8a6
wp-content/plugins/buddyboss-platform/bp-core/js/vendor/jquery.atwho.min.js?ver=1.5.7.3
It works fine with English.

**To Reproduce**
https://screencast-o-matic.com/watch/crelhBVcwFU

**Support ticket links**
https://secure.helpscout.net/conversation/1450341668/130080?folderId=3701248

**Comment by futureyoon** [comment]
this issue has come back.... Pleae help take a look. Thx

**Comment by abbymontano** [comment]
the issue came back, please check:  https://secure.helpscout.net/conversation/1711853876/176350/
