### ISSUE TITLE
Forums > Select whole page content

### ISSUE THREAD

**Issue by sumitbuddyboss** [buddyboss/buddyboss-platform#2240]
**Describe the bug**
When we upload an Image or Document at that time it select all the page content.

**To Reproduce**
1. Goto forum discussion
2. Upload the image or document
3. Post the content

Browser specification:
Windows 10
Chrome Version 89.0.4389.82 (64bit)

**Screenshots**
https://www.loom.com/share/95de607d875641eca00f769e8ecd6771

**Comment by krunal-buddyboss** [comment]
I am going to close this issue as this need to be fix on theme https://github.com/buddyboss/buddyboss-theme/issues/1537

@sourabhmatolia  @sumitbuddyboss
