### ISSUE TITLE
Events: past events not showing in search results

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2243]
**Describe the bug**
Past events ob search does not showing in search results on demo site

**To Reproduce**
1. Past events are not showing in search results: https://snipboard.io/tCrz5k.jpg Already tested on sandbox site

**Expected behavior**
Events should show 

**Screenshots**
https://snipboard.io/tCrz5k.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1453031290/130543/
https://secure.helpscout.net/conversation/1423881407/124835

**Jira issue** : [PROD-844]

[PROD-844]: https://buddyboss.atlassian.net/browse/PROD-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sourabhmatolia** [comment]
@ngolwalkar @asaquzzamanbb @shyamwp14 

Cross checked the issue and I can replicate/reproduce the issue easily. 

Check Video:
https://www.loom.com/share/734d8f36f68a4f918e4ddf28665827f1

Everybody, please check workflow thoroughly before flagging issue as "can't reproduce". 

Thnx

**Comment by fabiomail** [comment]
@sourabhmatolia thank you for confirming that the bug actually exists.

**Comment by shyamwp14** [comment]
It seems that for some reason the search is only working for some of my forums, but not all. As an example, I have some forums nested in the coaching page, but the big forum is nested in the community page:
https://prnt.sc/1332ie4

When I search for the word in red, for example, nothing comes up:
https://prnt.sc/1332j0c

I can only get the forums in the coaching tab to show up, but not in the community tab.
Here are some of the search settings:
https://prnt.sc/1332jsi

https://secure.helpscout.net/conversation/1426745949/125386?folderId=4265312

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1606757196/159692
