### ISSUE TITLE
User response is missing on login screen - similar to previously fixed issue #1899

### ISSUE THREAD

**Issue by hum-bug** [buddyboss/buddyboss-platform#2249]
Seems to be same issue as this previously fixed issue but on login form:
#1899 

[](https://1drv.ms/u/s!AtgoA-n7npsdjNNgG6CSM9gbRq5VoA?e=4BDKlx )

50% of time seems to occur. Seems more likely when trying to login to dashboard (i.e. visited wp-admin url and redirected to login). 

Using buddyboss platform Version 1.5.7.3  and theme.
WP 5.6.2
PHP Version: | 7.3.14

Plugin: 

reCaptcha Pro by BestWebSoft
Version 1.60

Google Recapture v3

No errors in debug log with debug mode enabled.

**Comment by milanhirapra** [comment]
I am unable to reproduce in the latest BuddyBoss Platform.
Here is the video: https://vimeo.com/606532848/10a8b61cc3

**Comment by imehedidev** [comment]
Not replicable with the latest version of BuddyBoss Platform
