### ISSUE TITLE
Safari Browser: Course Sidebar Scrolling Glitch

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#2251]
**Describe the bug**
Sidebar scrolling inside course page causing some glitch but when resizing the browser width, it fixes the issue.

**To Reproduce**
1. Go to any course page that composes long content.
2. Scroll down to page until you reach the end.
3. After, point the cursor on course topic sidebar and try scrolling up and down.
4. See error.

**Expected behavior**
Scrolling the course topic sidebar should be smooth. (Tried on both Chrome and Firefox but not encountered)

**Screenshots**
Customer Site:
https://drive.google.com/file/d/1eQhu7hLovPVFxTkNS8rXNvuMvf3yDV8O/view

Demo Site: 
https://drive.google.com/file/d/1u2htPcJw6foG6ouO1rnQbcMNV5RzLV6W/view

**Support ticket links**
https://secure.helpscout.net/conversation/1454474588/130775

**Comment by marienel21** [comment]
Bug can't be replicated on the latest version of Platform and Theme. Tested on demo.
