### ISSUE TITLE
Forum Comments not merged with Feed Replies

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2252]
**Describe the bug**
The issue where feed replies are not showing up in forums as replies.

**To Reproduce**
create test discussion/blog post comment through activity feed, it should also show as a reply in forum discussion page or blog page

**Expected behavior**
Forum Comments merged with Feed Replies

**Screenshots**
https://www.buddyboss.com/resources/docs/components/activity/posts-in-activity-feeds/
![image](https://user-images.githubusercontent.com/75772088/111742774-b3f81880-88ae-11eb-9264-ad807ea72ac3.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1455321259/130927?folderId=4265312

**Comment by marienel21** [comment]
On the latest version of the Platform, the comment button is hidden/removed on feed (for forum replies) 
![image](https://user-images.githubusercontent.com/77659570/127021566-42ed007b-deed-4ffb-9312-ef7fe6a1e372.png)
