### ISSUE TITLE
HTTP & HTTPS is not allowed in News Feed with Non admin role

### ISSUE THREAD

**Issue by anand-bb** [buddyboss/buddyboss-platform#2255]
**Describe the bug**
When a user without an admin role tries to paste the URL in the news feed, it gets the error.

**To Reproduce**
1. Create a user with any non-admin role
2. login with that user then Copy any link, maybe YouTube.
3. Paste it on the news feed
4. See an error 
5, If we don't add HTTP or HTTPS then it successfully gets posted.

**Expected behavior**
It should be posted without any problem.

**Screenshots**
https://drive.google.com/file/d/1Q7rgFtOlS6vcrl8BXh_1TaPXviM1w3bH/view

**Support ticket links**
https://secure.helpscout.net/conversation/1457968649/131424/

**Comment by marienel21** [comment]
Can't replicate with the latest version of the Platform.
