### ISSUE TITLE
Importing PHBB forum is not working

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2264]
**Describe the bug**
When importing a PHBB forum the platform's import tool always fails. But when using the bbPress it works.

**To Reproduce**
1. Go to BuddyBoss > Tools > import Forums
2. Select PHBB in "Select Platform", fill up the rest
3. Try to import and notice the error.

**Expected behavior**
It should work just like bbPress import tool.

**Other note**
The customer suggested this script that we review to help fix this issue in the platform https://pastebin.com/FpWsxsUG.

**Support ticket links**
https://secure.helpscout.net/conversation/1459569245/131825

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1578838016/154845

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1595328888/157662

When importing a Xenforo forum the platform's import tool always loading "Starting Conversion"

Screenshot:
https://prnt.sc/1of7c06
https://prnt.sc/1of7ma8

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1578838016/154845

**Comment by shyamgudadhe** [comment]
https://secure.helpscout.net/conversation/1633965013/164551/
