### ISSUE TITLE
Moving another photo to same album not allowed and move button disabled

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2277]
**Describe the bug**
Move button is disabled after moving first  photo to an album even for another second image.
**To Reproduce**

- Steps to reproduce the behavior:
- Create a new album say "Album 1"
- Goto photos tab from profile page
- Click More action ( "..." ) at right top corner of the photo and click on Move and select the album "Album 1"
- Similarly Click More action ( "..." ) at right top corner of the **another photo** and click on Move and select the album "Album 1" the Move button will be disabled for second photo also.
- Second photo can be moved to same album "Album 1" after a refresh

**Expected behavior**
As Second photo is not in the album, it should be allowed to move

**Screenshots**
https://prnt.sc/10vsax8

**Support ticket links**
https://secure.helpscout.net/conversation/1465394619/132887

**Comment by bb-yudhisthir** [comment]
reference video https://www.loom.com/share/7df317fd9b084023ac8ec29d34db6e91

**Comment by amincdev** [comment]
@bb-yudhisthir I tried to replicate this issue in our demo server, But it's working fine. Attaching a video for your review. Please test it again and let me know if you are facing this issue.

https://www.loom.com/share/55ab08ca315a40369be82a2d04797ac9
