### ISSUE TITLE
BuddyPress vulnerabilities

### ISSUE THREAD

**Issue by lumpysimon** [buddyboss/buddyboss-platform#2278]
I see that Buddypress 7.2.1 addresses [seven vulnerabilities](https://codex.buddypress.org/releases/version-7-2-1/), including a privilege escalation vulnerabillity.

Do these vulnerabilities also exist in BuddyBoss, and if so, when will a fix be released?

Do you keep track of vulnerabilities found in BuddyPress and port the fixes across to BuddyBoss?

**Comment by sourabhmatolia** [comment]
**UPDATE**

Issue fix and merged here:
https://github.com/buddyboss/buddyboss-platform-api/pull/240

**Comment by sourabhmatolia** [comment]
@lumpysimon 

Issue mentioned above is released in BuddyBoss Platform v.1.6.4

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-6-4/

Please update the plugin to see the latest changes.

Thank you.
