### ISSUE TITLE
The email template for discussion reply does not include line breaks and text formatting

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2283]
**To Reproduce**
1. Go to any forum discussion.
2. Make a reply.
3. Check the email notification received by the subscriber of that discussion
4. Notice the issue

**Screenshots**
![ss](https://user-images.githubusercontent.com/58522498/112735302-fc39c980-8f85-11eb-8cfb-e2ad9d3fcc20.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1465427121/132893

**Comment by bb-yudhisthir** [comment]
Same issue 
![image](https://user-images.githubusercontent.com/80085922/130422502-3805d7fc-f061-40c5-a051-17c53d2618a0.png)
there is no space being entered between paragraphs which means if one paragraph ends in a hyperlink, it makes the hyperlink appear incorrectly.

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1604221468/159266/
