### ISSUE TITLE
Display link preview issue in messages

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2284]
**Describe the bug**
We noticed a problem with showing links in private messages. When sometime we put the link in private message, the link preview will display ,but sometime it doesn't work.

**To Reproduce**
1. Go to 'Member profile.'
2. Click on Member profile Message link
3. Send some link in private message to other member
4. See error, link preview will not display

**Expected behavior**
It should be display link preview every time, when any member send the link via private message
**Screenshots**
https://prnt.sc/10ylng8

**Support ticket links**
https://secure.helpscout.net/conversation/1459147118/131732?folderId=4265312

**Comment by marienel21** [comment]
Link Preview is not working on messages. Tested on demo

**Comment by mahedihasannoman** [comment]
Hi @shyamwp14 , Link preview feature is only available in Activity post currently. So link preview will not show in private messages.
