### ISSUE TITLE
BB REST API - Group Detail Endpoint: throwing a fatal error.

### ISSUE THREAD

**Issue by manishpatolia** [buddyboss/buddyboss-platform#2305]
**Describe the bug**
When the group is hidden and the user is not part of the groups and trying to fetch the details that time getting the fatal error.

**To Reproduce**
1. Create a new hidden group
2. try to fetch detail with join this group
4. See an error

**Screenshots**

https://prnt.sc/114x5ks

**Expected behavior**
It should not throw the fatal error

**Support ticket links**
None

**Comment by mahedihasannoman** [comment]
Issue moved to Platform API: https://github.com/buddyboss/buddyboss-platform-api/issues/321
