### ISSUE TITLE
Subforum/Forum discussions are not showing in network search

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2306]
**Describe the bug**
Subforum discussions are not showing up in network search as well as in forum instant search result. For more clarification please refer to my video: [https://www.loom.com/share/611b8cbdcaad491b86c7441036157fee ](https://www.loom.com/share/611b8cbdcaad491b86c7441036157fee )

**Support ticket links**
[https://secure.helpscout.net/conversation/1473710819/134568?folderId=4314898](https://secure.helpscout.net/conversation/1473710819/134568?folderId=4314898)

**Comment by buntybuddyboss** [comment]
Similar issue reported by a client. 

Here is the video: https://www.loom.com/share/a51b07a1fa104e408df65e7f17c9a67d

**Comment by mahedihasannoman** [comment]
https://secure.helpscout.net/conversation/1512616690/142132/
