### ISSUE TITLE
Creating a discussion within a hidden group redirects to the homepage

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2307]
**Describe the bug**
When a non-admin user creates a discussion within a hidden group, it redirects to the homepage. This only happens in the BuddyBoss Platform v1.5.8

**To Reproduce**
1. Create a group and set the privacy to hidden
2. Associate a forum
3. Add a non-admin user to the group as a member
4. Login/View as a group member of the hidden group you just created
5. Try to create a discussion
6. Notice the issue

**Screencast**
https://cutt.ly/ZcT3Jdv

**Support ticket links**
https://secure.helpscout.net/conversation/1473092712/134416
https://secure.helpscout.net/conversation/1472050740/134217
https://secure.helpscout.net/conversation/1493809878/138691
https://secure.helpscout.net/conversation/1506226339/140993/

**Comment by grahamhoffman** [comment]
https://secure.helpscout.net/conversation/1506226339/140993/
