### ISSUE TITLE
Authentication with notification Restful API  issue

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2308]
**Describe the bug**
Got a 401 response when calling the create notification API , even we used basic auth login details in Postman tool.

**To Reproduce**
1. Here is our Buddyboss platform Notification Rest API 
https://www.buddyboss.com/resources/api/#api-Notifications-CreateBBNotifications
2. Go to our Community demo site.'
https://demos.buddyboss.com/online-communities/wp-json/buddyboss/v1/notifications
3. See error.

**Expected behavior**
Authentication with notification Restful API should be work.

Also for Buddyboss notifications rest APIs  need to pass 'X-WP-Nonce' header.

Feature request : Kindly please API also allow us to comment in groups? We haven't seen this function yet in the overview, however it would be great for us to enable this as well.

**Screenshots**
https://prnt.sc/115e8a2
https://demos.buddyboss.com/online-communities/wp-json/buddyboss/v1/notifications

**Support ticket links**
https://secure.helpscout.net/conversation/1460566506/132063?folderId=4265312

**Comment by sourabhmatolia** [comment]
@shyamwp14 

This is not a bug.
WordPress doesn’t support basic authentication default.
We are also not supporting JWT authentication also on our DEMO setup.
Everything should work fine on other WP setups with JWT authentication.
You can see we have notifications and everything working fine already using existing APIs.

@KartikSuthar Please elaborate if you want to.

Thanks.

**Comment by KartikSuthar** [comment]
@shyamwp14 

If they need to use basic authentication, they can use the basic authentication handler into their WP setup.
they can use plugin eg: WP Basic Authentication to enable basic authentication into the site. 

In our demo, we are not allowing users to authenticate via rest.
