### ISSUE TITLE
Open sub-groupforum: whole grouppage-surrounding disapears

### ISSUE THREAD

**Issue by brave-sites** [buddyboss/buddyboss-platform#2309]
**Is your feature request related to a problem? Please describe**
My groups are pretty big. I don’t want them to have ‘one big forum’ with all kind of discussions. That would become a big mess. So, I set the type of my groupforum to ‘category’ instead of ‘forum’, so nobody can add a discussion here and made 7 child-forums with the groupforum/category as parent. Looks okay on the group-page. But, when I click on one on the child-forums, the grouppage-surrounding disapears and there opens a new page where you can only see the forum. Grouppage is gone, no breadcrumbs, no 'go back to your group-button'. Same with the discussions on this child-forum. Is it possible to open/integrate the sub-forums and their discussions IN the grouppage, like normally is already like this when the discussions are in the parent-forum? 

**To Reproduce**
1. Make a groups
2. Create a group forum and set this forum to 'category' instead of forum
3. Make a few child-forums for this 'groupforum/category'
4. Open the grouppage --> forums
5. Click on a subforum + open a discussion

This 'll open in a new page, the grouppage surrounding disapears, but when you don't use any subforums (only the main parentforum) and you make a discussion, this discussion 'll open IN the grouppage. I want that subforums + subforum discussions behave the same.

**Describe the solution you'd like**
When you follow the steps above, the subforum + subforum discussion 'll open in a new page, the grouppage surrounding disapears. But when you don't use any subforums (only the main parentforum) and you make a discussion, this discussion 'll open IN the grouppage. I want that subforums + subforum discussions behave the same and open IN the grouppage.

**Screenshots**
![1](https://user-images.githubusercontent.com/7854158/113710350-db8b1580-96e3-11eb-877d-aa75d467524b.png)
![2](https://user-images.githubusercontent.com/7854158/113710355-dcbc4280-96e3-11eb-84f8-20a47b8d019b.png)
![3](https://user-images.githubusercontent.com/7854158/113710357-dcbc4280-96e3-11eb-89e8-b8e02a2e43f6.png)
![4](https://user-images.githubusercontent.com/7854158/113710343-da59e880-96e3-11eb-9ecd-70145342675a.png)

**Support ticket links**
Ticket number: #127349

**Comment by biguenique** [comment]
You could work your way around (in the meantime) by creating and linking _subgroups_ with your _subforums_.

**Comment by mikejyoung** [comment]
Hi @brave-sites

Thanks for submitting this idea to the public roadmap.

We are currently scoping improvements to discussion forums and this feedback is very helpful. When we are further into developing the improvements, we will add it to the public roadmap.  

I'm closing this issue here as part of our efforts to keep our GitHub repository focused on work that is ready for development.

Mike
BuddyBoss Product Manager
