### ISSUE TITLE
Creating new Forum Topic in Hidden Group fails and redirect to homepage

### ISSUE THREAD

**Issue by hercivalbuddyboss** [buddyboss/buddyboss-platform#2310]
**Steps to Reproduce:** 
[https://drive.google.com/file/d/1O6OvnCrm3E12c1fqRlG3HOuy5kIFPliE/view](https://drive.google.com/file/d/1O6OvnCrm3E12c1fqRlG3HOuy5kIFPliE/view)

**Supporting Tickets:**
[https://secure.helpscout.net/conversation/1472050740/134217](https://secure.helpscout.net/conversation/1472050740/134217)

**Comment by hercivalbuddyboss** [comment]
Another Ticket for this issue: [https://secure.helpscout.net/conversation/1488166203/137490](https://secure.helpscout.net/conversation/1488166203/137490)
Replicate on our demo: [https://vimeo.com/538591434/a2a9895b10](https://vimeo.com/538591434/a2a9895b10)

**Comment by hercivalbuddyboss** [comment]
supporting ticket: [https://secure.helpscout.net/conversation/1489432964/137815](https://secure.helpscout.net/conversation/1489432964/137815)

**Comment by samthenetwork** [comment]
After almost 3 weeks this bug is not fixed.  OUR COMMUNITY IS NON FUNCTIONAL.  We have half of our groups with members unable to post any new discussions rendering our community site useless.  We have hidden, private and public groups all effected.  Support does not reply on the weekends even for urgent issues like our community to being functional.

**Comment by samthenetwork** [comment]
​Here it is reproduced exactly on your sandbox site.  https://www.dropbox.com/t/FgCs9bsu18WtLsov

Starting new discussions is the entire point of a community site?  Why has this not been marked as critical and fixed?

**Comment by sourabhmatolia** [comment]
@samthenetwork

Issue mentioned above is released in BuddyBoss Platform v1.5.9

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-9/

Please update the plugin to see the latest changes.

Thank you.
