### ISSUE TITLE
BuddyBoss menus is not showing in the Appearance->Menus in multisite

### ISSUE THREAD

**Issue by anand-bb** [buddyboss/buddyboss-platform#2319]
**Describe the bug**
When we do the network activate then BuddyBoss menus do not display in the Appearance->Menus for subsites.

**To Reproduce**
1. Install the BuddyBoss platform in multisite.
2. Do Network Activate
3. Go to Appearance->Menus
4. BuddyBoss menus do not display.

**Expected behavior**
The BuddyBoss menus should be displayed on the subsites as well.

**Screenshots**
https://nimb.ws/Ty9o7d

**Support ticket links**
https://secure.helpscout.net/conversation/1473123882/134426?folderId=4312419

**Comment by bb-yudhisthir** [comment]
Default behavior when the Buddyboss is Network Enabled. Duplicate concern mentioned in #1037
Closing this GitHub issue

**Comment by Pagan-Idel** [comment]
@bb-yudhisthir Default behavior breaks us. How are we expected to build a BuddyPanel menu without BuddyBoss menu items?
