### ISSUE TITLE
WP Admin Bar should hidden when user is a "subscriber" only

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#2329]
**Describe the bug**
When a user register and role is set as a subscriber, the WP Admin Toolbar should not be visible.

**To Reproduce**
1. Go to Users
2. Change any user role to subscriber.
3. Go to incognito and login as this user. (don't use the "view as" option https://prnt.sc/11aulxv instead use the login page)
4. The WP Admin Bar should be hidden.

**Expected behavior**
When a user register and role is set as a subscriber, the WP Admin Bar should be hidden.

**Screenshots**
Set role:
https://prnt.sc/11aucz1
Result:
https://prnt.sc/11aubkr

**Support ticket links**
https://secure.helpscout.net/conversation/1471675825/134155

**Comment by shashank-buddyboss** [comment]
@jrbuddyboss 

We have Buddyboss Platform settings to manage the Admin Bar > https://prnt.sc/1g5eq96.

Please review the following video and confirm here so I can close this issue.

**Video:** https://www.loom.com/share/ebcd7ca1b58743f7a794562fc4ac50c9

Thanks.

**Comment by shashank-buddyboss** [comment]
I have confirmed with @jrbuddyboss , its working fine so I am closing this issue.
