### ISSUE TITLE
Main Forum Shows as Text After New Install

### ISSUE THREAD

**Issue by deborah86** [buddyboss/buddyboss-platform#2334]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

The main forum shows text instead of showing the actual forums.

**To Reproduce**

1. Install the BuddyBoss Plugin
2. Go to BuddyBoss > Pages
3. Click to button to create a new Forums page

Then try

1. Delete the created forums page
2. Create a new page under WordPress pages
3. Name the page and URL forums

**Expected behavior**

The new forums page to show the actual forums rather than text.

**Screenshots**

![image](https://user-images.githubusercontent.com/12677420/114740504-c1ae8b80-9cfe-11eb-80b1-37250f9a250f.png)
[https://lazyjack.blog/forums/](https://lazyjack.blog/forums/
)

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by deborah86** [comment]
Is there an update for this issue?

**Comment by deborah86** [comment]
According to WordPress core, this is the issue:

_I can replicate what you are experiencing, with that information in hand, but I don't thinks this is something that a theme should have to solve.
A lot of plugins could be experiencing issues like this (you already mentioned two), so this is like opening a can of worms if the theme should account for all plugins, instead the plugins them selves can be smart about this.
A plugin could either add specific Twenty Twenty compatibility code (as an example, WooCommerce does this, although not for this specific issue, they have a folder full of theme-specific modifications), for example by checking if the theme option to show summaries has been chosen, and changing the output via the the_excerpt conditionally.
Or they could outright filter the the_excerpt filter always, if a plugin relies on markup to be displayed on a site, to make sure their content is added correctly across themes without being specific to Twenty Twenty._

[WordPress Core Ticket](https://core.trac.wordpress.org/ticket/53147#comment:16)

**Comment by kent-carlo** [comment]
@deborah86 I just tested this issue on latest update. What happens now is that if you delete the forums page, it will be unassigned in Buddyboss > pages. So, this issue can't be replicated anymore. Here's my record when I was testing: https://www.loom.com/share/6f20ff57946d4eb5a51b2673d45e80da
