### ISSUE TITLE
"User joined message" flooding the group message thread

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2337]
**Describe the bug**
After receiving group messages from any group organiser, members of that group subsequently see ongoing messages of who's joining the group from within that group chat.

This is pretty much similar issue: [https://github.com/buddyboss/buddyboss-platform/issues/717 ](https://github.com/buddyboss/buddyboss-platform/issues/717 )

**To Reproduce**

1. Create a group message, send To All Group members, use Group Thread, not Private Reply (BCC)
2. Then make a new user and join this group.
3 New user joined group, message is shown in the group thread, triggering notification to all existing members

**Screenshots**
https://i.imgur.com/bFulifV.png

**Support ticket links**
[https://secure.helpscout.net/conversation/1483685993/136324?folderId=3510499](https://secure.helpscout.net/conversation/1483685993/136324?folderId=3510499)

**Jira issue** : [PROD-831]

[PROD-831]: https://buddyboss.atlassian.net/browse/PROD-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bb-yudhisthir** [comment]
same issue Joined/Left messages https://secure.helpscout.net/conversation/1465267617/132863/

**Comment by patriciaadr** [comment]
same issue is happening in this ticket https://secure.helpscout.net/conversation/1511277492/141868

**Comment by dericksolis** [comment]
the same issue is happening in this ticket https://secure.helpscout.net/conversation/1553118576/149213/

**Comment by patriciaadr** [comment]
same issue in this ticket: https://secure.helpscout.net/conversation/1559694044/150515/

**Comment by hercivalbuddyboss** [comment]
https://secure.helpscout.net/conversation/1570717482/153227

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1572070063/153508/

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1581700439/155359/

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1598071315/158173/

**Comment by sourabhmatolia** [comment]
**UPDATE**

Based on the discussion internally, we will group "joined and left" notification messages in Group Thread to something like:
`Userone, Usertwo and 3 others joined the group.`

Thanks

cc: @mikejyoung

**Comment by sourabhmatolia** [comment]
UPDATE here: https://github.com/buddyboss/buddyboss-platform/pull/2721#issuecomment-908109748

**Comment by imehedidev** [comment]
https://github.com/buddyboss/buddyboss-platform/issues/2337

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1521943777/143805

**Comment by japshem** [comment]
https://secure.helpscout.net/conversation/1704190187/174936?folderId=4355037

**Comment by abbymontano** [comment]
https://secure.helpscout.net/conversation/1727447562/178704/
