### ISSUE TITLE
BuddyBoss Forum conflicts with Elementor. Parent forum is not getting saved.

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2340]
**Describe the bug**
If you go and create a forum and assign it to a parent forum from Forum Attributes metabox then parent forum is not getting saved. The issue is happening for the field name "parent_id" is duplicate in forum edit page when elementor is active and Forums post type is checked from Elementor settings. Please refer to my video for more information: [https://www.loom.com/share/a628f09b6a2349578b6892d744ae5f04](https://www.loom.com/share/a628f09b6a2349578b6892d744ae5f04)

**To Reproduce**
1. Please install and activate the classic editor plugin and elementor plugin.
2. Then refer to my video to reproduce this issue

**Support ticket links**
[https://secure.helpscout.net/conversation/1484718068/136551?folderId=3510499](https://secure.helpscout.net/conversation/1484718068/136551?folderId=3510499)

**Comment by jrbuddyboss** [comment]
Related Ticket: https://secure.helpscout.net/conversation/1569069066/152921/
