### ISSUE TITLE
Forum list widget not working properly when adding parent forum ID

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2343]
**Describe the bug**
If I add a parent forum ID in Forum List widget then it is showing all forums instead of the child forums for the parent forum. The issue is also happening in our demo site. Please refer to the video: [https://drive.google.com/file/d/1pbIvaXmyKsnjLPf7_MOHzJrTGAtcOqJG/view?usp=sharing](https://drive.google.com/file/d/1pbIvaXmyKsnjLPf7_MOHzJrTGAtcOqJG/view?usp=sharing)

**Support ticket links**
[https://secure.helpscout.net/conversation/1486016121/136901?folderId=4314898](https://secure.helpscout.net/conversation/1486016121/136901?folderId=4314898)

**Jira issue** : [PROD-830]

[PROD-830]: https://buddyboss.atlassian.net/browse/PROD-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dipskakadiya** [comment]
@mahedihasannoman Duplicate PR https://github.com/buddyboss/buddyboss-platform/pull/2841/files
