### ISSUE TITLE
Timeline preview image is not working.

### ISSUE THREAD

**Issue by asaquzzamanbb** [buddyboss/buddyboss-platform#2345]
**Describe the bug**
Black preview image showing form user timeline. Upload PDF file from user timeline and save changes. It will show the blank image.

**To Reproduce**
1. Go to  this client site https://personaldevelopmentexpert.com/
2. Navigate to timeline and upload PDF file.
3. See error, PDF preview image will show blank.

**Expected behavior**
Need to show preview image.

**Screenshots**
https://www.loom.com/share/8464d432d4df479d9fb06c38b20a62ff

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by sumitbuddyboss** [comment]
Hello @asaquzzamanbb 

Issue >
Still, I can't see the pdf preview image please check the below issue video.

Issue
https://www.loom.com/share/f3e6bc67eb49430b8f6ba5f341de6da4

Thank you
