### ISSUE TITLE
All members should be on Members Directory on a specific sub-site in wpmu

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#2355]
**Describe the bug**
All members should be on Members Directory on a specific sub-site in wpmu

**To Reproduce**
1. Activate BuddyBoss Platform subsite wise (not network wise)
2. Go to a members directory page on a subsite
3. Displays all members over the network, should display all members from that specific subsite only

**Note**
- validated the issue
- when platform is activated subsite wise (not network wise), users created from a subsite backend > users, showing all users in other subsites frontend members dir page https://i.imgur.com/Jzptug6.png whereas they dont show in those subsites backend > users page https://i.imgur.com/va9sPX9.png
- same issue exists in buddypress

**Expected behavior**
On subsite members directory page, should display all members from that specific subsite only

**Support ticket links**
https://secure.helpscout.net/conversation/1485999473/136893/

**Jira issue** : [PROD-826]

[PROD-826]: https://buddyboss.atlassian.net/browse/PROD-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ngolwalkar** [comment]
@sadrul 
In Multisite by default, all sites have the same user table and user meta. So all the subsites share all the members across the network. We might need to discuss if we should separate it with the Platform plugin or not. 
CC : @sourabhmatolia

**Comment by kcristiano** [comment]
I've just run into the same issue on a WP Multi-Network.  It appears that when loading the members directory on a sub-site the subsite `wp_x_bp_xprofile_data` table gets populated from the global user table, resulting in all network users being shown on all subsites.

This does not occur in pure buddypress, It looks like `xprofile_filter_get_user_display_name` is what causes the site id to not be respected.   

We do believe that the members should be site specific.   This is a critical issue for us so we are interested in any progress.
