### ISSUE TITLE
Groups pages become slow when there are thousands of users in it with the latest version.

### ISSUE THREAD

**Issue by buntybuddyboss** [buddyboss/buddyboss-platform#2356]
If any group has thousands of users, then all the sub-tabs of that group are loading slow.

Previously reported here > https://github.com/buddyboss/buddyboss-platform/issues/1142. And it was last fixed in v1.4.7

This issue I noticed after v1.5.5.1

**To Reproduce**
1. Go to Groups which has thousands of users.
2. Try to click on all the sub-tabs one by one
3. All the pages of that group will load slow.

**Expected behavior**
Single groups pages should not load slow when there are thousands of users in it.

**Video**
https://www.loom.com/share/a4db46362abd4f9bb583f181de41ca4a

**Sample DB from my local site**
[wp_bbplatform.sql.zip](https://github.com/buddyboss/buddyboss-platform/files/4879500/wp_bbplatform.sql.zip)

**Support Tickets**
Issue reported on one of our client's site

**Comment by sourabhmatolia** [comment]
Similar issue shared here:
https://github.com/buddyboss/buddyboss-platform/issues/2327
Maybe same issue need to cross check.

**Comment by buntybuddyboss** [comment]
@sourabhmatolia That patch works. Verified on client's DEV site as well as on my local.
