### ISSUE TITLE
Add Legal Agreement checkbox to Register Form

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#2360]
**Scope**
Add the option in the BuddyBoss Platform's settings for site admins to require users check a box agreeing to their terms of service/privacy policy before registering. This is a requirement for GDPR-compliance.

**Loom:**
https://www.loom.com/share/cad89bee07d04c878c1a102117148409

**Wireframes:**
https://miro.com/app/board/o9J_lIFgkJg=/
bbregistercheckbox

**Acceptance Criteria**

- [ ] A Legal Agreement checkbox has been added to Settings > General
- [ ] When the checkbox is checked (and the form saved), the Terms/Privacy text at the register form is replaced with a checkbox above the button
- [ ] The button is disabled until the checkbox is checked
- [ ] When the checkbox is NOT checked, the Terms/Privacy text appears as currently configured
- [ ] The text of the checkbox changes dependent on whether the Terms of Service and Privacy Policy pages have been configured in the Pages settings
- [ ] Save a record in the user's meta data so that there is a record/log that they agreed

----

App Native Related:
https://github.com/buddyboss/buddyboss-app-native/issues/989

**Comment by mikejyoung** [comment]
@krunal-buddyboss 
Added one item to Acceptance Criteria:
_Save a record in the user's meta data so that there is a record/log that they agreed_

CC: @sourabhmatolia @grahamhoffman

**Comment by sourabhmatolia** [comment]
@mikejyoung 

As per discussion with Alyssa:
`We have apps that don't want registration on App but apple requires them for a Terms of Service and Privacy Policy on the login screen.`

We might need to provide setting to show TOS and PP on the login form also.
Same will show for App.

**Comment by eisenwasser** [comment]
@sourabhmatolia @krunal-buddyboss 

Updated Scope:
https://www.loom.com/share/1a8f87bc6752485f964a93d952f6e575?from_recorder=1&focus_title=1
