### ISSUE TITLE
2-byte code is not supported for group slug, need option to edit group slug in "Create a new group" page

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2361]
**Describe the bug**
If the group name has a 2-byte code, it doesn’t work properly. But if the permalink is changed from 2 bytes to 1 byte, (leaving the group name as it is,) it does work. However, the "Create A New Group" page doesn't have an option to change the slug. So if we put a field for group slug in frontend group creation page then the issue will be solved.

**To Reproduce**
1. Go to Create A New Group page.
2. Add a group name that has 2-byte code or any non ASCII characters.

**Support ticket links**
https://secure.helpscout.net/conversation/1491385360/138225/

**Jira issue** : [PROD-824]

[PROD-824]: https://buddyboss.atlassian.net/browse/PROD-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dipskakadiya** [comment]
@mahedihasannoman 

Here we have 2 separate issue

The group does not allow adding 2-byte characters into group name/slug
> I think the issue of the 2-byte character looks big because the group slug will be used in the permalink for the group page and many other places. [ We should try to use the same  characters in post slug and check how WordPress default handing that we should follow that here ]

Group doesn’t have the option to update the group slug.
> For Group slug we can add a new meta box in the backend only like WordPress post has to update post slug. [ Don’t forget, on update slug might be we need to flush rewrite rule ]
