### ISSUE TITLE
Hidden Groups - Create a Discussion for non-admin Bug 

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#2364]
**Describe the bug**
Members of hidden group get redirected to home page when creating new discussion.
Replicated in demo

**To Reproduce**
1. As an admin, create a new hidden group with forum
2. Create a new discussion on the group
3. Login as a non-admin (member of the group)
4. Create a new discussion
5. Redirected to home page

**Expected behavior**
Members of hidden groups should be able to create new discussions

**Screenshots**
https://www.loom.com/share/2a1acf157c3e44a1849ed5f137cab5fc

**Support ticket links**
https://secure.helpscout.net/conversation/1495178423/138933/

**Comment by manishpatolia** [comment]
@marilyn9425 

I have checked with the latest pull and it's working fine for me.
and I have also checked on the demo and there has also worked fine for me.

please see my proof and let me know if I have followed the wrong step

Proof:
https://www.loom.com/share/5d97811759f64626bcae4e0656b8414b
