### ISSUE TITLE
Sharing Document link in Private message breaks the Layout

### ISSUE THREAD

**Issue by sourabhmatolia** [buddyboss/buddyboss-platform#2369]
**Check Video for More details:**
https://www.loom.com/share/969af54810a3452399b2bea57d920216

**Again Note from the Video:**
- Allow sharing documents, photos, or any link in Private messages instead of embedding.
- Should be allowed to share the link in Activity post, Forums Discussions, Replies, Post Comments, etc.
- We will allow sharing of Documents and Photos but it will be accessible based on the privacy configured.

**Comment by roshni07** [comment]
https://secure.helpscout.net/conversation/1547243466/148351?folderId=4687016
