### ISSUE TITLE
 Issue with WP Project Manger user adding and file upload option.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#2370]
**Describe the bug**
When I try to add a user in the overview tab inside a project I get the following error, and the user does not get added to the project: https://imgur.com/a/a3BqAqF When I try to upload a file from the computer in the files tab I get the following errors: https://imgur.com/a/pndAdSm
https://www.buddyboss.com/integrations/wp-project-manager/

It works fine with buddypress.

**To Reproduce**
https://screencast-o-matic.com/watch/crfU31VeBwG

**Support ticket links**
https://secure.helpscout.net/conversation/1495417106/138982/

**Comment by kishanjasani** [comment]
We can't add Fix for this plugin in our platform. It's their plugin error. But you can add this snippet to the theme's function.php resolve this issue. Closing this issue.

`add_action( 'admin_head', function () {
  echo "<script type='text/javascript'> window.addEventListener( 'DOMContentLoaded', function() { window.jQuery = window.$ = jQuery; } ) </script>";
} );`
