### ISSUE TITLE
Profile field visibility is not working properly - "only me"

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2371]
**Describe the bug**
By default "only me" not working and visible to others when set with Allow members to override setting, It will work if the member at frontend changes to only me and saves or the only me with the enforce field visibility set

![image](https://user-images.githubusercontent.com/80085922/116784057-ad64df80-aaaf-11eb-9701-186cdee5970b.png)

**To Reproduce**
1. Add new field from the profile fields on the sign up form
2. Make the field visibility to only me set with Allow members to override
3. Now update this field for any subscriber say SUBSCRIBER A
4. Now check SUBSCRIBER A's profile with the other subscriber say SUBSCRIBER B logged in, the field will be still visible publicly

**Expected behavior**
The field should be private

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1500343384/139885

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1522714363/143977/

Customer have had to change the profile field to "Enforce Field Visibility" to get the field to not show on the user's profile, however, ideally I'd like to allow users to choose.

https://ibb.co/XyLf8nP

**Comment by bb-yudhisthir** [comment]
Tried to replicate again now but unable to replicate, seems might be resolved with the in between release updates
