### ISSUE TITLE
User lost the ability to create a discussion on hidden group that he/she is member of on latest platform update

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2374]
**Describe the bug**
It was working fine in v1.5.7.3 but now it is stopped working from v1.5.8. Please refer to my video where I demonstrate the issue: https://www.loom.com/share/e760f9dfe65648e09d5c4d23c4956116

**To Reproduce**
See video

**Support ticket links**
https://secure.helpscout.net/conversation/1501280777/140069?folderId=4314898

**Comment by mahedihasannoman** [comment]
The issue is happening for this commit: [https://github.com/buddyboss/buddyboss-platform/commit/5b3a1ca62eefa7d95221855cf2ac39fafe809485#diff-391ca9da004af956a9c1310fad101ee65964cfbd7f2d4dcb640e6f69be4aa21c](https://github.com/buddyboss/buddyboss-platform/commit/5b3a1ca62eefa7d95221855cf2ac39fafe809485#diff-391ca9da004af956a9c1310fad101ee65964cfbd7f2d4dcb640e6f69be4aa21c)

**Comment by krunal-buddyboss** [comment]
Hello @mahedihasannoman 
I have checked on our demo site with v1.5.9 version and I can not reproduce it.
Please check once from your side and let us know we can close it?
Thanks
FYI @sourabhmatolia

**Comment by mahedihasannoman** [comment]
As per checking this issue is not happening in latest version anymore. @krunal-buddyboss . So I am closing this issue.
