### ISSUE TITLE
New line not working properly and 2nd line not visible when typing a new feed or sending message in editor in Mobile browser

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2378]
**Describe the bug**
New line not working properly and 2nd line not visible when typing a new feed or sending message in editor in Mobile browser
Also in some resolution the editor gets cutoff and only one line visible. 
**To Reproduce**
1. Go to activity page from mobile browser
2. Create new activity feed and try to type the text in the editor, try to enter into the next line and enter the text
3. Similarly in Message editor new lines not working properly
4. Also in some resolution the editor gets cutoff and only one line visible
![image](https://user-images.githubusercontent.com/80085922/117130048-21a7c780-adbd-11eb-8a7f-1374c89f6115.png)
**Expected behavior**
New line should be visible and work properly

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1502456262/140261/

**Comment by marienel21** [comment]
I can't replicate this bug on the latest version of the Platform. tested on demo.

**Comment by marienel21** [comment]
![image](https://user-images.githubusercontent.com/77659570/129509994-46cc5634-b09a-4f2f-8a37-912fb9a1ae82.png)

**Comment by kishanjasani** [comment]
Not able to replicate it on the demo site and the buddyboss-release branch too. 

Closing this issue.
