### ISSUE TITLE
The GIF comment is being deleted when the owner edit that activity post.

### ISSUE THREAD

**Issue by anand-bb** [buddyboss/buddyboss-platform#2388]
**Describe the bug**
If someone does a GIF comment on an activity post and the owner edit that post then that GIF comment is getting deleted.
**To Reproduce**
1. Create an activity post
2. Do the GIF comment and then edit that post. 
3. The GIF comment is deleted now

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/1Y_tJBn54Wv7LHdPSwM4OtiI5uqw5xUCb/view

**Support ticket links**
https://secure.helpscout.net/mailbox/0c6c1f9d7be4e7d7/4312419/

**Jira issue** : [PROD-820]

[PROD-820]: https://buddyboss.atlassian.net/browse/PROD-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by roopeshbuddyboss** [comment]
Hi @anand-bb ,

I have checked this issue with the latest plugins and BB-theme and demos too and I could not replicate the issue. Can you please check the attached video and let me know if you finding something?

https://www.loom.com/share/74512da0491846a2b41e5bb639b0ebeb

-------

**Note:**
@anand-bb Please confirm so I can close the issue. If it's working fine for you too.

Thanks

**Comment by anand-bb** [comment]
Hello @roopeshbuddyboss,
Thanks for checking it.

Actually, I referred to a GIF comment, not a new GIF post.
Please refer to the following video.

It would help to replicate the issue.
https://drive.google.com/file/d/1vE09LBtq0gYyQfirx_5vG7iq0MNlXOyM/view

Please DM me if something is not clear.
Thank you:)
