### ISSUE TITLE
Error while posting clickable link with content in Activity feed

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2393]
**Describe the bug**
When we Have to paste an clickable URL (<a href="…) with content in activity feed area. Try post an update with a link that is blue/underlined and clickable.. Then you get the error.

**To Reproduce**
1. Go to '.Activity feed'
2. Copy the text with clickable url
3. Paste in Activity feed area and click on updates

**Expected behavior**
It should not get error while posting the clickable link with content in Activity feed area 

**Screenshots**
https://prnt.sc/12sinlq

**Support ticket links**
https://secure.helpscout.net/conversation/1508705863/141432/merge/1488471817/

**Comment by ngolwalkar** [comment]
@shyamwp14 
@janakkaneriya007 already explianed this issue here : [#683](https://github.com/buddyboss/buddyboss-platform/issues/683#issuecomment-607195790)
