### ISSUE TITLE
Single quote in user name or last name is not appearing correctly in private message.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#2398]
**Describe the bug**
 if a user's name or last name contains a single quote, it is not rendered correctly in the messages view, while it is viewed correctly in the member's area.

**To Reproduce**
Enable First Name and Last name from settings.
https://prnt.sc/12ud4hy

Send a message to someone and see the error in the private mesage.
https://prnt.sc/12ud3fx

**Screenshots**
https://prnt.sc/12ud3fx

**Support ticket links**
https://secure.helpscout.net/conversation/1506888072/141120?folderId=3701248

**Comment by umohitbuddyboss** [comment]
Verified Result - Fixed

Attached Screenshot - 
![image](https://user-images.githubusercontent.com/85428333/133045140-7f4cd726-7a37-4450-adac-9c8be931feaf.png)

Tested this on site : https://bb-app-platform.flywheelsites.com/
