### ISSUE TITLE
When switch on translated page the zoom integration activity post doesn't show right

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2405]
**Describe the bug**
When switch on translated page  using TranslatePress - Multilingual,  the zoom integration activity post doesn't show right

**To Reproduce**
1. Go to 'Create new meeting using zoom'
2. Click on 'Then switch on translated page (i.e using Fr language) the zoom integration activity post doesn't show right '
3. Using "TranslatePress - Multilingual" plugin.

**Expected behavior**
it should be display with proper translated  zoom meeting time .

**Screenshots & url**
https://prnt.sc/130zeho
https://prnt.sc/130zgmx
https://dev-shyam.flywheelsites.com/fr/groups/test-group33/zoom/meetings/1/

**Support ticket links**
https://secure.helpscout.net/conversation/1512049845/142029?folderId=4265312

**Comment by mahedihasannoman** [comment]
Hi @shyamwp14 , I am not able to re-produce this issue anymore. Please see my video: https://www.loom.com/share/cd010e5380134ffe8866ddbb08ad8cdc

If the issue is not reproducible then please close this ticket.

**Comment by shyamgudadhe** [comment]
I have tried to replicate again now but unable to replicate, seems might be resolved with the in between release updates
