### ISSUE TITLE
Link Preview on Activity is different on Forum link preview

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#2407]
**Describe the bug**
Link previews are different
Activity vs Forum

**To Reproduce**
1. Go to Forums > New Discussion
2. Add link (`https://msnglnk.com/storyseller/`)
3. Preview only displays Title

----

1. Add link on Activity feed
2. Preview displays Title, Image, Excerpt

**Expected behavior**
Same preview format - Title, Image (if any), excerpt

**Screenshots**
https://prnt.sc/1311fpv
https://www.loom.com/share/9885f83890c949eeb8c3ba0cd007fb63

**Support ticket links**
https://secure.helpscout.net/conversation/1509967355/141620/

**Jira issue** : [PROD-818]

[PROD-818]: https://buddyboss.atlassian.net/browse/PROD-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1621712112/162415

**Comment by ngolwalkar** [comment]
@sourabhmatolia 
I need to discuss this issue with you.
Do we really need to change the preview for URL in Discussions?
