### ISSUE TITLE
The target attribute in Paragraph Text field is being removed after saving

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2414]
**To Reproduce**
1. Add a Paragraph Text field in a profile fieldset
2. Go to the frontend and edit your profile
3. Edit a text and insert a link
4. Make sure to enable "Open link in a new tab".
5. Save changes and notice that the anchor attributes including the target attribute are missing.

**Screen recording**
https://cutt.ly/xb0dWFF

**Screenshots**
![ss1](https://user-images.githubusercontent.com/58522498/118765701-06a18100-b8ae-11eb-8ef9-5050b4667269.jpg)
![ss2](https://user-images.githubusercontent.com/58522498/118765703-07d2ae00-b8ae-11eb-92d7-260fa85dfd07.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1517243031/142886/

JIRA ISSUE: [PROD-816]

[PROD-816]: https://buddyboss.atlassian.net/browse/PROD-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by BBmazharul** [comment]
Another support ticket link: https://support.buddyboss.com/a/tickets/150865
