### ISSUE TITLE
"Start course" button on Group page is redirecting to wrong URL course

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2417]
**Describe the bug**
"Start course" button is redirecting to incorrect course when **Shared Course Steps** is enabled, courses has same lessons and there is only one course assigned on the ff group 

**To Reproduce**
1. Go to **LearnDash LMS > Courses > Settings > Enable Shared Course Steps**
2. Create 2 courses with different titles but with same lessons
3. Assign the newly created courses to 2 different groups (Make sure that the group has only the course (1) you created)
4. Go to Group page course tab and click the "start course" button
5. See error

**Screenshots**
https://www.loom.com/share/17f17c990df94681bd61fc2293d9e0c2

**Support ticket links**
https://secure.helpscout.net/conversation/1334678955/108214/
https://secure.helpscout.net/conversation/1436183066/127253
https://secure.helpscout.net/conversation/1367162948/114871
https://secure.helpscout.net/conversation/1504102610/140581

**Comment by manishpatolia** [comment]
@Santos-Jamie 

This is an issue from the theme side so I have created an issue on the theme(Below link) and create a PR there,
So I'm closing this issue.

https://github.com/buddyboss/buddyboss-theme/issues/1538
