### ISSUE TITLE
Subgroup detaches from Parent group when updating group "description"

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#2418]
**Describe the bug**
Subgroup detaches from Parent group when updating group "description" or renaming the group title. Please refer to the screen recording.
http://somup.com/crhq6EqcKl

**To Reproduce**
1. Enable subgroup option from buddyboss >> settings >> groups >> group hierarchy.
2. Create a sub-group and assign it to a parent group.
3. Now update the description of a subgroup.
4. See error.

**Expected behavior**
The parent group should be detached when updating the subgroup description.

**Support ticket links**
https://secure.helpscout.net/conversation/1517318916/142909?folderId=3701248

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1521777646/143742/

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1697295586/173902/

**Comment by SisirChowdhury** [comment]
https://www.loom.com/share/53b6abefbe5245cdb66e19b39abac7e6
