### ISSUE TITLE
LD Group and Social Group member sync bug

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#2419]
**Describe the bug**
Resaving the LearnDash Group (when adding courses as needed, or just resaving) the Roles (Organizer, Moderator, Members) set on Social Group is reset back.

**To Reproduce**
Steps to reproduce the behavior: (using LearnDash demo)
1. Go to BuddyBoss > Integration > LearnDash, Enable Social Group Sync and LearnDash Group Sync
2. Create LearnDash Group, set an Associated Group (ie. Coffee Addicts)
3. Go to front-end, Groups > Coffee Addicts
4. Manage > Members, Promote Organizers and Moderator
5. Go back to backend, LearnDash > Groups > Coffee Addicts
6. No need to change anything, just click update
7. Notice how the groups has no moderators

**Expected behavior**
Saving the LD group will retain the roles of the social groups

**Screenshots**
https://www.loom.com/share/2b5e27f9dee74132be90d63b4a9e865b

**Support ticket links**
https://secure.helpscout.net/conversation/1458075628/131461

JIRA ISSUE: [PROD-815]

[PROD-815]: https://buddyboss.atlassian.net/browse/PROD-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kent-carlo** [comment]
@marilyn9425 I have tested it and I was able to only replicate the issue with moderators gone after updating the LD course. I verified that the behavior is I think expected. Moderator/Mentor only exists on buddyboss and LD only has Group Leaders and Group users. In settings, Mentors is supposed to be sync as group leader. Please see screenshot below and can discuss with you if there's any confusion. Issue will get fixed if you set the Sync Moderators to none.
![image](https://user-images.githubusercontent.com/82648504/128878036-b04e1541-d38e-4da0-8e73-6a8f0233b5f6.png)
