### ISSUE TITLE
Subgroups are displaying in All Groups and My Groups tabs whereas Hide Subgroups option is checked from setting

### ISSUE THREAD

**Issue by jitendrabanjara1991** [buddyboss/buddyboss-platform#2420]
**Describe the bug**
Subgroups are displaying in All Groups and My Groups tabs whereas Hide Subgroups option is checked from setting.

**To Reproduce**
1. Go to BuddyBoss -> Groups -> Create Group ( i.e - Parent Group)
2. Go to BuddyBoss -> Groups -> Create Group  ( i.e - Sub Group) -> Select Group Parent ( i.e - Parent Group)
3. Go to BuddyBoss ->Settings -> Groups -> Hide Subgroups -> Checked
4. See error - https://screencast-o-matic.com/watch/crhYjFVfdVx

**Expected behavior**
Subgroup should not be display in All Groups and My Groups tabs if we enable Hide Subgroups option from setting.

**Screenshots**
https://screencast-o-matic.com/watch/crhYjFVfdVx

**Support ticket links**
Based on App testing

**Comment by surajkrsingh** [comment]
@jitendrabanjara1991 @KartikSuthar @chetansatasiya 
In the above PR, We have also considered one more case that is user profile > group page >My Groups tab

As settings, the subgroups shouldn't display in `my groups` tab and the user profile has also my group tab.
before it displayed the subgroups even if hide settings enabled 
See here - https://www.awesomescreenshot.com/image/12782881?key=ed8cef84258fcc2700f5fd3e2c6ac29b

After the fix, it will show the root parent groups only - https://tinyurl.com/yhjac3en 

Moreover, I need your suggestion on this test case.
Please let me know if need to change anything related to this test case.

**Comment by surajkrsingh** [comment]
@jitendrabanjara1991 
We discussed the issue with @chetansatasiya and @KartikSuthar  and got the actual scenario that 
My group's tab shows the subgroups intentionally on the group directory page.

So, I think this is not a valid issue.
please check and close this issue.
