### ISSUE TITLE
the "bp_register_member_type" function doesn’t work to create new profile type

### ISSUE THREAD

**Issue by mailalaki** [buddyboss/buddyboss-platform#2422]
the **"bp_register_member_type"** function doesn’t work when I want to add new profile type programmatically! This function returns the object without error, but nothing is actually created!
If using this function has other prerequisites, please help.

i'm using latest version(1.5.9) of buddyboss platform.

https://www.buddyboss.com/resources/reference/functions/bp_register_member_type/

**Comment by mailalaki** [comment]
> 
> 
> the **"bp_register_member_type"** function doesn’t work when I want to add new profile type programmatically! This function returns the object without error, but nothing is actually created!
> If using this function has other prerequisites, please help.
> 
> i'm using latest version(1.5.9) of buddyboss platform.
> 
> https://www.buddyboss.com/resources/reference/functions/bp_register_member_type/

the **"bp_groups_register_group_type"** function has same issue!

**Comment by surajkrsingh** [comment]
@mailalaki 
As per your query, You want to add the new profile type programmatically to the profile type list
but bp_register_member_type function is used to registered the created profile type as a member type dynamically

**To add the new profile type in the table** 
You can simply create a new post with `post_type` as `bp-member-type`  that is CPT.
For this, you can use WordPress core function  wp_insert_post

Your added profile type will automatically be registered as a member type by the hook `bp_register_member_types` 

Same as bp_groups_register_group_type function.
For this, you use post_type as `bp-group-type`

**Comment by surajkrsingh** [comment]
@dipskakadiya 
This is not a bug but a customer query regarding the function.

Now, We can close this issue.

**Comment by mailalaki** [comment]
after 3.5 months!
yes, that's right.
thanks
