### ISSUE TITLE
Selecting "Discussions by Last Post" returning /topics/ page 404 error

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2423]
**Describe the bug**
When "Discussions by Last Post" is selected on "Forums Directory show" the /topics/ page returning 404 error 

**To Reproduce**
1. Go to **BuddyBoss > Settings > Forums > Scroll down to Forums Directory shows > Select "Discussions by Last Post"**
2. Go to https://site-url/forums/
3. Scroll down to pagination then click 2
4. Scroll down again to pagination then go back to page 1

**Screenshots**
https://www.loom.com/share/de7f61dbae7943b683b1fd74f2d2c068

**Support ticket links**
https://secure.helpscout.net/conversation/1516970176/142831

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1530258510/145345/

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1556927124/149826
Forum Discussion topics paginiation 404 error using Memberium plugin as a members.
