### ISSUE TITLE
Learndash Course - Last Activity date is not getting change and showing older date.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#2429]
**Describe the bug**
If logged in user perform any activity on 'In progress' course and then check the "Last Activity date" then it shows older activity date and new activity date do not appear.

**To Reproduce**
1. Go to 'Courses' page.
2.  Perform activity in 'In Progress' courses.
3. Check activity date.
4. See error.

**Expected behavior**
Last activity date must appear according to last activity perform in course and it must change when ever user perform any activity.

**Screenshots**
https://www.loom.com/share/38e8baa3ac79443fa344625aa882c03a

**Support ticket links**
N/A reported internally by QA

**Comment by shakilAshraful** [comment]
unable to reproduce in the app. 
I just made some changes in the course and I am getting the updated date.
![Screenshot 2021-09-23 at 4 46 58 PM](https://user-images.githubusercontent.com/64884320/134494537-7ec70000-a7b2-44e6-a99a-2d67fdca53b4.png)

**Comment by mohit-buddyboss** [comment]
I'm also not able to reproduce this issue now. 
Tested on master branch of the platform and theme.
Video: https://screencast-o-matic.com/watch/crQ0hvV6UgQ

So, issue is not exist now that's why closing this issue.

cc @sourabhmatolia @firozwp @KartikSuthar
