### ISSUE TITLE
Custom Post Types options are not working with GamiPress Post Types

### ISSUE THREAD

**Issue by jitendrabanjara1991** [buddyboss/buddyboss-platform#2431]
**Describe the bug**
If enable **Achievement activity entries** option from GamiPress plugin. And uncheck GamiPress posttype (Related with Achievement ), then related with GamiPress's activity is displaying in activity section.

![image](https://user-images.githubusercontent.com/30429982/119499012-e711c900-bd83-11eb-90f7-00ea75dbbb40.png)

![image](https://user-images.githubusercontent.com/30429982/119499918-d6158780-bd84-11eb-93d2-5b52d758172c.png)

**To Reproduce**
1. Go to GamiPress - Achievement Types - Create New Achievement type and enable **Achievement activity entries** this option
2. Go to BuddyBoss - Settings - Activity - Custom Post Types (  See above screenshot for the settings - uncheck post types related with GamiPress )
3. Try to earn badges/achievement/rank - You can see in activity section - Achievement entry is displaying there.
![image](https://user-images.githubusercontent.com/30429982/119501244-4ffa4080-bd86-11eb-84a2-6633037cd2a1.png)

**Expected behavior**
GamiPress allow option to display entries in the activity section, At that time we can remove GamiPress Post type from **Custom Post Types** section OR can support both options.

**Screenshots**

https://github.com/buddyboss/buddyboss-app/issues/2028

**Comment by bb-yudhisthir** [comment]
@jitendrabanjara1991 The two things are totally different aspect
1) Settings in the Activity > Custom Post Type options - ( Post Publish activity of that post type ) like this activity created when any new achievement of that post type is created/published and will create a entry in activity and to enable/disable it we have to do from here:
https://user-images.githubusercontent.com/30429982/119499918-d6158780-bd84-11eb-93d2-5b52d758172c.png
http://somup.com/crQnjdrFsM
2) Gamipress Member Activity entries like when user unlock achievement/rank etc. and to enable/disable it we have to do from here:
https://user-images.githubusercontent.com/30429982/119499012-e711c900-bd83-11eb-90f7-00ea75dbbb40.png

So, both are different - 1) is for the Post type created while the 2) is for the members achieving that achievement

May be we can highlight the text or change the text in the Settings in the Activity > Custom Post Type section to make it clear and no confusion

cc: @sourabhmatolia
