### ISSUE TITLE
Group type pages stopped working

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2434]
**Describe the bug**
The group type pages have stopped working since the last update.

**To Reproduce**
1. Go to 'Buddyboss  > Group'
2. Click on 'Group type'
3. Create Group type like "sample-groups"
4. Then assigned that group type to the any created group.
5. Then you can group type page is not working
 https://demos.buddyboss.com/online-communities/groups/sample-groups/

**Expected behavior**
Group type url should be work for the group.
**Screenshots**
https://ibb.co/8M9dnm1

**Support ticket links**
https://secure.helpscout.net/conversation/1518427182/143127?folderId=4265312

**Comment by sourabhmatolia** [comment]
@shyamwp14 

When we create Group Type then URL is NOT:
https://demos.buddyboss.com/online-communities/groups/sample-groups/

It is something like
https://demos.buddyboss.com/online-communities/groups/type/sample-groups/

I tried and it works for me here on DEMO:
https://prnt.sc/13npv5p

Please cross-check this issue carefully and close. Thanks.
