### ISSUE TITLE
When uploading photos and viewing them in mobile screen mode, some of the photos will overlap and some will not display in the activity feed

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2435]
**Describe the bug**
When uploading photos and viewing them in mobile screen mode, some of the photos will overlap and some will not display in the activity feed.

**To Reproduce**
1. Go to 'Activity feed'
2. Click on 'upload photo'
3. 'When uploading photos and viewing them in mobile screen mode
4. some of the photos will overlap and some will not display in the activity feed.

**Expected behavior**
It should not overlap and some will display in the activity feed.

**Screenshots**
https://prnt.sc/13fsk7z

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

JIRA ISSUE: [PROD-814]

[PROD-814]: https://buddyboss.atlassian.net/browse/PROD-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by asadpalasara07** [comment]
@shyamwp14 

Photos you are facing overlap it's not overlapping but it's cut off from the Thumbnail box. Those images are Thumbnails and we can not cover the whole image in Thumbnail.
This seems like not an issue but still, let me know if you have any query.

Thanks

**Comment by shyamwp14** [comment]
can you resize the image size as per the Thumbnail box?

**Comment by amincdev** [comment]
@shyamwp14  Users post different dimensions and it is not possible to show full image as a thumbnail. However, User can always view the full photo in the popup.

**Comment by shyamgudadhe** [comment]
https://secure.helpscout.net/conversation/1657802348/168361/

**Comment by amincdev** [comment]
@shyamgudadhe I have confirmed: This issue is fixed by this PR already: https://github.com/buddyboss/buddyboss-platform/pull/2843

So, I'm attaching this issue to the same PR.

**Comment by bb-yudhisthir** [comment]
Same issue: https://newaccount1634721716508.freshdesk.com/a/tickets/150539
