### ISSUE TITLE
Send Message button doesn't get disabled after first click in Group Private Messages.

### ISSUE THREAD

**Issue by ngolwalkar** [buddyboss/buddyboss-platform#2438]
**Describe the bug**
In Group Messages, when the user tries to send a message to one or multiple members of that group, send button doesn't get disabled when the user clicks it, sometime it takes time to show the success message so that the user might click it multiple times, which causes the multiple emails to fire.

**To Reproduce**
1. Create two test member profiles with working email ids and create a test group, assign that group to both the members.
2. Login with one of the members.
3. Go to that group you created and get assigned.
4. Click on "Send Messages" ( Make sure the messages are allowed for all group members if you are trying as a group member )
5. Click on the "Send Private Message" tab
6. Try to send messages to other member profile you created. Click on "Send Message" multiple times until it shows success message.  
7. Check the second user email, you will get multiple emails for the same message.
**Expected behavior**
The "Send Message" button should be disabled right after the first click.

**Screenshots**
https://www.loom.com/share/2c2fa17102904e5a9e6dc2783a5b51af?fbclid=IwAR2kTlIXtx-8XQT0zLDNGrPDpUufVb08asVC0qF9lzsbX7HWuv6V52rd1FU

**Comment by justinpatrickkeller** [comment]
I just realized that one of the developers gave me this code a while ago. I had disabled it after the update that added the spinny wheel (as I thought it also added the "disable" button after initial click)... I have no idea why that aspect of this wasn't included in the release that added the spinny where... Just thought I would share if its helpful. 

jQuery(".bb-groups-messages-right #whats-new-toolbar #send_group_message_button").click(function(){
  jQuery(this).addClass("disabled");
  jQuery(this).val("Sending Message...");
  jQuery(this).after("<span class=button-overlay></span>");
});

CSS on Theme Options > Custom Codes:

.bb-groups-messages-right #whats-new-toolbar #send_group_message_button.disabled {
    background-color: #66b0b5;
    color: #ffffff;
    pointer-events: none;
}
#group-messages-new-submit span.button-overlay {
    position: absolute;
    right: -20px;
    bottom: -20px;
    width: 210px;
    height: 50px;
    cursor: not-allowed;
}

**Comment by chetansatasiya** [comment]
> I just realized that one of the developers gave me this code a while ago. I had disabled it after the update that added the spinny wheel (as I thought it also added the "disable" button after initial click)... I have no idea why that aspect of this wasn't included in the release that added the spinny where... Just thought I would share if its helpful.
> 
> jQuery(".bb-groups-messages-right #whats-new-toolbar #send_group_message_button").click(function(){
> jQuery(this).addClass("disabled");
> jQuery(this).val("Sending Message...");
> jQuery(this).after("");
> });
> 
> CSS on Theme Options > Custom Codes:
> 
> .bb-groups-messages-right #whats-new-toolbar #send_group_message_button.disabled {
> background-color: #66b0b5;
> color: #ffffff;
> pointer-events: none;
> }
> #group-messages-new-submit span.button-overlay {
> position: absolute;
> right: -20px;
> bottom: -20px;
> width: 210px;
> height: 50px;
> cursor: not-allowed;
> }

@justinpatrickkeller This will be fixed in https://github.com/buddyboss/buddyboss-platform/pull/2439/files this PR in the upcoming release.

**Comment by sourabhmatolia** [comment]
@justinpatrickkeller

Issue mentioned above is released in BuddyBoss Platform v1.6.1

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-6-1/

Please update the plugin to see the latest changes.

Thank you.
