### ISSUE TITLE
Issue in photo icon with  post on groups as Member user after latest updates

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2444]
**Describe the bug**
Customer  trying to update BB Platform but any version above 1.5.6 seems to break the good functioning of the site. Here are some issues I encounter: - Impossible to comment a post in the activity page or group page. - The image icon for attachment to a post is not available for non admin users in the group pages. It is available in the private messages though. - Impossible to edit an existed post (even with admin right).

**To Reproduce**
1. go to https://demos.buddyboss.com/online-communities/ (demo)
2. post in the activity page or group page  group page
3.image icon for attachment to a post
4. edit an existed post as a user

**Expected behavior**
It should be work for photo icon with  post on groups as Member user

**Screenshots**
https://photo-avenue.com/wp-content/share/bug_BB_Images_Post.mov

**Support ticket links**
https://secure.helpscout.net/conversation/1515729248/142616/

**Comment by sadrul** [comment]
@shyamwp14 I could not replicate the issue on buddyboss sandbox https://www.loom.com/share/23b916e142a74ca2b6c07a7a2cc5a2df
could you please share a video of how to replicate it. If the issue already fixed, could you please close this
