### ISSUE TITLE
Compatibility BB & Restrict Content Pro Component Restriction issue with free membership

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2445]
**Describe the bug**
User use Restrict Content Pro for memberships and the RCP Buddypress add on for integration. We have enabled the media component: users should be able to upload images. However, they are forwarded to .../profile/?rcpbp=restricted. Even if we disable BuddyPress component restriction in 'RCP Pro - Buddypress' settings page.

**To Reproduce**
1. Go to 'Restrict Content Pro' setting
2. Create membership level for free member
3. Then allow "Restrict Content Pro Component " of photo
4. But free memeber is not able to  upload media 

**Expected behavior**
In Restrict Content Pro Component Restriction, it should be work  for Free membership level member, when RCP photo component enabled.

**Screenshots**
https://ibb.co/kX23CSH
https://ibb.co/DzRNVGY

**Support ticket links**
https://secure.helpscout.net/conversation/1515872360/142637?folderId=4265312

**Comment by sadrul** [comment]
@shyamwp14 There is a compatibility issue with "Restrict Content pro Buddypress" plugin, it can be fixed using the below code in child theme functions.php

`add_filter( 'rcpbp_allowed_user_components', function( $components ) {

    if( !empty( $components ) && is_array( $components ) ){

        $components = array_map( function ( $single ){

            if( $single == 'document' ){
                $single = 'documents';
            }
            if( $single == 'media' ){
                $single = 'photos';
            }
            if( $single == 'video' ){
                $single = 'videos';
            }

            return $single;

        }, $components );

    }

    return $components;
} );`

Platform integrations in official list can be found here - https://www.buddyboss.com/integrations
"Restrcit content pro" is not platform official list rather its in third party list so we are not going to add this compatibility issue fix into platform. We can ask customer to add the above code into child theme
