### ISSUE TITLE
When add any field in Profile Search section then notice is displaying in debug log

### ISSUE THREAD

**Issue by jitendrabanjara1991** [buddyboss/buddyboss-platform#2448]
**Describe the bug**
When add any field in Profile Search section then below notice is displaying in debug log
[02-Jun-2021 11:49:21 UTC] PHP Notice:  Uninitialized string offset: 0 in wp-content\plugins\buddyboss-platform\src\bp-core\profile-search\bps-directory.php on line 185

**To Reproduce**
1. Make sure enable debug log
2. Go to BuddyBoss -> Profiles -> Profile Search
3. Add field

**Expected behavior**
Notice/Warning should not be display in debug log

**Screenshots**
https://screencast-o-matic.com/watch/cr1nXKVhubf

**Support ticket links**

**Comment by surajkrsingh** [comment]
@jitendrabanjara1991 @dipskakadiya 
We are not able to replicate this PHP notice in the debug.log
That is already fixed in the recent release.
Fixed commit here - https://github.com/buddyboss/buddyboss-platform/commit/af0c7ec0a6ea246e6e79e53ab57cff4a3dd3c62a

I am closing this issue.
