### ISSUE TITLE
Admin profile timeline tab is showing all the connected members activities

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2452]
**Describe the bug**
The admin profile tab is showing all the connected members activities

**To Reproduce**
1. Login as admin 
2. Go to your profile or site-url/members/me
3. Click the Timeline Tab
4. See that even the other users activity is showing on the admin timeline

**Expected behavior**
It will only display the member/admin activities

**Screenshots**
https://www.loom.com/share/42cd4c6130294eb380fbd71056e2f4af

**Support ticket links**
https://secure.helpscout.net/conversation/1526626112/144608

**Comment by roopeshbuddyboss** [comment]
Hi @Santos-Jamie ,

- I have checked this issue but this is the functionality we build it.

- It's not an issue.

- But you can achieve the above by enabling the option from the backend  https://demos.buddyboss.com/online-communities/wp-admin/admin.php?page=bp-settings&tab=bp-activity https://prnt.sc/1bqigcs

**Video Explanation**

https://www.loom.com/share/0b5b199e58f143b99e2d89fc47d6cea8


Thanks
