### ISSUE TITLE
"and" not translated below login page at before the privacy modal link after the buddyboss platform update

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2455]
**Describe the bug**
"and" not translated below login page at before the privacy modal link after the buddyboss platform update

Checked the code missing the __() localization function on Line 1520
```
$link        .= ' and ';
			$link        .= sprintf(
				'<a class="privacy-link popup-modal-login popup-privacy" href="%s">%s</a><div id="privacy-modal" class="mfp-hide login-popup bb-modal"><h1>%s</h1>%s<button title="%s" type="button" class="mfp-close">%s</button></div>',
				'#privacy-modal',
				$page_title,
				$page_title,
				wp_kses_post( apply_filters( 'the_content', $get_privacy->post_content ) ),
				esc_html( 'Close (Esc)' ),
				esc_html( '×' )
			);
```

**Expected behavior**
"and" should also be translated

**Support ticket links**
https://secure.helpscout.net/conversation/1528458944/144941/

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1545902411/148131/

**Comment by Jahnine** [comment]
https://secure.helpscout.net/conversation/1563309597/151521/

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1566118463/152165/

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1576693708/154445/

**Comment by Jahnine** [comment]
https://secure.helpscout.net/conversation/1591801738/157052/

**Comment by Nayeem-BB** [comment]
https://secure.helpscout.net/conversation/1604897902/159395

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1609132682/160113/

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1592365353/157136/

**Comment by hercivalbuddyboss** [comment]
https://secure.helpscout.net/conversation/1556500376/149737
