### ISSUE TITLE
Messages > Default content &nbsp; enters when in messages user sent only image,doc or GIF.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#2456]
**Describe the bug**
In messages when user send only GIF, Image or doc then we are adding &nbsp; into the content by default.

**To Reproduce**
1. Go to 'Messages'
2. Select recipient.
3. Send only GIF , image or doc in message without text.
4. Change entry in database.

**Expected behavior**
It should not add &nbsp in content.

**Video**
https://www.loom.com/share/1b90575d92e64c9a9e638ad0cb2a1640

**Support ticket links**
N/A reported internally by QA

**Jira issue** : [PROD-812]

[PROD-812]: https://buddyboss.atlassian.net/browse/PROD-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by milanhirapra** [comment]
https://github.com/buddyboss/buddyboss-theme/pull/1627
