### ISSUE TITLE
Forum Discussions > Reduce excessive space showing under "Read More"

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#2459]
In a forum discussion, reduce the spacing between "Read More" and the author. 

![image](https://user-images.githubusercontent.com/75724470/120824478-6a83a500-c550-11eb-96d8-d51f0a8301cd.png)

**Comment by amincdev** [comment]
@mikejyoung Looking at the UI, This seems from the App. Please let me know if this is related to the theme.

**Comment by mikejyoung** [comment]
This can be closed @amincdev 
Not relevant anymore
