### ISSUE TITLE
Document visibility level filter missing for the following REST endpoint: /wp-json/buddyboss/v1/document/details

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2463]
**Describe the bug**
Document visibility level apply_filter missing for the following REST endpoint: /wp-json/buddyboss/v1/document/details
Please see this screenshot: https://prnt.sc/14f2xoc
If I add extra filter for the document visibility then it is not working in the BuddyBoss App.

**Expected behavior**
It should be like the following below line:
`$privacy = apply_filters( 'bp_document_get_visibility_levels', buddypress()->document->visibility_levels );`

**Screenshots**
https://prnt.sc/14f2xoc

**Support ticket links**
https://secure.helpscout.net/conversation/1534569146/146030?folderId=3701391

**Jira issue** : [PROD-810]

[PROD-810]: https://buddyboss.atlassian.net/browse/PROD-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ExoGeek** [comment]
Same issue : https://github.com/buddyboss/buddyboss-platform/issues/2460
