### ISSUE TITLE
Getting blank page for some keyword after searching when "Replies" are enabled for search setting

### ISSUE THREAD

**Issue by buntybuddyboss** [buddyboss/buddyboss-platform#2465]
**Describe the bug**
Getting blank page for some keyword after searching when "Replies" are enabled for search setting

**To Reproduce**
1. Go to `BuddyBoss` --> `Settings` --> `Search`
2. Check `Forums` & `replies` https://prnt.sc/14h91ml
3. Try to seach any keyword related to your site URL( Watch video to understand )
4. Hit enter & you will have balnk page.

**Expected behavior**
We should have results on the search result page

**Video**
https://www.loom.com/share/86eb181236e54acda3728ca96e9289bb

**Support ticket links**
N/A

**NOTE**: Let me know if you need copy of DB.

**Comment by ngolwalkar** [comment]
@buntybuddyboss I have checked with the issue and it seems to be client-specific. I checked the Parent topic id and the title for the reply was not assigned somehow or removed accidentally. So when we were searching for the word "Solo", it relates to that reply so the searching loop was having that reply in it and the functionality was calling its title and the title was not there, that is why the issues were coming. After assigning the id for that it worked fine.

**Comment by buntybuddyboss** [comment]
@ngolwalkar Could you please share which reply?

**Comment by ngolwalkar** [comment]
Below is the reply content.
<span class="atwho-inserted">@Mark </span> Good question!

It's not too late to open a Solo 401k for 2020 if a timely extension was filed for the business tax return (eg. 1120S for a self-employed business taxed as an S-corp, 1040 for a self-employed business taxed as a sole prop/single-member LLC).

In that case, a Solo 401k can be established and employer (profit-sharing) contributions can be made anytime until the extended tax return dealine (9/15/2021 or 10/15/2021 as applicable).

Click <a href="http://htdocs/mysolo.mysolo401k.net/solo-401k/open-a-solo-401k-account/"><b>HERE</b></a> to submit our online application.

The reply id is 2178 in the client's DB which you shared.

You can solve it by just assigning it the title as "ID" value and then go to wp-admin and edit that reply and assign parent topic id to it.

**Comment by buntybuddyboss** [comment]
Thanks
