### ISSUE TITLE
Roll back the Learndash courses version 1.6.5 design

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2472]
**Is your feature request related to a problem? Please describe.**
Roll back the ribbon wordings "Start Module" and "In Progress" instead of just "Enrolled" like the original style at version 1.6.5 including the course grid design

**Support ticket links**
https://secure.helpscout.net/conversation/1529057543/145068

**Comment by mikejyoung** [comment]
@Santos-Jamie the correct labels are used and no buttons are present in the latest versions of the BuddyBoss Theme and LearnDash. See the public demo: https://demos.buddyboss.com/online-communities/

There must be something on this customer's site creating the problems they explain.

Closing this issue.
