### ISSUE TITLE
Forums total topic count is not consistent

### ISSUE THREAD

**Issue by vajidbb** [buddyboss/buddyboss-platform#2473]
**Describe the bug**
Forums Topic count is not consistent for forums with spams topics

**To Reproduce**
1. Go to Forums with spams topics
2. Match the total topics count on platform: sites, app

**Expected behavior**
Total topic count should match across all platform

**Screenshots**
https://prntscr.com/14v34tf
http://prntscr.com/14uyh4z
http://prntscr.com/14uyl87

**Comment by meetmakadiya** [comment]
@vajidbb 
I checked on the platform and find out there is a counting issue when any **super sticky** topics there so on a single page of the forum counted but on the listing page not count so not maintain the consistency.
please check the video I found the patch but I need to discuss that.
https://www.loom.com/share/2622ee6e20144d2c92876062f85b03d5
