### ISSUE TITLE
MemberPress: Sync groups to transactions when deleted 

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#2475]
**Is your feature request related to a problem? Please describe.**
When a transaction deleted, a user still have an access or can  interact with specific group activity they joined.

**Describe the solution you'd like**
Add new feature that remove the access of the user from the group activity they 

Screen Recording: 
https://drive.google.com/file/d/1c1dj_9azmJdyY0zRYTTAfz-zFG3rBXzE/view

**Support ticket links**
https://secure.helpscout.net/conversation/1526717850/144620

**Comment by mikejyoung** [comment]
@jrbuddyboss 

This would be a feature request for MemberPress to build into their integration
https://memberpress.com/add-ons/buddypress/

Closing this issue.
