### ISSUE TITLE
Unable to see Hidden Forum in Forum Directory

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#2478]
**Describe the bug**
Hidden Forum description:
This forum is only visible to site admins and **members added** into the forum.
However, members of hidden group is unable to see the Forum in the Forum directory.

**To Reproduce**
Steps to reproduce the behavior: _Replicated in demo_
1. Create a Hidden Group
2. Enable Group discussion
3. Add non-admin members
4. Using admin, Hidden Group Forum is visible in the Forum Directory
5. Using non-admin (member of the group/forum) is unable to see the Hidden group forum in the Forum Directory

**Expected behavior**
Members of the hidden group should be able to see the Hidden Forum

**Screenshots**
https://prnt.sc/150c1dr
https://prnt.sc/150btqb
https://prnt.sc/150cbpy
https://www.loom.com/share/9c57645d55444cef8e2971d980ab5263

**Support ticket links**
https://secure.helpscout.net/conversation/1533908018/145920

**Jira issue** : [PROD-806]

[PROD-806]: https://buddyboss.atlassian.net/browse/PROD-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by milanhirapra** [comment]
@marilyn9425 The hidden/private group appear in the search results if they have created or they organizers.

CC: @KartikSuthar @chetansatasiya
