### ISSUE TITLE
On-Screen Notifications > WP-Admin Settings

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#2482]
### Scope

**Design**
https://sketch.cloud/s/5d225452-8a1d-4f2c-95da-0eb927818399

**Instruction Video**
https://www.loom.com/share/2eb07e341fef421c84de6ad12b47cdb4

Settings

On-Screen Notifications
- Enable on-screen notifications if checked

Position on Screen
- Set whether notifications are aligned to the bottom left or bttom right of screen

Mobile Support
- Select whether to show notifications on screens smaller than 500px.

Automatically Hide
- Select whether to automaticalyl hide notifications
- Use the options: Never Hide, After 1 minute, After 3 Minutes, After 5 Minutes, After 15 Minutes

Show in Browser Tab
- See here: https://github.com/buddyboss/buddyboss-platform/issues/2490

### QA Needed
Test cases to be written and posted here by the QA team. (@joshuamarkt)

### Associated Issues
https://github.com/buddyboss/buddyboss-platform/issues/2483

### ProductBoard URL
https://buddyboss.productboard.com/feature-board/2860318-features-in-progress/features/7678066/detail

---

**On-Screen Notifications Issues**
https://github.com/buddyboss/buddyboss-platform/issues/2482
https://github.com/buddyboss/buddyboss-platform/issues/2490
https://github.com/buddyboss/buddyboss-platform/issues/2483

**Comment by joshuamarkt** [comment]
Test Cases:
- Enable On-Screen notifications
- Disable On-Screen notifications
- Set the Notification position (test bottom left & bottom right)
- Enable Mobile Support for on-screen notifications
- Disable Mobile Support for on-screen notifications
- Set Automatically Hide (test all dropdown selections)
