### ISSUE TITLE
On-Screen Notifications

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#2483]
### Scope

**Design**
https://sketch.cloud/s/5d225452-8a1d-4f2c-95da-0eb927818399

**Instruction Video**
https://www.loom.com/share/2eb07e341fef421c84de6ad12b47cdb4

On-screen notifications show users new notifications received while they are on a page.

This is the first implementation of the feature using AJAX. We will extend it in the future by connecting it to a socket service for instant notifications without the need for continuous AJAX actions.

After the page loads, start running a check for new notifications every 30 seconds. 

Retrieve notifications that meet the following conditions:
- They are NOT marked as read
- They have been created in the previous 30 seconds

Show the retrieved notifications on the screen, matching the design in the Sketch file.

Notifications are ordered from most to least recent, top to bottom.

If there is more than one notification of the same type found, use the “multiple” format. (@sourabhmatolia to confirm if we can use this functionality)

Every 30 seconds, load new notifications created since the last check. If new notifications are found, remove the orange border from previously loaded notifications.

When a notification is closed, it swipes out to the side. The notifications underneath move up.

When there is more than one notification, the Close button shows.

When there are more than three notifications, show a hidden notification under the third notification.

Change the background color of the notification on hover.

Match the position of the notifications on the screen to the "Position on Screen" setting in the WP-Admin.

On screens smaller than 500px, use the small screen design. Only one notification every shows in this style. 
Disable notifications on small screens if "Mobile Support" is deactivated in the WP-Admin.

If the "Automatically Hide" settings is used in the WP-Admin, then remove notifications after the time set in the setting.

### QA Needed
Test cases to be written and posted here by the QA team. (@joshuamarkt)

### Associated Issues
https://github.com/buddyboss/buddyboss-platform/issues/2482

### ProductBoard URL
https://buddyboss.productboard.com/feature-board/2860318-features-in-progress/features/7678066/detail

---

**On-Screen Notifications Issues**
https://github.com/buddyboss/buddyboss-platform/issues/2482
https://github.com/buddyboss/buddyboss-platform/issues/2490
https://github.com/buddyboss/buddyboss-platform/issues/2483

**Comment by joshuamarkt** [comment]
Test Cases:
For Web: 
- Validate notification timing (30 seconds intervals)
- Validate notifications viewing order (from most to least)
- Validate notifications for multiple format
	* more than 1 notifications
	* more than 3 notifications
- Validate notifications for single format
- Validate notification positions (bottom left & bottom right)
- View notification details
- Close notification
- Clear All notifications
- Validate background color on hover function (on mouse pointer)
- Validate notification display on Time set in "Automatically Hide"

For Mobile:
- Validate notification timing (30 seconds intervals)
- Validate notifications viewing order (from most to least)
- Validate format for multiple notifications
- Validate format for single notification
- View notification details
- Close notification
- Clear All notifications
- Validate notification display on Time set in "Automatically Hide"

**Comment by sourabhmatolia** [comment]
@asaquzzamanbb 

Before proceeding with the task, Please check Notification Group logic as discussed below:
https://www.loom.com/share/abc57b9bd63645a0ad9c6c3d4781430e

Share your finding, discuss with me, and then proceed. Thanks.

**Comment by asaquzzamanbb** [comment]
@sourabhmatolia 

You have a grouping logic above you have mentioned. But the logic is not working. So i have created an issue for this. https://github.com/buddyboss/buddyboss-platform/issues/2505.

Until we solve the issue we have to show the same type notification separately.

**Comment by singhleo** [comment]
I see there is a lot of JS code added into BuddyBoss Theme PR. 

What my concern is.
1. If it's a feature in the platform all major JS should go into Platform Plugin Itself.
2. Theme should only have styling control. 


cc @sourabhmatolia @mikejyoung

**Comment by singhleo** [comment]
Another concern I see 

The major code I looked at is in theme .. which I think is not the correct approach .. instead, it should go into the platform and the theme should be doing minimal styling changes. 

@sourabhmatolia @mikejyoung @asaquzzamanbb

**Comment by mikejyoung** [comment]
@singhleo 
This is being done right now
