### ISSUE TITLE
Add to cart button not always displayed when using Elementor woocommerce products widget

### ISSUE THREAD

**Issue by anoykin** [buddyboss/buddyboss-platform#2486]
The Add to cart button is not always displayed when using the Elementor woocommerce products widget. Disabling all third party plugins except woocommerce and buddyboss platform doesn't help. In this regard, I tend to think that this is a bug.

Screenshots:
https://drive.google.com/file/d/1US8bXCyXQE_o2KUwF1MJRZKHC94fMuiZ/view?usp=sharing

https://drive.google.com/file/d/1tYjXhxtBEkfx-K9NKk5-Y35noAAkvzTH/view?usp=sharing

**Comment by anoykin** [comment]
FIX THIS PLEASE

**Comment by asadpalasara07** [comment]
@anoykin 

It's buddyboss-theme issue, a similar ticket created in a theme that I have worked on Fixes, You can track it here https://github.com/buddyboss/buddyboss-theme/issues/1255

**Comment by anoykin** [comment]
> @anoykin
> 
> It's buddyboss-theme issue, a similar ticket created in a theme that I have worked on Fixes, You can track it here [buddyboss/buddyboss-theme#1255](https://github.com/buddyboss/buddyboss-theme/issues/1255)

When i am click on link it writes to me "Didn’t find anything here!"

**Comment by imehedidev** [comment]
It's a theme issue buddyboss/buddyboss-theme#1255
