### ISSUE TITLE
On Photos tab - text & dropdown is overriding 

### ISSUE THREAD

**Issue by shashank-buddyboss** [buddyboss/buddyboss-platform#2488]
**Describe the bug**
After changing the tab https://prnt.sc/15citel from "Upload" to "Select Photo" and then change it back to "Upload", then the Dropdown and text are overriding 

**To Reproduce**
1. Go to 'Profile > Photos tab'
2. Click on 'Album > Select any album > Upload any image in the album'
3. After uploading an image, please change the tab  https://prnt.sc/15citel from "Upload" to "Select Photo" and "Select Photo" to "Upload" 
4. See error: https://prnt.sc/15cibpg

**Expected behavior**
Like: https://prnt.sc/15cjeka

**Screenshots**
https://prnt.sc/15cibpg

**Video**
https://www.loom.com/share/0e858a2747694a6180324c9c18556cd6

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Fixed >
A related issue is resolved and now the Dropdown and text are display properly for proof please check the below video.

Video:
https://www.loom.com/share/b7bce41c9f994798a6a6164c59f861ba

Ready for release 🚀 

Thank you
