### ISSUE TITLE
On-Screen Notifications > Show in Browser Tab Title

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#2490]
When the "Show in Browser Tab" setting (see here: https://github.com/buddyboss/buddyboss-platform/issues/2490) is active, we want to show information about new notifications in the header's <title> tag.

Add the number of unread notifications as such:
(1) [SITE_TITLE] - [TAGLINE]
e.g. (1) BuddyBoss - Create Your Own Online Communities

When a new on-screen notification is loaded into a page (see: https://github.com/buddyboss/buddyboss-platform/issues/2483), show the most recent in the title, such as:
[NOTIFICATION] - [SITE_TITLE] - [TAGLINE]
e.g. John mentioned you - BuddyBoss - Create Your Own Online Communities
The notification should flash.  See Facebook as an example of this functionality. 

---

**On-Screen Notifications Issues**
https://github.com/buddyboss/buddyboss-platform/issues/2482
https://github.com/buddyboss/buddyboss-platform/issues/2490
https://github.com/buddyboss/buddyboss-platform/issues/2483

**Comment by mikejyoung** [comment]
Needs QA test cases as well @joshuamarkt

**Comment by joshuamarkt** [comment]
Test Cases:

WP-Admin:
- Enable Show in Browser Tab
- Disable Show in Browser Tab

For Web:
- Validate unread notification count
- View Notification list
- Validate notifications viewing order (from most recent to least)
