### ISSUE TITLE
No notifications on blogpost comment reply

### ISSUE THREAD

**Issue by karlemilnikka** [buddyboss/buddyboss-platform#2502]
**Describe the bug**
When a user replies to a comment on a blogpost, the original commenter doesn’t receive a notification about the new comment. 

**To Reproduce**
1. Comment on a blogpost as Alice.
2. Sign in as Bob and reply to Alice’s comment.
3. Sign in as Alice and check if there are any new notifications. 

**Expected behavior**
Alice should get a notification, so she knows that Bob has replied (just as when Bob replies to a comment in the forums).

**Comment by mikejyoung** [comment]
Hi @karlemilnikka 

Mike, product manager from BuddyBoss here.

There isn't currently a notification setup for comments on blog posts, so this would be a feature request.

Please add any feature requests here:
https://www.buddyboss.com/roadmap

We're exploring extending the notification and I'll make sure to review this suggestion in our planning.
