### ISSUE TITLE
Course lesson Navigation buttons do not work.

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2503]
**Describe the bug**
If Learndash courses lesson not make a complete, then user not able to click on next lesson button

Admin's are not supposed to be restricted in terms of course navigation.

**To Reproduce**
1. Go to 'Leanrdash Courses'
2. Click on 'lessons'
3. if user not click on Make a complete button
4. they will not able to click on Next lesson button to see.

**Expected behavior**
User able to click on next lesson button, still if they are not click on Make a complete button

**Screenshots**
https://ibb.co/ysg9c2N
https://ibb.co/d4P62Fj
https://demos.buddyboss.com/online-communities/topic/quick-tip-number-scrubbing/

**Support ticket links**
https://secure.helpscout.net/conversation/1536222374/146348/

**Jira issue** : [PROD-803]

[PROD-803]: https://buddyboss.atlassian.net/browse/PROD-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kishanjasani** [comment]
@dipskakadiya Needs your suggestion here. Actually, it's not an issue in the platform, It's a theme issue.

To resolve this issue, Should I add all the required checks( like if conditions ) or should I change the structure of the `course-steps.php` file?
It will be better if we change the structure of the `course-steps.php` file. Because Our code will consistent with the learndash in the future.

**Comment by dipskakadiya** [comment]
@kishanjasani I think my suggestion is to change the structure of the course-steps.php. 
Can you add more details like what type of structural change is required to fix this? 

CC: @chetansatasiya @KartikSuthar I think you should check this too.

**Comment by bb-yudhisthir** [comment]
@shyamgudadhe Its not an issue, its working fine and is a default behavior
https://somup.com/crltex0Spt

When we have the course progression set as linear moving to next lesson will not work via next button and when we have course progression set as free form, navigation to next lesson will work

@dipskakadiya @kishanjasani
