### ISSUE TITLE
Notification grouping logic is not working.

### ISSUE THREAD

**Issue by asaquzzamanbb** [buddyboss/buddyboss-platform#2505]
**Describe the bug**
BuddyBoss same type notification grouping logic is not working. Also we have made the grouping logic here https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-notifications/classes/class-bp-notifications-notification.php#L1183. But it's not working.

**To Reproduce**
https://prnt.sc/15htepw

**Expected behavior**
We need to show the notification as a group for the same type notification.

**Screenshots**
https://prnt.sc/15htepw

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by mikejyoung** [comment]
@sourabhmatolia  @asaquzzamanbb 
Could you check on BuddyPress if they're making use of this grouping? 
Maybe they started it before we forked it and have completed it since.

**Comment by asaquzzamanbb** [comment]
@mikejyoung @sourabhmatolia 

I have already checked with BuddyPress updated code (https://github.com/buddypress/buddypress/blob/master/src/bp-notifications/classes/class-bp-notifications-notification.php#L1153), But it still shows mysql error.

Testing procedure,
1. error_log() the mysql query for notification grouping.
2. Run the query in Sequel Pro.
3. Showing error as output.

**Comment by mikejyoung** [comment]
I'm going to clos ethis issue.
We need to identify how we want grouped notifications to work then add it as a feature.
