### ISSUE TITLE
Message > Username disappear on click  

### ISSUE THREAD

**Issue by sumitbuddyboss** [buddyboss/buddyboss-platform#2509]
**Describe the bug**
Message > When we click on username then the username disappears.

**To Reproduce**
1. Go to 'Message'
2. Type username like 'John'
3. Click on 'user name'

**Expected behavior**
On click, the name should be edit and should not disappear.

**Screenshots**
https://www.loom.com/share/a2867b5a055a44d79f847049cea38258

**Comment by mahedihasannoman** [comment]
Hi @sumitbuddyboss , You need to click on the suggest list to select a user. If you click on outside of suggest list then suggest list and text will be disappeared. This is the default behaviour. So this is not a bug. Confirmed by @dipskakadiya as well.
