### ISSUE TITLE
BuddyCommerce PHP 7.4 bug

### ISSUE THREAD

**Issue by lukecolburn** [buddyboss/buddyboss-platform#2511]
**Describe the bug**
Siteground recently upgraded our site from PHP 7.3 to 7.4, and when they did we started getting 502 errors going to wp-admin and the following error from BuddyCommerce:

Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 40560697096 bytes) in /home/customer/www/public_html/wp-content/plugins/buddycommerce/src/admin/pt-settings/pt-settings-loader.php on line 122

When we switched back to 7.3, this issue went away. Siteground support tells me that the issue was caused by 'pt-settings-loader.php on line 112 is using a function which in 7.4 is saved as arrow function'

**To Reproduce**
1. Install the BuddyCommerce plugin
2. Configure the WordPress site to use PHP 7.4
3. Navigating to wp-admin will periodically result in 502 or memory exhaustion error

**Expected behavior**
No 502 or memory exhaustion errors when using this plugin

**Screenshots**
NA

**Support ticket links**
NA

**Comment by mikejyoung** [comment]
Hi @lukecolburn 
This BuddyCommerce plugin is created and maintained by another developer. 
It is best to bring directly to their attention as it is not something we can resolve directly.
