### ISSUE TITLE
Non admin members cannot post a Group Feed with multiple links gives error

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2518]
**Describe the bug**
Non admin members cannot post a Group Feed with multiple links gives error "There was a problem posting your update. Please try again."
whereas admin can post the same content

**To Reproduce**
1. Login as a member(non admin) 
2. Go to his Group > Feed
3. Add the content with the multiple links

Eg. 

SEO Tools

https://tools.pingdom.com

https://gtmetrix.com

https://developers.google.com/speed/pagespeed/insights

4. Try to post and see error

**Expected behavior**
It should work

**Screenshots**
![image](https://user-images.githubusercontent.com/80085922/122633542-c7f22700-d0f6-11eb-88aa-bc21c805017d.png)

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.
https://secure.helpscout.net/conversation/1545112646/148011

**Comment by Gabrymi93** [comment]
+1

**Comment by marienel21** [comment]
I can't reproduce this on demo

**Comment by bb-yudhisthir** [comment]
Its been reflected from the following settings ![image](https://user-images.githubusercontent.com/80085922/134115358-a9dce48d-a0de-4eca-b3e2-9a6c7364b750.png)

Closing this issue
