### ISSUE TITLE
BB Platform is not working with the WPML Multilingual CMS

### ISSUE THREAD

**Issue by milanhirapra** [buddyboss/buddyboss-platform#2520]
**Describe the bug**
Unable to set BB platform pages to multilingual.

**To Reproduce**
1. Go to BuddyBoss > Pages
2. Select Component pages for the default language
3. Select another language as the default language from the WPML setting page
4. Again Go to BuddyBoss > Pages and select Component pages for the new default language
5. Switch back to the previous language and can see all components pages are reset automatically

**Expected behavior**
Component pages must be saved for all languages like Members, Photos, Documents, Social groups

**Screenshots**
**Video (Backend):** https://www.loom.com/share/26424324980e44b6ab97f6ef79c778aa
**Video (Frontend):** https://www.loom.com/share/5bfc3b2044c54f4fbc4003e789a7300c

**Support ticket links**
https://secure.helpscout.net/conversation/1547766481/148414/

**Comment by mikejyoung** [comment]
Hi @milanhirapra,

WPML is not among our integrations list, so the compatibility may be limited:
https://www.buddyboss.com/integrations/

BuddyBoss has better compatibility with TranslatePress and LocoTranslate.

Please only create bug reports for "Official" integrations. For "Compatible" and "Third-Party" integrations, we direct the customer directly to those developers.
