### ISSUE TITLE
Compare member search queries to email addresses

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#2521]
### Scope
When searching for a member, compare the search query to member email addresses in addition to first names, last names and nicknames.  

This should be implemented globally wherever a member search box is present: members directory, connections, invite, private messages, etc

### Acceptance Criteria
- When searching for a member in a member search box, I should see results for any members whose first name, last name, nickname **and/or email address**, match my search query
- This logic should be followed globally in all member search boxes

### QA Needed
@joshuamarkt Please prepare QA test case for this

Jira: [PROD-799]

[PROD-799]: https://buddyboss.atlassian.net/browse/PROD-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joshuamarkt** [comment]
Test Cases:
Main Header: (News Feed / Members / Messages / Others)
- Search by First Name
- Search by Last Name
- Search by Nickname
- Search by Email Address
- Search by First Name and Email Address
- Search by Last Name and Email Address
- Search by Nickname and Email Address
