### ISSUE TITLE
Random 404 url and table not found issue in new release of buddy boss Platform

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2522]
### Describe the bug
Random 404 url and table not found issue in new release of buddy boss Platform

### To Reproduce
When user enable the Moderation module in Platform at that time database table missing  error will ours and that may be leads to random 4040 .

### Error log 

`[22-Jun-2021 13:05:06 UTC] WordPress database error Table 'learnartsintegrationcom.ms' doesn't exist for query SELECT id FROM  ms WHERE ms.item_id = 6664 AND ms.item_type = 'user' AND ms.reported = 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('after_setup_theme'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_builder_activate, FusionBuilder::get_instance, FusionBuilder->__construct, FusionBuilder->init, do_action('fusion_builder_before_init'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_element_login, fusion_builder_frontend_data, FusionSC_Login::get_element_extras, get_avatar, get_avatar_url, get_avatar_data, apply_filters('get_avatar_url'), WP_Hook->apply_filters, BP_Moderation_Members->get_avatar_url, bp_moderation_is_user_blocked, bp_moderation_report_exist, BP_Moderation->__construct, BP_Moderation::check_moderation_exist`

`[22-Jun-2021 07:50:42 UTC] WordPress database error Table 'learnartsintegrationcom.ms' doesn't exist for query SELECT id FROM  ms WHERE ms.item_id = 6664 AND ms.item_type = 'user' AND ms.reported = 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('after_setup_theme'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_builder_activate, FusionBuilder::get_instance, FusionBuilder->__construct, FusionBuilder->init, do_action('fusion_builder_before_init'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_element_login, fusion_builder_frontend_data, FusionSC_Login::get_element_extras, get_avatar, get_avatar_url, get_avatar_data, apply_filters('get_avatar_url'), WP_Hook->apply_filters, BP_Moderation_Members->get_avatar_url, bp_moderation_is_user_blocked, bp_moderation_report_exist, BP_Moderation->__construct, BP_Moderation::check_moderation_exist`

### Support ticket links
https://secure.helpscout.net/conversation/1540431750/147298/

**Comment by mikejyoung** [comment]
Hey @rmmehta 
Please use the "Report a bug" issue template when creating bug reports so the correct labels are applied :)

**Comment by rmmehta** [comment]
@mikejyoung , Sure next time I will take care of it.

**Comment by rmmehta** [comment]
Hello @janakkaneriya007  as We have further investigated this issue and found that the Database error occurred due Avada Builder.

As in the investigation we solved this table error ,

`[22-Jun-2021 13:05:06 UTC] WordPress database error Table 'learnartsintegrationcom.ms' doesn't exist for query SELECT id FROM ms WHERE ms.item_id = 6664 AND ms.item_type = 'user' AND ms.reported = 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('after_setup_theme'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_builder_activate, FusionBuilder::get_instance, FusionBuilder->__construct, FusionBuilder->init, do_action('fusion_builder_before_init'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_element_login, fusion_builder_frontend_data, FusionSC_Login::get_element_extras, get_avatar, get_avatar_url, get_avatar_data, apply_filters('get_avatar_url'), WP_Hook->apply_filters, BP_Moderation_Members->get_avatar_url, bp_moderation_is_user_blocked, bp_moderation_report_exist, BP_Moderation->__construct, BP_Moderation::check_moderation_exist`

By adding patch in the customer staging site then another table missing error is arises  as below:

`[28-Jun-2021 12:24:54 UTC] PHP Notice: Undefined property: BP_Moderation_Component::$table_name in /www/learnartsintegrationcom_936/public/wp-content/plugins/buddyboss-platform/bp-moderation/classes/class-bp-moderation.php on line 184
[28-Jun-2021 12:24:54 UTC] WordPress database error Table 'learnartsintegrationcom.ms' doesn't exist for query SELECT id FROM ms WHERE ms.item_id = 6664 AND ms.item_type = 'user' AND ms.reported = 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('after_setup_theme'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_builder_activate, FusionBuilder::get_instance, FusionBuilder->__construct, FusionBuilder->init, do_action('fusion_builder_before_init'), WP_Hook->do_action, WP_Hook->apply_filters, fusion_element_login, fusion_builder_frontend_data, FusionSC_Login::get_element_extras, get_avatar, get_avatar_url, get_avatar_data, apply_filters('get_avatar_url'), WP_Hook->apply_filters, BP_Moderation_Members->get_avatar_url, bp_moderation_is_user_blocked, bp_moderation_report_exist, BP_Moderation->__construct, BP_Moderation::check_moderation_exist`

if we deactivate the Avada Builder then the DB error is gone. the bp_suspended is there in the DB then also it fires the DB error.

I have replicated this issue in my dev site. So the random 404 occurs in the client site is due to Database error and the Database error arises because of the Avada Builder plugin.

**Comment by janakkaneriya007** [comment]
@sourabhmatolia Client has a conflict with Avada Builder with our moderation module. Should we look into this issue or just let the client know to contact third-party plugin support? Advice here.

**Comment by mikejyoung** [comment]
@janakkaneriya007 
@rmmehta 

This should be passed onto Avada by customer. I don't think it's something we need to fix. 

@sourabhmatolia please close issue if you agree.

**Comment by grahamhoffman** [comment]
Need an update on this - customer is now asking for refund since it's not compatible with every theme (Avada Builder is part of their Avada Theme).

**Comment by mikejyoung** [comment]
@sourabhmatolia 
I think in this case we should fix the conflict with Avada, even though it isn't an official integration. Could you assign a dev to scope how long it will take to resolve? We can make a final decision when we understand the effort.

**Comment by grahamhoffman** [comment]
Customer added a stripe dispute today.

**Comment by grahamhoffman** [comment]
Any confirmation here @sourabhmatolia ?

**Comment by sourabhmatolia** [comment]
@grahamhoffman 

@janakkaneriya007 is looking into this right now.
We will keep you posted. Thnx.
