### ISSUE TITLE
 Cannot suppress the admin bar through any method when the BuddyBoss platform is enabled.

### ISSUE THREAD

**Issue by bretweinraub** [buddyboss/buddyboss-platform#2527]
**Describe the bug**
Cannot suppress the admin bar through any method when the BuddyBoss platform is enabled.

Detected:

BuddyBoss Platform: Version 1.6.4
WP: 5.7.2

**To Reproduce**
1. Use any method you like to try and suppress the admin bar.

 - any plugin like "Hide Admin Bar by User Role", for example.
 
Or try it from code:

```

add_action('plugins_loaded', function() {
/* Disable WordPress Admin Bar for all users */
  remove_all_filters( 'show_admin_bar');
  add_filter( 'show_admin_bar', '__return_false' );
});

```

But if you disable the buddyboss platform, all normal methods work.

This also does not work:

https://www.buddyboss.com/how-to-remove-the-buddypress-admin-bar/

**Comment by mikejyoung** [comment]
Hi @bretweinraub 

Thanks for your report.

We've tried to validate this issue ourselves and have been unable to. As such, I'm going to close this ticket. 

It is likely a plugin conflict causing the problem, so please send a ticket to support and then can help you resolve.

**Comment by bretweinraub** [comment]
Hi @mikejyoung -

Can you confirm that https://www.buddyboss.com/how-to-remove-the-buddypress-admin-bar/ is the correct method?

**Comment by bretweinraub** [comment]
Hi @mikejyoung -

Based on your comments, we deactivated all of our plugins, and sure enough, your recipe works!   The culprit is a bit of a surprise:

"Advanced Custom Fields PRO"

If we have that enabled, then disabling via your documentation has no effect.

**Comment by mikejyoung** [comment]
Glad to hear you found the culprit!

**Comment by bretweinraub** [comment]
Yeah I will file a bug with ACF.   I know this plugin is very popular.

**Comment by bretweinraub** [comment]
https://wordpress.org/support/topic/buddyboss-acf-issues-with-admin-bar/#new-topic-0
