### ISSUE TITLE
Course Authors, Enrolled Members & Participants avatars not loading on course after recent platform update

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2528]
**Describe the bug**
Course Authors, Enrolled Members & Participants avatars not loading on course after recent platform update
**To Reproduce**
1. Update the platform plugin to latest (1.6.4)
2. Check the course page and check the participants, author and enrolled members avatars shows default one
3. Revert back to old platform plugin version (1.6.2 ), you can see the avatars again

**Expected behavior**
Avatars should be seen

**Screenshots**
![image](https://user-images.githubusercontent.com/80085922/123503902-8f60c900-d673-11eb-9a1a-c12059dd7949.png)
![image](https://user-images.githubusercontent.com/80085922/123503920-a69fb680-d673-11eb-94e8-dac344d274c1.png)
![image](https://user-images.githubusercontent.com/80085922/123503959-e1a1ea00-d673-11eb-8cd5-65b32d96f741.png)

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.
https://secure.helpscout.net/conversation/1554524498/149436

**Comment by bb-yudhisthir** [comment]
another ticket https://secure.helpscout.net/conversation/1553464479/149260/

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1553807161/149330/
This is happening with Elementor Author Box and Learndash.

![image](https://user-images.githubusercontent.com/80085922/123509141-7a932e00-d691-11eb-8c68-ae4444ce6b32.png)

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1553739121/149314/
This is happening with Elementor's Author Box

**Comment by anand-bb** [comment]
https://secure.helpscout.net/conversation/1555395890/149566?folderId=4312419

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1553650296/149290

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1554330842/149415/

**Comment by Nayeem-BB** [comment]
https://secure.helpscout.net/conversation/1555298694/149553/

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1560752758/150837/

**Comment by futureyoon** [comment]
+1

**Comment by hercivalbuddyboss** [comment]
https://secure.helpscout.net/conversation/1558109811/150092

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1557964189/150050/
https://secure.helpscout.net/conversation/1556639719/149773/
https://secure.helpscout.net/conversation/1558324284/150155/

**Comment by futureyoon** [comment]
Just wondering 1.7.0.1 release includes this fix?

**Comment by roshni07** [comment]
https://secure.helpscout.net/conversation/1566260151/152196?folderId=4687016

**Comment by allenbuddyboss24** [comment]
https://secure.helpscout.net/conversation/1563009124/151442?folderId=4588147

**Comment by fabiomail** [comment]
After installing to the latest buddyboss plugin version (1.6.4), the buddyboss user avatars URLs are not loaded internally from  https://guri.me/wp-content/uploads/avatars/ but externally from https://secure.gravatar.com/avatar/  

It's affecting almost all avatars in the platform (groups, forums, etc.), not just courses. 

In my case, the conflict seems to be with Dokan+WooCommerce plugins.

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1572696104/153619/

**Comment by anand-bb** [comment]
https://secure.helpscout.net/conversation/1574591678/154017/

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1575165365/154157/

**Comment by aclaoallen24** [comment]
https://secure.helpscout.net/conversation/1578562764/154772?folderId=4588147

**Comment by mightyx** [comment]
> https://secure.helpscout.net/conversation/1572696104/153619/

I added the code from this fix to my functions.php and the issue seems gone. Thank you!

**Comment by fabiomail** [comment]
> > https://secure.helpscout.net/conversation/1572696104/153619/
> 
> I added the code from this fix to my functions.php and the issue seems gone. Thank you!

Hi @mightyx could you share the code with us? Thanks!

**Comment by mightyx** [comment]
> > > https://secure.helpscout.net/conversation/1572696104/153619/
> > 
> > 
> > I added the code from this fix to my functions.php and the issue seems gone. Thank you!
> 
> Hi @mightyx could you share the code with us? Thanks!

I just copied it from here:
https://github.com/buddyboss/buddyboss-platform/pull/2627

**Comment by sourabhmatolia** [comment]
**UPDATE**

Issue mentioned above is released in BuddyBoss Platform v1.7.3

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-3/

Please update the plugin to see the latest changes.

Thank you.
