### ISSUE TITLE
Adding group members from the backend is not working in multisite setup

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#2529]
**To Reproduce**
1. Setup multisite with [BuddyPress Multisite Network](https://buddydev.com/plugins/buddypress-multi-network/) plugin
2. go to a subsite and create a group
3. try to add a group member
4. notice the error

**Screenshots**
![ss](https://user-images.githubusercontent.com/58522498/123535050-27ce7a80-d754-11eb-8382-64939a30f033.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1544463014/147899/

**Comment by meetmakadiya** [comment]
@ayron-paul I check with the **BuddyPress Multisite Network** plugin and the issue was replicated but the plugin is not included our official plugin support so we can't fix this for a particular plugin-related issue.
please find the details list here : https://www.buddyboss.com/integrations/

**Comment by ayron-paul** [comment]
Hi @meetmakadiya, you can close this one, as this can be also replicated with BuddyPress. Thus, an issue with the BuddyPress Multisite Network plugin itself. Thanks for checking

**Comment by ayron-paul** [comment]
Closing now.
