### ISSUE TITLE
Group Type Shortcode Won't Update

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2531]
**Describe the bug**
The shortcode in group type is not changing when the name of the type is updated making it confusing in assigning shortcodes.

**To Reproduce**
Steps to Reproduce: On the demo site go to BuddyBoss dashboard>Groups>Group Types>Add New>Add "test" as name>Publish>take note of the shortcode>Change the name to "test New">Publish and take note of the shortcode is still the same and not changed to the new name of the group type.

**Expected behavior**
it should be updated.

**Screenshots**
https://ibb.co/qg9WnPS
https://ibb.co/Js8rXxf

**Support ticket links**
https://secure.helpscout.net/conversation/1555446563/149573/

**Comment by kishanjasani** [comment]
@shyamwp14 We can't consider it as a bug. 
I don’t think it’s a bug, if the value changes then the slug should be changed. WordPress not updating the slug on post update. WordPress has metabox to update the slug.

Closing this issue. If you have some findings let me know we can reopen this again.
