### ISSUE TITLE
Network search does not work if forums are deleted

### ISSUE THREAD

**Issue by Shamina07** [buddyboss/buddyboss-platform#2535]
**Describe the bug**

Remove all the forum and search a member on the network search option, it does not work

**To Reproduce**

1. Search on network bar with the name of a user and you will get a result
2. Now remove all the forum and search again
3. No result will be shown

**Expected behavior**

The network search should not be dependent on the forum 

**Screenshots**

The user created a video on our demo site  
https://iqbox.cloud/index.php/s/p3EWSE3BfsYfHtQ

**Support ticket links**

https://secure.helpscout.net/conversation/1554338216/0/?folderId=4687016

**Comment by roshni07** [comment]
https://secure.helpscout.net/conversation/1555082967/0/?folderId=3709078

**Comment by anand-bb** [comment]
https://secure.helpscout.net/conversation/1553471898/149263/

**Comment by Shamina07** [comment]
https://secure.helpscout.net/conversation/1605336182/159471?folderId=4687016

**Comment by surajkrsingh** [comment]
Found a similar issue.
The issue is only happening when there is no forum and topic on the user site.
After debugging we found a SQL query broken because of an empty value list passing in `pm.meta_value IN`

https://secure.helpscout.net/conversation/1623124696/162652?folderId=3709082
