### ISSUE TITLE
Learndash wrong slug category on Single Course Page

### ISSUE THREAD

**Issue by Gabrymi93** [buddyboss/buddyboss-platform#2538]
**Describe the bug**
I've changed LD course slug into my website language, but on the course page, the category slug stay the standard "course" link, this of course brings to a 404 page.

**To Reproduce**
1. Change Learndash course permalink
2. Set a category for a course
3. Go to the course frontend page and hover on the category link above the course title
4. You'll see the classic LD permalink "course"

**Expected behavior**
Use the dynamic LD course permalink

**Screenshots**
![Screenshot (43)](https://user-images.githubusercontent.com/78922322/123930973-808a5700-d990-11eb-8664-fbeecd9d23db.png)

**Comment by manishpatolia** [comment]
@here 

This issue has already been resolved and created PR for it with Below, so I'm closing this one:

https://github.com/buddyboss/buddyboss-theme/issues/1515

**Comment by Gabrymi93** [comment]
@manishpatolia no it's not.... On course page the category slug is still wrong
![image](https://user-images.githubusercontent.com/78922322/126776861-a1e4d43a-b328-49f1-83a5-58ededf1e427.png)

It should be using the new LD permalink --> /corsi/?search=&filter-categories=fitterz

![image](https://user-images.githubusercontent.com/78922322/126776990-0830b0ef-139e-42c6-9f9a-4729105a7a83.png)
