### ISSUE TITLE
Subforum discussions are not showing in network search

### ISSUE THREAD

**Issue by surajkrsingh** [buddyboss/buddyboss-platform#2539]
**Describe the bug**
Subforum discussion is not displaying on search results. 
The fix was done on version 1.6.3 PR - https://github.com/buddyboss/buddyboss-platform/pull/2379 but still not working for the customer site. 

The issue is only happening on the customer site whereas, on the dev site is working fine.
We debugged the issue deeply and found the query written on the function **nested_child_forum_ids** is not returning the results correctly. I am also able to replicate the issue on my local site and Tested the query on the MySQL server, it returns the wrong forum child ids.
A possible issue is on a given fix that might not be covering all test cases.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login into the customer site with given details
2. Try to search any subforum discussion which is not associated with any group
4. You will see, it is not returning any result
5. Database server should be Mariadb version 10 in order to replicate this issue.

**Expected behaviour**
Subforum discussion should be displayed on network search results.

**Screenshots**
https://www.loom.com/share/6b1bd401212d44988bdda9a2622b18b5

**Support ticket links**
Customer issue - https://secure.helpscout.net/conversation/1553604833/149277?folderId=3709082
Reference issue - https://github.com/buddyboss/buddyboss-platform/issues/2306 

Jira: [PROD-794]

[PROD-794]: https://buddyboss.atlassian.net/browse/PROD-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mahedihasannoman** [comment]
Hi @surajkrsingh , I have gone through some testing but unable to replicate this issue with the latest buddyboss-platform plugin. Please see the video: https://www.loom.com/share/135bc142c4f74368892b6a9881cd4ccc
Can you please check on your end and confirm?

**Comment by fabiomail** [comment]
@mahedihasannoman I was one of the ppl who reported this issue back then. With the latest platform plugin version, the issue is still present, unfortunately. I just tested it again. Please, let me know if I can help in any way.

**Comment by mikejyoung** [comment]
@surajkrsingh 
I am closing this issue as we are not able to replicate it in our environment.

@imehedidev Please re-check this ticket in Tier 3 to identify what is causing the issue on the customer's environment. If the issue is coming from one of our products, create a new issue specifying the cause.

**Comment by mikejyoung** [comment]
CC @mahedihasannoman

**Comment by mahedihasannoman** [comment]
Issue persist. I can able to reproduce this issue. This is happening on database server type mariadb on version 10.
Please see this video for more clarification: https://www.loom.com/share/0588e839ef8742d0b12ae6a24507bff5

CC @mikejyoung @sourabhmatolia @surajkrsingh

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1639352380/165420
