### ISSUE TITLE
Group messages notification conflict with media uploading components

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#2540]
**Describe the bug**
When deactivating the media uploading components that time group message notification sent as a private message to members.

**To Reproduce**
1. Deactive the media uploading components.
2. Go to any hidden groups and sent messages to the group.  
3. Switch back to any member and check the notification.
4. See the error of notification showing like a private message.

**Expected behavior**
When sent message in the group that time always sent notification as a group message instead of a private message.

**Screenshots**
https://www.loom.com/share/58ef0ba0c37d462f82e6700f46527c04

**Support ticket links**
https://secure.helpscout.net/conversation/1550066536/148726/

Jira: [PROD-793]

[PROD-793]: https://buddyboss.atlassian.net/browse/PROD-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aprilgeller** [comment]
Retested on QA ongoing branch. 
Status: Already Fixed

Proof Video recording: https://watch.screencastify.com/v/so3OH3QleIm6xIiQ04Em

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1715167291/176920
