### ISSUE TITLE
widgets in the Blog Does not work

### ISSUE THREAD

**Issue by TW593** [buddyboss/buddyboss-platform#2541]
When we place some widgets in the sidebar, they go to the end of the blogs not to the right as it normally did, this error started to occur in the last update.

**To Reproduce**
1/ Install Buddyboss clean without modifying anything.
2/ Create a few blogs
3/ Go to widgets in WordPress
4/ Add 3 to widgets in blog sidebar
5/ Go to blog and see the error

Widgets are going to the end of the blogs and not to the right, damaging the web design, would appreciate some solution to this please thanks.

**Comment by roopeshbuddyboss** [comment]
Hi @TW593 ,

Using the latest WordPress version **Version 5.7.2**

Latest BuddyBoss Platform **Version 1.7.0.1**

Latest BuddyBoss Theme **Version: 1.7.0**

Was unable to reproduce the issue.

**Video Explanation:**
https://www.loom.com/share/7d6bad7b60ff4e70875892c7ca221cde

Can you please test with the latest version and if still, the issue persists please share the demo video.

Thanks
