### ISSUE TITLE
Notification not working for the updates/new discussions/replies even with the Forum & Forum Discussion Subscriptions

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2544]
**Describe the bug**
Notification not working for the updates/new discussions even with the Forum & Forum Discussion Subscriptions
Same issue in group forums

**To Reproduce**
1. Subscribe to the Forum (subscribe button) logged in as a member say A
2. Create a new Discussion in that forum from another account B
3. No notification to member A
4. Similarly, Subscribe to the Forum Discussion logged in as a member say A
5. Create a reply in that Discussion in that forum from another account B
6. No notification to member A

**Expected behavior**
Notification should appear

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.
https://secure.helpscout.net/conversation/1556308970/149698/

Jira: [PROD-791]

[PROD-791]: https://buddyboss.atlassian.net/browse/PROD-791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mikejyoung** [comment]
There are not currently any notifications setup for forum subscriptions, only emails. The only notification generated for forums is when a member receives a new reply to a discussion they’ve created.

I am closing this issue as the product is working as currently intended.

We are looking adding more notification types, but no eta as of yet.

**Comment by mikejyoung** [comment]
Note: This refers to **EMAIL** notifications, not the built-in notification system.

**Comment by janakkaneriya007** [comment]
@bb-yudhisthir 
I have checked this issue with the release branch. Refer to the video below: https://www.loom.com/share/d9ef3990fe324f1293adc7dc9c5e29c4

Let me know if I am missing anything.

**Comment by bb-yudhisthir** [comment]
@janakkaneriya007 As seen clearly in the video you are checking the other way (enabling the notification for the each replies on your reply ) and whereas I am talking about the notification to the subscribed member for that forum and discussion. You are not following the steps mentioned in the steps to reproduce section, please follow the steps mentioned

**Comment by janakkaneriya007** [comment]
@bb-yudhisthir 
Check the above video from 0 to 49 seconds where you get the email about the discussion is created to the subscribed forum and another email is about that someone replied to the discussion. If it's not the same thing you are talking share a video to reproduce the issue with the platform's latest version.
As @mikejyoung said we are talking about the email notification, not the web notification. Can you confirm?

**Comment by bb-yudhisthir** [comment]
@janakkaneriya007 here I mean is by "Subscribed" forum, any updates in the subscribed forums like new discussion created member who subscribed the forum should be getting the email 
CC: @mikejyoung
