### ISSUE TITLE
BuddyBoss causing site to resurrect deleted pages, cycle through themes and inactive plugins?

### ISSUE THREAD

**Issue by Nemi313** [buddyboss/buddyboss-platform#2552]
Hi I am using the BuddyBoss platform with BuddyX theme, I started having an issue with the registration button alternating between deleted registration pages, and that the correct registration page would show a previous version of the registration form with fields I deleted as well as showing a deactivated plugin's registration form. Different pages of the site would cycle through previously active themes. Once the issues had started, deactivating themes and plugins didn't resolve them, and clearing caches didn't help. I asked my hosting provider to wipe all the data for my site, and I reinstalled BuddyBoss with BuddyX. This seemed to fix the problems at first, but I went to the BuddyBoss settings and created a second registration page and the issues started again, and my site even brought up a theme I hadn't reinstalled after the data was wiped. Do you please have any ideas what could be causing this? Is this a bug with the BuddyBoss platform caused by creating registration pages? Is it a conflict with BuddyX?

**Comment by mikejyoung** [comment]
Hi @Nemi313 
I can't replicate this issue on our end, so it could be an issue with the BuddyX theme. I haven't seen any other reports of this issue either, so I'm going to close this ticket.
