### ISSUE TITLE
Video - Safari Browser popup video not playing

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#2553]
**Describe the bug**
When you open a video in popup and symlink is enabled then the video is not playing in safari.

**To Reproduce**
1. Go to Activity OR Video pages in a group, user profile, and directory page
2. Open a video in the popup it's not playing.

**Expected behavior**
VIdeo Should play in popup in safari to

**Screenshots**

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by ThemeMetro** [comment]
One issue also getting in Safari unable to upload video too, please check.

**Comment by chetansatasiya** [comment]
> One issue also getting in Safari unable to upload video too, please check.

Which place you are not able to upload video?

**Comment by ThemeMetro** [comment]
> > One issue also getting in Safari unable to upload video too, please check.
> 
> @ThemeMetro Which place you are not able to upload video?

From Activity post

**Comment by chetansatasiya** [comment]
> > > One issue also getting in Safari unable to upload video too, please check.
> > 
> > 
> > @ThemeMetro Which place you are not able to upload video?
> 
> From Activity post

@ThemeMetro I just tested on the video in Safari browser it's working fine without any issues see here for more info https://www.loom.com/share/fb8e208a3e414eb9b45fc59b3cea658b?from_recorder=1&focus_title=1

**Comment by ThemeMetro** [comment]
> > > > One issue also getting in Safari unable to upload video too, please check.
> > > 
> > > 
> > > @ThemeMetro Which place you are not able to upload video?
> > 
> > 
> > From Activity post
> 
> @ThemeMetro I just tested on the video in Safari browser it's working fine without any issues see here for more info https://www.loom.com/share/fb8e208a3e414eb9b45fc59b3cea658b?from_recorder=1&focus_title=1

The issue coming in ios 14.x in iPhone 10XR

**Comment by sourabhmatolia** [comment]
**UPDATE**

Reopened this issue as we have applied a partial patch in the released PR.
This needs to be fixed properly.

**Comment by sourabhmatolia** [comment]
@ThemeMetro 

Issue mentioned above is released in BuddyBoss Platform v1.7.2

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-2/

Please update the plugin to see the latest changes.

Thank you.
