### ISSUE TITLE
On activation handling for Performance API.

### ISSUE THREAD

**Issue by singhleo** [buddyboss/buddyboss-platform#2555]
**Describe the bug**
We need to handle on activate function of performance API in in platform. so performance code can work for none buddyboss app holders.

@jitendrabanjara1991 explain it more, please in detail.

**To Reproduce**
N/A

**Expected behavior**
Performance should work without buddyboss app.

**Screenshots**
N/A

**Environment**
N/A

**Support ticket links**
N/A

Jira: [PROD-789]

[PROD-789]: https://buddyboss.atlassian.net/browse/PROD-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by singhleo** [comment]
after we finish we need to test it with buddyboss app so we can avoid any further conflicts.

**Comment by jitendrabanjara1991** [comment]
When we activate the **BuddyBoss Platfrom** plugin only,  not activate **BuddyBoss App**, At that time **bb_performance_cache** table is not creating in DB.
