### ISSUE TITLE
WP_Offload Plugin_ If "Remove files from server" setting is enabled then PDF previews are not appearing.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#2560]
**Describe the bug**
PDF preview when using WP Offload Media and the setting "Remove Files From Server" is enabled. When they set the setting "Remove Files From Server" to ON, the preview doesn't work. If they disable this setting, the preview is working fine.

**To Reproduce**
1. Go to 'WP offload settings'
2. Enable "Remove files from server" 
3. Upload PDF

**Expected behavior**
PDF preview must appear.

**Screenshots**
https://www.loom.com/share/6cbc5ed35a85447dbb4c05705da0dc56

**Environment**
https://platform-testing.flywheelsites.com/

**Support ticket links**
https://secure.helpscout.net/conversation/1542554997/147641/

**Comment by sourabhmatolia** [comment]
Cross Check issue with this PR:
https://github.com/buddyboss/buddyboss-platform/pull/2551

**Comment by mohit-buddyboss** [comment]
@chetansatasiya Cross checked with the PR #2551. Issue is exist on this branch also.  
It is not affecting older documents. But if the setting "Remove Files From Server" is 'enabled' or set to 'ON'. Then for new uploaded PDF files preview is not appearing. 

cc @sourabhmatolia

**Comment by ExoGeek** [comment]
I do have the same issue...

**Comment by KindHarvestAgDeveloper** [comment]
The same issue exists for other s3 offload plugins such as Media Folder Cloud.
There are other issues related to that plugin as well  - it does not correctly provide file size details from S3 back to buddyboss resulting in other document previews also failing.

**Comment by KindHarvestAgDeveloper** [comment]
The core of many of theses issues appears to be a that buddyboss uses native file access requests inside php such as is_file() which are not being correctly mapped by the s3 plugin to a php file provider

**Comment by KindHarvestAgDeveloper** [comment]
it seems like it is past time that buddyboss provided its own cloud provider module instead of relying on 3rd party options - especially now that the app is live

**Comment by chetansatasiya** [comment]
@mohit-buddyboss @ExoGeek @KindHarvestAgDeveloper See here https://www.loom.com/share/4a07f632e3a84a4d81fe1e6ead46882e I am not facing any issues on this. Can you guys share the video of how you guys are checking and what configuration you have?

**Comment by ExoGeek** [comment]
Plugin version : 
![image](https://user-images.githubusercontent.com/46819762/124610777-13376400-de71-11eb-9676-e2360fc0771a.png)

Configuration : 
![Screenshot 2021-07-06 at 15-33-16 Offload Media ‹ Pictoflash Staging — WordPress](https://user-images.githubusercontent.com/46819762/124610809-1a5e7200-de71-11eb-8eba-2cda27136b68.png)

Result with Remove = ON (no preview) and OFF (preview ok).
![image](https://user-images.githubusercontent.com/46819762/124610571-ed11c400-de70-11eb-8d2d-2267eb3d98c6.png)

**Comment by ExoGeek** [comment]
@chetansatasiya For your test, could you check that the PDF is correctly removed from the directory "\wp-content\uploads\bb_documents\2021\07" ?

I've just tested the case with Dilevery Provider = S3 and it appears that the PDF file is not correctly removed from server. That's why your test is working well (we can see the preview). But with my config (cloudfront + signed URL), the pdf is removed from the local server.

**Comment by welshlamb10** [comment]
Hi @ExoGeek @mohit-buddyboss,

I'm having similar issues with WP Offload. Although I cant upload any images or video with the latest update. 
The images get 403 errors. Is yours working?

**Comment by ExoGeek** [comment]
@welshlamb10 BuddyBoss fully supports WP Offload Media Plugin. They support the plugin pretty well (excepts some bugs that are currently investigated). 

If you receive 403 errors, I suggest you check AWS configuration (if needed, you should contact the support of Delicious Brain. They are excellent too)

**Comment by chetansatasiya** [comment]
> Plugin version :
> ![image](https://user-images.githubusercontent.com/46819762/124610777-13376400-de71-11eb-9676-e2360fc0771a.png)
> 
> Configuration :
> ![Screenshot 2021-07-06 at 15-33-16 Offload Media ‹ Pictoflash Staging — WordPress](https://user-images.githubusercontent.com/46819762/124610809-1a5e7200-de71-11eb-8eba-2cda27136b68.png)
> 
> Result with Remove = ON (no preview) and OFF (preview ok).
> ![image](https://user-images.githubusercontent.com/46819762/124610571-ed11c400-de70-11eb-8d2d-2267eb3d98c6.png)

@ExoGeek If possible can you create a support ticket and give us your staging server credentials with the FTP details so we can take a look on your staging server and find the cause?

**Comment by chetansatasiya** [comment]
@ExoGeek Can you check with this PR https://github.com/buddyboss/buddyboss-platform/pull/2591 like it's now working or not?

**Comment by chetansatasiya** [comment]
@ExoGeek I tested my patch to your staging server that you mentioned in your support ticket with us. Now preview is working fine with the **Remove File From Server** option as well.

**Comment by ExoGeek** [comment]
@chetansatasiya I've just tested on my dev site and **it works**. Thanks !

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

VERIFIED : Issue fixed through the PR: https://github.com/buddyboss/buddyboss-platform/pull/2591
https://github.com/buddyboss/buddyboss-platform/pull/2591#issuecomment-880431336
