### ISSUE TITLE
Photo page media disappear after Buddyboss platform plugin updates

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2561]
**Describe the bug**
After updated the BuddyBoss plugin to the latest version but it immediately deleted all user uploaded media (both in the community and in Media bin in the dashboard)

**To Reproduce**
1. Go to 'plugin page, updates Buddyboss platform plugin to  Version 1.7.0
2. then go to Member profile photo page
https://dev-shyam.flywheelsites.com/members/shyam1/photos/
3. See error all photo disappear.

**Expected behavior**
After Buddyboss platform plugin to  Version 1.7.0 updates, it should not disappear
**Screenshots**
https://ibb.co/ZfTxkMg

**Environment**
Dev site:
https://dev-shyam.flywheelsites.com/members/shyam1/photos/

**Support ticket links**
https://secure.helpscout.net/conversation/1561435784/151007?folderId=4265312

**Comment by futureyoon** [comment]
+1

**Comment by shyamwp14** [comment]
Previously, when we created this issue, we were able to reprodcued this issue including my dev site. Now on the latest updates, its working fine.
