### ISSUE TITLE
bb-platform-previews links not correctly built on Multisite networks

### ISSUE THREAD

**Issue by DanWin** [buddyboss/buddyboss-platform#2565]
**Describe the bug**
Since the update to 1.7.0 we have an issue that our buddyboss is generating Links like these: `/wp-content/uploads/sites/1/sites/1/bb-platform-previews/....` (Note the double `sites/1/`)

**To Reproduce**
1. Install Buddyboss in a multi-network setup
2. Upload several photos
3. View activity feed and have missing photos due to invalid links

**Expected behavior**
Links should be correctly generated 

**Screenshots**
![image](https://user-images.githubusercontent.com/3327912/124458701-941d2f80-dd8d-11eb-9979-fdbde7115026.png)

**Environment**
https://trainingsplattform.beinternett.de/

Jira: [PROD-787]

[PROD-787]: https://buddyboss.atlassian.net/browse/PROD-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by suprcb** [comment]
same problem here after update to 1.7.0.x , works in 1.6.3 but same problem in normal installation (not multisite) after update to 1.7.0.x (if downgrade to 1.6.3 works again) but in 1.7.0.x bb-platform-previews generate 404 error
