### ISSUE TITLE
Image on activity feeds looks very blurry on web & App

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2567]
**Describe the bug**
Image on activity feed looks very blurry on web & App.  It is happening after latest platform update. The issue is also happening in App as well. Please see the video at below link. Please note the link is restricted and can be access using buddyboss.com email.
https://www.loom.com/share/12d77bcf82f7428ea28fa2c67693ef35
https://docs.google.com/document/d/13S9CzVNciKou-uCLPzgRHdvwQWQSrlFQAqKDGLhVKXk/edit?usp=sharing

**To Reproduce**
1. See the video

**Environment**
Tested on client site.

**Support ticket links**
https://secure.helpscout.net/conversation/1559810023/150558?folderId=4314898

**Comment by ExoGeek** [comment]
I totally agree with the issue.

I would like to add that when images are uploaded from the BuddyBoss App, the image size is 1200px (max). With that image resolution, images are also blurry on website. I think you should add a parameter (in wordpress admin) to set up max image size (when uploaded from the app).
