### ISSUE TITLE
Download video doesn't work when the media url contains "?" (signed url) 

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#2572]
**Describe the bug**
When using signed url, we can't download video file.

Linked issue : https://github.com/buddyboss/buddyboss-platform/issues/1560

**To Reproduce**
1. Use WP Offload (signed URL)
2. Upload video to activity feed
3. Fullscreen video
4. Clic on "Download" (on bottom right)

**Expected behavior**
We should be able to download video file even with signed url.

**Screenshots**
![download_video](https://user-images.githubusercontent.com/46819762/124514474-665fd700-dddd-11eb-91ca-c530f329d59a.JPG)

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by sourabhmatolia** [comment]
@ExoGeek

Issue mentioned above is released in BuddyBoss Platform v1.7.0.1

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-0-1/

Please update the plugin to see the latest changes.

Thank you.
