### ISSUE TITLE
Reply submission stuck on Forum discussion  with pagination with wordpress 5.5.3

### ISSUE THREAD

**Issue by hercivalbuddyboss** [buddyboss/buddyboss-platform#2578]
**Describe the bug**
if you create a reply on a discussion with pagination, the reply is successfully submitted but it does not redirect and hang

**To Reproduce**
1. Downgrade the wordpress version to 5.5.3
2. Create a discussion that has more enough to have a pagination
3. create a reply on the discussion then submit
4. ajax submission is successful but failed to redirect

**Expected behavior**
if you create a reply on a discussion with pagination, the reply is successfully submitted but it does not redirect and hang

**Screenshots**
[https://www.loom.com/share/721f40f968a94c0fab5aa110aaef64e0 ](https://www.loom.com/share/721f40f968a94c0fab5aa110aaef64e0 )

**Environment**
Which site did you replicate this issue on?
Client live site and my localhost

**NOTE**
Issue with WordPress core version is 5.5.3. BuddyBoss claims to support WordPress version 4.9.1 or greater

**Support ticket links**
[https://secure.helpscout.net/conversation/1551043590/148888](https://secure.helpscout.net/conversation/1551043590/148888)

**Comment by milanhirapra** [comment]
This issue is in theme: https://github.com/buddyboss/buddyboss-theme/issues/1629
