### ISSUE TITLE
WordPress 8.0 Compatibility CHECK

### ISSUE THREAD

**Issue by sourabhmatolia** [buddyboss/buddyboss-platform#2586]
Check Platform compatibility with WordPress v5.8

All features: https://wordpress.org/news/2021/07/the-month-in-wordpress-june-2021/
Theme.json  : https://make.wordpress.org/test/2021/06/24/call-for-testing-thrive-with-theme-json/

IF we see issues specific to WP 8.0 then please note all issues here for someone to fix.

### Connected Issue in Platform Pro
https://github.com/buddyboss/buddyboss-platform-pro/issues/178

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

**Issue -1**
As per the new WordPress update now we can set our block as a widget so I've added our zoom meeting and zoom webinar as a widget, So the design is break and looks weird on the front side and backend side, for more detail please check below issue video.

https://www.loom.com/share/8a16e571e53a431b9ad865513980b354

Note: Testing is still ongoing, We'll add a new bug here.

cc @sourabhmatolia

**Comment by amincdev** [comment]
@sumitbuddyboss Test Issue - 1 first issue in Platform-pro PR: https://github.com/buddyboss/buddyboss-platform-pro/pull/179

**Comment by sadrul** [comment]
@sumitbuddyboss I did not find any new bugs, please proceed on testing the PR

**Comment by sumitbuddyboss** [comment]
Both the issue is resolved
https://github.com/buddyboss/buddyboss-platform-pro/pull/179
https://github.com/buddyboss/buddyboss-platform/pull/2607

Ready to release 🚀 

cc @sourabhmatolia
