### ISSUE TITLE
problem version 1.7.0.x (user can't add images in buddyboss posts)

### ISSUE THREAD

**Issue by suprcb** [buddyboss/buddyboss-platform#2588]
We install platform 1.6.3 and works but after update to 1.7.0 users can't upload images in his buddyboss posts, display a 404 error, if we downgrade to 1.6.3 works again, but if we install 1.7.0 or 1.7.0.1 again display error 404 in images (we restore permalink an don't resolve the problem)

Please any idea to help?
Thanks

**Comment by jakir-git** [comment]
https://secure.helpscout.net/conversation/1563451317/151546?folderId=3955985

**Comment by jakir-git** [comment]
https://secure.helpscout.net/conversation/1561400413/150996?folderId=3955985

**Comment by suprcb** [comment]
> https://secure.helpscout.net/conversation/1563451317/151546?folderId=3955985

How we can access to this helpscout?

**Comment by suprcb** [comment]
Any idea to solve this? Problem continues

**Comment by futureyoon** [comment]
+1

**Comment by marienel21** [comment]
Issue no longer reproducible in the latest version of the product.

**Comment by meetmakadiya** [comment]
@suprcb @jakir-git @futureyoon 
check with the latest version (1.7.6) issue is not replicated so might be fixed on the latest version.
