### ISSUE TITLE
Issue with Facet Location search box

### ISSUE THREAD

**Issue by ashishbrst** [buddyboss/buddyboss-platform#2589]
Facet location search box is not working with Buddyboss theme. It works with other themes but as soon I activate Budyboss theme then it creates problem. It shows for a second during page load and then removes. 

It is because budyboss theme builder changes the HTML of facet search box which leads to the issue. This is what the output should look like (via our State Parks demo, latest FWP version): https://d.pr/i/OTJMKu

And this is the output from your site: https://d.pr/i/0w48vv

**Comment by bb-yudhisthir** [comment]
@ashishbrst Can you create the support ticket with us from your BuddyBoss account and will check it for you?
And please also send the FacetWP plugin and other details like steps to replicate/screen recording of the issue

**Comment by bb-yudhisthir** [comment]
@ashishbrst Closing this issue, can reach us to our support with the support ticket
