### ISSUE TITLE
Comment is not working on activity posts on group

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#2596]
**Describe the bug**
Comment is not working on activities posted inside group if activity option **Allow members to edit their activity posts for a duration of** is disabled.

**To Reproduce**
1. Make sure Settings > Activity >  **Allow members to edit their activity posts for a duration of** is disabled.
2. Comment on any activities posted in group.
3. You will see that it would not work.

**Expected behavior**
Comment button should work as expected.

**Screenshots**
https://www.loom.com/share/3639acc704174f6d9a8d1fe2a8e0bf8a

**Environment**
Which site did you replicate this issue on? Graham's dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1565439177/152006

**Comment by kent-carlo** [comment]
https://secure.helpscout.net/conversation/1566812452/152352/

**Comment by shyamwp14** [comment]
https://secure.helpscout.net/conversation/1561616741/151072

**Comment by anand-bb** [comment]
https://secure.helpscout.net/conversation/1568113581/152697/

**Comment by chetansatasiya** [comment]
https://secure.helpscout.net/conversation/1563456544/151548/

**Comment by roshni07** [comment]
https://secure.helpscout.net/conversation/1567555704/152527?folderId=4687016
