### ISSUE TITLE
Mp3 file plays fine on activity but on the group it does not play

### ISSUE THREAD

**Issue by Shamina07** [buddyboss/buddyboss-platform#2603]
**Describe the bug**

Mp3 file plays fine if you upload on activity but on the group it does not play. 

**To Reproduce**
1.Upload mp3 file on activity
2. Upload mp3 file on a group
3. The mp3 file plays on activity but not on groups

**Expected behavior**

It should play on groups as well

**Video**

 https://share.vidyard.com/watch/n2n2fiAZMe7S59mM3WC7As?

**Environment**

Demo
Development environment
Client site

**Support ticket links**

https://secure.helpscout.net/conversation/1561104435/150923/

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 
Issue not getting resolve through PR : https://github.com/buddyboss/buddyboss-platform/pull/2591
https://github.com/buddyboss/buddyboss-platform/pull/2591#issuecomment-880408102

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

FIXED> Issue not getting resolve through PR : #2591
https://github.com/buddyboss/buddyboss-platform/pull/2591#issuecomment-880704210
