### ISSUE TITLE
File Upload Tool>Create Folder Broken

### ISSUE THREAD

**Issue by chrisdubia** [buddyboss/buddyboss-platform#2604]
File Upload tool is no longer working.

To replicate the issue, login to a group>go to Our files.  Either upload a file or create a folder.  The wheel will continue to spin- nothing will happen.

Also, when you visit OUR Files, you will see the message Requesting the Group Documents.  Please wait.. 

THIS IS EXTREMELY URGENT.

We have tested this on three staging servers and our live site. Same issue happens.  Have disabled all plugins and same issue happens.

Adding files to the activity feed on the homepage works and under discussion and replying to topic.  Not useful though, as we need to be able to organize files, permissions, etc

Here is a video: https://vimeo.com/574183968/9af92732ca

**Comment by chetansatasiya** [comment]
@chrisdubia We just tested on our end there are no issues we are seeing at this moment. However, I am seeing in your video there are issues like it's also showing you a privacy box in a popup. So could you please create a support ticket so our support team will help you and figure out the issue?
