### ISSUE TITLE
WPEngine - Media, Document & Video not displaying via php file

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#2611]
**Describe the bug**
WPEngine disabled the `symlink` function so we have to show the media via PHP but it still not showing the proper image or video.

**Expected behavior**
Media, Document & Video should display.

**Screenshots**

**Environment**
Live & Staging

**Support ticket links**
https://secure.helpscout.net/conversation/1554099952/149381/

**Comment by mohit-buddyboss** [comment]
FIXED through PR: https://github.com/buddyboss/buddyboss-platform/pull/2591
