### ISSUE TITLE
Group Description html encoding

### ISSUE THREAD

**Issue by vajidbb** [buddyboss/buddyboss-platform#2615]
**Describe the bug**
Updating group description with HTML content encodes the content

**To Reproduce**
1. Go to Group Manage Screen
2. Update Group Desc with HTML content
3. Go to activity feeds screen

**Expected behavior**
HTML content should be encoded and decoded properly while view

**Screenshots**
https://www.loom.com/share/8844621c775b4ed3ab3b612c8687a51d

**Environment**
https://bb-app-platform.flywheelsites.com/

**APP ISSUE**
https://github.com/buddyboss/buddyboss-app-native/issues/1334

**Comment by sourabhmatolia** [comment]
@krunal-buddyboss 

Please confirm with Chetan or Kartik and then start with this task.
We are allowing to add all kinds of Text formatting in the backend Group Edit screen.
Things are not working properly in Frontend.
