### ISSUE TITLE
Updating learndash group alters privacy settings on buddyboss group

### ISSUE THREAD

**Issue by kishanjasani** [buddyboss/buddyboss-platform#2618]
**Describe the bug**
Adding or removing users in a LearnDash group, the associated hidden group becomes a private group.

**To Reproduce**
1. Make sure that Social Group Sync and LearnDash Group Sync are enabled. Please see https://i.ibb.co/4VcQzhs/p1.png.
2. Create a Hidden Social Group
3. Create a LearnDash Group and associate it to the Social group you just created. https://i.ibb.co/HKsY8cD/p2.png
4. Try to add some users to the LearnDash group. https://i.ibb.co/7KRKhvG/p3.png
5. Now go to the Social Group and notice that it is now Private instead of Hidden.

Able to replicate it on local and dev sites.

**Note:**
It works fine when the Social Group Sync is disabled. For reference, please see https://i.ibb.co/bQVq3Gx/p5.png

**Screenshots**
https://drive.google.com/file/d/1VvnPHSs1CUjo-ITTwHbxkEAn4ShA5NyL/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1570672169/153215/

**Jira issue** : [PROD-784]

[PROD-784]: https://buddyboss.atlassian.net/browse/PROD-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Gabrymi93** [comment]
+1 it changes the group privacy on every LD group update, not only upon creation.
![image](https://user-images.githubusercontent.com/78922322/126224645-e72ed6f4-ac6e-4f33-9c41-424b2ba7191d.png)

**Comment by mahedihasannoman** [comment]
Hi @kishanjasani Seems like this is not a bug. We do have an option to set the Social Group Privacy during synchronization from BuddyBoss > Integration > LearnDash page. See the screenshot: https://nimb.ws/q8lsCa
If you set it to hidden then social group will be hidden and so on.

**Comment by mahedihasannoman** [comment]
Closed after getting confirmation from @kishanjasani .

**Comment by ayron-paul** [comment]
Hi @mahedihasannoman @kishanjasani, the issue still persists. The setting on the BuddyBoss Platform only indicates that it is applicable as the default upon creation and not for the existing groups.

<img width="682" alt="chrome_J1gBHPJqHK" src="https://user-images.githubusercontent.com/58522498/133335987-8eb70ce6-931b-45f1-851f-9536a860dd4e.png">

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1677569824/171102/
