### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#2620]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

On using https://github.com/buddyboss/buddyboss-theme/pull/1519 branch of the theme with platform master branch. 
And if forum component is disabled then News feed is not getting load and getting PHP fatal error :

`16-Jul-2021 05:37:39 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function bbp_user_can_view_forum() in C:\laragon\www\mohitktest2\wp-content\plugins\buddyboss-platform\src\bp-media\bp-media-functions.php:3790
Stack trace:
#0 C:\laragon\www\mohitktest2\wp-content\plugins\buddyboss-platform\src\bp-templates\bp-nouveau\buddypress\document\activity-entry.php(17): bb_media_user_can_access(503, 'document')
#1 C:\laragon\www\mohitktest2\wp-includes\template.php(732): require('C:\\laragon\\www\\...')
#2 C:\laragon\www\mohitktest2\wp-content\plugins\buddyboss-platform\src\bp-core\bp-core-template-loader.php(163): load_template('C:\\laragon\\www\\...', false)
#3 C:\laragon\www\mohitktest2\wp-content\plugins\buddyboss-platform\src\bp-core\bp-core-template-loader.php(60): bp_locate_template(Array, true, false)
#4 C:\laragon\www\mohitktest2\wp-content\plugins\buddyboss-platform\src\bp-document\bp-document-filters.php(167): bp_get_template_part('document/activi...')
#5 C:\laragon\www\mohitktest2\wp-includes\class-wp-hook.php(292): bp_document_activity_e in C:\laragon\www\mohitktest2\wp-content\plugins\buddyboss-platform\src\bp-media\bp-media-functions.php on line 3790`

@KartikSuthar
