### ISSUE TITLE
The publication of a new post will not appear as an Activity

### ISSUE THREAD

**Issue by AndresPerezfc** [buddyboss/buddyboss-platform#2631]
Today I updated the Buddyboss Platform plugin, and from that moment the publication of a new post does not appear in the Site Activity

I have the correct configuration marked

1. Publish a new blog post
2. Go to the latest user activity updates

**Screenshots**
https://ibb.co/HX4624P

**Comment by mikejyoung** [comment]
Hi @AndresPerezfc 

This is not something we can replicate ourselves.

We would need our support team to review your specific setup to look for conflicts from one of your plugins or your hosting environment. Please create a support ticket in your BuddyBoss account.

In the meanwhile, I am going to close this ticket. Our support team will create a new issue if a product bug is found.
