### ISSUE TITLE
URGENT!!! Dokan disable privacity Buddyboss Platform

### ISSUE THREAD

**Issue by Felipemauah** [buddyboss/buddyboss-platform#2637]
**Describe the bug**
When I install the Dokan Marketplace plugin it simply disables the site's privacy. Just install Dokan and it disables all privacy on the site and even if you delete the plugin the privacy doesn't work again!

**To Reproduce**
1. Install Dokan
2. Open site like unlogged user and you see all content

**Comment by mikejyoung** [comment]
Hi @Felipemauah 

Dokan Marketplace is not one of listed integrations: https://www.buddyboss.com/integrations/

Typically, we only resolve conflicts for integrations listed as "Official", but sometimes we will also for those listed as "Third-Party" or "Compatible". 

I've made a note to review this plugin in the future when we are adding more to our Integrations list.

For the time being, I am going to close this issue as it is not within our current scope of development.
