### ISSUE TITLE
Discussion reply activity showing only empty border no content in activity pages.

### ISSUE THREAD

**Issue by asaquzzamanbb** [buddyboss/buddyboss-platform#2640]
**Describe the bug**
In the activity pages when you have media data but no content for reply activity then it will show the empty border.
 
**To Reproduce**
1. Create discussion.
2. Create reply according the discussion with media data and no content (text).
3. Disabled the forum from the back-end settings.
4. Navigate the activity page.
5. Now you get the discussion reply activity with only empty border no content. 

**Expected behavior**
We should prevent render the reply activity when its content is empty and the forum is disabled.

**Screenshots**
https://prnt.sc/1dhv43d

**Environment**
Local server.

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by KartikSuthar** [comment]
@asaquzzamanbb It fixed from: https://github.com/buddyboss/buddyboss-platform/pull/2635#issuecomment-883943240
CC: @sourabhmatolia
