### ISSUE TITLE
Mov - file not playing

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#2642]
**Describe the bug**
When you upload the MOV file and then it will show the file format is not supported and after you refresh the page it will work fine without any issue.

As answer here https://stackoverflow.com/questions/40995987/how-to-play-mov-files-in-video-tag/40999234#40999234  .MOV container uses the Quicktime codec which is proprietary Apple software and is not on the list of [Media formats supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) by the HTML audio and video elements. I'd suggest transcoding the footage to .MP4 and using that instead.

The solution mentioned here https://stackoverflow.com/questions/31380695/how-to-open-mov-format-video-in-html-video-tag/44858204#44858204 as we can pass the `type` to `video/mp4` and it will work for .mov file

**To Reproduce**
1. Go to the activity directory and upload the .mov video and hit the update button.
2. It will show you the file is not supported.

**Expected behavior**
For certain codec types, it should play on the first time even without reload the page.

**Support ticket links**
https://secure.helpscout.net/conversation/1566285602/152205/

**Comment by milanhirapra** [comment]
@chetansatasiya Please add **mp4** extension for **m4v** file type.

**Issue:** The .m4v video file format from Apple is not working, https://i.ibb.co/QFpjV3p/not-sup.jpg.

HS: https://secure.helpscout.net/conversation/1569851796/153044/
