### ISSUE TITLE
BB Latest activities widget not shows the private group feed updates even when logged in, whereas the activity page shows

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2644]
**Describe the bug**
BB Latest activities widget not shows the private group feed updates even when logged in, whereas the activity page shows

**To Reproduce**
1. Add the latest activities to any page and then go to private group and create a feed
2. Check the activity in the widget, will not show
3. Check the activity on the news feed page it will show

**Expected behavior**
For the private type feeds it should display if the logged in user is authorized

**Screenshots**

**Environment**
Client as well as dev site

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.
https://secure.helpscout.net/conversation/1577275276/154541

**Jira issue** : [PROD-782]

[PROD-782]: https://buddyboss.atlassian.net/browse/PROD-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1597814296/158107/
