### ISSUE TITLE
buddyboss platform forum reply pagination not working showing 404

### ISSUE THREAD

**Issue by MohitPrakashSharma** [buddyboss/buddyboss-platform#2646]
**Describe the bug**
I having an issue with the forum reply pagination. the second-page pagination not working this is showing me the 404. I tried this [https://bbpress.trac.wordpress.org/attachment/ticket/1927/bbpress-paging-patch.diff](https://bbpress.trac.wordpress.org/attachment/ticket/1927/bbpress-paging-patch.diff) patch this is working fine but when I am updating the team and plugin. I am losing the changes. Please provide me a Permanent solution.  Please find the screenshot. 

**Expected behavior**
This should `te-damos-la-bienvenida-al-campamento-elei/?paged=24` but this is showing `e-damos-la-bienvenida-al-campamento-elei/page/24`

**Screenshots**
https://prnt.sc/1e1p8g7

**Comment by MohitPrakashSharma** [comment]
I am still looking for response

**Comment by marienel21** [comment]
Hi @MohitPrakashSharma
