### ISSUE TITLE
Updating the activity settings page reverts the symbolic links option as enabled

### ISSUE THREAD

**Issue by surajkrsingh** [buddyboss/buddyboss-platform#2647]
**Describe the bug**
Updating the activity settings page reverts the media symbolic link option to enable.

We tested this issue on the dev stage and found whenever we click on the Settings > Activity > save settings 
then enables the Settings > Media > Media Security & Performance > Symbolic link option
Dev staging demo - https://www.awesomescreenshot.com/video/4568225?key=5635263a3e7839589f20b7a42c27bf53
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to media settings and disable the Symbolic link option (if enabled)
2. Move on the activity setting page and just click save settings
3. Again back to the media settings and check the Symbolic link option
4. You will see the option is enabled

**Expected behaviour**
Updating activity settings should not affect media settings.

**Screenshots**
Issue from customer- https://www.awesomescreenshot.com/video/4566666?key=cd8791a7a4695cbfca5171371dba5002

**Environment**
BuddyBoss-Platform Version 1.7.2.2 
Customer site as well as on dev staging site

**Support ticket links**
https://secure.helpscout.net/conversation/1577225764/154530?folderId=3709082

**Jira issue** : [PROD-781]

[PROD-781]: https://buddyboss.atlassian.net/browse/PROD-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1714059772/176752
