### ISSUE TITLE
Photos previews broken when upgrading from 1.6.x to 1.7.2.2

### ISSUE THREAD

**Issue by ianmjones** [buddyboss/buddyboss-platform#2653]
With a clean working installation of BuddyBoss 1.6.x that has working photos and photo albums in my user and a group, I then updated it to the latest BB Platform 1.7.2.2.

Photos no longer load their previews:

![Screenshot from 2021-07-20 17-09-06@2x](https://user-images.githubusercontent.com/4710/126360011-d3d82d1e-3ddc-4b6b-bb3d-536ddea88a70.png)

Albums no longer show their preview:

![Screenshot from 2021-07-20 17-22-12@2x](https://user-images.githubusercontent.com/4710/126360241-53c70797-788a-49b6-8453-bef455f170f6.png)

The debug.log is reporting some database problems that did not exist prior to 1.7.2.2:

![Screenshot from 2021-07-20 17-24-29@2x](https://user-images.githubusercontent.com/4710/126360696-7ce1aae8-09bc-4e8f-92c6-fe1962003876.png)

It seems like BB Platform has failed to create any symlinks, as seen when logged into my DevilBox container (left of following screenshot), and therefore not in host system either (bottom right of following screenshot):

![Screenshot from 2021-07-20 17-39-26@2x](https://user-images.githubusercontent.com/4710/126362687-11eca90a-6eaa-4210-b908-85ab31c0577f.png)

If I disable (the on by default) symbolic links in BB's Media Settings:

![Screenshot from 2021-07-20 17-42-02@2x](https://user-images.githubusercontent.com/4710/126363335-63b49c87-1f40-4034-aa53-b1dc97f93251.png)

I can now see photos:

![Screenshot from 2021-07-20 17-43-25@2x](https://user-images.githubusercontent.com/4710/126363400-1b259ce6-57b8-4ee7-a7a9-f97dc11ca422.png)

**Comment by sourabhmatolia** [comment]
Hello @ianmjones 

We are aware of this issue shared above and that's the reason we have added a setting in the backend to disable the Symbolic link manually if it is not properly configured or working on your server.

Internally we have auto-detection logic to check if Symbolic link works fine or no, IF YES then enable settings by default, IF NO then we disable by default.
Now that auto-detection logic also does not seem to work fine 100% of the time and that's the reason you see the error as above.
We are working on this to resolve asap.

Thanks for sharing the issue above. Closing the ticket now.
IF you have more questions please reach out to us directly. We will be happy to help.

Thank you.

**Comment by suprcb** [comment]
We have the same problem, where we can find "setting in the backend to disable the Symbolic link manually"?
Thanks

**Comment by suprcb** [comment]
> Hello @ianmjones
> 
> We are aware of this issue shared above and that's the reason we have added a setting in the backend to disable the Symbolic link manually if it is not properly configured or working on your server.
> 
> Internally we have auto-detection logic to check if Symbolic link works fine or no, IF YES then enable settings by default, IF NO then we disable by default.
> Now that auto-detection logic also does not seem to work fine 100% of the time and that's the reason you see the error as above.
> We are working on this to resolve asap.
> 
> Thanks for sharing the issue above. Closing the ticket now.
> IF you have more questions please reach out to us directly. We will be happy to help.
> 
> Thank you.

We have the same problem, where we can find "setting in the backend to disable the Symbolic link manually"?
Thanks

**Comment by bronwenh** [comment]
I am having this same issue, except, when I un-check the symbolic links, the image is still broken.
I am getting 403 error.
Symbolic link not allowed or link target not accessible
I have removed BB-platform, re-downloaded it, etc.  Was working, now not.  (I really don't want to move people over to facebook group to share their art in my online art class)
