### ISSUE TITLE
Unusable suspended-mystery-man pictures added to Media Library when media uploads enabled

### ISSUE THREAD

**Issue by ianmjones** [buddyboss/buddyboss-platform#2656]
1. Clean install of BuddyBoss Platform 1.7.2.2 on clean install of WP5.8 with PHP7.4 & MariaDB 10.3
2. Enable media uploads, including Photos, Documents and Videos

"suspended-mystery-man" pictures are added to the Media Library for each type, but their thumbnails are not visible.

![Screenshot from 2021-07-21 16-55-39@2x](https://user-images.githubusercontent.com/4710/126522529-8bce33f9-b07d-41d8-ba10-3ace454a531f.png)

![Screenshot from 2021-07-21 17-15-49@2x](https://user-images.githubusercontent.com/4710/126523293-119e0705-3792-47e3-9cb1-35b3ac490f5d.png)

The referenced images are available where they're expected to be, and have the same permissions as other working images in the Media Library. It's no doubt the `.htaccess` file that is stopping access to an image in the site's Media Library.

![Screenshot from 2021-07-21 17-19-59@2x](https://user-images.githubusercontent.com/4710/126524029-915ae8b8-e0d6-40c6-8c38-2f5e892dd488.png)

**Comment by chrisdubia** [comment]
Can confirm this as well

**Comment by chetansatasiya** [comment]
@chrisdubia #2670 will fix the issue.

**Comment by sourabhmatolia** [comment]
@ianmjones @chrisdubia

Issue mentioned above is released in BuddyBoss Platform v1.7.4

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-4/

Please update the plugin to see the latest changes.

Thank you.
