### ISSUE TITLE
Moderation > Reported content list is taking too much time to get load due to slow queries.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#2659]
**Describe the bug**
When admin user tries to access Reported content from back end then many slow queries are getting fire and page is taking too much time to get load. Total members on website : 92K.

**To Reproduce**
1. Login as admin.
2. BB>moderation>reported content
3. See error

**Expected behavior**
Page must get load fast and slow queries should not be there.

**Screenshots**
https://prnt.sc/1edv7k3

**Environment**
Local server (master branch)

**Support ticket links**
N/A reported internally by QA

**Comment by janakkaneriya007** [comment]
@mohit-buddyboss I have tried to replicate this issue on my end but it's not getting replicated. Take a note that I only have Platform, Platform Pro plugins, and buddyboss theme is activated.

You can follow the same environment and check if you are facing the issue.

cc: @sourabhmatolia @firozwp

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

Tested on QA ongoing branch of the platform and theme.

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

Tested on QA ongoing branch of the platform and theme. Now I'm not able to replicate this issue while using Platform, Pro and BB theme.

So, closing this issue.

cc @sourabhmatolia @firozwp @KartikSuthar
