### ISSUE TITLE
Documents and Privacy

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#266]
**Is your feature request related to a problem? Please describe.**
BuddyBoss Platform does not yet have a built in documents component, and there is no good solution in the market. Related issue, is that our activity and media do not have privacy options. Documents will need privacy on release to be fully usable. These are both highly requested features and should come out of the box in a social networking plugin.

**Describe alternatives you've considered**
There are BuddyPress plugins for documents but they are difficult to use and do not have a friendly interface, do not work in forums or messages, and are not integrated smoothly into Platform. 

**Describe the solution you'd like**
We will add our own Documents options in the Media component, which will support uploading of documents into Profiles, Groups, Forums, and Messages. Documents can be uploaded into activity which will sync them into a documents area in the profile/group, or vice versa. Same logic as photos. The documents area will look and behave similar to Dropbox or Google Drive, with files that can easily be organized into folders. In the activity stream, the documents will have previews like you see in Slack.

We are building Activity Privacy options in this same branch, as documents will require privacy options. Activity, Media, and Documents will have privacy options once this branch is released.

**Video explanation**
https://www.loom.com/share/ac6404615c48469eaac3f630bd937832

**Wireframe**
[Documents.pdf](https://github.com/buddyboss/buddyboss-platform/files/3867169/Documents.pdf)

**Support ticket links**
https://secure.helpscout.net/conversation/1112074767/11924/
https://secure.helpscout.net/conversation/1112222437/17294/

Theme Issue: https://github.com/buddyboss/buddyboss-theme/issues/297

![Member-All Documents](https://user-images.githubusercontent.com/53221322/76048319-4e8eef00-5f1a-11ea-928f-5cda14282748.png)

![Group_documents V2](https://user-images.githubusercontent.com/53221322/76048334-551d6680-5f1a-11ea-9094-6a4544414fe9.png)

![Documents-Previews](https://user-images.githubusercontent.com/53221322/76048413-a4fc2d80-5f1a-11ea-9282-d66fc3d2d4ad.png)

**Comment by Jordane-L** [comment]
@chetansatasiya @amincdev  Will it be possible that it is only a person profile (eg: moderator) to add the documents to a group? Thank you!

**Comment by mehulkaklotar** [comment]
> @chetansatasiya @amincdev Will it be possible that it is only a person profile (eg: moderator) to add the documents to a group? Thank you!

@Jordane-L Yes. In group's settings, it will have a setting to set who can upload documents to the group. https://prnt.sc/rse6qh

**Comment by bryanr18lowe** [comment]
@eisenwasser so excited for the release of this documents and media privacy extension. Are the groups widgets depicted in the screen grabs above available? I would like to use that "Suggested Groups" widget and also the "Create new group widget" in my group archive and single group side bar. Thanks for any insight.

**Comment by eisenwasser** [comment]
@bryanr18lowe 

Awesome! We are excited too, the documents system is going to be really nice. Especially once you see the work we are doing in the theme for it, it's really cool.

The groups widgets in the screen grab are not actually part of this scope. The designer was just having some fun. But all of the documents stuff looks similar to those designs in the theme branch right now.

We might do widgets like that later on but not in this branch's scope.

**Comment by 007ke** [comment]
Hi Chetan

Will this be similar to https://wordpress.org/plugins/buddydrive/

It would be great to have this incorporate with the exact features as with this plugin and increase the features by adding the possibility to let the user create a PORTFOLIO (further divided by folders and files) for their projects. 

Currently, there are some plugins available but they are more for images and not supporting other file formats like PDF, DOC, XLS, etc... It would be good to have it support all the file formats and the admin can then configure the ones they wish to allow.

Thanks

**Comment by eisenwasser** [comment]
@007ke 

This is not influenced at all by BuddyDrive.

It will allow users to upload files and organize them into folders, and move files and folders around and into subfolders. It is most similar to Dropbox interface, in profiles and groups.

It will support many file formats and users have the ability to add their own file formats in the admin. All of that is working already.

**Comment by 007ke** [comment]
Thanks Michael

What about the file/folder sharing options. Apart from what is available,
can an user additionally also allow another user/group to access the shared
file/folder with some conditions like password, time duration, etc... ?
This feature is there in buddydrive and it would be great if you could
include the same. I totally understand that your development is not related
or influenced by buddydrive, but as a potential user, i felt the need to
highlight an available plugin and its features and how to best value add to
the buddyboss development.

Thanks

**Comment by eisenwasser** [comment]
@007ke

> What about the file/folder sharing options. Apart from what is available, can an user additionally also allow another user/group to access the shared file/folder with some conditions like password, time duration, etc... ? This feature is there in buddydrive and it would be great if you could include the same. I totally understand that your development is not related or influenced by buddydrive, but as a potential user, i felt the need to highlight an available plugin and its features and how to best value add to the buddyboss development.

At launch we will not have all of that. The privacy options are the same like all other BuddyBoss/BuddyPress features:
- Public
- All Members
- My Connections (Friends)
- Only Me

And additionally, if added into a group then the document inherits the groups privacy, just like activity, forums and all other group content does.

In the future we may expand these options to allow sharing documents (and activity etc) to specific members, and password protected folders, etc. But for v1 we don't want to overcomplicate it. We have so many good features in the initial release of the project and we're focusing on wrapping those up for release right now.

**Comment by 007ke** [comment]
Totally understandable and agree with you Michael

Keep safe and look after yourself well.

Best Regards,

Ketan Chandaria

**Comment by eisenwasser** [comment]
@007ke  Thanks, you too
