### ISSUE TITLE
Js error when click on edit button on video modal and edit button does not work

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#2662]
**Describe the bug**
Js error when click on edit button on video modal and edit button does not work

**To Reproduce**
1. Go to profile videos
2. upload a video, after uploaded, open it
3. In the video modal, click on edit button
4. you can see edit button does not do anything and notice js error in console

**Expected behavior**
Should not have any js error and edit button should work

**Screenshots**
https://prnt.sc/1en2z47

**Environment**
In my localhost and buddyboss sandbox - https://demos.buddyboss.com/online-communities/

**Support ticket links**
n/a

**Comment by sumitbuddyboss** [comment]
Hello @sadrul @amincdev 

**Issue - 1**
The "More options" button design is not proper.

**How to reproduce:**

1. Open any video in popup
2. Hover on Menu icon dots
3. See error

Screenshot:
https://prnt.sc/1g2lfo2
