### ISSUE TITLE
Photos and Videos broken when WP Offload Media plugin active

### ISSUE THREAD

**Issue by ianmjones** [buddyboss/buddyboss-platform#2665]
1. As a user add photos and mp4 video to own Photos and Videos areas in working BuddyBoss Platform 1.7.2.2 on WP5.8.
2. Ensure photos visible and clicking on video thumbnail displays video overlay and video can be played.
3. Install and activate WP Offload Media 2.5.5.
4. Configure WP Offload Media.
5. Do **not** offload anything.
6. Optional ... turn off "Rewrite Media URLs" setting in WP Offload Media (redundant but enforces that no URLs are going to be changed).
7. Return to (refresh) Videos section of profile.
8. Click on video thumbnail, see error "Video format is not supported. Please download to play."
9. Visit Photos area, photos not visible, just blank cards with filenames.
10. Deactivate WP Offload Media.
11. Return to (refresh) Videos section of profile.
12. Click on video thumbnail, video visible and can be played.
13. Visit Photos area, photos visible again.

Video without WP Offload Media active:

![Screenshot from 2021-07-22 13-57-01@2x](https://user-images.githubusercontent.com/4710/126644583-4707fd0d-8aed-4b37-bd48-0ae70ea45c28.png)

Video with WP Offload Media active:

![Screenshot from 2021-07-22 13-57-52@2x](https://user-images.githubusercontent.com/4710/126644637-da6d80e8-407e-42ca-b5b0-97b6c30345e8.png)

Photos without WP Offload Media active:

![Screenshot from 2021-07-22 14-20-17@2x](https://user-images.githubusercontent.com/4710/126646697-ff2355a3-a895-43ff-907f-e356f258dad5.png)

Photos with WP Offload Media active:

![Screenshot from 2021-07-22 14-21-46@2x](https://user-images.githubusercontent.com/4710/126646754-37c8716b-2bc4-4480-b184-8717f0ba0510.png)

Nothing is logged to debug.log

Prior to BuddyBoss Platform 1.7.x there were no issues with seeing Photos when WP Offload Media was active, or even when photos were offloaded by WP Offload Media, including when using its "Remove Files From Server" option.

**Comment by welshlamb10** [comment]
@ianmjones - I've also logged this bug. Although have not been advised on any fix from BB. WP Offload Media support are currently working on uploads of avatars and cover photos for BuddyBoss and are aware of the bug. 

I am unable to use the latest version of BB due to this bug. I'm holding out for them to make a fix. I believe the bug is due to the way that BB has change how it handles the media.

**Comment by TheWizardofWikacy** [comment]
Same issue with Cloudinary Plugin.  Has anyone figured this out, and why have they not validated the bug yet?

**Comment by marienel21** [comment]
Hi @ianmjones @welshlamb10 ,

The issue mentioned above is released in BuddyBoss Platform v1.7.6

You can check release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-6/

Please update the plugin to see the latest changes.

Thank you.
