### ISSUE TITLE
PDF document thumbnails not created when Remove Files From Server defined for WP Offload Media

### ISSUE THREAD

**Issue by ianmjones** [buddyboss/buddyboss-platform#2666]
When WP Offload Media's "Remove Files From Server" setting is turned on via the 'remove-local-file' key of its [AS3CF_SETTINGS](https://deliciousbrains.com/wp-offload-media/doc/settings-constants/) define, BuddyBoss Platform 1.7.2.2 does not create thumbnails for PDFs uploaded to Documents. The PDF is otherwise downloadable and usable.

![Screenshot from 2021-07-22 15-47-42@2x](https://user-images.githubusercontent.com/4710/126664461-812c0e93-01e2-4dce-ad03-e066769b8f9e.png)

Diagnostic Info that shows "Remove Files From Server" turned on using AS3CF_SETTINGS define:

[buddyboss17.loc-diagnostic-log-20210722145639.txt](https://github.com/deliciousbrains/wp-aws/files/6863370/buddyboss17.loc-diagnostic-log-20210722145639.txt)

If the 'remove-local-file' key is removed from the AS3CF_SETTINGS define, and the "Remove Files From Server" setting is instead set via WP Offload Media's UI, thumbnails are generated for PDF documents.

![Screenshot from 2021-07-22 16-01-54@2x](https://user-images.githubusercontent.com/4710/126664943-e5d2489f-5307-42ea-991e-1622b557baaa.png)

Diagnostics when using UI setting:

[buddyboss17.loc-diagnostic-log-20210722150748.txt](https://github.com/deliciousbrains/wp-aws/files/6863387/buddyboss17.loc-diagnostic-log-20210722150748.txt)

To reproduce...

1. Configure WP Offload Media as usual, but add following to wp-config.php:

```
define( 'AS3CF_SETTINGS', serialize( array(
        'remove-local-file' => true,
) ) );
```

2. Upload a PDF to Documents.

## Reason for Issue

The problem arises because of the new compatibility code introduced with BuddyBoss Platform 1.7.x.

In particular it [reaches into](https://github.com/buddyboss/buddyboss-platform/blob/ff07f8646f7a1c56516bbd6cf6f1ad3c92527589/src/bp-core/compatibility/bp-incompatible-plugins-helper.php#L220) WP Offload Media's settings as stored in the options or sitemeta database table to determine whether there is likely a local version of the document or not, i.e. it checks whether "Remove Files From Server" has been turned on.

This breaks when WP Offload Media's settings are being `define`d as the setting in question isn't in the database.

Apart from that obvious problem, there's a number of issues with how that compatibility code has been put together.

1. The compatibility code looks for a particular key in the unserialized settings records, that key may change in the future.
2. The settings constant being used may be moved to a new location in the code in the future (this is quite likely actually).
3. The `as3cf_get_attached_file_copy_back_to_local` filter is conditionally implemented based on whether "Remove Files From Server" has been turned on. It could simply be added and set to return true (`'__return_true'`) when a thumbnail needs to be generated, and then removed at the end of the thumbnail regeneration. WP Offload Media would then take care off copying the original file back to the server when `get_attached_file()` is used and the file does not exist locally yet, and then removes it from the server again if the "Remove Files From Server" setting is currently turned on.
4. With the current implementation BuddyBoss would not ask WP Offload Media to copy back the file if the "Remove Files From Server" option is turned off, but it's entirely possible that it was previously turned on and so a file is missing from the server.
5. In a clustered server setup the original file may reside on one server but BuddyBoss attempts to generate a thumbnail on a different server. A lot of people use WP Offload Media in clustered server setups to get around this problem, as WP Offload Media takes care of serving the file from the bucket or CDN to the browser regardless of which server generated the HTML. In a similar fashion, WP Offload Media also helps server side processing such as async thumbnail regeneration by being able to temporarily pull back the original file to whichever server is tasked with the process.

If you need any further help with this problem please ping me here or drop us a line via our [Contact Us](https://deliciousbrains.com/contact-us/) page, mention your message is for Ian (that's me), and link to this issue.

Oh, I should probably mention I'm the lead developer on WP Offload Media! :smile:

**Comment by chetansatasiya** [comment]
@ianmjones Is there a way we get all the settings without using the keys? So we don't have to care anything in future if you change any keys?

**Comment by chetansatasiya** [comment]
@ianmjones Can you check with the latest changes here https://github.com/buddyboss/buddyboss-platform/pull/2673 if it fixed all the issues for you or not?
