### ISSUE TITLE
Activity > Hashtags

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#267]
**Is your feature request related to a problem? Please describe.**
BuddyBoss Platform does not have the ability to use #hashtags in the activity feed, as popularized by Twitter and Facebook. This is a feature that many users expect in the activity feed of a social networking plugin.

**Describe the solution you'd like**
We will add our own Hashtag functionality
In the settings page for Activity we need a new setting:

>**Hashtags**
>Allow your users to use #hashtags in their activity posts

Once activated, any new text posted into the activity feed with a # in front of it will become a clickable link. When you click that link, the activity feed switches to showing only posts that include that hashtag. If you are on your own profile or in a group and click a #hashtag it redirects you to the main activity index and shows all sitewide posts using that #hashtag.

We need to make a UI for this also for auto-suggesting hashtags. When creating a post and you type a # it will start to show a dropdown of existing #hashtags from the database that you can choose from, or you can type your own, just like what happens when you are using @ to mention someone in activity stream. As shown here: http://prntscr.com/meoxsg

We will also need a Popular Hashtags widget that site admins can use in sidebar. The widget will display the top most used hashtags from the site, ordered from most to least.

**Describe any major concerns**
One thing we need to consider is what happens when the feature is enabled/disabled. If disabled then the old #hashtags in posts need to not be links anymore, and if enabled they need to become links again. Not sure how we handle this, as usually links saved in the database itself. Somehow we need to not save these in the database as links and apply it through Javascript or some other clever method.

**Describe alternatives you've considered**
This plugin does a lot of this already and seems to work (partially) when enabled with platform:
https://wordpress.org/plugins/hashbuddy/
However it has not been updated in over 5 years, and is no longer maintained. So we should build this into core of Platform in a better way.

**Support ticket links**
https://secure.helpscout.net/conversation/1112039255/10105/

**Comment by ragnabnet** [comment]
Hello, could you add a new feature about user post/ comment reporting?
This is the basic feature for forum/social media but buddyboss doesn't has it until now.
It'd be great if buddyboss has this feature. Thank you.

**Comment by eisenwasser** [comment]
@ragnabnet Thanks for the feedback. We will consider it. Keep in mind if you use Akisment it will add a spam button of activity (but not forums).

**Comment by BenJackGill** [comment]
This is probably a better plugin to emulate. It works all over WordPress (not just BuddyPress activity) and has been recently updated: https://wordpress.org/plugins/hashtagger/

I would also LOVE for users to be able to "follow" a hashtag. When a hashtag is followed popular posts the hashtag could be shown in their feed. A great way for users to follow topics that they like, without having to follow an entire account. This is how Tumblr etc works and it's great. It also helps you discover new users to follow who are putting out content that you like.

**Comment by eisenwasser** [comment]
@BenJackGill Thanks for the feedback. We will look into all of this.

**Comment by tomjutla** [comment]
> This is probably a better plugin to emulate. It's not just for BuddyPress so it also works for posts and pages (great feature), unifies the WordPress tag system with hashtags (awesome), and has been recently updated: https://wordpress.org/plugins/hashtagger/
> 
> I would also LOVE for users to be able to "follow" a hashtag. They click on a hashtag to open the "tag" page, and then click a follow button.
> 
> When a hashtag is followed popular posts from the hashtag could be shown in their activity feed. It's a great way for users to follow topics that they like, without having to find and follow specific accounts. This is how Tumblr etc works and I think it's a great system. It's also a fantastic way to discover new users across the network who are putting out good quality content that you enjoy.

@BenJackGill i completely agree and came to make the same comment but looks like you beat me to it...

**Comment by datdudejibril** [comment]
> This is probably a better plugin to emulate. It's not just for BuddyPress so it also works for posts and pages (great feature), unifies the WordPress tag system with hashtags (awesome), and has been recently updated: https://wordpress.org/plugins/hashtagger/
> 
> I would also LOVE for users to be able to "follow" a hashtag. They click on a hashtag to open the "tag" page, and then click a follow button.
> 
> When a hashtag is followed popular posts from the hashtag could be shown in their activity feed. It's a great way for users to follow topics that they like, without having to find and follow specific accounts. This is how Tumblr etc works and I think it's a great system. It's also a fantastic way to discover new users across the network who are putting out good quality content that you enjoy.

Hashtagger converts a hashtag into a wp tag and this plugin allows you to follow tags. I think both of these plugins combined are a good workaround until buddyboss adds it. 
https://wordpress.org/plugins/follow-tags/

**Comment by rhonmon62** [comment]
It would be an amazing feature to also allow a user to block certain hashtag so it doesn't show up in feed/groups/forums

**Comment by ragnabnet** [comment]
Hello, it's been a while i'm using buddyboss platform and in my experience i found a big problem for a making an active community using buddyboss.
The user experience in the buddyboss app and buddyboss platform are really passive. So the conversion of the engagement for our user is so little. Because there's no function for us to make a featured hot topics, hot forum, or hot issue. So people in our community doesn't know what's going on in the forum or in the community or what people in the community currently like, because there's no automation to make a posts that have the most like to be go up to the header of a activity page section or in a forum page or in the home page.

If we want to build a strong community. It's supposed to be having a feature post or maybe we can make a featured courses that people like also.
People need to click here and there to just find something that good for them and it'll take a long time to search. So please make these "featured" function to be release as we know the success of instagram and reddit as a community right now because their platform are really focusing on their user engagement. Thank you!

**Comment by bengrosser** [comment]
New BuddyBoss (and BB Theme) user. I noticed this feature appears next on the roadmap. Is its release imminent? Wondering if I should/could plan on it. And if not, do you have any suggestions for alternative plugins to implement this? (I noticed a few things are mentioned above, but thought @eisenwasser might have a suggestion). Thanks!

**Comment by tomjutla** [comment]
I also would like to know how imminent this is as i have used bbpress hashtag plugin which is a good basic work around but if you guys think you could be rolling this feature out in a month or 2 then i will hold off with publishing my App so i can remove the existing plugin and make sure the built in feature works well. Plus will it have the option on setup to absorb existing hashtags already in use by other plugins such as bbpress hashtag plugin? thanks

**Comment by dagamachris** [comment]
I agree with those who've suggested a hashtag follow function. This would make following specific topics so much easier and enable content to be more widely seen.

**Comment by mikejyoung** [comment]
This issue has been added to our internal feature planning software.
Once full designs and scope are created and ready for development, new issues will be created.
Closing this issue now.
