### ISSUE TITLE
Elementor bb templates not found

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2671]
**Describe the bug**
bb templates are not found in the  elementor.  when click on the bb orange icon, there are no templates available.

**To Reproduce**
1. Go to Templates
2. Crete new Templates and click on bb orange icon
4. See error "no templates found." 

Same error will reproduce if edit any page with elementor and click on BB orange icon.

**Expected behavior**
When click on BB orange icon then Template will be visible on that pop-up.

**Screenshots**
https://prnt.sc/1eh5c1i

**Environment**
This issue is reported by many customer and I have replicate it in my dev environment too.

**Support ticket links**
https://secure.helpscout.net/conversation/1579120684/154894
https://secure.helpscout.net/conversation/1581400590/155296

**Comment by amincdev** [comment]
@chetansatasiya I checked this issue and found that the ajax response is empty: https://ibb.co/xFRqVWF
