### ISSUE TITLE
Member pages become slow when Moderation module is active.

### ISSUE THREAD

**Issue by asaquzzamanbb** [buddyboss/buddyboss-platform#2674]
**Describe the bug**
Member pages become slow when the Moderation module is active. Because the Moderation module is joining some extra tables with the help of filters when fetching the members.

**To Reproduce**
1. Install query monitor WP plugin.
1. Install WP-CLI in your local server.
2. Create 2 lakh members with the help of this command line `wp bp member generate --count=200000`
3. Active Moderation module from back-end settings.
4. Navigate to the members page.
5. Check the query time from the query monitor only for this method `BP_User_Query->do_user_ids_query()`
6. Deactivate the moderation module from the back-end settings.
7.  Again navigate to the members page.
8. Again check the query time from the query monitor only for this method `BP_User_Query->do_user_ids_query()`
9. This time you will get the fast query after disable the Moderation module.

**Expected behavior**
Slow query need to make fast which is showing from the query monitor only for this method `BP_User_Query->do_user_ids_query()`

**Screenshots**
Check the query time from the following image when Moderation module is active.
https://prnt.sc/1eovqiy

Check the query time from the following image when Moderation module is deactivate.
https://prnt.sc/1erlkox

**Environment**
Local server.

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by chrisdubia** [comment]
I can verify that this exists even with the Moderation Module deactivated

**Comment by asaquzzamanbb** [comment]
@janakkaneriya007 @sourabhmatolia 

Actually, the issue is found from this site https://dev.strenuouslife.co/ . But this site is now working fine without any changes. Right now we are not able to reproduce this issue. So i am gonna close this issue.

Related issue: https://github.com/buddyboss/buddyboss-platform/issues/1202
