### ISSUE TITLE
JS scripts broken > Some activities are not loading the images with version 1.7.3 

### ISSUE THREAD

**Issue by surajkrsingh** [buddyboss/buddyboss-platform#2680]
**Describe the bug**
Some activity feeds are not loading the actual images and instead of the actual image, it shows the placeholder images.
because JS script is broken with the latest version 1.7.3 when we disable the Moderation component.

Issue is related to this commit - https://github.com/buddyboss/buddyboss-platform/commit/53d541262f57d949c5df78b75180d9bb67e14041

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  Buddyboss component list
2. Disable the **Moderation**
3. Load the activity page on the frontend 
4. Check the browser console and also see some activity won't load the images

**Expected behaviour**
Images should be load correctly on all activity and the js console error should be fixed.
 
**Screenshots**
Our demo site - https://tinyurl.com/yz3762eg
On customer site - https://www.awesomescreenshot.com/video/4613518?key=102ea5896ea4ea8e0bfdcdbb3a4459e9

**Environment**
I am able to replicate this issue on the customer staging, local dev stage as well as on our demo site.

**Support ticket links**
https://secure.helpscout.net/conversation/1580305848/155108?folderId=3709082

**Comment by mahedihasannoman** [comment]
https://secure.helpscout.net/conversation/1579983396/155037?folderId=4687016

**Comment by mahedihasannoman** [comment]
This issue is happening when moderation component is deactivated.
