### ISSUE TITLE
Buddyposs platforms new released , caused my negative errors on my site such as, news feed broken uploaded images, diapering post Edit and delete, i sent to buddyboss team but they not realized the problem yet. What is your suggestions? https://travellife.egsky.net 

### ISSUE THREAD

**Issue by egsky** [buddyboss/buddyboss-platform#2681]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.
[https://travellife.egsky.net](url)

**Comment by sourabhmatolia** [comment]
@egsky 

Issue mentioned above is released in BuddyBoss Platform v1.7.4

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-4/

Please update the plugin to see the latest changes.

Thank you.
