### ISSUE TITLE
[URGENT] MEDIA PREVIEW FOR IMAGES NO LONGER FUNCTIONS

### ISSUE THREAD

**Issue by chrisdubia** [buddyboss/buddyboss-platform#2683]
Hi - we just updated to the latest build today 1.1.3.2 and 1.7.2 and Image previews are no longer working for photos. . Our servers are throwing javascript error...on staging, live and on new builds.

![image0](https://user-images.githubusercontent.com/7943256/127051274-8287a1ca-c6dc-4c5f-b5bd-96451ea5b1e9.jpeg)

**Comment by chrisdubia** [comment]
If this is closed when is the release coming out to fix this? I know there is a Band-Aid fix by enabling moderation.￼

**Comment by sourabhmatolia** [comment]
@chrisdubia
 
Issue mentioned above is released in BuddyBoss Platform v1.7.4

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-4/

Please update the plugin to see the latest changes.

Thank you.
