### ISSUE TITLE
When creating the BuddyPanel from the WordPress Customizer, the menu item icons are not added.

### ISSUE THREAD

**Issue by preeti2909** [buddyboss/buddyboss-platform#2684]
**Describe the bug**
When creating the BuddyPanel from the WordPress Customizer, the menu item icons are not added. However, when creating a menu from the WordPress Dashboard > Appearance > Menus all icons for the BuddyPanel items are added.

**To Reproduce**

1. Go to 'WordPress Customizer > Menus > Create New Menu'
2. Mark the checkbox 'BuddyPanel - Logged in users (Current: BuddyPanel)'
3. Click 'Add Items'
4. Add menu items 'Profile, Account, Notifications, Connections, Groups' from the BuddyBoss (logged-in) 
5. Click 'Publish'
6. See error - https://prnt.sc/1gj98ti

**Expected behavior**
The menu items should have the correct icons as seen on the demo site - https://prnt.sc/1gja53a

**Screenshots**
Attached screenshots

**Environment**
Flywheel site

**Comment by kishanjasani** [comment]
This is not a Platform issue. Created an issue in the theme. https://github.com/buddyboss/buddyboss-theme/issues/1628
