### ISSUE TITLE
Forums > Support @mentions

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#269]
**Is your feature request related to a problem? Please describe.**
BuddyBoss Platform does not properly support using @mentions in forums. Currently if you type an @mention it will actually function once you publish the reply. However while typing the reply you will not see the dropdown auto-suggest box as you do in activity feed.

**Describe the solution you'd like**
We will add the ability to @mention users in Forums, with a dropdown auto-suggest box just like when mentioning users in activity feed. This does not require any new options; it will be a default functionality as long as Forums component is enabled. When you @mention a user in a forum, the user will receive a notification, same like if you mention them in an activity post. If Activity component is also enabled, then a new activity post will display as well, showing the user that they were mentioned in a forum post.

**Describe alternatives you've considered**
There are no plugins that allow for this currently.
Somehow WordPress.org is doing this already, maybe they open sourced their code?
https://wptavern.com/wordpress-support-forums-add-mentions-with-auto-complete

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/50168
https://buddyboss.zendesk.com/agent/tickets/53126
https://buddyboss.zendesk.com/agent/tickets/53423

**Comment by binaryfire** [comment]
@eisenwasser Mike, I think this plugin has the code you need: https://wordpress.org/plugins/bbp-mentions-email-notifications/

-Raj

**Comment by eisenwasser** [comment]
@binaryfire 

Thanks for the code suggestion. 

Right now, @ mentions work in forums already. They just need the JS dropdown auto-suggest to load. When @mehulkaklotar starts working on this project he can reference your code above to see if it is helpful.

**Comment by mehulkaklotar** [comment]
@binaryfire Thank you for the code suggestion. That code will only work if Activity component is enabled. We need to have mentions code separated only for forums pages on forms. so it will work with my latest commits.

**Comment by eisenwasser** [comment]
@binaryfire This is live now in the latest release.
