### ISSUE TITLE
News feed page quick reply popup does not display media upload buttons when access control enabled

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#2690]
**Describe the bug**
When users don't have access to upload media/document/video, then quick reply of a group forum does not show these icons in news feed page. However, it should display because media access is not applicable for group related stuff

**To Reproduce**
1. Go to buddyboss > settings > media access
2. Set media access for target user
3. Login to a user who does not have access to upload media, documents and videos
4. Created a discussion from a group forum
5. Go to news feed page and find that post
6. click on quick reply and you will not see media upload buttons

**Expected behavior**
User should get media upload buttons for quick reply as media access does not applicable for group forums

**Screenshots**
https://www.loom.com/share/7202aee1000b4f1b85f9b354e7369496

**Related BuddyBoss Theme issue**
https://github.com/buddyboss/buddyboss-theme/issues/1581

**Comment by KartikSuthar** [comment]
@sadrul @sourabhmatolia closing this issue as it's from the theme: 
https://github.com/buddyboss/buddyboss-theme/issues/1581

**Comment by sadrul** [comment]
Reopening this issue as we need to add some code to the related PR
