### ISSUE TITLE
Documents count is not showing on the user profile page.

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2705]
**Describe the bug**
Documents count is not showing on the user profile page.

![screenshot-demos buddyboss com-2021 07 28-18_02_30](https://user-images.githubusercontent.com/12556175/127552862-a6df708b-a81f-477b-ae0c-27c5a7643df0.png)

**To Reproduce**
1. Upload some documents
2. See the count is not showing in user profile page.

**Expected behavior**
Documents count should show there

**Environment**
Demo, local & client site

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Jira issue** : [PROD-777]

[PROD-777]: https://buddyboss.atlassian.net/browse/PROD-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chetansatasiya** [comment]
Closing this as we don’t have count in documents

**Comment by sourabhmatolia** [comment]
**UPDATE**

We might not go with the direct solution to show Documents count just like that because we have Folders in the listing and that might make things confusing for End Users.
We will discuss it internally and decide how to go about it. 
Thanks.
