### ISSUE TITLE
Compatibility with Cloudinary Media CDN for User Galleries

### ISSUE THREAD

**Issue by TheWizardofWikacy** [buddyboss/buddyboss-platform#2710]
Has anybody figured out how to enable compatibility with cloudinary media pluin for the user photos and videos in the new version of buddyboss?  The versions before the video upload feature was added was fine, but since the video uploads were added, none of the user photos will display in either activity feed or galleries.  New media added displays fine, but not the older media.

**Comment by mikejyoung** [comment]
Hi @TheWizardofWikacy 
We don't currently have support for Cloudinary.
If you'd like to se this feature, please submit it as an idea in our public roadmap:
https://buddyboss.com/roadmap

**Comment by TheWizardofWikacy** [comment]
Thank you but I actually already figured it out.  It was a simple fix.  It absolutely does support cloudinary.  For the benefit of the readers and those who have had the same problem with other off-site media plugins, all you have to do is rewrite or delete the htaccess file buddy boss has placed in the uploads/bb-medis and bb-videos folders.

Sorry I forgot to update this thread.  You can actually cross this off this excessively long bug list you have going here.  Issue Resolved.
