### ISSUE TITLE
Profile Fields not showing

### ISSUE THREAD

**Issue by pettraveladvisor** [buddyboss/buddyboss-platform#2712]
After installing the Buddy Boss platform, free version, I am not able to see any Profile Field. 
![image](https://user-images.githubusercontent.com/88267756/127767626-57bc3801-402c-4dc9-9383-c8b4436e6ba7.png)

Can you please give me some ideas how to solve this?

**Comment by pettraveladvisor** [comment]
?

**Comment by mikejyoung** [comment]
Hi @pettraveladvisor,

Sorry my comment didn't post. 

I'm order to help resolve your issue, it would need to be sent to our support team, which is not available on free plans. 

As we can't replicate this, it is likely a plugin or theme conflict in your site that is causing the issue.

**Comment by pettraveladvisor** [comment]
Ok, for me its a bit risky to buy at this case so I will try to be sure it will work in advance. Thanks for the answer
