### ISSUE TITLE
Error in reset password for existing user if social group component is disabled

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2719]
**Describe the bug**
The issue is if social group component is not active then reset password is not working for the existing user. it's show and error when click on forgot password. It's work fine for new user.

**To Reproduce**
1. Sign in to the site.
2. Click on 'Forgot Password?'
3. Add email id 
4. see the error 

**Expected behavior**
The reset password work for the existing user even if social group component is disabled.

**Screenshots**
http://i.prntscr.com/LSxXit9CQlS6ZwQpfuNhtA.png
http://i.prntscr.com/ChP1WJ5bTfeLFL-TBCznaw.png

It's shows this error in debug log 

`An error of type E_ERROR was caused in line 554 of the file /home/sciencematterski/staging.sciencematterskits.com/wp-content/plugins/buddyboss-platform/bp-integrations/learndash/library/SyncGenerator.php. Error message: Uncaught Error: Call to undefined function Buddyboss\LearndashIntegration\Library\groups_get_groupmeta() in /home/sciencematterski/staging.sciencematterskits.com/wp-content/plugins/buddyboss-platform/bp-integrations/learndash/library/SyncGenerator.php:554
Stack trace:
#0 /home/sciencematterski/staging.sciencematterskits.com/wp-content/plugins/buddyboss-platform/bp-integrations/learndash/library/SyncGenerator.php(535): Buddyboss\LearndashIntegration\Library\SyncGenerator->loadLdGroupId()
#1 /home/sciencematterski/staging.sciencematterskits.com/wp-content/plugins/buddyboss-platform/bp-integrations/learndash/library/SyncGenerator.php(38): Buddyboss\LearndashIntegration\Library\SyncGenerator->populateData()
#2 /home/sciencematterski/staging.sciencematterskits.com/wp-content/plugins/buddyboss-platform/bp-core/compatibility/bp-incompatible-plugins-helper.php(1038): Buddyboss\LearndashIntegration\Library\SyncGenerator->__construct()
#3 /home/sciencematterski/staging.sciencematterskits.com/wp-includes/class-wp-hook.p`

**Environment**
client site and replicate on my dev site.

**Support ticket links**
https://secure.helpscout.net/conversation/1579813552/155005

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1606642377/159668/

**Comment by hercivalbuddyboss** [comment]
https://secure.helpscout.net/conversation/1606135684/159594/
