### ISSUE TITLE
Report activity based on the content in it

### ISSUE THREAD

**Issue by janakkaneriya007** [buddyboss/buddyboss-platform#2729]
**Describe the bug**
When creating an activity with one photo, document, and video it should have a report button based on the moderation settings. Below are the scenatrios.

**To Reproduce**
1. If there is only one photo then it should show the "Report Activity" on activity listing and open photo, document, and video.
2. If the activity moderation is disabled from the moderation settings it should say "Report photo"
3. If Photo, Document, Video moderation is disabled from the moderation settings it should say "Report Post"
4. If Activity and media relevant settings are disabled from the moderation settings it should not show the report button.

**Expected behavior**
The report button should show based on the moderation settings.

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by nan07** [comment]
#1442  has to implement in app as well .
