### ISSUE TITLE
On activity page on forum reply Read More link not taking you to forum reply

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2741]
**Describe the bug**
Form the activity page if we click on read More link then it's not goes to that particular reply. Instead of that it's just open that forum discussion. 

So, there are basically two issues:

1) Join Discussion URL is mistakenly used for the Discussion reply "Read More" and vise a versa
2) The URL linking to the reply Id in that discussion once points to correct reply, but again points to the top

**To Reproduce**
1. Go to 'Forum' and add replay to any discussion 
2. Go to 'Activity' page 
3. Click on 'read more'  and then click on 'Join Discussion'

**Expected behavior**
1) When click on 'Join Discussion'  use the link used for the ' Read more' means open the discussion and when click on 'Read more' Please open the page with that particular discussion replay.
2) The URL linking to the reply ID in that discussion points to correct reply and not goes to the top of the page.

**Screenshots**
Check this video:  http://somup.com/crj1hFY5LV

**Environment**
I have also replicate this issue in client's site as well in my dev site.

**Support ticket links**
https://secure.helpscout.net/conversation/1580213235/155089/

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1602803779/159021/
