### ISSUE TITLE
MemberPress > Activity page and Widget doesn't protected

### ISSUE THREAD

**Issue by milanhirapra** [buddyboss/buddyboss-platform#2755]
**Describe the bug**
Create Memberships and rules using the Memberpress plugin.
Set protected the activity page with membership. When we go to the activity page we can see all activities and widget as well.

**To Reproduce**

Set Membership & rules in the MemberPress plugin:
1. Go to MemberPress > Memberships
2. Click on "Add New" and create a new membership
3. Go to MemberPress > Rules
4. Click on "Add New" and create a rule
5. Set Activity page in the Protected Content section and assign membership to this rule

Set widget
1. Go to Appearance > Widget
2. Add "(BB) Latest Activities" widget to the activity page

Results
1. Go to the Activity page
2. Can see the activities and widget without login

**Expected behavior**
Activities and widgets should not appear without subscription/login if the activity page is set to protected.

**Screenshots**
https://vimeo.com/584862862/ed513ca7bd

**Environment**
Which site did you replicate this issue on?
My dev site: https://dev-milan.flywheelsites.com
The customer's site: https://testacademy.liferevival.com/

BuddyBoss Platform(Version 1.7.5)
BuddyBoss Platform Pro(Version 1.1.4)
MemberPress(Version 1.9.19)
MemberPress + BuddyPress Integration(Version 1.1.10)

**Support ticket links**
https://secure.helpscout.net/conversation/1564860794/151869/

**Jira issue** : [PROD-771]

[PROD-771]: https://buddyboss.atlassian.net/browse/PROD-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mahedihasannoman** [comment]
Hi @milanhirapra I am not able to replicate this issue. See my video: https://www.loom.com/share/da7175071d674f5da69bce961a4172f0
It the issue is not reproducible on your end then please close this issue.

**Comment by milanhirapra** [comment]
Hi @mahedihasannoman 
I am able to replicate this issue.
Please check this video: https://vimeo.com/600022982/7c4db824ea
