### ISSUE TITLE
Blog Activity > Need an option to set video preview layout

### ISSUE THREAD

**Issue by milanhirapra** [buddyboss/buddyboss-platform#2758]
**Describe the bug**
Blog activity layout updated in version 1.7.2.
Old layout: https://nimb.ws/BUu1q8
New layout: https://nimb.ws/FvkNJq

**To Reproduce**

1. Go to Post > Add New
2. Add title and embed video
3. Go to the activity page
4. See new layout https://nimb.ws/FvkNJq

**Expected behavior**
There should be an option to set the video preview layout for the blog activity

**Screenshots**
Old layout: https://nimb.ws/BUu1q8
New layout: https://nimb.ws/FvkNJq

**Support ticket links**
https://secure.helpscout.net/conversation/1574475186/153993/

**Jira issue** : [PROD-770]

[PROD-770]: https://buddyboss.atlassian.net/browse/PROD-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amincdev** [comment]
@chetansatasiya @KartikSuthar I found that when you create a new post with just embedded video (https://ibb.co/sF0M5sW) then activity content is empty (https://ibb.co/8gGp70Y).
Is there a way we can get an iframe to show in activity in this case?
