### ISSUE TITLE
Documents in hidden and private groups is showing in the newsfeed

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#2760]
**Describe the bug**
Uploaded documents in hidden and private groups are being shown in public website newsfeed when you move the file inside the folder, even if the folder visibility is for Group Members only.

**To Reproduce**
1. Go to a private or hidden group 
2. Create a folder inside the selected group
3. Upload the file outside the folder, then move it inside the folder
4. Log out and visit the activity feed
5. See the activity post

**Expected behavior**
Uploaded document should only be visible for Group members

**Screenshots**
https://www.loom.com/share/83f6aed388a647d69c7565af10c077b1

**Environment**
On my dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1593216804/

**Jira issue** : [PROD-769]

[PROD-769]: https://buddyboss.atlassian.net/browse/PROD-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1719444380/177635/
