### ISSUE TITLE
Video is not playing with symbolic links option enabled

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#2761]
**Describe the bug**
Issue happens when you enable symbolic links option in media settings. Videos uploaded are not playing with an error "Video format is not supported. Please download to play.". Also, when you try to browse the video url, it can't be found.

**To Reproduce**
1. Enable symbolic links in media settings.
2. Check the existing videos or upload a new one.
3. You will see error saying "Video format is not supported. Please download to play.".

**Expected behavior**
Videos should work fine with symbolic links enabled.

**Screenshots**
https://www.loom.com/share/403724b78c614a0d91c7cd60e97ad56e

**Environment**
Which site did you replicate this issue on?
Tested on my dev site https://dev-kent.flywheelsites.com/
u: kent
p: password

**Support ticket links**
https://secure.helpscout.net/conversation/1587569919/156324/

**Comment by meetmakadiya** [comment]
@kent-carlo on the latest version (1.7.6) not replicated issue might be fixed on the latest version. please check the attachment 
https://www.loom.com/share/4acccf7d9c86434d8f4fb6555479ac66

**Comment by kent-carlo** [comment]
@meetmakadiya Yes, can't replicate anymore in my dev site. I'm closing this.
