### ISSUE TITLE
Add an option to restrict writing in other users profile wall 

### ISSUE THREAD

**Issue by abde1hakim** [buddyboss/buddyboss-platform#2764]
lately buddyboss added a new feature ,a user can write in other users wall without the wall plugin .
but there is no option to restrict this for only user friends or to desactivate this feature at all.
can you help me to restrict this for only  user friends .so only user friends can write in his/her profile wall .
thanks !

**Comment by mikejyoung** [comment]
Hi @abde1hakim 

Please submit your feature ideas or suggestions here:
https://www.buddyboss.com/roadmap

Issues added to the our backlog need to have been fully scoped and planned by the BuddyBoss product team.

I'm closing this issue here.
