### ISSUE TITLE
Change Password > front end change password function is not working

### ISSUE THREAD

**Issue by milanhirapra** [buddyboss/buddyboss-platform#2767]
**Describe the bug**
When we trying to change the password from the frontend (Account > Login Information) it's not working.

**To Reproduce**

1. Go to Account > Login Information
2. Add **current password**, **Add Your New Password**, and **Repeat Your New Password**
3. It gets redirected to the login page after clicking on the **Save Changes** button.
4. Will enter credentials with the new password but it will not work

**Expected behavior**
The new password should work after being changed from the account page.

**Screenshots**
https://vimeo.com/585756350/fee6fd5457

**Environment**
1) The customer site: https://udzbeniknaklik.com/staging-site-test-/
2) Replicated on local setup

**Support ticket links**
https://secure.helpscout.net/conversation/1578908679/154861?folderId=3709082
https://secure.helpscout.net/conversation/1591310685/156969/
https://secure.helpscout.net/conversation/1596039840/157788?folderId=3701248
https://secure.helpscout.net/conversation/1595728332/157724?folderId=3701248

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1592441126/157151

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1591687709/157024

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1599339672/158389/

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1600274762/158573/

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1599153822/158354/

**Comment by Shamina07** [comment]
https://secure.helpscout.net/conversation/1592161078/157103?folderId=3709082

**Comment by hercivalbuddyboss** [comment]
additional ticket: [https://secure.helpscout.net/conversation/1600952623/158678?folderId=4222127](https://secure.helpscout.net/conversation/1600952623/158678?folderId=4222127)

**Comment by Shamina07** [comment]
https://secure.helpscout.net/conversation/1601913803/158860/

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1606537800/159650/

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1610764420/160422/

**Comment by grahamhoffman** [comment]
https://secure.helpscout.net/conversation/1615704495/161320/
