### ISSUE TITLE
Video Not playing - Sound is though

### ISSUE THREAD

**Issue by chrisdubia** [buddyboss/buddyboss-platform#2779]
After Recent update certain videos that are uploaded no longer play.

1. A thumbnail is generated
2. When you press play, sound only plays if there is sound 
3. m4v file lo longer player at all.  Says not allowed
4. We have tested this on a fresh install with no plugins, live and staging
5. Here is a video https://vimeo.com/manage/videos/586382083/0e6415e9b4

**Comment by chrisdubia** [comment]
Amazing that this is still not fixed after one month.  We opened a ticket almost over a month ago.  Would be great if you would prioritize bugs.  How could a ticket that was submitted after this one already have someone assigned to it - and its about a date?  This is your video uploader tool which does not work

**Comment by tkyser-rodeo** [comment]
The video "feature" they released is half baked garbage, which is made worse by their obviously declining support.

**Comment by chrisdubia** [comment]
Still does not function.  We scrapped the one we built with clipchamp and then ziggeo.  Worked like a charm.

Regret removing it. Would be great to add more supported file types and to provide a better solution to me than sometimes it may or may not work depending upon the file
Type.

Imagine us have to tell our students and teachers this?  Most of them have completely abandoned using the tool￼

I hope some effort is put into fixing this.  It's essentially useless in its current state

**Comment by rmmehta** [comment]
Hello @chrisdubia , 

1) Regarding This, m4v file lo longer player at all. Says not allowed:
Follow this steps:

Step 1: Go to Buddyboss ' Settings' tab
Step 2: In settings tab go to 'Media'
Step 3:  add the video extension m4v there and it's work.

Please see the image:  ![screenshot-dev-riddhi flywheelsites com-2021 09 10-12_38_35](https://user-images.githubusercontent.com/82605214/132814281-a2ac6b12-6429-441f-bff9-9799f874d02a.png)

2) I have checked your video. I have checked you have main two  concern as below,

Point no 1: Normal video link preview is not working 
Point no 2: Video with sound not working , sound is working but video is not working .

with latest releases of the plugin resolved all the issues. I have created the video for the same and in that I have added different  types of video with sound and with out sound. ( for you reference I have added these video [ mp4, mov, m4v])

Please refer this video for point 1: [https://www.loom.com/share/3d536b1608744c56b0761dd88fbab20a](url)

Please refer this video for point 2: [https://www.loom.com/share/b9a59975768043ab96636ef92259172c](url)

Please check form your side. As issue is not there so I closed this one.

Thanks,
