### ISSUE TITLE
Profile date field in repeater > empty value auto converts to date January 1970

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#2780]
**Describe the bug**
Empty value in date field should stay empty and not auto converted to date January 1970. There are cases that it's important to stay empty. E.g. in work experience repeater, you need to leave blank if you still working in present.

**To Reproduce**
1. Add field set with date field under it.
2. In edit profile set the date to blank.
3. You will see that it will auto convert to date January 1970.

**Expected behavior**
Empty date value should stay empty.

**Screenshots**
http://somup.com/crjlFhYsfg

**Environment**
https://staging2.engineerly.io/

**Support ticket links**
https://secure.helpscout.net/conversation/1598403327/158236?folderId=3709082

**Jira issue** : [PROD-765]

[PROD-765]: https://buddyboss.atlassian.net/browse/PROD-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mahedihasannoman** [comment]
Wrong PR linked with this issue. Please ignore the above PR: 
Document is not opening in popup for network search - Fixed #2785
