### ISSUE TITLE
Video is not working on popup > When the video post is posted on the other's timeline the video is not working in the expanded popup

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2792]
**Describe the bug**
When the video post is posted on the other's timeline the video is not working in the expanded popup. this video is working fine with pop-up on news feed but not working on other's member timeline feed.

**To Reproduce**
1. Go to any Member's timeline
2. add any video on other member's time line
3. go to 'Mentions' on other member's time line
4. open video pop-up and see the error 

**Expected behavior**
The video should working fine in pop up for other member's timeline.

**Screenshots**
dev site recording: http://somup.com/crjb2hYPxr
client recording: https://www.screencast.com/t/jRfhm8a2B

**Environment**
I have replicate this issue on client's site as well as on my dev site too.

**Support ticket links**
https://secure.helpscout.net/conversation/1602283050/158926/

**Jira issue** : [PROD-763]

[PROD-763]: https://buddyboss.atlassian.net/browse/PROD-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by amincdev** [comment]
@chetansatasiya @KartikSuthar I have looked into this issue and found that when opening a video popup the ajax response have video_data empty: https://ibb.co/p0TcbSV
