### ISSUE TITLE
Compatibility issue of BBpress version with Buddyboss Platform

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2799]
Describe the bug
Currently we are using bbPress 2.5.14-6684 and having issues with their GD topic polls for bbpress plugins saying that it doesn't work well because BuddyBoss is behind the bbPress updates.

To Reproduce

Go to 'plugin'
Installed "GD Topic Polls for bbPress" plugin
https://wordpress.org/plugins/gd-topic-polls/
Then Got the message "system requirements check for GD topic polls for bbpress failed.
This plugin requires bbpress version 2.6.2 (your system runs version 2.5.14-6684).
The plugin will now be disabled
See error
Expected behavior
BBpress version should be updated in Buddyboss Platform.

Screenshots
https://ibb.co/ZNch1Ft
https://ibb.co/k3XN3MM

Support ticket links
https://secure.helpscout.net/conversation/1590539910/156831?folderId=4265312

**Comment by rmmehta** [comment]
Hello @shyamgudadhe ,

We can't do anything on this as this plugin is compatible with the BBPress not with BuddyBoss Platform. They need to contact the plugin author to make it compatible.

So, Close this issue.

Thanks,
