### ISSUE TITLE
Multisite > news feed images only displays in site where it's uploaded

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#2805]
**Describe the bug**
Multisite news feed images is broken in other sites. It's only visible in site where it's uploaded.

**To Reproduce**
1. Test site should be in multisite.
2. Post image in Site A news feed.
3. Go to Site B news feed page.
4. You can see the image is broken.

**Expected behavior**
Image should still properly shows even it's viewed from other site.

**Screenshots**
https://www.loom.com/share/ced4d036e06a411fb944aa5c965cb391

**Environment**
Which site did you replicate this issue on?
http://bb-tier1-mu.flywheelsites.com/

**Support ticket links**
https://secure.helpscout.net/conversation/1584323955/155770/

**Jira issue** : [PROD-760]

[PROD-760]: https://buddyboss.atlassian.net/browse/PROD-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hercivalbuddyboss** [comment]
same client but different ticket: https://secure.helpscout.net/conversation/1618893825/161890

**Comment by mahedihasannoman** [comment]
Same issue is happening with link preview feature.

**Comment by dipskakadiya** [comment]
Related issue : https://github.com/buddyboss/buddyboss-platform/pull/2945

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1605098160/159440
