### ISSUE TITLE
Version 1.6.2 after upgrade to version 1.7.5 photos deleted

### ISSUE THREAD

**Issue by johnnyhh123** [buddyboss/buddyboss-platform#2807]
My Buddyboss version is version 1.6.2. if i want to upgrade to version 1.7.5, all pictures of the community are deleted. I don't know why that could be.

**Comment by chetansatasiya** [comment]
@johnnyhh123 Create a support ticket with us and will help you to fix the issue. In any release, we haven't deleted any pictures.

**Comment by johnnyhh123** [comment]
@chetansatasiya I turned to buddyboss. They said I should describe the problem here.

After the upgrade, all images that were uploaded via buddyboss disappeared from Wordpress media. also from the buddyboss feed.

**Comment by chetansatasiya** [comment]
@johnnyhh123 Can you disable the **Symbolic Links** as per settings here https://prnt.sc/1qsawld and reset the permalink and see the images are showing or not?

Regarding the remove media from the WordPress Media as we did that changes on our release `1.7.0` and we hide all the media uploaded via BuddyBoss Platform.
