### ISSUE TITLE
Multisite- Database error when bp-root-blog enabled

### ISSUE THREAD

**Issue by gastronimo** [buddyboss/buddyboss-platform#2815]
Describe the bug
When converting existing BuddyPress multisite installation (defining ‘bp-root-blog’ in wp-config) to Buddyboss platform, the Buddyboss Components page Member Profiles>Settings and Profile Fields> Edit fields settings are not enabled/do not appear, and within the Settings page the Profile Names and Profile Photos sections are missing options.
The issue is only reproducible with BuddyBoss Platform activated 
The issue also occurs when BuddyBoss Theme is disabled 

To Reproduce
    1. define( 'BP_ROOT_BLOG', 20 ); in BP multisite install (BP network activated)
    2. Network Deactivate BuddyPress plugin
    3. Network Activate Buddyboss Platform plugin
    4. Navigate to Buddyboss Components admin page, 
    5. Navigate to Buddyboss Settings admin page- under Profile: Display Name fields are not selectable, Profile Cover Images>Allow members to upload cover images does not appear
    6. A PHP Notice and database error are produced:
PHP Notice:  Undefined property: stdClass::$table_name_groups in /home/mysite/public_html/wp-content/plugins/buddyboss-platform/bp-xprofile/classes/class-bp-xprofile-group.php on line 319

WordPress database error Table 'my_db.g' doesn't exist for query SELECT DISTINCT g.id FROM  g  ORDER BY g.group_order ASC made by require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, bp_admin_init, do_action('bp_admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, bp_register_admin_settings, do_action('bp_register_admin_settings'), WP_Hook->do_action, WP_Hook->apply_filters, BP_Admin->register_admin_settings, require_once('/plugins/buddyboss-platform/bp-core/admin/settings/bp-admin-setting-search.php'), BP_Admin_Tab->__construct, BP_Admin_Setting_Search->register_fields, bp_search_get_settings_fields_for_section, bp_search_get_settings_fields, bp_xprofile_get_groups, BP_XProfile_Group::get

Expected behavior
Continue using existing BP member subsite as the BBP member site...any existing BuddyPress site should be able to easily switch to BuddyBoss Platform, and continue to work as normal with minimal effort. The site owner may need to adjust some admin options, and update their theme, but nothing beyond that. This requires that data from BuddyPress continues to work when a user switches to BuddyBoss Platform. 

Screenshots
only upon request

Environment
Which site did you replicate this issue on?
Staging site

**Jira issue** : [PROD-757]

[PROD-757]: https://buddyboss.atlassian.net/browse/PROD-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by BrandonCurrentDebate** [comment]
I have the same error.

**Comment by gastronimo** [comment]
UPDATE- Aug 30:

So I commented out define( 'BP_ROOT_BLOG', 20 ), to see what Buddyboss settings I could configure on my community subsite where I had BuddyPress installed before.  It turns out that all the forums and discussions are still available there, but the Groups I had beautifully set up are not.  They are only visible on the main site.

Because I really do not wish to revert to BuddyPress, I am going to test how this affects snetwork/site registrations and group sign-ups, until BuddBoss support can address this issue for good.

**Comment by kent-carlo** [comment]
@gastronimo I tried replicating in my localhost and can't reproduce the same issue. If you could provide more information e.g. what components or plugins were active, it will really be a big help debugging the issue and will appreciate it. Thanks

**Comment by gastronimo** [comment]
@kent-carlo

Thanks for your attention to this issue!

I just went back to check on the staging site, I currently have these plugins network activated:
BuddybossPlatform v1.7.7, 
Enhanced Plugin Admin 
Heartbeat API Control for WPMS 
IP Location Block
Multisite Enhancements 
Multisite Plugin Manager 
Multisite Toolbar Additions 

with no other plugins active on the BP/BBP subsite

Good news is that as of today all the profile settings and profile fields now appear and I can view all groups on the defined bp-root subsite!  Maybe it was the platform update?

However, I have now lost my previous group hierarchies (very important) from the old BP Group Hierarchies plugin- tell me if maybe thats another issue? I suppose I have to redo that manually

**Comment by kent-carlo** [comment]
@gastronimo glad to know that all the profile settings and profile fields now appear and you can view all groups on the defined bp-root subsite already. As for the group hierarchies issue, I will try to validate it, submit an issue if ever, and will let you know. Thank you.

**Comment by gastronimo** [comment]
@kent-carlo,

As for group hierarchies, I was using the plugin Hierarchical Groups for BP Version 1.0.0  By dcavins.

I should report that within the past few days all I have done was update a few plugins and reintroduce on BP-root-blog lost Group Types, I have not yet applied group types to my preexisting groups, BUT...

I again have the problem where on the Buddyboss Components page Member Profiles>Settings link is not enabled/does not appear- this is running BBP 1.7.7, WP 5.8, and the same network-activated plugins as above.  

And I again receive these SUBSITE DB errors:
PHP Notice:  Undefined property: stdClass::$table_name_groups in /home/popul8/public_html/wp-content/plugins/buddyboss-platform/bp-xprofile/classes/class-bp-xprofile-group.php on line 319

[20-Sep-2021 14:48:52 UTC] WordPress database error Table 'mydb_live.g' doesn't exist for query SELECT DISTINCT g.id FROM  g  ORDER BY g.group_order ASC made by require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, bp_admin_init, do_action('bp_admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, bp_register_admin_settings, do_action('bp_register_admin_settings'), WP_Hook->do_action, WP_Hook->apply_filters, BP_Admin->register_admin_settings, require_once('/plugins/buddyboss-platform/bp-core/admin/settings/bp-admin-setting-search.php'), BP_Admin_Tab->__construct, BP_Admin_Setting_Search->register_fields, bp_search_get_settings_fields_for_section, bp_search_get_settings_fields, bp_xprofile_get_groups, BP_XProfile_Group::get
[20-Sep-2021 14:48:52 UTC] PHP Notice:  Undefined property: stdClass::$table_name_groups in /home/mysite/public_html/wp-content/plugins/buddyboss-platform/bp-xprofile/classes/class-bp-xprofile-group.php on line 319

And a new one:
 PHP Deprecated:  bp_core_get_avatar_data_url_filter is <strong>deprecated</strong> since version 1.5.2 with no alternative available. in /home/mysite/public_html/wp-includes/functions.php on line 4871

Also, from the Buddyboss>Profile Settings page, when I click on Profile Search tab, I get redirected to the site Dashboard!  And clicking on the Profile Navigation tab redirects me to the home page Customizer options

So, the only thing that really changed for the better is access to the profile settings page and complete profile fields tabs.

**Comment by surajkrsingh** [comment]
I am just validating the issue.
Not able to replicate the database error if you mentioned the correct `define( 'BP_ROOT_BLOG', 1 )` .

And I am not sure that we are supporting this `Hierarchical Groups for BP` plugin for our platform because the platform already has Group Hierarchies features under settings > group > Group Hierarchies.

@kent-carlo we can close it if no longer a valid issue.
