### ISSUE TITLE
New tag does not add when tag exists with same slug

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#2858]
**Describe the bug**
 new tag does not add when tag exists with same slug https://i.imgur.com/sU8RO4b.png

**To Reproduce**
1. Create a discussion topic with tag like "@c#"
2. Edit the topic and add new tag like "@c++"
3. Save it and check the tags 
4. See that "@c++" does not add

**Expected behavior**
New tags with the same slug should be added

**Screenshots**
https://i.imgur.com/sU8RO4b.png

**Related platform api issue**
https://github.com/buddyboss/buddyboss-platform-api/issues/326

**Related app native issue for QA**
https://github.com/buddyboss/buddyboss-app-native/issues/1598

**Comment by shakilAshraful** [comment]
@sadrul Bhai, the bug persists in API as well. this needs platform-api PR as well.

Sharing a sample POST bellow, 
```
curl -X POST  -H "accept:application/json, text/plain, */*" -H "content-type:application/json;charset=utf-8" -H "keep-alive:true" -H "connection:keep-alive" -H "accesstoken:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYmItYXBwLXBsYXRmb3JtLmZseXdoZWVsc2l0ZXMuY29tOnJlc3QtYXBpIiwiaWF0IjoxNjMxMDkxMzg1LCJuYmYiOjE2MzEwOTEzODUsImV4cCI6MTYzODg2NzM4NSwianRpIjoiRE12bilJOEJeTHlNc3JLNFQ1YUFjTVdDcTNUUDkpV0Z1YTNJZ15OYjcpRiIsImRhdGEiOnsidXNlciI6eyJpZCI6IjE3In19fQ.-ne2pR18AgH5uKZ-fcvD9wJTx8gveEn5CfF7V_38Itw" -H "appid:dd4a7c" -H "appversion:2.0.1" -H "appcodeversion:1.3.2" -H "appplatform:ios" https://bb-app-platform.flywheelsites.com/wp-json/buddyboss/v1/topics -d '{"title":"Tag test by shakil","content":"Tag test content by shakil","parent":10332,"status":"publish","type":"unstick","subscribe":false,"topic_tags":"@c++,@c#*","bbp_media":[],"bbp_documents":[]}'
```

video: https://www.loom.com/share/1a6fc5667e6b4ec9809582cfc153e49a
