### ISSUE TITLE
Forum Replies have a blank post_title field

### ISSUE THREAD

**Issue by nickchomey** [buddyboss/buddyboss-platform#2878]
**Describe the bug**
​When you create a reply in the forum, they get saved in the database with a blank post_title field. Yet, when you move, split, merge, etc... they receive a title of "Reply To: [topic title]". So, clearly there is no problem with having a title and this is just an oversight.
Moreover, I notice that there is a function (which doesn't seem to get used anywhere in the code) called bbp_get_reply_title_fallback, which exists to specifically apply this title to an empty reply title.

I noticed it previously, but only addressed it now when this caused a major conflict with a search plugin when it tries to index the new reply.
I have remedied this with the following snippet, but I figure this should be fixed in the platform code for the sake of all BB platform users.

```

add_filter('bbp_new_reply_pre_insert','reply_add_title');

function reply_add_title($reply_data) {

$reply_data['post_title'] = "Reply To: " . bbp_get_topic_title( $reply_data['post_parent']);

return $reply_data;

}

```
Please see the attached video for evidence

**To Reproduce**
1. Create a reply in any forum

**Expected behavior**
A post_title is generated in the wp_posts database table

**Screenshots**

https://user-images.githubusercontent.com/88559987/132029009-321ae38d-f7e1-4136-b8e7-204392740e69.mp4

**Support ticket links**
BuddyBoss support ticket #162231

**Jira issue** : [PROD-749]

[PROD-749]: https://buddyboss.atlassian.net/browse/PROD-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kishanjasani** [comment]
@nickchomey Not able to replicate this issue with the latest platform code. 
`Reply To` text is added in your post title because you have added a custom code snippet. It's not an bug it's intentionally disabled the reply to title in platform.

Thanks for reporting.

**Comment by kishanjasani** [comment]
@nickchomey Thanks for the feedback again! Let's wait for the senior developer's view on this issue.

Needs your suggestion on this issue.
cc: @chetansatasiya @KartikSuthar
