### ISSUE TITLE
When replying to any forum reply it always shows the name of the person who created the discussion in notification

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#2879]
**Describe the bug**
When replying to any forum reply it always shows the name of the person who created the discussion. This issue is happening in our demo as well. See the video: 

https://www.loom.com/share/f6499c6e1c084b2fb62c8ff24cd4a631

**To Reproduce**
See the above video.

**Environment**
Demo, local & client site

**Support ticket links**
https://secure.helpscout.net/conversation/1615546025/161296/

**Jira issue** : [PROD-748]

[PROD-748]: https://buddyboss.atlassian.net/browse/PROD-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Gabrymi93** [comment]
+1

**Comment by ReoVincent** [comment]
Related concern https://secure.helpscout.net/conversation/1641672384/165803/

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1707233309/175439/
