### ISSUE TITLE
fixing gif in activity posts and comments

### ISSUE THREAD

**Issue by abde1hakim** [buddyboss/buddyboss-platform#2882]
### Scope
gif when used in comments replys they look so big and also when used in activity feed sometimes gif doesn't fit the screen
[bbgif.txt](https://github.com/buddyboss/buddyboss-platform/files/7112344/bbgif.txt)

### just copy css code in custom.css in your child theme and it will be fixed

**Comment by amincdev** [comment]
The size of Gif in posts and comments seems fine and does not need any changes.
