### ISSUE TITLE
Multisite >> Profile picture not showing on a Multisite network

### ISSUE THREAD

**Issue by milanhirapra** [buddyboss/buddyboss-platform#2885]
**Describe the bug**
Create a multi-site network with subsites and activate BB Platform on all subsites. Go to any user profile and change/update the profile picture and the latest updated profile picture appear on the current site user but it doesn't appear on other sites.

**To Reproduce**

1. Create a multi-site network with subsites
2. Activate BB Platform on all sites.
3. Go to any user profile of any main/sub-site
4. Change/update profile picture and it will appear on the current site user
5. But it doesn't appear on other sites user

**Expected behavior**
If change/update profile of any user then it should appear on other sites same user also.

**Screenshots**
https://vimeo.com/598754157/605e6c3c40

**Environment**
Demo, local & client site

**Support ticket links**
https://secure.helpscout.net/conversation/1605098160/159440/

**Jira issue** : [PROD-747]

[PROD-747]: https://buddyboss.atlassian.net/browse/PROD-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by surajkrsingh** [comment]
I am able to replicate this issue with a multisite setup.
**See this** - https://www.loom.com/share/40355551a8b649828cc3f6899de0a36d
