### ISSUE TITLE
Research scope for Bunny.Net integration

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#2892]
We are conducting research into how we can integrate with Bunny.Net to deliver Video Compression & Offloading to customers using the [Bunny.Net Stream](https://bunny.net/stream/) service.

We need to consider the following scope in the research:

- [ ] **How will customers connect their site to Bunny.Net?**

- What fields are needed? (API Key, etc)
- How is the connection maintained?
- Is it re-checked periodically? Is it cached?
- What errors do we need to account for?

- [ ] **How will me manage problems with a Bunny.Net account (payment issues, plan limit reached, etc)?** 

- Are we able to retrieve these statuses via the API?
- Can we communicate the exact error to customers?

- [ ] **What is the exact flow for uploading/compressing videos to Bunny.Net?**

- What APIs will we use to upload videos?
- How will we retrieve statues of uploading/compression?
- Which errors do we need to account for?
- Where will the Bunny.Net URL be stored in WordPress?
- Will we keep the original file on the server? Can we provide this as an option to customers - if so, how?
- Will members need to wait till compression is completed before they can view? Can we use the original file until compression is done - if so, how?
- What APIs will we use to retrieve videos? What options are available?
- Can we play the Bunny.Net URL in our existing players (web and app) - if not, what changes do we need to make to the players?

- [ ] **What happens if a customer deletes a video in Bunny.Net?**

- What will show on their site/app?
- What errors do we need to account for?

- [ ] **How do we allow customers to upload their existing video library to Bunny.Net?**

- What is the workflow for doing this?
- How do we manage performance for large libraries?
- What errors do we need to account for?

- [ ] **How do we allow customers who wish to leave Bunny.Net download their videos back to their server?**

- What is the workflow for doing this?
- How do we manage performance for large libraries?
- What errors do we need to account for?

-------

In all research, include as much detail as possible. Specify which APIs will be used. It is recommended to use flow charts/diagrams when demonstrating workflows. 

**Jira issue** : [PROD-746]

[PROD-746]: https://buddyboss.atlassian.net/browse/PROD-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chetansatasiya** [comment]
I am planning to start research with the below points.

1. Review all the APIs.
2. Review the webhooks.
3. Review the compression.
4. Review the player.
5. Review the different compression methods.
6. Review all the video options.
7. Review the speed of upload & download.
8. Review the security options for the video like an access token & other options.
9. Review the storage things.

**Comment by mikejyoung** [comment]
@chetansatasiya 
I will identify the use cases we want to achieve in the integration to assist your technical review.

**Comment by chetansatasiya** [comment]
@mikejyoung @sourabhmatolia Adding all the things here related to research https://docs.google.com/document/d/1GnRiZTAwRrboW--if_zoXL36RJIHPFNT88QmOOiaoZk/edit#heading=h.hvaajlntnuof

**Comment by sourabhmatolia** [comment]
**UPDATE**

@chetansatasiya still working on this task doing R & D

**Comment by chetansatasiya** [comment]
@mikejyoung 

As discussed on call you will create a full scope with all the pieces of stuff and then we can go ahead with this integration as I checked it will work with the platform and we can implement it easily.

CC @sourabhmatolia @firozwp

**Comment by nickchomey** [comment]
I'm sure you guys have a good idea by now of what needs to be done, but I just found this plugin that might be useful as a reference point while developing this feature. https://wordpress.org/plugins/bunnycdnbunnyapi/
