### ISSUE TITLE
Generating video thumbnail stuck at loading

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#2906]
**Describe the bug**
When ffmpeg is installed in server and adding video, generating thumbnail stuck at loading. In my test, waited around 10 mins.

**To Reproduce**
1. Make sure site has ffmpeg installed, in my case I tested in demo site.
2. Upload video and trying changing thumbnail.
3. See that generating thumbnail stuck at loading.

**Expected behavior**
Should generate thumbnail.

**Screenshots**
https://www.loom.com/share/21ce639e9d264c34bd98fa3cc6524e15

**Environment**
Which site did you replicate this issue on?
Replicated on buddyboss demo site.

**Support ticket links**
https://secure.helpscout.net/conversation/1579569633/154974/

**Jira issue** : [PROD-743]

[PROD-743]: https://buddyboss.atlassian.net/browse/PROD-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ExoGeek** [comment]
I've got the same issue on my system (Ubuntu + FFMPEG).

**Comment by rmmehta** [comment]
https://secure.helpscout.net/conversation/1699842380/174350/
