### ISSUE TITLE
Forum Home page not working

### ISSUE THREAD

**Issue by AnneeSam** [buddyboss/buddyboss-platform#2918]
When installing the Permalink manager lite or permalink manager pro, the BuddyBoss platform forum home page not loaded/working. Can you please fix the issue asap.

**Comment by Nivasp** [comment]
Yes, I'm also facing the same issue in BuddyBoss forum

**Comment by bb-yudhisthir** [comment]
@AnneeSam @Nivasp Please note its the third party plugin ( Permalink manager lite or permalink manager pro) issue, after reset and removing all settings and the generated custom permalinks by this plugin from the Debug settings working fine again.

 ![image](https://user-images.githubusercontent.com/80085922/134163524-74cabe53-c26c-438d-98f4-53d20a0342ce.png)
