### ISSUE TITLE
Vulnerability with the document download feature

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#2920]
**Describe the bug**
Document download feature within the file wp-content/plugins/buddyboss-platform/bp-document/bp-document-filters.php bp_document_download_url_file function has vulnerabilities 

* Any one can download the private files if they change the document_file parameter with the one having the public access

* By iterating value of attachment parameter value from 1 to 300, below are presented responses which
are containing value of attachment parameter (request column), status and length of the HTTP
response. URL is the same as in previous finding:

![image](https://user-images.githubusercontent.com/80085922/133027484-88326d55-9cc5-462b-bb8d-3869b4b960cf.png)

**To Reproduce**
1. Go to documents and upload two documents one with public access and the other with the only me
2. Copy the URL of the Only Me one and paste in the incognito after replacing the download_document_file parameter same as the public document one
3. You can download it even its private
4. Similarly the attachment parameter iterating over with ids make us able to download files

**Expected behavior**
Private documents should not be accessed also the hash can be used instead of the id directly

**Screenshots**
https://screencast-o-matic.com/watch/crQIh1VQ88a

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
https://secure.helpscout.net/conversation/1622559778/162553/

**Comment by ExoGeek** [comment]
I've also tested on my system and I can reproduce the vulnerability !

Thanks @bb-yudhisthir for reporting it !

**Comment by chetansatasiya** [comment]
@ExoGeek @bb-yudhisthir Can you guys test if #2938 Fix the issue or not?
