### ISSUE TITLE
users not getting email notification for group message when email preference of private message set to NO

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#2927]
**Describe the bug**
users not getting email notification for group message when email preference of private message set to NO, though group sends message email preference is set to YES.

**To Reproduce**
1. Go to a group page
2. Switch to group admin
3. Set some members email preference like this https://i.imgur.com/yCbH6T9.png (private message NO, group message YES)
3. Send message > Send group message
4. See those members will not receive email notification

**Expected behavior**
member with email preference "private message NO, group message YES" should receive email for group public message notification

**Screenshots**
https://i.imgur.com/yCbH6T9.png
https://www.loom.com/share/a3e700d91b644073b1db631a308f48ab

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

**Note:**
Member with email preference "A group sends you a new message" NO then also member getting the mail. 

**Expected behavior**
Member should not receive mail if email preference is NO.
