### ISSUE TITLE
Send Invites email link issue

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2932]
**Describe the bug**
 If you enable email invites and sent to a user email if they click the link they will be routed to the registration form which their email is auto-populated on it.

**To Reproduce**
1. Go to '.Send Invites, add email id > send email'
2. Check email', If we enable email invites and sent to a user email if they click the link they will be routed to the registration form which their email is auto-populated on it.
3.If they happen to know how they can forward the link to another person and that person will click it, they will still be able to reach the registration form however the email of the first receiver of the link will still auto-populate. But the 2nd receiver can just change the email to his email to complete the registration and will receive an activation email link to activate the account.

**Expected behavior**
The link should be expired if a registration has been done once with it.

**Screenshots**
https://im.ge/i/image-1.Twjl0m
https://im.ge/i/image-2.TwjTV1
https://im.ge/i/image-3.TwjueW
https://im.ge/i/image-4.Twjrgr
https://im.ge/i/image-5.TwjXlf
https://im.ge/i/image-6.Twj2vc
https://im.ge/i/image-7.TwjOD0
https://im.ge/i/image-8.Twj1ET
https://im.ge/i/image-9.TwjdSL
https://im.ge/i/image-10.Twjq6G
https://im.ge/i/image-11.TwjsVx
https://im.ge/i/image-12.TwjD0J
https://im.ge/i/image.Twj7ra

**Environment**
Dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1626573777/163242?folderId=4265312

**Comment by bb-yudhisthir** [comment]
@shyamgudadhe Closing this GitHub issue as its the default behavior with auto populate the email address, also the link gives the message if you try to change the email
![image](https://user-images.githubusercontent.com/80085922/134881601-caeb62b2-1a6a-446b-8cc0-1acd140f7b23.png)
