### ISSUE TITLE
Checkout page > Removing a product from basket clears some billing details

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2944]
**Describe the bug**
When removing a product from the cart, some billing information is being cleared off (such as company, phone number, name ) 

More over when we refresh the cart page it will cleared off above belling information.

**To Reproduce**
1. Go to 'product page'
2. Click on add two or three products on cart
3. Go to ' Check out page'
4. Remove any product or refresh the checkout page.
5. see the error

**Expected behavior**
The billing details should not remove on product delete or page refresh.

**Screenshots**
Client video:  https://jumpshare.com/v/PciQNu1Xk7mycODombYY

Our demo site video:  https://www.loom.com/share/9179fa978cf445f3b244328d6bf5a833

**Environment**
It's replicate on client site and on our demo site as well.

**Support ticket links**
https://secure.helpscout.net/conversation/1629070826/163711/

**Comment by bb-yudhisthir** [comment]
@rmmehta Closing this issue as its the default behavior of the woocommerce on checkout page reload
