### ISSUE TITLE
Double spacing is been added after using @name in the mentions

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2946]
**Describe the bug**
After mentioning someone with @ the platform inserts after the users name 2xspace.

**To Reproduce**
1. please go online https://demos.buddyboss.com/online-communities/ 
2. In the Activity Feed mention some member
3. after you write @ see the issue with extra space

**Expected behavior**
It should take only one space not two space.

**Screenshots**
![2021-09-08_12-52-25](https://user-images.githubusercontent.com/82605214/133615115-bc355809-68ad-4111-a35d-946b8b37a63d.jpg)

**Environment**
client site as well on my deb site and on our demo site.

**Support ticket links**
https://secure.helpscout.net/conversation/1624690423/0/?folderId=3709082

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1653299501/167657
