### ISSUE TITLE
bbp_filter_sample_permalink

### ISSUE THREAD

**Issue by JessicaPeppit** [buddyboss/buddyboss-platform#2954]
I get this error: Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'bbp_filter_sample_permalink' not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php on line 303

I am using Avada and Avada childtheme. 

Buddyboss Plattform Version 1.7.7.1

Please advice.

**Comment by bb-yudhisthir** [comment]
@JessicaPeppit Please check after switching to default theme like twenty twenty one, if the issue doesn't appears please check with the Avada Theme support, also meanwhile can you send us Avada Theme Zip files

**Comment by bb-yudhisthir** [comment]
@JessicaPeppit Checked at our dev site with Avada Theme version 5.0.6 long with the buddyboss platform 1.7.7.1 working fine and no such issue, closing this issue
