### ISSUE TITLE
Popup not good for large monitors.

### ISSUE THREAD

**Issue by parmarhardip** [buddyboss/buddyboss-platform#2955]
**Describe the bug**
Video explanation - https://www.loom.com/share/3cc8d805509e420aba77939833966015

**To Reproduce**
1. open `wp-admin/?hello=buddyboss` popup in large monitors and see the issue.

**Expected behavior**
should be add max height.

**Screenshots**
https://www.loom.com/share/3cc8d805509e420aba77939833966015

More explanation on buddyboss app task: https://github.com/buddyboss/buddyboss-app/pull/2420#issuecomment-922098014

**Jira issue** : [PROD-737]

[PROD-737]: https://buddyboss.atlassian.net/browse/PROD-737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by harshalQA** [comment]
Fixed: Below PR will fixed this issue.

PR: https://github.com/buddyboss/buddyboss-app/pull/2420#issuecomment-922860315

**Comment by amincdev** [comment]
> Fixed: Below PR will fixed this issue.
> 
> PR: [buddyboss/buddyboss-app#2420 (comment)](https://github.com/buddyboss/buddyboss-app/pull/2420#issuecomment-922860315)

@harshalQA This task is done for bb-app popup and not for platform popup. Work is still pending here. Please remove `ready for release` tag from this issue.
