### ISSUE TITLE
Frontend/Styling/Look and Feel BuddyBoss Theme issues - No response on the original link

### ISSUE THREAD

**Issue by 007ke** [buddyboss/buddyboss-platform#2964]
**This is a duplicate issue logged as there is no response from the buddyboss team on the original issue link here**

https://github.com/buddyboss/buddyboss-platform/issues/1357

@chetansatasiya 
@sourabhmatolia 
@amincdev 
@eisenwasser 
@marienel21

**Comment by eisenwasser** [comment]
Closing this issue. We will work on the original one.

We are aware of this, it is in the pipeline to be resolved, thanks.
