### ISSUE TITLE
Profile type not correctly being assigned when inviting to site

### ISSUE THREAD

**Issue by chrisdubia** [buddyboss/buddyboss-platform#2965]
We implement the profile type option in buddy boss and created three 4 types

Administrator
Teacher
Student
Guest

When using Send Invite via the front end of the site our Administrators (Buddyboss profile type) are the only ones that can invite and also can choose to assign Buddyboss profile type upon invite.

Buddyboss Administrators are able to send the invite, but the profile type does not correctly get assigned.  The profile type that is getting assigned is Member - which is not a Profile type that we created.

We have tested this on Staging as well with no plugins activated or custom code.

To replicate this:

Login to your Sandbox or site

Go you your profile image in the upper right corner
Send Invite - make sure to choose a profile type
Accept the invite and register as the new user
Login as the  new user
You will see that the profile type that is assigned it Member

**Comment by milanhirapra** [comment]
Hi @chrisdubia 
I am unable to replicate this issue in the latest version of the BB Platform.
Please check here: https://vimeo.com/630945582/113176e129
