### ISSUE TITLE
Symlink issue

### ISSUE THREAD

**Issue by tejasvarmaT1** [buddyboss/buddyboss-platform#2970]
**Describe the bug**
after updating to the new version of the buddy boss platform I am not able to log in to my dashboard and even the activity on the home page is not loading. 

**error**
There has been a critical error on this website. Please check your site admin email inbox for instructions.

**it is also showing me this error**
Fatal error: Uncaught Error: Call to undefined function symlink() in /home/u499492541/domains/legendaryunite.com/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php:5765 Stack trace: #0 
/home/u499492541/domains/legendaryunite.com/public_html/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-schema.php(90): bb_core_enable_default_symlink_support() #1 /home/u499492541/domains/legendaryunite.com/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-update.php(225): bp_core_install() #2 
/home/u499492541/domains/legendaryunite.com/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-update.php(156): bp_version_updater() #3 
/home/u499492541/domains/legendaryunite.com/public_html/wp-includes/class-wp-hook.php(303): bp_setup_updater() #4 /home/u499492541/domains/legendaryunite.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #5 
/home/u499492541/domains/legendaryunite.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action() #6 /home/u499492541/domains/legendaryunite.com/public_html/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-actions.php(126): do_action() #7 
/home/u499492541/domains/legendaryunite.com/public_html/wp-includes/class-wp-hook.php(303): bp_admin_init() #8 
/home/u499492541/domains/legendaryunite.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #9 
/home/u499492541/domains/legendaryunite.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action() #10 
/home/u499492541/domains/legendaryunite.com/public_html/wp-admin/admin.php(175): do_action() #11 
/home/u499492541/domains/legendaryunite.com/public_html/wp-admin/index.php(10): require_once('/home/u49949254...') #12 {main} thrown in 
**/home/u499492541/domains/legendaryunite.com/public_html/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php on line 5765**

**link to my website**
https://legendaryunite.com/wp-admin/

**Comment by chetansatasiya** [comment]
@tejasvarmaT1 Can you create the support ticket with us from your BuddyBoss account and will check it for you?

**Comment by mahedihasannoman** [comment]
@tejasvarmaT1 This is a server side problem. symlink() is php default function you can see it here: https://www.php.net/manual/en/function.symlink.php
Probably symlink is disabled from server side that's why the above error is showing on your WP site. As it is not a BuddyBoss Platform issue, I am closing this issue.
