### ISSUE TITLE
404 error for "video-js-rtl.min.css" when using RTL site language

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#3000]
**Describe the bug**
Console error 404 error for "video-js-rtl.min.css" when using RTL site language
There is no rtl css files for buddyboss-platform/src/bp-core/css/vendor/video-js.css file. 

**To Reproduce**
1. With only BB Platform plugin active and default theme, change to any language with RTL format.
2. Visit any page on the frontend. See Error: https://prnt.sc/1u84pc6

**Expected behavior**
Should not show 404 error

**Screenshots**
https://prnt.sc/1u84pc6

**Environment**
dev site, demo site

**Support ticket links**
https://secure.helpscout.net/conversation/1641508321/165776?folderId=3709082

**Jira issue** : [PROD-731]

[PROD-731]: https://buddyboss.atlassian.net/browse/PROD-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by patilswapnilv** [comment]
https://secure.helpscout.net/conversation/1677222896/171053
