### ISSUE TITLE
404 on hidden group invite click

### ISSUE THREAD

**Issue by vajidbb** [buddyboss/buddyboss-platform#3007]
**Describe the bug**
Users are facing 404 when they try to navigate to hidden group from invitation

**To Reproduce**
follow steps from https://github.com/buddyboss/buddyboss-app-native/issues/1624

**Expected behavior**
User should land on the correct page

**Screenshots**
https://www.loom.com/share/442db5d3a1944d97ac6b6ebc2da04c59?sharedAppSource=personal_library

**Environment**
https://bb-app-platform.flywheelsites.com/

**Comment by chetansatasiya** [comment]
Closing this as it's a duplicate of https://github.com/buddyboss/buddyboss-platform/issues/2209
