### ISSUE TITLE
'Request Access' tab stuck in private Groups

### ISSUE THREAD

**Issue by kishanjasani** [buddyboss/buddyboss-platform#3020]
**Describe the bug**
The issue is related to the "Request Access" tab on the private group page
when the user requests access the "Request Access" tab shows up and when the admin accepts the request then this tab is not visible anymore.
But when the admin grants access from the WP-admin > Users > the specific user > scroll down > User Enrolled in group > grants access > Saves the changes.

Then the "Request Access" tab still shows up.

**To Reproduce**
1. Screenshot of the User Enroll in group field in the Users admin page (this is added by LearnDash) - https://snipboard.io/6okZ2P.jpg
2. Screenshot this is how the group looks like to the user when the request is still pending (correct behavior no issue here) - https://snipboard.io/JISmPx.jpg
3. Screenshot this is how the group looks when the request has been accepted by the admin in the backend - https://snipboard.io/lktVrO.jpg

Please make sure that the Group Sync is enabled between the LearnDash Group and the BB Social Group - https://snipboard.io/t0FYLp.jpg

The issue is replicable on dev and demo site.

**Support ticket links**
https://secure.helpscout.net/conversation/1650458517/167184/

**Comment by ngolwalkar** [comment]
The section to grant access to the group is added by the Learndash plugin, So that is not the BuddyBoss or platform issue.

**Comment by meetmakadiya** [comment]
I believe we can close this issue for now. If this issue comes up again, feel free to comment on the details here to reopen this issue.
