### ISSUE TITLE
Performance issue - Lots of duplicate queries for @mention when activity feed is rendering

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#3070]
**Describe the bug**
In activity feed rendering there are 8-12 duplicate queries (depending on settings) for a single @mention which causing a huge performance drop when there are multiple @mention and make the activity feed page unuseable for large data site.

Please see this video for details and replication: https://www.loom.com/share/3d886ff7442e4bfa98c9da2d634e700c

**To Reproduce**
See the above video.
1. Create an activity post with multiple @mentions
2. Capture the queries for the activity item where has multiple @mentions when rendering.
3. See lots of duplicate queries.

**Expected behavior**
Duplicate queries should not run.

**Environment**
Client site, Dev, Local

**Support ticket links**
https://secure.helpscout.net/conversation/1645082023/166301/

Related Theme Issue: https://github.com/buddyboss/buddyboss-theme/issues/1690

**Comment by nickchomey** [comment]
@mahedihasannoman can I make a suggestion for you and the rest of the BB team? Use the Query Monitor plugin - it will automatically do all of what you just did in the video, for example tracking all of the queries that are run on a page load, identify all duplicate queries, how long they took, where they came from, and MUCH more. It will be very useful for your debugging and to identify all of the other places where there are duplicate queries. I used it to fix dozens of duplicate queries on every network search in #3091, for example. 

https://wordpress.org/plugins/query-monitor/

![image](https://user-images.githubusercontent.com/88559987/138387978-c569133c-fb00-4479-99c9-9b3020905ff8.png)
![image](https://user-images.githubusercontent.com/88559987/138388031-d122da3a-b403-4f21-8d37-e8898574042f.png)

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1677656382/171124/
