### ISSUE TITLE
Forum is not visible while creating Group

### ISSUE THREAD

**Issue by kishanjasani** [buddyboss/buddyboss-platform#3074]
**Describe the bug**
The client trying to create a group with a forum, however, no option for a forum only a blank page, https://prnt.sc/1uv294r

**To Reproduce**
1. Go to 'BuddyBoss Setting -> Forums'
2. Change slug single forum slug to `fórum`
3. Try to Create group from frontend.
4. See error.

**Screenshots**
https://prnt.sc/1uv294r

**Support ticket links**
https://secure.helpscout.net/conversation/1647570363/0/?folderId=5218799

**Jira issue** : [PROD-716]

[PROD-716]: https://buddyboss.atlassian.net/browse/PROD-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kishanjasani** [comment]
WordPress is also not storing the accents in the slug. You can check it by adding a new post or page with a custom slug-like `fórum`.

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1687802341/172433/
