### ISSUE TITLE
Unit Testing > Identify test cases for the BuddyBoss Platform and Theme

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#3077]
We want to create more unit tests for our products to aid our development and testing.

Before beginning on this work, we want to identify all the test cases we want to create for the **BuddyBoss Platform and Theme**. We also need to know the priority and why they have been given the specific priority.

This has been estimated to be a lot of work, so we need to be well prepared on how we conduct this work so that it doesn't consume resources away from our other development objectives.

You can use this spreadsheet:
https://docs.google.com/spreadsheets/d/1_rqCj-uc3Qfr0DejM6zYD5c_h3jXcRTXetOaZHaIctQ/edit#gid=0

### Issue for BuddyBoss App:
https://github.com/buddyboss/buddyboss-app/issues/2498

**Jira issue** : [PROD-714]

[PROD-714]: https://buddyboss.atlassian.net/browse/PROD-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sourabhmatolia** [comment]
**UPDATE**

Chetan and Kartik are done with the Initial work to document every single Unit Test case existing and some test cases for new modules.
Moving forward we need to plan how we will execute and have everyone contribute to the document.
