### ISSUE TITLE
Identify a list of BuddyPress and BBPress performance and security improvements to implement

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#3078]
Since forking BuddyPress and BBPress, they have released a number of performance and security improvements. We want to ensure that all are replicated in BuddyBoss.

For this research:
- Look through all performance and security improvements released by BuddyPress or BBPress since we released BuddyBoss Platform
- For each one, identify whether it should be implemented into BuddyBoss
- Make sure to write down any important considerations such as:
  - If and how the improvement will need to be adjusted for BuddyBoss
  - The priority of implementing

List: https://docs.google.com/spreadsheets/d/1nKW7yuyu-DdTOQC54yRR0fpr2XYng6fjuIbbc9ym8CE/edit

**Jira issue** : [PROD-713]

[PROD-713]: https://buddyboss.atlassian.net/browse/PROD-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mehulkaklotar** [comment]
Considered improvements from BuddyPress & bbPress security & maintenance releases so far.
We are looking at some other code improvements in BuddyPress & bbPress releases that we can do in our codebase.

**Comment by sourabhmatolia** [comment]
**UPDATE**

I will review task further and we will proceed with the implementation. Thanks.
