### ISSUE TITLE
Video upload progress bar showing 100% and still it does not allow post update

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#3088]
**Describe the bug**
when we have the video upload progress bar showing the 100% and if the user clicks on post update the video does not get in the activity, actually it works only after the progress bar is removed so its the confusion many times as many times the progress bar is there on 100% for some time may due to processing/network delay

**To Reproduce**
1. Goto activity feed and upload the video
2. As soon as the progress bar shows 100%, click post update button
3. See error

**Expected behavior**
Post update button should be disabled until progress bar disappear completely

**Screenshots**
http://somup.com/cr6oX433Sq at time 6:20

**Environment**

**Support ticket links**

**Jira issue** : [PROD-712]

[PROD-712]: https://buddyboss.atlassian.net/browse/PROD-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bb-yudhisthir** [comment]
Its the confusion with the actual file data been send to server shows "100% uploaded" but after that it takes our background process to save the attachment and create DB record etc. and then throws the response in the success event, so another approach is to move the lines of code for showing 100% uploaded from the "uploadprogress" event to the actual completion "success" event handler
