### ISSUE TITLE
GD bbPress Attachments plugin settings does not work with platform but its working with bbpress

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#3089]
**Describe the bug**
GD bbPress Attachments plugin settings does not work with platform but its working with bbpress, showing error message "Sorry, you are not allowed to access this page." https://i.imgur.com/7axb3pU.png

**To Reproduce**
1. install GD bbPress Attachments plugin with platform
2. Click on this plugin settings from plugins page https://i.imgur.com/cN42jHI.png
3. See error

**Expected behavior**
Should work with platform as its working with bbpress

**Screenshots**
https://i.imgur.com/cN42jHI.png, https://i.imgur.com/7axb3pU.png

**Environment**

**Support ticket links**
https://secure.helpscout.net/conversation/1651350064/167305?folderId=3709082

**Comment by bb-yudhisthir** [comment]
As per checking with @ngolwalkar already "GD bbpress Attachment plugin is trying to add a submenu under BuddyBoss>>Forums, which is itself a submenu" so the issue, the plugin author needs to make it compatible to BuddyBoss

https://somup.com/crljhL0grC

GD bbpress Attachment plugin is third party and not in our integration list. General requirements for the GD Attachment plugin with bbpress version >=2.6.2

cc: @firozwp @sourabhmatolia Need discussion, if we can close the ticket

**Comment by chetansatasiya** [comment]
@firozwp @bb-yudhisthir @sourabhmatolia @ngolwalkar @sadrul 

This plugin is adding the support to upload media on forums and that we have already on the platform. So I don't think we need this plugin.

Fell free to reopen if I missed anything here.
