### ISSUE TITLE
Check Suspended Content Cache is bypassed in all of the 26 places that it is called -> Considerable duplicate queries

### ISSUE THREAD

**Issue by nickchomey** [buddyboss/buddyboss-platform#3092]
**Describe the bug**
The check_suspended_content function gets and sets an object cache group, but it literally never gets used because in ALL of the 26 places that called, a "true" argument is passed for $force, which bypasses the cache. Actually, it not only bypasses it, but it gets and sets the object cache each time - only to never be used.

This results in a TREMENDOUS amount of duplicate queries throughout the website. 

I do not see the need for it to be bypassed at all, given that the cache item is cleared by the bb_moderation_clear_suspend_cache function, which is hooked into any changes to suspensions by 

add_action( 'bb_suspend_before_add_suspend', 'bb_moderation_clear_suspend_cache' );
add_action( 'bb_suspend_before_remove_suspend', 'bb_moderation_clear_suspend_cache' );

I suggest one of the following:

1. all of the "true" arguments be changed to "false"
2. remove the bypass altogether
3. or be more selective with which functions bypass the cache

**To Reproduce**

This is just one example, but it surely happens in nearly every part of the site. 
1. Install query monitor
2. Do a network search
3. Look through the duplicate queries for BB_Core_Suspend::check_suspended_content()
4. Change line 446 in bp-moderation\classes\suspend\class-bp-core-suspend.php from
if ( false === $result || true === $force ) {

to 

if ( false === $result || false === $force ) {

and you will see the duplicate queries disappear.

**Expected behavior**
I would expect this cache object to actually be used. 

**Screenshots**
### Duplicate queries on a search
![image](https://user-images.githubusercontent.com/88559987/138321121-fcec3dd6-1e7d-4eb0-a088-dd8fcc59cd10.png)

### all of the instances in which the check_suspended_content function is called, all passing "true" to bypass the cache
![image](https://user-images.githubusercontent.com/88559987/138321798-8e74d436-3c76-495d-8619-330b69217285.png)

**Environment**
Which site did you replicate this issue on?

A local and webserver environment

**Support ticket links**

**Jira issue** : [PROD-710]

[PROD-710]: https://buddyboss.atlassian.net/browse/PROD-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nickchomey** [comment]
This issue appears to be broader than just check_suspended_content
### check_hidden_content  - more than half of the calls bypass the cache
![image](https://user-images.githubusercontent.com/88559987/138323504-95c15a24-2458-4b41-9690-1066965c9b0a.png)

## check_moderation_exist
![image](https://user-images.githubusercontent.com/88559987/138323941-170ec923-9a98-44e0-b572-2ec6f1c0f150.png)

It is peculiar that only some of the checks have a bypass - the following don't have a bypass
* check_user_suspend
* check_suspend_details_exist (doesnt even have a cache - probably should?)
* check_blocked_content (doesnt even have a cache - probably should?)

as well as plenty of other check functions in other files.

**Comment by chetansatasiya** [comment]
This PR https://github.com/buddyboss/buddyboss-platform/pull/3055 fix all the remaining BP_Core_Suspend::check_suspended_content( $activity_id, self::$type, true ) caching issues and some of them we have fixed in #3091 PR.

**Comment by nickchomey** [comment]
@chetansatasiya No, as I commented in #3055 11 days ago, you only fixed 4 of 26 instances of bypassing the check_suspended_content cache object. https://github.com/buddyboss/buddyboss-platform/pull/3055#issuecomment-961649693

**Comment by chetansatasiya** [comment]
@nickchomey As I said here https://github.com/buddyboss/buddyboss-platform/issues/3092#issuecomment-970285238 we will fix all the remaining ones in this https://github.com/buddyboss/buddyboss-platform/pull/3055

**Comment by nickchomey** [comment]
Sorry, I misunderstood your comment - I thought you were saying that 3055 has already fixed it all, rather than it will fix it all. I'll leave you to your work!

**Comment by nickchomey** [comment]
@mikejyoung I'm thrilled to see the progress made with the performance updates, but I'm curious as to why this was mostly ignored. Most times that check_suspended_content is called, the cache is bypassed. Likewise for some other functions in this file.

But, even worse than that, the cache is checked and then the wpdb query is run anyway and the cache re-set. 

Assuming that there is some legitimate reason to do the bypass (though this isn't at all self-evident), shouldn't the code look something like the following, whereby the cache is only checked if force/bypass = false?

`
public static function check_suspended_content( $item_id, $item_type, $force = false ) {
		global $wpdb;
		$bp        = buddypress();
		$cache_key = 'bb_check_suspended_content_' . $item_type . '_' . $item_id;		
		if ( false === $force ) {
			$result    = wp_cache_get( $cache_key, 'bp_moderation' );
		}
		if ( false === $result || true === $force ) {
			$result = $wpdb->get_var( $wpdb->prepare( "SELECT DISTINCT id FROM {$bp->moderation->table_name} WHERE item_id = %d AND item_type = %s AND user_suspended = 1", $item_id, $item_type ) ); // phpcs:ignore
			wp_cache_set( $cache_key, $result, 'bp_moderation' );
		}
		return ! empty( $result );
	}
`

**Comment by nickchomey** [comment]
@chetansatasiya @mikejyoung 

As it turns out, the force/bypass caching described above doesn't actually work. 

When the item being checked is not suspended, $wpdb->get_var just returns an empty value (`""`). Then, when `if ( false === $result || true === $force ) {` is evaluated, it fails with the following: 

Notice: Undefined variable: result in /home/seeingtheforest.net/public_html/wp-content/plugins/buddyboss-platform/bp-moderation/classes/suspend/class-bp-core-suspend.php on line 488

and doesn't even check the `true === $force ` part, so it skips the wpdb->get_var function and wp_cache_set. 

I assume there must be _some_ instances in which the bypass is desirable (though surely fewer than what is currently being done), so it would be worth fixing this. I also assume this same problem happens elsewhere throughout the caching mechanism (certainly also with check_hidden_content and check_blocked_user_content)

Also, it appears that the entire cache is flushed with wp_cache_flush() in bb_moderation_clear_suspend_cache(), bb_moderation_clear_status_change_cache() and bb_moderation_clear_delete_cache() (as well as with rather than selectively flushing the relevant cache keys. I just tested by suspending a user and can confirm that the whole cache is flushed when doing that. Doesn't this seem quite extreme? 

It is also fully flushed in some other places that don't seem warranted, such as when document folders are saved (bp_nouveau_ajax_document_folder_save):

![image](https://user-images.githubusercontent.com/88559987/158084516-c2f34cda-c387-41c5-8a52-3ec04771557d.png)
