### ISSUE TITLE
Follower Widget Count is showing more numbers than actually the members avatars are been shown

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#3095]
**Describe the bug**
Follower Widget Count is showing more numbers than actually the members avatars are been shown, due to the suspended members, currently the count is been taken from the bp_get_follower_ids() which in turn calling get_followers() function, which is not excluding the suspended ones

**To Reproduce**
1. Enable the Moderation Component
2. And allow members to block each other (member blocking) and enable the auto suspend on 1 time blocking from the Moderation Settings( Buddyboss > Settings > Moderation )
3. Login as few multiple members with View As and click Follow
4. Get back to the admin account and add the (BB) Members Following Me Widget to the Activity Page Sidebar
5. Check the follower count in widget should be equal to the numbers of members avatar is showing in the widget
6. But if we suspend the user by going to their profile page and clicking on block, the count still counting the suspended users while the members in widget is not showing the suspended user

**Expected behavior**
Both the count and the members avatars should match

**Screenshots**
http://somup.com/cr63n53yT3

**Environment**
Client and Development site

**Support ticket links**
https://secure.helpscout.net/conversation/1653749940/167748/

**Jira issue** : [PROD-708]

[PROD-708]: https://buddyboss.atlassian.net/browse/PROD-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by angelic-joyce** [comment]
https://newaccount1634721716508.freshdesk.com/a/tickets/151512
