### ISSUE TITLE
GD Topic Polls plugin does not install with platform but it installs with bbpress

### ISSUE THREAD

**Issue by sadrul** [buddyboss/buddyboss-platform#3100]
**Describe the bug**
GD Topic Polls plugin does not install with platform but it installs with bbPress.

**Findings**
I found there is a condition check in that plugin which check if this number more than 25, then activate, otherwise not https://i.imgur.com/6ozLsPG.png
So, default bbpress, its getting the number 26 https://i.imgur.com/P5sDkeQ.png (in latest version) and its getting 25 for platform https://i.imgur.com/Vljxume.png and does not install

**To Reproduce**
1. Activate GD Topic Polls plugin with platform
2. See it will not install
3. Activate GD Topic Polls plugin with bbPress and see it will install

**Expected behavior**
Activate GD Topic Polls plugin should install with platform

**Screenshots**

**Environment**

**Support ticket links**

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1651350064/167305

**Comment by ngolwalkar** [comment]
@sadrul 
In order to make the Platform compatible with GD Topic Polls plugin, we may need to update the bbpress version greater than 2.5, since the plugin GD Topic Polls check for the bbpress version greater than 2.5 while getting activated, We currently have 2.5 so the condition doesn't get satisfied and the plugin GD Topic Polls can't be activated.

**Comment by bb-yudhisthir** [comment]
GD poll plugin is third party and not in our integration list. Here is the general requirements for the GD poll plugin with bbpress version >=2.6.2 https://screencast-o-matic.com/i/crljhFV2bo7

cc: @firozwp @sourabhmatolia Need discussion, if we can close the ticket

**Comment by chetansatasiya** [comment]
@firozwp @sourabhmatolia @bb-yudhisthir @ngolwalkar @sadrul 

This is something that need to check on the plugin end we will not going to do anything here. So Closing this issue.
