### ISSUE TITLE
Unable to post a forum if page has a pop up from elementor

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#3106]
**Describe the bug**
Unable to post a forum if page has a pop up from elementor. Please see this video: https://www.loom.com/share/2b45131c5f5d444bb4259181005c10cf

**To Reproduce**
1. disable all other plugin except elementor, elementor pro, and bb platform
2. go to forums, stand alone or group forum
3. create new discussion - it will post as expected
4. go to dashboard, then templates > theme builder
5. create a pop-up template, add any content
6. conditionals - entire site, trigger - page load, advanced - show on browsers/ show on devices then publish
7. go to forum, stand alone or group forum
8. create new discussion - notice the console with editor error
9. submit the discussion only to return as no content on the discussion editor

**Environment**
Demo, local, dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1672631552/170439?folderId=3709082

**Comment by Shamina07** [comment]
https://secure.helpscout.net/conversation/1680694453/171470?folderId=4687016

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1700899143/174494?folderId=3701258
