### ISSUE TITLE
On Screen Notification conflict with WP Rocket Plugin

### ISSUE THREAD

**Issue by kishanjasani** [buddyboss/buddyboss-platform#3107]
**Describe the bug**
On Screen Notification is not working when WP Rocket Plugin is active.

**To Reproduce**
1. Install ' WP Rocket Plugin '
2. Enable 'on screen notification'
3. Send private message to someone 
4. See the error. On Screen Notification is not working.

**Environment**
Latest Version of Platform and WordPress : 5.8.1

**Support ticket links**
https://secure.helpscout.net/conversation/1668979331/169973/

**Comment by amincdev** [comment]
@kishanjasani I checked with WP Rocket plugin ( 3.5.2 ) installed. But not able to see any issue. Can you please share more details, If I'm missing anything: https://ibb.co/qCjY3k2

**Comment by kishanjasani** [comment]
Not able to replicate it in the latest version. Updated the customer.

Thanks
