### ISSUE TITLE
Learndash > Private Group is not accessible when user is auto enrolled on a  through course.

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#3112]
**Describe the bug**
When a user takes the course and that course assigns the group so when a user takes a course that time user auto-enrolled to groups but that is not happening. please check the video for more details.

**To Reproduce**
1. Allow LD Groups to Social Groups integration and vice versa
2. Create a Parent Group and set it as Private
3. Create a Child Group and set as Private then set this as a Child of Parent Group
4. Create a Course and assign the Child Group to be auto-enrolled
5. In the frontend, allow a user to take the Course
6. Group is not assigned to users in my groups.

**Expected behavior**
Learndash course assign groups should be joined when users take a course.

**Screenshots**
http://somup.com/cr6T2E3Ayz

**Environment**
dev and customer

**Support ticket links**
https://secure.helpscout.net/conversation/1663141443/169217/

**Comment by mahedihasannoman** [comment]
This is not a valid issue because when a course lives inside a LD group then user should purchase the group access not the course. So closing this issue.

**Comment by emmanoctaviano** [comment]
@mahedihasannoman bro, can you check this video? Let me know if there is something I missed: http://somup.com/c3VQjJZXqF
