### ISSUE TITLE
Edit Activity - Mention users preview getting generated on editing activity.

### ISSUE THREAD

**Issue by ngolwalkar** [buddyboss/buddyboss-platform#3119]
**Describe the bug**
When we mention a user while creating a post it does not preview the user profile. But when we edit the post then it does.
https://i.imgur.com/b6FgrKk.jpg
This is also working the same in our demo.

**To Reproduce**
https://www.loom.com/share/0c05c91d53974af59e077ebaa93c5f61

**Expected behavior**
Preview for mention user profile must appear either at all places or it should not appear at any place. The functionality should remain the same for all editors.

**Screenshots**
https://i.imgur.com/b6FgrKk.jpg
**Jira issue** : [PROD-701]

[PROD-701]: https://buddyboss.atlassian.net/browse/PROD-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1704521644/174974/
