### ISSUE TITLE
Private forums discussion submit page goes to 404

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#3125]
**Describe the bug**
When trying to open the private forums URL and try to create a discussion that time goes to the 404 page.

**To Reproduce**
1. Create a Private discussion.
2. login with the subscriber role.
3. go to the forums page and select the private forum.
4. try to create a discussion and submit that.
5. see the error goes to the 404 page.

**Expected behavior**
The discussion page should not go to the 404 page.

**Screenshots**
https://www.dropbox.com/sh/go6uf28pkfsd4t1/AAC8WevolG_b5Bbd404JDABWa?dl=0&preview=Recording+10-22-21+at+13.04.32.mp4

**Environment**
dev and customer site.

**Support ticket links**
https://secure.helpscout.net/conversation/1660388467/168751

**Comment by marienel21** [comment]
@meetmakadiya I can't reproduce the issue
https://www.loom.com/share/5f891dad59804cefb5f82bb697bf8862

**Comment by meetmakadiya** [comment]
@marienel21 please check the video I can replicate with the latest version plugin on my local site.

https://user-images.githubusercontent.com/83228316/140141992-08c2ee21-1c00-4793-82ad-50954039feb4.mp4

let me know if any queries.
Thanks.

**Comment by milanhirapra** [comment]
Hello @meetmakadiya 
As per our discussion over the call you have to re-calculate the Hidden and Private forums from the BuddyBoss > Tools > Repair Forums. Please check this screenshot: https://nimb.ws/WsS2j6

**Comment by meetmakadiya** [comment]
Thanks, @milanhirapra for detailed validation and I believe we can close this issue for now
