### ISSUE TITLE
Links preview incorrect when we assign link to some strings.

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#3126]
**Describe the bug**
When we write something and assign some links to words the time preview is not showing the right.

**To Reproduce**
1. Go to the activity feed.
2. create the activity and add some text and add the link.
3. see the preview is incorrect.

**Expected behavior**
Links preview should be the right preview.

**Screenshots**
https://cdn.muse.ai/w/fbdfbe96d862e27e7984ff20e3a8b94163da2215de38857095834fa13bfc483e/videos/video.mp4

**Environment**
dev, demo

**Support ticket links**
https://secure.helpscout.net/conversation/1678680519/171250/
**Jira issue** : [PROD-698]

[PROD-698]: https://buddyboss.atlassian.net/browse/PROD-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by marienel21** [comment]
![image](https://user-images.githubusercontent.com/77659570/140095425-3b0dc274-9aa7-4e74-a0fd-f4e60fd5d02c.png)
