### ISSUE TITLE
Translation issue with "You're a Organizer" string on group page

### ISSUE THREAD

**Issue by surajkrsingh** [buddyboss/buddyboss-platform#3127]
**Describe the bug**
ISSUE: Translation for Group Roles, `You\'re a Organizer` --> `Sie sind ein a Organisator/in` the letter `a` is still left behind after translation

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to loco translation > Buddyboss platform
2.  Create a new translation with any language( tried with Hindi)
3. Try to find the word - You're a Organizer ( that is chunks(two) You're  and Organizer  but `a` character is missing)
4. Translate and check the group page role button

**Expected behaviour**
The string should be correct on the pot file and translation should be accurate

**Screenshots**
https://www.awesomescreenshot.com/video/5845739?key=9b01f8c594b06d356de21bcd3dff2a5d

**Environment**
Tested on customer site and local dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1680594858/171459?folderId=3709082

**Comment by hercivalbuddyboss** [comment]
https://secure.helpscout.net/conversation/1680594858/171459

**Comment by vipul4** [comment]
https://secure.helpscout.net/conversation/1684453934/171928/

**Comment by marienel21** [comment]
Bug Validated in devsite

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1693768120/173393/

**Comment by aclaoallen24** [comment]
https://secure.helpscout.net/conversation/1696552300/173804/

**Comment by vipul4** [comment]
https://secure.helpscout.net/conversation/1706398267/175267?folderId=5218801

**Comment by krunal-buddyboss** [comment]
@surajkrsingh 
As we have checked and discussed, We are adding pre-fix(a/an) manually so we will have all three separate translation for `You're`, `a/an` and `Organizer`. Once after adding translation for `a` and `an` it will works fine and if the user did not added translation then it will use default English translation.  **We also have the filter(`bp_get_article_prefix`) to apply prefix as user want.**
So as everything is clear and no need to apply any changes I am going to close this issue.
Thanks.
FYI @sourabhmatolia @firozwp @vipul4 @hercivalbuddyboss @aclaoallen24 @ayron-paul
