### ISSUE TITLE
The more link is not working correctly on the few widgets

### ISSUE THREAD

**Issue by amincdev** [buddyboss/buddyboss-platform#3135]
**Describe the bug**
The more link is not working correctly on the following widgets.
1. (BB) Member I'm Following"
2. (BB) Members Following Me

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Appearance > Widgets > then add the "(BB) Member I'm Following" and "(BB) Members Following Me" to the activity page
2. Then go to the Activity page
3. Try to click on the "More" link and notice the issue.

**Expected behaviour**
More links on the widget should redirect to the correct page.

**Screenshots**
https://secure.helpscout.net/file/0c6c1f9d7be4e7d7/548143/4922830677/407247921/

**Support ticket links**
https://secure.helpscout.net/conversation/1671378454/170282?folderId=3709082

**Jira issue** : [PROD-695]

[PROD-695]: https://buddyboss.atlassian.net/browse/PROD-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1735128714/179655
