### ISSUE TITLE
Messages component on profile page

### ISSUE THREAD

**Issue by leshma** [buddyboss/buddyboss-platform#3139]
Is there any way to use the Messages component on other pages? Example: a custom page in my plugin with an inbox on it.
I'd like to have a compose screen with my messages inbox on the custom page in my project.

I tried using the following, but to no avail:
```php
<div class="messages-wrapper">
    <div class="messages-screen">
        <?php
        if ( ! in_array( bp_current_action(), array( 'inbox', 'starred', 'view', 'compose', 'notices' ), true ) ) :
            bp_get_template_part( 'members/single/plugins' );
        else :
            bp_nouveau_messages_member_interface();
        endif;
        ?>
    </div>
</div>
```

Adding that code I've got the messages wrapper, but nothing more.
![image](https://user-images.githubusercontent.com/26694571/140244664-95e7df6c-1e10-4c70-9c09-a88f8b5aa630.png)

**Comment by vukasinpetrovic** [comment]
I'm also looking for solution to this problem. I would like to isolate private messaging part to my custom widget/page. Any help would be appreciated.

**Comment by vukasinpetrovic** [comment]
@chetansatasiya  @mahedihasannoman @amincdev @ngolwalkar 
Do you guys have any info on this that would help us? Is this even possible to achieve?

**Comment by mikejyoung** [comment]
@leshma 
Please send this question through to BuddyBoss support.
I am closing this issue as it is question and not a task to work on.
