### ISSUE TITLE
Process Shortcodes in buddyboss activity posts

### ISSUE THREAD

**Issue by klettersteige** [buddyboss/buddyboss-platform#3145]
I still need that shortcodes (of third-party-plugins) can be processed within a buddyboss activity post (the same way when I use a shortcode in a normal wordpress post)
For a better understanding for you - I want paste shortcodes like e.g. [sgpx gpx="/wp-content/uploads/gpx/tour.gpx"] or [sabai-directory-listing id="1"] in the buddyboss activity post form and then the output of the activity post should visualize the shortcode in the same way as it is in normal wordpress posts (when I paste there the shortcode(s))
can you pls. tell me which files of the buddyboss platform I need to modify in order to achieve this?

**Comment by surajkrsingh** [comment]
Hello @klettersteige 
Rendering a shortcode for activity post contents can be a security concern. 
If still, this is your requirement then you can use the below custom code to render the activity post content as a shortcode.

```
/**
 * Function to render the shortcodes from activity content.
 * 
 * @param string $content
 * 
 * @return string
 */
function bp_get_activity_content_body_to_shortcode_render( $content ) {

	if ( empty( $content ) ) {
		return;
	}

	$content = do_shortcode( stripslashes( $content ) );

	return $content;
}
add_filter( 'bp_get_activity_content_body', 'bp_get_activity_content_body_to_shortcode_render', 5, 1 );

```

Let me know, how it works for you.

**Comment by klettersteige** [comment]
hi @surajkrsingh 
thank you very much for your reply and your code :-)
You are absolutely right that there exists a security risk with this code.
How can it be altered so that e.g. only certain shortcodes are processed.
can you give me perhaps an example how only the wikipedia shortcode [rdp-wiki-embed url="http://de.wikipedia.org"] will be processed (and other shortcodes not).
THANK YOU VERY MUCH for your advice!

**Comment by surajkrsingh** [comment]
@klettersteige 
Please check this WordPress doc and example- https://developer.wordpress.org/reference/functions/has_shortcode/

You can add the condition to check the shortcode tag is exist in contents or not 
using function `has_shortcode( string $content, string $tag )`

From this code - https://github.com/buddyboss/buddyboss-platform/issues/3145#issuecomment-964992191
Add this line `$content = do_shortcode( stripslashes( $content ) );` within that condition 

Please try out this example and do the same as mentioned, it will work.
And please close if it works fine for you

Thank you

**Comment by klettersteige** [comment]
thank you very much @surajkrsingh  I will try it out! 👍

**Comment by surajkrsingh** [comment]
This is a customer-specific requirement and is already resolved.
I am closing this issue
