### ISSUE TITLE
Profile Types not assigning when user activates account from Subsite

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#3150]
**Describe the bug**
Profile Types not assigning when user activates account from Subsite activated buddyboss platform
See here: http://somup.com/crXQ673RK0
This issue is not happening when Platform is network enabled
see here: http://somup.com/crXQ6g3Rdb

**To Reproduce**
1. Setup a multisite environment
2. Create a subsite
3. Activate Platform on Subsite only, do not network activate
4. Enable and Create Profile Types (make sure profile type is selected on registration)
5. Add Profile Type field in Sign Up form
6. Try to register in subsite
7. in Users > Pending, see that the pending user is assigned to a Profile Type
8. Activate user and see that the Profile Type is not assigned anymore

**Expected behavior**
The profile type should also be saved after user activation

**Screenshots**
http://somup.com/crX6eY3WXt

**Environment**
Replicated at dev site with multisite

**Support ticket links**
https://secure.helpscout.net/conversation/1684246918/171891/

**Jira issue** : [PROD-691]

[PROD-691]: https://buddyboss.atlassian.net/browse/PROD-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by meetmakadiya** [comment]
@bb-yudhisthir I check on my dev multisite setup and the issue is replicated when the platform plugin is not activated from the network. 

https://user-images.githubusercontent.com/83228316/147666966-846efd08-581b-4a37-bf35-cfa474fdd5ff.mp4
