### ISSUE TITLE
Moderation background process gives memory limit error

### ISSUE THREAD

**Issue by KartikSuthar** [buddyboss/buddyboss-platform#3153]
**Describe the bug**
When we have a large number of data in the system. moderation background process gives memory limit error and stops working.

**Expected behavior**
It should work smoothly without having any issues.

**Screenshots**
https://screencast-o-matic.com/watch/crX6XoVl9yZ

**Environment**
Test with DB: https://drive.google.com/file/d/1lDWRfKtOt0zUr8MDmweuyfxKKvLQIwql/view?usp=sharing

**Suggestions**
- Create an individual background process for each and every item in moderation.
- If possible create a paginated item when finding the related contents.
- If all are done then create a new background process for the moderation and write migration of already placed background process will work on a new background.
- Needs scope: How to handle if background process when not finished.

**Comment by meetmakadiya** [comment]
https://secure.helpscout.net/conversation/1687575412/172389
