### ISSUE TITLE
@mentions members suggestions not using a user's nickname in groups instead using user_nicename

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#3162]
Expected functionality for tagging a user when creating a new group discussion or reply should show a user's "mention" name (source), which is normally the user's nickname.
However, in groups, when I start typing a user's name like "@nicholas", the user_nicename shows up as the "mention" handle, and not the user's defined "nickname". This behavior does not happen in activity updates.
Reopening #2234
Its working fine in the news feed already because of the [commit](https://github.com/buddyboss/buddyboss-platform/commit/ab17367d457076165cd0bdde1b8dc7a7f15826e3#diff-16a33b227f75e53fcc67c9906851425864962dd9dd5a1f32a32b61c1f9c04e34) but need to change for the groups too

To Reproduce
Important: Ensure the user's nickname is set to something other than their "user_nicename" (or username).

1 Go to a group
2 Start typing a group member's name prefixed with "@" (Like "@nicholas")

The "@" mention name shown before the user in the dropdown list will not be their nickname

Expected behavior
The mention name should be the user's nickname and not their user_nicename.

Support ticket:
https://secure.helpscout.net/conversation/1685468138/172082

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1681075497/171510/

**Comment by Santos-Jamie** [comment]
https://secure.helpscout.net/conversation/1688184168/172493

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1684776752/171987/
