### ISSUE TITLE
Table bb_performance_cache is not being created for some mysql servers

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#3164]
**Describe the bug**
The issue happens if the MySQL server has a lesser maximum in terms of bytes size of columns. Some servers can't handle e.g. for **cache_name varchar(1000)** or **cache_group varchar(200)**. The server causes errors that can only handle lesser than that. It happens when you try to set the column as a key. 

**To Reproduce**
1. Turn on debug mode.
2. Try activating buddyboss app plugin.
3. You will see that error that it tries to look for the **bb_performance_cache** table.

**Expected behavior**
Query for creating **bb_performance_cache** table should be flexible enough for some cases on any servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/82648504/141472027-44661fea-6795-47d6-b036-752d6d501298.png)

`WordPress database error Table 'learncmt.wp_bb_performance_cache' doesn't exist for query SELECT * FROM wp_bb_performance_cache where cache_group='app_core' made by do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, ReduxFramework->_register_settings, ReduxFramework->set_options, ReduxFramework->set_transients, update_option, do_action('update_option'), WP_Hook->do_action, WP_Hook->apply_filters, BuddyBossAppPerformanceIntegrationBB_App_Core->event_update_option, BuddyBossPerformanceCache->purge_by_group`

**Environment**
Which site did you replicate this issue on?
Customer's site

**Support ticket links**
https://secure.helpscout.net/conversation/1676973984/171016
https://secure.helpscout.net/conversation/1675065531/170772/

**Jira issue** : [PROD-688]

[PROD-688]: https://buddyboss.atlassian.net/browse/PROD-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1694035360/173429/

**Comment by kent-carlo** [comment]
https://secure.helpscout.net/conversation/1703330208/174803/

**Comment by bb-yudhisthir** [comment]
seems the issue for MySQL related to MyISAM, the UTF8 character set and indexes

**Comment by meetmakadiya** [comment]
https://buddyboss.slack.com/archives/C027H1D2WSG/p1640787620016200
Not replicated from my dev and local site but customer complicate this issue and for this issue replicate need the low version for MySQL so as of now I didn't close the issue.
