### ISSUE TITLE
Translatepress - glitch in creating new activity when you are in any RTL languages

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#3171]
**Describe the bug**
When you are in any RTL languages using translatepress, there is a glitch when you try to post new activity. It also happens in comments or replies to comment.

**To Reproduce**
1. Activate translatepress plugin.
2. Go to the newsfeed page and try to switching to any RTL languages.
3. Try posting new activity.
4. You can see that the cursor jumps off weirdly.

**Expected behavior**
Translatepress is suppose to be compatible with buddyboss platform so there should be no issue when translating to RTL language.

**Screenshots**
https://www.loom.com/share/7b2c4f74c0834ad19081b8503718ba02

**Environment**
Which site did you replicate this issue on?
dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1691252536/173023

**Jira issue** : [PROD-685]

[PROD-685]: https://buddyboss.atlassian.net/browse/PROD-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by meetmakadiya** [comment]
@kent-carlo issue is replicated with the latest version on buddyboss and the Translatepress plugin.

https://user-images.githubusercontent.com/83228316/147759146-03ba4879-fc96-4d7e-b9ad-bd0932f2188a.mp4
