### ISSUE TITLE
Syntax error in BB Platform

### ISSUE THREAD

**Issue by bretweinraub** [buddyboss/buddyboss-platform#3172]
PHP 7.4

BP PLatform: 1.8.1

Latest version BuddyBoss:

[15-Nov-2021 17:17:53 UTC] PHP Parse error:  syntax error, unexpected ')' in /var/www/..../wp-content/plugins/buddyboss-platform/bp-core/bp-core-attachments.php on line 695

```
            'has_avatar_warning'        => __( 'If you\'d like to delete the existing profile photo but not upload a new one, please use the delete tab.', 'buddyboss' ),
            'avatar_size_warning'       => sprintf( __( 'For best results, upload an image that is %1$spx by %2$spx or larger.', 'buddyboss' ),
                bp_core_avatar_full_height(),
                bp_core_avatar_full_width(),
            ),
        )
    );
}
```

Quick workaround is to delete ',' at the end of                 bp_core_avatar_full_width(),

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1698577373/174127/

**Comment by SisirChowdhury** [comment]
https://secure.helpscout.net/conversation/1698160735/174018/
