### ISSUE TITLE
Editor stuck when we enter and typing second lane

### ISSUE THREAD

**Issue by manishpatolia** [buddyboss/buddyboss-platform#3187]
**Describe the bug**
When user start typing second lane then user stuck there for few seconds.

**To Reproduce**
1. Go to activity 
2. Click on comment and and try to typing in the editor.

**Expected behavior**
It should be worked smoothly 

**Screenshots**
https://www.loom.com/share/12441c182f184a09af7122ff94f8698c

**Environment**
Our Demo

**Jira issue** : [PROD-681]

[PROD-681]: https://buddyboss.atlassian.net/browse/PROD-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by meetmakadiya** [comment]
@manishpatolia validated the issue.

https://user-images.githubusercontent.com/83228316/147494949-2a4bcbbe-d807-4b3a-8afc-158ab917ed8a.mp4
