### ISSUE TITLE
Group > Private message > All the users are not displayed 

### ISSUE THREAD

**Issue by sumitbuddyboss** [buddyboss/buddyboss-platform#3188]
**Describe the bug**
Total users does not appear in the private message section list.

**To Reproduce**
1. Go to 'Group private message'
2. Scroll down 'user list'

**Expected behavior**
All the users should appear in the message list.

**Screenshots**
https://www.loom.com/share/4e562eb0b5294614a3dbf01bfadd833a

**Environment**
Local / Demo

**Comment by surajkrsingh** [comment]
The group private message user list shows only 10 users but it should list all the users.
https://secure.helpscout.net/conversation/1703147382/174777?folderId=3709082
