### ISSUE TITLE
Change the default group and profile images

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#3191]
## Story
As a customer, I want to be able to set default images for group and profile images, so I can better customize my site to my brand and community. 

## Scope

**Loom:**
https://www.loom.com/share/89bf1c6b69cd40a18151fad50decb742

**NEW LOOM: Crop Avatars / Preview Cover Images:**
https://www.loom.com/share/7bbcfef4f45c48a7864de2b588e2d927

**Wireframes:**
https://miro.com/app/board/o9J_litmTgI=/
Password: buddyboss

We want customers to be able to define default images for:

- Profile Avatars
- Profile Cover Images
- Group Avatars
- Group Cover Images

We want to allow customers to select one of our images or upload a custom image. For profile avatars, we also want to allow them to use the WordPress default avatar.

As part of this project, we need to migrate data to the new settings on plugin update, so please carefully review the Loom video and wireframes.

### WordPress > Settings > Discussion

- The image used for the "Mystery Person" has been reverted to the image used by WordPress
- If "Profile Avatars" is set to "BuddyBoss" show a notice in the "Avatars" section
  - Text is "Profile avatars are currently provided by the BuddyBoss Platform. To use the WordPress avatar system, change the Profile Avatars setting to "WordPress" in the Profile settings."
  - "Profile" links to BuddyBoss > Settings > Profiles

### BuddyBoss > Settings > Profiles

* The "Profile Photos" meta box has been renamed to "Profile Images"

**Profile Avatar**

* The "Profile Avatars" field has been changed to "Upload Avatars"
  * The checkbox text has been changed to "Allow members to upload a profile avatar"
* A new "Profile Avatars" field has been added with two options in the select box: "BuddyBoss", "WordPress"
* New helper text has been added to the "Profile Gravatars" field
* The "Default Profile Avatar" and "Upload Custom Avatar" fields have been added
* If "Profile Avatars" = "BuddyBoss", the following fields show:
  * Upload Avatars
  * Default Profile Avatar
  * Enable Gravatars
* If "Profile Avatars" = "WordPress", the following fields show:
  * Upload Avatars
  * Show the notice if "Avatar display" is disabled in the WordPress discussion settings
* The "Upload Custom Avatar" field shows if "Default Profile Avatar" is set to "Custom"
* Helper text has been added for the "Enable Gravatars" field
* If "Custom" is selected for "Default Profile Avatar" but NO image is uploaded to "Upload Custom Avatar", the setting is reverted to the previous selection on save

**Profile Cover Images**

* "Default Profile Cover Image" and "Upload Custom Cover Image" fields have been added
* The "Default Profile Cover Image" field only shows if "Profile Cover Images" is checked
* The "Upload Custom Cover Image" field shows if "Default Profile Cover Image" is set to "Custom"
* If "Custom" is selected for "Default Profile Cover Image" but NO image is uploaded to "Upload Custom Cover Image", the setting is reverted to the previous selection on save
  
### BuddyBoss > Settings > Groups

* A new "Group Images" meta box has been created
* The "Group Avatar" and "Group Cover Images" fields have been moved to the new "Group Images" meta box

**Group Avatars** 

* ~The "Group Avatars" field has been changed to "Upload Avatars"~
  * ~The checkbox text has been changed to "Allow group organizers to upload a group avatar"~
* Change the checkbox text for "Group Avatars" to "Enable avatars for groups"
* Add "When enabled, group organizers will be able to upload avatars in the group's settings" helper text to "Group Avatars"
* The "Default Group Avatar" field only shows if "Group Avatars" is checked 
* The "Default Group Avatar" and "Upload Custom Avatar" fields have been added
* If "Default Group Avatar" is set to "Custom", the "Upload Custom Avatar" field shows

**Group Cover Images**

* The "Default Group Cover Image" and "Upload Custom Cover Image" fields have been added
* The "Default Group Cover Image" field only shows if "Group Cover Images" is checked
* The "Upload Custom Cover Image" field shows if "Default Group Cover Image" is set to "Custom"
* If "Custom" is selected for "Default Group Cover Image" but NO image is uploaded to "Upload Custom Cover Image", the setting is reverted to the previous selection on save

### Crop Avatars

* When uploading custom avatars, the BuddyBoss Crop Avatar UI appears in a modal, allowing the user to crop the avatar
* In the modal, the "Upload" and "Take Photo" tab don't appear

### Preview Cover Images

* When "Profile Cover Images" or "Group Cover Images" are checked, the "Preview Cover Image" field appears
* If the BuddyBoss App is installed, a button switcher appears to switch between the "Browser" and "App" previews
* The cover image and avatars in the previews update automatically as fields are changed meta box
* The background color used in the "Browser" preview is the same as the "Cover Image Background" color in the Theme Options
  * If the BuddyBoss Theme is not active, the color matches the color in the CSS style sheet
* The background color used in the "App" preview is the same as the "Cover Image Background" color in the app's branding settings

### BuddyBoss > Theme Options > Cover Images

* The two "Default Cover Image" fields have been removed

### Migrations

* The data migrations flows showed on the wireframes have been achieved

### API / App Caching

* All options need to be available in API
* App should contain our default images in build files and use them when selected
* Custom images should be cached in app

### Front-end

**Profile Avatars**

* If "Profile Avatars" is set to "WordPress":
  * The default WordPress avatar is used when a member hasn't uploaded an avatar
  * If the WordPress default avatar set to "Blank" or "Avatar display" is disabled, we use a blank transparent image on the front-end (rather than using no image)
* If "Profile Avatars" is set to "BuddyBoss":
  * The image selected/uploaded for "Default Profile Avatar" is used when a member hasn't uploaded an avatar
* If "Upload Avatars" is disabled, profile avatars cannot be uploaded by members

**Profile Cover Images**

* If "Profile Cover Images" is disabled:
  * No cover image section shows on profiles
  * Members cannot upload profile cover images
* If the "Profile Cover Images" is enabled:
  * A cover image section shows on profiles
  * Cover Image Background color is used as the background of the section
  * Members can upload custom cover images
  * If "Default Profile Cover Image" is set to "BuddyBoss", use the "cover-image.png" file
  * If "Default Profile Cover Image" is set to "None", just the background color shows
  * If "Default Profile Cover Image" is set to "Custom", the custom image file shows

**Group Avatars**

* The image selected/uploaded for "Default Group Avatar" is used when a group hasn't uploaded an avatar
* If "Upload Avatars" is disabled, group avatars cannot be uploaded by members

**Group Cover Images**

* If "Group Cover Images" is disabled:
  * No cover image section shows on groups
  * Group organizers cannot upload group cover images
* If the "Group Cover Images" is enabled:
  * A cover image section shows on groups
  * The Cover Image Background color is used as the background of the section
  * Members can upload custom cover images
  * If "Default Group Cover Image" is set to "BuddyBoss", use the "cover-image.png" file
  * If "Default Group Cover Image" is set to "None", just the background color shows
  * If "Default Group Cover Image" is set to "Custom", the custom image file shows

## Related Links

**Image Files**
https://drive.google.com/file/d/1lCbVqoKFDFRX0GFYGyQaEQ0mBmWPj2KX/view?usp=sharing
(Must be logged in with @buddyboss.com account to access)

**App Plugin Issue**
https://github.com/buddyboss/buddyboss-app/issues/2600
https://github.com/buddyboss/buddyboss-app/issues/2634

**App Native Issue:** 
https://github.com/buddyboss/buddyboss-app-native/issues/1851

**Theme Issue:** 
https://github.com/buddyboss/buddyboss-theme/issues/1857

**Platform API Issue:** 
https://github.com/buddyboss/buddyboss-platform-api/issues/377

**Jira issue** : [PROD-679]

[PROD-679]: https://buddyboss.atlassian.net/browse/PROD-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by milanhirapra** [comment]
Hi @sourabhmatolia 

I have questions regarding Default Profile and Group Avatar.

1) There is no option to use default WordPress avatars in the Default Profile Avatar setting. Should we have to add this option?
2) Should we provide the crop function for group and profile avatar?

CC: @firozwp @chetansatasiya @KartikSuthar

**Comment by sourabhmatolia** [comment]
@mikejyoung 

Concern on default avatar for member.
Check video:
https://www.loom.com/share/694ed1befc224c29be7a1b5ffa6a2f56

**Comment by mikejyoung** [comment]
@sourabhmatolia 
The BuddyBoss avatar already overrides the WordPress, at least in my test environment. If that's not the case, it should do. I added a line of text to the description confirming that "This will override the Default Avatar in the WordPress settings."

@milanhirapra 
I changed the design of the wireframes to match how options are selected. This matches what we did for the On-Screen Notifications "Position" option. We'll use this as a standard going forward.

**Comment by sourabhmatolia** [comment]
@milanhirapra 

Here's more information on mockup changes above and also responding to your concern above.
Check Video:
https://www.loom.com/share/889bdef575834fd4b43e79021604f1fe

Let me know if you have further concerns? Thanks

cc: @mikejyoung

**Comment by mikejyoung** [comment]
@milanhirapra 
I am updating the scope/acceptance criteria today with new information.

**Comment by mikejyoung** [comment]
@milanhirapra 

I've updated the wireframes, loom video, scope and acceptance criteria. Let me know if you have any questions.

CC: @sourabhmatolia @firozwp

**Comment by mikejyoung** [comment]
@shakilAshraful 
If a member/group hasn't uploaded a cover image, does the app show a default cover image/color? 

If not, we will need to update the app to show the default cover image if they have set the "Default Group/Profile Cover Image" to anything but "None".

**Comment by shakilAshraful** [comment]
@mikejyoung 
If a member of a group has no cover image set, the App does not show any default cover/color.

**Comment by milanhirapra** [comment]
@mikejyoung 

I checked the updated wireframes and flow, but I didn't get below the point:

1) Revert the "Mystery Person" to the WordPress default (currently we override with custom image). Please check screenshot: https://nimb.ws/14VonO
**Question:** What should we do if the administrator has selected a "mystery person"?

CC: @sourabhmatolia @firozwp

**Comment by mikejyoung** [comment]
This is the "Mystery Person" avatar for WordPress when BuddyBoss Platform is **not** installed:

![806bfd319d96998e54ed6b9514327cde](https://user-images.githubusercontent.com/75724470/145006613-dfe8ee0e-fe48-4973-98ed-26475a5964f4.png)

We need to revert to that and stop BuddyBoss Platform from overwriting.

If the Wordpress "Default avatar" is set to "Mystery Person", the BuddyBoss "Default Profile Avatar" should be set to "BuddyBoss" on plugin update.

If the WordPress "Default avatar" is set to any other option, the BuddyBoss "Default Profile Avatar" should be set to "WordPress" on plugin update.

**Comment by mikejyoung** [comment]
@milanhirapra 
Image files:
https://drive.google.com/file/d/1lCbVqoKFDFRX0GFYGyQaEQ0mBmWPj2KX/view?usp=sharing
(Must be logged in with @buddyboss.com account to access)

CC: @firozwp

**Comment by milanhirapra** [comment]
@mikejyoung 

There are two images not available at the above link. 
https://nimb.ws/axQRr9

CC: @firozwp

**Comment by mikejyoung** [comment]
> @mikejyoung 
> 
> 
> 
> There are two images missing in the above link. 
> 
> https://nimb.ws/axQRr9
> 
> 
> 
> CC: @firozwp 

@milanhirapra 
These are just representations of the images uploaded by customer. Those field are image upload fields. 

@sourabhmatolia do we have an image upload field type in our custom settings framework?

**Comment by sourabhmatolia** [comment]
@milanhirapra 

>There are two images missing in the above link.
https://nimb.ws/axQRr9

Check video:
https://www.loom.com/share/b0b99367bd1e4a47af96ab5c08ae1e08

Let me know if you still have questions. Thanks.

**Comment by mikejyoung** [comment]
@milanhirapra 

I've updated the scope of this issue to cover two new requirements. Please review carefully.

**NEW LOOM: Crop Avatars / Preview Cover Images:**
https://www.loom.com/share/7bbcfef4f45c48a7864de2b588e2d927

**Crop Avatars**

* When uploading custom avatars, the BuddyBoss Crop Avatar UI appears in a modal, allowing the user to crop the avatar
* In the modal, the "Upload" and "Take Photo" tab don't appear

**Preview Cover Images**

* When "Profile Cover Images" or "Group Cover Images" are checked, the "Preview Cover Image" field appears
* If the BuddyBoss App is installed, a button switcher appears to switch between the "Browser" and "App" previews
* The cover image and avatars in the previews update automatically as fields are changed meta box
* The background color used in the "Browser" preview is the same as the "Cover Image Background" color in the Theme Options
  * If the BuddyBoss Theme is not active, the color matches the color in the CSS style sheet
* The background color used in the "App" preview is the same as the "Cover Image Background" color in the app's branding settings

**Images Updates**
https://drive.google.com/file/d/1lCbVqoKFDFRX0GFYGyQaEQ0mBmWPj2KX/view?usp=sharing

CC: @eisenwasser @sourabhmatolia @firozwp
