### ISSUE TITLE
View page of the Elementor saved template not working

### ISSUE THREAD

**Issue by mahedihasannoman** [buddyboss/buddyboss-platform#3194]
**Describe the bug**
View page of the Elementor saved template not working when news feed is set to as site home page. It is showing news feed page when clicking on the view link of the Elementor saved template. Please see this video: https://share.vidyard.com/watch/4fZwRF9yT6PTFPQpumtXsn?

**To Reproduce**
1. Make sure the News feed has been set as home page.
2. Go to Templates > Saved Templates
3. Click on the view for any saved templates

**Expected behavior**

**Environment**
Local, demo, client's site

**Support ticket links**
https://secure.helpscout.net/conversation/1703261813/174794/

**Jira issue** : [PROD-678]

[PROD-678]: https://buddyboss.atlassian.net/browse/PROD-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jrbuddyboss** [comment]
https://secure.helpscout.net/conversation/1730634884/179079/
