### ISSUE TITLE
Ability To Limit Documents, Video/ Photos Maximum Upload Storage Quota based on Membership Tier  #1013

### ISSUE THREAD

**Issue by edudemy** [buddyboss/buddyboss-platform#3198]
**Is your feature request related to a problem? Please describe.**
It is a problem if free tier users upload infinite files to your site, slowing it down severely and abuse free/basic/advanced user policy.

**Describe the solution you'd like**
With the new update of Media/Video uploading (which is fantastic by the way), it would be great if you can add the ability to set a maximum storage quota size for  *overall* uploads per user based on membership tier. This could be amended by admins in the backend at **media access controls**, and  also the limits displayed in the frontend upon file upload for users to be aware of.

**Describe alternatives you've considered**
We tried a workaround media gallery and membership plugin, by completely disabling native buddyboss media/video uploading, since this can easily bring down our server and also not economical to offer free tier anymore, as an operational strategy even if offloaded to s3 compatible storage via mediacloud.press and w3 offload media. 

[tested reference membership plugin] (https://rtmedia.io/docs/addons/membership/)
[alternative plugin ] (https://buddydev.com/plugins/mediapress-paid-memberships-pro-restrictions/)
![45054090-fb17-11e4-8bd9-28a7def70add](https://user-images.githubusercontent.com/2371533/143140409-16fff627-f021-42d7-855c-b04fcbef98d7.png)

**Comment by mikejyoung** [comment]
Hi @edudemy 

Please submit your feature ideas or suggestions here:
https://www.buddyboss.com/roadmap

Issues added to the our backlog need to have been fully scoped and planned by the BuddyBoss product team.

I'm closing this issue here.

**Comment by sujanpgowda** [comment]
Hi @mikejyoung Have already added it to the road map, but don't it being acknowledged  nor reflected in under consideration. Therefore it has made me reach out in various channels. I guess I speak for most customers, that what made us buy( fancy stuff)  are not the same things which will make us stay (usability), to continue using the product.

**Comment by manualsh** [comment]
Hi @mikejyoung Have already added it to the road map, but don't see It being acknowledged nor reflected in under consideration backlog. Therefore it has made me reach out in various channels. I guess I speak for most customers, In saying out loud that what made us buy
( fancy stuff) are not the same things which will make us stay (usability), to continue using the product.

The earlier (and related) issues which were being acknowledged in this open forum, is now moved to a private (and non transparent) forum has led us back here.

These are the related issues, which were discussed here earlier
(https://github.com/buddyboss/buddyboss-platform/issues/1013)
(https://github.com/buddyboss/buddyboss-platform/issues/991)
(https://github.com/buddyboss/buddyboss-platform/issues/987)
(https://github.com/buddyboss/buddyboss-platform/issues/3271)
(https://github.com/buddyboss/buddyboss-platform/issues/3166)
(https://github.com/buddyboss/buddyboss-platform/issues/823)
