### ISSUE TITLE
Preview not working for some urls in message box but working on activity feed

### ISSUE THREAD

**Issue by surajkrsingh** [buddyboss/buddyboss-platform#3199]
**Describe the bug**
URL preview doesn't work for some URLs in the message editor and sent the message. 
The same URLs preview works fine on the activity feed but not in the message box.

Some URLs work(like youtube video URLs) but most of them are not.

**To Reproduce**
1. Go to message
2. Click any member
3. Send URLs as mentioned on video
4. See preview

**Expected behavior**
URL preview should work correctly as like activity feeds.

**Screenshots**
https://www.awesomescreenshot.com/video/6139110?key=0c35400107fa2b042997e36fc5fa45e0

**Environment**
Buddyboss demo site
Dev site and customer site.

**Support ticket links**
https://secure.helpscout.net/conversation/1704584621/174980?folderId=3709082

**Jira issue** : [PROD-677]

[PROD-677]: https://buddyboss.atlassian.net/browse/PROD-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by meetmakadiya** [comment]
@surajkrsingh issue is replicated with the latest version and please check the video.

https://user-images.githubusercontent.com/83228316/147760259-a67d2d68-f624-4a89-b4cc-489861f72b94.mp4
