### ISSUE TITLE
uploaded non-square profile images are blurry

### ISSUE THREAD

**Issue by patrickmcelwee** [buddyboss/buddyboss-platform#3207]
We found this issue on our new site, and it is not affected by Firefox/Chrome use, which was the focus of a fix in #1543 . To reproduce, you need to use an image that is not square, where the crop box will be a smaller part of the overall image.

Here are two images that illustrate the problem and should allow you to reproduce it. The first is the original photo, 3385 x 5077, and is similar to a photo taken on a phone that one of our users might upload. When this is uploaded to the crop tool, it is blurry _before any cropping takes place_, suggesting that the image is downgraded prior to displaying the crop screen.

![image](https://user-images.githubusercontent.com/808015/142647125-3bb2467a-e660-47db-99d6-7b35375acdfc.png)

Here's the original:
![PatrickMcElwee_sml](https://user-images.githubusercontent.com/808015/142645288-bd977a60-3513-4d67-a52b-65c5763d70da.jpg)

The second image was cropped by me in Photoshop. It is 2291 x 2291, and when uploaded to BuddyBoss and cropped by the website, it continues to look relatively sharp.

![PatrickMcElwee_square](https://user-images.githubusercontent.com/808015/142645262-57988021-8863-49f7-8e94-a490390947e5.jpg)

Here is a side-by-side of the final result in the two cases:
![image](https://user-images.githubusercontent.com/808015/142646296-f4866e8c-1d80-4009-83cd-f3904d956bac.png) 
![image](https://user-images.githubusercontent.com/808015/142646369-a328732f-48c6-4774-8abb-91b4b1fbd4b6.png)

I hope that's helpful. I'm happy to assist however I can.

**Jira issue** : [PROD-673]

[PROD-673]: https://buddyboss.atlassian.net/browse/PROD-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by meetmakadiya** [comment]
When we upload the non-square image that time images are blurry.

https://user-images.githubusercontent.com/83228316/147771096-bcfe6e04-c770-4775-8ff0-bee2328d77cc.mp4
