### ISSUE TITLE
PHP 7.2 version issue with platform updated 1.8.2

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#3209]
**Describe the bug**
When we have php 7.2 or older version PHP that time there is an error through on bp-core/bp-core-attachments.php filr. 

**To Reproduce**
1. Platform update to 1.8.2
2. set the PHP version 7.2
3. See error http://i.imgur.com/bLuE8VY.png

**Expected behavior**
PHP 7.2 should not be got the error with the latest version on the platform.

**Screenshots**
http://i.imgur.com/bLuE8VY.png

**Environment**
local site.

**Comment by amincdev** [comment]
@meetmakadiya This issue has been fixed here: https://github.com/buddyboss/buddyboss-platform/pull/3174
You can still confirm once.

**Comment by meetmakadiya** [comment]
@amincdev thanks for informing about the PR I will close this issue
