### ISSUE TITLE
Minify JS files

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#3210]
Could you minify JS files to improve site load speed? 

Platfrom:

[buddyboss-platform/bp-core/js/emojionearea-edited.js](https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/js/emojionearea-edited.js)
[buddyboss-platform/bp-core/js/vendor/exif.js](https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/js/vendor/exif.js)

Theme:
```
buddyboss-theme/assets/js/main.js
buddyboss-theme/inc/plugins/elementor/assets/js/frontend.js
```

Some of them have .min.js version, but you are not using them for some reason. 

[buddyboss-platform/bp-core/js/emojionearea-edited.min.js](https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/js/emojionearea-edited.min.js)
`buddyboss-theme/assets/js/main.min.js`

--- 
buddyboss-platform v1.8.2

**Jira issue** : [PROD-672]

[PROD-672]: https://buddyboss.atlassian.net/browse/PROD-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bb-yudhisthir** [comment]
@firozwp @sourabhmatolia
we are loading some unminified js for eg:
buddyboss-platform/src/bp-core/bp-core-cssjs.php
https://screencast-o-matic.com/i/crlj1hV2bqN

Needs discussion on this if we need to make any changes

**Comment by kent-carlo** [comment]
@bb-yudhisthir I got a confirmation from @chetansatasiya. Unminified js files should also be minified.
