### ISSUE TITLE
Admin widget toggle not working. ( platform 1.8.1 + classic editor )

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#3214]
**Describe the bug**
When we active platform version 1.8.1 or higher version that time admin backend widget toggle button not working.

**To Reproduce**
1. activate the platform version 1.8.1
2. activate the latest version of the classic editor.
3. Go to the learndash course and try to toggle the right side widget.
4. See error toggle is not working.

**Note**
Platform version 1.8.1 and onwards not working earlier 1.8.0 or lower version working properly.

**Expected behavior**
Admin Backend (widget)toggle switches should be working as expected.

**Screenshots**
https://prnt.sc/20y4uv8

**Environment**
Customer site, Demo site, Local site

**Support ticket links**
https://secure.helpscout.net/conversation/1710300907/176053

**Jira issue** : [PROD-671]

[PROD-671]: https://buddyboss.atlassian.net/browse/PROD-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kent-carlo** [comment]
https://secure.helpscout.net/conversation/1712477213/176483/
