### ISSUE TITLE
Notifications > Desktop (Browser) Notifications

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#324]
**Is your feature request related to a problem? Please describe.**
When a user receives a notification and is not on the website in that moment, they might miss it. Site owners want their users to get the notifications right away to increase engagement, and desktop notifications is a popular solution to this issue.

**Describe the solution you'd like**
When Notifications component is enabled, add a new settings panel at BuddyBoss > Settings > Notifications. In this settings panel, add an option for enabling Browser Notifications. Once enabled, all notifications that the user has selected they want to receive (all the ones they would also get by email) should appear as browser notifications in their browser. 

**Resources**
Chrome - https://developers.google.com/web/fundamentals/codelabs/push-notifications
Firefox - https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
Safari - https://developer.apple.com/notifications/safari-push-notifications/
All Browsers - https://stackoverflow.com/questions/31684804/notifications-across-all-browsers

**Describe alternatives you've considered**
We can consider requiring that customers integrate into a third party service if there are obvious advantages. For example: https://onesignal.com/

**Related Issues**
https://github.com/buddyboss/buddyboss-platform/issues/325

**Comment by TokumeiJG** [comment]
Would prefer a native solution instead of requiring us to sign up for a separate service...

**Comment by ZandarKoad** [comment]
Yep. We need this. We can't use Buddy Boss platform for our clients unless push notifications are in place.

**Comment by karlemilnikka** [comment]
Do you have any update for when this great feature will be developed? The official roadmap has postponed it to Q1 2021, but I suppose it will get delayed again since we’re almost at the end of that quarter.

**Comment by AriHoresh** [comment]
> Do you have any update for when this great feature will be developed? The official roadmap has postponed it to Q1 2021, but I suppose it will get delayed again since we’re almost at the end of that quarter.

I believe so as well... too bad!

**Comment by mikejyoung** [comment]
I am closing this issue as it was predominately added here for tracking. We are now tracking planned features inside of our Product Board software.

We have been working on this feature in a separate r&d environment. When we are ready to implement the into the BuddyBoss Platform, we will create new scoped issues to this repo.

For an update on this feature, please watch our June 2021 product update:
https://www.youtube.com/watch?v=8U7hQNVpOqY&ab_channel=BuddyBoss
