### ISSUE TITLE
Over 150 console errors in activity feed

### ISSUE THREAD

**Issue by TheWizardofWikacy** [buddyboss/buddyboss-platform#3243]
There are over 150 console errors in buddyboss platform activity feed, all referring to video codes trying to call functions which do not exist until a user actually clicks to open a video module.  This is just unheard of.  Please get it together.

**Comment by bb-yudhisthir** [comment]
@TheWizardofWikacy can you send the details of the error message or the screenshot? Is it something related to : VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)

**Comment by bb-yudhisthir** [comment]
@TheWizardofWikacy Closing the issue
For the console error for videos, its seems related to #3059 and also if not, you can reach to our support with the details
