### ISSUE TITLE
Prompt message "Are you sure. you want to do this..." on saving the product, or even when adding the buddyboss group type etc

### ISSUE THREAD

**Issue by bb-yudhisthir** [buddyboss/buddyboss-platform#3244]
**Describe the bug**
When we edit or save a product and have the buddyboss platform and woocommerce active with settings options : woocommerce > settings > products > uncheck/disable the option Enable reviews : Enable product reviews
https://snipboard.io/sjmDlH.jpg

Another same prompt issue with Custom Post by CPT UI, when the custom post has comments disabled in CPT UI settings

**To Reproduce**
1. Enable buddyboss platform and woocommerce
2. Disable product reviews (woocommerce > settings > products > uncheck/disable the option Enable reviews : Enable product reviews)
3. Edit or add a new product and click on publish/update

**Expected behavior**
It should not give the prompt again and again, should work normally

**Screenshots**
https://snipboard.io/sjmDlH.jpg

**Environment**
Our dev and client site

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.
Woocommerce:
https://secure.helpscout.net/conversation/1707592640/175525/
CPT UI:
https://secure.helpscout.net/conversation/1715822181/177036/

**Jira issue** : [PROD-660]

[PROD-660]: https://buddyboss.atlassian.net/browse/PROD-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bb-yudhisthir** [comment]
https://secure.helpscout.net/conversation/1720970026/177888/

**Comment by kent-carlo** [comment]
@bb-yudhisthir Issue can still be replicated with the latest buddy boss platform plugin. I would like to add also that the issue happens to all post types when the comment is disabled and is using the classic editor. 
https://www.loom.com/share/2640e183cc324d23a04ec253e0551c18
