### ISSUE TITLE
Middle Name in registration form

### ISSUE THREAD

**Issue by CptGkm** [buddyboss/buddyboss-platform#3245]
**Middle Name set to not required in phpmysql**
![middle name-phpmyadmin](https://user-images.githubusercontent.com/96210065/146274434-0608c8ad-706e-4eb7-a20d-59db4c984d44.jpg)

**Still requiring middle name when opening registration form**

![middle name required](https://user-images.githubusercontent.com/96210065/146274516-8301b1c0-c489-4604-83e9-42383d566185.jpg)

**If deleting it via phpmyadmin, it causes not saving whole registration data**

**Comment by kent-carlo** [comment]
Hi, @CptGkm I tried to replicate the issue. It seems that in the latest version, the middle name field is not one of the default fields anymore. Also, I tried creating a middle name field and I still can't replicate the issue. It seems that issue is isolated on your site.
