### ISSUE TITLE
Course grid widget arrow down button is missing

### ISSUE THREAD

**Issue by Santos-Jamie** [buddyboss/buddyboss-platform#3249]
**Describe the bug**
Course grid widget arrow down button background is getting overwritten by BuddyBoss Platform CSS when displaying LifterLMS courses
 
**To Reproduce**
1. Create a page
2. Edit page with Elementor
3. Add a course grid widget
4. Make sure that the LifterLMS is enabled
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/74121050/146625104-aa2dd614-41bc-4123-8fba-59273590b636.png)
https://www.awesomescreenshot.com/video/6516194?key=1c6c9e650301b602a06b18e0a5688592

**Support ticket links**
https://secure.helpscout.net/conversation/1722317969/

**Jira issue** : [PROD-658]

[PROD-658]: https://buddyboss.atlassian.net/browse/PROD-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by surajkrsingh** [comment]
@Santos-Jamie 
I am not able to reproduce the issue on my dev site with the given steps.
Did you check your dev site or buddyboss demo site? 
Maybe this is a customer-specific issue.

Please check once and let me know if you still find this.

**Comment by kent-carlo** [comment]
@surajkrsingh I was able to reproduce the issue in localhost. Here are the steps:
1. Create a page
2. Edit page with Elementor
3. Set the page as e.g. newsfeed.
4. Make sure that the LifterLMS is enabled and not LD
5. You should be able to see the issue when you view the page.
https://user-images.githubusercontent.com/82648504/147824646-6d2d1c65-7d9c-4c80-822f-41291b85bcb0.png
