### ISSUE TITLE
Notifications > Web Push Notifications

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#325]
**Is your feature request related to a problem? Please describe.**
When a user receives a notification and is not on the website in that moment, they might miss it. Site owners want their users to get the notifications right away to increase engagement, and on-site 'Glimpse' notifications is a popular solution to this issue.

**Describe the solution you'd like**
When Notifications component is enabled, add a new settings panel at BuddyBoss > Settings > Notifications. In this settings panel, add an option for enabling Web Push Notifications. Once enabled, all notifications that the user has selected they want to receive (all the ones they would also get by email) should appear in the website as quick slide-in notification squares, that can be dismissed to slide out. Similar to this - https://prnt.sc/q8iaob

**Describe alternatives you've considered**
We can consider requiring that customers integrate into a third party service if there are obvious advantages. For example: https://onesignal.com/

**Related Issues**
https://github.com/buddyboss/buddyboss-platform/issues/324

**Comment by eisenwasser** [comment]
This plugin claims to have real time notifications (AJAX or WebSocket):
https://wordpress.org/plugins/bp-better-messages/

We can look and see if they are doing anything useful.

**Comment by rcimedia** [comment]
You might want to consider talking to SmartIOLabs .. they offer a cheap multi-channel plugin called "[Smart Push Notifications](https://codecanyon.net/item/desktop-mobile-push-notification-system-wordpress-plugin/6548533)" that is fully compatible (out of the box)  with BuddyPress, BBpress, WooCommerce (ie Abandoned Cart). ACF. WP Job Manager, and every major browser, desktop, and mobile web-push notifications.  The plugin has other channel hooks as well like FB Messenger, What'sApp, Email and others.   The web-push works directly with Firebase so it does not require OneSignal or any per-subscriber fees.   

All you would really need to do is create a toggle interface for users to be able to select their own push-notification options .. the plugin will take care of the rest.   It is definitely worth checking out for us BuddyBoss Operators.  

* ETA, I am a longtime BuddyBoss Customer. and not affiliated in any way with the plugin-developers.

**Comment by tentapps** [comment]
We would love to see this integration.  Any update on how the development of this is coming along?

**Comment by jenninejacob** [comment]
Hi there, this was on the docket for Q3 and I see it's been in "planned" for some time. Any update on when this is going to be started?

**Comment by theministerat** [comment]
This would be REVOLUTIONARY for us. It's the one thing that we really need to accomplish everything we hoped BuddyBoss would help us to do. I've been trying to find some work around for a time now, but so far no dice . . .

**Comment by mattttis** [comment]
> Hi there, this was on the docket for Q3 and I see it's been in "planned" for some time. Any update on when this is going to be started?

<img width="1492" alt="Screenshot 2020-12-17 at 13 45 55" src="https://user-images.githubusercontent.com/63421937/102489743-31bd4580-406e-11eb-9c7d-b5928859bb51.png">

It's currently still on 'Planned' for Q1 2021, guess we'll just have to wait and see :)

**Comment by Risepage** [comment]
> This plugin claims to have real time notifications (AJAX or WebSocket):
> https://wordpress.org/plugins/bp-better-messages/
> 
> We can look and see if they are doing anything useful.

I have been working with the Plugin developer for BP Better Messages and he said he can look into it if he has access to the App code, but until that point he cannot do anything to integrate ad it would be up to BuddyBoss to initiate that releationship to utilize his plugin. He is also providing video and voice calling through the Plugin and I have had nothing but a great experience working with him.

**Comment by mikejyoung** [comment]
Closing this issue as this feature has been released:
https://www.buddyboss.com/resources/docs/components/notifications/on-screen-notifications/
