### ISSUE TITLE
Public Group > Video tab doesn't load videos for non-member

### ISSUE THREAD

**Issue by surajkrsingh** [buddyboss/buddyboss-platform#3250]
**Describe the bug**
Videos are not loading when non-member visit the group > video tab whereas documents and photos are visible.
Even the video tab shows the **count** but doesn't load the videos but the group > activity feed also shows the video.

**To Reproduce**
1. Go to a public group
2. add videos
3. Open the group with non-member user
4. See video tab under that group

**Expected behavior**
Videos should be available like documents and photos

**Screenshots**
https://www.loom.com/share/1618d05a64f24f4d92fe3276114325c7

**Environment**
Dev site and customer site 

**Support ticket links**
https://secure.helpscout.net/conversation/1725394050/178438?folderId=3709082

**Jira issue** : [PROD-657]

[PROD-657]: https://buddyboss.atlassian.net/browse/PROD-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kent-carlo** [comment]
@surajkrsingh I was able to replicate the issue in latest plugin version 
https://www.loom.com/share/da3ec02a58a5426a88eb5be11a7626c6
