### ISSUE TITLE
Discussion > Pagination and post count break when you merge discussion.

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#3251]
**Describe the bug**
When we merge any discussion that time pagination and the post count is broken.

**To Reproduce**
1. Set a limit to 3 replies per page. http://i.imgur.com/F8Pl4Xk.png
2. create the two different discussions with repliers.
3. try to merge the discussion.
4. See the error of the pagination count once the merge is completed.

**Expected behavior**
Pagination and pagination count should not be broken.

**Screenshots**
Dev: 
https://user-images.githubusercontent.com/83228316/146747490-68638651-1f43-46c0-a7d3-1ea0f09f3f66.mp4

Customer:

https://user-images.githubusercontent.com/83228316/146751775-ad5ed1c7-5161-47a9-bc3f-1f2cd11c61e6.mp4
![Screen-Shot-2021-11-21-at-11-38-51-PM](https://user-images.githubusercontent.com/83228316/146751790-e21b39e8-bf29-47cc-8a49-16c486a5dd1c.png)

**Environment**
dev, local

**Support ticket links**
https://secure.helpscout.net/conversation/1701567391/174577

**Jira issue** : [PROD-656]

[PROD-656]: https://buddyboss.atlassian.net/browse/PROD-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by nickchomey** [comment]
This is related to #2507, where I've already fully diagnosed this issue. It all stems from a failure to appropriately update postmeta fields. 

https://github.com/buddyboss/buddyboss-platform/issues/2507#issuecomment-974611267

It is worth checking whether this issue happens for split and move as well - I only checked merge.

**Comment by kent-carlo** [comment]
@meetmakadiya I was able to replicate it in latest buddyboss app plugin in my local.
