### ISSUE TITLE
Activity feed allows you to post update before images are finished uploading / processing

### ISSUE THREAD

**Issue by rmmoul** [buddyboss/buddyboss-platform#3253]
**Describe the bug**
When uploading an image on a user profile's feed or on the global activity feed you can submit the post before the image is done uploading or processing. This leads to your post submitting and the text displaying but the image does not display. 

**To Reproduce**
1. Enable image uploads for the activity feed
2. Go to an activity feed and type some text, then add an image
3. Press the "post update" button before the image has finished uploading / processing. Images that have not uploaded or processed completely will show their circular upload indicator and the camera icon over the thumbnail, the camera icon disperse from the thumbnail after the upload / processing is done.
4. See that your post text shows in the activity feed but your image is missing

**Expected behavior**
The "post update" button should not allow the post to submit until all images are done being uploaded

**Screenshots**
I've created a video showing the issue:
https://drive.google.com/file/d/1rjPejFj0reh1cY_RuOLCygAIURLj_nak/view?usp=sharing 

**Environment**
This was initially discovered on a site with just these plugins active:
BuddyBoss Platform Version 1.8.3
BuddyBoss Platform Pro 1.1.8
BuddyBoss Products Updater 1.2.8 
Using the BuddyBoss Theme, version 1.8.1

**Support ticket links**
n/a at the moment

**Jira issue** : [PROD-655]

[PROD-655]: https://buddyboss.atlassian.net/browse/PROD-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ExoGeek** [comment]
Hello,

I think this issue is more related to BuddyBoss Theme but you're right. I have already reported this issue to BuddyBoss. This is quite annoying. 

Hope they will find a solution to this issue.

Kind regards,

**Comment by Hemligg** [comment]
Even more annoying that the image is uploaded with broken links without a relation to a post. Which just makes the image remain on disk even though the activity which was posted is deleted. Which result in a lot of crap images taking space on the storage.
