### ISSUE TITLE
BuddyBoss-based menu displays options for profile owner rather than logged in user 

### ISSUE THREAD

**Issue by wemakecommunity** [buddyboss/buddyboss-platform#3311]
**Describe the bug**
WordPress 5.9
BuddyBoss 1.8.5
Theme: custom theme

We've built our profile navigation in our custom theme using the BuddyBoss options in the Menu builder: Profile > View, Account > Login Information, etc. It works well *until* viewing another member's profile, at which point the navigation prints the viewed member's links instead of the logged in user's links.

We're also using GeoMyWP, which integrates with BuddyBoss. Their navigation items, which were added in the same way, remain correct even when viewing another member's profile.

Based on similar behavior we've witnessed elsewhere, I suspect that the supporting code might be using `wp_get_current_user()` which we've found will prefer the member of the profile being viewed over the logged in member. Instead, we've found it safer to base things off of `bp_loggedin_user_id()`

I'm adding screenshots with a link preview to illustrate. In the first shot, we're looking at a general site screen—note the username hammer in the link preview. In the second, we're looking at the profile of Virginia/virginia, who's slug is seen in the link URL.

This is currently a private install but, if you'd like, we can include links once we publish the site. However, we believe the behavior is universal.

Thanks for all your great work on BuddyBoss!

Ephrem

<img width="750" alt="Screen Shot 2022-01-28 at 11 02 48 AM" src="https://user-images.githubusercontent.com/98613662/151606419-e3ad84c9-8b03-4cc4-8bfd-e20724be3146.png">
<img width="750" alt="Screen Shot 2022-01-28 at 11 03 18 AM" src="https://user-images.githubusercontent.com/98613662/151606428-7303082f-1e09-4b8f-93b6-93431be66fd7.png">

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
