### ISSUE TITLE
When you are not anymore member of a private group, you cannot still have access to files, folders, subjects you created before leaving, it's a security issue.

### ISSUE THREAD

**Issue by Obeeone-tech** [buddyboss/buddyboss-platform#3328]
**Describe the bug**
When you are not anymore member of a private group, you cannot still have access to files, folders, subjects you created before leaving, it's a security issue.

**To Reproduce**
As a member of a private group, 
I create a new folder and I upload a file in the folder,
then I leave that private group.

If I go to my timeline, or général timeline, I can :
- still download my file
- still delete my file
- still create another folder and move my file in that folder
- still be notified for a comment about that file
Also , if I had copied before the url of that folder for sharing with someone in private messaging, I can still download the folder which may contains other files from members of that group.

As a member of a private group, 
I create a new subject forum, 
Then I leave that private group.

If I go to my timeline, or général timeline, I can :
- still make a quick reply to the subject I had created
- still be notified of an answer in that subject.

**Expected behavior**
when you leave a private group, you can not access to any items in it, neither modify them. 

**Environment**
Tested on buddyboss-platform 1.8.7 , buddyboss-platform-pro 1.1.9.1 and buddyboss-theme 1.8.5

**Support ticket links**
#158392

**Comment by Obeeone-tech** [comment]
Not all the behavior but some of then also apply to a public type group  when you not anymore member of that group:
documents  : 
- still delete my file
- still create another folder and move my file in that folder
- still be notified for a comment about that file
subject forum : 
- still make a quick reply to the subject I had created
- still be notified of an answer in that subject.

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
