### ISSUE TITLE
Buddy Boss Role doesn't get updated after the changing the WP Role

### ISSUE THREAD

**Issue by teachersep1978** [buddyboss/buddyboss-platform#3354]
Problem: Buddy Boss Role doesn't get updated after changing the WP Role

We have three times of roles: 
organizer  ---- > WP Editor
Instructor -------> WP Contributor 
Member ------ > WP subscriber 

The issue is that after updating the WP roles the Buddyboss profile roles don't get updated accordingly. Every role is displayed as a "member"

**Comment by azanoni** [comment]
Which BuddyBoss platform version are using? and which version of Wordpress?

**Comment by mahedihasannoman** [comment]
Hi @teachersep1978 ,
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
Thanks.
