### ISSUE TITLE
Menu Items don't match between to different Admin accounts 

### ISSUE THREAD

**Issue by teachersep1978** [buddyboss/buddyboss-platform#3355]
Menu Items don't match between two different Admin accounts 

**To Reproduce**
1. Two Admin users go to the Appearance and Menu section (Admin Dashboard)
4. one admin has visibility to 5 setting items while the other admin has visibility to 8 items 

**Expected behavior**
Both Admins should see the same number of items 

**Screenshots**
![Screenshot_8](https://user-images.githubusercontent.com/78563774/155761725-c7ca953e-1773-4168-a7d9-2fbf8acb4129.png)
![Screenshot_7](https://user-images.githubusercontent.com/78563774/155761738-2edb0dde-ca5c-41eb-ab82-f4b64a32bb69.png)

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
