### ISSUE TITLE
Notification link for reply to a forum topic reply taking user to the wrong page

### ISSUE THREAD

**Issue by scarabcoder** [buddyboss/buddyboss-platform#3376]
**Describe the bug**
When a forum topic has more than one page of replies, and a user replies/comments on a reply on a previous page, the notification URL for the new reply always takes the user to the last page of replies. 

**To Reproduce**
1. As User A, go to a topic with more than one page of replies
2. Reply to a topic reply from User B on the first page of replies
3. As User B, click the notification for the new reply
4. User B will be taken to the last page of replies for the topic, even though the reply in the notification is on an earlier page

**Expected behavior**
The user should be taken to the new reply that was made.

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
