### ISSUE TITLE
BP Members template - Compatibility issue with PHP 7.2

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#3389]
Could you please remove the "," to avoid compatibility issues with PHP 7.2 : 

https://github.com/buddyboss/buddyboss-platform/blob/d90bf7c33262a4d17de7d03466ebd327fce138f8/src/bp-members/bp-members-template.php#L2881

Lines : 2824, 2830, 2837, 2881, 2887, 2894

Thanks

**Comment by aterchin** [comment]
Same issue here.  Have a production server that cannot be upgraded to PHP 7.3 yet.

**Comment by meetmakadiya** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
