### ISSUE TITLE
Issue: GIPHY not working on replies coming from notifications - #57491

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#339]
**Describe the bug**
GIPHY not working on replies coming from notifications

**To Reproduce**
1. Post something in activity like mentioning "@" some user so they will be notified
2. Log in to that User and click on the notification, it will open to a single activity post
3. Add a Giphy reply to that user, the GIF shows nothing

**Expected behavior**
The GIPHY will show blank when you reply to a single activity post coming from notifications

**Screenshots**
https://www.loom.com/share/6d3cff4ad4fc4cea9d8da254cd619537

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/57491

**Comment by janakkaneriya007** [comment]
Working on sandbox site: https://www.loom.com/share/ffbc3214c14144289ee2b5ac5e6e5d28
