### ISSUE TITLE
Upgrading to Version 1.9.1 from last ver. 504 Error 

### ISSUE THREAD

**Issue by Nimdy** [buddyboss/buddyboss-platform#3390]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Go to '...' Plugins, 
2. Click on '....' Update Plugin

**Expected behavior**
Click update plugin and it should update

**Screenshots**
None

**Environment**
AWS Fargate ECS, EFS, Docker, Wordpress, NGINX, PHP-FPM, Aurora DB. 

**Support ticket links**
None

More Details:

Some strange behavior is being experienced during the upgrading from the latest ver to 1.9.1

When I click update, I receive a 504 error.

I understand that NGINX timeout and sock timeout issues when people have their servers with configurations that do not match the resources provided.  I can assure you that my resources are fine and the configurations on the backend are correct.

During the upgrade, I watched the folder directory delete and watched the folder directory build with the new folder structure.  When the folders and files stopped creating, I then noticed the 504 error.

I attempted this a few times and received the same results.

I even attempted to upload the files from the "add plugins" upload process and I received the same result.

After about 10 mins of my 8th attempt, I got up and came back about 8 mins later.  I then noticed all the folders and files in their place.

I went back to the WP admin plugin folder and saw BBP not activated and I proceeded with the activation.  

Everything came up just fine.

Not sure why this did what it did... but it did.

Also, is there any keep alive attempt during upgrading or uploading of the plugin?

Thank you

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
