### ISSUE TITLE
Media > caption

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#343]
**Describe the solution you'd like**
We should have caption for media on popup when we view the media. it should use the WP attachment's caption field. 

![image](https://user-images.githubusercontent.com/4090336/70620674-e5ab1a00-1c3d-11ea-85f8-01afba728349.png)

**Describe alternatives you've considered**
No alternatives yet.

**Comment by eisenwasser** [comment]
Closing, this is fixed in Documents branch.
