### ISSUE TITLE
Sharing TikTok links

### ISSUE THREAD

**Issue by glasner1982** [buddyboss/buddyboss-platform#3432]
Posting TikTok links to the activity feed by copy and paste, will link the username in the TikTok link to the Buddyboss profile of the same user, if that user exists on both platforms with the same name username.

https://www.growthread.com

Buddyboss Platform v1.9.3

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
