### ISSUE TITLE
Media > Choose profile photo from uploaded media

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#345]
**Is your feature request related to a problem? Please describe.**
User can upload the photo or cover of profile or group and display them but there is no option to chose from uploaded media.

**Describe the solution you'd like**
User should be given option to choose from uploaded media to select profile and group photo or cover. And user should be given option in the media where they can choose this media as profile photo or cover.

**Comment by mikejyoung** [comment]
Closing this issue. I've added to Product Board.
