### ISSUE TITLE
Cover image upload returns filetype error even though the filetype is correct.

### ISSUE THREAD

**Issue by TheWizardofWikacy** [buddyboss/buddyboss-platform#3463]
You guys have spelling errors in your allowed filetype code.  You spelled jpg as "jpe" and it is caausing an error to return when members try to upload a cover photo.

Will you guys PLEEZE stop breaking things with every update.

**Comment by meetmakadiya** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
