### ISSUE TITLE
Buddyboss feed upload image not working

### ISSUE THREAD

**Issue by waqaskhan8080** [buddyboss/buddyboss-platform#3469]
Hey can you check why the image screwed up
https://snipboard.io/9oI3rU.jpg

**Comment by meetmakadiya** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
