### ISSUE TITLE
Elementor Backend: Woo Products Grid 

### ISSUE THREAD

**Issue by claudioripoli** [buddyboss/buddyboss-platform#3470]
BuddyBoss Pro
BuddyBoss Theme
Elementor PRO

Hello!
when you insert a products grid it is displayed as in the attached image. 
There is no way to see it correctly. 
Is there any way to fix this bug? it's frustrating.
Can you help me?

Thanks,
Claudio

PS I opened a ticket but no one answers me

<img width="1580" alt="Schermata 2022-05-08 alle 10 32 11" src="https://user-images.githubusercontent.com/13406514/167288318-729b52fe-2f23-4b76-8923-a9869358ce04.png">

**Comment by surajkrsingh** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
