### ISSUE TITLE
Developer Issue : Create a hook when an activity is created and not edited

### ISSUE THREAD

**Issue by ExoGeek** [buddyboss/buddyboss-platform#3476]
Hello,

I try to create an action when user creates an activity... but I don't want to process that specific action when user update/edit the activity.

I can use the add_action 'bp_activity_add' or 'bp_activity_after_save' but there's not easy way to know if the activity is added or the activity is updated.

My suggestion is to modify the line below : 

https://github.com/buddyboss/buddyboss-platform/blob/8b7f2ba498db76bd0cbae84c1f45e4fb45764725/src/bp-activity/bp-activity-functions.php#L2236

in 

`do_action( 'bp_activity_add', $r,  $activity );`

---------------------------------------------
For the moment, the only way I've found : 

```
function my_activity_add_action_helper ( $activity ){
	if ( empty( $activity->id ) ) {
		add_action( 'bp_activity_after_save', 'my_custom_function', 999 );
	}
}
add_action( 'bp_activity_before_save', 'my_activity_add_action_helper', 999 );
```

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
