### ISSUE TITLE
Forum Post Tag Dropdown Selection Issue

### ISSUE THREAD

**Issue by darrylsyms** [buddyboss/buddyboss-platform#3483]
**Describe the Bug**
When adding tags, there's a selection dropdown that "suggests" pre-existing tags. If you type something that's an incomplete word, and then select something from the dropdown, both the complete and incomplete word will be attached the the post when publishing. Please see video showing this behaviour on the demo site.

On a site note, the dropdown completely obscures the text input which is a bit annoying. Nothing a little CSS margin can't fix though 👍 

**To Reproduce**
See video:
https://user-images.githubusercontent.com/82924984/168453330-82ce47b6-c3cc-44c0-92e3-4e9dae8d2dcf.mp4

**Expected Behaviour**
Only the selected tag should be published, not the unfinished phrase.

**Environment**
BussyBoss Demo Sandbox

**Comment by surajkrsingh** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
