### ISSUE TITLE
impossible to translate these strings

### ISSUE THREAD

**Issue by EloFran** [buddyboss/buddyboss-platform#3484]
**Describe the bug**
Impossible to translate these strings, before updating they were translated, after updating and synchronizing the .pot they are no longer translated. And I can't find how to translate them in any way.

**To Reproduce**
1. Go to 'wp-admin/index.php'
2. Now in forum

[https://prnt.sc/R8D5mE4zGLG8](url)
**Expected behavior**

**Screenshots**
[https://prnt.sc/R8D5mE4zGLG8](url)

**Comment by surajkrsingh** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
