### ISSUE TITLE
Developers keep changing css classes with every update

### ISSUE THREAD

**Issue by TheWizardofWikacy** [buddyboss/buddyboss-platform#3493]
The absolute worst practice for plugin developers is to keep changing the classes applies to elements which causes site owners custom css to break every time they update the buddyboss platform.  STOP DOING THIS YOU FREAKIN IDIOTS!

**Comment by meetmakadiya** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
