### ISSUE TITLE
[PHP 8.0 Error] Required parameter $notification follows optional parameter $size

### ISSUE THREAD

**Issue by laurelstreng** [buddyboss/buddyboss-platform#3598]
**Describe the bug**
Since upgrading to PHP 8, I've been seeing the following error: `Required parameter $notification follows optional parameter $size` reported from `wp-content/plugins/buddyboss-platform/bp-notifications/bp-notifications-functions.php:1198`

**To Reproduce**

1. Use the latest version of WordPress and BuddyBoss platform
2. Use PHP v8.0+
3. Enable WordPress debugging to see error

**Comment by noplanman** [comment]
https://github.com/buddyboss/buddyboss-platform/pull/3572

**Comment by meetmakadiya** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
