### ISSUE TITLE
Groups Discussions with Sub Forums View Mismatch

### ISSUE THREAD

**Issue by tjbuddyboss** [buddyboss/buddyboss-platform#364]
**Describe the bug**
When group discussions have subforums the main discussion forum and sub forums are shown differently. The main forum is show in list view and the sub forums are shown in card view. They should either both be the same view or allow to choose which view for both. (I think having a choice to choose which view is best)

**To Reproduce**
1. Create New Group
2. Create New Parent Forum
3. Create Child Forum
4. Assign New Parent Forum to New Group
5. Post discussion topic in New Parent Forum
6. See Activity Feed for New Parent Forum activity item
7. Post discussion topic in Child Forum
8. See Main forum in list view, sub forum in card view

**Expected behavior**
These forums should either have the option to change views or should both be the same view

**Screenshots**
![image](https://user-images.githubusercontent.com/54224831/70941167-b65f2900-2000-11ea-9bbf-447f7545c327.png)

**Support ticket links**
NONE

**Comment by chetansatasiya** [comment]
@tjbuddyboss I think this intensional. So I am closing this issue.
