### ISSUE TITLE
Black borders for the video preview in a discussion reply

### ISSUE THREAD

**Issue by little-brother** [buddyboss/buddyboss-platform#3641]
The video preview has fixed 16:9 aspect ratio

[activity-entry.php](https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-templates/bp-nouveau/buddypress/video/activity-entry.php#L111)
```
data-setup='{"aspectRatio": "16:9", "fluid": true, ...
```
If the video has another aspect ratio (e.g has a 800x600 resolution) then an user will see black borders. That doesn't happen if the aspect ratio is correct. The ratio can be easily defined if a preview image exists and therefore `$width` and `$height` are defined. The quick fix can be like below

```
data-setup='{"aspectRatio": "<?php echo $width && $height ? $width . ":" . $height : "16:9" ?>", "fluid": true, ...
```

P.S.  I can't send the report via [Report page](https://www.buddyboss.com/report-a-bug) due "Sorry, you have been blocked. You are unable to access buddyboss.com"-error.

P.P.S. I found by chance
> We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.

So maybe it worth to change a bug report template on GitHub?

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
