### ISSUE TITLE
BuddyBoss Group Hierarchies conflict with Send Invites

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#365]
**Describe the bug**
BuddyBoss Group Hierarchies allows user to have subgroups of the group. There is one setting in Group Hierarchies called **Restrict Invitations** which restricts the members to be invited to subgroups before being the member of the parent group, but currently user can request and group organizer can send invitation to be a member of the subgroups without being a member of the parent group first. For more detail please refer the video below.

**Video**
https://www.loom.com/share/0f709d9731f8437795929d47e561b21a

**Support ticket links**
Basecamp - https://basecamp.com/2472620/projects/16981946/todos/402944338
Trello - https://trello.com/c/jk2tgYgt/8-6-buddyboss-groups

**Comment by chetansatasiya** [comment]
This is already fixed in #254 so closing this issue.
