### ISSUE TITLE
Group Type could not be selected when assigning to Groups

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#366]
**Describe the bug**
The client is on localhost, using the BuddyBoss Theme and BuddyBoss Plugin.

There are several issues for this and it is numbered based on the zendesk ticket, I will divide them into Bugs and Feature requests.

Bugs:
1. In BuddyBoss Theme, when posting a feed on the Timeline, we can click the published date/time of the post and it is linked to a single post. This functionality is not present in the BuddyBoss Theme/BuddyBoss Platform. See screencast.
https://www.loom.com/share/59c10fe3b21944dd86e1239ee4d72198

**2. Group Type could not be selected when assigning to Groups. See Group Type bug screencast.
https://www.loom.com/share/2f00b9df5b474ebe865cc41c263626a1**

3. Emoji is not showing correctly in sent messages (see screenshot messages.png). I have tested this and I could not replicate this because it works on my end, but the client has sent his computer specs regarding this issue. 

As per client: "I see this bug only on Chromium 74.0.3729.169 browser (in activity stream and messages). I have disabled all extensions.
But on Firefox v68.0 (x64) browser everything looks good.
My OS: Ubuntu 16.04 (x64) Linux 4.15.0-55-generic"

**Screenshots**
![messages](https://user-images.githubusercontent.com/53221322/70962448-2047f480-203a-11ea-9486-5441dfd92370.png)

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/48288

**Comment by chetansatasiya** [comment]
This is already fixed in #253 so closing this issue.
