### ISSUE TITLE
Syntax error in BB Platform - new install

### ISSUE THREAD

**Issue by planckc** [buddyboss/buddyboss-platform#3664]
Parse error: syntax error, unexpected ')' in /home/xxx/yyy/zzz/wp-content/plugins/buddyboss-platform/bp-core/bp-core-functions.php on line 4692

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
