### ISSUE TITLE
Incorrectly using current_theme_supports( 'block-templates' ), need to switch to wp_is_block_theme()

### ISSUE THREAD

**Issue by kadencewp** [buddyboss/buddyboss-platform#3697]
**Describe the bug**
In two places inside of the buddyposs platform you are checking for current theme supports block templates when that is not correct, block templates support can be used in classic themes to allow users to create templates, this does not mean the theme is a FSE theme. You instead need to use wp_is_block_theme(). 

See here: https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/bp-core-template-loader.php#L406
And here: https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-forums/core/template-functions.php#L418

**To Reproduce**
1. Use a classic theme that has enabled block templates
2. Try to visit the forum page
3. You will see "No matching template found"

**Expected behavior**
The template canvas file should not be loaded in this case, as it's not a FSE theme.

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.

For your information, for this issue it's already forwarded to the development team.
