### ISSUE TITLE
Error when editing published Templates

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#375]
**Describe the bug**
When editing a saved template in Elementor an error occurs. Furthermore, it only happens to published Templates, when you change the status of the template to Draft you will be able to edit it again. This only persists when BuddyBoss Platform Plugin is activated

**To Reproduce**
1. Go to Elementor > Saved Templates
2. Click on any published templates
3. See error

**Expected behavior**
Should be able to edit published templates without changing the status to Draft

**Screencast**
https://d.pr/v/N66Wh1

**Support ticket links**
https://secure.helpscout.net/conversation/1111986829/6439/
https://secure.helpscout.net/conversation/1111983597/6176/
https://secure.helpscout.net/conversation/1111976337/5582/
https://secure.helpscout.net/conversation/1111929607/2037/
https://secure.helpscout.net/conversation/1124772882/66280/
https://secure.helpscout.net/conversation/1135585863/68497/
https://secure.helpscout.net/conversation/1136225070/68622/
https://secure.helpscout.net/conversation/1153000875/71523/

**Comment by archanabb** [comment]
https://secure.helpscout.net/conversation/1135585863/68497/

**Comment by annrra** [comment]
@ayron-paul 
Does this issue still exists?
Not able to reproduce - https://www.loom.com/share/8ad88579c9d64f0aac0caa8536a50d30

**Comment by ayron-paul** [comment]
Hi @annrra, yes, I was able to replicate this in our demo site. 
https://drive.google.com/file/d/1FVZSdXDPj4YbUg-WVEP4IrYUy6M8uOPb/view

Make sure that your homepage is a BuddyBoss Component page like News feed.

**Comment by annrra** [comment]
Thanks @ayron-paul 
Yes, now I can replicate that issue
I guess we expect support for BuddyPress

**Comment by mehulkaklotar** [comment]
https://github.com/elementor/elementor/issues/8551
