### ISSUE TITLE
Issue: Scrolling on Mobile renders to footer -#53296

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#376]
Issue can be replicated on demo

View page on mobile and scroll down, specifically Activity page

refer to this video: https://drive.google.com/open?id=1YCzdCuZSnmP7r-QK0y5SbyQJfvXgiOhA

This is only happending when Widgets are activated on the Activity feed.

**Comment by sagarjadhav** [comment]
Moved to theme issues - https://github.com/buddyboss/buddyboss-theme/issues/628
