### ISSUE TITLE
Could not edit Saved Templates of Elementor Pro when BuddyBoss Platform is activated - #57403

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#380]
**Describe the bug**
Could not edit Saved Templates of Elementor Pro when BuddyBoss Platform is activated

**To Reproduce**
MemberPress 1.7.3, BuddyBoss Platform 1.2.2 and BuddyBoss Theme 1.2.9 and Elementor Pro 2.7.3 must be activated
1. On Elementor, Create a New Template
2. Add a Single as Template, and Post as template type and name your template
3. Add anything on the layout
4. Publish it
5. Go the Saved Templates, click Edit with Elementor

**Expected behavior**
When you go to the Tempate and click edit with Elementor, it will prompt "go back"

**Screenshots**
https://www.loom.com/share/9ef6e5351dd84717b68a224175b6bba9

https://www.loom.com/share/03eca53337aa45ff82ed525637dc5389

**Support ticket links**
https://secure.helpscout.net/conversation/1111993697/6946/

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1135262060/68415?folderId=3701258

**Comment by sagarjadhav** [comment]
@mehulkaklotar Can you please look into this?

**Comment by lateamtec** [comment]
Hi everyone !
I have the same problem, has a solution been found?
