### ISSUE TITLE
Images & Videos do not display in feeds, user posts - Current version: 2.2.7

### ISSUE THREAD

**Issue by xcantene** [buddyboss/buddyboss-platform#3843]
**Describe the bug**
Working on a community platform, when activating media and testing to upload any via front, all images seem broken as the following:

![image](https://user-images.githubusercontent.com/53211659/221180821-e7ca155b-3356-4b2c-bd33-5df1e09e13b5.png)

Equally this issue happens when uploading any video- The format used was mp4:
![image](https://user-images.githubusercontent.com/53211659/221181124-e95bfca6-f748-43a7-abf2-b041786f556f.png)

I have read in the previous post that this could be an issue with symlinks but I am oblivious of what those are or even how to enable or disable them whichever could be the problem.

These are my current plugins in use:
![image](https://user-images.githubusercontent.com/53211659/221181355-c5c41cc3-f751-437b-94e1-d3e7b93271de.png)

Any suggestions on what could it be and how to fix it?

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
