### ISSUE TITLE
Issue with do_action( 'wp_login',  $username, $user)

### ISSUE THREAD

**Issue by tahiriqbalnajam** [buddyboss/buddyboss-platform#3852]
**Describe the bug**
I am trying to auto login(programmatic   login) user from our other site with an email and a confirmation token, so for this, I am using 

wp_set_current_user( $user_id, $username);
wp_set_auth_cookie( $user_id );
do_action( 'wp_login', $username, $user );

This thing logged the user but as I am trying to go to other pages, user get logged out.
If I disabled the buddyboss things are absolutely fine, login and other pages are accessible for user.

**To Reproduce**
1. try to programmatic  login 
2. User logged in successfully
3. Now try to go to any other secure page.
4. You will logged out.
5. After deactivating buddyboss things are fine.

**Comment by bb-yudhisthir** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
