### ISSUE TITLE
Adding underscore "_" does not allow users to register

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#391]
**Describe the bug**
Adding underscore "_" does not allow users to register gives 'Error: Sorry, Nickname may not contain the character ""!

**To Reproduce**
1. Place '_' in nickname.
2. Register. 
3. Error appears.

**Support ticket links**
https://secure.helpscout.net/conversation/1111985977/6372/
https://secure.helpscout.net/conversation/1111910557/507/

**Comment by chetansatasiya** [comment]
@ankitguptaindia I see you removed the label. Is this tested?
