### ISSUE TITLE
Mobile Scrolling jumps to footer when Left and Right widgets are activated on Activity

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#392]
**Describe the bug**
On our demo, the Activity page footer is behaving/moving by itself on mobile scrolling.

**To Reproduce**
1. In Appearance Widgets > Add Left and Right Widgets on Activity page
2. View footer on mobile and try to scroll
3. Remove the Left and Right Widgets
4. View footer again on Mobile, the footer is not auto scroling

**Expected behavior**
Try to scroll the footer part of Activity page on mobile, you will see auto scrolling

**Screenshots**
https://drive.google.com/file/d/1YCzdCuZSnmP7r-QK0y5SbyQJfvXgiOhA/view

**Support ticket links**
https://secure.helpscout.net/conversation/1112026284/9304/

**Comment by sagarjadhav** [comment]
Duplicate -
https://github.com/buddyboss/buddyboss-platform/issues/376
https://github.com/buddyboss/buddyboss-theme/issues/628
