### ISSUE TITLE
Submit button does not work on the forum topic and reply form (mobile only)

### ISSUE THREAD

**Issue by dralawady** [buddyboss/buddyboss-platform#3947]
submit button does not work on the forum topic or reply form when browsing from android chrome on mobile.  We've also noticed that the submit button will work on mobile if we start the text entry by pressing 'return' key before writing any text.

please notice that the error doesn't appear on the desktop chrome dev tools  in the 'mobile' mode. To get the error and troubleshoot the problem, you have to use 'remote debugging' and connect an android mobile to the debug desktop station.

------------------------------ the error log -------------------------------------------------------------
`jquery-migrate.min.js?ver=3.4.0:2` JQMIGRATE: Migrate is installed, version 3.4.0
jquery.min.js?ver=3.6.3:2 Uncaught Error: Syntax error, unrecognized expression:  jgjfjf fzfsgdhdghdh jffjfuttuyyfu 
`<br>`
    at se.error (jquery.min.js?ver=3.6.3:2:13759)
    at se.tokenize (jquery.min.js?ver=3.6.3:2:21770)
    at se.select (jquery.min.js?ver=3.6.3:2:22597)
    at Function.se (jquery.min.js?ver=3.6.3:2:7116)
    at Function.<anonymous> (jquery-migrate.min.js?ver=3.4.0:2:2847)
    at e.<computed> [as find] (jquery-migrate.min.js?ver=3.4.0:2:1566)
    at S.fn.init.find (jquery.min.js?ver=3.6.3:2:25167)
    at S.fn.init (jquery.min.js?ver=3.6.3:2:25656)
    at e.<computed>.<anonymous> (jquery-migrate.min.js?ver=3.4.0:2:2387)
    at new e.<computed> (jquery-migrate.min.js?ver=3.4.0:2:1566)
se.error @ jquery.min.js?ver=3.6.3:2
se.tokenize @ jquery.min.js?ver=3.6.3:2
se.select @ jquery.min.js?ver=3.6.3:2
se @ jquery.min.js?ver=3.6.3:2
(anonymous) @ jquery-migrate.min.js?ver=3.4.0:2
e.<computed> @ jquery-migrate.min.js?ver=3.4.0:2
find @ jquery.min.js?ver=3.6.3:2
S.fn.init @ jquery.min.js?ver=3.6.3:2
(anonymous) @ jquery-migrate.min.js?ver=3.4.0:2
e.<computed> @ jquery-migrate.min.js?ver=3.4.0:2
S @ jquery.min.js?ver=3.6.3:2
(anonymous) @ editor.js?ver=2.3.3:200
(anonymous) @ medium-editor.min.js?ver=2.3.3:1
triggerCustomEvent @ medium-editor.min.js?ver=2.3.3:1
updateInput @ medium-editor.min.js?ver=2.3.3:1
handleInput @ medium-editor.min.js?ver=2.3.3:1`

**Comment by kubano09** [comment]
I have the same problem...
Clear cache works for me
