### ISSUE TITLE
Adding Support for MemberPress + BuddyPress Integration when using MemberPress pro

### ISSUE THREAD

**Issue by Ravinder-qa** [buddyboss/buddyboss-platform#406]
**Description**
Getting Fatal error when trying to activate the MemberPress + BuddyPress Integration with memberpress pro plugin. It's work with Memberpress basis but not with Pro version

**Support ticket links**
https://secure.helpscout.net/conversation/1112163162/15362/

**Comment by marienel21** [comment]
Bug nonexistent in the current product version.
Steps done:
1. Activate Memberpress Pro plugin 
2. Activate  MemberPress + BuddyPress Integration plugin
Both plugins activate successfully and functional
