### ISSUE TITLE
Add the missing hooks into the Activity Comments

### ISSUE THREAD

**Issue by raftaar1191** [buddyboss/buddyboss-platform#4062]
**Describe the bug**
https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-activity/classes/class-bp-activity-activity.php#L1670
Hook is missing to perform the order by Query, So we need a filter to do that. 

**Expected behavior**
There should be a hook that a third-party developer can use to alter the SQL query for Activity Comment like we have in legacy version.

**Comment by firozwp** [comment]
We are no longer accepting GitHub issue submissions- as our issue tracking and development projects have now moved to JIRA. [Click here](https://www.buddyboss.com/moving-to-jira/) to read more about it.
If you wish to report an issue or bug, please do so from the [BuddyBoss Support Portal](https://support.buddyboss.com/support/login)- or [Report a Bug](https://www.buddyboss.com/report-a-bug) directly on our site.
