### ISSUE TITLE
Messages > Date Separator

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#407]
**Is your feature request related to a problem? Please describe.**
When viewing a message in your inbox, we need to show the messages group by date like Today, Yesterday and Friday, December 20th and so on... 

**Describe the solution you'd like**
We like to display the message same as on Slack.

![download (1)](https://user-images.githubusercontent.com/7081284/71408359-e000fb80-2663-11ea-9d39-fdf12bed12af.png)

**Comment by mattttis** [comment]
This would be a great feature!

**Comment by mikejyoung** [comment]
I'm closing this issue as we will be implementing this as part of our Live Messaging feature that we are currently working on. It will be readded to this repo when the issue has been properly scoped and ready for development.
