### ISSUE TITLE
Optimise the SQL

### ISSUE THREAD

**Issue by singhleo** [buddyboss/buddyboss-platform#4235]
https://github.com/buddyboss/buddyboss-platform/blob/5d524e1365374592ee537cbec6606220ec443a45/src/bp-members/bp-members-functions.php#L5620

In above SQL please make sure that `$unique_identifier` is not empty when being passed to query & remove the use of `DISTINCT` 

removing `DISTINCT` will improve the performance. and we don't really need DISTINCT here.

**Comment by firozwp** [comment]
Jira issue: https://buddyboss.atlassian.net/browse/PROD-6511
