### ISSUE TITLE
We shouldn't run the generate new slug on foreground.

### ISSUE THREAD

**Issue by singhleo** [buddyboss/buddyboss-platform#4236]
https://github.com/buddyboss/buddyboss-platform/blob/5d524e1365374592ee537cbec6606220ec443a45/src/bp-members/bp-members-functions.php#L197

In above code it's generating the slugs of users when  the page is loading. this can endup running generate slug function multiple times in pages like members etc. 

Instead we should use nickname default if user slug is not found.

**Comment by firozwp** [comment]
Jira issue: https://buddyboss.atlassian.net/browse/PROD-6511
