### ISSUE TITLE
Missing pagination for subforums.

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#425]
**Describe the bug**
Missing pagination for subforums. Replicated in demo as well.
No pagination even in default theme Twenty Twenty

**To Reproduce**
1. Create Parent Forum
2. Create at least 16 subforums (assigned to Parent Forum)
3. Keep default forums per page setting = 15

**Expected behavior**
Pagination should be visible for subforum sections when number of forum per page is exceeded

**Screen record**
https://www.loom.com/share/b6010f721c1048788006cd043554dbc5

**Support ticket links**
https://secure.helpscout.net/conversation/1111976917/5624/

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1213201186/81188

**Comment by shohelbuddyboss** [comment]
Fixed bu Pull https://github.com/buddyboss/buddyboss-platform/pull/441

**Comment by mehulkaklotar** [comment]
@marilyn9425 @shohelbuddyboss @archanabb @ayron-paul @furqanbb 

This is something that we can not support now because it interferes with all pagination links across site for forums. Sub forums can have maximum paged forums by using the following function in child theme's functions.php file.

```
function buddyboss_theme_child_bbp_get_sub_forums_per_page( $retval ) {
	if ( bbp_is_single_forum() ) {
		return -1;
	}
	return $retval;
}
add_filter( 'bbp_get_forums_per_page', 'buddyboss_theme_child_bbp_get_sub_forums_per_page' );
```
