### ISSUE TITLE
Default Data > ability to create default data for LearnDash

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#426]
**Is your feature request related to a problem? Please describe.**
When our customers create a new site setup, we provide default data for most social content. However we provide no default data for LearnDash, and it is very time consuming to create test LearnDash data.

**Describe the solution you'd like**
In BuddyBoss > Tools > Default Data:
Add a section for LearnDash, if LearnDash plugin is enabled.
From here, checkboxes to create default Courses, Lessons, Topics.

**Describe alternatives you've considered**
There does not appear to be any plugins or solutions anywhere that do this.

**Comment by mikejyoung** [comment]
Closing this issue. I've added to Product Board.
