### ISSUE TITLE
Group Types settings Profile Type joining access

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#428]
**Describe the bug**
Group Types settings Profile Type joining still has "Request Access" even if Profile Type is restricted.

**To Reproduce**
1. Create a Profile Type. example names: Profile Type 1 and Profile Type 2
2. Create New Groups. example names: Group 1 and Group 2
	2a. On Group 2. Set Privacy to Private.
	2b. On Group 2 Forum Settings > check Yes. I want this group to have a discssion forum
3. Create Group Types. example names: Group Type 1 and Group Type 2
	3a. On Group 2 Profile Type invites settings, select the created Profile Type 2.
	3b. and on the Profile Type Joining also select the created Profile Type 2.
4. Create new Forum. example name: Main Forum
5. Go to all Forums, and select Group 2 forum as a child of Main Forum
6. Create a new User and assign as a Profile Type 1
7. Login to created user and go to Group 2 forums and even though he is in Profile Type 1, he could still request access to Group 2 even if the Joining is limited to Profile Type 2 users

**Expected behavior**
Even if a user is assigned to a Profile Type 1, he still has a chance to access Profile Type 2, which is private.

**Screenshots**
https://www.loom.com/share/a3c3f9e8a8d045c0a0a95916a16f91fa

**Support ticket links**
https://secure.helpscout.net/conversation/1111977117/5641/

**Comment by janakkaneriya007** [comment]
@emmanoctaviano 

I think you have misunderstood the settings of group type and profile type:
Refer below video and let me know if you have any query:
https://www.loom.com/share/70f31152d0f74996940da952cf31e9c5
