### ISSUE TITLE
ErrorException: ob_flush(): Failed to flush buffer. No buffer to flush

### ISSUE THREAD

**Issue by jonyking** [buddyboss/buddyboss-platform#4296]
**Describe the bug**
Hello,
we noticed some notices in your code. We use sentry.io to detect errors and notices on our platforms. So we got over 2,5k times the following error:
Notice: ob_flush(): Failed to flush buffer. No buffer to flush

Stack Trace:
 buddyboss-platform-pro/includes/reactions/bb_reactions_functions.php  in bb_admin_setting_reaction_notice_field_callback at line 216

**Expected behavior**

**Screenshots**
<img width="1937" alt="Bildschirmfoto 2024-02-07 um 10 21 59" src="https://github.com/buddyboss/buddyboss-platform/assets/24831213/0e72cb2d-133c-49d6-8791-67c5a9affef5">

**Environment**
WordPress version: Up-to-date
Buddypress version: Up-to-date

**Comment by igaitan** [comment]
Hello, we are having the same issue with latest versions recently updated (2.5.40 Version)
This issue breaks member ajax search, and almost all ajax messages and notifications api calls.
