### ISSUE TITLE
Buddypress User Blog video preview is not showing properly on activity feed

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#443]
**Describe the bug**
Buddypress User Blog video preview is not showing properly on the Activity Feeds when the link is inserted using the video link importer.

**To Reproduce**
1. Install Buddypress User Blog
2. make sure the following are enabled:
- BuddyBoss > Settings > Activity > **_When links are used in activity posts, display an image and excerpt from the site_**
- BuddyBoss > Settings > Activity > **_Blog Posts_**
- BuddyBoss > User  Blog > **_Enable User Publishing_**

3. Go to the user profile page and create a new blog
4. Insert a video link (like youtube) using the importer
![import](https://user-images.githubusercontent.com/58522498/71647493-db5ad800-2d32-11ea-886b-41ca55596119.png)
5. Publish and go to activity

**Expected behavior**
Video preview should display properly and not just a broken image icon.

**Screenshots**
When using the importer:
![directly](https://user-images.githubusercontent.com/58522498/71647502-07765900-2d33-11ea-81a6-7e06cd4e38cc.png)

When inserting the link directly, works fine:
![insert-directly](https://user-images.githubusercontent.com/58522498/71647503-09d8b300-2d33-11ea-9ebf-037606558a01.png)

**Screencast**
https://drive.google.com/file/d/1qiZMyO_D1ON_xZF_piWRoNWnSd1P3RUn/view?usp=sharing

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/59126

**Comment by chetansatasiya** [comment]
@manishpatolia @ankitguptaindia I need the status what's remaining here.

**Comment by manishpatolia** [comment]
@chetansatasiya @ankitguptaindia I have solved the issue as per the last comment and push on the `buddypress-user-blog`. and also left a comment on the Trello card.

please test again and let me know if any issue there.

**Comment by chetansatasiya** [comment]
@manishpatolia @ankitguptaindia @ayron-paul I am closing this issue because this issue is related to `buddypress-user-blog` plugin not in platform.

**Comment by ankitguptaindia** [comment]
@chetansatasiya Okay Chetan, we'll review and deal with this issue On User Blog Trello card.

https://trello.com/c/Nb2lxf6V/164-buddypress-user-blog-video-preview-on-activity-page
