### ISSUE TITLE
UX issue - User Activity getting posted partially on News feed. 

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#450]
**Describe the bug**

**Scenario-** when user posting multiple media in activity and at the time of uploading media on page, if clicked the `Post Update` button then post getting uploaded without all media. (partially data)

Watch the attached video for detailed info.

**To Reproduce**

1. Go to News Feed
2. Click on upload more than 3-4 images
3. Click Post Update Button

**Expected behavior**
Post should not publish with uploading all Media

**Screenshots**
https://www.loom.com/share/912c2932f3814162a1caacbfbc82cf9c

**Support ticket links** N/A. Reported by QA

**Comment by marienel21** [comment]
This issue no longer exists in the latest version of the product.
