### ISSUE TITLE
Delete function not working when mentioning "@" in mobile

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#452]
**Describe the bug**
Delete function not working when mentioning "@" in mobile

**To Reproduce**
Actual Android 9 devices must be used.
1. Go to Activity Page
2. Try "@" mentioning someone
3. Try to delete that in your phone backspace

**Expected behavior**
When you delete the mentioned user, the first letter only gets delete, the rest of the characters cant be deleted

**Screenshots**
https://drive.google.com/file/d/13o4i4qqoQoLF6zyfCMGgY-O4rGow5VPx/view

**Support ticket links**
https://secure.helpscout.net/conversation/1112063516/11336/

**Comment by dipskakadiya** [comment]
@emmanoctaviano We got the same issue with the web and we fixed it. Can you check again? It should be fixed now.

**Comment by emmanoctaviano** [comment]
@dipskakadiya good to close. original ticker was closed already.
