### ISSUE TITLE
Unable to see Forum Activities in Member Profile when Forum Discussion, Replies, Favorites is associated to a Private Group

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#453]
**Describe the bug**
Unable to see Forum Activities in Member Profile when Forum Discussion, Replies, Favorites is associated to a Private Group. Replicated on demo

**To Reproduce**
1. Create a Private Group then associate it with a Forum Discussion
2. Add a non-admin member to the group (on the screenshot, Charles)
3. Using the non-admin member, add new discussion in a Private Group created
4. Using the non-admin member, go to profile > forums. Under My Discussions, you won't be able to see the discussion created in #3
5. Using the admin, go to the creator of the profile (Charles) > forums, under My Discussion you will see the discussion created in #3

**Expected behavior**
Even when a member of the private group creates a discussion, add a reply. The user can't see the discussion they created in their profile > forums >  My Discussion/ My Replies

**Screenshots**
_Admin View_
![admin-view](https://user-images.githubusercontent.com/53599687/71762313-c5067500-2f08-11ea-924d-130477f98b38.png)

_Admin View_
![admin-view2](https://user-images.githubusercontent.com/53599687/71762314-c59f0b80-2f08-11ea-9880-672c43efd562.png)

_Non Admin View_
![user-member-forums](https://user-images.githubusercontent.com/53599687/71762315-c59f0b80-2f08-11ea-83f8-4c2e0dbe5d92.png)

_Non Admin View_
![user-member-forums2 PNG](https://user-images.githubusercontent.com/53599687/71762316-c59f0b80-2f08-11ea-8167-8870d9263488.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1112128367/14098/
https://secure.helpscout.net/conversation/1111975763/5526/
https://secure.helpscout.net/conversation/1111980415/5929/

**PR Created added in Trello**
https://github.com/buddyboss/buddyboss-platform/pull/162

**Comment by janakkaneriya007** [comment]
@marilyn9425 
PR is linked for this issue.
Please check it's working or not. If it's working fine we can close this issue
