### ISSUE TITLE
BP activity shortcode like and comment option are not working

### ISSUE THREAD

**Issue by raftaar1191** [buddyboss/buddyboss-platform#460]
**Describe the bug**
When using BP activity shortcode on some page and when members "liking" or "commenting" on the activity it forces the whole page to refresh and commenting doesn't work, it just refreshes the page.
https://wordpress.org/plugins/bp-activity-shortcode/

**To Reproduce**
1. Install BuddyBoss platform and BuddyBoss Theme
2. Install the BP activity shortcode plugin 
3. Create a new page and add BP activity shortcode into the page and then try click ono like or try adding thee comment it will reload the pages and would not add any comment or like

**Expected behavior**
Like and Comment all the option should work

**Screenshots**
https://www.loom.com/share/15f2f6bf49d04fca944e30d3e612a869

**Support ticket links**
https://secure.helpscout.net/conversation/1112177882/15853/

**Comment by marienel21** [comment]
Component of this BP activity shortcode bug
- Hitting Like ( this is working on the latest version of the product ) 
- ** Adding Comment** - VALIDATED. Comment ca't be added

**Comment by mikejyoung** [comment]
Closing this as its a third party integration, which should be supported by the developer.
