### ISSUE TITLE
Words are broken in the URL preview of the activity.

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#463]
**Describe the bug**
When we share a URL in the activity, the preview generated looks fine. But when we post it, the preview is reduced a little and that breaks some words. 

**To Reproduce**
1. Go to 'activity page'
2. Add a URL and see the preview
3. Post the activity

**Expected behavior**
The preview while adding the activity and the preview after posting the activity should be the same. The words should not break. If the word is long, it should be shifted to the next line. 

**Screenshots**
https://www.loom.com/share/9f442d895e3c4197bb660938f662df52

**Support ticket links**
https://secure.helpscout.net/conversation/1111964632/4661/

**Comment by chetansatasiya** [comment]
I am closing this as per the @eisenwasser comment here on https://github.com/buddyboss/buddyboss-platform/pull/464#issuecomment-603474084
