### ISSUE TITLE
Groups with Arabic titles are not accessible. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#465]
**Describe the bug**
If a group title is in Arabic, it is not accessible. It throws an error "too many redirects". If the title has one word in English or the title is in English, it works without any issues. Also, on the user's site, I noticed that after creating the group, the slug is changed to "%d8%a". 

**To Reproduce**
1. Go to 'Create Group Page'
2. Create a group only with Arabic words
3. Open the group page

**Expected behavior**
The groups with Arabic names should be accessible without issue. 

**Screenshots**
- https://i.imgur.com/jnoQiMl.jpg 
- https://i.imgur.com/7YmKYpM.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1111981063/5973/

**Note**
I was not able to replicate the issue on my local site. But I could not make it work on the user's site even with the BuddyPress plugin and Twenty Nineteen theme. This could be a user-specific issue. I forwarded to @chetansatasiya and he asked me to create a card as this requires to be fixed on our end.

**Comment by KartikSuthar** [comment]
@archanabb @chetansatasiya @ankitguptaindia 
I have checked for the issue with the latest branch and I am not able to reproduce the issue.
http://somup.com/cYitjP6lVj

Can you please check and inform me if you are still able to reproduce the issue.
