### ISSUE TITLE
Comments are not available for Events, forum activities even if they are enabled at the backend.

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#467]
**Describe the bug**
An option to comment on the activities generated for events, forums is not available. It is enabled on the backend in the activity settings. 

**To Reproduce**
1. Go to 'activity settings page in the backend' and enable activities for forums and custom post types (events)
2. Click on 'activity page'
3. Scroll down to 'the events or forums activities'

**Expected behavior**
Only like and delete options are available. Option to comment is not working.

**Screenshots**
- https://i.imgur.com/M1jnFlM.jpg
- https://i.imgur.com/XNf1t7q.jpg

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/59215

**Comment by bryanr18lowe** [comment]
Hi @chetansatasiya Any update on the 'events' commenting fix would be so appreciated! Thank you!
