### ISSUE TITLE
Gamipress Achievement/Awards embeds in Activity

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#472]
**Describe the bug**
When a user is awarded with an Achievement/Rank in Gamipress, it shows the embedded content.

**To Reproduce**
1. BuddyBoss Platform, Gamipress and Gamipress BuddyPress integrations plugins must be activated
2. In Gamipress, create a new Achievement Type, ex. name: New Tests
3. In the New Tests, enable Achievement activity entries
4. Create a New Tests award, ex: Latest Award
5. In Latest Award, add Earned By: admin awarded and add featured image
6. In BuddyBoss > Settings > Activity > Posts in Activity Feeds > Custom Post Types. enable New Tests
7. In WP Dashboard, click Edit Your Profile and award yourself with New Tests award
8. See the Activity Page

**Expected behavior**
A preview of Achievement image will be shown and also a WP embedded content

**Screenshots**
https://drive.google.com/open?id=1iYFh6i5Mfxt4f-XP2qOxYOStpP6jfQ7u

**Support ticket links**
https://secure.helpscout.net/conversation/1112154579/15041/

**Note**
This maybe related with https://github.com/buddyboss/buddyboss-platform/issues/383 but that issue is adding a direct link in Activity

**Comment by dipskakadiya** [comment]
@emmanoctaviano Step:6 is not need for Gamipress Award Activity. You need to activate that only if you want to create activity on a new post created of post type `New Tests` 

Gamipress Award Activity will work without that setting

I tested with the latest code, it's working fine

<img width="919" alt="Screenshot 2020-09-09 at 4 06 56 PM" src="https://user-images.githubusercontent.com/2979084/92588462-a4bc6080-f2b6-11ea-8fa5-c66106ebf8c4.png">
