### ISSUE TITLE
Privacy issue - the user is still searchable with the fields set to "Only Me"

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#502]
**Describe the bug**
Privacy issue, when a user sets any field's visibility to "Only Me", the field is still being used as search reference thus making the user to be included in the search result.

**To Reproduce**
Steps to reproduce the behavior in Demo:
1. Using John's account, go to Profile > Edit Profile
2. For example, set "Phone" field's visibility to "Only Me".
3. Now, using another account, try to search the phone number of John and he will be included on the search result

**Expected behavior**
The field that is already set to "Only me" should be excluded from the search details of a user.

**Screencast**
https://drive.google.com/file/d/15_eNT_MChpGXlPlg4uOfzpvc_2JEmGPv/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1111957338/4162/

**Comment by ankitguptaindia** [comment]
Connected PR Tested. This issue is fixed.
