### ISSUE TITLE
Error on forums page. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#503]
**Describe the bug**
There is an error on the forum index page:
_strstr(): Empty needle in/home/platne/serwer44366/public_html/wp-content/plugins/buddyboss-platform/bp-templates/bp-nouveau/buddypress-functions.php_

**To Reproduce**
1. Go to 'Forum index page'
2. See error

**Screenshots**
- https://i.imgur.com/1RbzOfh.jpg

**Support ticket links**
- https://buddyboss.zendesk.com/agent/tickets/60475

**Comment by emmanoctaviano** [comment]
same customer experienced this. tested all his plugins and theme, and the issue seem to come when Forum Discussions is enabled. I have asked for his hosting details. https://buddyboss.zendesk.com/agent/tickets/63105
