### ISSUE TITLE
GamiPress Achievement/Points Images are blurry.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#508]
**Describe the bug**
The images of the achievements/points are blurry. Regardless of the size of the image is uploaded the image gets blurry in the activity feed. The same image in the media folder is nice and crisp.

**Screenshots**
https://prnt.sc/qq9c9p
https://prnt.sc/qq9cg2
https://prnt.sc/qq9coq
https://prnt.sc/qq9d3e

**Support ticket links**
https://secure.helpscout.net/conversation/1111953724/3897/

**Comment by marienel21** [comment]
GamiPress integration doesn't show any issues with images on the latest version.
