### ISSUE TITLE
No error message in registration is shown when username already existed

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#520]
**Describe the bug**
When a user tries to register a nickname but it is already used as a username by other members, no error message will show on the registration page.

**To Reproduce**
1. Try to edit any of your existing users by changing its current **NICKNAME**, make sure that nickname is different from **USERNAME**.
2. On your registration page, try to register and use the **USERNAME** of the account you have just modified, as the nickname.
3. The page will just refresh with no error being shown.

**Expected behavior**
An error message should display, notifying the user that the nickname or username has been taken already

**Screencast**
https://drive.google.com/file/d/1WuC4b1J8-AnJTljs6ngJ3pLjT382dJ_e/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1111949273/3578/

**Comment by mehulkaklotar** [comment]
this commit fixes this issue https://github.com/buddyboss/buddyboss-platform/commit/5749425698df8a5f2b39157b9c8cad65933f9280
