### ISSUE TITLE
List of members in the group invite page is incomplete

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#521]
**Describe the bug**
Not all members of the site are showing in the group invite page

**To Reproduce**
1. Go to any Groups
2. Under Send Invites, the members are incomplete

**Expected behavior**
The complete list of members should appear

**Screenshots**
![group-invites](https://user-images.githubusercontent.com/58522498/73128195-afb3d080-4006-11ea-828c-bad883e39741.png)

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/60831

This might be related: https://github.com/buddyboss/buddyboss-platform/issues/301

**Comment by chetansatasiya** [comment]
@KartikSuthar @ayron-paul I am closing this issue because it's working and fixed as per your conversations.
