### ISSUE TITLE
Jetpack Plugin is conflicting with profile Photo cropping.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#524]
**Describe the bug**
When you upload a photo all you see is a dot in the space where the cropping is supposed to work.

**To Reproduce**

1. Enable the Jetpack plugin and set up the plugin (You have to go through the complete setup process.)

2. Navigate to the profile page and try to change the profile photo.
3. See error.

**Screenshots**
https://prnt.sc/qspeer

**Support ticket links**
https://secure.helpscout.net/conversation/1111950441/3658/

**Comment by shohelbuddyboss** [comment]
Can't reproduce the issue, I installed Jetpack, and checked, it's working. Can anyone help me to reproduce it?

**Comment by furqanbb** [comment]
@shohelbuddyboss Try enabling the site accelerator settings in Jetpack.

**Comment by shohelbuddyboss** [comment]
@furqanbb I enabled site accelerator and others settings, but didn't get any issue, it will be great if you can reproduce this issue.

Best Regards

**Comment by chetansatasiya** [comment]
Confirmed with @furqanbb and it's not reproducible anymore.

**Comment by Anve-sri** [comment]
@chetansatasiya @mehulkaklotar @shohelbuddyboss Image crop has issues with jetpack 'Lazy load ' settings. Please refer to this screenshot https://prnt.sc/u6lwn3

if you disable this setting in Jetpack, the cropping works.

**Comment by chetansatasiya** [comment]
@Anve-sri See here https://www.loom.com/share/25cf2985d4034993ad78cc5c16bf282f even that setting on there is no issue. Working fine.

**Comment by Anve-sri** [comment]
@chetansatasiya , I have found many tickets related to this issue and disabling the 'Lazy Load' solves it. You can also check the below ones. 

https://secure.helpscout.net/conversation/1254440237/88298
https://secure.helpscout.net/conversation/1265474032/90253
https://secure.helpscout.net/conversation/1263391473/89926
https://secure.helpscout.net/conversation/1267411282/90587
https://secure.helpscout.net/conversation/1255180421/88428

Many more are there. Also , i have googled it and found https://github.com/Automattic/jetpack/issues/10016
You can also try with the Group image.

**Comment by chetansatasiya** [comment]
@Anve-sri Looking into this once I get the demo site with the issue is replicable.
