### ISSUE TITLE
Menus in groups and forums under Profile page are missing - WPML

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#531]
**Describe the bug**
When BuddyBoss Platform and WPML are both activated, the BuddyPanel, TitleBar and footer menus are missing in GROUPS, PHOTOS, and FORUMS under Profile Page.

**To Reproduce**
1. Activate WPML, BuddyPress Multilingual plugins together with BuddyBoss Platform
2. In WPML > Languages, make sure that Language URL format is set to Different languages in directories, please see below:
![langugae_url](https://user-images.githubusercontent.com/58522498/73572686-6226e000-44ac-11ea-90d2-bb7942578103.png)
3. Make sure that you have already set menu links on both BuddyPanel and titlebar
3. On the frontend, go to the profile page and navigate on groups and forums

**Expected behavior**
Menus should display on GROUPS, PHOTOS, and FORUMS under Profile Page

**Screenshots**
![wpml-missing-menus](https://user-images.githubusercontent.com/58522498/73572876-e5e0cc80-44ac-11ea-8916-84d68eec2a83.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1112031720/9694/
https://secure.helpscout.net/conversation/1112029122/9508/
https://secure.helpscout.net/conversation/1111935339/2453/
https://secure.helpscout.net/conversation/1127812593/66929/
https://secure.helpscout.net/conversation/1136280364/68633/
https://secure.helpscout.net/conversation/1138657882/69114
https://secure.helpscout.net/conversation/1164333433/73381
https://secure.helpscout.net/conversation/1134655135/68272

Related issue: https://github.com/buddyboss/buddyboss-platform/issues/396

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1134655135/68272
