### ISSUE TITLE
Update for BuddyPress Group Email Subscription on our Platform

### ISSUE THREAD

**Issue by MichaelKitt** [buddyboss/buddyboss-platform#553]
Experiencing slow loading issues as we are using an old version of BPGES that doesn’t include the asynchronous tools.

As per Michael, we have forked our Platform with BuddyPress v3.1 and this issue was fixed 
with BuddyPress v3.9

**Support ticket links**
https://buddyboss.slack.com/archives/GCCRGAZGS/p1581078275143500
https://secure.helpscout.net/conversation/1111937547/2615/

**Comment by grahamhoffman** [comment]
We have this feature as part of BuddyBoss Platform.

Dev Ops are looking at how to scale this feature on mass for large email subscriptions but 70 members shouldn't be  causing any problems at all.
