### ISSUE TITLE
Profiles/Groups > Cover Photo Cropper

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#561]
**Is your feature request related to a problem? Please describe.**
When you upload a profile photo, you can crop it.
When you upload a cover photo, you cannot crop it. But the cover photo has a really wide dimension and so most the photos you upload look terrible. If you could crop the photo vertically it would be much nicer. This is a highly requested feature.

**Describe the solution you'd like**
Do some research to find the best script for doing this, then experiment with that script in Platform. We will need to add support for it in the theme later also. Consider mobile also.
https://www.loom.com/share/f97b41de9e954704bcaff99d9133bc75

**Support ticket links**
https://secure.helpscout.net/conversation/1111922914/1512/

**Comment by firsthym** [comment]
This is what I am looking forward to!

**Comment by eisenwasser** [comment]
@firsthym Awesome :)

**Comment by hobhobuk** [comment]
Is this feature going to be added anytime soon?

I am now having to look into other platforms which is costing a hell of a lot of money as clients are fed up with the lack of being able to crop images..  

Sorry to sound a pain, but this is a basic feature.. And the BP platform was not a cheap purchase..

**Comment by eisenwasser** [comment]
@hobhobuk 
This is built already and in final testing. Likely to go live later in September.

**Comment by fun99** [comment]
@hobhobuk also it was informed in 1.5.0 but not, and i am also waiting too much for video upload support, it was in Roadmap written in Q3 and now i seen its moved to Q3, it means no hope before December OR maybe next year also.

Please don't mind, but it's true, buddyboss team is very slow in development basic features for social platforms. While basic features should be add first.

**Comment by sourabhmatolia** [comment]
@firsthym  @hobhobuk  @fun99 

Issue created above is released in Buddyboss Platform v1.5.1.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-1/

Please update the plugin to see the latest changes.

Thank you.

**Comment by hobhobuk** [comment]
Hello, fully updated and there is zero option to crop cover photos..
Profile yes, but not cover.

**Comment by hobhobuk** [comment]
This is not cropping.. this is uploading, then going to the profile and moving the image.

Shame you guys couldn't do the same with profile photos for this.. would have been great and very user friendly.
