### ISSUE TITLE
Xprofile dropdown field new options not saving after certain options

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#562]
**Describe the bug**
Xprofile dropdown field new options not saving after certain options like 150 to 200 and it always saying like the link is expired.

**To Reproduce**
1. Go to BuddyBoss > Profiles > Add New Field > Select Field Type to Dropdown
2. Add 100 to 200 options
3. Click on Save/Uppdate
4. It will not save the options

**Expected behavior**
It should be save all the options without any limit.

**Screenshots**
https://prnt.sc/r0mww0

**Support ticket links**

**Comment by Anve-sri** [comment]
https://buddyboss.zendesk.com/agent/tickets/61871
