### ISSUE TITLE
Profile - Mentions Tab redirects to 404

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#564]
**Describe the bug**
When you go to the mentions tab in the profile page an HTTP ERROR 404 occurs

**To Reproduce**
1. Make sure that **Activity Tabs** is enabled in BuddyBoss > Settings > Activity
2. Go to profile page > Timeline > Mentions
3. Redirected to error page

**Expected behavior**
It should show the feed you have been mentioned

**Screenshots**
![mentions](https://user-images.githubusercontent.com/58522498/74273401-60320c00-4d4b-11ea-8cf1-ba50ed3ed19c.png)
![error](https://user-images.githubusercontent.com/58522498/74273410-61633900-4d4b-11ea-8be7-1cd50c362faf.png)

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/61994
https://buddyboss.zendesk.com/agent/tickets/61994

**Comment by Anve-sri** [comment]
Getting https://prnt.sc/r14c5w
