### ISSUE TITLE
Unrelated results are being shown when using photo search

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#566]
**Describe the bug**
When you try to search an image using the filename or the description some of the results are not related

**To Reproduce**
1. Upload a photo in your profile or groups. Make sure to add a description or proper filename of the photo.
2. Go on the main photos page "/photos" and search for the photo that you have just uploaded.
3. See that the results have other unrelated photos in it and that those extra photos also appear in other searches.

**Expected behavior**
Unrelated results should not appear

**Screenshots**

- Upload with banana description
![photo-upload](https://user-images.githubusercontent.com/58522498/74479798-cacd7e00-4eea-11ea-9bcd-e213588af02b.png)

- Searched banana in photos archive
![photos-page](https://user-images.githubusercontent.com/58522498/74479793-c903ba80-4eea-11ea-949d-d330e7307b1d.png)

**Screencasts**
- https://www.loom.com/share/a5deb2a433324314a1b78a3df6b1a221
- https://www.loom.com/share/67a240ed84b14914a649b85088cbcfc3

**Support ticket links**
https://secure.helpscout.net/conversation/1111935198/2441/

**Comment by mehulkaklotar** [comment]
This issue has been fixed in recent releases.
