### ISSUE TITLE
The error warning does not display on the login page after changing the Login page URL

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#573]
**Describe the bug**
The error warning does not display when entering wrong info on both email/password fields after changing the login page url using WPS hide plugin or any other plugin.

**To Reproduce**
https://www.loom.com/share/0580b77065eb47aa82688b067bb0e7fa

**Expected behavior**
It should display the error when entering the wrong info on both email/password.

**Support ticket links**
https://secure.helpscout.net/conversation/1111937587/2620/

**Comment by manishpatolia** [comment]
@furqanbb I have checked with the latest dev pull and I seem it's working fine for me.
Please see my proof and let me know if I'm wrong.
I saw the client details on the ticket but that is not working. if the client has still this issue then please provide me details for the client dev site so I can check with client data.

https://www.loom.com/share/8a1c1df3b2124c6684ce6b8460f8fed8

**Comment by furqanbb** [comment]
Tested it on my local and this issue seems to be fixed. Please close this issue.
