### ISSUE TITLE
One Social to BuddyBoss Platform/Theme photo migration issue

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#575]
**Describe the bug**
Users who have uploaded images in the Gallery/Photos of One Social Theme and migrated to BuddyBoss Platform have their Photos transferred to the Admin user.

Meaning UserA has uploaded photos in Gallery of One Social Theme, then the website Migrated to BuddyBoss Platform/Theme, but after migration, the photos of UserA are now assigned to the Admin in the Gallery

**To Reproduce**
1. In One Social Theme setup: bbPress, BuddyPress, BuddyBoss Media must be active
2. In BuddyBoss Media, set up Gallery/Photo page
3. Login a different user (ex: UserA) in another browser and upload images in Gallery/Photos page
4. Go back as an Admin and change the website to BuddyBoss Platform/Theme set up
  4a. Deactivate all plugins
  4b. Change from One Social to BuddyBoss Theme
  4c. Activate BuddyBoss Platform
  4d. Set up Photos page in BuddyBoss Platform settings
  4e. In BuddyBoss > Tools > Media > Run Migration
5. Go to Photos page and click on the images uploaded by UserA, it is now named as uploaded by the Admin

**Expected behavior**
The photos in the Gallery/Page must still be named for the user who uploaded the image.

**Screenshots**
https://drive.google.com/open?id=1dh56xuMgpffxiJioZgq_4zXDacl3ghcX

**Support ticket links**
https://secure.helpscout.net/conversation/1111933277/2316/

**Added Notes**
In my local environment, I have checked the database for this
After running the Import Media tool, the `activity_id` of `wp_bp_media` does not match the ID of `wp_bp_activity`. See attached images
![wp_bp_activity](https://user-images.githubusercontent.com/58522224/74753741-873c9080-52ab-11ea-9ef5-b3cf91b45ded.JPG)
![wp_bp_media](https://user-images.githubusercontent.com/58522224/74753747-8a378100-52ab-11ea-935d-79f374bf5b40.JPG)

**Comment by buntybuddyboss** [comment]
@emmanoctaviano I've tried to check this on my local site, but not able to re-produce the issue. Could you please check this again.

Here is the video from my Local: https://www.loom.com/share/20e5353648464b22a7fe1d1b1aff7abd

**Comment by chetansatasiya** [comment]
Closing this as this is not reproducable anymore @emmanoctaviano feel free to open if you have steps to reproduce again.
