### ISSUE TITLE
Supplement Buddyboss with WP Rocket

### ISSUE THREAD

**Issue by TW593** [buddyboss/buddyboss-platform#580]
Hello I would like to give a suggestion for buddyboss to improve much more. this improvement applies to PageSpeed after creating my website optimize the site make all sorts of changes to accelerate much more the loading of my website both mobile and computers but the problem is that even if you optimize the theme and plugin and the whole site only reaches 50% of maximum score 60 now I found a solution to reach 80 to 100 score this is with the plugin wp rocket but the problem is that by activating this function is damaged the site 

the menu is deactivated and everything is moved in the mobile phone, the web is completely damaged, that's the error I noticed, my question is that it would be good if you optimize buddyboss to work perfectly with the wp rocket plugin, because inside the plugin there is an option called Alternative CSS Critical Path

this option improves the page 100% for 24 hours the page works full fast both for mobile and computers but after 24 hours the whole web is damaged and you have to deactivate this function 

it would be good if you optimize the theme and plugin to work perfectly with buddyboss or at least minimize buddyboss css because every update gets worse I hope this helps you and I hope you can make buddyboss compatible with wp rocket

**Comment by eisenwasser** [comment]
@TW593 

Thanks for your suggestions.

We have some big plans to improve BuddyBoss speed in more meaningful ways than this. We are working internally on our API and then we will be able to start caching API requests which should make very noticeable speed improvements.

> it would be good if you optimize the theme and plugin to work perfectly with buddyboss or at least minimize buddyboss css because every update gets worse

What do you mean when you say every update gets worse? I don't understand that comment. The CSS is already minimized in BuddyBoss in every update. It's also conditional, meaning if a feature or external plugin is disabled, the associated CSS is not loaded at all.

To be clear, the main things causing a social network site to slow down is not CSS. It is the fact that all data is live and dynamic, so there is a heavy burden on the server. Solutions related to CSS might improve the site speed by 1% maybe, and that is only on the first view. Second page view, your browser is already caching all of the CSS locally. The main way to speed up these sites is to cache the database requests, which is complex to do and needs to be done programmatically, and is something we are working on. Plugins like WPRocket will never solve the speed issue in a meaningful way. Almost all of the speed issues come from the server side, not the CSS in the browser.

**Comment by marienel21** [comment]
Hi @TW593,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
