### ISSUE TITLE
New Discussion modal window not working.

### ISSUE THREAD

**Issue by Jaydeep-Trivedi** [buddyboss/buddyboss-platform#587]
**Describe the bug**
New Discussion modal window is not opening because of a JS error when the plugin is activated with LearnDash Ratings, Reviews & Feedback plugin. 
`Uncaught ReferenceError: bp_select2 is not defined
    at HTMLDocument.<anonymous> (common.js?ver=2.5.14-6684:13)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)`

On further debugging found that the bp_select2 variable is only localized if wp_get_available_translations doesn't exist.

This code is present in bp-core/bp-core-cssjs.php. Please check the following link
https://github.com/buddyboss/buddyboss-platform/blob/dev/src/bp-core/bp-core-cssjs.php#L219

This issue is occurring because the LearnDash Ratings, Reviews & Feedback plugin also uses wp_get_available_translations function.

We can further extrapolate it to mean that if any plugin uses wp_get_available_translations in the frontend and its code is executed before buddyboss-platform then the code inside the "if condition" will not execute and all the js files which use bp_select2 variable will throw a JS error.

**Expected behavior**
The if condition should only wrap wp_get_available_translations function. The localization condition should be moved outside the if condition.
Alternatively, you can add checks in the js file for bp_select2 variable before using it. 

I am attaching a patch file with a fix for this and I would appreciate it if someone will review this and 
get the fix released as soon as possible.

[patch.zip](https://github.com/buddyboss/buddyboss-platform/files/4234779/patch.zip)

**Screenshots**
![Screenshot from 2020-02-21 12-53-49](https://user-images.githubusercontent.com/29191685/75012964-427e4880-54a9-11ea-8985-25a50090d7c3.png)

**Comment by chetansatasiya** [comment]
@Jaydeep-Trivedi Thanks for reporting the issue. We have fixed the issue and it will be in our next release soon.

**Comment by Jaydeep-Trivedi** [comment]
@chetansatasiya Thanks a lot :) I appreciate the quick response. Is the release date for the upcoming release finalized?

**Comment by chetansatasiya** [comment]
@Jaydeep-Trivedi At this moment it's not finalized.

**Comment by eisenwasser** [comment]
@Jaydeep-Trivedi Release will be in a week or two.

**Comment by eisenwasser** [comment]
@Jaydeep-Trivedi This is live now in today's release.
