### ISSUE TITLE
Group pagination issue on backend

### ISSUE THREAD

**Issue by janakkaneriya007** [buddyboss/buddyboss-platform#592]
**Describe the bug**
Group pagination number is not working on backend

**To Reproduce**
1. Go to Groups in backend
2. Try to change the number of group pagination

**Expected behavior**
Should change the group number and save properly

**Video**
https://www.loom.com/share/6b4ab9356c8f4810b5d3747a545b6ae0

**Comment by manishpatolia** [comment]
This is the duplicate issue so closing.
A related issue is #541
