### ISSUE TITLE
Forum form not displaying when Forum Feature > Post Formatting is unchecked

### ISSUE THREAD

**Issue by marilyn9425** [buddyboss/buddyboss-platform#599]
**Describe the bug**
No form displays when creating a new discussion or replying to a forum thread when Forum Features > Post Formatting is unchecked

**To Reproduce**
1. Go to BuddyBoss > Settings > Forums
2. Forum Features section, uncheck Post Formatting
3. Go to a Forum, create New Discussion or Reply to a forum thread
4. No form popup, the URL adds #new-post

**Expected behavior**
**Forum features that can be toggled on and off** indicates that the setting can be optional.
The form should still display whether the option is checked or unchecked

**Screenshots**
https://prnt.sc/r8bc5a
https://prnt.sc/r8balj
https://prnt.sc/r8bbef

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/62928

**Comment by chetansatasiya** [comment]
@marilyn9425 this already fixed in #577 #587 Can you check like it's fixed in latest dev branch or not?

**Comment by chetansatasiya** [comment]
Closing this issue because it's been fixed in latest dev branch.
