### ISSUE TITLE
Attaching a Parent forum for Groups forums is not working.

### ISSUE THREAD

**Issue by AmineBAIK1** [buddyboss/buddyboss-platform#601]
**Describe the bug**
When a user create a discussion in a Group. the forum generated (discussion) is going on root forums even when we choose a parent forum in (Settings -> Forums -> Group Forums Parent)

**Steps to reproduce the behavior**:
Go to " Settings -> Forums -> Group Forums Parent " Choose a Forum as a Parent forum. 
Create a group -> Discussions -> New Discussion ->  Create a discussion and submit. 
Go to all forums page, Open the forum generated / edit and look Forum attributes (Parent)

**Comment by shohelbuddyboss** [comment]
It seems didn't found any issue, parent forum is showing https://prnt.sc/te0iwm
Or can anyone help me to understand what should be there?

**Comment by chetansatasiya** [comment]
Closing this as this is not reproducable anymore.
