### ISSUE TITLE
Double check and cross marks

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#614]
**Describe the bug**
When you are typing a post in a forum discussion, it allows you to highlight the text and format it, including adding a hyperlink. When you click to add a hyperlink, there are 2 checkmarks and 2 cross marks.

**To Reproduce**
1. Go to 'Forum Discussion page and  reply to any forum discussion'
2. Highlight a text and click the hyperlink option.
3. See error

**Screenshots**
https://prnt.sc/rao3gm

**Comment by shashank-buddyboss** [comment]
@furqanbb 

I am closing this issue as it is related to theme and also I have created a same issue on buddyboss-theme side.

https://github.com/buddyboss/buddyboss-theme/issues/473

Thanks.
