### ISSUE TITLE
Hidden groups unavailable for Learndash group sync with Social group.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#617]
**Describe the bug**
The hidden social groups are unavailable in Learndash groups setting for Social group sync under 'Associated Social Group' setting. You can assign Public and private group though. 

**To Reproduce**
1. Go to BuddyBoss > Groups > Add new 
2. Choose 'hidden' in Group privacy. 
3. Go back to Learndash > Groups , edit
4. You will not see hidden group in 'Associated social group' setting.  

**Expected behavior**
All groups should get listed in the 'Associated social groups' setting on learndash groups. 

**Screenshots**
[hid.zip](https://github.com/buddyboss/buddyboss-platform/files/4280946/hid.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1111926484/1786/

**Comment by manishpatolia** [comment]
@Anve-sri @chetansatasiya I have debugged the code, and I saw when we get the group list that time excludes the hidden status groups.

@chetansatasiya @eisenwasser I need your thoughts. Should it allow the hidden groups?

**Comment by eisenwasser** [comment]
@manishpatolia 

All groups should be available here, including hidden groups.
Hidden group are not hidden from the admin, and this scenario it is the admin doing this.
