### ISSUE TITLE
Ability to use code brackets in text editors

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#618]
**Is your feature request related to a problem? Please describe.**
Users want the ability to easily wrap code in code blocks in forum replies. Some may want it also in messages and activity, so we should just make it a sitewide feature in all text editors.

User feedback:
> One issue my members have run into while using the forums in groups is the ability to add code into brackets. When one highlights the text, it gives limited styling options. I believe they are justification, bold, italic, and numbered list. There isn't any option to style the text in a "code" type of enclosure.

**Describe the solution you'd like**
When double-clicking text you get the tooltips - https://prnt.sc/rb7kaf
We need to add a code </> symbol in here, and it would add the `` brackets around the highlighted text, just like how it works here in Github editor and many other editors.

**Support ticket links**
Posted by user Erich99 on Youtube: https://youtu.be/fDmWumAWy_c

**Comment by yagom** [comment]
I think make options to use Markdown when users write their discussion, message, comments and so on.

**Comment by eisenwasser** [comment]
@yagom 

We are redesigning the whole text editor to be more intuitive, which should help with this in a more prominent way. We'll consider markdown for a future release also, thanks

**Comment by mehulkaklotar** [comment]
this is fixed in PR https://github.com/buddyboss/buddyboss-platform/pull/819

**Comment by alexeyzimarev** [comment]
@eisenwasser unfortunately, the current state of the editor is still by far not ideal. Copy-paste of rich text essentially breaks things.

To my support ticket I got the following reply:

> Regarding your concern, using HTML tags is not yet fully supported with our platform's text editor. In addition, copying and pasting formatted content from external text editors (like Microsoft Word or Pages from MacOS) will not be rendered properly and might cause such an issue, since the platform's text editor only supports Bold, Italic, List, Blockquote, Link and Preformatted text. For now, to remove those HTML tags, you will need to manually edit those forum discussions or replies. We understand that this will cause inconvenience so rest assured that we have already taken note of this in our internal roadmap as a feature enhancement to fully support HTML and other scripting tools when using our platform's text editor. While not guaranteed, it will be posted in our release notes once it is implemented.

None of my users like how it works as they struggle with messages being wrongly formatted, broken, showing up with HTML tags in the text, etc, etc. We all just want a simple Markdown editor option, like the one I am using to write this issue.

**Comment by prokop-solutions** [comment]
It would be ceate if you can integrate asyntax highlighter?
With this shortcodes it possible to adjust the code snippets. 
Like prism.js or other.

For example: I need Visual Basic for Application (VBA) for my forum. (VB is okay if VBA is not available)
Simple typing: [vba]My Code [/vba]
Hit Enter: The plugin/highlighter adjust with css and js the code snippet.

I just tried to integrate a plugin with the buddyboss plattgform but it doesnt work for me.
