### ISSUE TITLE
Importing discussions and replies using a zip or csv file does not assign data to their respected forums/discussions resulting in 404 error. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#619]
**Describe the bug**
Export the discussions and replies. Then, import them back using a csv or a zip file. They are added to the backend but when we visit them on the front end, it results in 404 error. Because the replies are not assigned the respected forums and discussions. 

**To Reproduce**
1. Go to Tools > Export
2. Export the discussions and replies separately
3.  Go to Tools > Import
4. See error: https://i.imgur.com/WKkSwjg.jpg

**Expected behavior**
The replies should be assigned their respective discussions and replies

**Screenshots**
- https://www.loom.com/share/06bd10a2d50d4631b5c17b769c634155

**Support ticket links**
- https://buddyboss.zendesk.com/agent/tickets/63016

**Comment by archanabb** [comment]
Tested this with the bbPress plugin. It works well. Please take a look at the following screenshots,
- https://i.imgur.com/fTUZtkH.jpg
- https://i.imgur.com/eGMnvJe.jpg
- https://i.imgur.com/krXzbXF.jpg

**Comment by chetansatasiya** [comment]
@archanabb We have already discussed and this is not an issue.

To fix this issue customers need to upload files in the below position.

1 ) Upload tags
2) Upload Reply
3) Upload Discussion
4) Upload Forum

and it will assign properly.
