### ISSUE TITLE
Medium Editor Enhancements

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#621]
**Is your feature request related to a problem? Please describe.**
Users having issues recognising floating medium editor in forums and messages while typing reply or message. For example, when user tries to reply via popup. They don't have any idea about whether there is an editor here or not.

**Describe the solution you'd like**
We can have editor floating above toolbar options (media, gif etc.). Or similar to slack, one formatting button which will toggle the editor toolbar.

**Describe alternatives you've considered**
Right now we are using similar to Medium.com concept but it is not enough so we can just improve it according to our needs.

**Comment by mikejyoung** [comment]
Added this to Product Board. We'll review doing this feature at a later date.
