### ISSUE TITLE
Issue with Forum search for non-admin users

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#632]
**Describe the bug**
When you log in as a non-admin user and try to search forums using the search bar appearing on the forum page.
You will get the no results 'Sorry, there were no discussions found.
But When logged as Admin, the forum's search works fine.

**To Reproduce**
1. Enable the forum banner and search from theme settings >> forums (If not enabled).
1. Logged as a normal user and search for forums or discussions.
2. See error (Sorry, there were no discussions found).

**Expected behavior**
It should return the result that matches the search keyword.

**Screencast*
https://screencast-o-matic.com/watch/cYe6lBxqyA

**Support ticket links**
https://secure.helpscout.net/conversation/1111920536/1338/

**Comment by janakkaneriya007** [comment]
@anoopmishrabuddyboss 
Can you please test this and confirm it's working or not?

**Comment by ankitguptaindia** [comment]
@janakkaneriya007 @chetansatasiya 

It would be great if you share in which PR or branch you fixed these issues.
thx

**Comment by ankitguptaindia** [comment]
@janakkaneriya007 
I faced this issue with admin role and subsriber role as well. When I try to search any forum then search not giving expected result.

https://www.loom.com/share/c10f53bfc5704fe0b96d5bd5dbdcf01e

**Comment by janakkaneriya007** [comment]
@ankitguptaindia 

As discussed with you the issue mentioned by @furqanbb is not getting replicated and for the issue you have mentioned, create new issue for that.

**Comment by ankitguptaindia** [comment]
@janakkaneriya007 Crated new issue here- https://github.com/buddyboss/buddyboss-platform/issues/781

Closing this issue.
