### ISSUE TITLE
BB Platform mail does not send using mailgun, and if forcefully send then does not use the BB platform email template.

### ISSUE THREAD

**Issue by manishpatolia** [buddyboss/buddyboss-platform#633]
**Describe the bug**

The issue is platform mail not store in Email log plugin and not send via mail gun detail.
IF we send forcefully(using this filter `add_filter( 'bp_email_use_wp_mail', '__return_true' )`) then it does not use the platform email template.

Buddypress does not use WordPress core’s wp_mail function to send an email, and the email log plugin depends on the filters that are called inside the wp_mail function to log the email.
If we force Buddypress to use WordPress core’s wp_mail function:
add_filter( 'bp_email_use_wp_mail', '__return_true' )
Then the mail will send by SMTP(mailgun) but email will send the plain email, will not use HTML content and it will be store in the email log plugin.
If we do not send forcefully by wp_mail function, then it will not send mail using mailgun but mail formate will use but will not store in any email log.
Please see bellow reference URL:
Buddypress support
https://buddypress.org/support/topic/buddypress-registration-ignoring-wp-mail-smtp/
Email log support
https://wordpress.org/support/topic/buddypress-emails-do-not-appear-in-the-log/

**To Reproduce**
1. Install wp SMTP pro plugin
2. add mailgun detail
3. Go to the message section 
4. Send a message to any of your users and see the mail.

**Screenshots**
When normal mail send:
https://prnt.sc/rejkg2

Forcefully used Wp-mail function:
https://prnt.sc/rejk6g

**Support ticket links**
Tell @cedricbuddyboss and @alan-buddyboss  when completed.

**Comment by eisenwasser** [comment]
Solution done on a client project:

`add_filter('bp_email_use_wp_mail', '__return_true');
add_filter( 'wp_mail_content_type', 'mathetis_use_html_wp_mail' );
function mathetis_use_html_wp_mail() {
    return 'text/html';
}
add_filter( 'bp_email_get_content_plaintext', 'mathetis_get_bp_email_content_plaintext', 10, 4 );
function mathetis_get_bp_email_content_plaintext( $content = '', $property = 'content_plaintext', $transform = 'replace-tokens', $bp_email ) {
    if ( ! did_action( 'bp_send_email' ) ) {
        return $content;
    }
    return $bp_email->get_template( 'add-content' );
}`

**Comment by chetansatasiya** [comment]
@eisenwasser @alan-buddyboss @cedricbuddyboss @manishpatolia 

I added the fix and now onward all the platform email will go via `wp_mail()` function so now no one will face email not sending issue and now they can use another Email Service provider OR customer can use the SMTP plugin to send the email.

@cedricbuddyboss I coordinated with @manishpatolia and added the same patch to the client site and now email is firing perfectly vis SMTP and Mailgun.

**Comment by chetansatasiya** [comment]
![OSjPC6iERC6l7igijRBaYQ](https://user-images.githubusercontent.com/7081284/77038083-dd9b0d00-69d8-11ea-955c-f136df8585fa.png)

**Comment by eisenwasser** [comment]
@mehulkaklotar 

Can you do review on this please?
