### ISSUE TITLE
Activity feed loading issue

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#634]
**Describe the bug**
 When posting activity with a link in it using just **www** and post after the embed finishes. Reloading the page gets stuck on loading activity. It takes time to load the activity feed.
If you add more, it takes longer! I added 4 to the demo site and it took almost 15 seconds to show the activity feed.

**To Reproduce**
Please refer to the video:
http://somup.com/cYeXhOhByx

**Support ticket links**
https://secure.helpscout.net/conversation/1111912705/698/

**Comment by janakkaneriya007** [comment]
@furqanbb 

As discussed with @mehulkaklotar we can't cache the link preview due to performance issues but you can suggest client to enable to object caching and activity link preview will load faster.

**Comment by furqanbb** [comment]
ok thanks @janakkaneriya007
