### ISSUE TITLE
Forums > Support @mentions - Some changes, Issues in newly added feature

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#635]
**Describe the bug**

Ref PR - https://github.com/buddyboss/buddyboss-platform/pull/609

Adding issues/suggestions for improvement in below comment. 

**To Reproduce**

Kindly check comment details

**Expected behavior**

Kindly check comment details

**Screenshots**
Kindly check comment details

**Support ticket links**
N/A

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

Self Tagging should not Trigger Notification.

For ex.  If user ABC is creating reply and tagging himself in reply then it should not trigger the notification in Bell icon.

Watch video- https://www.loom.com/share/9dd0eff502a5408688c8ae177c9fc23c

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 


**Issue/Suggestion-**  Notification should have detailed info like title of Discussion/Reply etc if someone mentioned.

How to Reproduce- https://www.loom.com/share/69f0c372009b48c1a2c64b5c76d7d29d

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

Some weird behaviour when using mention in nested Reply in forum https://prnt.sc/req712


https://www.loom.com/share/88111e4525f54cc39aa8659b30079618

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 
When mentioning more than 1 people in same reply then second member is not tagging properly
It shows always incomplete username.  https://prnt.sc/reqgoh

https://www.loom.com/share/736a05c046b34960a30d5f4645556c6f

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

Suggestion - It would be great if we add SPACE automatically after each @mention if any reply has many users

https://www.loom.com/share/a6875479db9f45d48b8ac0577af7b0d1

**Comment by mehulkaklotar** [comment]
@ankitguptaindia please test these issues now with the PR. https://github.com/buddyboss/buddyboss-platform/pull/640

> @mehulkaklotar
> 
> Self Tagging should not Trigger Notification.
> 
> For ex. If user ABC is creating reply and tagging himself in reply then it should not trigger the notification in Bell icon.
> 
> Watch video- https://www.loom.com/share/9dd0eff502a5408688c8ae177c9fc23c

fixed

> @mehulkaklotar
> 
> **Issue/Suggestion-** Notification should have detailed info like title of Discussion/Reply etc if someone mentioned.
> 
> How to Reproduce- https://www.loom.com/share/69f0c372009b48c1a2c64b5c76d7d29d

It has a topic title in notification. https://prnt.sc/rfwqxe

> @mehulkaklotar
> 
> Some weird behaviour when using mention in nested Reply in forum https://prnt.sc/req712
> 
> https://www.loom.com/share/88111e4525f54cc39aa8659b30079618
> https://www.loom.com/share/14953f5b72634c468513538d3deb2080

Try with new reply and topics. it is fixed now.

> @mehulkaklotar
> When mentioning more than 1 people in same reply then second member is not tagging properly
> It shows always incomplete username. https://prnt.sc/reqgoh
> 
> https://www.loom.com/share/736a05c046b34960a30d5f4645556c6f

Fixed.


> @mehulkaklotar
> 
> Suggestion - It would be great if we add SPACE automatically after each @mention if any reply has many users
> 
> https://www.loom.com/share/a6875479db9f45d48b8ac0577af7b0d1

Not needed. it is being copied from activity and in it we haven't done this.

**Comment by ankitguptaindia** [comment]
> @mehulkaklotar
> 
> Self Tagging should not Trigger Notification.
> 
> For ex. If user ABC is creating reply and tagging himself in reply then it should not trigger the notification in Bell icon.
> 
> Watch video-
> 
> https://www.loom.com/share/9dd0eff502a5408688c8ae177c9fc23c

**This is FIXED ..**

**Comment by ankitguptaindia** [comment]
> @mehulkaklotar
> 
> **Issue/Suggestion-** Notification should have detailed info like title of Discussion/Reply etc if someone mentioned.
> 
> How to Reproduce-
> 
> https://www.loom.com/share/69f0c372009b48c1a2c64b5c76d7d29d

Fixed.

**Comment by ankitguptaindia** [comment]
> @mehulkaklotar
> When mentioning more than 1 people in same reply then second member is not tagging properly
> It shows always incomplete username. https://prnt.sc/reqgoh
> 
> 
> https://www.loom.com/share/736a05c046b34960a30d5f4645556c6f

**Fixed..
Working fine now.**

**Comment by ankitguptaindia** [comment]
> Not needed. it is being copied from activity and in it we haven't done this.

>Dev Response - Not needed. it is being copied from activity and in it we haven't done this.

Okay.

**Comment by ankitguptaindia** [comment]
@mehulkaklotar I also want to test Forum mentioed in Group's Forum but when I am trying to create new group I am getting unknown error and not able to create new group.

https://www.loom.com/share/b56136646c314fa0859ed7aa83a72f76

**Comment by mehulkaklotar** [comment]
@ankitguptaindia there is similar issue with customer about the group creation steps in multisite. you can refer the issue here https://buddyboss.zendesk.com/agent/tickets/63595

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

**Issue-** Tagging a person who has not access of content doesn't make any sense.

**Expected-** 
Hidden Group Forum & Hidden Forum should not show people in Mention suggestion if those members are not in Group or not having access of Group.


**Current Status-** 
tagged member getting a notification and that Notification URL has 404.

** Steps-**  https://www.loom.com/share/51555423f3664b05a958da14ba3cb16d

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

Mention is not working in First Discussion for all members.  Although giving the Suggestion of users. 

Refer for steps-  https://www.loom.com/share/85d8cd1d29b940649fed832c6fbb897a

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

Mentions should cover the whole name in tagging if any user having First Name & Last Name.
Right now, It taking only first name as mention and last name appearing as normal text.

Refer for detail-  https://www.loom.com/share/4d6ee57f656e4e928f7c25c9ce508240

I believe this is not part of this module. Let me know then I will create separate new issue for this suggestion.

**Comment by mehulkaklotar** [comment]
> @mehulkaklotar
> 
> **Issue-** Tagging a person who has not access of content doesn't make any sense.
> 
> **Expected-**
> Hidden Group Forum & Hidden Forum should not show people in Mention suggestion if those members are not in Group or not having access of Group.
> 
> **Current Status-**
> tagged member getting a notification and that Notification URL has 404.
> 
> **Steps-** https://www.loom.com/share/51555423f3664b05a958da14ba3cb16d
> 
> For separate forum - https://www.loom.com/share/106378f8fcab45e99584eaf4237c8e1b

Fixed.

> @mehulkaklotar
> 
> Mention is not working in First Discussion for all members. Although giving the Suggestion of users.
> 
> Refer for steps- https://www.loom.com/share/85d8cd1d29b940649fed832c6fbb897a

@ankitguptaindia you have space in your nicknames which is not allowed in platform at all. fix those space issue and it will convert users in mentions.


> @mehulkaklotar
> 
> Mentions should cover the whole name in tagging if any user having First Name & Last Name.
> Right now, It taking only first name as mention and last name appearing as normal text.
> 
> Refer for detail- https://www.loom.com/share/4d6ee57f656e4e928f7c25c9ce508240
> 
> I believe this is not part of this module. Let me know then I will create separate new issue for this suggestion.

@ankitguptaindia you have space in your nicknames which is not allowed in platform at all. fix those space issue and it will convert users in mentions.

**Comment by ankitguptaindia** [comment]
>Issue- Tagging a person who has not access of content doesn't make any sense.

Fixed. 
As per discussion with developer. Now the user can tag other people who is not in a group but tagged person will not receive any notification with a broken link.

----
>@ankitguptaindia you have space in your nicknames which is not allowed in platform at all. fix those space issue and it will convert users in mentions.

@mehulkaklotar 
First Name and Last name appearing in suggestion when we tag other people.
Video - https://www.loom.com/share/139b3a14dbcf49fe87cb35094027e1d8

----

New Regression Issue-  `&nbsp;`appearing in suggestions with username when tagging someone.
https://www.loom.com/share/4a93355e91c84035b6a1bbd3e0a99f4d

**Comment by mehulkaklotar** [comment]
> > Issue- Tagging a person who has not access of content doesn't make any sense.
> 
> Fixed.
> As per discussion with developer. Now the user can tag other people who is not in a group but tagged person will not receive any notification with a broken link.
> 
> > @ankitguptaindia you have space in your nicknames which is not allowed in platform at all. fix those space issue and it will convert users in mentions.
> 
> @mehulkaklotar
> First Name and Last name appearing in suggestion when we tag other people.
> Video - https://www.loom.com/share/139b3a14dbcf49fe87cb35094027e1d8

@ankitguptaindia there is no way we can have nicknames with spaces. it is validated before submitting. `Invalid Nickname. Only "a-z", "0-9", "-" and "." are allowed.`

> New Regression Issue- `&nbsp;`appearing in suggestions with username when tagging someone.
> https://www.loom.com/share/4a93355e91c84035b6a1bbd3e0a99f4d

This is fixed now.

**Comment by ankitguptaindia** [comment]
>New Regression Issue- &nbsp;appearing in suggestions with username when tagging someone.

This issue has been fixed.

For this- https://github.com/buddyboss/buddyboss-platform/issues/635#issuecomment-601605845

>Mentions should cover the whole name in tagging if any user having First Name & Last Name.
Right now, It taking only first name as mention and last name appearing as normal text.

As discussed on slack, we will fix in a separate issue later. as not related to this PR.
So I will create new issue later. 


We are ready to merge theses fixes in dev @mehulkaklotar  🚀
