### ISSUE TITLE
Styling issue on Learndash courses [Mobile]

### ISSUE THREAD

**Issue by cedricbuddyboss** [buddyboss/buddyboss-platform#638]
**Describe the bug**
On mobile the Learndash course has some styling issues, see screenshots below:
- Our demo: https://prnt.sc/rf2t7r
- My client's live site (not updated to the latest version): https://prnt.sc/rf2jhe, https://prnt.sc/rf2lts
- My client's dev site (up-to-date): https://prnt.sc/rf2j9c, https://prnt.sc/rf2lmu 

**To Reproduce**
Visit any course URL from our demo on mobile: https://demos.buddyboss.com/online-communities/courses/advanced-js-games-visualizations/

**Comment by chetansatasiya** [comment]
@cedricbuddyboss This is a theme issue so I am closing here and created a new issue in theme https://github.com/buddyboss/buddyboss-theme/issues/489
