### ISSUE TITLE
Blog comments are basic

### ISSUE THREAD

**Issue by hobhobuk** [buddyboss/buddyboss-platform#642]
Hello,

I am struggling to get Blog comments to work in a similar fashion to the acivity stream.
I have tried a few plugins, but presume they are clashing with buddyboss as they do not work..
Just wondering if anyone can suggest a way of making the blog comments nicer?

Users can use the activity stream to post emoji, images, videos etc.
However blog comments just show up as normal..
I presume this maybe due to it just being a wordpress standard feature.. so just curious if anyone has suggestions to how to make this area better?

**Jira issue** : [PROD-956]

[PROD-956]: https://buddyboss.atlassian.net/browse/PROD-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hobhobuk** [comment]
If a user posts a blog, it shows on the newsfeed.
If a user then comments this on the activity feed, they can add images etc
If a user adds a comment to the actual blog post, they cannot.

Yet both set of comments show in the activity feed and blog.
So if I upload an image as response on the activity feed, on the blog, it shows as a blank comment.

I really need a fix for this..

**Comment by chetansatasiya** [comment]
@hobhobuk Thanks for the reporting this issue https://github.com/buddyboss/buddyboss-platform/issues/642#issuecomment-599624383

I am working on it and it will be fixed in next release.
