### ISSUE TITLE
Email view - HTML and Email Tokens are stripped down from Email Invites when used with MailGun

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#643]
**Describe the bug**
On Email view,  HTML and Email Tokens are stripped down from Email Invites when used with MailGun

**To Reproduce**
1. Set up a MailGun account (free version)
2. Install MailGun Plugin https://wordpress.org/plugins/mailgun/
3. Setup credentials in MailGun plguin from created mailgun account
4. On frontend, try to invite a user on Email Invites on your profile
5. Check invited users email, all html and email tokens are stripped

**Expected behavior**
Email Invites should have a layout 

**Screenshots**
https://www.loom.com/share/816b15a82b124e77be38e979f2a4b7c0
![email-setup](https://user-images.githubusercontent.com/58522224/76788227-7a04ba00-67f5-11ea-8c40-6f63612463b9.JPG)
![email-test2](https://user-images.githubusercontent.com/58522224/76788232-7cffaa80-67f5-11ea-82b5-c460f99053e3.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1111910564/508/

**Comment by jaydeeprami** [comment]
@emmanoctaviano 

I have check this issue and not able to reproduce it. 

Please see below proof of testing:
https://www.loom.com/share/c4158ddd15b1464f80019063620f1639

Thanks

**Comment by eisenwasser** [comment]
@jaydeeprami @emmanoctaviano 

I believe this was fixed already in Platform v1.2.9
