### ISSUE TITLE
Styling issue on Internet Explorer Browser for Message section

### ISSUE THREAD

**Issue by shashank-buddyboss** [buddyboss/buddyboss-platform#644]
**Describe the bug**
- Delete icon is misaligned
- New Compose Message does not look properly on IE (https://prnt.sc/rhl2lk) compare to google chrome (https://prnt.sc/rhl30a)
- Styling not working on message content

**To Reproduce**
1. Go to 'https://prnt.sc/rhl3iz'
2. Click on 'New message / Reply on existing message'
3. See error

**Screenshots**
Delete Icon > 
New Compose Message > https://prnt.sc/rhl4yq
Styling not working on message content > https://prnt.sc/rhl68t(IE-11) please compare this with 
https://prnt.sc/rhl5ob (Chrome)

**Comment by amincdev** [comment]
Closing this issue and created a new one in theme, since this is related to the theme. 
https://github.com/buddyboss/buddyboss-theme/issues/503
