### ISSUE TITLE
Support slug change of Group, Activity and Friends Component

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#645]
**Describe the bug**
Customer is trying to change the slug of Activity, Friends and group components by adding below constant into the `bp-custom.php` file.

> define ( 'BP_FRIENDS_SLUG', 'contacts' );
define ( 'BP_GROUPS_SLUG', 'groupes' );
define ( 'BP_ACTIVITY_SLUG', 'activite' );

**To Reproduce**
1. Create `bp-custom.php` file in `wp-content/plugins` folder
2.  Add below constant in the file.
                   

> define ( 'BP_FRIENDS_SLUG', 'contacts' );
>                    define ( 'BP_GROUPS_SLUG', 'groupes' );
>                    define ( 'BP_ACTIVITY_SLUG', 'activite' );

3. Now visit the https://prnt.sc/rhp392 page and you will lose all the filters functionality, Grid/List view & You can't message to any users via the button.

**Expected behavior**
It should be functional even if you change the slug.

**Support ticket links**
https://secure.helpscout.net/conversation/1111916418/996/

**Jira issue** : [PROD-955]

[PROD-955]: https://buddyboss.atlassian.net/browse/PROD-955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by BenJackGill** [comment]
This commit has introduced a new bug.

It breaks the display of the group "cards" found under the "Groups" tab of the user profile page. The styling is gone, and also filtering options (sort by, grid view, list view).

The following screenshots where taken on a fresh install of BuddyBoss with the default Twenty Twenty theme. The same thing happens no matter what theme you are using.

1) This is how it looks with the normal slug (e.g "/members/user-name/groups/"): https://imgur.com/a/tm5Tq0f
2) This is how it looks when the slug is changed (e.g. "/members/user-name/teams/"): https://imgur.com/a/AO7K9jS

Should I create a new bug report or will this suffice?

**Comment by BenJackGill** [comment]
Upon reading this issue again, maybe I misinterpreted the original text.

It seems this issue is highlighting the same bugs I am also raising - i.e. filters and grid buttons not working.

If that's the case, it looks like these commits have not solved the bug, which is what assumed they did.

**Comment by vinaysagar4u** [comment]
I want to change slugs too. What is the update on this?
