### ISSUE TITLE
Profile pic not sync with profile photo inside messages when users log via OneAll Social Login

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#653]
**Describe the bug**
OneAll Social Login, profile pic not sync with profile photo inside messages

**To Reproduce**
1. Install and setup OneAll Social Login https://www.buddyboss.com/integrations/social-login/
2. Set up a LinkedIn app for the connection
3. try to use this as a login

**Expected behavior**
Profile images must be synchronized with profile images inside messaging inbox

**Screenshots**
https://drive.google.com/open?id=1woLVozudU9Au1jqhU4pxUDgZLaC42APD

**Support ticket links**
https://secure.helpscout.net/conversation/1111908066/275/

**Comment by janakkaneriya007** [comment]
@emmanoctaviano @chetansatasiya 

The **Social Login** plugin hook into the _bp_core_fetch_avatar_ so it's shows the social profile pic in site on some places but when we just need the profile pic url only it doesn't hook into that filter which is _bp_core_fetch_avatar_url_ so we need to ask plugin author to add the support for this.

@chetansatasiya 
Let, me know your thoughts on this and the process to contact the plugin author to add the support for this.

**Comment by janakkaneriya007** [comment]
@emmanoctaviano 

They will add the support for this and will be available in the next release.
https://wordpress.org/support/topic/buddpress-and-buddyboss-platform-plugin-support/
