### ISSUE TITLE
Change content of  Forum, Reply and Discussion when user remove from system

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#657]
**Is your feature request related to a problem? Please describe.**
When a user is deleted from the system then all the data of the forum he/she created remain as it is.

**Describe the solution you'd like**
We will update the text of each forum, discussion and reply he/she created and will change the content to `This content was deleted.`

**Support ticket links**
If applicable, add Zendesk link or ticket number where the issue was originally reported.

**Jira issue** : [PROD-954]

[PROD-954]: https://buddyboss.atlassian.net/browse/PROD-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mehulkaklotar** [comment]
https://bbpress.trac.wordpress.org/ticket/3116
https://buddypress.org/support/topic/delete-user-what-happens-with-his-data/
https://bbpress.org/forums/topic/deleting-users/
