### ISSUE TITLE
Issue - The plugin does not have a valid header. Unable to Activate Plugin

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#661]
**Describe the bug**
When activating plugin just after installing plugin zip it shows error `The plugin does not have a valid header.`

**To Reproduce**

1. Go to Plugin uploader plage
2. Upload Plugin zip files 
3. Activate the plugin just after installing the plugin.
4. See error `The plugin does not have a valid header.` 

**Expected behavior**
Should activate as other WordPress plugins.

**Screenshots**
https://www.loom.com/share/e89e1b5a495641cc8e5fbd0bd1e7b783

**Support ticket links**
NA- Issue from QA

**Comment by AiratHalitov** [comment]
@ankitguptaindia
This is not a plugin's bug. 
The real plugin located in `/src` folder ([here](https://github.com/buddyboss/buddyboss-platform/tree/dev/src)). You should download all files and manually create a `buddyboss-platfrom.zip` file with files from `/src` folder. 

@eisenwasser Could you add normal plugin's zip file into Assets on [releases](https://github.com/buddyboss/buddyboss-platform/releases) page? 
And adding a changelog will be great too. 
It should be looks like this: 
https://github.com/woocommerce/woocommerce/releases
or like this https://github.com/WordPress/gutenberg/releases/latest
File name example: `buddyboss-platform-v1.2.8.zip`

**Comment by eisenwasser** [comment]
@AiratHalitov 

Sure, I will look into that for the future, thanks.

For now, if you want to test any release version as a "normal" plugin (not running from /src) you can checkout from that tag in Git, and then run 'grunt release' command and it will generate the ZIP for you and put the ZIP into the plugin directory.

**Comment by ankitguptaindia** [comment]
@janakkaneriya007 It seems working now. I tried on new setup of WordPress.

I am closing this issue now.
