### ISSUE TITLE
Issue: Member type filter should not filter user on connection tab

### ISSUE THREAD

**Issue by dipskakadiya** [buddyboss/buddyboss-platform#662]
When we compare result of My Connections tabs on member directory and connection tab on user profile of login use it shows different user due to member type filter. 
Check Screenshots for more understanding. 

**To Reproduce**
1. Login with valid user
2. Open "My Connections" tab on member directory page
3. Open login user "connection" tab 
4 Compare result of both screen

**Expected behavior**
On "My Connections" tabs member should not be hide by member type

**Screenshots**
![image](https://user-images.githubusercontent.com/2979084/77095052-621a7980-6a33-11ea-8fff-cbf463d02acc.png)

![image](https://user-images.githubusercontent.com/2979084/77095150-8413fc00-6a33-11ea-8df9-4dac3465e855.png)

**Comment by chetansatasiya** [comment]
@dipskakadiya I checked this issue and found that you Hide the `Guest` Member Type from Members Directory tab see here for more info https://prnt.sc/rjf0r3 https://prnt.sc/rjf177

**Comment by dipskakadiya** [comment]
@chetansatasiya  Yeah i know about setting but it's showing different result for below two screen
1. Members directory page -> My connection tab
2. User profile -> My connection tab 

Both screen should show same result. that's bug

**Comment by chetansatasiya** [comment]
@dipskakadiya That setting only hides in Members Directory, not in Members Connections tab. Otherwise, there is no meaning to friend connections.

@eisenwasser Need your thoughts on this

**Comment by dipskakadiya** [comment]
@chetansatasiya yeah you right but right now it's hiding user in Connections tab on member directory
