### ISSUE TITLE
Screen options pagination options for Activity in admin

### ISSUE THREAD

**Issue by hobhobuk** [buddyboss/buddyboss-platform#666]
**Describe the bug**
Possible issue related to Buddyboss platform plugin.  When using the wordpress admin area 'screen options', using the pagination options to increase how many items are shown on page, cannot be changed from any otber number than 20.  Entering 200 would just load back up to 20.  Making it not possible to bulk manage large sets of posts.

**To Reproduce**
1. Go to Buddyboss admin menu
2. Click on Activity
3. Click on 'screen options'
4. Change pagination from 20 to any other option
5. Returns 20 again.

(Unsure how to change priority but it should be: low)

**Comment by eisenwasser** [comment]
@hobhobuk 

Thanks for letting us know about this. A fix is merged and will be in the next release.

**Comment by eisenwasser** [comment]
@hobhobuk 

This fix was included in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-2-9/
