### ISSUE TITLE
Blog post doesn't appear in activity feed in multi-site setup

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#675]
**Describe the bug**
In a multisite environment, this option is not working.
https://prnt.sc/rlo0x0
When the author publishes a blog post, it doesn't appear in the activity feed.

**To Reproduce**
1. Activate the BuddyBoss Platform on subsite
2. Enable the blog post option from settings >> activity
3. Publish a blog post.
4. See, there is no blog post in activity feed.

**Expected behavior**
The blog post should appear in the activity feed.

**Screenshots**
https://prnt.sc/rlo0x0

**Support ticket links**
https://secure.helpscout.net/conversation/1111915198/910?folderId=3701248

**Comment by janakkaneriya007** [comment]
@furqanbb 
As per the discussion with you it's working on client's site.
