### ISSUE TITLE
Per page display settings of forum are not working for forum replies. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#678]
**Describe the bug**
The setting to display the number of replies is not working. When I set the number of replies to 5, it still displayed 7 replies in the front-end. It works fine for the forums and discussions. Only the replies have an issue. 

I replicated the issue on our demo site as well on my local site using the dev branch version of the theme and plugin.

**To Reproduce**
1. Go to Dashboard >  BuddyBoss > Settings > Forums > Discussions and replies per page
2. Set the number of replies
3. Visit the forum > Discussions page in the front end

**Expected behavior**
It should display the number of replies as per the setting in the back-end. 

**Screenshots**
- https://i.imgur.com/MNfnli5.jpg
- https://i.imgur.com/eLLOGRZ.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1112295179/19505/

**Comment by janakkaneriya007** [comment]
@archanabb 

Reply per page option will not work when you have "Reply Threading" setting is enabled.

Refer the below video.
https://www.loom.com/share/35ed0caf4ccf4914903f7627dd6fcb38
