### ISSUE TITLE
Who's online widget shows hidden users. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#679]
**Describe the bug**
Created a profile type and enabled the option to hide the users from the member's directory. It hides the users on member's page but displays them on "Who's online widget". 

I am not sure if it is intended to work like that. 

**To Reproduce**
1. Go to BuddyBoss > Profiles > Profile Type
2. Create a profile type and enable "hide users from member's directory" 
3. Open a page where "Who's online" widget is added

**Expected behavior**
The hidden users should not be displayed on Who's online widget too. 

**Screenshots**
- https://i.imgur.com/fzprY3i.jpg
- https://i.imgur.com/de9vxao.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1114816861/63632/

**Comment by manishpatolia** [comment]
@archanabb @chetansatasiya I have one question about this.

After connected, also we should hide that user from connections(In widget area)???

**Comment by chetansatasiya** [comment]
@archanabb @manishpatolia 

This is not an issue and those setrtings will work only in All the main directory pages tabs like `All Members` & `All Groups`

It will not effect any other area where members OR groups listing also in any widgets.

@eisenwasser I need your thoughts and correct me if I am wrong here.

**Comment by archanabb** [comment]
@chetansatasiya thanks for your comment. We hide some users for privacy reasons. If we use this widget that hides the users ONLY on the member's page and displays the hidden users on other pages that break the privacy. And honestly, that doesn't make any sense. @eisenwasser your thoughts on this will be much appreciated.

**Comment by chetansatasiya** [comment]
As per @sourabhmatolia comment on Slack https://buddyboss.slack.com/archives/C015TD6DTPU/p1604902607004000 closing this.
