### ISSUE TITLE
When the subscriber replies a URL in the activity comment, it throws an error. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#683]
**Describe the bug**
When a subscriber comments a URL in the activity, it throws an error. It works well for the admin users. I tested this using the Dev branch versions of the theme and plugin on my local setup. 

**To Reproduce**
1. Log in as a subscriber
2. Open activity page
3. Reply to activity and add a URL in the reply

**Expected behavior**
All the users regardless of their roles should be able to send URLs in the comments(replies). 

**Screenshots**
- https://i.imgur.com/GeRKa4K.jpg 

**Support ticket links**
- https://secure.helpscout.net/conversation/1122098195/65745/

**Comment by janakkaneriya007** [comment]
@archanabb 

BuddyBoss is using the WordPress comment moderation system which doesn't allow to post links more than set number of links in the discussion settings of the WordPress.

However you can increase the number of links contain in single comment and it will allow to add the links in activity comment but make sure setting the high number of links allowed cause the spam issue.

Refer the screenshot:
https://prnt.sc/rqs9xz
