### ISSUE TITLE
Social Networks profile fields - add Twitch to the list

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#684]
**Is your feature request related to a problem? Please describe.**
Some customers want us to add "Twitch" to the list of available networks in our Social Networks profile field.

**Describe the solution you'd like**
Add Twitch as one of the options, make sure it is sorted alphabetically. When added we need to have a Twitch icon in the profile fields display on the profile.

**Support ticket links**
Requested on Youtube: https://youtu.be/qoSmwI48EbI
By user Frags.network

**Comment by AiratHalitov** [comment]
@eisenwasser 
What about vk.com? 
and telegram.org? (telegram.me and t.me)
and WhatsApp? (wa.me)

Could you add these Social Networks too? 

Google+ is closed - you may delete it.

**Comment by eisenwasser** [comment]
@AiratHalitov 

Thanks for the feedback.
VK was added into yesterday's release.

For Telegram and WhatsApp, do people have individual profile links?
I was not aware that I can share a WhatsApp profile URL for example... are you able to?

**Comment by AiratHalitov** [comment]
@eisenwasser

> VK was added into yesterday's release.

Thanks!

> For Telegram and WhatsApp, do people have individual profile links?

WhatsApp profile link looks like `https://wa.me/<number>` where the `<number>` is a full phone number in international format.
Example: https://wa.me/79674533132
Help: https://faq.whatsapp.com/en/android/26000030/
Icon: https://fontawesome.com/icons/whatsapp?style=brands

Telegram channels, groups, bots and individual profile links looks like `https://t.me/USERNAME`
Examples:
channel: https://t.me/durov or https://telegram.me/durov
chat/group: https://t.me/th_chat
individual profile: https://t.me/Airat_Halitov
Icon: https://fontawesome.com/icons/telegram?style=brands

**Comment by eisenwasser** [comment]
@AiratHalitov 

Thanks!

Issue posted https://github.com/buddyboss/buddyboss-platform/issues/765
