### ISSUE TITLE
Zoom integrations

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#685]
**Is your feature request related to a problem? Please describe.**
Members want the ability to easily create Zoom calls and record them, and reference them later on. Especially to connect them to groups to assist with courses connected to those groups.

**Describe the solution you'd like**
In BuddyBoss > Settings > Integration, we will add Zoom integration settings.
In here you enter your Zoom API Key and API Secret Key to connect Zoom.
You also have option to enable Zoom for groups.

Then on frontend, when editing a group you have options to enable Zoom in each group. If enabled you get a Zoom tab on the group. This tab has a list of previous Zoom recordings and scheduled Zoom recordings. Group organizer can create Zooms from here, enter the meeting name and agenda, schedule the start time / timezone, length of call, add a password for the call, and everyone from the group can click a link to join the Zoom call. Group members are emailed notices for upcoming zooms. After a call is done, if the site admin is using pro version of Zoom (that allows for recording the Zoom call in the cloud) we will auto-pull in the Zoom video and chat record and display it in the site. So for the Zoom tab in the group, we can imagine a list of meetings and when you click one you can watch it and read the chat transcript. Also can click a button copy the embed link to the Zoom video into your clipboard.

**Zoom APIs**
https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/recordingget
https://marketplace.zoom.us/docs/api-reference/zoom-api/im-chat/imchatmessages

**Describe alternatives you've considered**
Check out these existing WordPress plugins and see what they are doing:
https://wordpress.org/plugins/video-conferencing-with-zoom-api/
https://elearningevolve.com/products/wordpress-zoom-integration

**Support ticket links**
None yet

**Comment by ayhanmalkoc** [comment]
+1

**Comment by daaamncom** [comment]
Hello! Any idea regarding the release period? Thank you so much

**Comment by mailalaki** [comment]
Hit please add Bigbluebutton integrations too. its very useful
https://wordpress.org/plugins/bigbluebutton/
http://docs.bigbluebutton.org/dev/api.html

**Comment by eisenwasser** [comment]
@daaamncom In approx 2 weeks.

@mailalaki Thanks for the suggestions. Right now we are focusing just on Zoom.

**Comment by mr-upgr8d** [comment]
Hi @eisenwasser ,
Will this integration work with Events Calendar for scheduling virtual events?

**Comment by eisenwasser** [comment]
@mr-upgr8d 

This integration comes with a Gutenberg block for creating a Zoom event. You can place that block into any WordPress editor, so you could use it to add a Zoom into an event.

**Comment by daaamncom** [comment]
@eisenwasser 

> @daaamncom In approx 2 weeks.

Can't wait!! Any idea of when it will be released? Do you know if the document functionality will be in the same release as well?

Thank you so much

**Comment by eisenwasser** [comment]
@daaamncom 

Documents will be released this week, in the coming days.

Zoom is planned for  some time next week.

**Comment by mr-upgr8d** [comment]
Hi @eisenwasser,
Any updates when this will be released?  I see the card was closed but haven't found documents on the feature, etc.

**Comment by eisenwasser** [comment]
@mr-upgr8d We are planning to release it this coming Monday or Tuesday.

This card is closed because we moved development into a separate repo right now.

**Comment by mr-upgr8d** [comment]
I noticed in the video the Zoom link is shown to group members and am wondering if you know how we could go about protecting the link for recurring meetings?  

Example is if we're using Memberium for membership control and  someone isn't a valid member (payment fail, etc.)  we wouldn't want them having access directly via Zoom instead of only being able to access via the group/page that the Zoom event is occurring.

**Comment by eisenwasser** [comment]
@mr-upgr8d 

Just make it a private group and then all group tabs are then hidden from anyone who is not a member of the group. Then if their membership payment fails you need to remove them from the group or otherwise restrict their access using Memberium's options.

**Comment by daaamncom** [comment]
@eisenwasser Is it sill planned to be released today? Best

**Comment by eisenwasser** [comment]
@daaamncom 

This week, but not today. Wednesday or Thursday.

**Comment by JPvanRooyen** [comment]
@eisenwasser 
Excited about this release.

I have, however, reached out on buddyboss.com's pre-sales contact, but never received a reply or even confirmation that my message was received.
I don't want to hijack this thread, but need to know how I can get my questions answered before purchasing the theme.

If I should direct my questions to you in person, please let me know where I should contact.

Thank you!

**Comment by eisenwasser** [comment]
@JPvanRooyen 

I could not find the pre-sales submission, although I am not sure what email you sent it from. What are your pre-sales questions? Just post them here thanks

**Comment by eisenwasser** [comment]
Also note that Zoom feature is live now: https://www.buddyboss.com/resources/docs/integrations/zoom/

**Comment by mr-upgr8d** [comment]
Thanks @eisenwasser!  We've been playing with it over the weekend and it's quite elegant so far.  

Where's the best place to leave feedback and suggestions?

**Comment by JPvanRooyen** [comment]
> @JPvanRooyen
> 
> I could not find the pre-sales submission, although I am not sure what email you sent it from. What are your pre-sales questions? Just post them here thanks

@eisenwasser  Thank you for your reply.

These are the concerns I raised (was considering a lifetime license, but it's obviously too late now):

1) Do I need to purchase this plugin https://www.buddyboss.com/resources/docs/integrations/learndash/multiple-instructors-for-learndash/
for FRONT END course management by users, or is this type of functionality built into the BuddyBoss platform or theme?

2) On your site, /resources/docs/integrations are many plugins that seem to be redundant, because BuddyBoss Platform has those features built-in.
How can I confirm which plugins are redundant and which are still relevant to purchase from third parties, specifically relating to Learndash and the "BuddyPress Addons" section?

An example issue I'm concerned about:
The plugin "Invite Anyone" (https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/invite-anyone/) breaks some of BuddyBoss's functionality...

During the Group Creation steps on the front end, the option to check the "Create and sync a LearnDash group" is not available any longer. (It is enabled in back-end and also works correctly when Invite-Anyone is disabled)
Also, the "Invite Anyone" email invite step in the Group Creation process completely replaces the email invite step of BuddyBoss Platform.
I wanted to just add the functionality to invite new group members via email, which BuddyBoss does not currently support.

Before implementing BuddyBoss I need to be sure that all these mentioned functions will work properly.

Thanks for your time, looking forward to hear from you.

**Comment by eisenwasser** [comment]
@mr-upgr8d 
Thanks! We do not have a specific place for feedback right now. If you find any bugs please submit them to support and we will review.

@JPvanRooyen 

1. Yes, you would need to purchase that plugin if you want frontend course creations, which is not built into LearnDash.

2. Any plugins related to LearnDash are relevant. We style LearnDash nicely and add some extra integrations, like connecting courses to groups, and a profile tab showing your courses, but that is all. LearnDash add-ons are all relevant. We try not to add any plugins that are duplicating functionality, sometimes they might forget to remove one if we have added that functionality later.

>The plugin "Invite Anyone" (https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/invite-anyone/) breaks some of BuddyBoss's functionality.

Every plugin in our Integrations page has been tested with BuddyBoss Platform before being posted. So either the tester didn't notice this or it is a newer issue. In general you should assume that every single plugin in the list has gone through testing and verification prior to being listed.

**Comment by eisenwasser** [comment]
@JPvanRooyen I have created an issue for it here https://github.com/buddyboss/buddyboss-platform/issues/1172

**Comment by JPvanRooyen** [comment]
Thank you @eisenwasser - Have a good day

**Comment by marquemedia** [comment]
@eisenwasser Hey, I'm having trouble with BuddyBoss, I've set up the Zoom integration, but When I click "Meeting details" it looks like this and doesn't let me click

http://prntscr.com/twcdph

**Comment by eisenwasser** [comment]
@marquemedia 

That is not typical behavior. Can you try disabling all other plugins and trying again? Possibly there is a CSS or Javascript conflict with another plugin. If you still get this after trying that please submit a support ticket. Thanks!

**Comment by marlon-montgomery** [comment]
Hi - was the email functionality notifying group members of the zoom meeting implemented? This does not seem to be working for us. 

Thanks

**Comment by heinzkoop** [comment]
Hello,

somehow the Zoom Recording function is not working. 
We create the Meeting with a Zoom Pro account and add the option "enable join before host" for every meeting. 
But the host email is not joining the meeting, our instructors will join with their own zoom account.
Therefore we only have to pay one Zoom Pro Account for sheduling and not for every instructor. 
Maybe it is not triggered that the zoom meeting had started this way and therefore it will not show the recording?

Thanks in advance!

Best regards,
Heinz
