### ISSUE TITLE
Sent Invite Table doesn't scroll on iOS.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#689]
**Describe the bug**

Sent Invite Table doesn't scroll on mobile (iOS). Please check on real device to reproduce the issue.

**Screencast To Reproduce**
https://screencast-o-matic.com/watch/cYewi54YyE

**Expected behavior**
The table should scroll horizontally so that the user can see other details in the table.

**Comment by sagarjadhav** [comment]
Added in theme issues -
https://github.com/buddyboss/buddyboss-theme/issues/617
