### ISSUE TITLE
Forum Features - Post Formatting not working

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#694]
**Describe the bug**
In BuddyBoss > Settings > Forums > Forum Features, we have an option to enable Post Formatting.
This however, doesn't work on the frontend

**To Reproduce**
1. Go to BuddyBoss > Settings > Forums > Forum Features and enable Post Formatting
2. Go to Forum Discussion on frontend, no Toolbar and button on textareas

**Expected behavior**
When Post Formatting is enabled, toolbars should be available on textarea

**Screenshots**
![pf1](https://user-images.githubusercontent.com/58522224/78141436-12d63f00-745e-11ea-9a5b-87317828ed6d.JPG)
![pf2](https://user-images.githubusercontent.com/58522224/78141449-15d12f80-745e-11ea-8b46-0c556f16d0a3.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1122635843/65865?folderId=3701258

**Comment by chetansatasiya** [comment]
@emmanoctaviano I am closing this issue becase it's not an issue see how this functionality will work in this video https://www.loom.com/share/0c8db463856640f29fe04c4a7e2f6f40
