### ISSUE TITLE
The pagination on Forums > My discussions on the profile page is giving 404 error. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#696]
**Describe the bug**
The pagination on Forums > My discussions on the profile page is giving 404 error. It doesn't work for admin, subscribers or even when we use the "View As" feature. I tried resaving the permalinks but didn' help.

**To Reproduce**
1. Go to 'profile > forums' page
2. Click on 'my discussions'
3. Scroll down to 'pagination' and click on the next page

**Expected behavior**
Pagination should work fine. 

**Screenshots**
- https://cl.ly/d8f84ef1904b

**Support ticket links**
- https://secure.helpscout.net/conversation/1125937624/66586/

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1149411844/70983
