### ISSUE TITLE
WPML is conflicting with the platform

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#699]
**Describe the bug**
When clicking on the "Photos" tab in profile, it redirects to the "All Photos" page, not the member's photos. The problem occurs when you visit another member's page.

**To Reproduce please watch the video**
https://screencast-o-matic.com/watch/cYfnil4gxP

**Expected behavior**
It should redirect to the user's photos page.

**Support ticket links**
https://secure.helpscout.net/conversation/1124273233/66196?folderId=3701248

**Comment by janakkaneriya007** [comment]
@furqanbb as per the discussion with you I have shared the workaround for the time being and I have reported plugin author to add the support for the same. I hope they will add the support for this soon.

**Comment by KartikSuthar** [comment]
Duplicate issue: https://github.com/buddyboss/buddyboss-platform/issues/531
