### ISSUE TITLE
Forum and activate page doesn't work if it's under parent page.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#700]
**Describe the bug**
Forum and activate page doesn't work if it's under the parent page.

**To Reproduce**
1. Create a forum page and set a parent page for it.
2. go to buddyboss >> pages and assign the forum page here
3. View the page on the forum page.

**Expected behavior**
It should work even if the buddyboss components pages(forum, activate) are subpages.

**Screenshots**
https://prnt.sc/rnom3a
https://prnt.sc/rnombc
https://prnt.sc/rnomq4

**Support ticket links**
https://secure.helpscout.net/conversation/1118931299/64680
https://secure.helpscout.net/conversation/1239674191/85675

**Comment by ankitguptaindia** [comment]
@mohit-buddyboss Please test this issue/related PR for this next release..
