### ISSUE TITLE
Disallow Nickname visibility to be changed on frontend instead of First Name

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#702]
**Describe the bug**
Nicknames can't be disabled on backend yet it can be set its visibility in frontend.
First Name can be disabled on backend but we can't change the visibility in frontend.

**To Reproduce**
1. Go to BuddyBoss > Settings > Profile
2. Allow Nickname, First Name and Last Name
3. Go to BuddyBoss > Profile Fields and set the visibility of First Name to public and allow members to override
4. In frontend, go to Profile > Edit. In this scenario, there is no option for First Name field to be hidden, but for Nickname there is an option. 

**Expected behavior**
This should be the other way around, Nicknames should not have the option to change the visibility in the frontend since it cannot be disabled on the backend and it is used for mentioning. First Names should have an editable visibility option

**Screenshots**
![backend](https://user-images.githubusercontent.com/58522224/78510295-c032b500-77c6-11ea-913d-1c035271263f.jpg)
![front](https://user-images.githubusercontent.com/58522224/78510296-c45ed280-77c6-11ea-8ac3-24747f1485fa.jpg)

**Support ticket links**
https://secure.helpscout.net/conversation/1122055167/65736?folderId=3701258

**Comment by proskurius** [comment]
I have the same problem

**Comment by proskurius** [comment]
One problem else.
In this case (when Display Name Format = Nickname), I can't change requirement (required/optional) for First Name and Last Name.

**Comment by eisenwasser** [comment]
@proskurius 
Noted thanks

**Comment by imehedidev** [comment]
https://secure.helpscout.net/conversation/1271517547/91307

**Comment by dipskakadiya** [comment]
@mehulkaklotar https://github.com/buddyboss/buddyboss-theme/pull/986 BuddyBoss theme changes

**Comment by sourabhmatolia** [comment]
@proskurius

Issue created above is released in Buddyboss Platform v1.5.1.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-1/

Please update the plugin to see the latest changes.

Thank you.
