### ISSUE TITLE
When we create a new forum from the backend, it opens a profile type page and displays profile settings menu. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#708]
**Describe the bug**
When we create a new forum from the backend, it opens a profile type and displays a profile settings menu. 

**To Reproduce**
1. Go to Dashboard > BuddyBoss > Forums > New Forum
2. See error

**Expected behavior**
It should open a new forum page. 

**Screenshots**
- https://cl.ly/4ee3f3281dbd (

**Comment by janakkaneriya007** [comment]
@archanabb 
This issue will be fixed in next release.

**Comment by chetansatasiya** [comment]
@archanabb Closing this because already fixed in 1.2.9.1
