### ISSUE TITLE
Creating a new forum from the backend redirects to the profile type page after the creation of the forum. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#709]
**Describe the bug**
Creating a new forum from the backend redirects to the profile type page after the creation of the forum. However, the forum is created successfully and when we click on "View Forum" and view this in the front end, it works fine. 

But the slug on the frontend for that forum is incorrect. It still displays the profile type name in the URL and not the forum's name. 

**To Reproduce**
1. Go to Dashboard > BuddyBoss > Forums
2. Click on New Forum, edit a title and save the forum
3. See error

**Expected behavior**
- It should redirect to the forum's page

**Screenshots**
- https://cl.ly/fafaeafd50ed

**Comment by janakkaneriya007** [comment]
@archanabb 
Duplicated issue: https://github.com/buddyboss/buddyboss-platform/issues/708

**Comment by chetansatasiya** [comment]
@archanabb Closing this because already fixed in 1.2.9.1
