### ISSUE TITLE
Editing forums from the backend redirects to the profile type page. Can not edit the forums from the backend. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#710]
**Describe the bug**
Editing forums from the backend redirects to the profile type page. I cannot edit the forums from the backend. 

I created a fresh website where I didn't have any data (No posts, pages or forums). It worked fine on it. But I am experiencing the issues with the existing site that has some forum data and other data. 

**To Reproduce**
1. Go to Dashboard > BuddyBoss > Forums
2. Click on Forum to edit 
3. See error: it will redirect to profile type page

**Expected behavior**
The forums must be editable from the backend. 

**Screenshots**
- https://cl.ly/a0ff2ca72aea

**Comment by mehulkaklotar** [comment]
@archanabb this https://github.com/buddyboss/buddyboss-platform/commit/a9f8369decf490656898337815cc6053f8c97d85 commit will fix this issue.

**Comment by chetansatasiya** [comment]
@archanabb closing this issue because we fixed it in https://www.buddyboss.com/resources/buddyboss-platform-releases/1-2-9-1/ release
