### ISSUE TITLE
Permalink of a group type does not show the list of groups

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#715]
**Describe the bug**
When accessing directly the permalink of a group type, it does not show the list of groups that belong to this type

**To Reproduce**
1. Create a group type
2. Click the permalink
3. Notice that it will only show a blank page.

**Expected behavior**
Group type permalink should show the list of the groups of this type

**Screenshots**
![group type](https://user-images.githubusercontent.com/58522498/78705489-2262f580-7940-11ea-90bb-58a3b9f41800.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1111927384/1861?folderId=3701263

**Comment by chetansatasiya** [comment]
@ayron-paul We don't have a  this kind of functionality. To view the list of group type of particular you can use the shortcode and place it in page and it will display all the groups of that type. see this https://prnt.sc/rv51ht
