### ISSUE TITLE
Non-admins could not post multiple links on Activity feed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#716]
**Describe the bug**
Non-admin accounts could not post multiple links on Activity feed. Issue can be replicated on demo.

**To Reproduce**
1. Login as Subscriber
2. Go to Activity page
3. Post multiple links on feed

**Expected behavior**
Users must be allowed to share multiple links. They must have an option like when link previews are disabled, they are allowed to post multiple links

**Screenshots**
https://drive.google.com/open?id=1Dpmoh5kNzpf_9xSyE7Q_QFvcWxVVYM1v.

**Support ticket links**
https://secure.helpscout.net/conversation/1126439068/66693?folderId=3701258

**Comment by janakkaneriya007** [comment]
@emmanoctaviano 

I have explain this issue here: https://github.com/buddyboss/buddyboss-platform/issues/683
