### ISSUE TITLE
"User joined message" flooding the group message thread sending too many notifications to users.

### ISSUE THREAD

**Issue by mehulthakkarexcel** [buddyboss/buddyboss-platform#717]
**Describe the bug**
In a combination of Learndash + Woocommerce + Buddyboss Platform. Suppose an admin has sent a Group message using "Group Thread" not Private BCC. Now every time a new user joins the course, he is also added to the group automatically, as a course as been attached to group. This new user who is auto added to the group also ends up being shown in the Group message thread. Now if in a day 100 new users sign up in the course, that sends 100 notifications each to all the existing 200+ users of that course. This needs to be made either an option or stopped totally.

**To Reproduce**
1. Create a group message, send To All Group members, use Group Thread, not Private Reply (BCC)
2. Then make a new user do the registration for the course to which this group is attached
3. When new user registers and buys that course he is auto added to the group you will see a notification and a message on your profile.
4. Notification says new user has sent me a private message.
5. In reality, New user joined group, message is shown in the group thread, triggering notification to all existing members

**Expected behavior**
Either the message should not be shown or we need to have a setting to disable this notification behavior

**Screenshots**
https://www.loom.com/share/b54b86d0276a4aa3bf2e1d3f5686a7aa

**Support ticket links**
https://www.buddyboss.com/my-account/?conversation_id=1130480525

**Comment by chetansatasiya** [comment]
We have fixed this issue on `1-3-0` release now notification is not sending anymore.
