### ISSUE TITLE
Losing chat of other users if a group message is sent with Private Reply BCC

### ISSUE THREAD

**Issue by mehulthakkarexcel** [buddyboss/buddyboss-platform#718]
**Describe the bug**
When a group admin sends out a group message using Private Reply BCC option then assuming 200 users exist in the group, 200 threads are opening up in the inbox. This takes away all the existing chats off the scroll-able chat list. If I forget the name of the person I was chatting to, before sending out group message then there is no way to locate the person until they reply and the thread comes up on the list again

**To Reproduce**
1. Start a 1 to 1 chat with normal user
2. Send a group message with private reply BCC
3. Scroll down to locate the chat of that normal user, assuming we forgot the name of that person, there is no way to locate that chat

**Expected behavior**
Expecting that all Private Reply BCCs should remain hidden until the recipient  responds. OR
Group them all together like "Group Name (BCC)" just like Group Thread option. However, if a user replies, it will break into a separate 1 to 1 convo with user.

**Bug video**
https://www.loom.com/share/726e1ae7db4c43949200afb88e8166c5

**Comment by eisenwasser** [comment]
@mehulthakkarexcel  

Thanks for your feedback. We are implementing a solution to make this less cluttered.

"Expecting that all Private Reply BCCs should remain hidden until the recipient responds."

It will be similar to this, but with some other improvements to make things more clear.

**Comment by eisenwasser** [comment]
@mehulthakkarexcel 
We have made these changes in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-0/
https://www.buddyboss.com/resources/buddyboss-theme-releases/1-4-2/

Messages now have an option to "Hide Conversation". If you search for the message and click it that will unhide it. If the recipient replies that will also unhide it.

And when sending a group message to multiple people privately, we automatically make the sent messages hidden now, until the recipient replies (unless you already have an open conversation with the recipient).

We also added new options to "Mark unread" and to "Delete Conversation" (for admins only) in this release. You will see Delete Conversation when you View As another member, so you can delete their conversations. But if you actually log in as the user for real, they don't see that option.

**Comment by mehulthakkarexcel** [comment]
@eisenwasser 
This is great, just tested it, I could delete that conversation finally. Cheers.
Meanwhile, opening another bug/issue in group messages. I merely have 500 users on my community, but I do love buddyboss and will try reporting as much as I can so that this tool can become awesome.
Thank you

**Comment by eisenwasser** [comment]
@mehulthakkarexcel 

Thanks! We appreciate the feedback, it helps us improve the product.
