### ISSUE TITLE
First name and Last name still display on registration page when disabled.

### ISSUE THREAD

**Issue by SeanBannister** [buddyboss/buddyboss-platform#724]
If you disable First Name and Last Name in BuddyBoss they're still displayed on Wordpress's registration page. After some research I've realised this is Wordpress's default behaviour but as a new user this didn't make sense, I presumed disabling them would remove them throughout the site. If BuddyBoss could remove them from the registration page when they were disabled it would help with usability.

**To Reproduce**
1. Go to /wp-admin/admin.php?page=bp-settings&tab=bp-xprofile 
2. Set "Display Name Format" to "Nickname"
3. In "Display Name Fields" disable "First Name" and "Last Name"
4. Click "Save Setting".
5. Go to /register/

**Expected behavior**
First name and Last name wouldn't be displayed on the wordpress registration page.

**Screenshots**
![image](https://user-images.githubusercontent.com/197231/78931724-b58b5f00-7ae9-11ea-8c62-e3991ac323de.png)
![image](https://user-images.githubusercontent.com/197231/78931852-e8cdee00-7ae9-11ea-939a-e62dd4bcc8a9.png)

**Comment by manishpatolia** [comment]
@SeanBannister I have tested with the latest dev pull and it seems working fine for me.
Please see my proof:
https://www.loom.com/share/51bebf5ed2544ee59911631f17f1dfbf
