### ISSUE TITLE
Photo comment section is not showing when viewing from single activity page

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#731]
**Describe the bug**
The comment section for photos of an activity is not showing when viewing from single activity page

**To Reproduce**
1. Post an activity with some images
2. View the activity from single page by clicking the timestamp
3. Clicking the images seems to not work, it does not show the lightbox where comment section should appear.

**Expected behavior**
Comment section should appear even in single activity page.

**Screencast**
https://drive.google.com/file/d/1jB9wcBw_Pv8G5NeTlult-aBDuLjdU1MM/view

**Screenshots**
![lightbox](https://user-images.githubusercontent.com/58522498/79050932-db3a7480-7c5f-11ea-9743-b16b18e286f0.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1131166374/67562?folderId=3701263

**Comment by manishpatolia** [comment]
@ayron-paul This issue related to #348, PR already sent for review.
