### ISSUE TITLE
Profile Type filter in members directory is not working when there is a hidden profile type

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#732]
**Describe the bug**
When there is a hidden profile type, the profile type filter in the members directory is not working

**To Reproduce**
1. Create another profile type
2. Under, permission, enable "Hide all members of this type from Members Directory"
3. Go to members directory and try to use the profile type filter

**Expected behavior**
Profile type filter should work even there are hidden members

**Screenshots**
![prfiletypefilter](https://user-images.githubusercontent.com/58522498/79057218-74ce4a00-7c91-11ea-8b81-c6f174f23166.png)

![profiletypefilter](https://user-images.githubusercontent.com/58522498/79057220-7ac42b00-7c91-11ea-81f6-eb85f93daa20.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1133704583/68080/
https://secure.helpscout.net/conversation/1139712819/69314

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1132045440/67711

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1115872873/64004/
