### ISSUE TITLE
URL preview for posts and pages (specially homepage) is inconsistent. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#733]
**Describe the bug**
When we share the URL on the activity page, the preview of that link is displayed inconsistently. Meaning, sometimes it displays the correct preview but sometimes the image is not displayed in the preview. 

**To Reproduce**
1. Go to the Activity page
2. Share a URL of a blog post or homepage 
3. do not enter space or write anything after entering the URL, let the preview load 

**Expected behavior**
The preview must be displayed the same every time we share the URL. 

**Screenshots**
- https://i.imgur.com/GQ3P8dM.jpg and https://i.imgur.com/X6D0vqJ.jpg (for the same URL)
- https://i.imgur.com/tK3XIf4.jpg (for https://www.buddyboss.com/)

**Support ticket links**
- https://secure.helpscout.net/conversation/1131432299/67593/
- https://secure.helpscout.net/conversation/1130216571/67322/
- https://secure.helpscout.net/conversation/1134655135/68272/
- https://secure.helpscout.net/conversation/1140435190/69438?folderId=3709080

---

Notes from @eisenwasser to clarify this task:

**Actual Issues**
* [ ] Fix WordPress thumbnail issue in embeds (WordPress 5.4 bug)
* [ ] In our fallback preview, update layout to match WP default embeds (WP 5.4 changed the layout)
* [x] In our fallback preview, fix us fetching incorrect default image and not always fetching the description
* [x] Some links produce weird characters in the link preview

Video explanation:
https://www.loom.com/share/5da8318f12e5488baf248a5ed87b2281

**Test Links for content previews**
- https://cpp-luxury.com/cruise-shows-being-held-all-over-the-world-are-a-huge-but-meaningless-waste-of-money-says-giorgio-armani/
- https://joblux.com/curated-luxury-news/giorgio-armani-cruise-shows-being-held-are-a-huge-but-meaningless-waste-of-money/

**Test Links for weird character output**
- https://versusshoubiao.world.tmall.com/shop/view_shop.htm?spm=a1z10.3-b-s.1997427721.d4918089.14c3350dM8lsaA

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1134655135/68272/

**Comment by joblux** [comment]
Its even more dislocated when you share a link & skip a line & add text into a group activity ...the share block needs re-thinking.  Issue is that the human facvtor has not been considered here, and no one shares links the same way.

**Comment by eisenwasser** [comment]
@joblux 

Can you post the URL of the link(s) you were testing?

**Comment by joblux** [comment]
![case1](https://user-images.githubusercontent.com/20825408/79782159-a3d96100-830c-11ea-8a45-cbb2ab998123.JPG)
![case2](https://user-images.githubusercontent.com/20825408/79782169-a5a32480-830c-11ea-832b-c2dbf76895ef.JPG)
![case3](https://user-images.githubusercontent.com/20825408/79782175-a89e1500-830c-11ea-8155-6d6b8510c7cb.JPG)
![case4](https://user-images.githubusercontent.com/20825408/79782178-ab990580-830c-11ea-9d06-2aa9ecee2383.JPG)
![case5](https://user-images.githubusercontent.com/20825408/79782191-af2c8c80-830c-11ea-9bcf-e19ef630314c.JPG)

**Comment by joblux** [comment]
The one before last is how one would expect it to look, more or less. The others are the same link shared differently on the BB demo site. The last one is our site and when our users shared the link a group wall .... i assumed it was the line skipping that moved the lay out, may be not when i read the previous thred content. 

![sharejobx](https://user-images.githubusercontent.com/20825408/79782331-e56a0c00-830c-11ea-9a04-011a026087ae.JPG)

**Comment by eisenwasser** [comment]
@joblux 

This video should help explain a lot of what is going on:
https://www.loom.com/share/5da8318f12e5488baf248a5ed87b2281

**Comment by eisenwasser** [comment]
@joblux 

Every time you share feedback here, can you also paste the exact links you are testing with. That will help us tremendously.

**Comment by joblux** [comment]
Which i did in anticipation to your video as we always do because we are here to HELP. by sharing link and all pics ... there is  still a gap between what i am poiting out is wrong and what Wordpress is responsible for. In fact we have tickets in the support dating from November last year, so this is not new to us.  Here is the link if it may help but the main focus is the share activity section as a whole. https://versusshoubiao.world.tmall.com/shop/view_shop.htm?spm=a1z10.3-b-s.1997427721.d4918089.14c3350dM8lsaA

**Comment by eisenwasser** [comment]
Thanks for adding the link. I am sure you have added links in support tickets in the past. I just meant here in Github if you paste screenshots please also add the link that is producing the image in the screenshot. I appreciate the help!

**Comment by eisenwasser** [comment]
@joblux 
If you scroll to the top of this Github issue you will see I updated the issue more with all the details. We will prioritize this and resolve these issues.

**Comment by joblux** [comment]
Thats your call. We provided a global feedback.

**Comment by eisenwasser** [comment]
@joblux 

The issue with Chinese characters showing crazy is fixed and will be in the next release, which will be live in the next few days.

See screenshot from my local testing.
<img width="1256" alt="screenshot" src="https://user-images.githubusercontent.com/53221322/80293444-48e0a900-8714-11ea-8ecb-75d3250f4472.png">

**Comment by eisenwasser** [comment]
@sagarjadhav 

Can you make a new PR to fix this issue:
_In our fallback preview, update layout to match WP default embeds (WP 5.4 changed the layout)_

I explain the visual issues in this video explanation:
https://www.loom.com/share/5da8318f12e5488baf248a5ed87b2281

**Comment by joblux** [comment]
Do we still have to space when pasting a link or will it load automatically ?

**Comment by eisenwasser** [comment]
@joblux It should load automatically

**Comment by eisenwasser** [comment]
Update is available now:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-2/
https://www.buddyboss.com/resources/buddyboss-theme-releases/1-4-4/

**Comment by joblux** [comment]
is it mandatory to ad **www** or http before the link most people enter buddyboss.com when they share a link ...

**Comment by AmineBAIK1** [comment]
Hello, 
In files changed there is :
bp-activity/vendors/website-parser/website_parser.php
But /vendors/ is no more available in downloadable folder and also CSS and JS in bp-activity folder ! Why?

**Comment by joblux** [comment]
Third round:

Same link share : still same issue with the outcome with bb ...

Besides no **[non-it user](url)** wil understand formatting for the Aa  ... 

The link sharing in the formatting menu is not reading it neither...




![Buddyboss123](https://user-images.githubusercontent.com/20825408/80399401-202cf080-8887-11ea-8898-bc2ae2001f0e.JPG)
![buddyboss12345](https://user-images.githubusercontent.com/20825408/80399407-228f4a80-8887-11ea-9374-7dfdae78f340.JPG)
![buddyboss12345678](https://user-images.githubusercontent.com/20825408/80399413-24590e00-8887-11ea-8818-b16c0bf0476e.JPG)

**Comment by eisenwasser** [comment]
@joblux 

This is not a support thread. Please keep it focused on the URL previews. I will answer your other questions but in the future please don't post random support questions in here. This is Github, it is for discussing development on specific issues, to help our developers resolve issues.

> In files changed there is :
> bp-activity/vendors/website-parser/website_parser.php
> But /vendors/ is no more available in downloadable folder and also CSS and JS in bp-activity folder ! Why?

It was removed. Files changed includes files added, removed, and modified.

> Besides no non-it user wil understand formatting for the Aa ...

I strongly disagree.
This is the method used in Gmail - https://prnt.sc/s6zupv
It is also used in Slack - https://prnt.sc/s6zv3n

This is the industry standard in modern applications. Everyone I know has a Gmail account and they figure this out just fine. There is not enough room to fit all of the formatting options plus all the other options in all views.

**Comment by eisenwasser** [comment]
For the URL previews, if I post this in my news feed:
https://joblux.com/curated-luxury-news/giorgio-armani-cruise-shows-being-held-are-a-huge-but-meaningless-waste-of-money/

I get this:
https://prnt.sc/s6zy8i

If I post this:
https://joblux.com/

I get this:
https://prnt.sc/s6zz4h

Did you update? I am getting the exact same result as Facebook. Same title, same image, same text.

**Comment by joblux** [comment]
This is exactly what i am doign helping out here. And in line with the original ticket. what is exactly off script here ?

**Comment by eisenwasser** [comment]
Just the stuff about the "Aa" is off-ticket. Don't worry about it, not a big problem. We appreciate your feedback.

**Comment by AmineBAIK1** [comment]
Just saw the reply to my post: just saying it would useful for developpers to have an indication of status of files in the changelogs. Thanks

**Comment by mehulkaklotar** [comment]
> Just saw the reply to my post: just saying it would useful for developpers to have an indication of status of files in the changelogs. Thanks

@AmineBAIK1 you can find the changelog here https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-3/

**Comment by AmineBAIK1** [comment]
@AmineBAIK1 I already know where to find changelog. Thanks
I'm speaking about changlog accompagned with file status. ex: 
~/class-bp-token-email.php [Deleted] or [Added] or Updated

**Comment by AmineBAIK1** [comment]
@mehulkaklotar   I already know where to find changelog. Thanks
I'm speaking about changlog accompagned with file status. ex:
~/class-bp-token-email.php [Deleted] or [Added] or Updated

**Comment by eisenwasser** [comment]
@AmineBAIK1 

I understand what you are asking for. We'll see if this is possible to incorporate into our process in the future. Right now we run a command that shows all modified files. We'll need to update that to also specify added/deleted files.

**Comment by joblux** [comment]
@eisenwasser  Well regarding the examples used for the formatting not sure we have the same dynamics for social networks but that your call.

Regarding the link preview, i still have proportions issues such as, image too small, title is over dimensioned ...

![linksz](https://user-images.githubusercontent.com/20825408/81084521-f8134200-8ec3-11ea-9d48-0ccf2eaafac6.JPG)

**Comment by archanabb** [comment]
https://secure.helpscout.net/conversation/1130216571/67322
The user is experiencing the issue for blog posts and pages even after the recent update.

**Comment by eisenwasser** [comment]
@mehulkaklotar See above. Some website still cannot generate a preview but work on Facebook.

**Comment by eisenwasser** [comment]
@joblux 

The visual style of link previews was not changed at all in the last update. That is being worked on in a separate pull request:
https://github.com/buddyboss/buddyboss-theme/pull/593

**Comment by joblux** [comment]
i can pinpoint why same link is showing different preview ... one is on BBdemo one is n my website ...the bb is more cose to how it should look, but mine is way off road..


![samelink](https://user-images.githubusercontent.com/20825408/81716545-7ed99900-9447-11ea-8e00-073eaef669bd.JPG)

![samelink2](https://user-images.githubusercontent.com/20825408/81716560-81d48980-9447-11ea-94e9-d3bb73640a60.JPG)

**Comment by eisenwasser** [comment]
@joblux It looks like the one on your website failed to fetch the preview totally. Not sure why. We are continuing to improve these link embeds we have not forgotten about it.

**Comment by eisenwasser** [comment]
@joblux 

Please try after today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-5/

You should see more consistent results from link previews now.
