### ISSUE TITLE
BuddyPress Edit Activity compatibility with BuddyBoss theme/Platform

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#737]
**Describe the bug**

Edit Activity option not working for member activity.
User can not edit content of the post and Style of button also not matching with theme.
This is our Free plugin and should work as expected on our new theme
https://wordpress.org/plugins/buddypress-edit-activity/

**To Reproduce**
1. Go to Site wide activity or Group activity 
2. Click on edit button

**Expected behavior**
User should able to edit activity.

**Screenshots**
https://prnt.sc/ry8zwt  
https://www.loom.com/share/14f2b7748de4487ca0c3dd4a19197b83

**Support ticket links**
https://app.clickup.com/t/2njb3f

**Comment by ankitguptaindia** [comment]
@janakkaneriya007 Could you please share Commit URL or branch where you pushed these fixes.

@amincdev Please do the needful changes for this fix. I have to release new build for this plugin. 
let me know if you need any info related to this.

**Comment by amincdev** [comment]
@ankitguptaindia PR is added now. Also below theme PR is connected with this issue.
https://github.com/buddyboss/buddyboss-theme/pull/579

**Comment by janakkaneriya007** [comment]
@sourabhmatolia @firozwp @mikejyoung 
We have merged the option to edit activity in BuddyBoss Platform plugin settings itself.
Should we close this issue now?
