### ISSUE TITLE
Platform plugin compatibility issues with BuddyPress Member Types Pro plugin. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#743]
**Describe the bug**
Issue 1: Duplicate profile types on the registration page
Issue 2: Duplicate profile types on Dashboard > Users > search filters dropdown
Issue 3: Duplicate profile fields meta boxes on the profile type field (profiles > profile fields)

**To Reproduce**
1. Go to the Registration page
2. Go to Dashboard > All users page and check the dropdown filters of search
3. Go to Dashboard > BuddyBoss > Profiles > Profile Fields page > 

**Expected behavior**
It should work as mentioned in our tutorials. 

**Screenshots**
- https://cl.ly/b15c637bfb13
- https://cl.ly/e1f093f4ddeb on registration page
- https://i.imgur.com/Gi53GM7.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1131305293/67581/
- https://secure.helpscout.net/conversation/1134402348/68219/

**Comment by janakkaneriya007** [comment]
@archanabb 
I have checked on my end and it's working fine.
Can you share the issue reproducing video?

**Comment by archanabb** [comment]
@janakkaneriya007 it worked fine for me too. @preeti2909 could replicate them on http://community-demo2.bb-dev.demo.appboss.com/ testing site. You can replicate them on the user's site tho.

**Comment by janakkaneriya007** [comment]
@archanabb @preeti2909 

We already have added support for Profile Types in BuddyBoss Platform as a core feature so if you want to add the profile type then you need to use the BuddyBoss Platform profile type.

Also, we haven't added support for "BuddyPress Member Types Pro" third party plugin.
