### ISSUE TITLE
Social Networks profile fields - add VK.com to the list

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#749]
**Is your feature request related to a problem? Please describe.**
Could you add "VK" to the list of available networks in Social Networks profile field?

**Describe the solution you'd like**
Add VK.com as one of the options, make sure it is sorted alphabetically. When added we need to have a VK.com icon in the profile fields display on the profile.

**Icons:**
https://fontawesome.com/icons/vk?style=brands
https://vk.com/brand (English language switcher in the footer) 

Wiki: https://en.wikipedia.org/wiki/VK_(service)

Related: #684

**Comment by eisenwasser** [comment]
@AiratHalitov Sure we can do this easily.

@annrra Can you handle this one?

**Comment by annrra** [comment]
@eisenwasser @AiratHalitov VK added to social networks list via #750

**Comment by eisenwasser** [comment]
@AiratHalitov VK  is added in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-0/

**Comment by justinpatrickkeller** [comment]
@eisenwasser any chance the team can provide this capability as an add-on plugin or something. It's a real pain to have to go through custom dev work for simple stuff like adding a social network to the options. I asked support for the code, and they told me they can't provide, which was a bit surprising based on how simple the request seems from this closed issue. 
Anyhow, I'm trying to add Strava to my options. Thanks.
