### ISSUE TITLE
WP post urls show blurry featured image when post in activity feed with Gamipress activated.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#751]
**Describe the bug**
WP post urls show blurry featured image in preview when posted in activity feed with Gamipress activated. On deactivating gamipress , issue gets resolved. 

**To Reproduce**
1. Add a new post and a featured image. 
2. Copy url and paste in Activity feed. 
3. Blurry featured image in Preview. 

**Expected behavior**
Crisp image expected. 

**Screenshots**
https://www.loom.com/share/aea5db2473a94c9791d85f8d5b47c9b1

**Support ticket links**
https://secure.helpscout.net/conversation/1117889203/64414?folderId=3701249

**Comment by mehulkaklotar** [comment]
@Anve-sri We can't fix this in Platform. Gamipress needs to fix it. 

WordPress's embed code runs and checks for available image sizes for feature image. In that Gamipress's Points Image size conflicts with the code and WP selects that image size to show in embeds.

Customers can use this filter of WP to use intended image size.
`$image_size = apply_filters( 'embed_thumbnail_image_size', $image_size, $thumbnail_id );`
```
function bb_embed_thumbnail_image_size($image_size, $thumbnail_id) {
	$meta = wp_get_attachment_metadata( $thumbnail_id );
	if ( ! empty( $meta['sizes'] ) ) {
		foreach ( $meta['sizes'] as $size => $data ) {
			if ( $data['height'] > 100 && $data['width'] > 100 && $data['width'] / $data['height'] > 1 ) {
				$image_size   = $size;
			}
		}
	}
	return $image_size;
}
add_filter( 'embed_thumbnail_image_size', 'bb_embed_thumbnail_image_size', 10, 2 );
```
