### ISSUE TITLE
Add BP Auto Group Join plugin into core of buddyboss-platform

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#754]
**Is your feature request related to a problem? Please describe.**
Could you add integration with your old plugin [BP Auto Group Join](https://wordpress.org/plugins/bp-auto-group-join/)?

**Describe the solution you'd like**
I think this function should be integrated into core of the buddyboss-platform and work without any additional plugins.

**Comment by chetansatasiya** [comment]
Hey @AiratHalitov 

This is already a part of a platform and you can achieve via Group Type & Member Type settings.

https://www.youtube.com/watch?v=0JIyhZ_PMY0
https://www.youtube.com/watch?v=ufSoFyxiLUw

**Comment by AiratHalitov** [comment]
@chetansatasiya ok, thanks!
