### ISSUE TITLE
Group Messages > required user to be connected message when sending message

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#758]
**Describe the bug**
When `Require users to be connected before they can message each other` is true then group message can't send. And shows the message `You need to be connected with all recipients to continue this conversation.`.

**To Reproduce**
1. Go to WP Admin > BuddyBoss > Settings > Connection
2. Enable `Require users to be connected before they can message each other`
3. Go to Group > Send Messages in the front end.
4. Send group message and see the error if any member of the group is not connection.

**Expected behavior**
It should allow to send group message without checking connection.

**Screenshots**
https://prnt.sc/s0y8h0

**Comment by sourabhmatolia** [comment]
@buddy4kp 

I ran couple of tests and couldn't get this working for me. 
Check the video showing BUG here:
https://www.loom.com/share/d866b2dcf16e4e3eb445d56bc983451d

Please have a look. Thanks.
