### ISSUE TITLE
Social Networks profile fields - add telegram.org and WhatsApp

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#765]
**Is your feature request related to a problem? Please describe.**
Add "WhatsApp" and "Telegram" to the list of available networks in Social Networks profile field.

**Describe the solution you'd like**
Add WhatsApp and Telegram as new options, make sure it is sorted alphabetically. When added we need to have WhatsApp and Telegram icons in the profile fields display on the profile.

**Additional Details**
WhatsApp profile link looks like https://wa.me/<number> where the <number> is a full phone number in international format.
Example: https://wa.me/79674533132
Also you can use group invite link
Help: https://faq.whatsapp.com/en/android/26000030/
Icon: https://fontawesome.com/icons/whatsapp?style=brands

Telegram channels, groups, bots and individual profile links looks like https://t.me/USERNAME
Examples:
channel: https://t.me/durov or https://telegram.me/durov
chat/group: https://t.me/th_chat
individual profile: https://t.me/Airat_Halitov
Icon: https://fontawesome.com/icons/telegram?style=brands

**Support ticket links**
@AiratHalitov mentioned in:
https://github.com/buddyboss/buddyboss-platform/issues/684#event-3190552887

**Comment by annrra** [comment]
WhatsApp and Telegram fields added - http://i.imgur.com/GzMReNX.png

**Comment by eisenwasser** [comment]
@AiratHalitov 

This is resolved in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-2/

WhatsApp and Telegram fields added - http://i.imgur.com/GzMReNX.png

**Comment by AiratHalitov** [comment]
@eisenwasser 
Thanks!

**Comment by AiratHalitov** [comment]
@eisenwasser 
Could you add "Telegram" (`https://t.me/USERNAME`) field into buddyboss-theme social links in footer?
