### ISSUE TITLE
Nickname Profile field visibility is not working. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#771]
**Describe the bug**
I set the nickname field visibility to "Only Me", logged out of the site and checked the profile, the nickname field was visible. 

**To Reproduce**
1. Go to Dashboard > BuddyBoss > Profiles > Edit Nickname field
2. Set visibility to "Only Me" 
3. Check some other user's profile or log out of the site and check a profile

**Expected behavior**
The nickname field should be visible only to the user who belongs to that profile and not to any other user. 

**Screenshots**
- https://cl.ly/422c8e1c5fe1
- https://cl.ly/968316edfc45

**Support ticket links**
- https://secure.helpscout.net/conversation/1140957913/69529/

**Comment by manishpatolia** [comment]
@archanabb 
I have checked with latest pull but I can't reproduce this from my end.
Can you help me for reproducing the issue if I did the wrong?

https://www.loom.com/share/764990c2735a47a0a681314591c50c56
