### ISSUE TITLE
Enhancement Data Storing of Users Avatar/Cover Photo and Group Avatar/Cover Photo

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#774]
**Is your feature request related to a problem? Please describe.**
At this moment platform is storing all the data related to avatar/cover photos into the `avatar/USERID/.jpg` and same for the Groups as `group-avatars/GROUPID/.jpg`  and it's not storing these values in the Database.

Basically avatars do not get stored in the database at all, they pull from the file system based on user id matching folder id. This causes a problem for plugins that sync everything to AWS as they don't sync any of the avatars.

**Describe the solution you'd like**
We need to store values in DB and then we have to test the plugins that sync files to AWS S3 to make sure they work with avatars and cover photos.

This is the main plugin we need to test with:
https://deliciousbrains.com/wp-offload-media/

**Comment by welshlamb10** [comment]
I'm unable to use WP Offload on the latest version of the plugin. I get error 'Server repsonded 0 code' and if I post the image is blank just a broken URL. I'm in contact with WP Offload and BuddyBoss support. Hoping for a fix.

**Comment by denis-sandu** [comment]
> I'm unable to use WP Offload on the latest version of the plugin. I get error 'Server repsonded 0 code' and if I post the image is blank just a broken URL. I'm in contact with WP Offload and BuddyBoss support. Hoping for a fix.

Thanks a lot for digin up!

**Comment by sourabhmatolia** [comment]
**UPDATE**

Support to allow offloading Profile Photo, Profile Cover, Group Photo, and Group Cover will be provided by the WP Offload Media plugin team.
We might hear an update from them very soon.
Closing ticket for now. 
Thank you.
