### ISSUE TITLE
Upgrading to Worpress v5.4 causes menu icon selection controls to show up twice in the backend

### ISSUE THREAD

**Issue by ZiadJ** [buddyboss/buddyboss-platform#775]
**Describe the bug**
Upgrading to Worpress v5.4 causes menu icon selection controls to show up twice in the backend

**Screenshots**
![Screenshot_2020-04-21 Menus ‹ RBE United — WordPress](https://user-images.githubusercontent.com/1817207/79796141-175b8c80-8366-11ea-9af8-14972b2463de.png)

**Comment by eisenwasser** [comment]
@ZiadJ 

Please update your theme to the latest version. This is already fixed.
https://www.buddyboss.com/resources/buddyboss-theme-releases/1-4-3/

I am closing this issue.
