### ISSUE TITLE
GIPHY Enhancement

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#777]
**Is your feature request related to a problem? Please describe.**
When someone add GIPHY into the any places on platform then we are downloading that GIPHY video from GIPHY server and storing in server.

**Describe the solution you'd like**
We need to remove GIPHY download from the GIPHY server and we need the GIPHY url to load the GIPHY in content.

**Comment by wmacmill** [comment]
Great to see this on here - just opened my media library and realized all the images were downloaded in there! Super bloated.

**Comment by sourabhmatolia** [comment]
@wmacmill 

Issue discussed above is released in BuddyBoss Platform v1.5.5.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-5/

Please update the plugin to see the latest changes.

Thank you.
