### ISSUE TITLE
Lost Password link not working when WooCommerce plugin active

### ISSUE THREAD

**Issue by manishpatolia** [buddyboss/buddyboss-platform#778]
**Describe the bug**
When you are logged in you can edit your email address or change your password. But if you don't remember your password then the link takes you to that page. But not working lost password link when WC active.

**To Reproduce**
1. Active WC
2. Login with any subscriber user
3. Go to Account -> Login Information
4. Find our link "Lost password" and click on it

**Expected behavior**
It should work when clicking on the lost password link, it should be redirect on the lost password screen instead of my account page. 
It will be working fine after removing the WC filter
```add_filter( 'lostpassword_url', 'wc_lostpassword_url', 10, 1 );```

**Screenshots**
https://www.loom.com/share/447db582098e4078aaf82e4f2156e4b6

**Support ticket links**
 None yet

**Comment by amincdev** [comment]
The connected issue in Theme for Reset Password Form UI issue: https://github.com/buddyboss/buddyboss-theme/issues/625
