### ISSUE TITLE
Can not translate 'Drop files here to upload' string.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#780]
**Describe the bug**
You can not translate 'Drop files here to upload' string in the Media uploader box. 

**To Reproduce**
1. Go to 'Activity' page.
2. Click on media upload icon.
3. You will see the text 'Drop files here to upload'
4. You can not translate the text.

**Screenshots**
https://prnt.sc/s390da

**Support ticket links**
https://secure.helpscout.net/conversation/1135406026/68457/

**Comment by chetansatasiya** [comment]
@Anve-sri This is already fixed in previous release 1.4.0
