### ISSUE TITLE
Creating LearnDash Group with associated Social Group results to critical error since BuddyBoss Platform 1.3.0

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#785]
**Describe the bug**
A critical error occurs when you create a LearnDash group and associate it with the BuddyBoss social group. This happens since BuddyBoss Platform1.3.0 and when the Private Messaging component is disabled. 

**To Reproduce**
1. Make sure to have the latest BuddyBoss 1.3.1
2. Make sure that Social Group and Learndash Group Syncing is enabled.
3. Disable the Private Messaging component
3. Go to LearnDash LMS > Groups
4. Create a group and associate with Social Group
5. Notice that upon saving it will result in an error

**Screencast**
https://drive.google.com/file/d/1Jc_GSWp28Erp8Ps-lzRbvaJt4QnXj6Cp/view

**Support ticket links**
https://secure.helpscout.net/conversation/1142402149/69817/

**Comment by chetansatasiya** [comment]
@ayron-paul add this https://github.com/buddyboss/buddyboss-platform/pull/787/files changes to customers site who are facing this issue and it will be fixed in our next release.
