### ISSUE TITLE
Default Profile Type is not registered when the registration form is created with MemberPress. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#789]
**Describe the bug**
When we use the default BuddyBoss registration method with only Email, password, and username fields, we can see the default profile type is set automatically for a user. 

But when we create a registration page using MemberPress, nothing is entered for the profile type field for the user. 

**To Reproduce**
1. Create a registration page using MemberPress
2. Set a default profile type
3. Register a new user
4. Check the user details in the backend

**Expected behavior**
Most of our users use MemberPress and it is easy to have a paid membership while registering through MemberPress. The default registration features should work for MemberPress too. 

**Screenshots**
- https://cl.ly/dd4b89ddbd5b
- https://cl.ly/40a7bd724502
- https://cl.ly/8af18c8efde7
- https://www.loom.com/share/b32c63a09477459d8e81628ae0999282
- https://www.loom.com/share/632e1bd044584f31860368d7d079d2cc

**Support ticket links**
- https://secure.helpscout.net/conversation/1138344509/69048/

**Comment by archanabb** [comment]
https://secure.helpscout.net/conversation/1142681486/69875

**Comment by tonymeltone** [comment]
Thank you!

**Comment by tonymeltone** [comment]
Hello -

I was asked to update my plugin indicating that this issue was addressed.  But it's not addressed, yet.  This is preventing me from going live on my site.

**Comment by HQRaja** [comment]
Hello,

I need something similar too. When creating memberships in MemberPress, I need to be able to associate each membership with a BuddyBoss Profile Type. So if I create 'Silver Member' and 'Gold Member' as two profile types in BuddyBoss, as well as 'Silver Membership' and 'Gold Membership' in BuddyPress, anyone who registers for the Silver Membership gets assigned 'Silver Member' profile type in their BuddyBoss profile, and those registering for Gold Membership get assigned 'Gold Member' profile type there.

**Comment by tonymeltone** [comment]
@eisenwasser This bug was patched in my 1.3.4 environment but hasn't been merged in 1.3.5 and I just loaded 1.4.0 and it doesn't look like it was merged in that release either.  I am stuck at 1.3.4 (with no REST API) until this fix gets merged.  Can you assist?

**Comment by chetansatasiya** [comment]
@tonymeltone are you talking about this patch https://github.com/buddyboss/buddyboss-platform/pull/829 to add? If so it will be in next release for sure.

**Comment by chetansatasiya** [comment]
@HQRaja You can use [`bp_set_member_type` ](https://www.buddyboss.com/resources/reference/functions/bp_set_member_type/)function to set the member type when user is register via memberpress. So memberpress have any hook/filter when they are assigning the mebership at that time you can set the member type of the registered member.

**Comment by chetansatasiya** [comment]
> Hello,
> 
> I need something similar too. When creating memberships in MemberPress, I need to be able to associate each membership with a BuddyBoss Profile Type. So if I create 'Silver Member' and 'Gold Member' as two profile types in BuddyBoss, as well as 'Silver Membership' and 'Gold Membership' in MemberPress, anyone who registers for the Silver Membership gets assigned 'Silver Member' profile type in their BuddyBoss profile, and those registering for Gold Membership get assigned 'Gold Member' profile type there.

@HQRaja You can use bp_set_member_type function to set the member type when user is register via memberpress. So memberpress have any hook/filter when they are assigning the mebership at that time you can set the member type of the registered member.

**Comment by chetansatasiya** [comment]
> @eisenwasser This bug was patched in my 1.3.4 environment but hasn't been merged in 1.3.5 and I just loaded 1.4.0 and it doesn't look like it was merged in that release either. I am stuck at 1.3.4 (with no REST API) until this fix gets merged. Can you assist?

@tonymeltone are you talking about this patch #829 to add? If so it will be in next release for sure.

**Comment by tonymeltone** [comment]
When is next release?

**Comment by eisenwasser** [comment]
@tonymeltone Sometime within the next week or so.

**Comment by eisenwasser** [comment]
@tonymeltone @HQRaja 

This is fixed in the latest release, pushed live today:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-4/

**Comment by tonymeltone** [comment]
Got it.  All works.
Thank you, Michael and team.
