### ISSUE TITLE
Topic/Lessons link not working in the Search result when a logged user is a subscriber

### ISSUE THREAD

**Issue by manishpatolia** [buddyboss/buddyboss-platform#792]
**Describe the bug**
when **nested URL**(https://prnt.sc/s1clqk) is on in the permalink and course setting has **Shared Course Steps** (https://prnt.sc/s1cla7) enabled.
 that time for any subscriber users can search and from the result click any topic/lesson it is redirecting on the course.
It's happening only when the above 2 options enabled.

**To Reproduce**
1. Go to Paramlink and enable "nested URL"(https://prnt.sc/s1clqk)
2. Go to course setting and enable Shared Course Steps("Sections, topics, and quizzes can be shared across multiple courses"(https://prnt.sc/s1cla7))
3. logging with subscriber users
4. Click on any topic and lesson and see...

**Screenshots**
https://www.loom.com/share/7a7bdd8dd8c34835b96f78a40db6533b.

**Comment by manishpatolia** [comment]
@eisenwasser @chetansatasiya 
For this is have debugged and I saw, when enable "Nested URL" and "Shared Course Steps", that time for subscriber users lesson and topic URL works if it has selected primary course in "Course switcher(https://prnt.sc/s1cp90)" otherwise it will redirect on course.

Its LD method on bellow path
```sfwd-lms\includes\course/ld-course-functions.php
 line number 2511```
I think this is an issue or we need to change search terms when above both option enabled?
Please give me your thought about this.

**Comment by chetansatasiya** [comment]
@manishpatolia We are not going to fix this one as because it's from the LearnDash plugin.
