### ISSUE TITLE
The subgroup also showing in Groups when Allow groups to have subgroups.

### ISSUE THREAD

**Issue by manishpatolia** [buddyboss/buddyboss-platform#793]
**Describe the bug**
When Allow groups to have subgroups that time showing subgroups in the groups list

**To Reproduce**
1. Go to Setting-> Groups
2. Check Allow groups to have subgroups option
3. Create a new group and assign parent group
4. And see front send in a group list

**Expected behavior**
I think in group list subgroup not show when option enabled.

**Screenshots**
https://www.loom.com/share/f08ea9f8c56e47878ddd7023a7fb259d

**Comment by chetansatasiya** [comment]
@manishpatolia @eisenwasser Closing this as we are not going to work on this
