### ISSUE TITLE
Global search results shutting when scrolling it

### ISSUE THREAD

**Issue by joblux** [buddyboss/buddyboss-platform#795]
When using iphone, and in mode guest  your site needs to have content for this to show.

**To Reproduce**

1. search global search from iphone 
2. try read resultst in windows
3. Scroll down 
4. windows shut itself

**Expected behavior**

Expected to be able to read and scroll through the results until i initiate the close of the windows or select a result

**Screenshots**

**Support ticket links**

#68708

**Comment by amincdev** [comment]
This issue will be fixed by this PR: https://github.com/buddyboss/buddyboss-platform/pull/2901

**Comment by rmmehta** [comment]
As this issue is fix by#2901 I have closed this issue
