### ISSUE TITLE
Subgroup not displayed in subgroup tab

### ISSUE THREAD

**Issue by cedricbuddyboss** [buddyboss/buddyboss-platform#797]
**Describe the bug**
My client wants to hide the subgroups from the /groups page. For this they created a Group type and selected the option "Hide all groups of this type from Groups Directory" . But as a results the sub group isn’t displayed in the parent’ subgroup tab.

Video: https://www.loom.com/share/8dee366659c8443899a9279ab8461d82

**To Reproduce**
1. Create a group type and enable "Hide all groups of this type from Groups Directory"
2. Make this group a subgroup of another group
3. The group doesn't show in the subgroup tab (filter "All type") unless I select the correct group type in the filter

**Expected behavior**
The "Hide all groups of this type from Groups Directory" should hide the group type from the group directory only

**Comment by eisenwasser** [comment]
@cedricbuddyboss 
This is fixed and live now:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-3/

Subgroups show now in their parent group's "Subgroup" tab, if the subgroup's Group Type is set to be hidden from main Groups Directory.
