### ISSUE TITLE
BuddyBoss Email Header > can't select entire Logo

### ISSUE THREAD

**Issue by shashank-buddyboss** [buddyboss/buddyboss-platform#800]
**Describe the bug**
While I am added Logo on BuddyBoss Email Header > can not select the entire logo and also there is no option to skip image crop.

**To Reproduce**
1. Go to 'Admin Dashboard - Buddyboss - Email'
2. Click on 'Customize Layout - Header - Upload logo'
3. See error

**Expected behavior**
Can select the entire logo or have a button to skip the image crop functionality.

**Screenshots**
https://www.loom.com/share/4f5021d4029d460eb141ceee7efabf71

**Comment by eisenwasser** [comment]
@shashank-buddyboss This is fixed in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-3/
