### ISSUE TITLE
Pasting embedded video in discussion does not render video

### ISSUE THREAD

**Issue by MorganTrudeau** [buddyboss/buddyboss-platform#808]
**Description**
When creating a new topic a user may paste an embedded video in the content. They would expect this video to be rendered and be playable.

**To Reproduce**
1. Navigate to create topic screen.
2. Paste embedded video in content. Add title and submit discussion.

**Expected behavior**
Video should be rendered in iframe and be playable.

**Screenshots**
![Screen Shot 2020-04-24 at 3 53 47 PM](https://user-images.githubusercontent.com/28589416/80263017-28e1b480-8644-11ea-8e04-ad206771deba.png)

**Comment by eisenwasser** [comment]
@MorganTrudeau 

What did you embed when testing?

Did you paste a video URL such as:
https://youtu.be/-_-3jAO0jSE

Or did you paste an iframe like in your screenshot?

**Comment by eisenwasser** [comment]
@MorganTrudeau 

We are not supporting iframes only URL embeds. If we support iframes it could cause problems when people embed other kinds of iframes. I am closing this ticket for now.
