### ISSUE TITLE
Default BuddyBoss Registration Form works randomly

### ISSUE THREAD

**Issue by elkwaet** [buddyboss/buddyboss-platform#809]
I think it is a bug (sorry if it is not be one) :

I am trying to use just the plugin BuddyBossPlatform for othe theme such as Hello or Twenty_ themes (for the moment) and guess many problem with the registration form which not work fine.

When enable  registration for a non-members via "BuddyBoss Platform default form", they have many difficulties to register properly. It works only randomly and i don't understand anything about this. The tests are doing on differents browsers, different modes, deferents devices: when the fields are completed and clicking on Registrer buttom, it return on the same page keeping the informations entered without passwords fields. Despite of cookies purge and GuestMode Navigation the problem persist.
When from the dashboard new user is add, he receive promptly his Activation Mail.
**PS: We got this problem with any theme and all plugins disabling.**

Desperate, i am trying to use another registration plugin but don't know what do with BuddyBossPlatform to get his ActivationEMail sending for each registration from the custom registration page.

**Comment by jaydeeprami** [comment]
@elkwaet ,

I can't reproduce this issue. I have tried a non-BuddyBoss theme with only the BuddyBoss Platform activate and tested on different browsers.

See Proof:
https://www.loom.com/share/cea60f33f9c44a47bd6a22ca4f513d9c

Thanks

**Comment by elkwaet** [comment]
ok. Thank you.
