### ISSUE TITLE
Editor Enhancement

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#813]
**Describe the bug**
There are still few issues in Editor that needs to be fixed.

**To Reproduce**
https://www.loom.com/share/5ea81f6b257b4b3da7e987664f8db0f0
https://www.loom.com/share/f3541c5524d14e82970280663a97fe62

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1148252392/70787
