### ISSUE TITLE
PHP warnings on search page

### ISSUE THREAD

**Issue by janakkaneriya007** [buddyboss/buddyboss-platform#815]
**Describe the bug**
When all the components for search are disable and try to search something will give you PHP warning.

**To Reproduce**
1. Uncheck all option here https://prnt.sc/s6kck3
2. Go to front and search anything
3. See the PHP warnings

**Expected behavior**
There shouldn't be any PHP warnings or errors

**Screenshots**
https://prnt.sc/s6kck3
https://prnt.sc/s6kev7

**Comment by eisenwasser** [comment]
@janakkaneriya007 

This is fixed in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-3/
