### ISSUE TITLE
bp_groups_posted_update action not triggered

### ISSUE THREAD

**Issue by rubengc** [buddyboss/buddyboss-platform#821]
Hi there

On GamiPress we have an integration with BuddyPress that hooks the `bp_groups_posted_update` action to award users that post any activity in a group, but some users have reported us that this event is not working on BuddyBoss when an activity is published in a group

Can you verify if this action is correctly triggered on BuddyBoss like is triggered on BuddyPress?

**Comment by chetansatasiya** [comment]
@rubengc I just tested with the platform and that hook firing properly see here: https://www.loom.com/share/b86db00392e54b30b6448482b7befa40

Let me know if you have any particular steps to not firing that hook.

Thanks

**Comment by rubengc** [comment]
Hi @chetansatasiya thanks you so much for confirm this

i will share your video with all users that reported this issue, probably there is some a incorrect setup at their side or a conflict with any of their plugins

Best regards
