### ISSUE TITLE
Notifications on nested replies in discussion bug

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#822]
**Describe the bug**
In notifications, Admin is showing as the one who replied even if the subscriber is the actual user who replied in the nested discussions.

**To Reproduce**
1. As an Admin post a sample discussion
2. As a Subscriber, reply to the Admin post
3. As an Admin, click the option to reply to the Subscribers reply
4. As a Subscriber, click the option to reply to the Admins reply
5. See error in Subscriber notification

**Expected behavior**
The Subscriber will receive a notification that that the Admin replied when actually the subscriber is the one who replied

**Screenshots**
https://drive.google.com/open?id=1c-Bx-MYNOzeB_95ZXK_sm6GROAHL8_1Q

**Support ticket links**
https://secure.helpscout.net/conversation/1145872836/70382?folderId=3701258

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1163847775/73308
