### ISSUE TITLE
Photo Component To Include Captions/Descriptions - Pull From Text Box When Adding Photos

### ISSUE THREAD

**Issue by bryanr18lowe** [buddyboss/buddyboss-platform#826]
**Is your feature request related to a problem? Please describe.**

As we all know most images on the social networks we're all familiar with index the image caption or post text along with the image in the Photo Gallery so users browsing the photo gallery have more information along with the photo. Currently, when clicking on a photo from the photo gallery and opening it, you see that the Buddyboss Platform allows for commenting and liking the image in the right hand sidebar of the image lightbox but does not show the verbiage entered in the post or the text box when using the "Add Photos" button.

**Describe the solution you'd like**

I would like to see the verbiage from the image post or the text entered into the text box when using the "Add Photos" button appended to the user info in the upper right side of the side bar in the single image light box but above the like and comment feature. ie: 

Bryan Lowe posted an update 3 months, 2 weeks ago
Image or post verbiage goes here
Like - Comment - Delete

**Describe alternatives you've considered**

I have tried to find 3rd party plugins that would implement this feature enhancement and I have had a hard time finding one. I have noticed that others also have interest in this feature based on the fact that there are multiple projects listed for hire to do exactly as stated above on freelancer and codeable.io 

**Support ticket links**

I currently have not supplied this information to the support ticketing system.

**Comment by bryanr18lowe** [comment]
@eisenwasser I hope I'm not overstepping my boundary here by offering this feature enhancement on the git "issues". Please do not hesitate to let me know if this is something that is out of scope but I think it's extremely helpful for all users and not just myself. This is also something that would be very helpful for the future media enhancement that is pending to allow for uploading of raw video. Most video will require caption of some sort to provide enough of a description to be an effective call to action to view the video when browsing the media gallery.

**Comment by eisenwasser** [comment]
@bryanr18lowe 

Thanks for writing up a detailed description. Yes this is a commonly requested feature.

We are actually working on this in our Documents branch:
https://github.com/buddyboss/buddyboss-platform/pull/530

Document uploads also will get a preview popup similar to photos popup. We are doing a lot of random improvements in that branch including adding captions to photos and documents popups.

**Comment by bryanr18lowe** [comment]
@eisenwasser This is awesome. Thanks for the reply and the all of the hard work you guys are putting in. You all really have it together and it's very much appreciated!

**Comment by eisenwasser** [comment]
@bryanr18lowe  Thank you!

**Comment by bryanr18lowe** [comment]
@eisenwasser Sorry, last quick comment. If I have a major feature that would benefit users in mass and I could provide a precise outline of how to implement within the current buddyboss platform/theme framework, is this a good stage for outlining it?

**Comment by eisenwasser** [comment]
@bryanr18lowe 

Sure, you can outline it here:
https://github.com/buddyboss/buddyboss-platform/issues/new/choose

Select "New Enhancement" and the tag me on it. I cannot guarantee we will do it, or when we will do it, but you can go ahead and suggest it and tag me so I see. I'll take a look.
