### ISSUE TITLE
The Preview appearing twice after posting on activity feed. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#830]
**Describe the bug**
The preview for the links appearing twice. 

**To Reproduce**
1. Go to 'Activity' page.
2. Post a link there. 
3. Click on 'Post Update'.
4. The previews appear twice. 

**Expected behavior**
Only one preview should appear.

**Screenshots**
https://prnt.sc/s8kgcu

**Support ticket links**
https://secure.helpscout.net/conversation/1149365511/70971?folderId=3709080

**Comment by archanabb** [comment]
https://secure.helpscout.net/conversation/1140435190/69438/

**Comment by marilyn9425** [comment]
https://secure.helpscout.net/conversation/1149363673/70970
