### ISSUE TITLE
Strings like "His", "Their" are not translatable, they are in a JavaScript file in non-translatable way. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#832]
**Describe the bug**
Strings like "His", "Their" are not translatable, they are in a JavaScript file in a non-translatable way. 

**To Reproduce**
The strings which are gender-related are not translatable. Loco Translate could not find them so I tried to search for the strings using the String Locator plugin. 

I found "his_" in the following two files, _bps-xprofile.php_, and _class-bp-xprofile-field-type-gender.php_ files. 

**Expected behavior**
All the strings must be translatable. 

**Screenshots**
- https://i.imgur.com/h0TqZQL.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1147987881/70738?folderId=3701247#modal

**Comment by janakkaneriya007** [comment]
@archanabb 

The strings you have mentioned are not for the display purpose also those stings are not visible on frontend as well.
