### ISSUE TITLE
Forums don't allow threaded discussions beyond one level deep

### ISSUE THREAD

**Issue by IdeaOutline** [buddyboss/buddyboss-platform#834]
In Buddyboss / Settings / Forums: After setting Reply threading up to 10 levels deep, the most I can get is one level deep before it reverts to straight line commenting.

**Comment by eisenwasser** [comment]
@IdeaOutline 
This is fixed in today's release:

https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-0/
https://www.buddyboss.com/resources/buddyboss-theme-releases/1-5-0/

**Comment by IdeaOutline** [comment]
Thanks! It works great and looks good, all the way down to the 10th level!

**Comment by eisenwasser** [comment]
Awesome!
