### ISSUE TITLE
Credit card field not working in memberpress form.

### ISSUE THREAD

**Issue by manishpatolia** [buddyboss/buddyboss-platform#850]
**Describe the bug**
When we create new membership and add payment gateway strip and open that form for signup membership that time credit card field not working.

**To Reproduce**
1. Active Memberpress 
2. Create New Membership and add payment gateway strip.
3. Open that form and see credit card detail fields

**Expected behavior**
The credit card field should work fine in the form.

**Screenshots**
https://prnt.sc/sb2nyc

**Note:** Need to change on `bp-code/js/register.js` line number 31 `if ( typeof dropDownSelected.val() !== 'undefined' && dropDownSelected.val().length )` instead of `if ( dropDownSelected.val().length )`.

**Comment by emmanoctaviano** [comment]
https://secure.helpscout.net/conversation/1149911154/71054?folderId=3701258
