### ISSUE TITLE
BP Profile Search plugin throws a warning when the platform plugin is active. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#854]
**Describe the bug**
BP Profile Search plugin throws a warning when the platform plugin is active. Checked with the default WP theme and BuddyPress plugin, it works without any error/warning. 

Here is the warning:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'bp_profile_search_show_form' not found or invalid function name in /app/public/wp-includes/class-wp-hook.php on line 287

**To Reproduce**
1. Install and activate the BP Profile Search plugin
2. Create a search template
3. Add a widget and visit it in the front end

**Expected behavior**
It should work without any warnings. 

**Screenshots**
- with default theme: https://i.imgur.com/PI9PxtS.jpg
- with the platform: https://i.imgur.com/5dmhQ3s.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1157056737/72179

**Comment by janakkaneriya007** [comment]
@archanabb 
This issue is related to theme and created the issue there: https://github.com/buddyboss/buddyboss-theme/issues/645
