### ISSUE TITLE
Activity page loads really slow. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#856]
**Describe the bug**
A user reported that some links shared on the activity page make the page load slow. I am not sure about the links but the page loads really slow after the recent update. It takes 12- 15 seconds to load the page. 

**To Reproduce**
1. Go to activity page
2. See error

**Expected behavior**
The page should load without issues. 

**Screenshots**
- https://www.loom.com/share/c58c536d41dc48be9b93a133f63bafa4

**Support ticket links**
- https://secure.helpscout.net/conversation/1151202224/71255/

**Comment by janakkaneriya007** [comment]
@archanabb 
Are trying same scenario mentioned here?
https://github.com/buddyboss/buddyboss-platform/issues/634

**Comment by archanabb** [comment]
Yep @janakkaneriya007 It's the same.
