### ISSUE TITLE
Forums - If Tags are disabled then they should not show on discussion replies

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#858]
**Describe the bug**
When disabling tags in discussions, they are still appearing on discussion replies.

**To Reproduce**
1. Go to BuddyBoss > Settings > Forums
2. Uncheck "Allow discussions to have tags"
3. View frontend, tags are gone from discussions/topics, but still appear on replies.

**Expected behavior**
Tags should be removed from both discussions and replies.

**Screenshots**

**Support ticket links**
None yet. Reported by AppBoss team

**Comment by janakkaneriya007** [comment]
@eisenwasser 
Do you mean tags mentioned here?
https://prnt.sc/scj1o3

**Comment by eisenwasser** [comment]
Yes
