### ISSUE TITLE
Group members are not loading if huge number of users are there in a group

### ISSUE THREAD

**Issue by BhargavBhandari90** [buddyboss/buddyboss-platform#859]
When there are thousands of users in a group, and when we try to access members section of the group, it will take a lot of time to load members OR it gives us 505 error in console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create any group.
2. Try to add around 7000 users.
3. Now try to access the members section. > http://prntscr.com/sc52ts 
4. It will always display this message. > http://prntscr.com/sc538g 

**Expected behaviour**
It should load members on the group members section as it is loading on the `https://siteurl.com/members/` ( 20 users on each page )

**Video Explaining the issue**
https://www.loom.com/share/8898738258b0414cbd119066a1153cad

**Required DB**

**Comment by eisenwasser** [comment]
@BhargavBhandari90 Can you provide the sample DB you are using to @janakkaneriya007 so he can easily reproduce this

**Comment by BhargavBhandari90** [comment]
I've already provided in the description at the last line "Required DB"

**Comment by eisenwasser** [comment]
The last line **Required DB** has no value under it.
But Janak is already in progress on this so I think he got the data sample he needs anyways

**Comment by MadCowWeb** [comment]
FWIW, really bummed that this was closed. still a massive downfall of this platform. we've had to move hosting from wpengine since their platform wouldn't even run that page.  baffled that the smart folks at BB have not learned how to just load the first 20 users.  any update on this?
