### ISSUE TITLE
URL Preview issues in the activity feed. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#866]
**Describe the bug**
1. The preview is following WordPress style and not the theme's style

Other scenarios ( I could not replicate any of these on my site but the user is experiencing)

1. Preview link/box instead of the embed player

- Copy-paste any Youtube / Soundcloud / Vimeo link
- Click on 'enter' BEFORE the preview link pops up and start typing (note: need to do it fast enough or have a bad internet connection in order to replicate it)
- Click on submit
- Youtube embed result: Preview box instead of the embed player
- Soundcloud embed result: 9 out of 10 times it works, that one time it didn't work it doesn't show a preview at all
- Vimeo embed result: A message with a red font color: 'Sorry! preview is not available right now. Please try again later.'

2. Visible embed link

**_- First case_**
- Copy-paste any Youtube / Soundcloud / Vimeo link
- AFTER the preview link pops up
- Click on 'enter' and start typing anything
- Click on submit
- Youtube embed result: Looks good. No problem
- Soundcloud embed result: Looks good. No problem
- Vimeo embed result: Looks good. No problem
**_- Second case_**
- Copy-paste any Youtube / Soundcloud / Vimeo link
- AFTER the preview link pops up
- Click on 'space' start typing anything
- Click on submit
- Youtube embed result:Embed link is visible
- Soundcloud embed result:Embed link is visible
- Vimeo embed result: Embed link is visible
**_- Third case_**
- Type anything first BEFORE you add any links
- Copy-paste any Youtube / Soundcloud / Vimeo link
- Click on submit
- Youtube embed result: Embed link is visible
- Soundcloud embed result: Embed link is visible
- Vimeo embed result: Embed link is visible

**Screenshots**
- https://i.imgur.com/3Q9Nmwf.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1150244392/71113?folderId=3701247
- https://secure.helpscout.net/conversation/1140435190/69438/

**Comment by archanabb** [comment]
https://secure.helpscout.net/conversation/1162952061/73175?folderId=3709080

**Comment by sadrul** [comment]
@sourabhmatolia this is what i found in sandbox site -  https://www.loom.com/share/6589465653b44726ab37bdc0af2f1776

For #1, I was able to replicate this issue - https://i.imgur.com/GRIm9UI.png when I don't allow time to generate embed code (in the video time 3:33) but I wonder is it a bug or user should allow that time? Need your comments

For #2 third case https://i.imgur.com/BjCtDhF.png, I could replicate that. But should we consider this as a bug, please suggest

**Comment by marienel21** [comment]
I can validate the third case bug.
