### ISSUE TITLE
Non-admin have HTML tags showing on forum replies

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#867]
**Describe the bug**
Non-admin have HTML tags showing on forum replies if they copy the content from a web page

**To Reproduce**
1. As a Subscriber, go to Discussions and reply to one 
2. Copy your content from a web page
3. Paste the content and reply this in the discussion
4. See error, HTML Tags are showing

**Expected behavior**
When subscribers are posting replies that they copy from a web page, HTML tags are showing.
For admins however, this is working fine. 

**Screenshots**
https://drive.google.com/open?id=1kteSXP6Rgq0kulSpB5lCUv8dLgEtUfZC

**Support ticket links**
https://secure.helpscout.net/conversation/1158427048/72424?folderId=3701258

**Comment by janakkaneriya007** [comment]
@emmanoctaviano 

The content is being filtered based on the user capabilities that's why when admins post something in replies it show content without html tags and for other users it show content with html tags.

**Comment by emmanoctaviano** [comment]
@eisenwasser @KartikSuthar this issue is not yet resolved. 

Issue can still be reproduced on demo: https://drive.google.com/open?id=1KxcPVejpURNw-iOmlRGIvf4suQRCE7Nt

Also on dev site: 
![htmlforums](https://user-images.githubusercontent.com/58522224/83874055-7c790f00-a767-11ea-9e92-a42622f1d1d5.JPG)

**Comment by eisenwasser** [comment]
@emmanoctaviano 

Wow thanks, that's not good. In my own testing I was unable to reproduce this actually, so apparently it depends on where you copy from.

@KartikSuthar Need to re-investigate this, apparently is still happening.

**Comment by buddyedilene** [comment]
Hi All. I have a client who has the same issue. A non-admin user created a discussion topic on iPad Safari and entered extra 'enter keys' at the end of the sentences. https://prnt.sc/tj2hae
Please check ticket: https://secure.helpscout.net/conversation/1224571499/83184?folderId=3701257
