### ISSUE TITLE
Profile Details _Name fields not having any length validations

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#868]
**Description**
If registered user enters any long string in name field then it is breaking design of whole website .

**Steps**
1. Login
2. Go to User Profile '
3. Click on 'Edit Profile'
4. Edit First Name and Last Name fields and enter very long string.
5. Click on save changes.
6. See Error

**Expected behavior**
First Name and Last Namefields must have restricted length.  

**Kindly see below video**
[Video Link](https://www.loom.com/share/d63ac18d7ce642a3931d9a97e67ad632)

**Jira issue** : [PROD-951]

[PROD-951]: https://buddyboss.atlassian.net/browse/PROD-951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ankitguptaindia** [comment]
@mohit-buddyboss 

No, This issue is not genuine in real scenario. In the general way no one having name like you entered  
 https://prnt.sc/sd0ga4

If any user still having Long name then they will have space in between the word like `Arnold Schwarzenegger`  `Michael Eisenwasser`   and these words are working fine in our theme.
https://prnt.sc/sd0k6m

**Comment by mohit-buddyboss** [comment]
@ankitguptaindia 

Yes, agree that this is negative scenario but still this case is possible if any user intentionally put name longer then it can break whole website UI.  

So,it can create 2 problems
1) It will create UI as well as security concern  for website.
2) Also, if in future customer wants to integrate BB platform with other tools or social media applications then also it will create issues.  Because all major social media platforms have length limit validation in their Name fields.  Twitter allow 20 characters where as FB don't mention any limit but if we check in their General Settings they consider name long if we add more than 30 characters. 

So, it is low priority issue but it can impact platform.
