### ISSUE TITLE
Message activity email notification contains HTML elements.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#869]
**Description**
When user sends a message to another user on BuddyBoss Platform then it sends an email to the receiver . But that message in email appearing along with HTML elements.

**Steps**
1. Send a message to another registered user on BuddyBoss platform.
2. Check Receiver email.
3. See Error

**Expected behavior**
Email body must not display HTML elements..

**Screenshots**
See this [Screenshot](https://prnt.sc/sctz1l) and [Video](https://www.loom.com/share/7677859af5ff4aa69bd5d1a6c3db4711)

Thank you

**Comment by ankitguptaindia** [comment]
@mohit-buddyboss Thanks for the feedback. 
Please check this issue with Dev branch once and let us know if issue is still there.

Thanks

**Comment by mohit-buddyboss** [comment]
@ankitguptaindia 
Tested on dev branch[version: 1.3.4],  Issue exist in dev branch. See [Screenshot](https://prnt.sc/sd0nc8)

Thank you

**Comment by ankitguptaindia** [comment]
Okay Thanks @mohit-buddyboss 
----

@chetansatasiya Please assign this issue as high priority to respective developer

**Comment by ayron-paul** [comment]
Same issue: https://secure.helpscout.net/conversation/1156011786/71974/

**Comment by manishpatolia** [comment]
@mohit-buddyboss @ankitguptaindia @chetansatasiya  I have checked the above HTML tag issue in mail working fine for me. We should care about a thing when we use token in HTML content then aways used `{{{ }}}` curly braces. when you used HTML content token with 2 curly braces then it will show HTML tags.
Proof:
https://www.loom.com/share/02910cbd781a4dfe8a0baf7d429c6ba8

@ayron-paul I have checked the above ticket client's dev site, and I saw there have also the same thing happening there. I have changed HTML content token and checked, mail working fine.

See the below proof:
https://prnt.sc/sffyg9
https://prnt.sc/sffzv5
https://prnt.sc/sfg0aa
https://prnt.sc/sfg0i1

**Comment by ayron-paul** [comment]
Noted @manishpatolia, thank you very much.

**Comment by mohit-buddyboss** [comment]
@manishpatolia Thanks for the clarification.
