### ISSUE TITLE
No 'Delete Conversation' option in Messages for non-admins

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#870]
**Describe the bug**
When viewing users messages by "View As", there is an option to Delete Conversation. But it is not visible if you signed in as a user itself.

**To Reproduce**
1. Log in as non-admin
2. Go to 'Messages'
3. Click on 'three dots' in chat area.
4. No 'delete conversation' option.

**Screenshots**
http://somup.com/cYhiIljhRy

**Support ticket links**
https://secure.helpscout.net/conversation/1158588806/72442/

**Comment by manishpatolia** [comment]
@Anve-sri This is not a bug, Only admin and "View As" has a 'delete conversation' option, not any non-admin can see that option.
@chetansatasiya Can you give us your thought here?

**Comment by chetansatasiya** [comment]
> @Anve-sri This is not a bug, Only admin and "View As" user has a 'delete conversation' option, not any non-admin can see that option.
> @chetansatasiya Can you give us your thought here?

@manishpatolia Yes, you are correct.

@Anve-sri only the admin users have a `delete conversation` options not admin user can remove his/her messages only.

**Comment by Anve-sri** [comment]
Thanks for explaining
