### ISSUE TITLE
Members Following Me widget setting is not working properly

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#871]
**Describe the bug**
When using **(BB) Members Following Me** widget, setting the "**Max members to show**" is not working when more than 20 is set to be displayed. Also, more button only redirects to members page.

**To Reproduce**
1. Try to use **(BB) Members Following Me** widget
2. Set the **Max members to show** to more than 20
3. Go to a member with more than 20 followers

**Expected behavior**
The **Max members to show** setting should work properly

**Screenshots**
![set-30](https://user-images.githubusercontent.com/58522498/81439166-87f50c80-91a0-11ea-91c6-1e7353335373.png)
![members-followers](https://user-images.githubusercontent.com/58522498/81439167-888da300-91a0-11ea-9b8f-6f89d7ad181b.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1154430495/71749?folderId=3701263

**Comment by ayron-paul** [comment]
Hi @janakkaneriya007, any updates on this? Thanks

**Comment by Nayeem-BB** [comment]
https://secure.helpscout.net/conversation/1346864368/110614
