### ISSUE TITLE
All results in search for blank string shows the quotation marks.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#872]
**Describe the bug**
If you click on search with no string mentioned , it shows double quotation marks in 'All results'.

**Expected behavior**
Should not show the quotation marks. 

**Screenshots**
[search.zip](https://github.com/buddyboss/buddyboss-platform/files/4602891/search.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1140460465/69444?folderId=3701249

**Comment by janakkaneriya007** [comment]
@Anve-sri 
If you try to search for the string it also shows the searched term in single quote. So, if you directly search anything without typing anything it consider it as a string also. Although we can some kind of validation like required search string. Please confirm with @eisenwasser

**Comment by eisenwasser** [comment]
@janakkaneriya007 

Can you make it just say **No results found** if they do a blank search?

This is extremely low priority though...
