### ISSUE TITLE
Translation of the back-end strings are not working.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#873]
**Describe the bug**
You can not translate the strings that appear in back-end for BuddyBoss settings. 
The customer needs to have fully translated backend. 

**Screenshots**
<img width="1168" alt="string1" src="https://user-images.githubusercontent.com/58801078/81467510-a5ed5c00-91f6-11ea-8b16-9171e8949bd7.png">
<img width="1668" alt="string2" src="https://user-images.githubusercontent.com/58801078/81467513-ad146a00-91f6-11ea-8833-f7a4ecacdf2e.png">
<img width="1136" alt="string3" src="https://user-images.githubusercontent.com/58801078/81467518-b6053b80-91f6-11ea-986f-c6d36ed76435.png">
<img width="1136" alt="string4" src="https://user-images.githubusercontent.com/58801078/81467520-bc93b300-91f6-11ea-8d3f-76dc6f820c00.png">

**Support ticket links**
https://secure.helpscout.net/conversation/1140460465/69444?folderId=3701249

**Comment by AiratHalitov** [comment]
@eisenwasser 
It would be great if you will check front-end strings and theme's translations too.

**Comment by AiratHalitov** [comment]
I see the Russian language in the screenshots. Could this translations be added into buddyboss-platform?

**Comment by eisenwasser** [comment]
@AiratHalitov 

Those screenshots are coming from a customer's website, from a customer support ticket. That person did their own translations specific to their website.

We can only publish translations if someone voluntarily contributes them to us.

**Comment by AiratHalitov** [comment]
@eisenwasser 
Yes, I know it. 
Maybe could you ask them to push their translations into this repository?

**Comment by eisenwasser** [comment]
@AiratHalitov 

We are currently setting up a website where users will be able to upload and contribute to our language files, which we will then merge into our repo periodically. It will resolve this problem.

**Comment by AiratHalitov** [comment]
@eisenwasser 
Are you talking about transifex? Or GlotPress? Or other solution?
Any way it would be great.

**Comment by eisenwasser** [comment]
@AiratHalitov 

Yes we are experimenting with those and also https://weglot.com/

**Comment by AiratHalitov** [comment]
@eisenwasser 
What about publishing buddyboss-platform plugin into WordPress.org repository?

**Comment by eisenwasser** [comment]
That will happen eventually. Once we do that we need to reply to all the customer support on wordpress.org, so we just want to wait until we are ready for all that. The plugin is very popular already and will get hundreds or maybe thousands of questions once it is there, we need to make sure we are able to answer them all. It's not super urgent as we are already open source on Github and able to provide automatic updates. It will happen eventually.

**Comment by velmyshanovnyi** [comment]
Всем привет, 
вижу на скриншотах русский текст, подскажите, есть ли у кого то русский  (ru_RU) перевод для фронтенда?

не могу нигде найти... :(

**Comment by velmyshanovnyi** [comment]
Привет
вот РУССКИЙ ПЕРЕВОД ЛОКАЛИЗАЦИИ (продолжаю фиксить ошибки)
пользуйтесь :)

если будет ветка на https://translate.wordpress.org/ 
то все будет значительно быстрее

перевод с помощью:
https://wordpress.org/plugins/loco-translate/

buddyboss-theme-ru_RU.PO
[buddyboss-theme-ru_RU.zip](https://github.com/buddyboss/buddyboss-platform/files/5875238/buddyboss-theme-ru_RU.zip)

buddyboss-pro-ru_RU.PO
[buddyboss-pro-ru_RU.zip](https://github.com/buddyboss/buddyboss-platform/files/5875260/buddyboss-pro-ru_RU.zip)

buddyboss-ru_RU.PO
[buddyboss-ru_RU.zip](https://github.com/buddyboss/buddyboss-platform/files/5875261/buddyboss-ru_RU.zip)

**Comment by velmyshanovnyi** [comment]
![image](https://user-images.githubusercontent.com/1027826/105889744-31be4700-6017-11eb-90b4-0d5211e2bcc7.png)
![image](https://user-images.githubusercontent.com/1027826/105889882-561a2380-6017-11eb-98a9-8f426e97a5b3.png)
![image](https://user-images.githubusercontent.com/1027826/105890018-7e098700-6017-11eb-94c1-0aaf8f2ae87e.png)

**Comment by AiratHalitov** [comment]
@velmyshanovnyi Thanks! 
`buddyboss-theme-ru_RU.po` file is empty

Here is what I found:

- https://neonafm.ru/product/buddyboss-theme-ru_ru/
- https://neonafm.ru/product/buddyboss-ru_ru/
- https://neonafm.ru/product/buddyboss-pro-ru_ru/

Maybe it will be useful.
