### ISSUE TITLE
Buddyboss EVENT plugin

### ISSUE THREAD

**Issue by makfoulie** [buddyboss/buddyboss-platform#874]
**Is your feature request related to a problem? Please describe.**
Users want to have a plugin where they can inform their plans, update and engage the participants of their events. As a community administrator, you have full control on this app such as approve events, configure the permission of event creation, editing, deletion on each user group and more.

**Describe the solution you'd like**
Manage Events
You can manage all events created by your users. You can edit full information of events as well as approve or feature or even delete them.

Approval System
You can enable approval system where, if enabled, users will have their events viewed by a site moderator before it can be viewed publicly. The moderators can then decide to either approve or deny the event.

Quick & Easy
Provide a block on your user's dashboard so they can create an event at any time within seconds.

Report an Event
Events can be reported to the Admins by the community to help prevent SPAM and/or remove inappropriate material that is considered to breach the terms & conditions of the site.

Invite Friends
Allow your users to invite their friends to join the event by using a powerful guest list manager or by sending out emails.

Mass Email
Keeping users up-to-date with an event is crucial and those that host events can mass email all of their guests directly from their event manager.

Likes, Comments & Shares
Keep your users active by giving them the ability to easily Like or comment on an event.

Activity Feed
Each event includes its very own activity feed. When a user attend an event it creates an activity feed.

Search Filter
By using search filter your users can easily find the events they are looking for.

RSVP
Potential guests to an event can RSVP one of the following options (Admin can active or not the maybe attending option) :

- Attending

- Maybe Attending (Admin can activate or not this option)

- Not Attending

Create a widget with attendees' avatar and count.

Join Events
Provide some options for your users to express their willingness to join events or not. They can be attending, (maybe attending) or not attending.

Post status
Keep your users active by giving them the ability to easily post their statuses into the events.

Start & End Times
Your users can define the exact time their event will start and end (optional in admin section).

Privacy Control
Users can control who can view and comment on their event (all, only friends, custom...). 

Custom Categories
You can create as many categories as you want and edit the categories for events.

Also all front end fields must be editable in admin dashboard and admin can mandatory or not a field.

**Describe alternatives you've considered**
Here is a description from the CMS PHPFOX:
https://www.phpfox.com/features/engagement/events/

For buddypress/boss there is NOT a dedicated event plugin.
The buddypress simple event:
https://wordpress.org/plugins/buddypress-simple-events/#developers
miss some features.

**Support ticket links**
I have not submitted this information to the ticketing platform.

Hope you will consider this request. Most CMS have this feature: PHPFOX, socialengine, Jomsocial (joomla), Easysocial (Joomla)... I think this is a basic feature for all communities CMS. This is just insane that a plugin like Buddypress haven't a viable option for event...

Regards.

**Comment by eisenwasser** [comment]
@makfoulie 

Thanks for the suggestion.

Right now we are using Events Calendar to handle events:
https://theeventscalendar.com/

We are in talks with them to extend their integrations for BuddyBoss to make everything more feature rich. We will consider your feedback above in these decisions.

For now I am closing this issue as we are not actively working on this feature in the actual BuddyBoss Platform plugin code.

Thanks!

**Comment by justinpatrickkeller** [comment]
@eisenwasser is this getting anywhere? Getting TEC to extend their integration with BuddyBoss... After reviewing all the events plugins I've stuck with TEC and AutomatorWP... there is ALOT of opportunity here. It's been a total PITA that a community platform doesn't have a dialed integration with an events management system.
