### ISSUE TITLE
Conditional Profile Fields

### ISSUE THREAD

**Issue by makfoulie** [buddyboss/buddyboss-platform#875]
**Is your feature request related to a problem? Please describe.**
Conditional Profile Fields plugin allows site admins to set conditions for the hiding/showing profile fields based on the various data entered by the user.

**Describe the solution you'd like**
Maybe this feature is easy to integrate in the platform. So we don't need to use another addon with no guarantee that it will be updated in the future by the autor.

**Describe alternatives you've considered**
https://buddydev.com/plugins/conditional-profile-fields-for-buddypress/
![image](https://user-images.githubusercontent.com/25231367/81474956-37fe6000-9209-11ea-9beb-12e7688d76ad.png)

**Support ticket links**
No ticket.

**Comment by eisenwasser** [comment]
@makfoulie 

Yes, this is something we have considered adding in the past. I will add this one to the official list. Not sure when we will get to working on this, will probably be some time. But it's in the list now.

Thanks!

**Comment by tonymeltone** [comment]
Would love to see conditional fields in platform @eisenwasser and team.  We have several fields that we want to restrict from certain member types, but allow other member types to view.   For example, we want athlete phone numbers to be visible by coaches but not other athletes (both coaches and athletes are members)

**Comment by tonymeltone** [comment]
@eisenwasser I would like to see conditional field display logic based on the **logged in user's profile type.**  

For each field you can set visibility based on profile.  It would allow display or hide field based on one or more profile types selected.  This would be applied to the logged in user viewing the profile  - not the person entering profile data.

**Comment by eisenwasser** [comment]
@tonymeltone 

Makes sense, I use this same feature all the time in Gravity Forms. We'll keep this on the to-do list.

**Comment by tonymeltone** [comment]
I am having a plugin developed to do it.  Will share with you if it helps.

**Comment by eisenwasser** [comment]
Cool! Sure, feel free to share.

**Comment by tonymeltone** [comment]
@eisenwasser I sent you a collaboration invitation for the plugin.

**Comment by vinaysagar4u** [comment]
Any Updates on this?

What is the latest solution to make it work?

**Comment by makfoulie** [comment]
Hello the add-on "conditional profile fields" works fine with buddy boss. We would prefer to be in core 😉

**Comment by vinaysagar4u** [comment]
Cool! When would it occur!? Haha

**Comment by sourabhmatolia** [comment]
@vinaysagar4u @makfoulie 

We will check internally again and get back to you guys. Thanks.

**Comment by marienel21** [comment]
Hi @makfoulie,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
