### ISSUE TITLE
Add some Custom Field Types

### ISSUE THREAD

**Issue by makfoulie** [buddyboss/buddyboss-platform#876]
Note from Michael:
This needs an official scope of approved fields before we begin development.

----

**Is your feature request related to a problem? Please describe.**
Custom Field Types plugin adds some essential field types to BuddyPress Profile.
When using an extra addon like "BuddyPress Xprofile Custom Field Types" we can't set extra fields in the default search fields selector provided by buddyboss. We need to install another plugin like https://wordpress.org/plugins/bp-profile-search/ to filter these custom fields.

**Describe the solution you'd like**
In the default buddyboss field types, there are some missing field types such as:

* Birthdate.
* Image.
* File.
* Checkbox acceptance.
* From/To field(can be used to show 2 numbers or text strings).
* Token (can be used to set a list of predefined approved codes for registration etc).
* oEmbed ( allow your users to use youtube/facebook, vimeo and other oembed supporting urls to embed in their profile).
* Email.
* Web.
* Datepicker.
* Custom post type selector.
* Custom post type multiselector.
* Colorpicker.
* Decimal number.
* Number within min/max values.
* Custom taxonomy selector.
* Custom taxonomy multiselector.
* Range input (slider)
* Select2 javascript plugin for select boxes.

Maybe you can easily add these fields to the buddyboss platform ?

**Describe alternatives you've considered**
https://wordpress.org/plugins/bp-xprofile-custom-field-types/
https://wordpress.org/plugins/bp-profile-search/
and https://wordpress.org/plugins/bp-distance-search/ for distance search

3 plugins to do something basic :/ .

**Support ticket links**
No ticket.

**Comment by eisenwasser** [comment]
@makfoulie 

Thanks for the feedback! This is something we have considered in the past, to extend the default profile fields with more types. 

We will come back to this eventually. We may not add all of the types you suggested, but some of the more important ones. I also would like to add an Address field, that has multiple items in it like City, State, ZIP, Country, and for State/Province it has drop-downs already populated for major countries like USA, Canada etc. Country dropdown could be pre-populated also.

**Comment by makfoulie** [comment]
Thank you for considering this :).
I think Birthdate is a must have field for a networking platform. Then a profile picture field to force (or not, admin can activate/desactivate in back office this option to be mandatory) users to upload a profile picture in register form is, IMO, a must have.

**Comment by makfoulie** [comment]
Google APIs permit users to enter their city and auto complete the field so don't need many fields with Contry, City, Zip code... 
![image](https://user-images.githubusercontent.com/25231367/83341102-ced9ac00-a2df-11ea-96b9-53bf0a9aa397.png)

**Comment by eisenwasser** [comment]
@makfoulie Yes but users need to pay for Google API and it has been getting more expensive over time. Not everyone wants to do that. We could still integrate with it, but for many people if we auto-populate the country list and the cities it resolves a lot if they are not using Google API.

If you have used Gravity Forms, their address field is a really nice example of this.

**Comment by tonymeltone** [comment]
I would like to see a decimal field (constantly struggling with that) a currency field (prepend with symbol, number, commas, decimals)  a proper number field (displaying commas) and a percent field.

**Comment by eisenwasser** [comment]
Thanks for the feedback.

**Comment by marienel21** [comment]
Hi @makfoulie ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
