### ISSUE TITLE
Likes and comments on the image are not in sync. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#881]
**Describe the bug**
Likes and comments on the image are not in sync. The images shared on the activity feeds do not display any likes or comments when we click on them and open. Not even in the photo album. 

**To Reproduce**
1. Go to the activity page
2. post a picture, like it and add a comment
3. click on the image and open OR open the photos tab from your profile and open the image

**Expected behavior**
The comments and likes should be synced on all the pages. 

**Screenshots**
https://www.loom.com/share/d6e4ce90791d4c56a164a252e7a5f58f

**Support ticket links**
https://secure.helpscout.net/conversation/1155971541/71966/

**Comment by KartikSuthar** [comment]
@archanabb It was already fixed and released. http://prntscr.com/t2ha8d
http://somup.com/cY1qfKQOO4
