### ISSUE TITLE
Add ability to include joined group posts in All Updates tab in Activity feed

### ISSUE THREAD

**Issue by LukeStaszewski** [buddyboss/buddyboss-platform#883]
**Is your feature request related to a problem? Please describe.**
When a user views the News Feed / Activity page the default selection is the All Updates tab. In this tab, we are currently unable to include updates from Groups that the user has joined if they are private groups. The desired functionality would be similar to how Facebook groups work as of now.

**Describe the solution you'd like**
An option to include joined group posts in the newsfeed. Perhaps in this section of the admin: https://i.imgur.com/lJwfKcW.png

**Describe alternatives you've considered**
I've tried to find Buddypress plugins for this, but it seems like this functionality is available by default in Buddypress, so there is no plugins for it.

**Support ticket links**
72439

I would be happy to attempt to fix this issue myself and contribute to this project, however, it would be great to have some clarification this isn't something that someone else has fixed already or there are any technical limitations as to why this isn't already a feature.

**Comment by eisenwasser** [comment]
@LukeStaszewski 

This is fixed in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-3/

No need to do any special settings. It is now the default behavior.
