### ISSUE TITLE
vertical scroll bar disappears (and progressive load fails) when message list height > 660 px

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#884]
**Describe the bug**

In Private Messaging, Progressively loads message history as long as .bp-messages-nav-panel is shorter than 660px height. However, on large monitors, the div (correctly) gets taller. But then the scrollbar disappears, and as a result, only the first 10 messages show. No progressive loading. 

**To Reproduce**
https://drive.google.com/file/d/1vsnLOpuJV7gilM0jdiInCmP3sX5VWka0/view

**Expected behavior**
 The scroll bar should be relative to .bp-messages-nav-panel and should always display as long as (132 + (66 x {number of total messages})) > height.bp-messages-nav-panel

**Support ticket links**
https://secure.helpscout.net/conversation/1142950781/69914?folderId=3709081

**Comment by kent-carlo** [comment]
@furqanbb I can't replicate the issue in my dev site with latest bb platform plugin and theme. 
![image](https://user-images.githubusercontent.com/82648504/129584864-adcbde68-9bf9-49e4-8a41-6bf9c1a96297.png)

**Comment by furqanbb** [comment]
Working fine with the latest theme/platform version.
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-7-5/
https://www.buddyboss.com/resources/buddyboss-theme-releases/1-7-3/

Closing this issue here.
