### ISSUE TITLE
Forums Still Showing Regardless of Restriction. 

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#885]
**Describe the bug**
Private Network option is enabled but still forum page is accessible.

**To Reproduce**
1. Go to 'Admin Dashboard >> BuddyBoss >> Settings.
2. Enable Private Network option.
3. View the forum page.

**Expected behavior**
Forums page should not be accessible if it's not included in the public content area.

**Support ticket links**
https://secure.helpscout.net/conversation/1147898009/70721/

**Comment by janakkaneriya007** [comment]
@furqanbb 
FYI It's happening because there is no forums on the site and when trying to access the forums page it's showing forums page regardless restrict settings.
