### ISSUE TITLE
[activity-stream] is not working with BuddyBoss Platform plugin. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#888]
**Describe the bug**
_[activity-stream]_ provided by https://wordpress.org/plugins/bp-activity-shortcode/ is not working with the BuddyBoss Platform plugin. 

As mentioned here https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-activity-shortcode/, it should work. 

**To Reproduce**
1. Create a page using this shortcode
2. Check that page on the front end
3. See error

**Expected behavior**
It should work without any issue. 

**Screenshots**
- https://i.imgur.com/hvkPgTT.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1161065261/72865/

**Comment by manishpatolia** [comment]
@archanabb I have checked with the latest dev pull and working fine for me.
Check my below video and let me know if I forget any step for reproducing.
https://www.loom.com/share/76025cc7e89b4c59b50a95540ca0108f

**Comment by chetansatasiya** [comment]
Closing this as this is not reproducable anymore.
