### ISSUE TITLE
Email notification for reply on comment not show images if user commented using photo.

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#896]
**Describe the bug**
If user B comments on User A status or activity and attached image to the comment then email notification for reply on comment blank text area gets display .

**To Reproduce**
1. Go to user status.
2. Click on reply
3. Attach image using 'Attach a photo' option
4. Post comment
5. Check email notification for comment.

**Expected behavior**
Commented images must be display

**Screenshots**
https://www.loom.com/share/4cf3504de4a741feb2ce3bc245f7ced5

**Comment by marienel21** [comment]
![image](https://user-images.githubusercontent.com/77659570/127489367-41556844-8c1e-4bbd-9e56-cb5acbaed01d.png)

**Comment by kent-carlo** [comment]
@mohit-buddyboss the out is intended as what I can see in the code, it should only display the number of photos uploaded.

**Comment by mohit-buddyboss** [comment]
@kent-carlo Thanks for the clarification. Closing this issue.
