### ISSUE TITLE
Entries in repeating fieldsets cannot be deleted when containing a paragraph text field 

### ISSUE THREAD

**Issue by ZiadJ** [buddyboss/buddyboss-platform#898]
Repeating field sets with a paragraph text field don't respond to deletion clicks in the profile edit page.

**To Reproduce**
1. Create a repeating field set 
2. Add a field of type paragraph text to it
3. Add a second field set to the list
4. Click on the delete button on any of them

**Expected behavior**
The deleted field set should be removed from the list but nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/1817207/81872614-1e537480-958b-11ea-8c09-e26ce416acbd.png)

**Comment by sourabhmatolia** [comment]
Hello @ZiadJ 

Issue created above is fixed and released in Buddyboss Platform v1.4.7.

**Find plugin v1.4.7 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-7/

Please update the plugin to see the latest changes.

Thanks
