### ISSUE TITLE
"src" folder is missing.

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#899]
**Describe the bug**
"src" folder is missing from the BuddyBoss Platform plugin folder. I am not really sure about the structure. Copying the email content,

Putting the "src" thing to one side (as that may actually not be an issue) ...

Compare the following:

https://bb.erikdslater.com/wp-content/plugins/buddyboss-platform/bp-activity/css/mentions.min.css?ver=1.3.4 [NOT FOUND]
vs
https://demos.buddyboss.com/online-communities/wp-content/plugins/buddyboss-platform/bp-activity/css/mentions.min.css?ver=1.3.4 [OK]

And:

https://bb.erikdslater.com/wp-content/plugins/buddyboss-platform/bp-activity/js/mentions.min.js?ver=1.3.4 [NOT FOUND]
vs
https://demos.buddyboss.com/online-communities/wp-content/plugins/buddyboss-platform/bp-activity/js/mentions.min.js?ver=1.3.4 [OK]

I'm now wondering ...

Should the CSS and JS files be coming from "/buddyboss-platform/bp-core/" rather than "/buddyboss-platform/bp-activity/"?

**Screenshots**
https://share.getcloudapp.com/12uyQvw9

**Support ticket links**
https://secure.helpscout.net/conversation/1160721546/72807/

**Comment by mehulkaklotar** [comment]
@archanabb this is fixed in latest dev branch. closing.
