### ISSUE TITLE
Maintenance mode 'Countdown' time units can not be translated.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#901]
**Describe the bug**
The Maintenance mode 'Countdown' units can not be translated.

**To Reproduce**
1. Go to 'BuddyBoss > Theme options > Maintenance mode 
2. Enable it and enable the 'countdown'. 
3. Log out of the website to see the issue.

**Expected behavior**
TRANSLATABLE

**Screenshots**
https://prnt.sc/sghv5k

**Support ticket links**
https://secure.helpscout.net/conversation/1140460465/69444?folderId=3701249

**Comment by janakkaneriya007** [comment]
It's a theme issue: https://github.com/buddyboss/buddyboss-theme/issues/667
