### ISSUE TITLE
All Updates tab does not include the activities from private groups

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#905]
**Describe the bug**
All Updates tab in the sitewide activity does not include the activities from private groups

**To Reproduce**
1. Create a private group
2. Post an activity in the private group
3. Go to the sitewide activity, in "All Updates" you cannot see the post in the private groups, but you can see it in the "Group" tab only.

**Expected behavior**
"All Updates" tab should also include the private group activities

**Screencast**
https://drive.google.com/file/d/1I9NeaJPsa4FQAlwZVWY8L9gemHlhvfaX/view

**Screenshots**
![private](https://user-images.githubusercontent.com/58522498/81980886-039fff00-9662-11ea-94d3-35a0d25baa32.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1156009103/71971?folderId=3709080

**Comment by manishpatolia** [comment]
@ayron-paul 
It won't include updates from private groups in the All Updates tab, that is not possible.
it will only show in the group's tab if groups are private.
Please confirm this with @mehulkaklotar

**Comment by ayron-paul** [comment]
Hi @manishpatolia, please check the internal note of this ticket, I reattached the conversation provided by Tier 1, Mike confirmed that it is a bug - https://secure.helpscout.net/conversation/1156009103/71971

**Comment by manishpatolia** [comment]
@ayron-paul Yes, I saw that not and I discussed with Mehul about that.
That is not possible to include an update from a private group.

Please confirm with @mehulkaklotar.

**Comment by ayron-paul** [comment]
Hi @manishpatolia @mehulkaklotar, may we know the reason why it is not possible so we can explain it to the customer? Thanks

**Comment by mehulkaklotar** [comment]
This will be fixed in this PR https://github.com/buddyboss/buddyboss-platform/pull/1007
