### ISSUE TITLE
Items in the repeating field set cannot be deleted

### ISSUE THREAD

**Issue by ZiadJ** [buddyboss/buddyboss-platform#907]
**To Reproduce**
1. Create a repeating field set with a field of type text
2. Add two field sets to the list
4. Click on the delete button for both of them and save the changes

**Expected behavior**
The deleted field sets should be removed from the list but they show up again after submit

**Comment by ZiadJ** [comment]
Note that this differs from issue #902 that happens on the client side in the sense that the items do get deleted on the client side but then show up again after submit

**Comment by eisenwasser** [comment]
@ZiadJ Thanks, we will look into it.

@chetansatasiya Is this already fixed in our next upcoming release? I remember seeing something similar to this.

**Comment by chetansatasiya** [comment]
@ZiadJ Can you add this patch https://github.com/buddyboss/buddyboss-platform/pull/1040 to your site and see this issue is persisting or not?
