### ISSUE TITLE
Messages and Notifications to SMS

### ISSUE THREAD

**Issue by tonymeltone** [buddyboss/buddyboss-platform#918]
I would like to see the ability to provide notification to users via SMS messaging.  

For younger community members (say under 25 years old) email correspondence is "not a thing".  Their email inbox is the last place they go for communication.  In contrast, email is still relied on by many other personas.

While the REST API should greatly assist in the development of mobile applications, adding SMS functionality to the platform would go a long way in the mobile realm.

Here are my start on requirements for text communication between members:

As a member, I would like to receive a text message alert via my cell phone number when I receive a new message in BuddyBoss.  It should include the following information in the text message as a minimum:
- Site name
- Sender name 
- URL link to recipient's message page in BuddyBoss
https://www.sitename.com/members/username/messages/

As a member, I would like to receive a text message alert via my cell phone number when I receive a new notification in BuddyBoss.  It should include the following information as minimum:
- Notification type
- Sender or group name
- Notification text if applicable
- Link to recipient's notification page
https://www.sitename.com/members/username/notifications/

As a member, I would like the ability to control whether I receive text alerts when I receive a message in BuddyBoss (on or off) in the Email settings (rename to Email & Text Settings)

As a member, I would like the ability to control whether I receive text alerts of a BuddyBoss notification. (on or off) in the Email settings.

As a system administrator, I would like to be able to send text messages without asking the user to specify the carrier (AT&T, Verizon etc.)

As a system administrator, I would like to send text messages using existing SMS sending services.  I would specifically like to integrate with Amazon's SNS service.   

As a system administrator, I would like to be able to turn on or off the use of SMS alerts for either messages or notifications or both.

As an administrator, I would like to avoid installing a plugin for this functionality.

**Comment by marienel21** [comment]
Hi @tonymeltone,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team
