### ISSUE TITLE
Notification count issue. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#922]
**Describe the bug**
Message notification count does not disappear even when you read the message. You have to click on the notification to make it disappear. 

**To Reproduce**
1. Go to user > profile > messages
2. Click on the unread message
3. check the message notification icon on the top header
4. See error: it will still show the count for unread message

**Expected behavior**
The count should be reduced if the messages are read. 

**Screenshots**
- https://www.loom.com/share/65e759531b4f47ccb7e57c062f975059

**Support ticket links**
- https://secure.helpscout.net/conversation/1159617597/72604/
- https://secure.helpscout.net/conversation/1157649807/72283/

**Comment by mehulkaklotar** [comment]
@archanabb this will be fixed in buddyboss theme next release. https://github.com/buddyboss/buddyboss-theme/pull/695
