### ISSUE TITLE
BP Auto Group Join plugin is not working with the platform plugin.

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#924]
**Describe the bug**
BP Auto Group Join plugin is not working with the platform plugin.

**To Reproduce**
1. Install and Setup the BP Auto Group Join plugin
2. Check the groups
3. No user joins automatically (existing user/new user both)

**Expected behavior**
It should work without any issue just like it works with the BP plugin. 

**Support ticket links**
- https://secure.helpscout.net/conversation/1171037047/74392/

**Comment by chetansatasiya** [comment]
@archanabb I am closing the issue because it's already in built in platform you don't need this plugin anymore.

**Comment by archanabb** [comment]
I checked this thoroughly, we don't have this feature built-in in the platform plugin.

**Comment by jrbuddyboss** [comment]
Related Ticket:
https://secure.helpscout.net/conversation/1296962337/101364/

**Comment by janakkaneriya007** [comment]
@jrbuddyboss @ankitguptaindia 
Fixed the issue with the auto group joining and shared with internal team to review.

**Comment by janakkaneriya007** [comment]
@sourabhmatolia 

The issue has been fixed with the BP Auto Group Join plugin and I had sent it for review to @mehulkaklotar  and he has approved it and @ankitguptaindia can confirm after he tests it that the issue is fixed.

**Comment by christinabbsupport** [comment]
https://secure.helpscout.net/conversation/1315397689/104298?folderId=3701264

**Comment by ankitguptaindia** [comment]
This is Live now with fixes. https://wordpress.org/plugins/bp-auto-group-join/


Closing this issue. 

@sourabhmatolia  @janakkaneriya007 @chetansatasiya
