### ISSUE TITLE
Products added on WC Vendors Pro are not shown in feed

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#928]
**Describe the bug**
Products added in the frontend via WC vendors pro are not added in activity feed. Products added in the backend are shown.

**To Reproduce**
1. Setup Woocommerce, WC Vendors and WC Vendor Pro
2. Enable Products posting on BuddyBoss > Settings > Activity > Custom Posts
3. Go to frontend, and as vendor, try to post a product, this is not showing on the feed

**Expected behavior**
adding products in backend or frontend should be showing in the feed

**Screenshots**
https://drive.google.com/file/d/1tObwvOANLnsUq9iwZtOMnaygrHIn3Znw/view

**Support ticket links**
https://secure.helpscout.net/conversation/1173921788/74809?folderId=3709081

**Comment by Anve-sri** [comment]
@chetansatasiya is this PR https://github.com/buddyboss/buddyboss-platform/pull/995 related to this issue ?
