### ISSUE TITLE
Call to sanitize_file_name( $displayed_user->id ) throwing an error

### ISSUE THREAD

**Issue by erika0530** [buddyboss/buddyboss-platform#929]
**Describe the bug**
In bp-members-template.php around line 1407 you are calling sanitize_file_name( $displayed_user->id ) and passing the user id, which is an integer and causes an error when sanitize_file_name() passes that value to seems_utf8( $filename ).

This is happening in more places too...

sanitize_file_name() called at [/var/www/html/goodliving-com/wp/wp-content/plugins/buddyboss-platform/bp-members/classes/class-bp-members-theme-compat.php:176]

sanitize_file_name() called at [/var/www/html/goodliving-com/wp/wp-content/plugins/buddyboss-platform/bp-templates/bp-nouveau/includes/members/functions.php:265]

sanitize_file_name() called at [/var/www/html/goodliving-com/wp/wp-content/plugins/buddyboss-platform/bp-members/classes/class-bp-members-theme-compat.php:176]

It's happening with the current WP version under PHP 7.4.4

**To Reproduce**

This is already technical. I can't provide steps to reproduce the issue.

**Expected behavior**

This is already technical. I can't provide expected behavior for this.

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1172002089/0/?folderId=3701271

**Comment by chetansatasiya** [comment]
@erika0530 This is fixed already in https://www.buddyboss.com/resources/buddyboss-platform-releases/1-3-5/
