### ISSUE TITLE
Search results page displayed blank when the SEOPress plugin is active. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#930]
**Describe the bug**
Search results page displayed blank when the SEOPress plugin is active. 

**To Reproduce**
1. Activate the SEOPress plugin
2. Search something on the frontend
3. See error

**Expected behavior**
it should work without any issue as mentioned here https://www.buddyboss.com/integrations/seopress/. 

**Screenshots**
- https://i.imgur.com/CKO2k2q.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1164447532/73402/

**Comment by KartikSuthar** [comment]
@archanabb, I have checked for the issue, and its from SEOPress plugin.
When you disable "SOCIAL NETWORKS" from plugin it will work. http://prntscr.com/tdctwd
OR you can disable "Facebook Open Graph" and "Twitter card".
http://prntscr.com/tdctnn
http://prntscr.com/tdcsnl

Please check with the SEOPress.
