### ISSUE TITLE
Inconsistent output of Site title with special characters on email

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#933]
**Describe the bug**
When BuddyBoss Platform is activated and you input special characters in the Site Title.
The characters in the email is showing inconsistently when a user receives an email from his registration

**To Reproduce**
1. In Settings > General > Site Title, add special characters "Femnøise àèîôû"
2. Register as a user with working email address and view email address
3. Change the Site Title to Femnøise
4. Register again and view email address

**Expected behavior**
Special characters must be the same input and output

**Screenshots**
![spec-char](https://user-images.githubusercontent.com/58522224/82823525-525b5d80-9eda-11ea-8c41-2139dc158b23.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1170168393/74257?folderId=3701258

**Comment by kishanjasani** [comment]
Hi @emmanoctaviano, I validated this issue on Gmail. But getting a proper response on Yahoo mail.
![screenshot-mail yahoo com-2021 08 05-16_37_42](https://user-images.githubusercontent.com/25550562/128357938-3e48b7a3-5f42-4303-b64f-b5aa50636593.png)

This is not an issue from buddy boss. You can check it by disabling the BB Platform and all other plugins. You will also get this kind of Inconsistent output. So, It's from WordPress. 

To reproduce it, You can change the site title to `Femnøise àèîôû`. Now try to reset your password for a User who uses Gmail.

**Comment by kishanjasani** [comment]
https://core.trac.wordpress.org/ticket/53885
