### ISSUE TITLE
The avatar in {{{member.card}}} email token is not showing in Outlook

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#934]
**Describe the bug**
The avatar in {{{member.card}}} email token is not showing in Outlook, you may refer on the following email templates:

- New request to connect from
- accepted your request to connect

**To Reproduce**
1. Try to use {{{member.card}}} token on any email templates
2. Check the notification email using Microsoft Outlook application

**Expected behavior**
The avatar should show even using the Outlook application

**Screenshots**
![outlook1](https://user-images.githubusercontent.com/58522498/82832113-cd2d7400-9eec-11ea-9558-e1fa9b6335ae.png)
![outlook2](https://user-images.githubusercontent.com/58522498/82832114-ce5ea100-9eec-11ea-9c0e-686cc7ca93b4.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1162742659/73145?

**Comment by mahedihasannoman** [comment]
https://secure.helpscout.net/conversation/1517840800/143005?folderId=3510499

**Comment by johnlorenzbb** [comment]
Follow up: https://secure.helpscout.net/conversation/1567390231/152485?folderId=4516041

**Comment by furqanbb** [comment]
https://secure.helpscout.net/conversation/1620445922/162170

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1681056969/171509/
