### ISSUE TITLE
Notice/warning is thrown on the Group > Course page when BuddyPress GDPR plugin is active. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#938]
**Describe the bug**
Notice is thrown on the Group > Course page when BuddyPress GDPR plugin is active. 

Notice: Undefined variable: lesson_count in /app/public/wp-content/plugins/buddyboss-platform/bp-integrations/learndash/templates/buddypress/groups/single/courses-loop.php on line 150 Warning: sizeof(): Parameter must be an array or an object that implements Countable in /app/public/wp-content/plugins/buddyboss-platform/bp-integrations/learndash/templates/buddypress/groups/single/courses-loop.php on line 150

**To Reproduce**
1. Install and activate BuddyPress GDPR plugin
2. Open group which has more than 2 courses assigned to it
3. See error

**Expected behavior**
It should work without any issue. 

**Screenshots**
- https://i.imgur.com/ckyE5v3.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1173463454/74741/

**Comment by manishpatolia** [comment]
@archanabb I have checked, No issue with the GDPR plugin.
this notice/warning issue will be solved with #970
https://github.com/buddyboss/buddyboss-platform/issues/970

**Comment by chetansatasiya** [comment]
Closing as this fixed in https://github.com/buddyboss/buddyboss-platform/issues/970
