### ISSUE TITLE
"reinstall emails" link brings me to "not allowed" page

### ISSUE THREAD

**Issue by KaloyanNaumov** [buddyboss/buddyboss-platform#939]
**Describe the bug**
In the WP Admin -> BuddyBoss -> Emails page, there is a message on top:
`Are these emails not written in your site's language? Go to BuddyBoss Tools and try the "reinstall emails" tool.`

Clicking the link brings me to $SITE_URL/wp-admin/tools.php?page=bp-tools
And I get: “Sorry, you are not allowed to access this page”

The feature works through the admin.php handler, not the tools.php.

**To Reproduce**
1. Go to WP Admin -> BuddyBoss -> Emails 
2. Click on "try the "reinstall emails" tool" link
3. The browser opens new window
4. See error “Sorry, you are not allowed to access this page”

**Expected behavior**
It’s better to update the link to bring us to:
$SITE_URL/wp-admin/admin.php?page=bp-repair-community&tab=bp-repair-community
There is a checkbox to re-populate the emails there.

It's possible the issue to be specific to my WP installation. I am reading such things happen. The recommended solution was to disable all plugins and re-enable them, blah-blah. I've invested many hours and it didn't work out well.

Changing link from tools.php to the admin.php would likely works great for many.

**Screenshots**
N/A

**Support ticket links**
I see the ticket as #75108 in the my-account area. 
https://www.buddyboss.com/my-account/?conversation_id=1175955810

**Comment by eisenwasser** [comment]
@KaloyanNaumov Thanks, we will look into it

**Comment by sourabhmatolia** [comment]
Hello @KaloyanNaumov 

Issue created above is fixed and released in Buddyboss Platform v1.4.7.

**Find plugin v1.4.7 release notes here:**
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-7/

Please update the plugin to see the latest changes.

Thanks
