### ISSUE TITLE
Pagination issue after Profile Type filter on Member directory

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#940]
**Describe the bug**
In Members directory, after filtering a Profile Type with more than 20 members (to show pagination), the second page does not show the filtered members correctly. It will show other Profile Types as well

**To Reproduce**
1. Create sample Profile Types (e.g. Profile Type 1, Profile Type 2) and enable the Display this profile type in "Types" filter in Members Directory
2. Create 23 or more members (21 for Profile Type 1, the rest Profile Type 2)
3. On Members page, filter Profile Type 1, on 1st page this shows correctly
4. Click on the pagination for the 2nd page, this will show all Members

**Expected behavior**
When clicking the pagination, this must show only the Profile Type 1.
In the screencast, only 21 members are assigned to Profile Type 1 but after clicking the 2nd page of pagination, this shows 24 members.

**Screenshots**
https://drive.google.com/open?id=1y77RVIxpNBAOQfE_sfrfolwvVRhw0td5

**Support ticket links**
https://secure.helpscout.net/conversation/1178201701/75398?folderId=3701258

**Comment by ayron-paul** [comment]
https://secure.helpscout.net/conversation/1198685632/78447/
