### ISSUE TITLE
Enable Sites Directory on Multisite

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#942]
**Describe the bug**
On Multisite fresh install, sometime the "Sites Directory" is enabled, sometime not

**Expected behavior**
This must be enabled on every installation of BuddyBoss Platform/Theme setup

**Screenshots**
![component](https://user-images.githubusercontent.com/58522224/83182472-fbaf8700-a158-11ea-8977-afedd8c0d64c.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1161975036/73029?folderId=3701258

**Jira issue** : [PROD-947]

[PROD-947]: https://buddyboss.atlassian.net/browse/PROD-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by emmanoctaviano** [comment]
@chetansatasiya this issue happens randomly. when users install BuddyBoss Platform on a Multisite, sometimes the Site Directory is enabled and sometime not.

**Comment by emmanoctaviano** [comment]
similar issue https://github.com/buddyboss/buddyboss-platform/issues/974

**Comment by mehulkaklotar** [comment]
@emmanoctaviano we have removed the site directory from platform the very beginning.

**Comment by Dreamsync** [comment]
Please support this feature. 

While I understand that Buddyboss isn't (yet) geared for multisite installs, one of the core features of Buddypress is how it works with multisite installs. I am setting up multisite networks, with Buddyboss as the network hub, and it is crucial that I'm able to aggregate network-wide updates (posts, comments, etc) on the main BP site.

The way Buddypress was integrated into multisite allows you to create social blogging networks.

Bring it back! 👍

**Comment by sourabhmatolia** [comment]
@Dreamsync 

We will work on Multi-Site support soon. Thanks for showing interest.
