### ISSUE TITLE
Forums - merge in security vulnerability patches from bbPress 2.6.5

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#943]
**Describe the bug**
bbPress 2.6.5 was released May 28:
https://bbpress.org/blog/2020/05/bbpress-2-6-5-is-out/?fbclid=IwAR1GHKcar34fNqOVmIMNU3fBbgd8mkEU_7e-5DwCjuvPdfDqibh71PI3Rb0

It includes a security release. We need to review the changes and see if any of the vulnerabilities exist in Platform, if so, patch them.

**Support ticket links**
User "Raj Siva-Rajah" posted on Facebook.

**Comment by AiratHalitov** [comment]
@eisenwasser 
Could you tell when next version (1.3.5) will be released?

**Comment by eisenwasser** [comment]
@AiratHalitov 

After this weekend, not sure which day but some time this coming week.
