### ISSUE TITLE
Register screen, password should get an "eye" to toggle it on and off.

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#944]
**Describe the bug**
On the login screen there is an eye to toggle it on/off - https://prnt.sc/sptj2v
But our Register screen does not - https://prnt.sc/sptja2

**Expected behavior**
We should add the "eye" on the password field/s on register screen.
If the user enabled to confirm password, the confirm field needs the eye also.
By default you see *** but when you click the eye you see the text entered.

Make sure to do the same in Profile > Account > Login Information.
It also has password fields with the same issue.

**Screenshots**
https://prnt.sc/sptj2v
https://prnt.sc/sptja2

**Support ticket links**
Reported on Youtube video:
https://www.youtube.com/watch?v=p196OOrAF-A&lc=UgxxxsCqwh8GxteWxot4AaABAg&feature=em-comments

**Comment by sourabhmatolia** [comment]
@sagarjadhav 

As Michael mentioned in the issue description, provide an eye icon for password fields on Profile > Account > Login Information screen as well.
Not working here: https://prnt.sc/tnopcu

Please fix. Thanks.
