### ISSUE TITLE
Lessons count shows 0 in Groups view

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#952]
**Describe the bug**
Lesson count show 0 lessons on Groups view. This is when you enable the Learndash and BuddyBoss Social Groups sync and add courses to a certain group

**To Reproduce**
Issue can be replicated on demo
1. Enable LearnDash and BuddyBoss Groups integration in BuddyBoss > Integrations > LearnDash
2. Create a Test Group 
3. Add two or more courses to Test Group
4. view in frontend (make sure you are an organizer/member), e.g: /groups/test-group-1/courses/

**Expected behavior**
Lessons count show display correctly

**Screenshots**
![lessoncount](https://user-images.githubusercontent.com/58522224/83350304-dd6ea480-a36d-11ea-8bba-07e6ca7c0c54.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1177453722/75295

**Comment by manishpatolia** [comment]
@emmanoctaviano This issue solved with #970

**Comment by chetansatasiya** [comment]
Closing this as this issue fixed the issue https://github.com/buddyboss/buddyboss-platform/issues/970
