### ISSUE TITLE
String "Invited by" could not be translated

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#954]
**Describe the bug**
String "Invited by" could not be translated when a member is invited to a Group

**To Reproduce**
1. As an Admin, Invite a User to a Group
2. Login to the User account and view Group invitation (/members/user/groups/invites/)
3. "Invited by" string could not be translated

**Screenshots**
![invitedby1](https://user-images.githubusercontent.com/58522224/83351647-7aced600-a378-11ea-9346-971b74545ef8.JPG)
![invitedby2](https://user-images.githubusercontent.com/58522224/83351651-7f938a00-a378-11ea-9cf0-486cd2a25a6b.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1178045872/75372

**Comment by manishpatolia** [comment]
@emmanoctaviano the above string will come from the theme because the page is overwritten so it also should change from the theme strings.

But I have seen for above there have date issue and also not showing the invited user name.
So for that, I will solve and create new pr for it.
