### ISSUE TITLE
Group invites Invited By showing wrong date and no user is shown

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#955]
**Describe the bug**
After inviting a user to a group, the user will receive a notification for this. 
The "Invited by" notification shows wrong date and no user is shown.

**To Reproduce**
1. As an Admin, Invite a User to a Group
2. Login to the User account and view Group invitation (/members/user/groups/invites/)
3. See error, "Invited by" has no user and it is showing the wrong date

**Expected behavior**
Invited by string must show the user who came this invitation from and it must show the correct date

**Screenshots**
![invitedate](https://user-images.githubusercontent.com/58522224/83352141-29c0e100-a37c-11ea-9782-3f97d56c8dfe.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1178045872/75372

**Comment by manishpatolia** [comment]
@emmanoctaviano This issue fixed in issue #954
