### ISSUE TITLE
Incorrect spelling of tabs for Social Articles plugin

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#956]
**Describe the bug**
Social Articles plugin are showing incorrect spelling when Social Articles plugin is activated on BuddyBoss Platform

**To Reproduce**
1. Install Social Articles plugin https://www.buddyboss.com/integrations/social-articles/
2. View user Social Articles on user profile /members/users/articles/
3. Click on Articles tab

**Expected behavior**
This is happening if it is activated on BuddyBoss Platform, tested on BuddyPress and spelling is correct

**Screenshots**
![Soc-A](https://user-images.githubusercontent.com/58522224/83353558-06029880-a386-11ea-9075-b809617708ad.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1179384899/75534

**Comment by manishpatolia** [comment]
@emmanoctaviano I have checked this and I seem this issue with Social Articles plugin.
I have checked with BuddyPress and the default theme and not working properly.
See Proof:
https://prnt.sc/sszt8u

**Comment by chetansatasiya** [comment]
@manishpatolia @emmanoctaviano if this issue is related to extenal plugin and if there is nothing to do here then this issue should be closed here.

**Comment by manishpatolia** [comment]
@chetansatasiya @emmanoctaviano I'm closing this issue because this is an external issue.
