### ISSUE TITLE
"Edit Group Discussion" Text is not translatable

### ISSUE THREAD

**Issue by buntybuddyboss** [buddyboss/buddyboss-platform#958]
**Describe the bug**
"Edit Group Discussion" text in adminbar is not translatable.

**Expected behavior**
Text should be written using WP "__" function

**Screenshots**
http://prntscr.com/srku9c

Code LINE(80): https://github.com/buddyboss/buddyboss-platform/blob/dev/src/bp-groups/bp-groups-adminbar.php#L80

**Comment by chetansatasiya** [comment]
@buntybuddyboss This issue fixed in upcoming release.

**Comment by buntybuddyboss** [comment]
Thanks @chetansatasiya for quick fix
