### ISSUE TITLE
BP Edit Activity plugin is not working properly with the platform plugin. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#959]
**Describe the bug**
BP Edit Activity plugin is not working properly with the platform plugin. Not able to edit the activities or replies. 

Please watch the screencast to know more about the issue. 

**To Reproduce**
1. Install and activate the BP Edit Activity page
2. Open the activity page
3. Try editing an activity or reply

**Expected behavior**
It should work without any issue. 

**Screenshots**
- https://www.loom.com/share/aacaae7e14bc46eca709354f859cf266

**Support ticket links**
- https://secure.helpscout.net/conversation/1180191741/75609?folderId=3701247

**Comment by dipskakadiya** [comment]
@imehedidev We release Edit activity feature in the platform recently so I don't think BP Edit Activity plugin needed anymore with the platform.
