### ISSUE TITLE
Enhancement - Replace Comment System to Activity Block

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#963]
**Describe the solution you'd like**
https://www.loom.com/share/ec71af7b2bcb4e1bba46ab234d87ee3c

The core concept is to allow any existing WordPress comment section to be replaced with Activity Feed and all activity features. Existing comments would be converted into activity. 

**Jira issue** : [PROD-946]

[PROD-946]: https://buddyboss.atlassian.net/browse/PROD-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AiratHalitov** [comment]
I would be great if comments will be updating in real time without page reloading.

**Comment by eisenwasser** [comment]
Activity is able to do that. Comments are using default WordPress comments system. If we replace comments with activity then it will be able to have real time updating.

**Comment by King-Ding** [comment]
This would be an incredibly revolutionary feature Michael. Would love to see this implemented sometime!

**Comment by eisenwasser** [comment]
@King-Ding Thanks for the feedback.

I agree, this would be super cool. It's a complex project, we will come to it eventually.
