### ISSUE TITLE
Private messages are deleted as soon as you click on the send button. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#968]
**Describe the bug**
Private messages are deleted as soon as you click on the send button. Please watch the screencast to understand the issue.

I could not replicate it on my local. This is a user-specific issue. 

**To Reproduce**
1. Go to profile > messages
2. Compose a message and send
3. See error

**Expected behavior**
It should work without any issue. 

**Screenshots**
- https://www.loom.com/share/e37bff9d5df8434f908d79da6c8427b3

**Support ticket links**
- https://secure.helpscout.net/conversation/1169453029/74175?folderId=3701247

**Comment by archanabb** [comment]
Hello @KartikSuthar can you please check this?

**Comment by KartikSuthar** [comment]
@archanabb Will check and update you.
