### ISSUE TITLE
Posts/updates from private and hidden groups are not showing up on the All Updates tab.

### ISSUE THREAD

**Issue by gomezlee** [buddyboss/buddyboss-platform#971]
As stated on this documentation https://www.buddyboss.com/resources/docs/components/activity/activity-tabs/, all posts/updates from groups (public, private, hidden) should be posted/consolidated on the All Updates tab but only posts from public groups are showing up.

**To Reproduce**
Create a test post on a public and private group. Both posts will show up on the Groups tab but only the post from public group will be posted on the All Updates tab. 

**Expected behavior**
If the user can see those updates in their Groups tab, they should see them in All updates tab also.

**Screenshots**
![image](https://user-images.githubusercontent.com/61354756/83578467-71589000-a569-11ea-9d17-f3f49ab03f95.png)
![image](https://user-images.githubusercontent.com/61354756/83578485-7d445200-a569-11ea-8215-8810557aff74.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1177758555/75339?folderId=3701272

**Comment by mehulkaklotar** [comment]
This will be fixed in this changes https://github.com/buddyboss/buddyboss-platform/tree/fix/document-fix
