### ISSUE TITLE
PHP 7.4 support issues. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#973]
**Describe the bug**

Every single URL would not load on the website except for the homepage.
All URLS resulted in a 502 error. Once turning off php 7.4 and reverting back to 7.2 it solved this. But with php 7.4 active we cannot keep the Buddyboss Platform plugin active or it breaks the website.
ALSO...
Last night I upgraded another website on WP Engine (on a totally different WP Engine account and hosted on a different WP Engine server) and had the same problem. We moved from Social Learner to Buddyboss theme and platform and after activation, a similar issue... tons of 502 errors all over the website.
We disabled the Buddyboss Platform plugin, then reverted back to php 7.2 and the errors went away.
Something with WP Engine and Buddyboss Platform plugin running on php 7.4 breaks the website every time we have attempted to run it with PHP 7.4 on WP Engine.

**Support ticket links**
https://secure.helpscout.net/conversation/1176641443/75182?folderId=3701249

**Comment by eisenwasser** [comment]
This issue is specific to WP Engine, and we need to see what custom thing WP Engine is doing in their configuration.

All our local dev sites and our public demos are using PHP 7.4 without issue. It is the primary PHP version we all test against.

**Comment by christopherbigelow** [comment]
Was there a fix found for this? We are experiencing the exact same issues on WP Engine... we cannot run Buddyboss on 7.4 and also with Learndash being activated at the same time as Buddyboss, takes down the entire website with 502 errors.

Support Ticket Link:
https://www.buddyboss.com/my-account/?conversation_id=1176641443

**Comment by eisenwasser** [comment]
@christopherbigelow 
This was fixed in this PR https://github.com/buddyboss/buddyboss-platform/pull/1007
And included in a release back in June.

Which version of BB Platform are you running?

@chetansatasiya Can you look at this again?

**Comment by christopherbigelow** [comment]
Hello @eisenwasser and thank you so much for getting back to me!! 

We are running version Buddyboss Platform Version 1.4.6 and Buddyboss Platform Pro Version 1.0.0 on production and hosting on WP Engine. We cannot upgrade the plugins (I am aware there are newer versions) on the website or the entire website goes into instant 502 error. We are also stuck on PHP 7.2 as if we upgrade the website and have Buddyboss plugins active, the website also goes into 502 error. 

I have provided access to our staging website in the ticket I have referenced. 

We have also noticed on that staging website that when the new versions of the Buddyboss plugins are active and we activate the Learndash plugin, then the entire website also instantly goes to 502 error. 

Our staging website is running php 7.4 and has both Buddyboss Platform plugins installed. If you try and activate Learndash it instantly 502 errors the whole website. WP Engine tier 2 support and Jeremy from Learndash have both extensively looked things over and both come to the conclusion that this is something with a segfault and Buddyboss code running on WP Engine.

Support Ticket Link:
https://www.buddyboss.com/my-account/?conversation_id=1176641443

The worst part of this is that WP Engine is forcing all websites off of php 7.2 on Sept 1, 2020 so time is of the essence as we cannot upgrade our website to 7.4 and cannot update the Buddyboss plugins.

If you need anything else from me, please let me know in that ticket and I will get it for you right away. THANK YOU!!! 👍

**Comment by christopherbigelow** [comment]
@eisenwasser we have the latest versions on staging... The latest versions on staging are Buddyboss Platform Version 1.4.8 / Buddyboss Platform Pro Version 1.0.2 and these are still causing issues. If you activate Learndash on our staging you will see that it instantly takes website down with 502 errors. If you disable Buddyboss plugins and activate Learndash and then try and activate the Buddyboss plugins, the same thing happens and it takes down the website with 502 errors.

You can login to our staging and I have provided SFTP access in that ticket so @chetansatasiya can take a look. There is a file in the root of the staging website called .strace and this contains the segment fault error that WP Engine has discovered.

Support Ticket Link:
https://www.buddyboss.com/my-account/?conversation_id=1176641443

**Comment by chetansatasiya** [comment]
@christopherbigelow I am looking and I replied their.

**Comment by christopherbigelow** [comment]
@chetansatasiya please review this ticket. https://www.buddyboss.com/my-account/?conversation_id=1176641443

Thank you! 👍
