### ISSUE TITLE
Multisite network issue: Sites tab is not visible in the profile menu and cannot access "my sites" on sites page

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#974]
**Describe the bug**
Multisite network issue: Sites tab is not visible in the profile menu and cannot access "my sites" on sites page.

I tried to replicate the issue but I did not get an option to set the "sites" page https://i.imgur.com/9ufCXZ1.jpg. 

**To Reproduce**
(Copy of the email)
1- The Main site doesn't show in the "Sites" profile tab and "My sites" in sites page for me and all users.
2- When a user joins a new site it doesn't show up for him in both tabs too (Register a new account and go to any other subsite, then click on "join this blog" from Join blog widget at the home page of the subsite) This subsite will not appear in your account in both tabs.
3- When I change the blog photo it doesn't change and keep displaying my profile photo on all sites (In my other sites it shows the blog photo on each blog)

**Expected behavior**
It should work without any issue. 

**Screenshots**
- 

**Support ticket links**
- https://secure.helpscout.net/conversation/1177522279/75310/

**Jira issue** : [PROD-945]

[PROD-945]: https://buddyboss.atlassian.net/browse/PROD-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mehulkaklotar** [comment]
@archanabb we have removed sites directory from platform from the very beginning.
