### ISSUE TITLE
User receives the notification of his own reply in the forums. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#980]
**Describe the bug**
User receives the notification of his own reply in the forums. Please check the screencast to understand the issue. 

**To Reproduce**
1. Go to Forum discussions  
2. create a reply
3. check the notification icon in the top header

**Expected behavior**
It should show the notifications received only from other users. 

**Screenshots**
- https://www.loom.com/share/d27c8fbb86154d90a68b518053add6ea

**Support ticket links**
- https://secure.helpscout.net/conversation/1182193743/75826?folderId=3709075

**Comment by manishpatolia** [comment]
@archanabb This issue solved below PR
https://github.com/buddyboss/buddyboss-platform/pull/861
