### ISSUE TITLE
Forums page not working when set as a Child page

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#981]
**Describe the bug**
Forums page not working when set as a Child page. Other BuddyBoss pages are working fine

**To Reproduce**
1. Go to Pages, set Forums as a Child page of any page
2. View on frontend (/sample-page/forums), this is showing as blank page
3. See error

**Expected behavior**
when set as a Child page, this should be working like other BuddyBoss Pages

**Screenshots**
https://drive.google.com/open?id=1_28uYh0Kmwi7hv_OTOQbLK-vgR7vq079

**Support ticket links**
https://secure.helpscout.net/conversation/1179982497/75589

**Comment by dipskakadiya** [comment]
https://github.com/buddyboss/buddyboss-platform/issues/700
