### ISSUE TITLE
Restrict Content pro CSV import issue

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#986]
**Describe the bug**
When trying to import CSV file from content pro tools >> Import a CSV. Import doesn't Work. Jquery Error in the console.
The CSV import works fine if the buddyboss platform is deactivated.

**To Reproduce**
1. Install Restrict Content Pro Plugin.
2. Go to Admin Dashboard >> Restrict Content Pro tools >> Import CSV
3. See error

**Expected behavior**
CSV should be imported successfully as it works without the BuddyBoss Platform.

**Screencasts**
This is with buddyboss deactivated, it works fine.
https://share.wpherc.com/36264440d727

This is with buddyboss active, it does not work:
http://share.wpherc.com/0706f499d696

**Support ticket links**
https://secure.helpscout.net/conversation/1129811829/67249/.

**Comment by kent-carlo** [comment]
@furqanbb I tested with the latest platform plugin and latest restrict content pro. It seems that there's no error now.

**Comment by furqanbb** [comment]
Seems working fine with the latest version.

**Comment by kent-carlo** [comment]
Thanks @furqanbb
