### ISSUE TITLE
Security issue with Documents

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#987]
**Describe the bug**
User can execute uploaded files and scripts. 
User can download malware code. Then find out a direct link to it, and then use this code in attacks on the site.

**To Reproduce**
1. Go to Documents page and upload js file with code "`alert('Hi!');`"
2. Go to activity feed and click to file. 
3. See alert "Hi!" 
4. Or click to file Documents page and see the same alert. 

**Expected behavior / Solution:**
- JS script shouldn't be executable.
- Files shouldn't be accessible for direct link. User shouldn't know or see direct link to file (see how it works in woocommece downloads).
- Files shouldn't be located in `/wp-content/uploads/` folder. It should be another folder, which can be hidden from search engines with using `robots.txt` file. For example `/wp-content/uploads/documents/` (Related #668)
- You may change default filename to random name (or name + salt). Original filename could be saved to DB. 

**Screenshots / GIF**
![bp-bug](https://user-images.githubusercontent.com/4050715/83878605-da9cf680-a755-11ea-9ad8-240106100cbc.gif)

**Configuration:**
- buddyboss-platform 1.4.0.2 
- buddyboss-theme 1.4.6 and 1.5.0
- WordPress 5.4.1

**Comment by eisenwasser** [comment]
@AiratHalitov 

Thanks much, we are taking this seriously and will provide updates to address these concerns.

**Comment by eisenwasser** [comment]
For this point:

>Files shouldn't be accessible for direct link. User shouldn't know or see direct link to file (see how it works in woocommece downloads).

The direct link is actually not exposed on the frontend currently.

**Comment by eisenwasser** [comment]
For this point:

>Files shouldn't be located in /wp-content/uploads/ folder. It should be another folder, which can be hidden from search engines with using robots.txt file. For example /wp-content/uploads/documents/ (Related #668)

We are creating out own bb_documents folder to upload to, and will add an .htaccess so its contents are publicly hidden. We can migrate existing doc uploads with a script.

For this point:

>JS script shouldn't be executable.

Agreed, we will fix this.

**Comment by AiratHalitov** [comment]
@eisenwasser 
> We are creating our own bb_documents folder to upload to, and will add an .htaccess so its contents are publicly hidden. We can migrate existing doc uploads with a script.

Good solution. 
There is a `.htaccess` file from [Wordfence](https://wordpress.org/plugins/wordfence/) which protect folder from code execution:
```
# BEGIN Wordfence code execution protection
<IfModule mod_php5.c>
php_flag engine 0
</IfModule>
<IfModule mod_php7.c>
php_flag engine 0
</IfModule>

AddHandler cgi-script .php .phtml .php3 .pl .py .jsp .asp .htm .shtml .sh .cgi
Options -ExecCGI
# END Wordfence code execution protection
```
Maybe you will add it or use it in your `.htaccess` file. 

---
> The direct link is actually not exposed on the frontend currently.

But they can know the link after clicking Download button. It will be better if download will be start automatically after clicking to the Download button. 
"download" attribute will be help:
`<a href="LINK_TO_FILE" download>`
Docs: https://www.w3schools.com/TAGS/att_a_download.asp

**Example:**
![bb-download](https://user-images.githubusercontent.com/4050715/83955132-28eeea00-a869-11ea-8d9a-5bf672b98353.gif)

---
>> JS script shouldn't be executable.

>Agreed, we will fix this.

Files should be open in a safe area. User can hide the script in any other type of file.

**Comment by eisenwasser** [comment]
Thanks!

**Comment by AiratHalitov** [comment]
@eisenwasser 
How to limit maximum size of uploaded file? 
I think that the platform should have a special setting for this.
I know how do it with using `php.ini` file, but it's not a good and easy solution.

**Comment by eisenwasser** [comment]
@AiratHalitov 

Most of the above is resolved in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-1/

- JS and other files cannot execute anymore in the browser
- NEW file uploads go into uploads/bb_documents/ folder
- uploads/bb_documents/ folder has .htaccess file inserted

We will add a migration script in a future update to move any previously uploaded documents (from past 2 days) into the bb_documents folder

"How to limit maximum size and number of uploaded files?"
I will reply in the other issue for this question.

**Comment by AiratHalitov** [comment]
Thanks everyone for quick response! 
v1.4.1 partially works well.

- _JS and other files cannot execute anymore in the browser_ - OK
- _NEW file uploads go into uploads/bb_documents/ folder_ - OK
- _uploads/bb_documents/ folder has .htaccess file inserted_ - OK

But there is an issue with file download. 

1) You forgot adding ["download" attribute](https://www.w3schools.com/TAGS/att_a_download.asp) for Download button (see my previous comment: https://github.com/buddyboss/buddyboss-platform/issues/987#issuecomment-640122770). 
Or does it need a buddyboss-theme update? (I don't think so, it look like a platform feature) 

2) `.htaccess` file don't allow download files from site. 
The problem with your line: 
`deny from all`
Without this line download will be working good. 
But without this line user can see and explore folder `test.site/wp-content/uploads/bb_documents/` in browser. 

For example it's `.htaccess` file from [wp-dbmanager](https://wordpress.org/plugins/wp-dbmanager/) plugin:
```
<Files ~ ".*\..*">
order allow,deny
deny from all
</Files>
```
But it didn't help either. ¯\\\_(ツ)\_/¯

Could you fix force download? 

**Example (GIF):**
![bb-docs-download-bug](https://user-images.githubusercontent.com/4050715/83980939-f7daec00-a932-11ea-8f5d-fab32b785bc2.gif)

**Comment by eisenwasser** [comment]
Thanks for this feedback.

We are planning a secondary security release this week with some more improvements. We will look into these items as well. We really wanted to push something fast that addressed the JS files being executable in the browser as that is a major problem.

**Comment by ExoGeek** [comment]
Here is my personal solution : 

```
/**
 * Use unique filename in order to improve security.
 *
 * @param $filename
 *
 * @return string
 */
if ( !function_exists( 'pf_sanitize_media_filename' ) ) {
	function pf_sanitize_media_filename( $filename ) {

		// Separate the filename into a name and extension.
		$ext = pathinfo( $filename, PATHINFO_EXTENSION );
		if ( $ext ) {
			$ext = '.' . strtolower( $ext );
		}

		//Create some random filename to avoid easy access
		//$temp_filename = wp_generate_password( 35, false, false );
		$temp_filename = wp_generate_uuid4();

		return $temp_filename . $ext;
	}
}

/**
 * @param $filename
 * @param $ext
 * @param $dir
 *
 * @return string
 */
if ( !function_exists( 'pf_sanitize_unique_media_filename' ) ) {
	function pf_sanitize_unique_media_filename( $filename, $ext, $dir ) {

		$name = pathinfo( $filename, PATHINFO_FILENAME );

		//If there's a duplicate name, wordpress adds "-1" at the end of the file.
		//If there's a duplicate filename generated by the pf_sanitize_media_filename, we call that function again to generate
		//another unique filename
		if ( preg_match( '/-[0-9]+$/', $name ) ) {
			do {
				$filename = pf_sanitize_media_filename( $filename );
			} while ( file_exists( $dir . "/$filename" ) );
		}

		return $filename;
	}
}

add_filter( 'sanitize_file_name', 'pf_sanitize_media_filename', 10, 1 );
add_filter( 'wp_unique_filename', 'pf_sanitize_unique_media_filename', 10, 3);
```

**Comment by eisenwasser** [comment]
@ExoGeek 

Thanks for posting this. 

@chetansatasiya Can you review?

**Comment by chetansatasiya** [comment]
> Here is my personal solution :
> 
> ```
> /**
>  * Use unique filename in order to improve security.
>  *
>  * @param $filename
>  *
>  * @return string
>  */
> if ( !function_exists( 'pf_sanitize_media_filename' ) ) {
> 	function pf_sanitize_media_filename( $filename ) {
> 
> 		// Separate the filename into a name and extension.
> 		$ext = pathinfo( $filename, PATHINFO_EXTENSION );
> 		if ( $ext ) {
> 			$ext = '.' . strtolower( $ext );
> 		}
> 
> 		//Create some random filename to avoid easy access
> 		//$temp_filename = wp_generate_password( 35, false, false );
> 		$temp_filename = wp_generate_uuid4();
> 
> 		return $temp_filename . $ext;
> 	}
> }
> 
> /**
>  * @param $filename
>  * @param $ext
>  * @param $dir
>  *
>  * @return string
>  */
> if ( !function_exists( 'pf_sanitize_unique_media_filename' ) ) {
> 	function pf_sanitize_unique_media_filename( $filename, $ext, $dir ) {
> 
> 		$name = pathinfo( $filename, PATHINFO_FILENAME );
> 
> 		//If there's a duplicate name, wordpress adds "-1" at the end of the file.
> 		//If there's a duplicate filename generated by the pf_sanitize_media_filename, we call that function again to generate
> 		//another unique filename
> 		if ( preg_match( '/-[0-9]+$/', $name ) ) {
> 			do {
> 				$filename = pf_sanitize_media_filename( $filename );
> 			} while ( file_exists( $dir . "/$filename" ) );
> 		}
> 
> 		return $filename;
> 	}
> }
> 
> add_filter( 'sanitize_file_name', 'pf_sanitize_media_filename', 10, 1 );
> add_filter( 'wp_unique_filename', 'pf_sanitize_unique_media_filename', 10, 3);
> ```

@ExoGeek What is the reason to do something like this? As we have already followed the WordPress File name/slug rules here and also we have take care of all security issues as well. Can you elloborate more in details please? Also we have a rename feature as well so this will not work with that and create a many issues.

CC @eisenwasser

**Comment by ExoGeek** [comment]
Hello @chetansatasiya 

To be honest, I haven't tested the code with BuddyBoss yet. But it worked well in BuddyPress (I used BuddyPress in the previous version of my project. Now, it's all BuddyBoss).

The reason of doing that is the following. In a social network (private or not), photos and documents are sensitive data. In Wordpress, all files are stored in `/wp-content/uploads/2020/09/` wich by default is world readable. If you know the filename of a media, it's quite easy to search for that media by using the url only (you only have to try every url with `https://localhost/wp-content/uploads/<year>/<month>/your-file.jpg`. 
With this method, you can access each and every media of your social network without any privacy concerns (but ok, you have to know the filename of the media).

BUT !! In a social media, users will upload photos took by their smartphone or their camera. It's then quite easy (for a hacker) to guess the filename of a photo because the filename is always formatted with the same pattern : 

- Android : date_999999.jpg
- Old camera : DCMI_date_count.jpg
- WhatsApp : IMG-date-WA9999.jpg
...

So, by modifying the filename of each and every media when they are uploaded, it's nearly impossible (see UUID collisions statistics) for a hacker to guess any of the filename stored in `/wp-content/uploads/` subfolders.

In fact, if you look at facebook image url, you will see that they have done the same thing.

`https://scontent.fbru2-1.fna.fbcdn.net/v/t1.0-9/10001416_10152258308549651_851378713_n.jpg?_nc_cat=107&_nc_sid=9267fe&_nc_ohc=6Ct0urWn4kgAX9W6dHW&_nc_ht=scontent.fbru2-1.fna&oh=e6779c3a68780c8f207b47e6e4ce5102&oe=5F76A6C6`

Regards,
ExoGeek

**Comment by chetansatasiya** [comment]
> Hello @chetansatasiya
> 
> To be honest, I haven't tested the code with BuddyBoss yet. But it worked well in BuddyPress (I used BuddyPress in the previous version of my project. Now, it's all BuddyBoss).
> 
> The reason of doing that is the following. In a social network (private or not), photos and documents are sensitive data. In Wordpress, all files are stored in `/wp-content/uploads/2020/09/` wich by default is world readable. If you know the filename of a media, it's quite easy to search for that media by using the url only (you only have to try every url with `https://localhost/wp-content/uploads/<year>/<month>/your-file.jpg`.
> With this method, you can access each and every media of your social network without any privacy concerns (but ok, you have to know the filename of the media).
> 
> BUT !! In a social media, users will upload photos took by their smartphone or their camera. It's then quite easy (for a hacker) to guess the filename of a photo because the filename is always formatted with the same pattern :
> 
> * Android : date_999999.jpg
> * Old camera : DCMI_date_count.jpg
> * WhatsApp : IMG-date-WA9999.jpg
>   ...
> 
> So, by modifying the filename of each and every media when they are uploaded, it's nearly impossible (see UUID collisions statistics) for a hacker to guess any of the filename stored in `/wp-content/uploads/` subfolders.
> 
> In fact, if you look at facebook image url, you will see that they have done the same thing.
> 
> `https://scontent.fbru2-1.fna.fbcdn.net/v/t1.0-9/10001416_10152258308549651_851378713_n.jpg?_nc_cat=107&_nc_sid=9267fe&_nc_ohc=6Ct0urWn4kgAX9W6dHW&_nc_ht=scontent.fbru2-1.fna&oh=e6779c3a68780c8f207b47e6e4ce5102&oe=5F76A6C6`
> 
> Regards,
> ExoGeek

@ExoGeek Totally agreed with you here about the all social media things. Right now in the platform for the Document we are stroing the document something like this `https://localhost/wp-content/uploads/**bb_documents**/<year>/<month>/your-file.jpg` but we have a `.htaccess` & `index.html` for both type of web server `Apache` & `nginx` so it will handle the security things. Even If try to access the document via URL like  `https://localhost/wp-content/uploads/bb_documents/<year>/<month>/your-file.jpg` you will not see the document OR download the document in platform. Same process will doing in a Media enhancement.

Let me know if you have more questions in this I would love to hear you.

CC @eisenwasser @sourabhmatolia

**Comment by ExoGeek** [comment]
Ok, I think I'm not in the right topic. In fact I haven't tested **BuddyBoss Document** functionality right now. My Concern was more about photos uploaded in **activity feed**.

For the moment, these uploaded medias (when you attach photos to your activity) are stored in `/wp-content/uploads/2020/09/` and then my comment above make sense.

Maybe you should create a topic to secure medias uploaded in activity feed ?

Regards

**Comment by chetansatasiya** [comment]
> Ok, I think I'm not in the right topic. In fact I haven't tested **BuddyBoss Document** functionality right now. My Concern was more about photos uploaded in **activity feed**.
> 
> For the moment, these uploaded medias (when you attach photos to your activity) are stored in `/wp-content/uploads/2020/09/` and then my comment above make sense.
> 
> Maybe you should create a topic to secure medias uploaded in activity feed ?
> 
> Regards

@ExoGeek We have already in planned to make those things for the media and it will be in future for sure.

**Comment by ExoGeek** [comment]
@chetansatasiya Do you plan to make it compatible with the great plugin https://deliciousbrains.com/wp-offload-media/ ? Or, even better, do you plan to have your own solution (to offload media to S3) ?

For your information, (in the previous version of my project, when I was using Buddypress) I do use that plugin to 

- Offload Medias to S3
- Use **AWS Signed URL** to secure even more the photos uploaded to the buddypress.
