### ISSUE TITLE
Icon to delete the cover image is loading slow in BP user blog plugin when used with the platform plugin.

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#990]
**Describe the bug**
Icon to delete the cover image is loading slow in BP user blog plugin when used with the platform plugin.

**To Reproduce**
1. Go to edit blog post on the front end
2. Click on edit cove image icon
3. See error

**Expected behavior**
The icon should load immediately. Because its slow load gives the impression that the icon is not available. 

**Screenshots**
https://i.imgur.com/n0pcj71.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1181017944/75705/

**Comment by sourabhmatolia** [comment]
@shohelbuddyboss 

Please take over. Thanks.

**Comment by shohelbuddyboss** [comment]
@sourabhmatolia @mehulkaklotar @ankitguptaindia 

- Fixed Adding a title requires users to click into the title field twice, 
- icon to delete the cover image is loading slow

https://trello.com/c/He1aEEZn/167-adding-a-title-requires-users-to-click-into-the-title-field-twice
https://github.com/buddyboss/buddyboss-platform/issues/990

branch `fix-title-twich-click`

Repository: https://buddyboss.git.beanstalkapp.com/buddypress-user-blog.git 

Please check this
