### ISSUE TITLE
Add a limits to the number of uploaded images to the activity feed

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#991]
**Is your feature request related to a problem? Please describe.**
User can upload a lot of images per one activity feed post. It can slow down the system and fill up memory quickly.
**Screenshot**
![image](https://user-images.githubusercontent.com/4050715/83955480-c8fa4280-a86c-11ea-9a7a-bcf0863bcd40.png)

**Describe the solution you'd like**
Add to the platform settings an ability to set the limits of the maximum number of uploaded images to the activity feed. 

![image](https://user-images.githubusercontent.com/4050715/83972526-0ce75900-a8fa-11ea-9883-4bc2b13943ee.png)

**Describe alternatives you've considered**
This solution is working in your [BuddyBoss Media](https://www.buddyboss.com/product/buddyboss-media/) plugin.

- buddyboss-platform 1.4.0.2

**Comment by chetansatasiya** [comment]
@AiratHalitov 

We are introducing below filters for the Media/Document file Size as well as chunk file limit in our upcoming release and then you will resrtict all the things.

**Media**

1. File Size Limit : `bp_media_file_upload_max_size`
2. File Chunk Limit : `bp_media_upload_chunk_limit`

**Document**

1. File Size Limit : `bp_document_file_upload_max_size`
2. File Chunk LImit : `bp_document_upload_chunk_limit`

**Comment by AiratHalitov** [comment]
@chetansatasiya 
Thanks!
What about adding these settings into UI of the platform?
**Example:**
![image](https://user-images.githubusercontent.com/4050715/83972526-0ce75900-a8fa-11ea-9883-4bc2b13943ee.png)

**Comment by mehulkaklotar** [comment]
@AiratHalitov That is very a good suggestion. We will do this in future release. Adding this into development queue.

**Comment by eisenwasser** [comment]
@AiratHalitov 

This is partially addressed in today's release:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-4-1/

We set max files per batch at 10, hard-coded.
If you upload more than 10 you will get a notice and it will only upload the first 10 files.

In a future update we will look into adding a backend setting where you can control this. At least for now users cannot upload dozens of files.

**Comment by AiratHalitov** [comment]
New default limits in v1.4.1 are working good. Thanks! 
Looking forward to next UI updates.

**Comment by eisenwasser** [comment]
Great

**Comment by eisenwasser** [comment]
@AiratHalitov 

I am closing this issue, and will let this one take over: https://github.com/buddyboss/buddyboss-platform/issues/1013

As it is more defined in terms of the remaining tasks.

**Comment by sujanpgowda** [comment]
@eisenwasser You had mentioned "In a future update we will look into adding a backend setting where you can control this. At least for now users cannot upload dozens of files."

This doesn't stop the users from uploading multiple batches of dozens of files, even if the batch sir limit is limited to a dozen.

The backend setting, i.e.. media access controls,  needs to be more on the lines of maximum storage quotas based on maximum files and maximum size, allowed per user, based on membership tier.

This is a basic requirement of a membership platform, any feature introduced such a media uploading, needs to have access controls and membership tiers, else it will lead to abuse of the platform and removal of free tier defeating the purpose of membership tiers.

For example, enclsoing sample screens for rtmedia membership quotas, which already works on buddypress platform.

[Rtmedia memberships for buddypress ](https://rtmedia.io/docs/addons/membership/
![143140409-16fff627-f021-42d7-855c-b04fcbef98d7](https://user-images.githubusercontent.com/9027216/144817282-dc6cdcd7-1ce6-4f3f-a35d-48b0bd47c85a.png)
)

**Comment by manualsh** [comment]
@eisenwasser You had mentioned "In a future update we will look into adding a backend setting where you can control this. At least for now users cannot upload dozens of files."

This doesn't stop the users from uploading multiple batches of dozens of files, even if the batch size is limited to a dozen.

The backend setting, i.e. media access controls, needs to be more on the lines of maximum storage quotas based on maximum files and maximum size, allowed per user on daily, monthly, lifetime duration based on membership tier.

This is a basic requirement of a membership platform, any feature introduced such as media uploading, needs to have access controls and membership tiers, else it will lead to abuse of the platform and removal of free tier defeating the purpose of membership tiers.

For example, enclosing sample screens for rtmedia membership quotas, which already works on buddypress platform.

[Rtmedia memberships for buddypress ](https://rtmedia.io/docs/addons/membership/
143140409-16fff627-f021-42d7-855c-b04fcbef98d7
https://github.com/buddyboss/buddyboss-platform/issues/987
https://github.com/buddyboss/buddyboss-platform/issues/3198
