### ISSUE TITLE
Documents - If set privacy to "only me" it is still showing in Followers timeline

### ISSUE THREAD

**Issue by eisenwasser** [buddyboss/buddyboss-platform#993]
**Describe the bug**
When adding a document and marking the privacy setting to visible only to me, there is an update posted to my timeline and my followers can also see this update posted to their timeline.

**To Reproduce**
1. Enabled Following in activity settings
2. Upload a document into timeline and set privacy as Only Me
3. Log into a user who is following the person who uploaded
4. They can see the upload and timeline post

**Expected behavior**
If set to Only Me it should be hidden from Timeline of users following them. Also need to test these same conditions again for My Connections filter.

**Screenshots**

**Support ticket links**
Reported in Youtube by user "Lachlan Lowe"
https://www.youtube.com/watch?v=H_6c0PBGQok&lc=UgyYAhx9MKdy55i4F8J4AaABAg&feature=em-comments

**Comment by AiratHalitov** [comment]
Changing the privacy of a document does not change the privacy of a linked post in activity.

**Comment by KartikSuthar** [comment]
> Changing the privacy of a document does not change the privacy of a linked post in activity.
@AiratHalitov I have checked in our demo and it's working: http://somup.com/cY1j63Q6VW

**Comment by AiratHalitov** [comment]
@KartikSuthar 
It's working good for privacy levels "All Members" and "My Connections". 
But try to set privacy to "Only Me" on /documents/ page and see the result on /activity/ page. It will be set to "Everyone".

**Comment by AiratHalitov** [comment]
UPD: Now for me the privacy changing is working good in every cases.
